import ModularCurves.EllipticCurve.PoleSheaf

/-!
# Sections away from a marked section

This file identifies the overlap of a Cartier-generator chart with the open complement of a
marked section. This is the geometric input for extending regular functions on the complement
to sections with a finite-order pole along the marked section.
-/

open AlgebraicGeometry CategoryTheory Limits Opposite TopologicalSpace

universe u

namespace ModularCurves

/-- The open complement of the image of a marked section of a separated morphism. -/
noncomputable def sectionAway
    {C S : Scheme.{u}} {π : C ⟶ S}
    [IsSeparated π] (z : S ⟶ C) (hz : z ≫ π = 𝟙 S) : C.Opens := by
  letI : IsClosedImmersion z := isClosedImmersion_section z hz
  exact ⟨(Set.range ⇑z)ᶜ, z.isClosedEmbedding.isClosed_range.isOpen_compl⟩

/-- On an affine chart where the ideal of a marked section is generated by `r`, its complement
meets the chart in the basic open defined by `r`. -/
theorem affine_inf_sectionAway_eq_basicOpen
    {C S : Scheme.{u}} {π : C ⟶ S}
    [IsSeparated π]
    (z : S ⟶ C) (hz : z ≫ π = 𝟙 S)
    (U : C.affineOpens) (r : Γ(C, U.1))
    (hspan : z.ker.ideal U = Ideal.span {r}) :
    U.1 ⊓ sectionAway z hz = C.basicOpen r := by
  letI : IsClosedImmersion z := isClosedImmersion_section z hz
  ext x
  change x ∈ (U.1 : Set C) ∩ (Set.range ⇑z)ᶜ ↔ x ∈ C.basicOpen r
  rw [← z.isClosedEmbedding.isClosed_range.closure_eq]
  rw [← z.support_ker]
  simp only [Set.mem_inter_iff, Set.mem_compl_iff]
  constructor
  · rintro ⟨hxU, hx⟩
    by_contra hxr
    apply hx
    apply (z.ker.mem_support_iff_of_mem hxU).2
    rw [hspan, C.zeroLocus_span, C.zeroLocus_singleton]
    exact hxr
  · intro hxr
    have hxU : x ∈ U.1 := C.basicOpen_le r hxr
    refine ⟨hxU, ?_⟩
    intro hx
    have hxzero := (z.ker.mem_support_iff_of_mem hxU).1 hx
    rw [hspan, C.zeroLocus_span, C.zeroLocus_singleton] at hxzero
    exact hxzero hxr

end ModularCurves
