/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import ModularCurves.EllipticCurve.PoleSheafSuccessorCoordinateMul

/-!
# Normalized monomials in pole sections

Normalized pole-order-two and pole-order-three sections determine the sequence
`x, y, x², xy, x³, ...`. Every term has leading Cartier coefficient one in
its pole-order successor quotient.
-/

open AlgebraicGeometry CategoryTheory Limits Opposite TopologicalSpace
open TensorProduct

universe u

namespace ModularCurves

/-- The sequence `x, y, x², xy, x³, ...` of positive-pole monomials. Its
`n`th term lies in the pole module of order `n + 2`. -/
noncomputable def sectionPoleSheafPower_normalizedMonomial
    {C S : Scheme.{u}} {π : C ⟶ S} [IsSeparated π]
    (z : S ⟶ C) (hz : z ≫ π = 𝟙 S)
    (x : Scheme.Modules.baseSections π
      (sectionPoleSheafPower π z hz 2))
    (y : Scheme.Modules.baseSections π
      (sectionPoleSheafPower π z hz 3)) :
    (n : ℕ) → Scheme.Modules.baseSections π
      (sectionPoleSheafPower π z hz (n + 2))
  | 0 => x
  | 1 => y
  | n + 2 =>
      sectionPoleSheafPower_baseSectionsMul z hz (n + 2) 2
        (sectionPoleSheafPower_normalizedMonomial z hz x y n ⊗ₜ x)

@[simp]
theorem sectionPoleSheafPower_normalizedMonomial_zero
    {C S : Scheme.{u}} {π : C ⟶ S} [IsSeparated π]
    (z : S ⟶ C) (hz : z ≫ π = 𝟙 S)
    (x : Scheme.Modules.baseSections π
      (sectionPoleSheafPower π z hz 2))
    (y : Scheme.Modules.baseSections π
      (sectionPoleSheafPower π z hz 3)) :
    sectionPoleSheafPower_normalizedMonomial z hz x y 0 = x :=
  rfl

@[simp]
theorem sectionPoleSheafPower_normalizedMonomial_one
    {C S : Scheme.{u}} {π : C ⟶ S} [IsSeparated π]
    (z : S ⟶ C) (hz : z ≫ π = 𝟙 S)
    (x : Scheme.Modules.baseSections π
      (sectionPoleSheafPower π z hz 2))
    (y : Scheme.Modules.baseSections π
      (sectionPoleSheafPower π z hz 3)) :
    sectionPoleSheafPower_normalizedMonomial z hz x y 1 = y :=
  rfl

@[simp]
theorem sectionPoleSheafPower_normalizedMonomial_add_two
    {C S : Scheme.{u}} {π : C ⟶ S} [IsSeparated π]
    (z : S ⟶ C) (hz : z ≫ π = 𝟙 S)
    (x : Scheme.Modules.baseSections π
      (sectionPoleSheafPower π z hz 2))
    (y : Scheme.Modules.baseSections π
      (sectionPoleSheafPower π z hz 3))
    (n : ℕ) :
    sectionPoleSheafPower_normalizedMonomial z hz x y (n + 2) =
      sectionPoleSheafPower_baseSectionsMul z hz (n + 2) 2
        (sectionPoleSheafPower_normalizedMonomial z hz x y n ⊗ₜ x) :=
  rfl

/-- Every positive-pole monomial generated by normalized `x` and `y` has
leading Cartier coefficient one. -/
theorem sectionPoleSheafPower_normalizedMonomial_coordinate
    {C S : Scheme.{u}} {π : C ⟶ S}
    (hsm : SmoothOfRelativeDimension 1 π) [IsSeparated π]
    (z : S ⟶ C) (hz : z ≫ π = 𝟙 S)
    (U : C.affineOpens) (hU : z ⁻¹ᵁ U.1 = ⊤)
    (r : Γ(C, U.1)) (hspan : z.ker.ideal U = Ideal.span {r})
    (hnzd : r ∈ nonZeroDivisors Γ(C, U.1))
    (x : Scheme.Modules.baseSections π
      (sectionPoleSheafPower π z hz 2))
    (hx : sectionPoleSheafPower_succ_baseSectionsCoordinateOfCartierGenerator
      hsm z hz U hU r hspan hnzd 1 x = 1)
    (y : Scheme.Modules.baseSections π
      (sectionPoleSheafPower π z hz 3))
    (hy : sectionPoleSheafPower_succ_baseSectionsCoordinateOfCartierGenerator
      hsm z hz U hU r hspan hnzd 2 y = 1)
    (n : ℕ) :
    sectionPoleSheafPower_succ_baseSectionsCoordinateOfCartierGenerator
        hsm z hz U hU r hspan hnzd (n + 1)
        (sectionPoleSheafPower_normalizedMonomial z hz x y n) = 1 := by
  induction n using Nat.twoStepInduction with
  | zero => exact hx
  | one => exact hy
  | more n hn _ =>
      rw [sectionPoleSheafPower_normalizedMonomial_add_two]
      rw [sectionPoleSheafPower_succ_baseSectionsCoordinateOfCartierGenerator_mul
        hsm z hz U hU r hspan hnzd (n + 1) 1
          (sectionPoleSheafPower_normalizedMonomial z hz x y n) x,
        hn, hx, one_mul]

end ModularCurves
