import ModularCurves.EllipticCurve.PoleFiltration
import ModularCurves.EllipticCurve.PoleSheaf

/-!
# Pole sheaves on a projective Weierstrass model

This file identifies the zero-section ideal on the two standard charts of
`projModel W`. On the `Y`-chart it is the augmentation ideal `(s, t)`, while on the
affine `Z`-chart it is the unit ideal. After restricting the `Y`-chart to the basic open
where the section unit is invertible, the ideal is generated by the nonzerodivisor `s`.
These are the chart trivializations used to compare `O(n[0])` with
`poleOrderFiltration W n`.
-/

open AlgebraicGeometry CategoryTheory Limits WeierstrassCurve HomogeneousIdeal

attribute [local instance] MvPolynomial.gradedAlgebra

universe u

namespace ModularCurves

variable {R : Type u} [CommRing R]

/-- The standard `Y`-chart of the projective Weierstrass model, as an affine open. -/
noncomputable abbrev projModelYChart (W : WeierstrassCurve R) :
    (projModel W).affineOpens :=
  ⟨Proj.basicOpen (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1)),
    Proj.isAffineOpen_basicOpen (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1))
      (mk_X_mem_quotientGrading_one W 1) one_pos⟩

/-- The standard affine `Z`-chart of the projective Weierstrass model. -/
noncomputable abbrev projModelZChart (W : WeierstrassCurve R) :
    (projModel W).affineOpens :=
  ⟨Proj.basicOpen (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 2)),
    Proj.isAffineOpen_basicOpen (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 2))
      (mk_X_mem_quotientGrading_one W 2) one_pos⟩

/-- On the `Y`-chart, the zero-section ideal is the augmentation ideal `(s, t)`. -/
theorem projModelZero_ker_ideal_chartY (W : WeierstrassCurve R) :
    (projModelZero W).ker.ideal (projModelYChart W) =
      Ideal.span {(chartYSectionsRingEquiv W).symm
          (AdjoinRoot.root (infChartCubic W)),
        (chartYSectionsRingEquiv W).symm (infChartTElem W)} := by
  rw [Scheme.Hom.ker_apply]
  let e := chartYSectionsRingEquiv W
  let htop : projModelZero W ⁻¹ᵁ (projModelYChart W : (projModel W).Opens) = ⊤ :=
    projModelZero_preimage_yChart W
  let hUV : (⊤ : (Spec (CommRingCat.of R)).Opens) ≤
      projModelZero W ⁻¹ᵁ (projModelYChart W : (projModel W).Opens) :=
    le_of_eq htop.symm
  have hkerApp : RingHom.ker ((projModelZero W).app (projModelYChart W)).hom =
      RingHom.ker ((projModelZero W).appLE (projModelYChart W) ⊤ hUV).hom := by
    haveI : IsIso (homOfLE hUV) :=
      ⟨homOfLE (le_of_eq htop), Subsingleton.elim _ _, Subsingleton.elim _ _⟩
    have hinj : Function.Injective
        ((Spec (CommRingCat.of R)).presheaf.map (homOfLE hUV).op).hom :=
      (ConcreteCategory.bijective_of_isIso
        ((Spec (CommRingCat.of R)).presheaf.map (homOfLE hUV).op)).1
    ext a
    rw [RingHom.mem_ker, RingHom.mem_ker]
    change ((projModelZero W).app (projModelYChart W)).hom a = 0 ↔
      ((Spec (CommRingCat.of R)).presheaf.map (homOfLE hUV).op).hom
        (((projModelZero W).app (projModelYChart W)).hom a) = 0
    constructor
    · intro ha
      rw [ha, map_zero]
    · intro ha
      apply hinj
      rw [ha, map_zero]
  rw [hkerApp]
  have hker : RingHom.ker ((projModelZero W).appLE
      (projModelYChart W) ⊤ hUV).hom =
      Ideal.comap e.toRingHom (RingHom.ker (infChartAug W)) := by
    ext a
    rw [RingHom.mem_ker, Ideal.mem_comap, RingHom.mem_ker]
    have hformula : (((projModelZero W).appLE
        (projModelYChart W) ⊤ hUV).hom a) =
        ((Scheme.ΓSpecIso (CommRingCat.of R)).inv).hom
          (infChartAug W (e a)) := by
      rw [show hUV = le_of_eq (projModelZero_preimage_yChart W).symm from
        Subsingleton.elim _ _]
      simpa only [e, RingEquiv.symm_apply_apply] using
        projModelZero_appLE_chartYSection W (e a)
    constructor
    · intro ha
      apply (ConcreteCategory.bijective_of_isIso
        (Scheme.ΓSpecIso (CommRingCat.of R)).inv).1
      calc
        ((Scheme.ΓSpecIso (CommRingCat.of R)).inv).hom
            (infChartAug W (e a)) =
          ((projModelZero W).appLE (projModelYChart W) ⊤ hUV).hom a :=
            hformula.symm
        _ = 0 := ha
        _ = ((Scheme.ΓSpecIso (CommRingCat.of R)).inv).hom 0 := (map_zero _).symm
    · intro ha
      calc
        ((projModelZero W).appLE (projModelYChart W) ⊤ hUV).hom a =
          ((Scheme.ΓSpecIso (CommRingCat.of R)).inv).hom
            (infChartAug W (e a)) := hformula
        _ = ((Scheme.ΓSpecIso (CommRingCat.of R)).inv).hom 0 := congrArg _ ha
        _ = 0 := map_zero _
  rw [hker, ker_infChartAug W]
  change Ideal.comap (chartYSectionsRingEquiv W) _ = _
  rw [show Ideal.comap (chartYSectionsRingEquiv W)
      (Ideal.span {AdjoinRoot.root (infChartCubic W), infChartTElem W}) =
    Ideal.map (chartYSectionsRingEquiv W).symm
      (Ideal.span {AdjoinRoot.root (infChartCubic W), infChartTElem W}) by
        exact Ideal.comap_symm (f := (chartYSectionsRingEquiv W).symm)
          (I := Ideal.span {AdjoinRoot.root (infChartCubic W), infChartTElem W})]
  rw [Ideal.map_span, Set.image_insert_eq, Set.image_singleton]

/-- The zero section misses the `Z`-chart, so its ideal there is generated by `1`. -/
theorem projModelZero_ker_ideal_chartZ (W : WeierstrassCurve R) :
    (projModelZero W).ker.ideal (projModelZChart W) = Ideal.span {1} := by
  rw [Scheme.Hom.ker_apply]
  have hker : RingHom.ker ((projModelZero W).app (projModelZChart W)).hom = ⊤ := by
    ext a
    constructor
    · intro _
      trivial
    · intro _
      rw [RingHom.mem_ker]
      have hpre := projModelZero_not_preimage_zChart W
      haveI : Subsingleton Γ(Spec (CommRingCat.of R),
          projModelZero W ⁻¹ᵁ (projModelZChart W : (projModel W).Opens)) := by
        rw [hpre]
        infer_instance
      exact Subsingleton.elim _ _
  rw [hker, Ideal.span_singleton_one]

/-- The section unit, viewed as a section of the `Y`-chart. -/
noncomputable def projModelSectionUnitSection (W : WeierstrassCurve R) :
    Γ(projModel W, projModelYChart W) :=
  (chartYSectionsRingEquiv W).symm (sectionUnitElem W)

/-- The canonical affine neighborhood of the zero section where the section unit is
invertible. -/
noncomputable abbrev projModelSectionNeighborhood (W : WeierstrassCurve R) :
    (projModel W).affineOpens :=
  (projModel W).affineBasicOpen (projModelSectionUnitSection W)

/-- The root coordinate `s`, restricted to the canonical section neighborhood. -/
noncomputable def projModelSectionRoot (W : WeierstrassCurve R) :
    Γ(projModel W, projModelSectionNeighborhood W) :=
  (projModel W).presheaf.map
    (homOfLE ((projModel W).affineBasicOpen_le
      (projModelSectionUnitSection W))).op
    ((chartYSectionsRingEquiv W).symm
      (AdjoinRoot.root (infChartCubic W)))

/-- On the canonical section neighborhood, the zero-section ideal is generated by `s`. -/
theorem projModelZero_ker_ideal_sectionNeighborhood (W : WeierstrassCurve R) :
    (projModelZero W).ker.ideal (projModelSectionNeighborhood W) =
      Ideal.span {projModelSectionRoot W} := by
  let X := projModel W
  let U := projModelYChart W
  let u := projModelSectionUnitSection W
  let V := projModelSectionNeighborhood W
  let s : Γ(X, U) := (chartYSectionsRingEquiv W).symm
    (AdjoinRoot.root (infChartCubic W))
  let t : Γ(X, U) := (chartYSectionsRingEquiv W).symm (infChartTElem W)
  let res : Γ(X, U) ⟶ Γ(X, V) :=
    X.presheaf.map (homOfLE (X.affineBasicOpen_le u)).op
  have hmap := (projModelZero W).ker.map_ideal (X.affineBasicOpen_le u)
  change Ideal.map res.hom ((projModelZero W).ker.ideal U) =
      (projModelZero W).ker.ideal V at hmap
  rw [← hmap]
  rw [show (projModelZero W).ker.ideal U = Ideal.span {s, t} from
    projModelZero_ker_ideal_chartY W]
  rw [Ideal.map_span, Set.image_insert_eq, Set.image_singleton]
  apply le_antisymm
  · refine Ideal.span_le.mpr ?_
    rintro a (rfl | rfl)
    · exact Ideal.mem_span_singleton_self _
    · let ψ : AdjoinRoot (infChartCubic W) →+* Γ(X, V) :=
        res.hom.comp (chartYSectionsRingEquiv W).symm.toRingHom
      have hu : IsUnit (ψ (sectionUnitElem W)) := by
        change IsUnit (res.hom u)
        exact AlgebraicGeometry.RingedSpace.isUnit_res_basicOpen X.toRingedSpace u
      change ψ (infChartTElem W) ∈
        Ideal.span {ψ (AdjoinRoot.root (infChartCubic W))}
      exact tel_image_mem_span_of_isUnit ψ hu
  · exact Ideal.span_mono (Set.singleton_subset_iff.mpr (Set.mem_insert _ _))

/-- The generator `s` remains a nonzerodivisor on the canonical section neighborhood. -/
theorem projModelSectionRoot_mem_nonZeroDivisors (W : WeierstrassCurve R) :
    projModelSectionRoot W ∈
      nonZeroDivisors Γ(projModel W, projModelSectionNeighborhood W) := by
  let X := projModel W
  let U := projModelYChart W
  let u := projModelSectionUnitSection W
  let s : Γ(X, U) := (chartYSectionsRingEquiv W).symm
    (AdjoinRoot.root (infChartCubic W))
  change (X.presheaf.map (homOfLE (X.affineBasicOpen_le u)).op).hom s ∈
    nonZeroDivisors Γ(X, X.affineBasicOpen u)
  let res : Γ(X, U) ⟶ Γ(X, X.affineBasicOpen u) :=
    X.presheaf.map (homOfLE (X.affineBasicOpen_le u)).op
  letI : Algebra Γ(X, U) Γ(X, X.affineBasicOpen u) := res.hom.toAlgebra
  haveI : IsLocalization.Away u Γ(X, X.affineBasicOpen u) :=
    U.2.isLocalization_basicOpen u
  exact IsLocalization.map_nonZeroDivisors_le (Submonoid.powers u)
    Γ(X, X.affineBasicOpen u) ⟨s,
      RingEquiv_map_mem_nonZeroDivisors (chartYSectionsRingEquiv W).symm
        (infChart_root_mem_nonZeroDivisors W), rfl⟩

/-- The explicit ideal-sheaf trivialization on the canonical neighborhood of the zero
section. -/
noncomputable def projModelZeroIdealTrivialization (W : WeierstrassCurve R) :
    Scheme.Modules.unitObj (projModelSectionNeighborhood W).1.toScheme ≅
      (idealModule (projModelZero W)).restrict
        (projModelSectionNeighborhood W).1.ι := by
  let r := projModelSectionRoot W
  have hspan := projModelZero_ker_ideal_sectionNeighborhood W
  have hr : r ∈ (projModelZero W).ker.ideal (projModelSectionNeighborhood W) := by
    rw [hspan]
    exact Ideal.mem_span_singleton_self r
  exact localIdealGeneratorIso (projModelZero W) (projModelSectionNeighborhood W)
    r hr hspan (projModelSectionRoot_mem_nonZeroDivisors W)

/-- The ideal-sheaf trivialization on the affine `Z`-chart, where the generator is `1`. -/
noncomputable def projModelZeroIdealTrivializationZ (W : WeierstrassCurve R) :
    Scheme.Modules.unitObj (projModelZChart W).1.toScheme ≅
      (idealModule (projModelZero W)).restrict (projModelZChart W).1.ι := by
  have hspan := projModelZero_ker_ideal_chartZ W
  have hr : (1 : Γ(projModel W, projModelZChart W)) ∈
      (projModelZero W).ker.ideal (projModelZChart W) := by
    rw [hspan]
    exact Ideal.mem_span_singleton_self 1
  exact localIdealGeneratorIso (projModelZero W) (projModelZChart W)
    1 hr hspan (by exact one_mem (nonZeroDivisors _))

end ModularCurves
