/-
Copyright (c) 2026 The AINTLIB Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AINTLIB Authors
-/
import ModularCurves.EllipticCurve.AdditionChartZeroIdeal
import ModularCurves.EllipticCurve.PoleSheafModel
import ModularCurves.EllipticCurve.WeierstrassModelCoordinateTransition
import ModularCurves.ForMathlib.SchemeAppLE

/-!
# Pulling back the zero ideal through a Weierstrass chart

This file identifies the comorphism of a unit-`Y` projective coordinate map on the standard
`Y`-chart. For a normalized pole-coordinate triple, the model zero ideal then pulls back to
the principal ideal generated by the local equation of the marked section.
-/

open AlgebraicGeometry CategoryTheory TopologicalSpace
open WeierstrassCurve.Projective HomogeneousIdeal

attribute [local instance] MvPolynomial.gradedAlgebra

namespace ModularCurves

universe u

variable {R : Type u} [CommRing R]

private theorem ideal_comap_affineOpens_eq_map
    {X Y : Scheme.{u}} (I : Y.IdealSheafData) (f : X ⟶ Y)
    (U : X.affineOpens) (V : Y.affineOpens)
    (hUV : U.1 ≤ f ⁻¹ᵁ V.1) :
    (I.comap f).ideal U =
      (I.ideal V).map (f.appLE V.1 U.1 hUV).hom := by
  rw [ideal_comap_affineOpens_nested I f U V hUV]
  rw [← Scheme.IdealSheafData.map_ideal I
    (U := V)
    (V := ⟨V.1.ι ''ᵁ ⊤,
      (isAffineOpen_top _).image_of_isOpenImmersion _⟩)
    V.1.ι_image_top.ge]
  simp only [Ideal.map_map]
  congr 1
  apply RingHom.ext
  intro a
  simp only [RingHom.coe_comp, Function.comp_apply,
    Scheme.Opens.ι_appIso]
  change
    (X.presheaf.map (homOfLE U.1.ι_image_top.ge).op).hom
        ((f.resLE V.1 U.1 hUV).appTop.hom a) =
      (f.appLE V.1 U.1 hUV).hom
        ((Y.presheaf.map (homOfLE V.1.ι_image_top.ge).op).hom a)
  have hUmap :
      X.presheaf.map (homOfLE U.1.ι_image_top.ge).op =
        U.1.topIso.hom := by
    apply X.presheaf.congr_map
    exact Subsingleton.elim _ _
  have hUcancel :
      U.1.topIso.inv ≫
        X.presheaf.map (homOfLE U.1.ι_image_top.ge).op = 𝟙 _ := by
    exact hUmap ▸ U.1.topIso.inv_hom_id
  have hVmap :
      Y.presheaf.map (homOfLE V.1.ι_image_top.ge).op =
        V.1.topIso.hom := by
    apply Y.presheaf.congr_map
    exact Subsingleton.elim _ _
  have hres := Scheme.Hom.resLE_app_top
    (f := f) (U := V.1) (V := U.1) hUV
  have hresApply := ConcreteCategory.congr_hom hres a
  change (f.resLE V.1 U.1 hUV).appTop.hom a =
    U.1.topIso.inv.hom
      ((f.appLE V.1 U.1 hUV).hom
        (V.1.topIso.hom.hom a)) at hresApply
  have hresOuter := congrArg
    (X.presheaf.map (homOfLE U.1.ι_image_top.ge).op).hom hresApply
  have hUcancelApply := ConcreteCategory.congr_hom hUcancel
    ((f.appLE V.1 U.1 hUV).hom (V.1.topIso.hom.hom a))
  change
    (X.presheaf.map (homOfLE U.1.ι_image_top.ge).op).hom
        (U.1.topIso.inv.hom
          ((f.appLE V.1 U.1 hUV).hom
            (V.1.topIso.hom.hom a))) =
      (f.appLE V.1 U.1 hUV).hom
        (V.1.topIso.hom.hom a) at hUcancelApply
  have hVapply := ConcreteCategory.congr_hom hVmap a
  exact hresOuter.trans (hUcancelApply.trans
    (congrArg (f.appLE V.1 U.1 hUV).hom hVapply.symm))

/-- A unit-`Y` projective coordinate map pulls a standard `Y`-chart section back by
`chartAwayHomOfTriple`. -/
theorem projModelFromOfGlobalSections_appLE_chartYSection
    {X : Scheme.{u}} (W : WeierstrassCurve R)
    [Algebra R Γ(X, (⊤ : X.Opens))]
    (P : Fin 3 → Γ(X, (⊤ : X.Opens)))
    (hP : (W.map (algebraMap R Γ(X, (⊤ : X.Opens)))).toProjective.Equation P)
    (hi : IsUnit (P 1)) (b : AdjoinRoot (infChartCubic W)) :
    (projModelFromOfGlobalSections W
        (algebraMap R Γ(X, (⊤ : X.Opens))) P hP 1 hi).appLE
          (projModelYChart W)
          ⊤
          (by
            rw [projModelFromOfGlobalSections_preimage_basicOpen]
            rw [Scheme.basicOpen_of_isUnit X hi])
          ((chartYSectionsRingEquiv W).symm b) =
      chartAwayHomOfTriple W 1 P
        (↑hi.unit⁻¹) hi.mul_val_inv hP
          ((chartYRingEquiv W).symm b) := by
  let U : (projModel W).Opens := projModelYChart W
  let hU : IsAffineOpen U := (projModelYChart W).2
  let F : X ⟶ projModel W :=
    projModelFromOfGlobalSections W
      (algebraMap R Γ(X, (⊤ : X.Opens))) P hP 1 hi
  let e : CommRingCat.of (chartAway W 1) ≅ Γ(projModel W, U) :=
    Proj.basicOpenIsoAway (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1))
      (mk_X_mem_quotientGrading_one W 1) one_pos
  let φ : chartAway W 1 →+* Γ(X, (⊤ : X.Opens)) :=
    (chartAwayHomOfTriple W 1 P
      (↑hi.unit⁻¹) hi.mul_val_inv hP).toRingHom
  let ψ : Γ(projModel W, U) ⟶ Γ(X, (⊤ : X.Opens)) :=
    e.inv ≫ CommRingCat.ofHom φ
  let G : X ⟶ Spec Γ(projModel W, U) :=
    X.toSpecΓ ≫ Spec.map ψ
  have hpre : (⊤ : X.Opens) ≤ F ⁻¹ᵁ U := by
    dsimp only [F, U]
    rw [projModelFromOfGlobalSections_preimage_basicOpen]
    rw [Scheme.basicOpen_of_isUnit X hi]
  have hfromSpec :
      hU.fromSpec =
        Spec.map e.hom ≫ chartι W 1 := by
    dsimp only [hU, U, e]
    exact Proj_fromSpec_awayToSection_awayι
      (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1))
      (mk_X_mem_quotientGrading_one W 1) one_pos
  have hspec :
      Spec.map ψ ≫ Spec.map e.hom =
        Spec.map (CommRingCat.ofHom φ) := by
    rw [← Spec.map_comp]
    apply congrArg Spec.map
    exact e.hom_inv_id_assoc (CommRingCat.ofHom φ)
  have hfactor :
      F = G ≫ hU.fromSpec := by
    calc
      F = X.toSpecΓ ≫
          Spec.map (CommRingCat.ofHom φ) ≫ chartι W 1 := by
        dsimp only [F, φ]
        exact projModelFromOfGlobalSections_eq_chart W P hP 1 hi
      _ = G ≫ hU.fromSpec := by
        rw [hfromSpec]
        dsimp only [G]
        rw [← hspec]
        simp only [Category.assoc]
  have hmap :
      F.appLE U ⊤ hpre = ψ := by
    rw [appLE_congr_hom hfactor U ⊤]
    rw [← Scheme.Hom.appLE_comp_appLE
      G hU.fromSpec U ⊤ ⊤
      (le_of_eq hU.fromSpec_preimage_self.symm) le_top]
    rw [show G.appLE ⊤ ⊤ le_top =
        (Spec.map ψ).appLE ⊤ ⊤ le_top ≫
          X.toSpecΓ.appLE ⊤ ⊤ le_top by
      dsimp only [G]
      exact (Scheme.Hom.appLE_comp_appLE
        X.toSpecΓ (Spec.map ψ) ⊤ ⊤ ⊤ le_top le_top).symm]
    rw [appLE_top_top, appLE_top_top, Scheme.toSpecΓ_appTop]
    rw [Scheme.ΓSpecIso_naturality]
    rw [← Category.assoc, IsAffineOpen.fromSpec_appLE_comp_ΓSpecIso,
      Category.id_comp]
  change (F.appLE U ⊤ hpre).hom
      ((chartYSectionsRingEquiv W).symm b) =
    φ ((chartYRingEquiv W).symm b)
  rw [hmap]
  change φ (e.inv.hom ((chartYSectionsRingEquiv W).symm b)) =
    φ ((chartYRingEquiv W).symm b)
  congr 1
  have hform :
      (chartYSectionsRingEquiv W).symm b =
        e.hom.hom ((chartYRingEquiv W).symm b) := by
    rfl
  rw [hform]
  have hcancel := congrArg
    (fun q => CommRingCat.Hom.hom q ((chartYRingEquiv W).symm b))
    e.hom_inv_id
  simpa only [CommRingCat.hom_comp, RingHom.comp_apply,
    CommRingCat.hom_id, RingHom.id_apply] using hcancel

/-- For normalized coordinates on the `Y`-chart, the pullback of the model zero ideal is
generated by the local equation `r`. -/
theorem projModelFromOfGlobalSections_map_zeroIdeal_chartY
    {X : Scheme.{u}} (W : WeierstrassCurve R)
    [Algebra R Γ(X, (⊤ : X.Opens))]
    (P : Fin 3 → Γ(X, (⊤ : X.Opens)))
    (hP : (W.map (algebraMap R Γ(X, (⊤ : X.Opens)))).toProjective.Equation P)
    (hi : IsUnit (P 1))
    (r x : Γ(X, (⊤ : X.Opens)))
    (hP0 : P 0 = x * r) (hP2 : P 2 = r ^ 3)
    (hx : IsUnit x) :
    Ideal.map
        ((projModelFromOfGlobalSections W
          (algebraMap R Γ(X, (⊤ : X.Opens))) P hP 1 hi).appLE
            (projModelYChart W)
            ⊤
            (by
              rw [projModelFromOfGlobalSections_preimage_basicOpen]
              rw [Scheme.basicOpen_of_isUnit X hi])).hom
        ((projModelZero W).ker.ideal (projModelYChart W)) =
      Ideal.span {r} := by
  rw [projModelZero_ker_ideal_chartY]
  rw [Ideal.map_span, Set.image_insert_eq, Set.image_singleton]
  change Ideal.span {
      ((projModelFromOfGlobalSections W
        (algebraMap R Γ(X, (⊤ : X.Opens))) P hP 1 hi).appLE
          (projModelYChart W) ⊤ _)
        ((chartYSectionsRingEquiv W).symm
          (AdjoinRoot.root (infChartCubic W))),
      ((projModelFromOfGlobalSections W
        (algebraMap R Γ(X, (⊤ : X.Opens))) P hP 1 hi).appLE
          (projModelYChart W) ⊤ _)
        ((chartYSectionsRingEquiv W).symm (infChartTElem W))} =
    Ideal.span {r}
  rw [projModelFromOfGlobalSections_appLE_chartYSection,
    projModelFromOfGlobalSections_appLE_chartYSection]
  change Ideal.span {
      (chartAwayHomOfTriple W 1 P
        (↑hi.unit⁻¹) hi.mul_val_inv hP).toRingHom
          ((chartYRingEquiv W).symm
            (AdjoinRoot.root (infChartCubic W))),
      (chartAwayHomOfTriple W 1 P
        (↑hi.unit⁻¹) hi.mul_val_inv hP).toRingHom
          ((chartYRingEquiv W).symm (infChartTElem W))} =
    Ideal.span {r}
  simpa only [Ideal.map_span, Set.image_insert_eq,
    Set.image_singleton] using
      chartAwayHomOfTriple_map_chartYZeroIdeal W P
        (↑hi.unit⁻¹) hi.mul_val_inv hP r x hP0 hP2 hx

/-- For normalized coordinates on an affine source, the scheme-theoretic inverse image
of the model zero ideal is generated by the local equation `r`. -/
theorem projModelFromOfGlobalSections_comap_zeroIdeal_chartY
    {X : Scheme.{u}} [IsAffine X] (W : WeierstrassCurve R)
    [Algebra R Γ(X, (⊤ : X.Opens))]
    (P : Fin 3 → Γ(X, (⊤ : X.Opens)))
    (hP : (W.map
      (algebraMap R Γ(X, (⊤ : X.Opens)))).toProjective.Equation P)
    (hi : IsUnit (P 1))
    (r x : Γ(X, (⊤ : X.Opens)))
    (hP0 : P 0 = x * r) (hP2 : P 2 = r ^ 3)
    (hx : IsUnit x) :
    ((projModelZero W).ker.comap
      (projModelFromOfGlobalSections W
        (algebraMap R Γ(X, (⊤ : X.Opens))) P hP 1 hi)).ideal
          ⟨⊤, isAffineOpen_top X⟩ = Ideal.span {r} := by
  let F := projModelFromOfGlobalSections W
    (algebraMap R Γ(X, (⊤ : X.Opens))) P hP 1 hi
  have hpre : (⊤ : X.Opens) ≤
      F ⁻¹ᵁ (projModelYChart W : (projModel W).Opens) := by
    dsimp only [F]
    rw [projModelFromOfGlobalSections_preimage_basicOpen]
    rw [Scheme.basicOpen_of_isUnit X hi]
  rw [ideal_comap_affineOpens_eq_map (projModelZero W).ker F
    ⟨⊤, isAffineOpen_top X⟩ (projModelYChart W) hpre]
  exact projModelFromOfGlobalSections_map_zeroIdeal_chartY
    W P hP hi r x hP0 hP2 hx

end ModularCurves
