import ModularCurves.EllipticCurve.PoleFiltration
import ModularCurves.EllipticCurve.PoleSheaf

/-!
# Pole sheaves on a projective Weierstrass model

This file identifies the zero-section ideal on the two standard charts of
`projModel W`. On the `Y`-chart it is the augmentation ideal `(s, t)`, while on the
affine `Z`-chart it is the unit ideal. After restricting the `Y`-chart to the basic open
where the section unit is invertible, the ideal is generated by the nonzerodivisor `s`.
These are the chart trivializations used to compare `O(n[0])` with
`poleOrderFiltration W n`.
-/

open AlgebraicGeometry CategoryTheory Limits WeierstrassCurve HomogeneousIdeal

attribute [local instance] MvPolynomial.gradedAlgebra

universe u

namespace ModularCurves

variable {R : Type u} [CommRing R]

/-- The standard `Y`-chart of the projective Weierstrass model, as an affine open. -/
noncomputable abbrev projModelYChart (W : WeierstrassCurve R) :
    (projModel W).affineOpens :=
  ⟨Proj.basicOpen (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1)),
    Proj.isAffineOpen_basicOpen (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1))
      (mk_X_mem_quotientGrading_one W 1) one_pos⟩

/-- The standard affine `Z`-chart of the projective Weierstrass model. -/
noncomputable abbrev projModelZChart (W : WeierstrassCurve R) :
    (projModel W).affineOpens :=
  ⟨Proj.basicOpen (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 2)),
    Proj.isAffineOpen_basicOpen (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 2))
      (mk_X_mem_quotientGrading_one W 2) one_pos⟩

/-- On the `Y`-chart, the zero-section ideal is the augmentation ideal `(s, t)`. -/
theorem projModelZero_ker_ideal_chartY (W : WeierstrassCurve R) :
    (projModelZero W).ker.ideal (projModelYChart W) =
      Ideal.span {(chartYSectionsRingEquiv W).symm
          (AdjoinRoot.root (infChartCubic W)),
        (chartYSectionsRingEquiv W).symm (infChartTElem W)} := by
  rw [Scheme.Hom.ker_apply]
  let e := chartYSectionsRingEquiv W
  let htop : projModelZero W ⁻¹ᵁ (projModelYChart W : (projModel W).Opens) = ⊤ :=
    projModelZero_preimage_yChart W
  let hUV : (⊤ : (Spec (CommRingCat.of R)).Opens) ≤
      projModelZero W ⁻¹ᵁ (projModelYChart W : (projModel W).Opens) :=
    le_of_eq htop.symm
  have hkerApp : RingHom.ker ((projModelZero W).app (projModelYChart W)).hom =
      RingHom.ker ((projModelZero W).appLE (projModelYChart W) ⊤ hUV).hom := by
    haveI : IsIso (homOfLE hUV) :=
      ⟨homOfLE (le_of_eq htop), Subsingleton.elim _ _, Subsingleton.elim _ _⟩
    have hinj : Function.Injective
        ((Spec (CommRingCat.of R)).presheaf.map (homOfLE hUV).op).hom :=
      (ConcreteCategory.bijective_of_isIso
        ((Spec (CommRingCat.of R)).presheaf.map (homOfLE hUV).op)).1
    ext a
    rw [RingHom.mem_ker, RingHom.mem_ker]
    change ((projModelZero W).app (projModelYChart W)).hom a = 0 ↔
      ((Spec (CommRingCat.of R)).presheaf.map (homOfLE hUV).op).hom
        (((projModelZero W).app (projModelYChart W)).hom a) = 0
    constructor
    · intro ha
      rw [ha, map_zero]
    · intro ha
      apply hinj
      rw [ha, map_zero]
  rw [hkerApp]
  have hker : RingHom.ker ((projModelZero W).appLE
      (projModelYChart W) ⊤ hUV).hom =
      Ideal.comap e.toRingHom (RingHom.ker (infChartAug W)) := by
    ext a
    rw [RingHom.mem_ker, Ideal.mem_comap, RingHom.mem_ker]
    have hformula : (((projModelZero W).appLE
        (projModelYChart W) ⊤ hUV).hom a) =
        ((Scheme.ΓSpecIso (CommRingCat.of R)).inv).hom
          (infChartAug W (e a)) := by
      rw [show hUV = le_of_eq (projModelZero_preimage_yChart W).symm from
        Subsingleton.elim _ _]
      simpa only [e, RingEquiv.symm_apply_apply] using
        projModelZero_appLE_chartYSection W (e a)
    constructor
    · intro ha
      apply (ConcreteCategory.bijective_of_isIso
        (Scheme.ΓSpecIso (CommRingCat.of R)).inv).1
      calc
        ((Scheme.ΓSpecIso (CommRingCat.of R)).inv).hom
            (infChartAug W (e a)) =
          ((projModelZero W).appLE (projModelYChart W) ⊤ hUV).hom a :=
            hformula.symm
        _ = 0 := ha
        _ = ((Scheme.ΓSpecIso (CommRingCat.of R)).inv).hom 0 := (map_zero _).symm
    · intro ha
      calc
        ((projModelZero W).appLE (projModelYChart W) ⊤ hUV).hom a =
          ((Scheme.ΓSpecIso (CommRingCat.of R)).inv).hom
            (infChartAug W (e a)) := hformula
        _ = ((Scheme.ΓSpecIso (CommRingCat.of R)).inv).hom 0 := congrArg _ ha
        _ = 0 := map_zero _
  rw [hker, ker_infChartAug W]
  change Ideal.comap (chartYSectionsRingEquiv W) _ = _
  rw [show Ideal.comap (chartYSectionsRingEquiv W)
      (Ideal.span {AdjoinRoot.root (infChartCubic W), infChartTElem W}) =
    Ideal.map (chartYSectionsRingEquiv W).symm
      (Ideal.span {AdjoinRoot.root (infChartCubic W), infChartTElem W}) by
        exact Ideal.comap_symm (f := (chartYSectionsRingEquiv W).symm)
          (I := Ideal.span {AdjoinRoot.root (infChartCubic W), infChartTElem W})]
  rw [Ideal.map_span, Set.image_insert_eq, Set.image_singleton]

/-- The zero section misses the `Z`-chart, so its ideal there is generated by `1`. -/
theorem projModelZero_ker_ideal_chartZ (W : WeierstrassCurve R) :
    (projModelZero W).ker.ideal (projModelZChart W) = Ideal.span {1} := by
  rw [Scheme.Hom.ker_apply]
  have hker : RingHom.ker ((projModelZero W).app (projModelZChart W)).hom = ⊤ := by
    ext a
    constructor
    · intro _
      trivial
    · intro _
      rw [RingHom.mem_ker]
      have hpre := projModelZero_not_preimage_zChart W
      haveI : Subsingleton Γ(Spec (CommRingCat.of R),
          projModelZero W ⁻¹ᵁ (projModelZChart W : (projModel W).Opens)) := by
        rw [hpre]
        infer_instance
      exact Subsingleton.elim _ _
  rw [hker, Ideal.span_singleton_one]

/-- The section unit, viewed as a section of the `Y`-chart. -/
noncomputable def projModelSectionUnitSection (W : WeierstrassCurve R) :
    Γ(projModel W, projModelYChart W) :=
  (chartYSectionsRingEquiv W).symm (sectionUnitElem W)

/-- The canonical affine neighborhood of the zero section where the section unit is
invertible. -/
noncomputable abbrev projModelSectionNeighborhood (W : WeierstrassCurve R) :
    (projModel W).affineOpens :=
  (projModel W).affineBasicOpen (projModelSectionUnitSection W)

/-- Under the standard `Y`-chart identification, the localized `X₂` coordinate
is the section corresponding to `t`. -/
lemma awayToSection_X2_eq_infChartTElemSection (W : WeierstrassCurve R) :
    (Proj.awayToSection (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1))).hom
        (HomogeneousLocalization.Away.isLocalizationElem
          (mk_X_mem_quotientGrading_one W 1) (mk_X_mem_quotientGrading_one W 2)) =
      (chartYSectionsRingEquiv W).symm (infChartTElem W) := by
  have hsymm : (chartYRingEquiv W).symm (infChartTElem W) =
      HomogeneousLocalization.Away.isLocalizationElem
        (mk_X_mem_quotientGrading_one W 1)
        (mk_X_mem_quotientGrading_one W 2) :=
    (RingEquiv.symm_apply_eq _).mpr
      (chartYRingEquiv_isLocalizationElem W).symm
  have hval : (chartYSectionsRingEquiv W).symm (infChartTElem W) =
      ((Proj.basicOpenIsoAway (quotientGrading (projIdeal W))
        ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1))
        (mk_X_mem_quotientGrading_one W 1) one_pos).hom).hom
          (HomogeneousLocalization.Away.isLocalizationElem
            (mk_X_mem_quotientGrading_one W 1)
            (mk_X_mem_quotientGrading_one W 2)) := by
    show ((chartYRingEquiv W).symm.trans
      (Proj.basicOpenIsoAway (quotientGrading (projIdeal W))
        ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1))
        (mk_X_mem_quotientGrading_one W 1)
        one_pos).commRingCatIsoToRingEquiv) (infChartTElem W) = _
    rw [RingEquiv.trans_apply, hsymm]
    rfl
  exact hval.symm

/-- A point of the `Y`-chart lies in the `Z`-chart exactly when its chart prime
avoids the coordinate `t`. -/
lemma mem_projModelZChart_iff_not_mem_infChartTElem (W : WeierstrassCurve R)
    (x : projModel W) (hx : x ∈ (projModelYChart W : (projModel W).Opens)) :
    x ∈ (projModelZChart W : (projModel W).Opens) ↔
      (chartYSectionsRingEquiv W).symm (infChartTElem W) ∉
        ((projModelYChart W).2.primeIdealOf ⟨x, hx⟩).asIdeal := by
  let q := (projModelYChart W).2.primeIdealOf ⟨x, hx⟩
  have hxq : (projModelYChart W).2.fromSpec.base q = x := by
    simpa only [q] using
      (projModelYChart W).2.fromSpec_primeIdealOf ⟨x, hx⟩
  change x ∈ (projModelZChart W : (projModel W).Opens) ↔
    (chartYSectionsRingEquiv W).symm (infChartTElem W) ∉ q.asIdeal
  rw [← hxq, Proj_fromSpec_awayToSection_awayι]
  change (Proj.awayι (quotientGrading (projIdeal W))
      ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1))
      (mk_X_mem_quotientGrading_one W 1) one_pos).base
        ((Spec.map (Proj.awayToSection (quotientGrading (projIdeal W))
          ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1)))).base q) ∈
      Proj.basicOpen (quotientGrading (projIdeal W))
        ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 2)) ↔ _
  rw [← Scheme.Hom.mem_preimage,
    Proj.awayι_preimage_basicOpen (quotientGrading (projIdeal W))
      (mk_X_mem_quotientGrading_one W 1) one_pos
      (mk_X_mem_quotientGrading_one W 2) one_pos]
  change HomogeneousLocalization.Away.isLocalizationElem
      (mk_X_mem_quotientGrading_one W 1) (mk_X_mem_quotientGrading_one W 2) ∉
        ((Spec.map (Proj.awayToSection (quotientGrading (projIdeal W))
          ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1)))).base q).asIdeal ↔ _
  change HomogeneousLocalization.Away.isLocalizationElem
      (mk_X_mem_quotientGrading_one W 1) (mk_X_mem_quotientGrading_one W 2) ∉
        Ideal.comap (Proj.awayToSection (quotientGrading (projIdeal W))
          ((quotientGradingHom (projIdeal W)) (MvPolynomial.X 1))).hom q.asIdeal ↔ _
  rw [Ideal.mem_comap, awayToSection_X2_eq_infChartTElemSection]

/-- The canonical section neighborhood and the affine `Z`-chart cover the
projective Weierstrass model. -/
theorem projModelZChart_sup_sectionNeighborhood_eq_top (W : WeierstrassCurve R) :
    (projModelZChart W : (projModel W).Opens) ⊔
      (projModelSectionNeighborhood W : (projModel W).Opens) = ⊤ := by
  rw [_root_.eq_top_iff]
  intro x _
  rw [TopologicalSpace.Opens.mem_sup]
  have hYZ : x ∈ (projModelYChart W : (projModel W).Opens) ∨
      x ∈ (projModelZChart W : (projModel W).Opens) := by
    have hcover : (projModelYChart W : (projModel W).Opens) ⊔
        (projModelZChart W : (projModel W).Opens) = ⊤ :=
      basicOpen_X1_sup_basicOpen_X2_eq_top W
    rw [← TopologicalSpace.Opens.mem_sup, hcover]
    trivial
  rcases hYZ with hxY | hxZ
  · by_cases hxZ : x ∈ (projModelZChart W : (projModel W).Opens)
    · exact Or.inl hxZ
    · right
      let q := (projModelYChart W).2.primeIdealOf ⟨x, hxY⟩
      have htq : (chartYSectionsRingEquiv W).symm (infChartTElem W) ∈ q.asIdeal := by
        by_contra htq
        exact hxZ ((mem_projModelZChart_iff_not_mem_infChartTElem W x hxY).mpr htq)
      let P : Ideal (AdjoinRoot (infChartCubic W)) :=
        Ideal.map (chartYSectionsRingEquiv W) q.asIdeal
      letI : P.IsPrime := Ideal.map_isPrime_of_equiv (chartYSectionsRingEquiv W)
      have htP : infChartTElem W ∈ P := by
        have hmap := Ideal.mem_map_of_mem (chartYSectionsRingEquiv W) htq
        simpa only [RingEquiv.apply_symm_apply] using hmap
      have hsP : AdjoinRoot.root (infChartCubic W) ∈ P :=
        root_mem_of_tel_mem W P htP
      have huSub : sectionUnitElem W - 1 ∈ P := by
        apply (Ideal.span_le.mpr ?_) (sectionUnitElem_sub_one_mem W)
        rintro a (rfl | rfl)
        · exact hsP
        · exact htP
      have huq : (chartYSectionsRingEquiv W).symm (sectionUnitElem W) ∉ q.asIdeal := by
        intro huq
        have huP : sectionUnitElem W ∈ P := by
          have hmap := Ideal.mem_map_of_mem (chartYSectionsRingEquiv W) huq
          simpa only [RingEquiv.apply_symm_apply] using hmap
        have h1 : (1 : AdjoinRoot (infChartCubic W)) ∈ P := by
          have := P.sub_mem huP huSub
          simpa only [sub_sub_cancel] using this
        exact (inferInstance : P.IsPrime).ne_top ((Ideal.eq_top_iff_one P).mpr h1)
      show x ∈ (projModel W).basicOpen (projModelSectionUnitSection W)
      have hkey : (chartYSectionsRingEquiv W).symm (sectionUnitElem W) ∉ q.asIdeal ↔
          x ∈ (projModel W).basicOpen
            ((chartYSectionsRingEquiv W).symm (sectionUnitElem W)) := by
        change (chartYSectionsRingEquiv W).symm (sectionUnitElem W) ∉
            ((projModelYChart W).2.primeIdealOf ⟨x, hxY⟩).asIdeal ↔ _
        rw [← PrimeSpectrum.mem_basicOpen, IsAffineOpen.primeIdealOf,
          ← (projModelYChart W).2.fromSpec_preimage_basicOpen]
        show (projModelYChart W).2.fromSpec.base
            ((projModelYChart W).1.toSpecΓ.base ⟨x, hxY⟩) ∈
              (projModel W).basicOpen
                ((chartYSectionsRingEquiv W).symm (sectionUnitElem W)) ↔ _
        rw [← Scheme.Hom.comp_apply, IsAffineOpen.toSpecΓ_fromSpec,
          Scheme.Opens.ι_apply]
      exact hkey.mp huq
  · exact Or.inl hxZ

/-- The root coordinate `s`, restricted to the canonical section neighborhood. -/
noncomputable def projModelSectionRoot (W : WeierstrassCurve R) :
    Γ(projModel W, projModelSectionNeighborhood W) :=
  (projModel W).presheaf.map
    (homOfLE ((projModel W).affineBasicOpen_le
      (projModelSectionUnitSection W))).op
    ((chartYSectionsRingEquiv W).symm
      (AdjoinRoot.root (infChartCubic W)))

/-- On the canonical section neighborhood, the zero-section ideal is generated by `s`. -/
theorem projModelZero_ker_ideal_sectionNeighborhood (W : WeierstrassCurve R) :
    (projModelZero W).ker.ideal (projModelSectionNeighborhood W) =
      Ideal.span {projModelSectionRoot W} := by
  let X := projModel W
  let U := projModelYChart W
  let u := projModelSectionUnitSection W
  let V := projModelSectionNeighborhood W
  let s : Γ(X, U) := (chartYSectionsRingEquiv W).symm
    (AdjoinRoot.root (infChartCubic W))
  let t : Γ(X, U) := (chartYSectionsRingEquiv W).symm (infChartTElem W)
  let res : Γ(X, U) ⟶ Γ(X, V) :=
    X.presheaf.map (homOfLE (X.affineBasicOpen_le u)).op
  have hmap := (projModelZero W).ker.map_ideal (X.affineBasicOpen_le u)
  change Ideal.map res.hom ((projModelZero W).ker.ideal U) =
      (projModelZero W).ker.ideal V at hmap
  rw [← hmap]
  rw [show (projModelZero W).ker.ideal U = Ideal.span {s, t} from
    projModelZero_ker_ideal_chartY W]
  rw [Ideal.map_span, Set.image_insert_eq, Set.image_singleton]
  apply le_antisymm
  · refine Ideal.span_le.mpr ?_
    rintro a (rfl | rfl)
    · exact Ideal.mem_span_singleton_self _
    · let ψ : AdjoinRoot (infChartCubic W) →+* Γ(X, V) :=
        res.hom.comp (chartYSectionsRingEquiv W).symm.toRingHom
      have hu : IsUnit (ψ (sectionUnitElem W)) := by
        change IsUnit (res.hom u)
        exact AlgebraicGeometry.RingedSpace.isUnit_res_basicOpen X.toRingedSpace u
      change ψ (infChartTElem W) ∈
        Ideal.span {ψ (AdjoinRoot.root (infChartCubic W))}
      exact tel_image_mem_span_of_isUnit ψ hu
  · exact Ideal.span_mono (Set.singleton_subset_iff.mpr (Set.mem_insert _ _))

/-- The generator `s` remains a nonzerodivisor on the canonical section neighborhood. -/
theorem projModelSectionRoot_mem_nonZeroDivisors (W : WeierstrassCurve R) :
    projModelSectionRoot W ∈
      nonZeroDivisors Γ(projModel W, projModelSectionNeighborhood W) := by
  let X := projModel W
  let U := projModelYChart W
  let u := projModelSectionUnitSection W
  let s : Γ(X, U) := (chartYSectionsRingEquiv W).symm
    (AdjoinRoot.root (infChartCubic W))
  change (X.presheaf.map (homOfLE (X.affineBasicOpen_le u)).op).hom s ∈
    nonZeroDivisors Γ(X, X.affineBasicOpen u)
  let res : Γ(X, U) ⟶ Γ(X, X.affineBasicOpen u) :=
    X.presheaf.map (homOfLE (X.affineBasicOpen_le u)).op
  letI : Algebra Γ(X, U) Γ(X, X.affineBasicOpen u) := res.hom.toAlgebra
  haveI : IsLocalization.Away u Γ(X, X.affineBasicOpen u) :=
    U.2.isLocalization_basicOpen u
  exact IsLocalization.map_nonZeroDivisors_le (Submonoid.powers u)
    Γ(X, X.affineBasicOpen u) ⟨s,
      RingEquiv_map_mem_nonZeroDivisors (chartYSectionsRingEquiv W).symm
        (infChart_root_mem_nonZeroDivisors W), rfl⟩

/-- The explicit ideal-sheaf trivialization on the canonical neighborhood of the zero
section. -/
noncomputable def projModelZeroIdealTrivialization (W : WeierstrassCurve R) :
    Scheme.Modules.unitObj (projModelSectionNeighborhood W).1.toScheme ≅
      (idealModule (projModelZero W)).restrict
        (projModelSectionNeighborhood W).1.ι := by
  let r := projModelSectionRoot W
  have hspan := projModelZero_ker_ideal_sectionNeighborhood W
  have hr : r ∈ (projModelZero W).ker.ideal (projModelSectionNeighborhood W) := by
    rw [hspan]
    exact Ideal.mem_span_singleton_self r
  exact localIdealGeneratorIso (projModelZero W) (projModelSectionNeighborhood W)
    r hr hspan (projModelSectionRoot_mem_nonZeroDivisors W)

/-- The ideal-sheaf trivialization on the affine `Z`-chart, where the generator is `1`. -/
noncomputable def projModelZeroIdealTrivializationZ (W : WeierstrassCurve R) :
    Scheme.Modules.unitObj (projModelZChart W).1.toScheme ≅
      (idealModule (projModelZero W)).restrict (projModelZChart W).1.ι := by
  have hspan := projModelZero_ker_ideal_chartZ W
  have hr : (1 : Γ(projModel W, projModelZChart W)) ∈
      (projModelZero W).ker.ideal (projModelZChart W) := by
    rw [hspan]
    exact Ideal.mem_span_singleton_self 1
  exact localIdealGeneratorIso (projModelZero W) (projModelZChart W)
    1 hr hspan (by exact one_mem (nonZeroDivisors _))

/-- The overlap of the canonical section neighborhood with the affine `Z`-chart. -/
noncomputable def projModelPoleOverlap (W : WeierstrassCurve R) :
    (projModel W).Opens :=
  (projModelSectionNeighborhood W : (projModel W).Opens) ⊓
    (projModelZChart W : (projModel W).Opens)

theorem projModelPoleOverlap_le_sectionNeighborhood (W : WeierstrassCurve R) :
    projModelPoleOverlap W ≤
      (projModelSectionNeighborhood W : (projModel W).Opens) :=
  inf_le_left

theorem projModelPoleOverlap_le_ZChart (W : WeierstrassCurve R) :
    projModelPoleOverlap W ≤ (projModelZChart W : (projModel W).Opens) :=
  inf_le_right

/-- The section parameter `s`, restricted to the overlap with the `Z`-chart. -/
noncomputable def projModelSectionRootOverlap (W : WeierstrassCurve R) :
    Γ(projModel W, projModelPoleOverlap W) :=
  (projModel W).presheaf.map
    (homOfLE (projModelPoleOverlap_le_sectionNeighborhood W)).op
    (projModelSectionRoot W)

/-- The section-neighborhood ideal trivialization, expressed on its over-site. -/
noncomputable def projModelZeroIdealOverTrivialization (W : WeierstrassCurve R) :
    (idealModule (projModelZero W)).over (projModelSectionNeighborhood W) ≅
      SheafOfModules.unit
        ((projModel W).ringCatSheaf.over (projModelSectionNeighborhood W)) :=
  Scheme.Modules.overTrivializationOfRestrictIso
    (idealModule (projModelZero W)) (projModelSectionNeighborhood W)
    (projModelZeroIdealTrivialization W).symm

/-- The `Z`-chart ideal trivialization, expressed on its over-site. -/
noncomputable def projModelZeroIdealOverTrivializationZ (W : WeierstrassCurve R) :
    (idealModule (projModelZero W)).over (projModelZChart W) ≅
      SheafOfModules.unit ((projModel W).ringCatSheaf.over (projModelZChart W)) :=
  Scheme.Modules.overTrivializationOfRestrictIso
    (idealModule (projModelZero W)) (projModelZChart W)
    (projModelZeroIdealTrivializationZ W).symm

theorem projModelZeroIdealOverTrivialization_inv_comp
    (W : WeierstrassCurve R) :
    (projModelZeroIdealOverTrivialization W).inv ≫
        (idealModuleToUnit (projModelZero W)).over
          (projModelSectionNeighborhood W) =
      SheafOfModules.overUnitScalarEnd (projModel W).ringCatSheaf
        (projModelSectionNeighborhood W) (projModelSectionRoot W) := by
  let r := projModelSectionRoot W
  have hspan := projModelZero_ker_ideal_sectionNeighborhood W
  have hr : r ∈ (projModelZero W).ker.ideal
      (projModelSectionNeighborhood W) := by
    rw [hspan]
    exact Ideal.mem_span_singleton_self r
  simpa only [projModelZeroIdealOverTrivialization,
    projModelZeroIdealTrivialization] using
    localIdealGeneratorOverTrivialization_inv_comp
      (projModelZero W) (projModelSectionNeighborhood W) r hr hspan
        (projModelSectionRoot_mem_nonZeroDivisors W)

theorem projModelZeroIdealOverTrivializationZ_inv_comp
    (W : WeierstrassCurve R) :
    (projModelZeroIdealOverTrivializationZ W).inv ≫
        (idealModuleToUnit (projModelZero W)).over (projModelZChart W) =
      SheafOfModules.overUnitScalarEnd (projModel W).ringCatSheaf
        (projModelZChart W) (1 : Γ(projModel W, projModelZChart W)) := by
  have hspan := projModelZero_ker_ideal_chartZ W
  have hr : (1 : Γ(projModel W, projModelZChart W)) ∈
      (projModelZero W).ker.ideal (projModelZChart W) := by
    rw [hspan]
    exact Ideal.mem_span_singleton_self 1
  simpa only [projModelZeroIdealOverTrivializationZ,
    projModelZeroIdealTrivializationZ] using
    localIdealGeneratorOverTrivialization_inv_comp
      (projModelZero W) (projModelZChart W) 1 hr hspan
        (one_mem (nonZeroDivisors _))

/-- The section-neighborhood ideal trivialization, restricted to the overlap. -/
noncomputable def projModelZeroIdealOverlapTrivialization
    (W : WeierstrassCurve R) :
    (idealModule (projModelZero W)).over (projModelPoleOverlap W) ≅
      SheafOfModules.unit
        ((projModel W).ringCatSheaf.over (projModelPoleOverlap W)) :=
  SheafOfModules.restrictOverTrivialization (projModel W).ringCatSheaf
    (idealModule (projModelZero W)) (projModelSectionNeighborhood W)
    (projModelZeroIdealOverTrivialization W)
    (Over.mk (homOfLE (projModelPoleOverlap_le_sectionNeighborhood W)))

/-- The `Z`-chart ideal trivialization, restricted to the overlap. -/
noncomputable def projModelZeroIdealOverlapTrivializationZ
    (W : WeierstrassCurve R) :
    (idealModule (projModelZero W)).over (projModelPoleOverlap W) ≅
      SheafOfModules.unit
        ((projModel W).ringCatSheaf.over (projModelPoleOverlap W)) :=
  SheafOfModules.restrictOverTrivialization (projModel W).ringCatSheaf
    (idealModule (projModelZero W)) (projModelZChart W)
    (projModelZeroIdealOverTrivializationZ W)
    (Over.mk (homOfLE (projModelPoleOverlap_le_ZChart W)))

theorem projModelZeroIdealOverlapTrivialization_inv_comp
    (W : WeierstrassCurve R) :
    (projModelZeroIdealOverlapTrivialization W).inv ≫
        (idealModuleToUnit (projModelZero W)).over (projModelPoleOverlap W) =
      SheafOfModules.overUnitScalarEnd (projModel W).ringCatSheaf
        (projModelPoleOverlap W) (projModelSectionRootOverlap W) := by
  have hres := restrictOverTrivialization_inv_comp_over
    (idealModuleToUnit (projModelZero W)) (projModelSectionNeighborhood W)
      (projModelZeroIdealOverTrivialization W) (projModelSectionRoot W)
        (projModelZeroIdealOverTrivialization_inv_comp W)
          (projModelPoleOverlap_le_sectionNeighborhood W)
  convert hres using 1
  all_goals simp only [projModelZeroIdealOverlapTrivialization,
    projModelSectionRootOverlap]
  all_goals rfl

theorem projModelZeroIdealOverlapTrivializationZ_inv_comp
    (W : WeierstrassCurve R) :
    (projModelZeroIdealOverlapTrivializationZ W).inv ≫
        (idealModuleToUnit (projModelZero W)).over (projModelPoleOverlap W) =
      SheafOfModules.overUnitScalarEnd (projModel W).ringCatSheaf
        (projModelPoleOverlap W) (1 : Γ(projModel W, projModelPoleOverlap W)) := by
  have hres := restrictOverTrivialization_inv_comp_over
    (idealModuleToUnit (projModelZero W)) (projModelZChart W)
      (projModelZeroIdealOverTrivializationZ W)
        (1 : Γ(projModel W, projModelZChart W))
          (projModelZeroIdealOverTrivializationZ_inv_comp W)
            (projModelPoleOverlap_le_ZChart W)
  convert hres using 1
  all_goals simp only [projModelZeroIdealOverlapTrivializationZ, map_one]
  all_goals rfl

section

local instance (X : Scheme.{u}) :
    ∀ U, IsMulCommutative (X.ringCatSheaf.obj.obj U) :=
  fun U ↦ by
    change IsMulCommutative (X.presheaf.obj U)
    exact IsMulCommutative.of_comm fun a b ↦ mul_comm a b

/-- On the overlap, the ideal trivializations differ by multiplication by the
section parameter `s`. -/
theorem projModelZeroIdealOverlap_transition (W : WeierstrassCurve R) :
    (projModelZeroIdealOverlapTrivializationZ W).hom =
      (projModelZeroIdealOverlapTrivialization W).hom ≫
        SheafOfModules.overUnitScalarEnd (projModel W).ringCatSheaf
          (projModelPoleOverlap W) (projModelSectionRootOverlap W) := by
  let eU := projModelZeroIdealOverlapTrivialization W
  let eZ := projModelZeroIdealOverlapTrivializationZ W
  let i := (idealModuleToUnit (projModelZero W)).over (projModelPoleOverlap W)
  let s := projModelSectionRootOverlap W
  change eZ.hom = eU.hom ≫
    SheafOfModules.overUnitScalarEnd (projModel W).ringCatSheaf
      (projModelPoleOverlap W) s
  have hone := map_one
    (SheafOfModules.overUnitScalarEndRingHom (projModel W).ringCatSheaf
      (projModelPoleOverlap W))
  have hZ : eZ.inv ≫ i = 𝟙 _ := by
    rw [show eZ.inv ≫ i =
      SheafOfModules.overUnitScalarEnd (projModel W).ringCatSheaf
        (projModelPoleOverlap W) 1 from
          projModelZeroIdealOverlapTrivializationZ_inv_comp W]
    exact hone
  have hi : i = eZ.hom := by
    calc
      i = 𝟙 _ ≫ i := (Category.id_comp i).symm
      _ = (eZ.hom ≫ eZ.inv) ≫ i := by rw [eZ.hom_inv_id]
      _ = eZ.hom ≫ (eZ.inv ≫ i) := Category.assoc _ _ _
      _ = eZ.hom ≫ 𝟙 _ := congrArg (fun q ↦ eZ.hom ≫ q) hZ
      _ = eZ.hom := Category.comp_id _
  apply (cancel_epi eU.inv).1
  rw [eU.inv_hom_id_assoc]
  rw [← hi]
  exact projModelZeroIdealOverlapTrivialization_inv_comp W

end

section

local instance (X : Scheme.{u}) :
    ∀ U, IsMulCommutative (X.ringCatSheaf.obj.obj U) :=
  fun U ↦ by
    change IsMulCommutative (X.presheaf.obj U)
    exact IsMulCommutative.of_comm fun a b ↦ mul_comm a b

/-- The section-neighborhood simple-pole trivialization, restricted to the
overlap with the `Z`-chart. -/
noncomputable def projModelSectionPoleOverlapTrivialization
    (W : WeierstrassCurve R) :
    (sectionPoleSheaf (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W)).over (projModelPoleOverlap W) ≅
      SheafOfModules.unit
        ((projModel W).ringCatSheaf.over (projModelPoleOverlap W)) := by
  change (Scheme.Modules.dualObj
      (sectionIdealModule (projModelπ W) (projModelZero W)
        (projModelZero_projModelπ W))).over (projModelPoleOverlap W) ≅ _
  apply SheafOfModules.dualOverIsoOfIso (projModel W).ringCatSheaf
    (sectionIdealModule (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W)) (projModelPoleOverlap W)
  change (idealModule (projModelZero W)).over (projModelPoleOverlap W) ≅ _
  exact projModelZeroIdealOverlapTrivialization W

/-- The `Z`-chart simple-pole trivialization, restricted to the overlap. -/
noncomputable def projModelSectionPoleOverlapTrivializationZ
    (W : WeierstrassCurve R) :
    (sectionPoleSheaf (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W)).over (projModelPoleOverlap W) ≅
      SheafOfModules.unit
        ((projModel W).ringCatSheaf.over (projModelPoleOverlap W)) := by
  change (Scheme.Modules.dualObj
      (sectionIdealModule (projModelπ W) (projModelZero W)
        (projModelZero_projModelπ W))).over (projModelPoleOverlap W) ≅ _
  apply SheafOfModules.dualOverIsoOfIso (projModel W).ringCatSheaf
    (sectionIdealModule (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W)) (projModelPoleOverlap W)
  change (idealModule (projModelZero W)).over (projModelPoleOverlap W) ≅ _
  exact projModelZeroIdealOverlapTrivializationZ W

/-- On the overlap, the simple-pole trivializations differ by multiplication by
the section parameter `s`. -/
theorem projModelSectionPoleOverlap_transition (W : WeierstrassCurve R) :
    (projModelSectionPoleOverlapTrivialization W).hom =
      (projModelSectionPoleOverlapTrivializationZ W).hom ≫
        SheafOfModules.overUnitScalarEnd (projModel W).ringCatSheaf
          (projModelPoleOverlap W) (projModelSectionRootOverlap W) := by
  let M := sectionIdealModule (projModelπ W) (projModelZero W)
    (projModelZero_projModelπ W)
  let e : M.over (projModelPoleOverlap W) ≅
      SheafOfModules.unit
        ((projModel W).ringCatSheaf.over (projModelPoleOverlap W)) := by
    change (idealModule (projModelZero W)).over (projModelPoleOverlap W) ≅ _
    exact projModelZeroIdealOverlapTrivialization W
  let g : M.over (projModelPoleOverlap W) ≅
      SheafOfModules.unit
        ((projModel W).ringCatSheaf.over (projModelPoleOverlap W)) := by
    change (idealModule (projModelZero W)).over (projModelPoleOverlap W) ≅ _
    exact projModelZeroIdealOverlapTrivializationZ W
  have h : g.hom = e.hom ≫
      SheafOfModules.overUnitScalarEnd (projModel W).ringCatSheaf
        (projModelPoleOverlap W) (projModelSectionRootOverlap W) := by
    change (projModelZeroIdealOverlapTrivializationZ W).hom =
      (projModelZeroIdealOverlapTrivialization W).hom ≫ _
    exact projModelZeroIdealOverlap_transition W
  change (SheafOfModules.dualOverIsoOfIso (projModel W).ringCatSheaf M
      (projModelPoleOverlap W) e).hom =
    (SheafOfModules.dualOverIsoOfIso (projModel W).ringCatSheaf M
      (projModelPoleOverlap W) g).hom ≫ _
  exact dualOverIsoOfIso_hom_eq_comp_scalar M (projModelPoleOverlap W)
    e g (projModelSectionRootOverlap W) h

end

/-- The simple-pole sheaf is trivial on the canonical neighborhood of the zero
section, by dualizing the ideal generated by `s`. -/
noncomputable def projModelSectionPoleSheafTrivialization (W : WeierstrassCurve R) :
    (sectionPoleSheaf (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W)).restrict
        (projModelSectionNeighborhood W).1.ι ≅
      Scheme.Modules.unitObj (projModelSectionNeighborhood W).1.toScheme := by
  apply Scheme.Modules.dualRestrictIsoOfRestrictIso
    (sectionIdealModule (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W))
    (projModelSectionNeighborhood W)
  change (idealModule (projModelZero W)).restrict
      (projModelSectionNeighborhood W).1.ι ≅
    Scheme.Modules.unitObj (projModelSectionNeighborhood W).1.toScheme
  exact (projModelZeroIdealTrivialization W).symm

/-- The simple-pole sheaf is trivial on the affine `Z`-chart, where the zero
section is absent. -/
noncomputable def projModelSectionPoleSheafTrivializationZ (W : WeierstrassCurve R) :
    (sectionPoleSheaf (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W)).restrict (projModelZChart W).1.ι ≅
      Scheme.Modules.unitObj (projModelZChart W).1.toScheme := by
  apply Scheme.Modules.dualRestrictIsoOfRestrictIso
    (sectionIdealModule (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W)) (projModelZChart W)
  change (idealModule (projModelZero W)).restrict (projModelZChart W).1.ι ≅
    Scheme.Modules.unitObj (projModelZChart W).1.toScheme
  exact (projModelZeroIdealTrivializationZ W).symm

/-- The induced trivialization of `O(n[0])` on the canonical section
neighborhood. -/
noncomputable def projModelSectionPoleSheafPowerTrivialization
    (W : WeierstrassCurve R) (n : ℕ) :
    (sectionPoleSheafPower (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W) n).restrict
        (projModelSectionNeighborhood W).1.ι ≅
      Scheme.Modules.unitObj (projModelSectionNeighborhood W).1.toScheme :=
  sectionPoleSheafPowerTrivialization (projModelZero W)
    (projModelZero_projModelπ W) (projModelSectionNeighborhood W)
    (projModelSectionPoleSheafTrivialization W) n

/-- The induced trivialization of `O(n[0])` on the affine `Z`-chart. -/
noncomputable def projModelSectionPoleSheafPowerTrivializationZ
    (W : WeierstrassCurve R) (n : ℕ) :
    (sectionPoleSheafPower (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W) n).restrict (projModelZChart W).1.ι ≅
      Scheme.Modules.unitObj (projModelZChart W).1.toScheme :=
  sectionPoleSheafPowerTrivialization (projModelZero W)
    (projModelZero_projModelπ W) (projModelZChart W)
    (projModelSectionPoleSheafTrivializationZ W) n

/-- The coefficient near the zero section of a global section of `O(n[0])`. -/
noncomputable def projModelSectionPoleCoefficient (W : WeierstrassCurve R) (n : ℕ)
    (m : Γ(sectionPoleSheafPower (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W) n, (⊤ : (projModel W).Opens))) :
    Γ(projModel W, projModelSectionNeighborhood W) :=
  localTrivializationCoefficient
    (sectionPoleSheafPower (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W) n)
    (projModelSectionNeighborhood W)
    (projModelSectionPoleSheafPowerTrivialization W n) m

/-- The affine coordinate of a global section of `O(n[0])` on the `Z`-chart. -/
noncomputable def projModelSectionPoleCoefficientZ (W : WeierstrassCurve R) (n : ℕ)
    (m : Γ(sectionPoleSheafPower (projModelπ W) (projModelZero W)
      (projModelZero_projModelπ W) n, (⊤ : (projModel W).Opens))) :
    W.toAffine.CoordinateRing :=
  chartZSectionsRingEquiv W
    (localTrivializationCoefficient
      (sectionPoleSheafPower (projModelπ W) (projModelZero W)
        (projModelZero_projModelπ W) n)
      (projModelZChart W)
      (projModelSectionPoleSheafPowerTrivializationZ W n) m)

end ModularCurves
