module

public import Mathlib.NumberTheory.NumberField.Units.Regulator

/-!
# Regulator-index algebra

This file gives the cyclotomic-unit route a stable name for the standard
regulator/index identity for a full-rank unit family, as provided by mathlib.
-/

@[expose] public section

noncomputable section

open NumberField

namespace BernoulliRegular

/-- The regulator of a full-rank unit family equals the regulator of the field
multiplied by the index of the subgroup generated by the family and torsion.

This is a direct rearrangement of mathlib's
`NumberField.Units.regOfFamily_div_regulator`. -/
theorem regulator_subgroup_eq_index_mul_regulator
    {F : Type*} [Field F] [NumberField F]
    (u : Fin (NumberField.Units.rank F) → (𝓞 F)ˣ) :
    NumberField.Units.regOfFamily u =
      ((Subgroup.closure (Set.range u) ⊔ NumberField.Units.torsion F).index : ℝ) *
        NumberField.Units.regulator F := by
  have h := NumberField.Units.regOfFamily_div_regulator u
  have hreg_ne : NumberField.Units.regulator F ≠ 0 :=
    (NumberField.Units.regulator_pos F).ne'
  calc
    NumberField.Units.regOfFamily u =
        NumberField.Units.regOfFamily u / NumberField.Units.regulator F *
          NumberField.Units.regulator F := by
      field_simp [hreg_ne]
    _ = ((Subgroup.closure (Set.range u) ⊔ NumberField.Units.torsion F).index : ℝ) *
          NumberField.Units.regulator F := by
      rw [h]

end BernoulliRegular

end
