module

public import BernoulliRegular.HilbertClassField
public import Mathlib.FieldTheory.KummerExtension

/-!
# Kummer setup for explicit Hilbert/Kummer presentation data

This file starts the `T037` Kummer-pairing layer.  It packages the quotient
`Kˣ/(Kˣ)^p` and the subgroup `C` that will generate the Kummer description of
an explicit Hilbert/Kummer presentation.

The subgroup is currently data. A full `HilbertPClassField` can still be
supplied explicitly, but component-extension no longer postulates its existence; the current
component-extension package exposes a component-refined unramified cyclic degree-`p` extension
projection. Later refinement work should replace this broad presentation layer
with one built from that narrower extension package.
-/

@[expose] public section

universe u v

noncomputable section

open NumberField

namespace BernoulliRegular

set_option linter.unusedSectionVars false

section Setup

variable (p : ℕ) [Fact p.Prime] (K : Type u) [Field K] [NumberField K]

/-- The subgroup of `p`-th powers in `Kˣ`. -/
abbrev kummerPowerSubgroup : Subgroup Kˣ :=
  (powMonoidHom p : Kˣ →* Kˣ).range

/-- The Kummer quotient `Kˣ/(Kˣ)^p`. -/
abbrev KummerPowerQuotient : Type _ :=
  Kˣ ⧸ kummerPowerSubgroup (p := p) K

/-- The quotient map `Kˣ → Kˣ/(Kˣ)^p`. -/
def kummerPowerClass : Kˣ →* KummerPowerQuotient (p := p) K :=
  QuotientGroup.mk' (kummerPowerSubgroup (p := p) K)

@[simp]
lemma kummerPowerClass_apply (x : Kˣ) :
    kummerPowerClass (p := p) K x =
      (QuotientGroup.mk x : KummerPowerQuotient (p := p) K) :=
  rfl

/-- A declared Kummer subgroup attached to a chosen Hilbert `p`-class field.

The field `subgroup` is the `C ⊂ Kˣ/(Kˣ)^p` used downstream to construct the
Kummer pairing.  The explicit realization of the Hilbert class field as the
extension generated by adjoining `p`-th roots of representatives of `C` is
recorded separately in `T037b`. -/
structure HilbertKummerSubgroup where
  hilbert : HilbertPClassField.{u, v} K p
  subgroup : Subgroup (KummerPowerQuotient (p := p) K)

namespace HilbertKummerSubgroup

variable {p K}

/-- The Hilbert `p`-class field in a Kummer-subgroup package. -/
abbrev Hp (C : HilbertKummerSubgroup (p := p) K) : Type _ :=
  C.hilbert.Hp

instance field (C : HilbertKummerSubgroup (p := p) K) : Field C.Hp :=
  C.hilbert.field

instance algebra (C : HilbertKummerSubgroup (p := p) K) : Algebra K C.Hp :=
  C.hilbert.algebra

instance isGalois (C : HilbertKummerSubgroup (p := p) K) : IsGalois K C.Hp :=
  C.hilbert.isGalois

instance finiteDimensional (C : HilbertKummerSubgroup (p := p) K) :
    FiniteDimensional K C.Hp :=
  C.hilbert.finiteDimensional

/-- The declared subgroup `C ⊂ Kˣ/(Kˣ)^p`. -/
abbrev C (H : HilbertKummerSubgroup (p := p) K) :
    Subgroup (KummerPowerQuotient (p := p) K) :=
  H.subgroup

/-- The class-field-theory Galois isomorphism from the Hilbert package. -/
def galEquiv (H : HilbertKummerSubgroup (p := p) K) :
    (H.Hp ≃ₐ[K] H.Hp) ≃* ClassGroupModP K p :=
  H.hilbert.galEquiv

/-- `T037b`: a Kummer-extension presentation of the Hilbert `p`-class field.

The field `E` is the extension used by the Kummer pairing, `subgroup` is the
declared Kummer subgroup `C ⊂ Kˣ/(Kˣ)^p`, and `toHilbert` identifies `E` with
the Hilbert `p`-class field from Axiom component-extension.  The actual Kummer-generation theorem
is represented by this presentation data, so downstream files can depend on a
single object without adding another axiom. -/
structure HilbertKummerExtension (H : HilbertKummerSubgroup.{u, v} (p := p) K) where
  /-- The Kummer extension field. -/
  E : Type v
  /-- Field structure on the Kummer extension. -/
  [field : Field E]
  /-- Base-field algebra structure. -/
  [algebra : Algebra K E]
  /-- The Kummer extension is Galois over the base. -/
  [isGalois : IsGalois K E]
  /-- The Kummer extension is finite over the base. -/
  [finiteDimensional : FiniteDimensional K E]
  /-- The Kummer subgroup used to present the extension. -/
  subgroup : Subgroup (KummerPowerQuotient (p := p) K)
  /-- The presented subgroup is the declared subgroup attached to `H`. -/
  subgroup_eq : subgroup = H.C
  /-- Identification of the Kummer extension with the Hilbert `p`-class field. -/
  toHilbert : E ≃ₐ[K] H.Hp
  /-- The transported class-field-theory Galois isomorphism in the presentation
  field. -/
  galEquiv : (E ≃ₐ[K] E) ≃* ClassGroupModP K p

namespace HilbertKummerExtension

variable {H : HilbertKummerSubgroup.{u, v} (p := p) K}

attribute [instance] field algebra isGalois finiteDimensional

/-- The subgroup in a Kummer presentation, rewritten as the declared subgroup
attached to the Hilbert package. -/
theorem subgroup_eq_C (P : HilbertKummerExtension (p := p) (K := K) H) :
    P.subgroup = H.C :=
  P.subgroup_eq

end HilbertKummerExtension

/-- The canonical presentation using the Hilbert `p`-class field itself as the
Kummer extension field. -/
def toKummerExtension (H : HilbertKummerSubgroup (p := p) K) :
    HilbertKummerExtension (p := p) (K := K) H where
  E := H.Hp
  field := inferInstance
  algebra := inferInstance
  isGalois := inferInstance
  finiteDimensional := inferInstance
  subgroup := H.C
  subgroup_eq := rfl
  toHilbert := (AlgEquiv.refl : H.Hp ≃ₐ[K] H.Hp)
  galEquiv := H.galEquiv

@[simp]
theorem toKummerExtension_subgroup
    (H : HilbertKummerSubgroup (p := p) K) :
    H.toKummerExtension.subgroup = H.C :=
  rfl

/-- A single object bundling the declared Kummer subgroup and its Hilbert-field
presentation.  This is the form consumed by the pairing construction after
`T037`. -/
structure HilbertKummerPresentation where
  subgroupData : HilbertKummerSubgroup.{u, v} (p := p) K
  extension : HilbertKummerExtension (p := p) (K := K) subgroupData

namespace HilbertKummerPresentation

variable (P : HilbertKummerPresentation (p := p) (K := K))

/-- The Kummer subgroup in the final presentation. -/
abbrev C : Subgroup (KummerPowerQuotient (p := p) K) :=
  P.subgroupData.C

/-- The extension field in the final presentation. -/
abbrev E : Type v :=
  P.extension.E

instance field : Field P.E :=
  P.extension.field

instance algebra : Algebra K P.E :=
  P.extension.algebra

instance isGalois : IsGalois K P.E :=
  P.extension.isGalois

instance finiteDimensional : FiniteDimensional K P.E :=
  P.extension.finiteDimensional

/-- The presentation field is identified with the Hilbert `p`-class field. -/
def toHilbert : P.E ≃ₐ[K] P.subgroupData.Hp :=
  P.extension.toHilbert

/-- The class-field-theory Galois isomorphism in the presentation field. -/
def galEquiv : (P.E ≃ₐ[K] P.E) ≃* ClassGroupModP K p :=
  P.extension.galEquiv

end HilbertKummerPresentation

/-- Build the final Kummer-pairing presentation from a declared Hilbert Kummer
subgroup. -/
def presentation (H : HilbertKummerSubgroup (p := p) K) :
    HilbertKummerPresentation (p := p) (K := K) where
  subgroupData := H
  extension := H.toKummerExtension

end HilbertKummerSubgroup

end Setup

end BernoulliRegular

end
