import ModularCurves.LevelStructure.ExactOrder

/-!
# Level structures: Γ(N), Γ₁(N), Γ₀(N) (KM Ch. 3)

The four basic moduli problems of KM Ch. 3, in two register:

1. **Drinfeld form** (arbitrary base — the definitions of record, KM 3.1–3.4):
   * `[Γ(N)]`: pairs of points `P, Q ∈ E(S)` such that the `N²` combinations `aP + bQ`
     form a full set of sections of `E[N]` (KM 3.1).
   * `[Γ₁(N)]`: points of exact order `N` (KM 3.2, via KM 1.4).
   * `[Γ₀(N)]`: finite locally free rank-`N` cyclic subgroup schemes (KM 3.4, "cyclic" =
     fppf-locally generated by a point of exact order `N`, KM 1.4.1).

2. **Naive form** (`N` invertible; Loeffler Fact 3.8.1, verbatim for `Γ(N)`: "pairs of
   sections `P, Q ∈ E[S]` generating `E[N]` in every fibre"). The equivalence with the
   Drinfeld form when `N` is invertible is KM 1.4.4 / KM 3.7 ("the situation when `N` is
   invertible") — theorems `naive_iff_drinfeld_*` below.

Γ(N)-structures in the Drinfeld register need the full-sets-of-sections machinery on the
scheme `E[N]` (not just its affine model); the skeleton states the fibrewise/naive versions
completely and routes the Drinfeld `Γ(N)` through the affine form on the (affine over
affines) scheme `E[N]` — globalisation is ticket `T-D4`.
-/

open AlgebraicGeometry CategoryTheory Limits

attribute [local instance] CategoryTheory.Over.cartesianMonoidalCategory
  CategoryTheory.Over.braidedCategory

universe u

namespace ModularCurves

namespace EllipticCurve

variable {S : Scheme.{u}} (E : EllipticCurve S)

/-- **Naive full level-`N` structure** (Loeffler Fact 3.8.1, for `N` invertible on `S`):
a pair of points `P, Q ∈ E(S)`, killed by `N`, generating `E[N]` on every geometric fibre:
for every geometric point `t` of `S`, every `N`-torsion point of `E` over `t` is an
integral combination of `P_t` and `Q_t`. -/
def IsNaiveFullLevel (N : ℕ) [NeZero N] (P Q : E.Section) : Prop :=
  ((N : ℤ) • P = 0 ∧ (N : ℤ) • Q = 0) ∧
    ∀ (k : Type u) [Field k] [IsAlgClosed k] (t : Spec (.of k) ⟶ S),
      ∀ x : E.Point t, (N : ℤ) • x = 0 →
        x ∈ AddSubgroup.closure {Point.pull E t P, Point.pull E t Q}

/-- **Naive Γ₁(N)-structure**: a point killed by `N`, of fibrewise exact order `N`
(the right-hand side of KM 1.4.4, *with its standing hypothesis*). For `N` invertible
this coincides with the Drinfeld notion (`Section.hasExactOrder_iff_geometric`).

ADVERSARIAL FIX (2026-07-06, converged on by three independent passes): the global
killing clause `(N : ℤ) • P = 0` is REQUIRED (mirroring `IsNaiveFullLevel`) — without
it, over `Spec ℚ̄[ε]` any tangent-direction lift of an exact-order-`N` point satisfies
the fibrewise clauses while `N•P ≠ 0`; the moduli functor built on the unkilled form
strictly contains `h_{Y₁(N)}` (pro-representation `ℚ̄[[t,s]]`, tangent dimension 2)
and `gammaOneNaive_representable` was FALSE for it. Loeffler's own construction cuts
`Y₁(N)` out by exactly the closed condition `N·(0:0:1) = (0:1:0)`. -/
def IsNaiveGammaOne (N : ℕ) [NeZero N] (P : E.Section) : Prop :=
  ((N : ℤ) • P = 0) ∧
  ∀ (k : Type u) [Field k] [IsAlgClosed k] (t : Spec (.of k) ⟶ S),
    (N : ℤ) • Point.pull E t P = 0 ∧
    ∀ a : ℕ, 0 < a → a < N → (a : ℤ) • Point.pull E t P ≠ 0

/-- **Drinfeld Γ₁(N)-structure** (KM 3.2): a point of exact order `N` in the sense of
KM 1.4.1. This is the definition of record over an arbitrary base. -/
def IsGammaOne (N : ℕ) [NeZero N] (P : E.Section) : Prop :=
  P.HasExactOrder E N

/-- The ideal sheaf of `E[N]` as a closed subscheme of `E`: the kernel ideal of the
inclusion `E[N] ⟶ E` (mathlib `Scheme.Hom.ker`).

REAL definition (adversarial pass 2026-07-06 — previously an *unregistered* data-sorry;
`Scheme.Hom.ker` makes it definable outright, and the pin is `torsionIdeal_subscheme`
below). -/
noncomputable def torsionIdeal (N : ℕ) : Scheme.IdealSheafData E.E :=
  (E.torsionι N).ker

/-- **(T-B3a, pinning spec)** The closed subscheme cut out by `torsionIdeal N` is `E[N]`
itself, compatibly with the inclusions. Discharge: `torsionι_isClosedImmersion` (T-B3)
+ mathlib's `ker_subschemeι` dictionary. -/
theorem torsionIdeal_subscheme (N : ℕ) :
    ∃ e : (E.torsionIdeal N).subscheme ≅ E.torsion N,
      e.hom ≫ E.torsionι N = (E.torsionIdeal N).subschemeι := by sorry

/-- **Drinfeld Γ(N)-structure** (KM 3.1): a pair `P, Q` of points killed by `N` such that
the divisor `Σ_{(a,b) ∈ (ℤ/N)²} [aP + bQ]` equals `E[N]` as a closed subscheme — i.e. the
`N²` points `aP + bQ` form a full set of sections of `E[N]/S`. -/
def IsFullLevel (N : ℕ) [NeZero N] (P Q : E.Section) : Prop :=
  ((N : ℤ) • P = 0 ∧ (N : ℤ) • Q = 0) ∧
    (RelEffCartierDiv.sectionsDivisor E.π
        (fun i : Fin (N ^ 2) =>
          (((((i : ℕ) % N : ℕ) : ℤ) • P + ((((i : ℕ) / N : ℕ) : ℤ) • Q) :
            E.Point (𝟙 S))))).ideal =
      (E.torsionIdeal N)

/-- **(T-D8 = KM 3.7 / KM 1.4.4 upgraded to Γ(N))** For `N` invertible on `S`, Drinfeld
full-level structures and naive full-level structures coincide. -/
theorem isFullLevel_iff_naive (N : ℕ) [NeZero N] (hN : NIsInvertible S N)
    (P Q : E.Section) :
    E.IsFullLevel N P Q ↔ E.IsNaiveFullLevel N P Q := by sorry

/-- **(T-D9 = KM 1.4.4 (1) ⇔ (3), restated)** For `N` invertible, Drinfeld Γ₁(N) equals
naive Γ₁(N). -/
theorem isGammaOne_iff_naive (N : ℕ) [NeZero N] (hN : NIsInvertible S N) (P : E.Section) :
    E.IsGammaOne N P ↔ E.IsNaiveGammaOne N P := by sorry

/-- **Γ₀(N)-structure** (KM 3.4): a relative effective Cartier divisor `G ⊆ E` of degree
`N` which is a subgroup (KM 1.3.6) and is *cyclic* (KM 1.4.1: fppf-locally on `S` admits a
generator of exact order `N`). The generator condition is stated here in its
geometric-fibre **Drinfeld** form: over every geometric point, some section generates
`G` in the divisor sense, `Σ_{a=1}^{N} [a·P₀] = G` as closed subschemes.

ADVERSARIAL FIX (2026-07-06): the previous surrogate demanded a point of *naive* exact
order `N` on fibres — wrong in char `p ∣ N`: `G = Ker F ⊂ E` supersingular over `F̄_p`
(`N = p`) is KM-cyclic with Drinfeld generator `P₀ = 0` (`Σ_a [a·0] = p[0] = Ker F`,
KM 1.4.3), but `E[p](k̄) = 0` has no naive generator, so the old form excluded a
legitimate KM Γ₀(p)-structure. The divisor form below is honest over geometric points
in all characteristics; the literal fppf-local form of record is ticket `T-D10`. -/
structure IsGammaZero (N : ℕ) [NeZero N] (G : RelEffCartierDiv E.π) : Prop where
  isSubgroup : G.IsSubgroup E
  degree_eq : ∀ s : S, G.degree s = N
  /-- Geometric Drinfeld cyclicity: over every geometric point `t` there is a section
  `P₀` of the base-changed curve with `Σ_{a=1}^{N} [a·P₀] = G_t` as divisors. -/
  geometricallyCyclic :
    ∀ (k : Type u) [Field k] [IsAlgClosed k] (t : Spec (.of k) ⟶ S),
      ∃ P₀ : (E.baseChange t).Section,
        (P₀.orderDivisor (E.baseChange t) N).ideal = (G.baseChange t).ideal

end EllipticCurve

end ModularCurves
