/-
Copyright (c) 2026 The AINTLIB Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The AINTLIB Authors
-/
import Mathlib.Algebra.Group.Subgroup.Lattice
import Mathlib.Data.ZMod.Basic
import Mathlib.SetTheory.Cardinal.Finite

/-!
# The fibrewise full-level group-theoretic core (T-D8-bridge, step D)

Over a geometric point the `N`-torsion group `G` has order `N²` (T-B6, `E[N]_{k̄} ≅ (ℤ/N)²`).
For two `N`-torsion elements `P, Q`, the `N²` combinations `[a]P + [b]Q` (indexed by
`Fin (N²)` via `a = i % N`, `b = i / N`) are **pairwise distinct** iff `P, Q` generate `G`:
the map `Fin (N²) → G` has image `⟨P, Q⟩` (an `N²`-element domain into an `N²`-element
codomain), so injective ⟺ surjective ⟺ the image is all of `G`.
-/

namespace ModularCurves

variable {G : Type*} [AddCommGroup G] (N : ℕ) (P Q : G)

/-- The `N²` combination map `i ↦ [i % N]·P + [i / N]·Q`. -/
def comboFamily (i : Fin (N ^ 2)) : G := ((i : ℕ) % N : ℤ) • P + ((i : ℕ) / N : ℤ) • Q

variable {N P Q}

/-- Scalar multiplication of an `N`-killed element is `N`-periodic in the coefficient. -/
private theorem zsmul_emod [NeZero N] {R : G} (hR : (N : ℤ) • R = 0) (c : ℤ) :
    ((c % N).toNat : ℤ) • R = c • R := by
  rw [Int.toNat_of_nonneg (Int.emod_nonneg c (by exact_mod_cast NeZero.ne N))]
  conv_rhs => rw [← Int.emod_add_mul_ediv c (N : ℤ)]
  rw [add_zsmul, mul_comm (N : ℤ), mul_zsmul, hR, smul_zero, add_zero]

variable (N P Q) in
/-- The image of the combination family is exactly the subgroup generated by `P, Q`. -/
theorem range_comboFamily_eq_closure [NeZero N] (hP : (N : ℤ) • P = 0) (hQ : (N : ℤ) • Q = 0) :
    Set.range (comboFamily N P Q) = (AddSubgroup.closure {P, Q} : Set G) := by
  have hpN : 0 < N := Nat.pos_of_ne_zero (NeZero.ne N)
  have hPc : P ∈ AddSubgroup.closure ({P, Q} : Set G) :=
    AddSubgroup.subset_closure (Set.mem_insert P {Q})
  have hQc : Q ∈ AddSubgroup.closure ({P, Q} : Set G) :=
    AddSubgroup.subset_closure (Set.mem_insert_of_mem P rfl)
  apply Set.Subset.antisymm
  · rintro _ ⟨i, rfl⟩
    simp only [comboFamily]
    exact AddSubgroup.add_mem _ (AddSubgroup.zsmul_mem _ hPc _) (AddSubgroup.zsmul_mem _ hQc _)
  · intro x hx
    rw [SetLike.mem_coe, AddSubgroup.mem_closure_pair] at hx
    obtain ⟨a, b, rfl⟩ := hx
    have ha : (a % N).toNat < N := by
      rw [Int.toNat_lt (Int.emod_nonneg a (by exact_mod_cast NeZero.ne N))]
      exact_mod_cast Int.emod_lt_of_pos a (by exact_mod_cast hpN)
    have hb : (b % N).toNat < N := by
      rw [Int.toNat_lt (Int.emod_nonneg b (by exact_mod_cast NeZero.ne N))]
      exact_mod_cast Int.emod_lt_of_pos b (by exact_mod_cast hpN)
    have hid : N + (N - 1) * N = N ^ 2 := by
      have hle : N ≤ N * N := Nat.le_mul_of_pos_left N hpN
      rw [Nat.sub_one_mul, pow_two]; omega
    have hbn : (b % N).toNat * N ≤ (N - 1) * N := Nat.mul_le_mul_right N (by omega)
    have hlt : (a % N).toNat + (b % N).toNat * N < N ^ 2 := by omega
    refine ⟨⟨(a % N).toNat + (b % N).toNat * N, hlt⟩, ?_⟩
    have hmod : ((a % N).toNat + (b % N).toNat * N) % N = (a % N).toNat := by
      rw [Nat.add_mul_mod_self_right]; exact Nat.mod_eq_of_lt ha
    have hdiv : ((a % N).toNat + (b % N).toNat * N) / N = (b % N).toNat := by
      rw [Nat.add_mul_div_right _ _ hpN, Nat.div_eq_of_lt ha, zero_add]
    show ((((a % N).toNat + (b % N).toNat * N) % N : ℕ) : ℤ) • P
        + ((((a % N).toNat + (b % N).toNat * N) / N : ℕ) : ℤ) • Q = a • P + b • Q
    rw [hmod, hdiv, zsmul_emod hP a, zsmul_emod hQ b]

variable (N P Q) in
/-- **[Step D]** For `N` invertible over the geometric point (so `#G = N²`), the `N²`
combinations `[a]P + [b]Q` are pairwise distinct iff `P, Q` generate `G`. -/
theorem comboFamily_injective_iff_closure_top [Finite G] [NeZero N] (hP : (N : ℤ) • P = 0)
    (hQ : (N : ℤ) • Q = 0) (hcard : Nat.card G = N ^ 2) :
    Function.Injective (comboFamily N P Q) ↔ AddSubgroup.closure {P, Q} = ⊤ := by
  haveI : Fintype G := Fintype.ofFinite G
  have hcardFin : Fintype.card (Fin (N ^ 2)) = Fintype.card G := by
    rw [Fintype.card_fin, ← Nat.card_eq_fintype_card, hcard]
  have hiff : Function.Injective (comboFamily N P Q) ↔ Function.Surjective (comboFamily N P Q) :=
    ⟨fun h => ((Fintype.bijective_iff_injective_and_card _).mpr ⟨h, hcardFin⟩).2,
     fun h => ((Fintype.bijective_iff_surjective_and_card _).mpr ⟨h, hcardFin⟩).1⟩
  rw [hiff, ← Set.range_eq_univ, range_comboFamily_eq_closure N P Q hP hQ,
    ← AddSubgroup.coe_top, SetLike.coe_set_eq]

variable (N P Q) in
/-- The `0`-indexed combination is `0`. -/
theorem comboFamily_zero [NeZero (N ^ 2)] : comboFamily N P Q 0 = 0 := by
  simp [comboFamily]

variable (N P Q) in
/-- **[Step D corollary]** If `P, Q` generate `G` (order `N²`), every nonzero-indexed combination
`[a]P + [b]Q` is nonzero — the form consumed by the Y(N) `[YF-⊆]` no-vanishing argument. -/
theorem comboFamily_ne_zero_of_closure_top [Finite G] [NeZero N] [NeZero (N ^ 2)]
    (hP : (N : ℤ) • P = 0) (hQ : (N : ℤ) • Q = 0) (hcard : Nat.card G = N ^ 2)
    (htop : AddSubgroup.closure {P, Q} = ⊤) {i : Fin (N ^ 2)} (hi : i ≠ 0) :
    comboFamily N P Q i ≠ 0 := fun h0 =>
  hi ((comboFamily_injective_iff_closure_top N P Q hP hQ hcard).mpr htop
    (h0.trans (comboFamily_zero N P Q).symm))

end ModularCurves
