/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import ModularCurves.LevelStructure.Factorization
import ModularCurves.Moduli.PullSectionCanonicity
import ModularCurves.ForMathlib.FiniteFlatRigidity

/-!
# The full-level bridge, forward half (T-D8 ⟹, KM 3.7 / 1.4.4 for Γ(N))

**[KM-W0 / T-D8-forward]** If the divisor `Σ_{(a,b) ∈ (ℤ/N)²} [aP + bQ]` EQUALS `E[N]`
as a closed subscheme (the Drinfeld full-level condition of `IsFullLevel`), then at every
geometric point the pulled `P, Q` generate the `N`-torsion: an `N`-killed geometric point
factors through `E[N]` (the kernel property), hence through the divisor (the hypothesis),
and the **exhaustion engine** (`point_eq_section_of_factors`, KM p. 29) pins it as one of
the combination sections `aP + bQ` — a member of the subgroup generated by `P` and `Q`.

This is the forward half of the `T-D8-bridge` register box in `LevelStructure/Basic.lean`
(`fullLevel_divisor_iff_naive_gen`); it lives here because the exhaustion engine
(`LevelStructure/Factorization.lean`) and the divisor base-change leg
(`Moduli/PullSectionCanonicity.lean`) sit above `Basic` in the import order. Note the
hypotheses are WEAKER than the box's: no `N`-invertibility and no killing of `P, Q` is
needed for this direction. The converse (naive generation ⟹ divisor equality) is the
remaining content of the box — see the scope notes on the board (it needs the
divisor↔norm dictionary `isFullSetOfSectionsAlg_iff_fields` (T-D2, proved) or an
étale/reduced-fibre route).
-/

open AlgebraicGeometry CategoryTheory Limits

universe u

namespace ModularCurves

namespace EllipticCurve

variable {S : Scheme.{u}} (E : EllipticCurve S)

/-- **[T-D8-forward] (KM 3.7, Drinfeld ⟹ naive)** If the combination divisor
`Σ_{(a,b)} [aP + bQ]` equals `E[N]`, then every `N`-killed geometric point is a
`ℤ`-combination of the pulled `P, Q`. -/
theorem fullLevel_divisor_forward (N : ℕ) [NeZero N] (P Q : E.Section)
    (hdiv : (RelEffCartierDiv.sectionsDivisor E.π
        (fun i : Fin (N ^ 2) =>
          (((((i : ℕ) % N : ℕ) : ℤ) • P + ((((i : ℕ) / N : ℕ) : ℤ) • Q) :
            E.Point (𝟙 S))))).ideal =
      (E.torsionIdeal N)) :
    ∀ (k : Type u) [Field k] [IsAlgClosed k] (t : Spec (.of k) ⟶ S),
      ∀ x : E.Point t, (N : ℤ) • x = 0 →
        x ∈ AddSubgroup.closure {Point.pull E t P, Point.pull E t Q} := by
  intro k _ _ t x hx
  classical
  set Ps : Fin (N ^ 2) → E.Point (𝟙 S) := fun i =>
    (((i : ℕ) % N : ℕ) : ℤ) • P + (((i : ℕ) / N : ℕ) : ℤ) • Q with hPs
  -- the N-killed point factors through E[N]
  have hxm : x.1 ≫ E.mulByHom N = t ≫ E.zero := by
    have h1 : ((N : ℤ) • x : E.Point t).1 = x.1 ≫ E.mulByHom (N : ℤ) :=
      point_smul_eq_comp_mulBy E t (N : ℤ) x
    have h2 : ((N : ℤ) • x : E.Point t).1 = (0 : E.Point t).1 := by rw [hx]
    have h3 : (0 : E.Point t).1 = t ≫ E.zero := point_zero_val E t
    exact (h1.symm.trans h2).trans h3
  -- hence through the torsion-ideal subscheme, hence through the divisor subscheme
  obtain ⟨e, he⟩ := E.torsionIdeal_subscheme N
  have hfacS : ∃ w : Spec (CommRingCat.of k) ⟶ (E.torsionIdeal N).subscheme,
      w ≫ (E.torsionIdeal N).subschemeι = x.1 := by
    refine ⟨E.pointToTorsion x hxm ≫ e.symm.hom, ?_⟩
    have h4 : e.symm.hom ≫ (E.torsionIdeal N).subschemeι
        = e.symm.hom ≫ e.hom ≫ E.torsionι N := by rw [he]
    rw [Category.assoc, h4, Iso.symm_hom, Iso.inv_hom_id_assoc,
      pointToTorsion_torsionι]
  rw [← hdiv] at hfacS
  -- transport the factoring to the geometric fibre
  have hfacT : ∃ w : Spec (CommRingCat.of k)
      ⟶ ((RelEffCartierDiv.sectionsDivisor E.π Ps).baseChange t).ideal.subscheme,
      w ≫ ((RelEffCartierDiv.sectionsDivisor E.π Ps).baseChange t).ideal.subschemeι
        = (Point.asSection E t x).1 := by
    rw [RelEffCartierDiv.baseChange_ideal]
    refine (AlgebraicGeometry.Scheme.IdealSheafData.exists_factor_comap_iff
      (RelEffCartierDiv.sectionsDivisor E.π Ps).ideal
      (Limits.pullback.fst E.π t) (Point.asSection E t x).1).mpr ?_
    obtain ⟨w, hw⟩ := hfacS
    exact ⟨w, hw.trans (Point.asSection_val_fst E t x).symm⟩
  rw [ModularCurves.sectionsDivisor_baseChange E Ps t] at hfacT
  -- the exhaustion engine over the geometric point
  have hpos' : IsSeparated (E.baseChange t).π ∧
      SmoothOfRelativeDimension 1 (E.baseChange t).π :=
    ⟨inferInstance, (E.baseChange t).smooth⟩
  obtain ⟨-, ⟨V, hV, rfl⟩, hxV, -⟩ :=
    (E.baseChange t).E.isBasis_affineOpens.exists_subset_of_mem_open
      (Set.mem_univ ((Point.asSection E t x).1
        (default : ↑(Spec (CommRingCat.of k))))) isOpen_univ
  obtain ⟨j, hj⟩ := RelEffCartierDiv.point_eq_section_of_factors
    (π := (E.baseChange t).π)
    (fun i => Point.asSection E t (Point.pull E t (Ps i)))
    hpos' (Point.asSection E t x).1 (Point.asSection E t x).2 hfacT ⟨V, hV⟩ hxV
  -- recover the point identity from the section identity
  have hxsec : Point.asSection E t x = Point.asSection E t (Point.pull E t (Ps j)) :=
    Subtype.ext hj
  have hxval : x.1 = (Point.pull E t (Ps j)).1 :=
    ((Point.asSection_val_fst E t x).symm.trans
      (congrArg (fun z => (z : (E.baseChange t).Point (𝟙 _)).1
        ≫ pullback.fst E.π t) hxsec)).trans
      (Point.asSection_val_fst E t (Point.pull E t (Ps j)))
  have hxeq : x = Point.pull E t (Ps j) := Subtype.ext hxval
  -- a pulled combination lies in the closure of the pulled generators
  rw [hxeq, hPs]
  simp only []
  rw [Point.pull_add, Point.pull_zsmul, Point.pull_zsmul]
  exact AddSubgroup.add_mem _
    (AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (by simp)) _)
    (AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (by simp)) _)

/-! ## The backward half (T-D8 ⟸): naive generation ⟹ divisor equality

Route (the v10.302 fork ruling, posted to inbox/STREAM-OMEGA): geometric distinctness of
the `N²` combination sections (generation + the `N²`-count) → comaximal graph ideals
(`sup_ker_eq_top_of_pull_ne`) → ideal-CRT (`torsionIdeal ≤ ∏ ker = divisor ideal`) →
rank rigidity (a closed immersion of finite flat `S`-schemes of equal fibre rank is an
iso). No reducedness hypotheses anywhere. -/

/-- Killed elements absorb `ℤ`-scalars mod `N`. -/
theorem zsmul_emod_of_killed {G : Type*} [AddCommGroup G] {N : ℕ} {x : G}
    (hx : (N : ℤ) • x = 0) (a : ℤ) : a • x = (a.emod N) • x := by
  have hdecomp : a = (N : ℤ) * (a.ediv N) + a.emod N :=
    (Int.mul_ediv_add_emod a N).symm
  conv_lhs => rw [hdecomp]
  rw [add_smul, mul_smul, smul_comm, show ((N : ℤ) • x) = 0 from hx, smul_zero, zero_add]

/-- Any `ℤ`-combination of two `N`-killed points is a value of the `Fin (N²)`-indexed
combination family. -/
theorem exists_combo_index {G : Type*} [AddCommGroup G] (N : ℕ) [NeZero N]
    {P Q : G} (hP : (N : ℤ) • P = 0) (hQ : (N : ℤ) • Q = 0) (a b : ℤ) :
    ∃ i : Fin (N ^ 2),
      (((i : ℕ) % N : ℕ) : ℤ) • P + (((i : ℕ) / N : ℕ) : ℤ) • Q = a • P + b • Q := by
  have hNpos : (0 : ℤ) < N := by exact_mod_cast Nat.pos_of_ne_zero (NeZero.ne N)
  have ha0 : 0 ≤ a.emod N := Int.emod_nonneg a (by exact_mod_cast NeZero.ne N)
  have hb0 : 0 ≤ b.emod N := Int.emod_nonneg b (by exact_mod_cast NeZero.ne N)
  have haN : a.emod N < N := Int.emod_lt_of_pos a hNpos
  have hbN : b.emod N < N := Int.emod_lt_of_pos b hNpos
  have hr₁ : (a.emod N).toNat < N := by omega
  have hr₂ : (b.emod N).toNat < N := by omega
  have hNn : 0 < N := Nat.pos_of_ne_zero (NeZero.ne N)
  have hlt : (a.emod N).toNat + (b.emod N).toNat * N < N ^ 2 := by
    rw [pow_two]
    have h2 : ((b.emod N).toNat + 1) * N ≤ N * N :=
      Nat.mul_le_mul_right N (Nat.succ_le_of_lt hr₂)
    have h3 : ((b.emod N).toNat + 1) * N = (b.emod N).toNat * N + N := by ring
    omega
  refine ⟨⟨(a.emod N).toNat + (b.emod N).toNat * N, hlt⟩, ?_⟩
  have hmod : ((a.emod N).toNat + (b.emod N).toNat * N) % N = (a.emod N).toNat := by
    rw [Nat.add_mul_mod_self_right]
    exact Nat.mod_eq_of_lt hr₁
  have hdiv : ((a.emod N).toNat + (b.emod N).toNat * N) / N = (b.emod N).toNat := by
    rw [Nat.add_mul_div_right _ _ (Nat.pos_of_ne_zero (NeZero.ne N)),
      Nat.div_eq_of_lt hr₁, Nat.zero_add]
  show (((((a.emod N).toNat + (b.emod N).toNat * N : ℕ)) % N : ℕ) : ℤ) • P
      + (((((a.emod N).toNat + (b.emod N).toNat * N : ℕ)) / N : ℕ) : ℤ) • Q
      = a • P + b • Q
  rw [hmod, hdiv, Int.toNat_of_nonneg ha0, Int.toNat_of_nonneg hb0,
    ← zsmul_emod_of_killed hP a, ← zsmul_emod_of_killed hQ b]

/-- Each `Fin (N²)`-combination of two `N`-killed elements is `N`-killed. -/
theorem combo_killed {G : Type*} [AddCommGroup G] (N : ℕ) {P Q : G}
    (hP : (N : ℤ) • P = 0) (hQ : (N : ℤ) • Q = 0) (a b : ℤ) :
    (N : ℤ) • (a • P + b • Q) = 0 := by
  rw [smul_add, smul_comm, hP, smul_zero, smul_comm, hQ, smul_zero, add_zero]

/-- **[S1]** The torsion ideal bounds every combination graph kernel: an `N`-killed
section factors through `E[N]`. -/
theorem torsionIdeal_le_ker_of_killed {P₀ : E.Section} (N : ℕ)
    (hkill : (N : ℤ) • P₀ = 0) :
    E.torsionIdeal N ≤ Scheme.Hom.ker P₀.1 := by
  have hxm : P₀.1 ≫ E.mulByHom N = 𝟙 S ≫ E.zero := by
    have h1 : ((N : ℤ) • P₀ : E.Section).1 = P₀.1 ≫ E.mulByHom (N : ℤ) :=
      point_smul_eq_comp_mulBy E (𝟙 S) (N : ℤ) P₀
    have h2 : ((N : ℤ) • P₀ : E.Section).1 = (0 : E.Section).1 := by rw [hkill]
    have h3 : (0 : E.Section).1 = 𝟙 S ≫ E.zero := point_zero_val E (𝟙 S)
    exact (h1.symm.trans h2).trans h3
  have hfac : P₀.1 = E.pointToTorsion P₀ hxm ≫ E.torsionι N :=
    (E.pointToTorsion_torsionι P₀ hxm).symm
  show (E.torsionι N).ker ≤ Scheme.Hom.ker P₀.1
  rw [hfac]
  exact Scheme.Hom.le_ker_comp _ _

/-- **[CRT]** An ideal below each member of a pairwise-comaximal finite family is below
the product. -/
theorem _root_.Ideal.le_prod_of_pairwise_coprime {R : Type*} [CommRing R] {n : ℕ}
    (I : Fin n → Ideal R) (J : Ideal R) (hle : ∀ i, J ≤ I i)
    (hpair : Pairwise fun i j => I i ⊔ I j = ⊤) :
    J ≤ ∏ i, I i := by
  classical
  induction n with
  | zero => simp
  | succ m ih =>
    rw [Fin.prod_univ_succ]
    have hcop : I 0 ⊔ ∏ i : Fin m, I i.succ = ⊤ :=
      Ideal.sup_prod_eq_top fun i _ => hpair (Fin.succ_ne_zero i).symm
    have hrest : J ≤ ∏ i : Fin m, I i.succ :=
      ih (fun i => I i.succ) (fun i => hle i.succ)
        (fun i j hij => hpair (fun h => hij (Fin.succ_injective _ h)))
    calc J ≤ I 0 ⊓ ∏ i : Fin m, I i.succ := le_inf (hle 0) hrest
      _ = I 0 * ∏ i : Fin m, I i.succ := (Ideal.mul_eq_inf_of_coprime hcop).symm

/-- **[S2 — the counting distinctness]** Under naive generation, the `N²` combination
sections have pairwise distinct pulls at every algebraically closed geometric point:
the combination map surjects onto the `N`-torsion (generation + mod-`N` reduction),
which has exactly `N²` elements (`torsion_geometricFibre_rank_two`), so it is
bijective. -/
theorem combo_pull_ne (N : ℕ) [NeZero N] (hN : NIsInvertible S N) (P Q : E.Section)
    (hP : (N : ℤ) • P = 0) (hQ : (N : ℤ) • Q = 0)
    (hgen : ∀ (k : Type u) [Field k] [IsAlgClosed k] (t : Spec (.of k) ⟶ S),
      ∀ x : E.Point t, (N : ℤ) • x = 0 →
        x ∈ AddSubgroup.closure {Point.pull E t P, Point.pull E t Q})
    (k : Type u) [Field k] [IsAlgClosed k] (t : Spec (CommRingCat.of k) ⟶ S)
    {i j : Fin (N ^ 2)} (hij : i ≠ j) :
    t ≫ ((((i : ℕ) % N : ℕ) : ℤ) • P + (((i : ℕ) / N : ℕ) : ℤ) • Q : E.Section).1
      ≠ t ≫ ((((j : ℕ) % N : ℕ) : ℤ) • P + (((j : ℕ) / N : ℕ) : ℤ) • Q : E.Section).1 := by
  -- the pulled generators are `N`-killed
  have hPk : (N : ℤ) • Point.pull E t P = 0 := by
    rw [← Point.pull_zsmul, hP, Point.pull_zero]
  have hQk : (N : ℤ) • Point.pull E t Q = 0 := by
    rw [← Point.pull_zsmul, hQ, Point.pull_zero]
  -- the combination map into the N-torsion
  set ψ : Fin (N ^ 2) → Submodule.torsionBy ℤ (E.Point t) (N : ℤ) := fun a =>
    ⟨(((a : ℕ) % N : ℕ) : ℤ) • Point.pull E t P
      + (((a : ℕ) / N : ℕ) : ℤ) • Point.pull E t Q,
      (Submodule.mem_torsionBy_iff _ _).mpr (combo_killed N hPk hQk _ _)⟩ with hψ
  -- surjectivity from generation
  have hsurj : Function.Surjective ψ := by
    rintro ⟨x, hx⟩
    have hx' : (N : ℤ) • x = 0 := (Submodule.mem_torsionBy_iff _ _).mp hx
    have hcl := hgen k t x hx'
    rw [AddSubgroup.mem_closure_pair] at hcl
    obtain ⟨a, b, hab⟩ := hcl
    obtain ⟨i₀, hi₀⟩ := exists_combo_index N hPk hQk a b
    exact ⟨i₀, Subtype.ext (hi₀.trans hab)⟩
  -- the count: N-torsion has N² elements
  have hNk : (N : k) ≠ 0 := (nIsInvertible_spec_iff k N).mp (hN.of_hom t)
  obtain ⟨e⟩ := E.torsion_geometricFibre_rank_two N k t hNk
  haveI hfin : Finite (Submodule.torsionBy ℤ (E.Point t) (N : ℤ)) :=
    Finite.of_equiv _ e.symm.toEquiv
  have hcard : Nat.card (Submodule.torsionBy ℤ (E.Point t) (N : ℤ)) = N ^ 2 := by
    rw [Nat.card_congr e.toEquiv, Nat.card_fun, Nat.card_zmod]
    simp [pow_two]
  -- bijectivity
  have hbij : Function.Bijective ψ :=
    (Nat.bijective_iff_surjective_and_card ψ).mpr ⟨hsurj, by
      rw [Nat.card_eq_fintype_card, Fintype.card_fin, hcard]⟩
  -- distinct values, hence distinct underlying morphisms
  intro hcon
  apply hij
  apply hbij.injective
  refine Subtype.ext ?_
  show (((i : ℕ) % N : ℕ) : ℤ) • Point.pull E t P
      + (((i : ℕ) / N : ℕ) : ℤ) • Point.pull E t Q
    = (((j : ℕ) % N : ℕ) : ℤ) • Point.pull E t P
      + (((j : ℕ) / N : ℕ) : ℤ) • Point.pull E t Q
  have hpull : ∀ a : Fin (N ^ 2),
      (((a : ℕ) % N : ℕ) : ℤ) • Point.pull E t P
        + (((a : ℕ) / N : ℕ) : ℤ) • Point.pull E t Q
      = Point.pull E t
          ((((a : ℕ) % N : ℕ) : ℤ) • P + (((a : ℕ) / N : ℕ) : ℤ) • Q) := by
    intro a
    rw [Point.pull_add, Point.pull_zsmul, Point.pull_zsmul]
  rw [hpull i, hpull j]
  exact Subtype.ext hcon

/-- **[T-D8 ⟸, modulo rank rigidity] (KM 3.7, naive ⟹ Drinfeld)** If the pulled `P, Q`
generate the `N`-torsion at every algebraically closed geometric point, the combination
divisor `Σ_{(a,b)} [aP + bQ]` EQUALS `E[N]`. Containment `torsionIdeal ≤ divisor.ideal`
is proven here (comaximal graphs + CRT); the reverse containment is the rank-rigidity
step (both sides finite flat of rank `N²`), tracked as the `[RANK-RIGIDITY]` brick. -/
theorem fullLevel_divisor_backward (N : ℕ) [NeZero N] (hN : NIsInvertible S N)
    (P Q : E.Section) (hP : (N : ℤ) • P = 0) (hQ : (N : ℤ) • Q = 0)
    (hgen : ∀ (k : Type u) [Field k] [IsAlgClosed k] (t : Spec (.of k) ⟶ S),
      ∀ x : E.Point t, (N : ℤ) • x = 0 →
        x ∈ AddSubgroup.closure {Point.pull E t P, Point.pull E t Q}) :
    (RelEffCartierDiv.sectionsDivisor E.π
        (fun i : Fin (N ^ 2) =>
          (((((i : ℕ) % N : ℕ) : ℤ) • P + ((((i : ℕ) / N : ℕ) : ℤ) • Q) :
            E.Point (𝟙 S))))).ideal =
      (E.torsionIdeal N) := by
  set fam : Fin (N ^ 2) → E.Point (𝟙 S) := fun i =>
    (((i : ℕ) % N : ℕ) : ℤ) • P + (((i : ℕ) / N : ℕ) : ℤ) • Q with hfam
  have hpos : IsSeparated E.π ∧ SmoothOfRelativeDimension 1 E.π :=
    ⟨inferInstance, E.smooth⟩
  -- the graph kernels are pairwise comaximal
  have hpair : Pairwise fun i j : Fin (N ^ 2) =>
      Scheme.Hom.ker (fam i).1 ⊔ Scheme.Hom.ker (fam j).1 = ⊤ := by
    intro i j hij
    exact RelEffCartierDiv.sup_ker_eq_top_of_pull_ne (π := E.π) _ _
      (fam i).2 (fam j).2
      (fun k _ _ t => combo_pull_ne E N hN P Q hP hQ hgen k t hij)
  -- each combination is N-killed, so its kernel dominates the torsion ideal
  have hleker : ∀ i : Fin (N ^ 2),
      E.torsionIdeal N ≤ Scheme.Hom.ker (fam i).1 := fun i =>
    torsionIdeal_le_ker_of_killed E N (combo_killed N hP hQ _ _)
  -- the divisor ideal is the product of the graph kernels
  have hDideal : (RelEffCartierDiv.sectionsDivisor E.π fam).ideal
      = ∏ i : Fin (N ^ 2), Scheme.Hom.ker (fam i).1 := by
    rw [RelEffCartierDiv.sectionsDivisor, dif_pos hpos]
  -- CRT: torsionIdeal ≤ the divisor ideal
  have hle : E.torsionIdeal N ≤ (RelEffCartierDiv.sectionsDivisor E.π fam).ideal := by
    rw [hDideal]
    intro U
    have hprodU : ((∏ i : Fin (N ^ 2), Scheme.Hom.ker (fam i).1 :
          Scheme.IdealSheafData E.E)).ideal U
        = ∏ i : Fin (N ^ 2), (Scheme.Hom.ker (fam i).1).ideal U := by
      have h1 : ((∏ i : Fin (N ^ 2), Scheme.Hom.ker (fam i).1 :
            Scheme.IdealSheafData E.E)).ideal
          = ∏ i : Fin (N ^ 2), (Scheme.IdealSheafData.idealMonoidHom E.E)
              (Scheme.Hom.ker (fam i).1) :=
        map_prod (Scheme.IdealSheafData.idealMonoidHom E.E) _ Finset.univ
      rw [show ((∏ i : Fin (N ^ 2), Scheme.Hom.ker (fam i).1 :
            Scheme.IdealSheafData E.E)).ideal U
          = (((∏ i : Fin (N ^ 2), Scheme.Hom.ker (fam i).1 :
            Scheme.IdealSheafData E.E)).ideal) U from rfl, h1, Finset.prod_apply]
      rfl
    rw [hprodU]
    refine Ideal.le_prod_of_pairwise_coprime _ _ (fun i => hleker i U) ?_
    intro i j hij
    have h3 : ((Scheme.Hom.ker (fam i).1 ⊔ Scheme.Hom.ker (fam j).1 :
          Scheme.IdealSheafData E.E)).ideal U
        = (⊤ : Scheme.IdealSheafData E.E).ideal U := by rw [hpair hij]
    rw [Scheme.IdealSheafData.ideal_sup] at h3
    simpa using h3
  -- the reverse containment: rank rigidity (both finite flat lfp of fibre rank N²)
  have hge : (RelEffCartierDiv.sectionsDivisor E.π fam).ideal ≤ E.torsionIdeal N := by
    haveI hfinD := (RelEffCartierDiv.sectionsDivisor E.π fam).finite
    haveI hflatD := (RelEffCartierDiv.sectionsDivisor E.π fam).flat
    haveI hlfpD := (RelEffCartierDiv.sectionsDivisor E.π fam).lfp
    obtain ⟨e, he⟩ := E.torsionIdeal_subscheme N
    have hcompT : (E.torsionIdeal N).subschemeι ≫ E.π = e.hom ≫ E.torsionπ N := by
      rw [← he, Category.assoc, E.torsionι_π]
    have htransport : ∀ (P : MorphismProperty Scheme.{u}) [P.RespectsIso],
        P (E.torsionπ N) → P ((E.torsionIdeal N).subschemeι ≫ E.π) := by
      intro P _ hP
      rw [hcompT, MorphismProperty.cancel_left_of_respectsIso P]
      exact hP
    haveI hfinT : IsFinite ((E.torsionIdeal N).subschemeι ≫ E.π) :=
      htransport @IsFinite (E.torsionπ_isFinite N)
    haveI hflatT : AlgebraicGeometry.Flat ((E.torsionIdeal N).subschemeι ≫ E.π) :=
      htransport @AlgebraicGeometry.Flat (E.torsionπ_flat N)
    haveI hlfpT : LocallyOfFinitePresentation ((E.torsionIdeal N).subschemeι ≫ E.π) :=
      htransport @LocallyOfFinitePresentation
        (MorphismProperty.pullback_snd _ _ (E.mulByHom_locallyOfFinitePresentation N))
    have hrank : ∀ s : ↑S,
        ((RelEffCartierDiv.sectionsDivisor E.π fam).ideal.subschemeι ≫ E.π).finrank s
        = ((E.torsionIdeal N).subschemeι ≫ E.π).finrank s := by
      intro s
      have hD : ((RelEffCartierDiv.sectionsDivisor E.π fam).ideal.subschemeι
            ≫ E.π).finrank s = N ^ 2 :=
        RelEffCartierDiv.sectionsDivisor_degree E.π E.smooth fam s
      have hT : ((E.torsionIdeal N).subschemeι ≫ E.π).finrank s = N ^ 2 := by
        haveI := E.torsionπ_flat N
        haveI := E.torsionπ_isFinite N
        rw [show ((E.torsionIdeal N).subschemeι ≫ E.π).finrank s
            = (e.hom ≫ E.torsionπ N).finrank s from by rw [hcompT],
          Scheme.Hom.finrank_comp_left_of_isIso]
        exact E.torsion_rank N s
      rw [hD, hT]
    exact le_of_eq (ModularCurves.eq_of_le_of_finrank_eq E.π _ _ hle hrank)
  exact le_antisymm hge hle

/-- **[T-D8, the full bridge — KM 3.7 / 1.4.4 for Γ(N)] The Drinfeld full-level divisor
condition is equivalent to naive geometric generation.** This is the content of the
`T-D8-bridge` register box (`LevelStructure/Basic.lean:115`), proven here (above `Basic`
in the import order): forward via the exhaustion engine, backward via counting
distinctness → comaximal graphs → ideal-CRT → rank rigidity. Axiom-clean. -/
theorem fullLevel_divisor_iff_naive_gen' (N : ℕ) [NeZero N] (hN : NIsInvertible S N)
    (P Q : E.Section) (hP : (N : ℤ) • P = 0) (hQ : (N : ℤ) • Q = 0) :
    (RelEffCartierDiv.sectionsDivisor E.π
        (fun i : Fin (N ^ 2) =>
          (((((i : ℕ) % N : ℕ) : ℤ) • P + ((((i : ℕ) / N : ℕ) : ℤ) • Q) :
            E.Point (𝟙 S))))).ideal =
      (E.torsionIdeal N) ↔
      ∀ (k : Type u) [Field k] [IsAlgClosed k] (t : Spec (.of k) ⟶ S),
        ∀ x : E.Point t, (N : ℤ) • x = 0 →
          x ∈ AddSubgroup.closure {Point.pull E t P, Point.pull E t Q} :=
  ⟨fun h => fullLevel_divisor_forward E N P Q h,
    fun h => fullLevel_divisor_backward E N hN P Q hP hQ h⟩

end EllipticCurve

end ModularCurves
