/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import ModularCurves.LevelStructure.Factorization
import ModularCurves.Moduli.PullSectionCanonicity

/-!
# The full-level bridge, forward half (T-D8 ⟹, KM 3.7 / 1.4.4 for Γ(N))

**[KM-W0 / T-D8-forward]** If the divisor `Σ_{(a,b) ∈ (ℤ/N)²} [aP + bQ]` EQUALS `E[N]`
as a closed subscheme (the Drinfeld full-level condition of `IsFullLevel`), then at every
geometric point the pulled `P, Q` generate the `N`-torsion: an `N`-killed geometric point
factors through `E[N]` (the kernel property), hence through the divisor (the hypothesis),
and the **exhaustion engine** (`point_eq_section_of_factors`, KM p. 29) pins it as one of
the combination sections `aP + bQ` — a member of the subgroup generated by `P` and `Q`.

This is the forward half of the `T-D8-bridge` register box in `LevelStructure/Basic.lean`
(`fullLevel_divisor_iff_naive_gen`); it lives here because the exhaustion engine
(`LevelStructure/Factorization.lean`) and the divisor base-change leg
(`Moduli/PullSectionCanonicity.lean`) sit above `Basic` in the import order. Note the
hypotheses are WEAKER than the box's: no `N`-invertibility and no killing of `P, Q` is
needed for this direction. The converse (naive generation ⟹ divisor equality) is the
remaining content of the box — see the scope notes on the board (it needs the
divisor↔norm dictionary `isFullSetOfSectionsAlg_iff_fields` (T-D2, proved) or an
étale/reduced-fibre route).
-/

open AlgebraicGeometry CategoryTheory Limits

universe u

namespace ModularCurves

namespace EllipticCurve

variable {S : Scheme.{u}} (E : EllipticCurve S)

/-- **[T-D8-forward] (KM 3.7, Drinfeld ⟹ naive)** If the combination divisor
`Σ_{(a,b)} [aP + bQ]` equals `E[N]`, then every `N`-killed geometric point is a
`ℤ`-combination of the pulled `P, Q`. -/
theorem fullLevel_divisor_forward (N : ℕ) [NeZero N] (P Q : E.Section)
    (hdiv : (RelEffCartierDiv.sectionsDivisor E.π
        (fun i : Fin (N ^ 2) =>
          (((((i : ℕ) % N : ℕ) : ℤ) • P + ((((i : ℕ) / N : ℕ) : ℤ) • Q) :
            E.Point (𝟙 S))))).ideal =
      (E.torsionIdeal N)) :
    ∀ (k : Type u) [Field k] [IsAlgClosed k] (t : Spec (.of k) ⟶ S),
      ∀ x : E.Point t, (N : ℤ) • x = 0 →
        x ∈ AddSubgroup.closure {Point.pull E t P, Point.pull E t Q} := by
  intro k _ _ t x hx
  classical
  set Ps : Fin (N ^ 2) → E.Point (𝟙 S) := fun i =>
    (((i : ℕ) % N : ℕ) : ℤ) • P + (((i : ℕ) / N : ℕ) : ℤ) • Q with hPs
  -- the N-killed point factors through E[N]
  have hxm : x.1 ≫ E.mulByHom N = t ≫ E.zero := by
    have h1 : ((N : ℤ) • x : E.Point t).1 = x.1 ≫ E.mulByHom (N : ℤ) :=
      point_smul_eq_comp_mulBy E t (N : ℤ) x
    have h2 : ((N : ℤ) • x : E.Point t).1 = (0 : E.Point t).1 := by rw [hx]
    have h3 : (0 : E.Point t).1 = t ≫ E.zero := point_zero_val E t
    exact (h1.symm.trans h2).trans h3
  -- hence through the torsion-ideal subscheme, hence through the divisor subscheme
  obtain ⟨e, he⟩ := E.torsionIdeal_subscheme N
  have hfacS : ∃ w : Spec (CommRingCat.of k) ⟶ (E.torsionIdeal N).subscheme,
      w ≫ (E.torsionIdeal N).subschemeι = x.1 := by
    refine ⟨E.pointToTorsion x hxm ≫ e.symm.hom, ?_⟩
    have h4 : e.symm.hom ≫ (E.torsionIdeal N).subschemeι
        = e.symm.hom ≫ e.hom ≫ E.torsionι N := by rw [he]
    rw [Category.assoc, h4, Iso.symm_hom, Iso.inv_hom_id_assoc,
      pointToTorsion_torsionι]
  rw [← hdiv] at hfacS
  -- transport the factoring to the geometric fibre
  have hfacT : ∃ w : Spec (CommRingCat.of k)
      ⟶ ((RelEffCartierDiv.sectionsDivisor E.π Ps).baseChange t).ideal.subscheme,
      w ≫ ((RelEffCartierDiv.sectionsDivisor E.π Ps).baseChange t).ideal.subschemeι
        = (Point.asSection E t x).1 := by
    rw [RelEffCartierDiv.baseChange_ideal]
    refine (AlgebraicGeometry.Scheme.IdealSheafData.exists_factor_comap_iff
      (RelEffCartierDiv.sectionsDivisor E.π Ps).ideal
      (Limits.pullback.fst E.π t) (Point.asSection E t x).1).mpr ?_
    obtain ⟨w, hw⟩ := hfacS
    exact ⟨w, hw.trans (Point.asSection_val_fst E t x).symm⟩
  rw [ModularCurves.sectionsDivisor_baseChange E Ps t] at hfacT
  -- the exhaustion engine over the geometric point
  have hpos' : IsSeparated (E.baseChange t).π ∧
      SmoothOfRelativeDimension 1 (E.baseChange t).π :=
    ⟨inferInstance, (E.baseChange t).smooth⟩
  obtain ⟨-, ⟨V, hV, rfl⟩, hxV, -⟩ :=
    (E.baseChange t).E.isBasis_affineOpens.exists_subset_of_mem_open
      (Set.mem_univ ((Point.asSection E t x).1
        (default : ↑(Spec (CommRingCat.of k))))) isOpen_univ
  obtain ⟨j, hj⟩ := RelEffCartierDiv.point_eq_section_of_factors
    (π := (E.baseChange t).π)
    (fun i => Point.asSection E t (Point.pull E t (Ps i)))
    hpos' (Point.asSection E t x).1 (Point.asSection E t x).2 hfacT ⟨V, hV⟩ hxV
  -- recover the point identity from the section identity
  have hxsec : Point.asSection E t x = Point.asSection E t (Point.pull E t (Ps j)) :=
    Subtype.ext hj
  have hxval : x.1 = (Point.pull E t (Ps j)).1 :=
    ((Point.asSection_val_fst E t x).symm.trans
      (congrArg (fun z => (z : (E.baseChange t).Point (𝟙 _)).1
        ≫ pullback.fst E.π t) hxsec)).trans
      (Point.asSection_val_fst E t (Point.pull E t (Ps j)))
  have hxeq : x = Point.pull E t (Ps j) := Subtype.ext hxval
  -- a pulled combination lies in the closure of the pulled generators
  rw [hxeq, hPs]
  simp only []
  rw [Point.pull_add, Point.pull_zsmul, Point.pull_zsmul]
  exact AddSubgroup.add_mem _
    (AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (by simp)) _)
    (AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (by simp)) _)

/-! ## The backward half (T-D8 ⟸): naive generation ⟹ divisor equality

Route (the v10.302 fork ruling, posted to inbox/STREAM-OMEGA): geometric distinctness of
the `N²` combination sections (generation + the `N²`-count) → comaximal graph ideals
(`sup_ker_eq_top_of_pull_ne`) → ideal-CRT (`torsionIdeal ≤ ∏ ker = divisor ideal`) →
rank rigidity (a closed immersion of finite flat `S`-schemes of equal fibre rank is an
iso). No reducedness hypotheses anywhere. -/

/-- Killed elements absorb `ℤ`-scalars mod `N`. -/
theorem zsmul_emod_of_killed {G : Type*} [AddCommGroup G] {N : ℕ} {x : G}
    (hx : (N : ℤ) • x = 0) (a : ℤ) : a • x = (a.emod N) • x := by
  have hdecomp : a = (N : ℤ) * (a.ediv N) + a.emod N :=
    (Int.mul_ediv_add_emod a N).symm
  conv_lhs => rw [hdecomp]
  rw [add_smul, mul_smul, smul_comm, show ((N : ℤ) • x) = 0 from hx, smul_zero, zero_add]

/-- Any `ℤ`-combination of two `N`-killed points is a value of the `Fin (N²)`-indexed
combination family. -/
theorem exists_combo_index {G : Type*} [AddCommGroup G] (N : ℕ) [NeZero N]
    {P Q : G} (hP : (N : ℤ) • P = 0) (hQ : (N : ℤ) • Q = 0) (a b : ℤ) :
    ∃ i : Fin (N ^ 2),
      (((i : ℕ) % N : ℕ) : ℤ) • P + (((i : ℕ) / N : ℕ) : ℤ) • Q = a • P + b • Q := by
  have hNpos : (0 : ℤ) < N := by exact_mod_cast Nat.pos_of_ne_zero (NeZero.ne N)
  have ha0 : 0 ≤ a.emod N := Int.emod_nonneg a (by exact_mod_cast NeZero.ne N)
  have hb0 : 0 ≤ b.emod N := Int.emod_nonneg b (by exact_mod_cast NeZero.ne N)
  have haN : a.emod N < N := Int.emod_lt_of_pos a hNpos
  have hbN : b.emod N < N := Int.emod_lt_of_pos b hNpos
  have hr₁ : (a.emod N).toNat < N := by omega
  have hr₂ : (b.emod N).toNat < N := by omega
  have hNn : 0 < N := Nat.pos_of_ne_zero (NeZero.ne N)
  have hlt : (a.emod N).toNat + (b.emod N).toNat * N < N ^ 2 := by
    rw [pow_two]
    have h2 : ((b.emod N).toNat + 1) * N ≤ N * N :=
      Nat.mul_le_mul_right N (Nat.succ_le_of_lt hr₂)
    have h3 : ((b.emod N).toNat + 1) * N = (b.emod N).toNat * N + N := by ring
    omega
  refine ⟨⟨(a.emod N).toNat + (b.emod N).toNat * N, hlt⟩, ?_⟩
  have hmod : ((a.emod N).toNat + (b.emod N).toNat * N) % N = (a.emod N).toNat := by
    rw [Nat.add_mul_mod_self_right]
    exact Nat.mod_eq_of_lt hr₁
  have hdiv : ((a.emod N).toNat + (b.emod N).toNat * N) / N = (b.emod N).toNat := by
    rw [Nat.add_mul_div_right _ _ (Nat.pos_of_ne_zero (NeZero.ne N)),
      Nat.div_eq_of_lt hr₁, Nat.zero_add]
  show (((((a.emod N).toNat + (b.emod N).toNat * N : ℕ)) % N : ℕ) : ℤ) • P
      + (((((a.emod N).toNat + (b.emod N).toNat * N : ℕ)) / N : ℕ) : ℤ) • Q
      = a • P + b • Q
  rw [hmod, hdiv, Int.toNat_of_nonneg ha0, Int.toNat_of_nonneg hb0,
    ← zsmul_emod_of_killed hP a, ← zsmul_emod_of_killed hQ b]

end EllipticCurve

end ModularCurves
