/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import ModularCurves.LevelStructure.Factorization
import ModularCurves.Moduli.PullSectionCanonicity

/-!
# The full-level bridge, forward half (T-D8 ⟹, KM 3.7 / 1.4.4 for Γ(N))

**[KM-W0 / T-D8-forward]** If the divisor `Σ_{(a,b) ∈ (ℤ/N)²} [aP + bQ]` EQUALS `E[N]`
as a closed subscheme (the Drinfeld full-level condition of `IsFullLevel`), then at every
geometric point the pulled `P, Q` generate the `N`-torsion: an `N`-killed geometric point
factors through `E[N]` (the kernel property), hence through the divisor (the hypothesis),
and the **exhaustion engine** (`point_eq_section_of_factors`, KM p. 29) pins it as one of
the combination sections `aP + bQ` — a member of the subgroup generated by `P` and `Q`.

This is the forward half of the `T-D8-bridge` register box in `LevelStructure/Basic.lean`
(`fullLevel_divisor_iff_naive_gen`); it lives here because the exhaustion engine
(`LevelStructure/Factorization.lean`) and the divisor base-change leg
(`Moduli/PullSectionCanonicity.lean`) sit above `Basic` in the import order. Note the
hypotheses are WEAKER than the box's: no `N`-invertibility and no killing of `P, Q` is
needed for this direction. The converse (naive generation ⟹ divisor equality) is the
remaining content of the box — see the scope notes on the board (it needs the
divisor↔norm dictionary `isFullSetOfSectionsAlg_iff_fields` (T-D2, proved) or an
étale/reduced-fibre route).
-/

open AlgebraicGeometry CategoryTheory Limits

universe u

namespace ModularCurves

namespace EllipticCurve

variable {S : Scheme.{u}} (E : EllipticCurve S)

/-- **[T-D8-forward] (KM 3.7, Drinfeld ⟹ naive)** If the combination divisor
`Σ_{(a,b)} [aP + bQ]` equals `E[N]`, then every `N`-killed geometric point is a
`ℤ`-combination of the pulled `P, Q`. -/
theorem fullLevel_divisor_forward (N : ℕ) [NeZero N] (P Q : E.Section)
    (hdiv : (RelEffCartierDiv.sectionsDivisor E.π
        (fun i : Fin (N ^ 2) =>
          (((((i : ℕ) % N : ℕ) : ℤ) • P + ((((i : ℕ) / N : ℕ) : ℤ) • Q) :
            E.Point (𝟙 S))))).ideal =
      (E.torsionIdeal N)) :
    ∀ (k : Type u) [Field k] [IsAlgClosed k] (t : Spec (.of k) ⟶ S),
      ∀ x : E.Point t, (N : ℤ) • x = 0 →
        x ∈ AddSubgroup.closure {Point.pull E t P, Point.pull E t Q} := by
  intro k _ _ t x hx
  classical
  set Ps : Fin (N ^ 2) → E.Point (𝟙 S) := fun i =>
    (((i : ℕ) % N : ℕ) : ℤ) • P + (((i : ℕ) / N : ℕ) : ℤ) • Q with hPs
  -- the N-killed point factors through E[N]
  have hxm : x.1 ≫ E.mulByHom N = t ≫ E.zero := by
    have h1 : ((N : ℤ) • x : E.Point t).1 = x.1 ≫ E.mulByHom (N : ℤ) :=
      point_smul_eq_comp_mulBy E t (N : ℤ) x
    have h2 : ((N : ℤ) • x : E.Point t).1 = (0 : E.Point t).1 := by rw [hx]
    have h3 : (0 : E.Point t).1 = t ≫ E.zero := point_zero_val E t
    exact (h1.symm.trans h2).trans h3
  -- hence through the torsion-ideal subscheme, hence through the divisor subscheme
  obtain ⟨e, he⟩ := E.torsionIdeal_subscheme N
  have hfacS : ∃ w : Spec (CommRingCat.of k) ⟶ (E.torsionIdeal N).subscheme,
      w ≫ (E.torsionIdeal N).subschemeι = x.1 := by
    refine ⟨E.pointToTorsion x hxm ≫ e.symm.hom, ?_⟩
    have h4 : e.symm.hom ≫ (E.torsionIdeal N).subschemeι
        = e.symm.hom ≫ e.hom ≫ E.torsionι N := by rw [he]
    rw [Category.assoc, h4, Iso.symm_hom, Iso.inv_hom_id_assoc,
      pointToTorsion_torsionι]
  rw [← hdiv] at hfacS
  -- transport the factoring to the geometric fibre
  have hfacT : ∃ w : Spec (CommRingCat.of k)
      ⟶ ((RelEffCartierDiv.sectionsDivisor E.π Ps).baseChange t).ideal.subscheme,
      w ≫ ((RelEffCartierDiv.sectionsDivisor E.π Ps).baseChange t).ideal.subschemeι
        = (Point.asSection E t x).1 := by
    rw [RelEffCartierDiv.baseChange_ideal]
    refine (AlgebraicGeometry.Scheme.IdealSheafData.exists_factor_comap_iff
      (RelEffCartierDiv.sectionsDivisor E.π Ps).ideal
      (Limits.pullback.fst E.π t) (Point.asSection E t x).1).mpr ?_
    obtain ⟨w, hw⟩ := hfacS
    exact ⟨w, hw.trans (Point.asSection_val_fst E t x).symm⟩
  rw [ModularCurves.sectionsDivisor_baseChange E Ps t] at hfacT
  -- the exhaustion engine over the geometric point
  have hpos' : IsSeparated (E.baseChange t).π ∧
      SmoothOfRelativeDimension 1 (E.baseChange t).π :=
    ⟨inferInstance, (E.baseChange t).smooth⟩
  obtain ⟨-, ⟨V, hV, rfl⟩, hxV, -⟩ :=
    (E.baseChange t).E.isBasis_affineOpens.exists_subset_of_mem_open
      (Set.mem_univ ((Point.asSection E t x).1
        (default : ↑(Spec (CommRingCat.of k))))) isOpen_univ
  obtain ⟨j, hj⟩ := RelEffCartierDiv.point_eq_section_of_factors
    (π := (E.baseChange t).π)
    (fun i => Point.asSection E t (Point.pull E t (Ps i)))
    hpos' (Point.asSection E t x).1 (Point.asSection E t x).2 hfacT ⟨V, hV⟩ hxV
  -- recover the point identity from the section identity
  have hxsec : Point.asSection E t x = Point.asSection E t (Point.pull E t (Ps j)) :=
    Subtype.ext hj
  have hxval : x.1 = (Point.pull E t (Ps j)).1 :=
    ((Point.asSection_val_fst E t x).symm.trans
      (congrArg (fun z => (z : (E.baseChange t).Point (𝟙 _)).1
        ≫ pullback.fst E.π t) hxsec)).trans
      (Point.asSection_val_fst E t (Point.pull E t (Ps j)))
  have hxeq : x = Point.pull E t (Ps j) := Subtype.ext hxval
  -- a pulled combination lies in the closure of the pulled generators
  rw [hxeq, hPs]
  simp only []
  rw [Point.pull_add, Point.pull_zsmul, Point.pull_zsmul]
  exact AddSubgroup.add_mem _
    (AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (by simp)) _)
    (AddSubgroup.zsmul_mem _ (AddSubgroup.subset_closure (by simp)) _)

end EllipticCurve

end ModularCurves
