import ModularCurves.LevelStructure.ExactOrder
import ModularCurves.LevelStructure.Basic
import Mathlib.LinearAlgebra.Basis.Defs

/-!
# The Cartier-incidence representability block (KM 1.3; expert-review addition)

The core representability engine of KM Ch. 1, added as a first-class phase per the
expert review (2026-07-05): the closed subscheme representing `D' ≤ D`, then equality
of divisors, then "`D` is a subgroup", and from these the `A`-structure/`A`-generator
representability. Reviewer: "Once this exists, exact order and Drinfeld level are
formal."

Verbatim sources in hand (KM preview):

* KM 1.3.5 (book p. 15): "…universal for the relation `D = D'`, in the sense that for
  any `T → S`, `D_T = D'_T` in `C_T` if and only if `T → S` factors through `Z`. The
  subscheme `Z ⊂ S` is defined locally in `S` by `deg(D)` equations, and its formation
  commutes with arbitrary change of base `S' → S`."
* KM 1.3.7 (book pp. 15–16): "Let `C/S` be a smooth curve which is a group-scheme over
  `S`. Let `D` be an effective Cartier divisor in `C/S`, proper over `S`. Then there
  exists a unique closed subscheme `Z ⊂ S` which is universal for the relation '`D` is
  a subgroup' … The subscheme `Z ⊂ S` is defined locally in `S` by
  `1 + deg(D) + (deg(D))²` equations, and its formation commutes with arbitrary change
  of base `S' → S`." — via the three conditions `[e] ≤ D`, `D = inv*(D)`, and
  `[m(P₁,P₂)] ≤ D_W` over `W = D ×_S D` ("the condition that the subset `D(T) ⊂ C(T)`
  always be stable by multiplication").

The mechanism (KM 1.3.5's proof; reviewer's ticket `zero-locus-section-flf-module`):
restrict the section defining `D` to the finite locally free `D'` and set its
coordinates equal to zero in the finite locally free module `H⁰(D', L|_{D'})`.

The general `A`-structure/`A`-generator representability (KM 1.5–1.6) is uniform in a
finite abelian `A`; this file states the two instances the modular-curve programme
consumes (`A = ℤ/N`: the exact-order locus in `E[N]`; `A = (ℤ/N)²`: the full-level
locus in `E[N] ×_S E[N]`), with the general statement recorded as ticket `T-D21`.
-/

open AlgebraicGeometry CategoryTheory Limits

universe u

namespace ModularCurves

section ZeroLocus

variable (R : Type u) [CommRing R] (M : Type u) [AddCommGroup M] [Module R M]

/-- The vanishing ideal of an element `σ` of an `R`-module `M`: the ideal generated by
the values of all linear functionals at `σ` (for `M` finite locally free, locally the
ideal of coordinates of `σ`). `V(sectionVanishingIdeal σ) ⊆ Spec R` is the zero locus
of the section `σ`. Meaningful only for `M` projective/locally free — for `M` with
trivial dual (e.g. `ℤ/2` over `ℤ`) the ideal is junk-`⊥`, matching the fact that the
zero locus is then not closed. Source: KM 1.3.5 proof / reviewer ticket
`zero-locus-section-flf-module`. -/
def sectionVanishingIdeal (σ : M) : Ideal R :=
  Ideal.span (Set.range fun φ : Module.Dual R M => φ σ)

/-- **(T-D13, basis form)** For a basis `b` of `M`, the vanishing ideal of `σ` is
generated by the coordinates of `σ` alone — KM 1.3.5's "set its coordinates equal to
zero", the finitely-many-equations engine behind the `deg D'` / `1 + deg D + (deg D)²`
equation counts of KM 1.3.4/1.3.5/1.3.7.

ADVERSARIAL FIX (2026-07-06): the previous `∀`-functional form was a hypothesis-free
tautology (`Ideal.span_le` unfolds it to itself) that a worker could "discharge"
without producing the load-bearing content; this basis form is the real lemma. -/
theorem sectionVanishingIdeal_eq_span_coord {ι : Type u} (b : Module.Basis ι R M) (σ : M) :
    sectionVanishingIdeal R M σ = Ideal.span (Set.range fun i => b.coord i σ) := by
  refine Submodule.span_eq_span (Set.range_subset_iff.2 fun φ => ?_)
    (Set.range_subset_iff.2 fun i => Ideal.subset_span ⟨b.coord i, rfl⟩)
  have h : φ σ = ∑ i ∈ (b.repr σ).support, b.repr σ i * φ (b i) := by
    conv_lhs => rw [← b.linearCombination_repr σ]
    simp only [Finsupp.linearCombination_apply, Finsupp.sum, map_sum, map_smul, smul_eq_mul]
  exact h ▸ sum_mem fun i _ => Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)

/-- **(T-D27, coordinate descent along a tower)** For `M` a `B`-module and `B` an
`R`-algebra (compatibly, `[IsScalarTower R B M]`), the `R`-vanishing ideal of `σ` is
generated by the `R`-coordinates of the `B`-coordinates of `σ` — KM 1.3.7's "the
vanishing on `W` of a single function is equivalent to the vanishing on `S` of its
coordinates", the `(deg D)²`-equations descent from `W = D ×_S D` to `S`. -/
theorem sectionVanishingIdeal_eq_span_coord_coord {B : Type u} [CommRing B] [Algebra R B]
    [Module B M] [IsScalarTower R B M] {ι κ : Type u} (c : Module.Basis κ R B)
    (b : Module.Basis ι B M) (σ : M) :
    sectionVanishingIdeal R M σ =
      Ideal.span (Set.range fun p : κ × ι => c.coord p.1 (b.coord p.2 σ)) := by
  rw [sectionVanishingIdeal_eq_span_coord R M (c.smulTower b) σ]
  congr 1

end ZeroLocus

section Incidence

variable {C S : Scheme.{u}} {π : C ⟶ S}

namespace RelEffCartierDiv

-- `RelEffCartierDiv.baseChange` now lives in `LevelStructure/CartierDivisor.lean`
-- (moved 2026-07-06 so that `LevelStructure/Basic.lean` can consume it).

/-- `D' ≤ D` for effective divisors: the closed subscheme of `D'` factors through that
of `D` (equivalently, containment of ideal sheaves; equivalently, KM's section-divides
relation). -/
def IsSubdivisor (D' D : RelEffCartierDiv π) : Prop :=
  ∃ j : D'.ideal.subscheme ⟶ D.ideal.subscheme,
    j ≫ D.ideal.subschemeι = D'.ideal.subschemeι

/-- **(T-D14 = KM 1.3.4, incidence `≤`)** For a smooth relative curve and effective
divisors `D, D'` with `D'` proper (= finite) over `S`, there is a closed subscheme
`Z ⊆ S` universal for `D' ≤ D`, cut out locally by `deg D'` equations, compatible with
arbitrary base change. -/
theorem exists_incidenceLocusLE [IsSeparated π] (hsm : SmoothOfRelativeDimension 1 π)
    (D D' : RelEffCartierDiv π) :
    ∃ Z : S.IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = t) ↔
        IsSubdivisor (D'.baseChange t) (D.baseChange t) := by sorry

/-- **(T-D15 = KM 1.3.5, incidence `=`, verbatim source in hand)** As above, universal
for `D_T = D'_T`, cut out locally by `deg D` equations. -/
theorem exists_incidenceLocusEQ [IsSeparated π] (hsm : SmoothOfRelativeDimension 1 π)
    (D D' : RelEffCartierDiv π) :
    ∃ Z : S.IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = t) ↔
        (IsSubdivisor (D'.baseChange t) (D.baseChange t) ∧
         IsSubdivisor (D.baseChange t) (D'.baseChange t)) := by sorry

end RelEffCartierDiv

/-- **(T-D16 = KM 1.3.7, the subgroup-divisor locus, verbatim source in hand with
proof)** For an elliptic curve `E/S` and an effective divisor `D` in `E/S`, there is a
closed subscheme `Z ⊆ S` universal for "`D` is a subgroup", cut out locally by
`1 + deg D + (deg D)²` equations (`[e] ≤ D`; `D = inv*D`; `[m(P₁,P₂)] ≤ D` over
`D ×_S D`), compatible with arbitrary base change. -/
theorem exists_subgroupLocus (E : EllipticCurve S) (D : RelEffCartierDiv E.π) :
    ∃ Z : S.IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = t) ↔
        (D.baseChange t).IsSubgroup (E.baseChange t) := by sorry

/-- **(T-D17 = KM 1.6 for `A = ℤ/N`; the exact-order locus)** There is a closed
subscheme of `E[N]` universal for "the (torsion) point has exact order `N`": a point
of `E` killed by `N` over `t` has exact order `N` (as a section of the base-changed
curve) iff its classifying map to `E[N]` factors through the locus.
Consequence of `exists_subgroupLocus` applied to the universal divisor
`Σₐ [a·P_univ]` over `E[N]` (KM 1.6.1-style bootstrap). -/
theorem exists_exactOrderLocus (E : EllipticCurve S) (N : ℕ) [NeZero N] :
    ∃ Z : (E.torsion N).IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S)
      (P : E.Point t) (hP : P.1 ≫ E.mulByHom N = t ≫ E.zero),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = E.pointToTorsion P hP) ↔
        EllipticCurve.Section.HasExactOrder (E.baseChange t) (EllipticCurve.Point.asSection E t P) N :=
  by sorry

/-- **(T-D18 = KM 1.5–1.6 for `A = (ℤ/N)²`; the full-level locus)** There is a closed
subscheme of `E[N] ×_S E[N]` universal for "the pair is a Drinfeld full level-`N`
structure". Together with the Weil-pairing non-vanishing decomposition this is the
relative representability of `[Γ(N)]` (Loeffler Prop 3.8.2). -/
theorem exists_fullLevelLocus (E : EllipticCurve S) (N : ℕ) [NeZero N] :
    ∃ Z : (pullback (E.torsionπ N) (E.torsionπ N)).IdealSheafData,
      ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S) (P Q : E.Point t)
        (hP : P.1 ≫ E.mulByHom N = t ≫ E.zero)
        (hQ : Q.1 ≫ E.mulByHom N = t ≫ E.zero),
      (∃ h : T ⟶ Z.subscheme,
          h ≫ Z.subschemeι = pullback.lift (E.pointToTorsion P hP)
            (E.pointToTorsion Q hQ) (by simp)) ↔
        (E.baseChange t).IsFullLevel N (EllipticCurve.Point.asSection E t P) (EllipticCurve.Point.asSection E t Q) :=
  by sorry

end Incidence

end ModularCurves
