import ModularCurves.LevelStructure.ExactOrder
import ModularCurves.LevelStructure.Basic
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.Algebra.Module.LocalizedModule.Submodule
import Mathlib.LinearAlgebra.Basis.Defs
import Mathlib.LinearAlgebra.TensorProduct.Basis
import Mathlib.RingTheory.Localization.Module

/-!
# The Cartier-incidence representability block (KM 1.3; expert-review addition)

The core representability engine of KM Ch. 1, added as a first-class phase per the
expert review (2026-07-05): the closed subscheme representing `D' ≤ D`, then equality
of divisors, then "`D` is a subgroup", and from these the `A`-structure/`A`-generator
representability. Reviewer: "Once this exists, exact order and Drinfeld level are
formal."

Verbatim sources in hand (KM preview):

* KM 1.3.5 (book p. 15): "…universal for the relation `D = D'`, in the sense that for
  any `T → S`, `D_T = D'_T` in `C_T` if and only if `T → S` factors through `Z`. The
  subscheme `Z ⊂ S` is defined locally in `S` by `deg(D)` equations, and its formation
  commutes with arbitrary change of base `S' → S`."
* KM 1.3.7 (book pp. 15–16): "Let `C/S` be a smooth curve which is a group-scheme over
  `S`. Let `D` be an effective Cartier divisor in `C/S`, proper over `S`. Then there
  exists a unique closed subscheme `Z ⊂ S` which is universal for the relation '`D` is
  a subgroup' … The subscheme `Z ⊂ S` is defined locally in `S` by
  `1 + deg(D) + (deg(D))²` equations, and its formation commutes with arbitrary change
  of base `S' → S`." — via the three conditions `[e] ≤ D`, `D = inv*(D)`, and
  `[m(P₁,P₂)] ≤ D_W` over `W = D ×_S D` ("the condition that the subset `D(T) ⊂ C(T)`
  always be stable by multiplication").

The mechanism (KM 1.3.5's proof; reviewer's ticket `zero-locus-section-flf-module`):
restrict the section defining `D` to the finite locally free `D'` and set its
coordinates equal to zero in the finite locally free module `H⁰(D', L|_{D'})`.

The general `A`-structure/`A`-generator representability (KM 1.5–1.6) is uniform in a
finite abelian `A`; this file states the two instances the modular-curve programme
consumes (`A = ℤ/N`: the exact-order locus in `E[N]`; `A = (ℤ/N)²`: the full-level
locus in `E[N] ×_S E[N]`), with the general statement recorded as ticket `T-D21`.
-/

open AlgebraicGeometry CategoryTheory Limits

universe u

namespace ModularCurves

section ZeroLocus

variable (R : Type u) [CommRing R] (M : Type u) [AddCommGroup M] [Module R M]

/-- The vanishing ideal of an element `σ` of an `R`-module `M`: the ideal generated by
the values of all linear functionals at `σ` (for `M` finite locally free, locally the
ideal of coordinates of `σ`). `V(sectionVanishingIdeal σ) ⊆ Spec R` is the zero locus
of the section `σ`. Meaningful only for `M` projective/locally free — for `M` with
trivial dual (e.g. `ℤ/2` over `ℤ`) the ideal is junk-`⊥`, matching the fact that the
zero locus is then not closed. Source: KM 1.3.5 proof / reviewer ticket
`zero-locus-section-flf-module`. -/
def sectionVanishingIdeal (σ : M) : Ideal R :=
  Ideal.span (Set.range fun φ : Module.Dual R M => φ σ)

/-- **(T-D13, basis form)** For a basis `b` of `M`, the vanishing ideal of `σ` is
generated by the coordinates of `σ` alone — KM 1.3.5's "set its coordinates equal to
zero", the finitely-many-equations engine behind the `deg D'` / `1 + deg D + (deg D)²`
equation counts of KM 1.3.4/1.3.5/1.3.7.

ADVERSARIAL FIX (2026-07-06): the previous `∀`-functional form was a hypothesis-free
tautology (`Ideal.span_le` unfolds it to itself) that a worker could "discharge"
without producing the load-bearing content; this basis form is the real lemma. -/
theorem sectionVanishingIdeal_eq_span_coord {ι : Type u} (b : Module.Basis ι R M) (σ : M) :
    sectionVanishingIdeal R M σ = Ideal.span (Set.range fun i => b.coord i σ) := by
  refine Submodule.span_eq_span (Set.range_subset_iff.2 fun φ => ?_)
    (Set.range_subset_iff.2 fun i => Ideal.subset_span ⟨b.coord i, rfl⟩)
  have h : φ σ = ∑ i ∈ (b.repr σ).support, b.repr σ i * φ (b i) := by
    conv_lhs => rw [← b.linearCombination_repr σ]
    simp only [Finsupp.linearCombination_apply, Finsupp.sum, map_sum, map_smul, smul_eq_mul]
  exact h ▸ sum_mem fun i _ => Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)

/-- **(T-D27, coordinate descent along a tower)** For `M` a `B`-module and `B` an
`R`-algebra (compatibly, `[IsScalarTower R B M]`), the `R`-vanishing ideal of `σ` is
generated by the `R`-coordinates of the `B`-coordinates of `σ` — KM 1.3.7's "the
vanishing on `W` of a single function is equivalent to the vanishing on `S` of its
coordinates", the `(deg D)²`-equations descent from `W = D ×_S D` to `S`. -/
theorem sectionVanishingIdeal_eq_span_coord_coord {B : Type u} [CommRing B] [Algebra R B]
    [Module B M] [IsScalarTower R B M] {ι κ : Type u} (c : Module.Basis κ R B)
    (b : Module.Basis ι B M) (σ : M) : sectionVanishingIdeal R M σ =
      Ideal.span (Set.range fun p : κ × ι => c.coord p.1 (b.coord p.2 σ)) :=
  sectionVanishingIdeal_eq_span_coord R M (c.smulTower b) σ

open TensorProduct in
/-- **(T-D14c, base-change vanishing bridge)** Finitely many elements of a free
`R`-algebra all die in the base change `A ⊗[R] B` iff the ideal of all their
coordinates is killed by `R → A` — KM 1.3.4's "the condition `ℓ = 0` is represented
by the simultaneous vanishing of `r₁,…,r_{d′}`", the T-point universality engine of
the incidence loci. -/
theorem forall_one_tmul_eq_zero_iff_span_coord_le_ker {A B : Type u} [CommRing A]
    [CommRing B] [Algebra R A] [Algebra R B] {ι κ : Type u} (b : Module.Basis ι R B)
    (g : κ → B) :
    (∀ j, (1 : A) ⊗ₜ[R] g j = (0 : A ⊗[R] B)) ↔
      Ideal.span (Set.range fun p : κ × ι => b.coord p.2 (g p.1)) ≤
        RingHom.ker (algebraMap R A) := by
  rw [Ideal.span_le]
  constructor
  · rintro h _ ⟨⟨j, i⟩, rfl⟩
    have h0 := congrArg ((b.baseChange A).repr · i) (h j)
    simpa [Module.Basis.baseChange_repr_tmul, Algebra.algebraMap_eq_smul_one] using h0
  · intro h j
    have hrepr : ∀ i, (b.baseChange A).repr ((1 : A) ⊗ₜ[R] g j) i = 0 := by
      intro i
      have hmem : b.coord i (g j) ∈ RingHom.ker (algebraMap R A) := h ⟨(j, i), rfl⟩
      rw [RingHom.mem_ker] at hmem
      simpa [Module.Basis.baseChange_repr_tmul, Algebra.algebraMap_eq_smul_one] using hmem
    refine (b.baseChange A).repr.injective ?_
    rw [map_zero]
    exact Finsupp.ext hrepr

end ZeroLocus

section SubmoduleVanishing

variable {R : Type u} [CommRing R] {M : Type u} [AddCommGroup M] [Module R M]

variable (R M) in
/-- The vanishing ideal of a submodule: the ideal generated by all values of all
linear functionals on all elements of the submodule. This is the basis-free form of
KM 1.3.4's "coordinates" — on free pieces it is the coordinate ideal
(`sectionVanishingIdeal_eq_span_coord`), but it is defined globally, which is what
makes the incidence locus glue. -/
def submoduleVanishingIdeal (J : Submodule R M) : Ideal R :=
  ⨆ g : J, sectionVanishingIdeal R M g

theorem sectionVanishingIdeal_le_submoduleVanishingIdeal {J : Submodule R M} {g : M}
    (hg : g ∈ J) :
    sectionVanishingIdeal R M g ≤ submoduleVanishingIdeal R M J :=
  le_iSup (fun g : J => sectionVanishingIdeal R M g.1) ⟨g, hg⟩

theorem apply_mem_submoduleVanishingIdeal {J : Submodule R M} {g : M} (hg : g ∈ J)
    (φ : Module.Dual R M) : φ g ∈ submoduleVanishingIdeal R M J :=
  sectionVanishingIdeal_le_submoduleVanishingIdeal hg (Ideal.subset_span ⟨φ, rfl⟩)

open IsLocalizedModule in
/-- **(T-D14c-0, gluing keystone)** The vanishing ideal of a submodule commutes with
localization when the ambient module is finitely presented (so that linear functionals
localize, `Module.FinitePresentation.isLocalizedModule_mapExtendScalars`). This is
what glues the affine-local incidence ideals into an ideal sheaf on the base. -/
theorem submoduleVanishingIdeal_localized {Rₛ Nₛ : Type u} [CommRing Rₛ] [Algebra R Rₛ]
    [AddCommGroup Nₛ] [Module R Nₛ] [Module Rₛ Nₛ] [IsScalarTower R Rₛ Nₛ]
    (S : Submonoid R) [IsLocalization S Rₛ] (f : M →ₗ[R] Nₛ) [IsLocalizedModule S f]
    [Module.FinitePresentation R M] (J : Submodule R M) :
    (submoduleVanishingIdeal R M J).map (algebraMap R Rₛ) =
      submoduleVanishingIdeal Rₛ Nₛ (J.localized' Rₛ S f) := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    refine iSup_le fun g => Ideal.span_le.2 ?_
    rintro _ ⟨φ, rfl⟩
    have key : algebraMap R Rₛ (φ g.1) =
        (mapExtendScalars S f (Algebra.linearMap R Rₛ) Rₛ φ) (f g.1) := by
      simp
    show φ g.1 ∈ Ideal.comap (algebraMap R Rₛ) _
    rw [Ideal.mem_comap, key]
    exact apply_mem_submoduleVanishingIdeal
      ((Submodule.mem_localized' _ _ _ _ _).mpr ⟨g.1, g.2, 1, by simp⟩) _
  · refine iSup_le fun y => Ideal.span_le.2 ?_
    rintro _ ⟨ψ, rfl⟩
    obtain ⟨m, hm, s, hy⟩ := y.2
    obtain ⟨⟨φ, s₂⟩, hφ⟩ := IsLocalizedModule.surj S
      (mapExtendScalars S f (Algebra.linearMap R Rₛ) Rₛ) ψ
    dsimp only at hφ
    have hunit : ∀ (t : S) (x : Rₛ), x ∈ (submoduleVanishingIdeal R M J).map
        (algebraMap R Rₛ) ↔ algebraMap R Rₛ t * x ∈ (submoduleVanishingIdeal R M J).map
        (algebraMap R Rₛ) :=
      fun t x => (Ideal.unit_mul_mem_iff_mem _ (IsLocalization.map_units Rₛ t)).symm
    have h1 : algebraMap R Rₛ s * ψ y.1 = ψ (f m) := by
      rw [← hy, ← Algebra.smul_def, ← LinearMap.map_smul_of_tower,
        ← Submonoid.smul_def, IsLocalizedModule.mk'_cancel']
    have h2 : algebraMap R Rₛ s₂ * ψ (f m) = algebraMap R Rₛ (φ m) := by
      rw [← Algebra.smul_def, ← LinearMap.smul_apply, ← Submonoid.smul_def, hφ]
      simp
    show ψ y.1 ∈ Ideal.map (algebraMap R Rₛ) (submoduleVanishingIdeal R M J)
    rw [hunit s₂ _, hunit s _, mul_left_comm, h1, h2]
    exact Ideal.mem_map_of_mem _ (apply_mem_submoduleVanishingIdeal hm φ)

open IsLocalizedModule in
/-- Localizing an ideal of an `R`-algebra `A` (viewed as an `R`-submodule) into the
localization `Af` of `A` at the image monoid is the pushforward ideal, restricted:
the tower version of `Ideal.localized'_eq_map`. -/
theorem localized'_restrictScalars_eq_restrictScalars_map
    {R Rf A Af : Type u} [CommRing R] [CommRing Rf] [CommRing A] [CommRing Af]
    [Algebra R Rf] [Algebra R A] [Algebra A Af] [Algebra R Af] [Algebra Rf Af]
    [IsScalarTower R A Af] [IsScalarTower R Rf Af]
    (S : Submonoid R) [IsLocalization S Rf]
    [IsLocalization (Algebra.algebraMapSubmonoid A S) Af]
    [IsLocalizedModule S (IsScalarTower.toAlgHom R A Af).toLinearMap]
    (J : Ideal A) :
    Submodule.localized' Rf S (IsScalarTower.toAlgHom R A Af).toLinearMap
        (J.restrictScalars R) =
      (J.map (algebraMap A Af)).restrictScalars Rf := by
  ext x
  rw [Submodule.mem_localized', Submodule.restrictScalars_mem,
    IsLocalization.mem_map_algebraMap_iff (Algebra.algebraMapSubmonoid A S)]
  constructor
  · rintro ⟨m, hm, s, rfl⟩
    refine ⟨⟨⟨m, hm⟩, ⟨algebraMap R A s, s, s.2, rfl⟩⟩, ?_⟩
    have h1 : (mk' (IsScalarTower.toAlgHom R A Af).toLinearMap m s : Af) *
        algebraMap A Af (algebraMap R A s) = algebraMap A Af m := by
      rw [← IsScalarTower.algebraMap_apply, mul_comm, ← Algebra.smul_def,
        ← Submonoid.smul_def, mk'_cancel']
      rfl
    exact h1
  · rintro ⟨⟨⟨j, hj⟩, ⟨t, ⟨s, hs, rfl⟩⟩⟩, hx⟩
    refine ⟨j, hj, ⟨s, hs⟩, ?_⟩
    rw [mk'_eq_iff]
    show algebraMap A Af j = _
    rw [Submonoid.smul_def, Algebra.smul_def, IsScalarTower.algebraMap_apply R A Af, ← hx]
    ring

end SubmoduleVanishing

section VanishingLocus

variable {W S : Scheme.{u}} (p : W ⟶ S) [IsFinite p] [Flat p]
  [LocallyOfFinitePresentation p] (E : W.IdealSheafData)

/-- The preimage of an affine open under a finite (hence affine) morphism, as an
affine open. -/
def affinePreimage (U : S.affineOpens) : W.affineOpens :=
  ⟨p ⁻¹ᵁ U.1, U.2.preimage p⟩

/-- **(T-D14c-1)** The vanishing locus on `S` of an ideal sheaf `E` on a scheme `W`
finite locally free over `S`: over an affine `U ⊆ S` it is the vanishing ideal of the
sections of `E` inside the finite locally free `Γ(S, U)`-module `Γ(W, p⁻¹U)`. This is
KM 1.3.4's locus of "simultaneous vanishing of the coordinates", in the basis-free
form; its universal property is `vanishingLocus_le_ker_iff` (T-D14c-2). -/
noncomputable def vanishingLocus : S.IdealSheafData where
  ideal U :=
    letI := ((p.app U.1).hom).toAlgebra
    submoduleVanishingIdeal Γ(S, U.1) Γ(W, p ⁻¹ᵁ U.1)
      ((E.ideal ⟨p ⁻¹ᵁ U.1, U.2.preimage p⟩).restrictScalars Γ(S, U.1))
  map_ideal_basicOpen U f := by
    letI := ((p.app U.1).hom).toAlgebra
    letI := ((p.app (S.basicOpen f)).hom).toAlgebra
    letI := ((S.presheaf.map (homOfLE <| S.basicOpen_le f).op).hom).toAlgebra
    letI := ((W.presheaf.map (homOfLE
      (show p ⁻¹ᵁ S.basicOpen f ≤ p ⁻¹ᵁ U.1 from
        fun _ hx => S.basicOpen_le f hx)).op).hom).toAlgebra
    letI := ((p.appLE U.1 (p ⁻¹ᵁ S.basicOpen f)
      (show p ⁻¹ᵁ S.basicOpen f ≤ p ⁻¹ᵁ U.1 from
        fun _ hx => S.basicOpen_le f hx)).hom).toAlgebra
    haveI : IsScalarTower Γ(S, U.1) Γ(S, S.basicOpen f) Γ(W, p ⁻¹ᵁ S.basicOpen f) :=
      IsScalarTower.of_algebraMap_eq' (by
        rw [RingHom.algebraMap_toAlgebra, RingHom.algebraMap_toAlgebra,
          RingHom.algebraMap_toAlgebra, ← CommRingCat.hom_comp]
        simp only [Scheme.Hom.app_eq_appLE, Scheme.Hom.map_appLE, Scheme.Hom.appLE_map])
    haveI : IsScalarTower Γ(S, U.1) Γ(W, p ⁻¹ᵁ U.1) Γ(W, p ⁻¹ᵁ S.basicOpen f) :=
      IsScalarTower.of_algebraMap_eq' (by
        rw [RingHom.algebraMap_toAlgebra, RingHom.algebraMap_toAlgebra,
          RingHom.algebraMap_toAlgebra, ← CommRingCat.hom_comp]
        simp only [Scheme.Hom.app_eq_appLE, Scheme.Hom.map_appLE, Scheme.Hom.appLE_map])
    haveI hfin : Module.Finite Γ(S, U.1) Γ(W, p ⁻¹ᵁ U.1) := p.finite_app U.1 U.2
    haveI hfp : RingHom.FinitePresentation
        (p.appLE U.1 (p ⁻¹ᵁ U.1) le_rfl).hom :=
      HasRingHomProperty.appLE @LocallyOfFinitePresentation p ‹_› U
        ⟨p ⁻¹ᵁ U.1, U.2.preimage p⟩ le_rfl
    rw [← Scheme.Hom.app_eq_appLE] at hfp
    haveI : Algebra.FinitePresentation Γ(S, U.1) Γ(W, p ⁻¹ᵁ U.1) := hfp
    haveI : Module.FinitePresentation Γ(S, U.1) Γ(W, p ⁻¹ᵁ U.1) :=
      Module.FinitePresentation.of_finite_of_finitePresentation _ _
    haveI hSloc : IsLocalization.Away f Γ(S, S.basicOpen f) :=
      U.2.isLocalization_basicOpen f
    haveI hWloc := (U.2.preimage p).isLocalization_of_eq_basicOpen
      (algebraMap Γ(S, U.1) Γ(W, p ⁻¹ᵁ U.1) f)
      (homOfLE (show p ⁻¹ᵁ S.basicOpen f ≤ p ⁻¹ᵁ U.1 from
        fun _ hx => S.basicOpen_le f hx))
      (by rw [Scheme.preimage_basicOpen, RingHom.algebraMap_toAlgebra])
    haveI : IsLocalizedModule (Submonoid.powers f)
        (IsScalarTower.toAlgHom Γ(S, U.1) Γ(W, p ⁻¹ᵁ U.1)
          Γ(W, p ⁻¹ᵁ S.basicOpen f)).toLinearMap := by
      haveI : IsLocalization (Algebra.algebraMapSubmonoid (R := Γ(S, U.1))
          Γ(W, p ⁻¹ᵁ U.1) (Submonoid.powers f)) Γ(W, p ⁻¹ᵁ S.basicOpen f) := by
        rw [show Algebra.algebraMapSubmonoid (R := Γ(S, U.1)) Γ(W, p ⁻¹ᵁ U.1)
            (Submonoid.powers f) = Submonoid.powers
              (algebraMap Γ(S, U.1) Γ(W, p ⁻¹ᵁ U.1) f) from
          Submonoid.map_powers _ f]
        exact hWloc
      infer_instance
    have hglue := submoduleVanishingIdeal_localized (Rₛ := Γ(S, S.basicOpen f))
      (Submonoid.powers f)
      (IsScalarTower.toAlgHom Γ(S, U.1) Γ(W, p ⁻¹ᵁ U.1)
        Γ(W, p ⁻¹ᵁ S.basicOpen f)).toLinearMap
      ((E.ideal ⟨p ⁻¹ᵁ U.1, U.2.preimage p⟩).restrictScalars Γ(S, U.1))
    rw [localized'_restrictScalars_eq_restrictScalars_map, RingHom.algebraMap_toAlgebra,
      RingHom.algebraMap_toAlgebra,
      E.map_ideal' (U := ⟨p ⁻¹ᵁ S.basicOpen f, (S.affineBasicOpen f).2.preimage p⟩)
        (V := ⟨p ⁻¹ᵁ U.1, U.2.preimage p⟩)] at hglue
    exact hglue

/-- **(T-D14c-i, free cover)** A finite flat finitely-presented morphism has free
sections over an affine neighbourhood of every point of the base: shrink any affine
to a basic open where the (finite locally free) pushforward module trivialises. -/
theorem exists_affineOpen_mem_free (s : S) :
    ∃ U : S.affineOpens, s ∈ U.1 ∧
      (letI := ((p.app U.1).hom).toAlgebra
       Module.Free Γ(S, U.1) Γ(W, p ⁻¹ᵁ U.1)) := by
  sorry

/-- `≤ (ker f)` is a pointwise condition over all affine opens — no quasi-compactness
needed, since `Scheme.Hom.ker` is the `ofIdeals`-closure of the sectionwise kernels. -/
theorem le_ker_iff_forall {X Y : Scheme.{u}} (I : Y.IdealSheafData) (f : X ⟶ Y) :
    I ≤ f.ker ↔ ∀ U : Y.affineOpens, I.ideal U ≤ RingHom.ker (f.app U.1).hom :=
  Scheme.IdealSheafData.le_ofIdeals_iff

/-- **(T-D14c-2, universal property of the vanishing locus)** `T → S` kills the
vanishing locus of `E` iff `E` pulls back to the zero ideal sheaf on the base change
of `W`. Combined with `exists_factor_subschemeι_iff`, `isSubdivisor_iff_le`,
`baseChange_ideal` and the `map_bot` Galois reduction, this is the whole content of
KM 1.3.4. -/
theorem vanishingLocus_le_ker_iff {T : Scheme.{u}} (t : T ⟶ S) :
    vanishingLocus p E ≤ t.ker ↔ E.comap (pullback.snd t p) = ⊥ := by
  rw [(Scheme.IdealSheafData.map_gc (pullback.snd t p)).l_eq_bot,
    Scheme.IdealSheafData.map_bot]
  sorry

end VanishingLocus

section Incidence

variable {C S : Scheme.{u}} {π : C ⟶ S}

namespace RelEffCartierDiv

-- `RelEffCartierDiv.baseChange` now lives in `LevelStructure/CartierDivisor.lean`
-- (moved 2026-07-06 so that `LevelStructure/Basic.lean` can consume it).

/-- `D' ≤ D` for effective divisors: the closed subscheme of `D'` factors through that
of `D` (equivalently, containment of ideal sheaves; equivalently, KM's section-divides
relation). -/
def IsSubdivisor (D' D : RelEffCartierDiv π) : Prop :=
  ∃ j : D'.ideal.subscheme ⟶ D.ideal.subscheme,
    j ≫ D.ideal.subschemeι = D'.ideal.subschemeι

/-- **(T-D14a)** The subscheme-factorization form of `D' ≤ D` is ideal-sheaf
containment (KM 1.3.1's `I(D) ⊆ I(D')` dictionary — the effective divisor `D'` is
larger exactly when its ideal is smaller). -/
theorem isSubdivisor_iff_le (D' D : RelEffCartierDiv π) :
    IsSubdivisor D' D ↔ D.ideal ≤ D'.ideal := by
  constructor
  · rintro ⟨j, hj⟩
    have h := j.le_ker_comp D.ideal.subschemeι
    rwa [hj, Scheme.IdealSheafData.ker_subschemeι,
      Scheme.IdealSheafData.ker_subschemeι] at h
  · intro h
    exact ⟨Scheme.IdealSheafData.inclusion h, Scheme.IdealSheafData.inclusion_subschemeι h⟩


/-- **(T-D14a′)** A morphism factors through the closed subscheme of an ideal sheaf
iff the ideal is contained in its kernel — the object-level unpacking of mathlib's
`kerAdjunction`, in the form the incidence loci consume. -/
theorem _root_.ModularCurves.exists_factor_subschemeι_iff {T : Scheme.{u}}
    (Z : S.IdealSheafData) (t : T ⟶ S) :
    (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = t) ↔ Z ≤ t.ker := by
  constructor
  · rintro ⟨h, rfl⟩
    simpa using h.le_ker_comp Z.subschemeι
  · intro hZ
    exact ⟨t.toImage ≫ Scheme.IdealSheafData.inclusion hZ, by
      rw [Category.assoc, Scheme.IdealSheafData.inclusion_subschemeι,
        Scheme.Hom.toImage_imageι]⟩

/-- **(T-D14 = KM 1.3.4, incidence `≤`)** For a smooth relative curve and effective
divisors `D, D'` with `D'` proper (= finite) over `S`, there is a closed subscheme
`Z ⊆ S` universal for `D' ≤ D`, cut out locally by `deg D'` equations, compatible with
arbitrary base change. -/
theorem exists_incidenceLocusLE [IsSeparated π] (hsm : SmoothOfRelativeDimension 1 π)
    (D D' : RelEffCartierDiv π) :
    ∃ Z : S.IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = t) ↔
        IsSubdivisor (D'.baseChange t) (D.baseChange t) := by sorry

/-- **(T-D15 = KM 1.3.5, incidence `=`, verbatim source in hand)** As above, universal
for `D_T = D'_T`, cut out locally by `deg D` equations. -/
theorem exists_incidenceLocusEQ [IsSeparated π] (hsm : SmoothOfRelativeDimension 1 π)
    (D D' : RelEffCartierDiv π) :
    ∃ Z : S.IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = t) ↔
        (IsSubdivisor (D'.baseChange t) (D.baseChange t) ∧
         IsSubdivisor (D.baseChange t) (D'.baseChange t)) := by sorry

end RelEffCartierDiv

/-- **(T-D16 = KM 1.3.7, the subgroup-divisor locus, verbatim source in hand with
proof)** For an elliptic curve `E/S` and an effective divisor `D` in `E/S`, there is a
closed subscheme `Z ⊆ S` universal for "`D` is a subgroup", cut out locally by
`1 + deg D + (deg D)²` equations (`[e] ≤ D`; `D = inv*D`; `[m(P₁,P₂)] ≤ D` over
`D ×_S D`), compatible with arbitrary base change. -/
theorem exists_subgroupLocus (E : EllipticCurve S) (D : RelEffCartierDiv E.π) :
    ∃ Z : S.IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = t) ↔
        (D.baseChange t).IsSubgroup (E.baseChange t) := by sorry

/-- **(T-D17 = KM 1.6 for `A = ℤ/N`; the exact-order locus)** There is a closed
subscheme of `E[N]` universal for "the (torsion) point has exact order `N`": a point
of `E` killed by `N` over `t` has exact order `N` (as a section of the base-changed
curve) iff its classifying map to `E[N]` factors through the locus.
Consequence of `exists_subgroupLocus` applied to the universal divisor
`Σₐ [a·P_univ]` over `E[N]` (KM 1.6.1-style bootstrap). -/
theorem exists_exactOrderLocus (E : EllipticCurve S) (N : ℕ) [NeZero N] :
    ∃ Z : (E.torsion N).IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S)
      (P : E.Point t) (hP : P.1 ≫ E.mulByHom N = t ≫ E.zero),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = E.pointToTorsion P hP) ↔
        EllipticCurve.Section.HasExactOrder (E.baseChange t) (EllipticCurve.Point.asSection E t P) N :=
  by sorry

/-- **(T-D18 = KM 1.5–1.6 for `A = (ℤ/N)²`; the full-level locus)** There is a closed
subscheme of `E[N] ×_S E[N]` universal for "the pair is a Drinfeld full level-`N`
structure". Together with the Weil-pairing non-vanishing decomposition this is the
relative representability of `[Γ(N)]` (Loeffler Prop 3.8.2). -/
theorem exists_fullLevelLocus (E : EllipticCurve S) (N : ℕ) [NeZero N] :
    ∃ Z : (pullback (E.torsionπ N) (E.torsionπ N)).IdealSheafData,
      ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S) (P Q : E.Point t)
        (hP : P.1 ≫ E.mulByHom N = t ≫ E.zero)
        (hQ : Q.1 ≫ E.mulByHom N = t ≫ E.zero),
      (∃ h : T ⟶ Z.subscheme,
          h ≫ Z.subschemeι = pullback.lift (E.pointToTorsion P hP)
            (E.pointToTorsion Q hQ) (by simp)) ↔
        (E.baseChange t).IsFullLevel N (EllipticCurve.Point.asSection E t P) (EllipticCurve.Point.asSection E t Q) :=
  by sorry

end Incidence

end ModularCurves
