import ModularCurves.LevelStructure.ExactOrder
import ModularCurves.LevelStructure.Basic

/-!
# The Cartier-incidence representability block (KM 1.3; expert-review addition)

The core representability engine of KM Ch. 1, added as a first-class phase per the
expert review (2026-07-05): the closed subscheme representing `D' ≤ D`, then equality
of divisors, then "`D` is a subgroup", and from these the `A`-structure/`A`-generator
representability. Reviewer: "Once this exists, exact order and Drinfeld level are
formal."

Verbatim sources in hand (KM preview):

* KM 1.3.5 (book p. 15): "…universal for the relation `D = D'`, in the sense that for
  any `T → S`, `D_T = D'_T` in `C_T` if and only if `T → S` factors through `Z`. The
  subscheme `Z ⊂ S` is defined locally in `S` by `deg(D)` equations, and its formation
  commutes with arbitrary change of base `S' → S`."
* KM 1.3.7 (book pp. 15–16): "Let `C/S` be a smooth curve which is a group-scheme over
  `S`. Let `D` be an effective Cartier divisor in `C/S`, proper over `S`. Then there
  exists a unique closed subscheme `Z ⊂ S` which is universal for the relation '`D` is
  a subgroup' … The subscheme `Z ⊂ S` is defined locally in `S` by
  `1 + deg(D) + (deg(D))²` equations, and its formation commutes with arbitrary change
  of base `S' → S`." — via the three conditions `[e] ≤ D`, `D = inv*(D)`, and
  `[m(P₁,P₂)] ≤ D_W` over `W = D ×_S D` ("the condition that the subset `D(T) ⊂ C(T)`
  always be stable by multiplication").

The mechanism (KM 1.3.5's proof; reviewer's ticket `zero-locus-section-flf-module`):
restrict the section defining `D` to the finite locally free `D'` and set its
coordinates equal to zero in the finite locally free module `H⁰(D', L|_{D'})`.

The general `A`-structure/`A`-generator representability (KM 1.5–1.6) is uniform in a
finite abelian `A`; this file states the two instances the modular-curve programme
consumes (`A = ℤ/N`: the exact-order locus in `E[N]`; `A = (ℤ/N)²`: the full-level
locus in `E[N] ×_S E[N]`), with the general statement recorded as ticket `T-D21`.
-/

open AlgebraicGeometry CategoryTheory Limits

universe u

namespace ModularCurves

section ZeroLocus

variable (R : Type u) [CommRing R] (M : Type u) [AddCommGroup M] [Module R M]

/-- The vanishing ideal of an element `σ` of an `R`-module `M`: the ideal generated by
the values of all linear functionals at `σ` (for `M` finite locally free, locally the
ideal of coordinates of `σ`). `V(sectionVanishingIdeal σ) ⊆ Spec R` is the zero locus
of the section `σ`. Source: KM 1.3.5 proof / reviewer ticket
`zero-locus-section-flf-module`. -/
def sectionVanishingIdeal (σ : M) : Ideal R :=
  Ideal.span (Set.range fun φ : Module.Dual R M => φ σ)

/-- **(T-D13)** Universal property of the zero locus for finite free modules: a ring
map `f : R →+* A` kills every coordinate of `σ` iff it kills the vanishing ideal.
("Set its coordinates equal to zero.") -/
theorem sectionVanishingIdeal_spec [Module.Finite R M] [Module.Free R M] (σ : M)
    (A : Type u) [CommRing A] (f : R →+* A) :
    (∀ φ : Module.Dual R M, f (φ σ) = 0) ↔
      sectionVanishingIdeal R M σ ≤ RingHom.ker f := by sorry

end ZeroLocus

section Incidence

variable {C S : Scheme.{u}} {π : C ⟶ S}

namespace RelEffCartierDiv

/-- Base change of a relative effective Cartier divisor along `t : T ⟶ S`: the ideal
sheaf of the base-changed closed subscheme `D ×_S T ↪ C ×_S T` (kernel ideal of the
pulled-back closed immersion), as a divisor in the base-changed curve (structure
morphism `pullback.snd π t`). Finiteness/flatness/finite presentation are base-change
stability, ticket `T-D12`; formation is functorial (KM 1.1). -/
noncomputable def baseChange (D : RelEffCartierDiv π) {T : Scheme.{u}} (t : T ⟶ S) :
    RelEffCartierDiv (pullback.snd π t) where
  ideal := (pullback.snd D.ideal.subschemeι (pullback.fst π t)).ker
  finite := by sorry
  flat := by sorry
  lfp := by sorry

/-- `D' ≤ D` for effective divisors: the closed subscheme of `D'` factors through that
of `D` (equivalently, containment of ideal sheaves; equivalently, KM's section-divides
relation). -/
def IsSubdivisor (D' D : RelEffCartierDiv π) : Prop :=
  ∃ j : D'.ideal.subscheme ⟶ D.ideal.subscheme,
    j ≫ D.ideal.subschemeι = D'.ideal.subschemeι

/-- **(T-D14 = KM 1.3.4, incidence `≤`)** For a smooth relative curve and effective
divisors `D, D'` with `D'` proper (= finite) over `S`, there is a closed subscheme
`Z ⊆ S` universal for `D' ≤ D`, cut out locally by `deg D'` equations, compatible with
arbitrary base change. -/
theorem exists_incidenceLocusLE (hsm : SmoothOfRelativeDimension 1 π)
    (D D' : RelEffCartierDiv π) :
    ∃ Z : S.IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = t) ↔
        IsSubdivisor (D'.baseChange t) (D.baseChange t) := by sorry

/-- **(T-D15 = KM 1.3.5, incidence `=`, verbatim source in hand)** As above, universal
for `D_T = D'_T`, cut out locally by `deg D` equations. -/
theorem exists_incidenceLocusEQ (hsm : SmoothOfRelativeDimension 1 π)
    (D D' : RelEffCartierDiv π) :
    ∃ Z : S.IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = t) ↔
        (IsSubdivisor (D'.baseChange t) (D.baseChange t) ∧
         IsSubdivisor (D.baseChange t) (D'.baseChange t)) := by sorry

end RelEffCartierDiv

/-- **(T-D16 = KM 1.3.7, the subgroup-divisor locus, verbatim source in hand with
proof)** For an elliptic curve `E/S` and an effective divisor `D` in `E/S`, there is a
closed subscheme `Z ⊆ S` universal for "`D` is a subgroup", cut out locally by
`1 + deg D + (deg D)²` equations (`[e] ≤ D`; `D = inv*D`; `[m(P₁,P₂)] ≤ D` over
`D ×_S D`), compatible with arbitrary base change. -/
theorem exists_subgroupLocus (E : EllipticCurve S) (D : RelEffCartierDiv E.π) :
    ∃ Z : S.IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = t) ↔
        (D.baseChange t).IsSubgroup (E.baseChange t) := by sorry

/-- **(T-D17 = KM 1.6 for `A = ℤ/N`; the exact-order locus)** There is a closed
subscheme of `E[N]` universal for "the (torsion) point has exact order `N`": a point
of `E` killed by `N` over `t` has exact order `N` (as a section of the base-changed
curve) iff its classifying map to `E[N]` factors through the locus.
Consequence of `exists_subgroupLocus` applied to the universal divisor
`Σₐ [a·P_univ]` over `E[N]` (KM 1.6.1-style bootstrap). -/
theorem exists_exactOrderLocus (E : EllipticCurve S) (N : ℕ) [NeZero N] :
    ∃ Z : (E.torsion N).IdealSheafData, ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S)
      (P : E.Point t) (hP : P.1 ≫ E.mulByHom N = t ≫ E.zero),
      (∃ h : T ⟶ Z.subscheme, h ≫ Z.subschemeι = E.pointToTorsion P hP) ↔
        EllipticCurve.Section.HasExactOrder (E.baseChange t) (EllipticCurve.Point.asSection E t P) N :=
  by sorry

/-- **(T-D18 = KM 1.5–1.6 for `A = (ℤ/N)²`; the full-level locus)** There is a closed
subscheme of `E[N] ×_S E[N]` universal for "the pair is a Drinfeld full level-`N`
structure". Together with the Weil-pairing non-vanishing decomposition this is the
relative representability of `[Γ(N)]` (Loeffler Prop 3.8.2). -/
theorem exists_fullLevelLocus (E : EllipticCurve S) (N : ℕ) [NeZero N] :
    ∃ Z : (pullback (E.torsionπ N) (E.torsionπ N)).IdealSheafData,
      ∀ ⦃T : Scheme.{u}⦄ (t : T ⟶ S) (P Q : E.Point t)
        (hP : P.1 ≫ E.mulByHom N = t ≫ E.zero)
        (hQ : Q.1 ≫ E.mulByHom N = t ≫ E.zero),
      (∃ h : T ⟶ Z.subscheme,
          h ≫ Z.subschemeι = pullback.lift (E.pointToTorsion P hP)
            (E.pointToTorsion Q hQ) (by simp)) ↔
        (E.baseChange t).IsFullLevel N (EllipticCurve.Point.asSection E t P) (EllipticCurve.Point.asSection E t Q) :=
  by sorry

end Incidence

end ModularCurves
