module

public import BernoulliRegular.Reflection.KummerCharacterUnitLift
public import BernoulliRegular.Reflection.Kummer.UnramifiedCriterion
public import BernoulliRegular.Reflection.Kummer.WildCriterion
public import BernoulliRegular.Reflection.Kummer.CharacterMatching
public import BernoulliRegular.Reflection.Kummer.PrincipalLift
public import BernoulliRegular.Reflection.KummerToUnitQuotientComposer.PipelineAndRecipe

/-!
# End-to-end composer

Per-character component-extension pipeline to
`KummerCharacterUnitLift.OfComponentExtensions`.

This file composes the per-step Kummer-theoretic atoms — `KummerPresentation`,
`KummerDedekindUnramified`, principal-ideal lift, and
`KummerCharacterMatchingHypothesis` — into the per-character substantive
obligation `KummerCharacterUnitLift.OfComponentExtensions`.

## Structure of the composition

The chain is:

```
Ext : ComponentUnramifiedCyclicDegreePExtension K χ C
  ↓ Ext.kummerPresentation (Step 1, `Kummer/Presentation.lean`)
P : KummerPresentation Ext -- γ_χ ∈ K, α^p = γ_χ, K(α) = E

P + KummerDedekindUnramified P (Step 2a, `Kummer/UnramifiedCriterion.lean`)
  ↓ genIsPowOfFractionalIdealClass_of_isUnramified
GenIsPowOfFractionalIdealClass P -- (γ_χ) = J^p as fractional ideals

P + GenIsPowOfFractionalIdealClass P + principal lift (Step 2b, `Kummer/UnramifiedUnit.lean`)
  ↓ genEqUnitMulPow_of_genIsPowOfFractionalIdealClass_with_principal_lift
GenEqUnitMulPow P -- γ_χ = u_χ · β_χ^p with u_χ ∈ (𝓞_K)ˣ

P + KummerCharacterMatchingHypothesis P (Step 3, `Kummer/CharacterMatching.lean`)
  ↓ genInChiTwistDualEigenspace_of_matchingHypothesis
GenInChiTwistDualEigenspace P -- [γ_χ] in χ-twist-dual eigenspace
```

These four pieces (1 → 2a → 2b ; 1 → 3) deliver:

* a unit `u_χ ∈ (𝓞_K)ˣ` whose class in `(𝓞_K)ˣ/((𝓞_K)ˣ)^p` is the
  unit-quotient image of `[γ_χ] ∈ K^×/(K^×)^p`, and
* a witness that this class lies in the matching χ-eigenspace.

## What this file builds

Building a *full* `KummerCharacterUnitLift R S χ` — i.e.\ a `MonoidHom`
from the entire χ-Kummer-component into the χ-unit-quotient-component
together with its injectivity — needs more than per-element data: it
requires a global characterisation of how the χ-Kummer-component is
generated by the per-extension `γ_χ`s. That global characterisation is
the substantive Kummer-theoretic input that classical Kummer theory
provides via the unramified `K(C^{1/p})`-correspondence.

We therefore expose the composer in two layers:

* **Per-extension data bundle**
  `KummerPipelinePerExtension` packages the four atomic predicates for a
  single extension `Ext` of a given component `C` — so producing one of
  these is now a clean per-extension obligation instead of four separate
  ones.

* **Per-extension lift extraction**
  `KummerPipelinePerExtension.unitDecomposition` packages the
  `(u_χ, β_χ)` data extracted by composing 2a → 2b, together with the
  matching χ-eigenspace witness.

* **Top-level composer**
  `KummerCharacterUnitLift.ofComponentExtensions_of_perCharacterFamily` takes a
  per-character family of:

  - `KummerPipelinePerExtension`s (one per `(χ, C, Ext)`), and
  - a *promotion-to-hom* step (`KummerCharacterUnitLift.HomPromotion`)
    that turns the per-extension unit-decomposition data into the
    per-character monoid-hom-with-injectivity.

  Together these produce `KummerCharacterUnitLift.OfComponentExtensions R S`.

The promotion-to-hom step is what classical Kummer theory delivers in
its unramified-Kummer-correspondence form. It is the only remaining
*mathematical* obligation; all the *structural* composition is discharged
in this file.

## References

* Washington, *Introduction to Cyclotomic Fields*, §10.2-10.3.
* Diekmann, *FLT for regular primes*, §6.
* Borevich-Shafarevich, *Number Theory*, §4.9.
-/

@[expose] public section

universe u v

noncomputable section

open NumberField

namespace BernoulliRegular

section KummerToUnitQuotientComposer

variable {p : ℕ} [Fact p.Prime]
variable {K : Type u} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
variable {P : HilbertKummerSubgroup.HilbertKummerPresentation.{u, v} (p := p) (K := K)}

namespace KummerCharacterUnitLiftRecipe

variable {N : NondegenerateKummerPairing (p := p) (K := K) P}
variable {T : KummerPairingTwistData (p := p) (K := K) N}
variable {R : KummerPairingRawComparison (p := p) (K := K) N T}
variable {S : CyclotomicUnitModPStructure (p := p) K}

/-- **Pre-compose** with an injective `MonoidHom` on the source.

Given a recipe and an injective hom `g : H →* R.kummerComponent χ`, the
composition `Rec.toFun ∘ g` is an injective hom from `H`, packaged as a
`MonoidHom + injective` pair. This is *not* a
`KummerCharacterUnitLiftRecipe` because the source shape changes. -/
def precompMonoidHom {χ : MulChar (ZMod p)ˣ ℚ}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ)
    {H : Type*} [Group H]
    (g : H →* R.kummerComponent χ) (hg : Function.Injective g) :
    { f : H →* (S.components.component χ).Carrier // Function.Injective f } :=
  ⟨Rec.toMonoidHom.comp g, Rec.injective.comp hg⟩

/-! ### Equational lemmas for the structural constructors

The following `@[simp]` lemmas record the underlying-function behaviour of
`congrSource`, `congrTarget`, and `compose`, plus the identity laws
`congrSource (refl) = id`, `congrTarget (refl) = id`, and
`compose (refl, refl) = id`.

These are pure structural lemmas: they unfold definitionally but are useful
as `simp` normal forms when chaining recipe transformations. -/

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **`congrSource` toFun** unfolds to pre-composition with the equivalence. -/
@[simp] theorem congrSource_toFun {χ : MulChar (ZMod p)ˣ ℚ}
    {R' : KummerPairingRawComparison (p := p) (K := K) N T}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ)
    (e : R'.kummerComponent χ ≃* R.kummerComponent χ) :
    (Rec.congrSource (R' := R') e).toFun = fun x ↦ Rec.toFun (e x) := rfl

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **`congrTarget` toFun** unfolds to post-composition with the equivalence. -/
@[simp] theorem congrTarget_toFun {χ : MulChar (ZMod p)ˣ ℚ}
    {S' : CyclotomicUnitModPStructure (p := p) K}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ)
    (e : (S.components.component χ).Carrier ≃*
      (S'.components.component χ).Carrier) :
    (Rec.congrTarget (S' := S') e).toFun = fun x ↦ e (Rec.toFun x) := rfl

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **`compose` toFun** unfolds to bilateral composition. -/
@[simp] theorem compose_toFun {χ : MulChar (ZMod p)ˣ ℚ}
    {R' : KummerPairingRawComparison (p := p) (K := K) N T}
    {S' : CyclotomicUnitModPStructure (p := p) K}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ)
    (eSource : R'.kummerComponent χ ≃* R.kummerComponent χ)
    (eTarget : (S.components.component χ).Carrier ≃*
      (S'.components.component χ).Carrier) :
    (Rec.compose (R' := R') (S' := S') eSource eTarget).toFun =
      fun x ↦ eTarget (Rec.toFun (eSource x)) := rfl

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **`congrSource` with the identity equivalence** is the original recipe. -/
@[simp] theorem congrSource_refl {χ : MulChar (ZMod p)ˣ ℚ}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ) :
    Rec.congrSource (R' := R) (MulEquiv.refl (R.kummerComponent χ)) = Rec := by
  ext; rfl

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **`congrTarget` with the identity equivalence** is the original recipe. -/
@[simp] theorem congrTarget_refl {χ : MulChar (ZMod p)ˣ ℚ}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ) :
    Rec.congrTarget (S' := S)
        (MulEquiv.refl (S.components.component χ).Carrier) = Rec := by
  ext; rfl

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **`compose` with the identity on both sides** is the original recipe. -/
@[simp] theorem compose_refl {χ : MulChar (ZMod p)ˣ ℚ}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ) :
    Rec.compose (R' := R) (S' := S)
        (MulEquiv.refl (R.kummerComponent χ))
        (MulEquiv.refl (S.components.component χ).Carrier) = Rec := by
  ext; rfl

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **`congrSource` is associative with `congrTarget`**: post-composing the
target equiv after a source congruence equals applying the source congruence
to the target-congruence-transformed recipe. This is the definitional
unfolding of `compose`. -/
theorem congrSource_congrTarget
    {χ : MulChar (ZMod p)ˣ ℚ}
    {R' : KummerPairingRawComparison (p := p) (K := K) N T}
    {S' : CyclotomicUnitModPStructure (p := p) K}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ)
    (eSource : R'.kummerComponent χ ≃* R.kummerComponent χ)
    (eTarget : (S.components.component χ).Carrier ≃*
      (S'.components.component χ).Carrier) :
    (Rec.congrSource (R' := R') eSource).congrTarget (S' := S') eTarget =
      Rec.compose (R' := R') (S' := S') eSource eTarget := rfl

end KummerCharacterUnitLiftRecipe

/-! ### Existence instances for `KummerCharacterUnitLiftRecipe`

When the Kummer-side χ-component is a subsingleton, the trivial recipe
provides an instance of `Nonempty`. This is the recipe-level analogue of
the trivial-case discharge of `HomPromotion`. -/

/-- **Nonempty instance** when the Kummer-side χ-component is a subsingleton:
the trivial recipe provides the witness. -/
instance KummerCharacterUnitLiftRecipe.instNonemptyOfSubsingleton
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    [Subsingleton (R.kummerComponent χ : Type _)] :
    Nonempty (KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ) :=
  ⟨KummerCharacterUnitLiftRecipe.trivial (p := p) (K := K) (R := R) (S := S)
    (χ := χ)⟩

/-! ### Trivial-case discharges of `PerExtensionRecipe`

For characters whose Kummer-side χ-component is a subsingleton, the
`PerExtensionRecipe` is discharged uniformly by handing back the trivial
recipe regardless of the supplied per-extension data. This is the recipe
analogue of `HomPromotion.ofKummerComponentSubsingleton`. -/

/-- **Trivial-case discharge** of `PerExtensionRecipe` when the Kummer
χ-component is a subsingleton.

When the χ-component is empty of non-trivial classes, the trivial recipe
discharges the obligation uniformly. -/
theorem KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.ofKummerComponentSubsingleton
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    [Subsingleton (R.kummerComponent χ : Type _)] :
    KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.{u, v}
      (p := p) (K := K) R S χ := fun _ _ _ _ ↦
  ⟨KummerCharacterUnitLiftRecipe.trivial
    (p := p) (K := K) (R := R) (S := S) (χ := χ)⟩

/-- **Trivial-case bridge**: a Kummer-component-subsingleton character has a
`PerExtensionRecipe` whose induced `HomPromotion` agrees with
`HomPromotion.ofKummerComponentSubsingleton` up to the structural unfolding
provided by `ofRecipe`.

This is the recipe-level analogue of saying the trivial `PerExtensionRecipe`
"reduces to" the trivial `HomPromotion` discharge — the substantive content
is the discharge itself, exposed here as a recipe. -/
theorem KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.refl_for_trivial_χ_component
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    [Subsingleton (R.kummerComponent χ : Type _)] :
    KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.{u, v}
      (p := p) (K := K) R S χ :=
  KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.ofKummerComponentSubsingleton
    (p := p) (K := K) (R := R) (S := S) (χ := χ)

/-! ### `MulEquiv`-based discharges of `PerExtensionRecipe`

The non-trivial discharges of `PerExtensionRecipe` come from a concrete
mathematical witness identifying the Kummer χ-component with the unit-quotient
χ-component. We expose two universal `MulEquiv`-based discharges:

* **`ofMulEquiv`** — when there is a `MulEquiv` between the Kummer
  χ-component and the unit-quotient χ-component, the recipe is the
  identity-via-equiv.  This is the cleanest "the unit lift is the
  isomorphism" discharge.

* **`refl_for_unit_kummer`** — the universal "kummer equals unit-quotient"
  discharge: when the χ-component of the unit quotient *is* the χ-component
  of the Kummer side (witnessed by a `MulEquiv`), the per-extension recipe
  is the identity recipe. This is the recipe-level analogue of
  `MulEquiv.refl` and is the natural discharge in the (rare) case when the
  two sides are forced to coincide upstream.
-/

/-- **`MulEquiv`-based discharge** of `PerExtensionRecipe`.

When there is a `MulEquiv` between the Kummer χ-component and the
unit-quotient χ-component, the per-extension recipe is the
identity-via-equiv (it ignores the per-extension data and just hands
back the equivalence).

This is the universal "the unit lift is the isomorphism" discharge: the
substantive Kummer-theoretic content — the existence of an isomorphism
between the Kummer side and the unit-quotient side — is plugged in
directly, and the recipe is automatic. -/
theorem KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.ofMulEquiv
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    (e : R.kummerComponent χ ≃* (S.components.component χ).Carrier) :
    KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.{u, v}
      (p := p) (K := K) R S χ := fun _ _ _ _ ↦
  ⟨KummerCharacterUnitLiftRecipe.ofMulEquiv
    (R := R) (S := S) (χ := χ) e⟩

/-- **"Kummer = unit-quotient" discharge** of `PerExtensionRecipe`.

Universal discharge: when the χ-component of the Kummer side *is* the
χ-component of the unit-quotient side (witnessed by a `MulEquiv`), the
per-extension recipe is the identity-via-equiv.

Mathematically this is the strongest possible identification — the two
χ-components are isomorphic — and the recipe is the canonical isomorphism.
This is the analogue of `MulEquiv.refl` lifted to the
`PerExtensionRecipe` level. -/
theorem KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.refl_for_unit_kummer
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    (e : R.kummerComponent χ ≃* (S.components.component χ).Carrier) :
    KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.{u, v}
      (p := p) (K := K) R S χ :=
  KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.ofMulEquiv
    (p := p) (K := K) (R := R) (S := S) (χ := χ) e

/-- **Injective-`MonoidHom` discharge** of `PerExtensionRecipe`.

A more permissive version of `ofMulEquiv`: when there is an injective
`MonoidHom` between the Kummer χ-component and the unit-quotient
χ-component, the per-extension recipe is the identity-via-`MonoidHom`.

This is the substantive form: a single injective hom suffices (no
surjectivity required), since the recipe contract only demands
multiplicativity + injectivity. -/
theorem KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.ofInjectiveMonoidHom
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    (f : R.kummerComponent χ →* (S.components.component χ).Carrier)
    (hf : Function.Injective f) :
    KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.{u, v}
      (p := p) (K := K) R S χ := fun _ _ _ _ ↦
  ⟨KummerCharacterUnitLiftRecipe.ofMonoidHom
    (R := R) (S := S) (χ := χ) f hf⟩

/-! ### Family-level packaging of recipes

The χ-indexed family analogue of `PerExtensionRecipe`: at every χ, supply
a recipe. This combines with `HomPromotionFamily.ofPartition` to produce
`HomPromotionFamily`. -/

/-- **Family-level recipe** at every character.

A `PerCharacterRecipe` is the χ-indexed bundle of `PerExtensionRecipe`s.
This is the cleanest input shape for the family-level discharge of
`HomPromotionFamily`: at every character supply a recipe, and the
trivial χ-components are still discharged automatically inside each
`PerExtensionRecipe`. -/
def KummerCharacterUnitLift.HomPromotionFamily.PerCharacterRecipe
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    (R : KummerPairingRawComparison (p := p) (K := K) N T)
    (S : CyclotomicUnitModPStructure (p := p) K) : Prop :=
  ∀ χ : MulChar (ZMod p)ˣ ℚ,
    KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.{u, v}
      (p := p) (K := K) R S χ

/-- **Discharge of `HomPromotionFamily` from a family of recipes.**

Each per-character recipe is converted to a `HomPromotion` via
`ofPerExtensionRecipe`. -/
theorem KummerCharacterUnitLift.HomPromotionFamily.ofPerCharacterRecipe
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    (recipes :
      KummerCharacterUnitLift.HomPromotionFamily.PerCharacterRecipe.{u, v}
        (p := p) (K := K) R S) :
    KummerCharacterUnitLift.HomPromotionFamily.{u, v} (p := p) (K := K) R S :=
  fun χ ↦
    KummerCharacterUnitLift.HomPromotion.ofPerExtensionRecipe
      (p := p) (K := K) (R := R) (S := S) (χ := χ) (recipes χ)

/-- **Mixed-discharge** of `HomPromotionFamily` from per-character recipes
*restricted* to the non-trivial Kummer-side characters.

The trivial Kummer-side characters are handled automatically via
`HomPromotion.ofKummerComponentSubsingleton`, leaving the substantive
mathematical input as a `PerExtensionRecipe` only at characters whose
χ-component is genuinely non-trivial. -/
theorem KummerCharacterUnitLift.HomPromotionFamily.ofNonTrivialPerCharacterRecipe
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    (nonTrivialRecipes :
      ∀ χ : MulChar (ZMod p)ˣ ℚ,
        ¬ Subsingleton (R.kummerComponent χ : Type _) →
        KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.{u, v}
          (p := p) (K := K) R S χ) :
    KummerCharacterUnitLift.HomPromotionFamily.{u, v} (p := p) (K := K) R S := by
  refine KummerCharacterUnitLift.HomPromotionFamily.ofPartition
    (p := p) (K := K) (R := R) (S := S) ?_
  intro χ hχ
  exact KummerCharacterUnitLift.HomPromotion.ofPerExtensionRecipe
    (p := p) (K := K) (R := R) (S := S) (χ := χ) (nonTrivialRecipes χ hχ)

/-! ### Family-level `MulEquiv`-based discharges

When the χ-indexed family of identifications between Kummer χ-components and
unit-quotient χ-components is supplied as `MulEquiv`s (one per `χ`), the
entire `HomPromotionFamily` is discharged uniformly. This is the cleanest
"the unit lift is the χ-indexed family of isomorphisms" discharge. -/

/-- **Family-level `MulEquiv`-based discharge.**

Given a `MulEquiv` for every χ between the Kummer χ-component and the
unit-quotient χ-component, the entire `HomPromotionFamily` follows by
applying `PerExtensionRecipe.ofMulEquiv` at every χ. -/
theorem KummerCharacterUnitLift.HomPromotionFamily.ofPerCharacterMulEquiv
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    (eFamily : ∀ χ : MulChar (ZMod p)ˣ ℚ,
      R.kummerComponent χ ≃* (S.components.component χ).Carrier) :
    KummerCharacterUnitLift.HomPromotionFamily.{u, v} (p := p) (K := K) R S :=
  KummerCharacterUnitLift.HomPromotionFamily.ofPerCharacterRecipe
    (p := p) (K := K) (R := R) (S := S)
    (fun χ ↦
      KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.ofMulEquiv
        (p := p) (K := K) (R := R) (S := S) (χ := χ) (eFamily χ))

/-- **Family-level injective-`MonoidHom` discharge.**

A more permissive version of `ofPerCharacterMulEquiv`: given an injective
`MonoidHom` for every χ, the `HomPromotionFamily` follows. -/
theorem KummerCharacterUnitLift.HomPromotionFamily.ofPerCharacterInjectiveMonoidHom
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    (fFamily : ∀ χ : MulChar (ZMod p)ˣ ℚ,
      R.kummerComponent χ →* (S.components.component χ).Carrier)
    (hFamily : ∀ χ : MulChar (ZMod p)ˣ ℚ, Function.Injective (fFamily χ)) :
    KummerCharacterUnitLift.HomPromotionFamily.{u, v} (p := p) (K := K) R S :=
  KummerCharacterUnitLift.HomPromotionFamily.ofPerCharacterRecipe
    (p := p) (K := K) (R := R) (S := S)
    (fun χ ↦
      KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.ofInjectiveMonoidHom
        (p := p) (K := K) (R := R) (S := S) (χ := χ) (fFamily χ) (hFamily χ))

/-! ### Remaining substantive obligation

After all the structural discharges above, the only remaining mathematical
content needed to construct a `HomPromotionFamily` end-to-end is:

* a `PerExtensionRecipe` at every χ whose Kummer-side χ-component is
  *not* a subsingleton (handled by `ofNonTrivialPerCharacterRecipe`).

That obligation is exactly the global unramified Kummer correspondence:
on the χ-component the unit lift is `[γ_χ] ↦ [u_χ]` where `u_χ` is the
unit factor in the decomposition `γ_χ = u_χ · β_χ^p` extracted from the
per-extension pipeline.

The constructor `KummerCharacterUnitLiftRecipe.ofPointwiseUnit` shows that
producing this recipe from per-element data + multiplicativity + injectivity
is the canonical shape; the substantive Kummer-theoretic content lives
entirely in *constructing* such per-element data with multiplicativity and
injectivity from the per-extension `UnitDecompositionData`. -/

/-! ### Composer (per character)

For one character `χ`, we compose:

* the `KummerPipelinePerExtension Ext` (per-extension pipeline data) and
* the `HomPromotion R S χ` (promotion-to-hom step)

into the per-character substantive obligation `KummerCharacterUnitLift R S χ`.
-/

/-- **Per-character composer.**

From one `(χ, C, Ext, KummerPipelinePerExtension Ext)` quadruple plus the
per-character promotion-to-hom step, produce `KummerCharacterUnitLift R S χ`. -/
theorem KummerCharacterUnitLift.ofPerCharacterPipeline
    [IsCMField K]
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    {Comp : CyclotomicFieldClassGroupPSylowComponent (p := p) K}
    (hCχ : Comp.character = χ)
    (Ext : ComponentUnramifiedCyclicDegreePExtension.{u, v} (p := p) K χ Comp)
    (Pi : KummerPipelinePerExtension Ext)
    (promotion : KummerCharacterUnitLift.HomPromotion.{u, v}
      (p := p) (K := K) R S χ) :
    Nonempty (KummerCharacterUnitLift (p := p) (K := K) R S χ) :=
  promotion Comp hCχ Ext Pi.unitDecomposition

/-! ### Top-level composer feeding `OfComponentExtensions`

For every `χ` and every component `Comp` whose component extension is supplied,
the per-character pipeline data (one `KummerPipelinePerExtension Ext`)
together with the per-character promotion-to-hom step produces a
`KummerCharacterUnitLift R S χ`. Wrapping this for all `χ` produces the
target `KummerCharacterUnitLift.OfComponentExtensions R S`.
-/

/-- **Family-level per-extension pipeline.**

For every `χ`, every `Comp` whose component extension is non-empty, every choice
of `Ext`, this is the obligation to produce a `KummerPipelinePerExtension Ext`. -/
def KummerCharacterUnitLift.PerExtensionPipelineFamily
    [IsCMField K] : Prop :=
  ∀ (χ : MulChar (ZMod p)ˣ ℚ)
    (Comp : CyclotomicFieldClassGroupPSylowComponent (p := p) K)
    (_ : Comp.character = χ)
    (Ext : ComponentUnramifiedCyclicDegreePExtension.{u, v} (p := p) K χ Comp),
    Nonempty (KummerPipelinePerExtension Ext)

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **Top-level composer.**

Given a per-extension pipeline family and a per-character promotion-to-hom
family, the composition produces
`KummerCharacterUnitLift.OfComponentExtensions R S`. -/
theorem KummerCharacterUnitLift.ofComponentExtensions_of_perCharacterFamily
    [IsCyclotomicExtension {p} ℚ K] [IsCMField K]
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    (R : KummerPairingRawComparison (p := p) (K := K) N T)
    (S : CyclotomicUnitModPStructure (p := p) K)
    (pipelineFamily :
      KummerCharacterUnitLift.PerExtensionPipelineFamily.{u, v} (p := p) (K := K))
    (promotionFamily :
      KummerCharacterUnitLift.HomPromotionFamily.{u, v} (p := p) (K := K) R S) :
    KummerCharacterUnitLift.OfComponentExtensions.{u, v} (p := p) (K := K) R S := by
  intro χ Comp hCχ hExt
  obtain ⟨Ext⟩ := hExt
  obtain ⟨Pi⟩ := pipelineFamily χ Comp hCχ Ext
  exact KummerCharacterUnitLift.ofPerCharacterPipeline (p := p) (K := K)
    (R := R) (S := S) (χ := χ) (Comp := Comp)
    hCχ Ext Pi (promotionFamily χ)

/-! ### Direct composer feeding the family of `KummerCharacterUnitLift`s

A more direct shape: from `OfComponentExtensions` plus component-extension existence statement,
build a `KummerNonTrivialUnitLiftData` (the per-non-trivial-χ obligation
input that `KummerCharacterUnitLift` consumes).
-/

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **From `OfComponentExtensions` to the non-trivial-χ family input.**

Given `OfComponentExtensions`, plus component-extension existence at every
non-trivial Kummer-side χ-component, build the per-non-trivial-χ obligation
data consumed by `KummerCharacterUnitLift`'s partition family
constructor.

The χ-to-Comp wiring (what component a non-trivial Kummer-side χ corresponds
to) is supplied as the `componentChoice` parameter; in the actual
component-extension setting, this is provided by the global Kummer-pairing
dictionary. -/
theorem kummerNonTrivialUnitLiftData_of_ofComponentExtensions
    [IsCyclotomicExtension {p} ℚ K] [IsCMField K]
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    (h : KummerCharacterUnitLift.OfComponentExtensions.{u, v} (p := p) (K := K) R S)
    (componentChoice :
      ∀ χ : MulChar (ZMod p)ˣ ℚ,
        ¬ Subsingleton (R.kummerComponent χ : Type _) →
        Σ' (Comp : CyclotomicFieldClassGroupPSylowComponent (p := p) K),
          Comp.character = χ ∧
            Nonempty (ComponentUnramifiedCyclicDegreePExtension.{u, v}
              (p := p) K χ Comp)) :
    KummerNonTrivialUnitLiftData (p := p) (K := K) R S := by
  intro χ hχ
  obtain ⟨Comp, hCχ, hExt⟩ := componentChoice χ hχ
  exact h χ Comp hCχ hExt

/-- **Composite top-level composer feeding the embedding data.**

Combine the per-character pipeline family + promotion family with
component-extension existence to build the full
`KummerToUnitQuotientEmbeddingData`. -/
noncomputable def kummerToUnitQuotientEmbeddingData_of_perCharacterFamily
    [IsCMField K]
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    (pipelineFamily :
      KummerCharacterUnitLift.PerExtensionPipelineFamily.{u, v} (p := p) (K := K))
    (promotionFamily :
      KummerCharacterUnitLift.HomPromotionFamily.{u, v} (p := p) (K := K) R S)
    (componentChoice :
      ∀ χ : MulChar (ZMod p)ˣ ℚ,
        ¬ Subsingleton (R.kummerComponent χ : Type _) →
        Σ' (Comp : CyclotomicFieldClassGroupPSylowComponent (p := p) K),
          Comp.character = χ ∧
            Nonempty (ComponentUnramifiedCyclicDegreePExtension.{u, v}
              (p := p) K χ Comp)) :
    KummerToUnitQuotientEmbeddingData (p := p) (K := K) R S :=
  kummerToUnitQuotientEmbeddingData_of_nonTrivialUnitLiftData
    (p := p) (K := K) (R := R) (S := S)
    (kummerNonTrivialUnitLiftData_of_ofComponentExtensions
      (p := p) (K := K) (R := R) (S := S)
      (KummerCharacterUnitLift.ofComponentExtensions_of_perCharacterFamily
        (p := p) (K := K) R S pipelineFamily promotionFamily)
      componentChoice)

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **Composite top-level composer feeding the cardinality inclusion.**

Compress the embedding-data composer into the inclusion form consumed by
the rank-inequality bridge. -/
theorem kummerToUnitQuotientInclusion_of_perCharacterFamily
    [IsCyclotomicExtension {p} ℚ K] [IsCMField K]
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    (pipelineFamily :
      KummerCharacterUnitLift.PerExtensionPipelineFamily.{u, v} (p := p) (K := K))
    (promotionFamily :
      KummerCharacterUnitLift.HomPromotionFamily.{u, v} (p := p) (K := K) R S)
    (componentChoice :
      ∀ χ : MulChar (ZMod p)ˣ ℚ,
        ¬ Subsingleton (R.kummerComponent χ : Type _) →
        Σ' (Comp : CyclotomicFieldClassGroupPSylowComponent (p := p) K),
          Comp.character = χ ∧
            Nonempty (ComponentUnramifiedCyclicDegreePExtension.{u, v}
              (p := p) K χ Comp)) :
    KummerToUnitQuotientInclusion (p := p) (K := K) R S :=
  (kummerToUnitQuotientEmbeddingData_of_perCharacterFamily
    (p := p) (K := K) (R := R) (S := S)
    pipelineFamily promotionFamily componentChoice).toInclusion

end KummerToUnitQuotientComposer

end BernoulliRegular

end
