module

public import BernoulliRegular.Reflection.KummerCharacterUnitLift
public import BernoulliRegular.Reflection.Kummer.UnramifiedCriterion
public import BernoulliRegular.Reflection.Kummer.WildCriterion
public import BernoulliRegular.Reflection.Kummer.CharacterMatching
public import BernoulliRegular.Reflection.Kummer.PrincipalLift

/-!
# End-to-end composer

Per-character component-extension pipeline to
`KummerCharacterUnitLift.OfComponentExtensions`.

This file composes the per-step Kummer-theoretic atoms — `KummerPresentation`,
`KummerDedekindUnramified`, principal-ideal lift, and
`KummerCharacterMatchingHypothesis` — into the per-character substantive
obligation `KummerCharacterUnitLift.OfComponentExtensions`.

## Structure of the composition

The chain is:

```
Ext : ComponentUnramifiedCyclicDegreePExtension K χ C
  ↓ Ext.kummerPresentation (Step 1, `Kummer/Presentation.lean`)
P : KummerPresentation Ext -- γ_χ ∈ K, α^p = γ_χ, K(α) = E

P + KummerDedekindUnramified P (Step 2a, `Kummer/UnramifiedCriterion.lean`)
  ↓ genIsPowOfFractionalIdealClass_of_isUnramified
GenIsPowOfFractionalIdealClass P -- (γ_χ) = J^p as fractional ideals

P + GenIsPowOfFractionalIdealClass P + principal lift (Step 2b, `Kummer/UnramifiedUnit.lean`)
  ↓ genEqUnitMulPow_of_genIsPowOfFractionalIdealClass_with_principal_lift
GenEqUnitMulPow P -- γ_χ = u_χ · β_χ^p with u_χ ∈ (𝓞_K)ˣ

P + KummerCharacterMatchingHypothesis P (Step 3, `Kummer/CharacterMatching.lean`)
  ↓ genInChiTwistDualEigenspace_of_matchingHypothesis
GenInChiTwistDualEigenspace P -- [γ_χ] in χ-twist-dual eigenspace
```

These four pieces (1 → 2a → 2b ; 1 → 3) deliver:

* a unit `u_χ ∈ (𝓞_K)ˣ` whose class in `(𝓞_K)ˣ/((𝓞_K)ˣ)^p` is the
  unit-quotient image of `[γ_χ] ∈ K^×/(K^×)^p`, and
* a witness that this class lies in the matching χ-eigenspace.

## What this file builds

Building a *full* `KummerCharacterUnitLift R S χ` — i.e.\ a `MonoidHom`
from the entire χ-Kummer-component into the χ-unit-quotient-component
together with its injectivity — needs more than per-element data: it
requires a global characterisation of how the χ-Kummer-component is
generated by the per-extension `γ_χ`s. That global characterisation is
the substantive Kummer-theoretic input that classical Kummer theory
provides via the unramified `K(C^{1/p})`-correspondence.

We therefore expose the composer in two layers:

* **Per-extension data bundle**
  `KummerPipelinePerExtension` packages the four atomic predicates for a
  single extension `Ext` of a given component `C` — so producing one of
  these is now a clean per-extension obligation instead of four separate
  ones.

* **Per-extension lift extraction**
  `KummerPipelinePerExtension.unitDecomposition` packages the
  `(u_χ, β_χ)` data extracted by composing 2a → 2b, together with the
  matching χ-eigenspace witness.

* **Top-level composer**
  `KummerCharacterUnitLift.ofComponentExtensions_of_perCharacterFamily` takes a
  per-character family of:

  - `KummerPipelinePerExtension`s (one per `(χ, C, Ext)`), and
  - a *promotion-to-hom* step (`KummerCharacterUnitLift.HomPromotion`)
    that turns the per-extension unit-decomposition data into the
    per-character monoid-hom-with-injectivity.

  Together these produce `KummerCharacterUnitLift.OfComponentExtensions R S`.

The promotion-to-hom step is what classical Kummer theory delivers in
its unramified-Kummer-correspondence form. It is the only remaining
*mathematical* obligation; all the *structural* composition is discharged
in this file.

## References

* Washington, *Introduction to Cyclotomic Fields*, §10.2-10.3.
* Diekmann, *FLT for regular primes*, §6.
* Borevich-Shafarevich, *Number Theory*, §4.9.
-/

@[expose] public section

universe u v

noncomputable section

open NumberField
open scoped nonZeroDivisors

namespace BernoulliRegular

section KummerToUnitQuotientComposer

variable {p : ℕ} [Fact p.Prime]
variable {K : Type u} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
variable {P : HilbertKummerSubgroup.HilbertKummerPresentation.{u, v} (p := p) (K := K)}

/-! ### Per-extension pipeline data bundle

`KummerPipelinePerExtension` packages the four atomic predicates needed for
one `(χ, C, Ext)` triple: the Kummer presentation, the per-prime
Kummer-Dedekind hypothesis, the principal-ideal lift, and the χ-character
matching.
-/

/-- **Per-extension pipeline data.**

For a single component-refined extension `Ext`, this bundles:

* `presentation` — the Kummer presentation `α^p = γ_χ` (Step 1);
* `kummerDedekind` — the per-prime Kummer-Dedekind input
  `IsUnramifiedAt v.asIdeal → (p : ℤ) ∣ count v γ_χ` (Step 2a);
* `principalLift` — the class-group lift turning the weak-form `(γ_χ) = J^p`
  into the strong form with a principal `J` (Step 2b prerequisite);
* `matchingHypothesis` — the substantive χ-character matching, packaging the
  Galois-equivariance of the Kummer pairing + cyclotomic character (Step 3).

Producing one of these per `(χ, C, Ext)` is the per-extension obligation
that the downstream Kummer-theoretic refinement of component-extension must discharge. -/
structure KummerPipelinePerExtension
    {χ : MulChar (ZMod p)ˣ ℚ}
    {Comp : CyclotomicFieldClassGroupPSylowComponent (p := p) K}
    (Ext : ComponentUnramifiedCyclicDegreePExtension (p := p) K χ Comp) where
  /-- The Kummer presentation `α^p = γ_χ` derived from `Ext`. -/
  presentation : KummerPresentation Ext
  /-- The per-prime Kummer-Dedekind unramified criterion: at every height-one
  prime `v`, unramifiedness of `v` in `𝓞 E` implies `v_v(γ_χ)` is divisible
  by `p`. -/
  kummerDedekind : presentation.KummerDedekindUnramified
  /-- The principal-ideal lift: from `(γ_χ) = J^p` in the fractional-ideal
  group, there exists a principal representative `(β)` for `J` modulo `p`-th
  powers. -/
  principalLift : ∀ J : (FractionalIdeal (𝓞 K)⁰ K)ˣ,
    toPrincipalIdeal (𝓞 K) K presentation.genUnit = J ^ p →
    ∃ β : Kˣ, J = toPrincipalIdeal (𝓞 K) K β
  /-- The χ-character matching hypothesis: `[γ_χ] ∈ K^×/(K^×)^p` lies in the
  χ-twist-dual eigenspace under the `Δ`-action. -/
  matchingHypothesis : presentation.KummerCharacterMatchingHypothesis

namespace KummerPipelinePerExtension

variable {χ : MulChar (ZMod p)ˣ ℚ}
variable {Comp : CyclotomicFieldClassGroupPSylowComponent (p := p) K}
variable {Ext : ComponentUnramifiedCyclicDegreePExtension (p := p) K χ Comp}

/-- **Composite reduction (Step 1 + Step 2a).** From the per-extension pipeline
data, derive the weak fractional-ideal form `(γ_χ) = J^p`. -/
theorem genIsPowOfFractionalIdealClass
    (Pi : KummerPipelinePerExtension Ext) :
    Pi.presentation.GenIsPowOfFractionalIdealClass :=
  Pi.presentation.genIsPowOfFractionalIdealClass_of_isUnramified Pi.kummerDedekind

/-- **Composite reduction (Step 1 + Step 2a + Step 2b).** From the per-extension
pipeline data, derive the strong fractional-ideal form `(γ_χ) = (β)^p`. -/
theorem genIsPowOfPrincipalFractionalIdeal
    (Pi : KummerPipelinePerExtension Ext) :
    Pi.presentation.GenIsPowOfPrincipalFractionalIdeal := by
  obtain ⟨J, hJ⟩ := Pi.genIsPowOfFractionalIdealClass
  obtain ⟨β, hβ⟩ := Pi.principalLift J hJ
  refine ⟨β, ?_⟩
  rw [hJ, hβ]

/-- **Composite reduction (Steps 1, 2a, 2b).** From the per-extension pipeline
data, derive the unit decomposition `γ_χ = u_χ · β_χ^p`. -/
theorem genEqUnitMulPow
    (Pi : KummerPipelinePerExtension Ext) :
    Pi.presentation.GenEqUnitMulPow :=
  Pi.presentation.genEqUnitMulPow_of_genIsPowOfPrincipalFractionalIdeal
    Pi.genIsPowOfPrincipalFractionalIdeal

/-- **Composite reduction (Step 3).** From the per-extension pipeline data,
derive that `[γ_χ]` is in the χ-twist-dual eigenspace. -/
theorem genInChiTwistDualEigenspace
    (Pi : KummerPipelinePerExtension Ext) :
    Pi.presentation.GenInChiTwistDualEigenspace :=
  Pi.presentation.genInChiTwistDualEigenspace_of_matchingHypothesis
    Pi.matchingHypothesis

/-! ### Extracted unit-decomposition data

The substantive output of the per-extension pipeline is:

* a unit `u_χ ∈ (𝓞_K)ˣ`,
* a non-zero `β_χ ∈ Kˣ`, and
* the equation `γ_χ = u_χ · β_χ^p`,

together with the matching χ-eigenspace witness. We expose this as the
shape that the promotion-to-hom step consumes.
-/

/-- **Extracted unit-decomposition data.**

The per-extension pipeline yields an `(u_χ, β_χ)` decomposition of the
Kummer generator together with the χ-eigenspace witness. This is the
shape consumed by the promotion-to-hom step.
-/
structure UnitDecompositionData
    {χ : MulChar (ZMod p)ˣ ℚ}
    {Comp : CyclotomicFieldClassGroupPSylowComponent (p := p) K}
    (Ext : ComponentUnramifiedCyclicDegreePExtension (p := p) K χ Comp) where
  /-- The Kummer presentation. -/
  presentation : KummerPresentation Ext
  /-- The unit `u_χ ∈ (𝓞_K)ˣ`. -/
  unit : (𝓞 K)ˣ
  /-- The auxiliary `β_χ ∈ Kˣ`. -/
  beta : Kˣ
  /-- The unit decomposition equation. -/
  decomposition_eq : (presentation.gen : K) =
    algebraMap (𝓞 K) K (unit : 𝓞 K) * (beta : K) ^ p
  /-- The χ-eigenspace witness. -/
  inChiTwistDualEigenspace : presentation.GenInChiTwistDualEigenspace

/-- **Extract the unit-decomposition data from the per-extension pipeline.** -/
noncomputable def unitDecomposition
    (Pi : KummerPipelinePerExtension Ext) :
    UnitDecompositionData Ext :=
  let h := Pi.genEqUnitMulPow
  { presentation := Pi.presentation
    unit := h.choose
    beta := h.choose_spec.choose
    decomposition_eq := h.choose_spec.choose_spec
    inChiTwistDualEigenspace := Pi.genInChiTwistDualEigenspace }

end KummerPipelinePerExtension

/-! ### Top-level composer feeding `OfComponentExtensions`

The final piece is the composer that takes:

* a per-character family of `KummerPipelinePerExtension`s, and
* a promotion-to-hom step turning the per-extension unit-decomposition
  data into the per-character monoid-hom-with-injectivity,

and produces `KummerCharacterUnitLift.OfComponentExtensions`.
-/

/-- **Promotion-to-hom step (per character).**

The substantive Kummer-theoretic content not handled by the per-extension
pipeline: from one `(χ, C, Ext, unit-decomposition data)` quadruple,
produce a `KummerCharacterUnitLift R S χ`.

Mathematically this corresponds to the global *unramified Kummer
correspondence* `(𝓞_K)ˣ/((𝓞_K)ˣ)^p ↞ C` (where `C ⊂ Kˣ/(Kˣ)^p` is the
declared Kummer subgroup): the χ-component of `C` is generated by the
classes `[γ_χ]`, and each `[γ_χ]` lifts to `[u_χ]`, giving the χ-component
of `(𝓞_K)ˣ/((𝓞_K)ˣ)^p`. -/
def KummerCharacterUnitLift.HomPromotion
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    (R : KummerPairingRawComparison (p := p) (K := K) N T)
    (S : CyclotomicUnitModPStructure (p := p) K)
    (χ : MulChar (ZMod p)ˣ ℚ) : Prop :=
  ∀ (C : CyclotomicFieldClassGroupPSylowComponent (p := p) K),
    C.character = χ →
    ∀ (Ext : ComponentUnramifiedCyclicDegreePExtension.{u, v} (p := p) K χ C),
    KummerPipelinePerExtension.UnitDecompositionData Ext →
    Nonempty (KummerCharacterUnitLift (p := p) (K := K) R S χ)

/-- **Family-level promotion-to-hom data.**

The χ-indexed family of promotion steps. -/
def KummerCharacterUnitLift.HomPromotionFamily
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    (R : KummerPairingRawComparison (p := p) (K := K) N T)
    (S : CyclotomicUnitModPStructure (p := p) K) : Prop :=
  ∀ χ : MulChar (ZMod p)ˣ ℚ,
    KummerCharacterUnitLift.HomPromotion.{u, v} (p := p) (K := K) R S χ

/-! ### Discharge of `HomPromotion` (trivial case + sub-atomic refinement)

We expose two layers of discharge for `HomPromotion`:

* **Trivial-case discharge** (`HomPromotion.ofKummerComponentSubsingleton`) —
  when the χ-Kummer-component is a subsingleton, the trivial unit-lift
  `KummerCharacterUnitLift.ofKummerComponentSubsingleton` discharges the
  promotion uniformly, regardless of the supplied per-extension data.

* **Sub-atomic refinement** (`HomPromotion.PerExtensionUnitLift` and
  `HomPromotion.ofPerExtensionUnitLift`) — refines the substantive content
  into a per-`(C, Ext, UnitDecompositionData)` recipe for producing one
  `KummerCharacterUnitLift R S χ`. This is the irreducible mathematical
  obligation.

Both layers feed `HomPromotionFamily` via the family-level partition
constructor `HomPromotionFamily.ofPartition`. -/

/-- **Trivial-case discharge** of `HomPromotion`: when the Kummer-side
χ-component is a subsingleton, the promotion succeeds uniformly via
`KummerCharacterUnitLift.ofKummerComponentSubsingleton`, ignoring the
supplied per-extension data.

This is the analogue, at the promotion-to-hom level, of the trivial-case
constructor `KummerCharacterUnitLift.ofKummerComponentSubsingleton` at the
per-character lift level. -/
theorem KummerCharacterUnitLift.HomPromotion.ofKummerComponentSubsingleton
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    [Subsingleton (R.kummerComponent χ : Type _)] :
    KummerCharacterUnitLift.HomPromotion.{u, v} (p := p) (K := K) R S χ := fun _ _ _ _ ↦
  ⟨KummerCharacterUnitLift.ofKummerComponentSubsingleton
    (p := p) (K := K) (R := R) (S := S) (χ := χ)⟩

/-- **Per-extension unit-lift recipe.**

The substantive Kummer-theoretic input that the non-trivial discharge of
`HomPromotion` requires: a per-`(C, Ext, UnitDecompositionData)` constructor
producing a single `KummerCharacterUnitLift R S χ`.

Mathematically, this constructor packages the Kummer-theoretic step that
turns one element of unit-decomposition data into the per-character
`(MonoidHom + injective)` over the entire χ-Kummer-component. This is
where the global Kummer-correspondence input enters. -/
def KummerCharacterUnitLift.HomPromotion.PerExtensionUnitLift
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    (R : KummerPairingRawComparison (p := p) (K := K) N T)
    (S : CyclotomicUnitModPStructure (p := p) K)
    (χ : MulChar (ZMod p)ˣ ℚ) : Prop :=
  ∀ (C : CyclotomicFieldClassGroupPSylowComponent (p := p) K),
    C.character = χ →
    ∀ (Ext : ComponentUnramifiedCyclicDegreePExtension.{u, v} (p := p) K χ C)
      (_ : KummerPipelinePerExtension.UnitDecompositionData Ext),
      Nonempty (KummerCharacterUnitLift (p := p) (K := K) R S χ)

/-- **Sub-atomic discharge** of `HomPromotion`: from a
`PerExtensionUnitLift` recipe, the promotion follows by direct application.

This is the structural step that connects the substantive
Kummer-theoretic input to the promotion contract. -/
theorem KummerCharacterUnitLift.HomPromotion.ofPerExtensionUnitLift
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    (recipe : KummerCharacterUnitLift.HomPromotion.PerExtensionUnitLift.{u, v}
      (p := p) (K := K) R S χ) :
    KummerCharacterUnitLift.HomPromotion.{u, v} (p := p) (K := K) R S χ :=
  fun C hCχ Ext data ↦ recipe C hCχ Ext data

/-- **Equivalence of `HomPromotion` with `PerExtensionUnitLift`.**

Definitional unfolding shows the two are the same Prop, modulo argument
shape. The two-way bridge makes sub-atomic refinement explicit: any
`HomPromotion` is itself a `PerExtensionUnitLift` and vice versa. -/
theorem KummerCharacterUnitLift.HomPromotion.toPerExtensionUnitLift
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    (h : KummerCharacterUnitLift.HomPromotion.{u, v} (p := p) (K := K) R S χ) :
    KummerCharacterUnitLift.HomPromotion.PerExtensionUnitLift.{u, v}
      (p := p) (K := K) R S χ :=
  fun C hCχ Ext data ↦ h C hCχ Ext data

/-! ### Family-level discharge of `HomPromotionFamily`

For the χ-indexed family, we expose a partition constructor analogous to
`KummerCharacterUnitLiftFamily.ofPartition`: at every `χ`, decide whether
the Kummer-side component is a subsingleton; if so use the trivial
discharge, otherwise consume a non-trivial recipe.
-/

/-- **Non-trivial-case promotion family.**

A χ-indexed promotion supplied only on characters whose Kummer-side
component is non-trivial; the trivial characters are handled automatically
via `HomPromotion.ofKummerComponentSubsingleton`. -/
def KummerCharacterUnitLift.NonTrivialHomPromotionFamily
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    (R : KummerPairingRawComparison (p := p) (K := K) N T)
    (S : CyclotomicUnitModPStructure (p := p) K) : Prop :=
  ∀ χ : MulChar (ZMod p)ˣ ℚ,
    ¬ Subsingleton (R.kummerComponent χ : Type _) →
    KummerCharacterUnitLift.HomPromotion.{u, v} (p := p) (K := K) R S χ

/-- **Family-level partition discharge** of `HomPromotionFamily`.

Combine the automatic trivial-case discharge with a non-trivial-case
input to obtain the full `HomPromotionFamily`. This isolates the only
substantive obligation as the non-trivial-case input. -/
theorem KummerCharacterUnitLift.HomPromotionFamily.ofPartition
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    (nonTrivial :
      KummerCharacterUnitLift.NonTrivialHomPromotionFamily.{u, v}
        (p := p) (K := K) R S) :
    KummerCharacterUnitLift.HomPromotionFamily.{u, v} (p := p) (K := K) R S := by
  classical
  intro χ
  by_cases h : Subsingleton (R.kummerComponent χ : Type _)
  · exact
      KummerCharacterUnitLift.HomPromotion.ofKummerComponentSubsingleton
        (p := p) (K := K) (R := R) (S := S) (χ := χ)
  · exact nonTrivial χ h

/-- **All-trivial family discharge** of `HomPromotionFamily`.

When *every* Kummer-side χ-component is a subsingleton, the family is built
entirely from the trivial-case discharge — no substantive input required. -/
theorem KummerCharacterUnitLift.HomPromotionFamily.ofAllTrivial
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    (h : ∀ χ : MulChar (ZMod p)ˣ ℚ, Subsingleton (R.kummerComponent χ : Type _)) :
    KummerCharacterUnitLift.HomPromotionFamily.{u, v} (p := p) (K := K) R S :=
  KummerCharacterUnitLift.HomPromotionFamily.ofPartition
    (p := p) (K := K) (R := R) (S := S)
    (fun χ habs ↦ absurd (h χ) habs)

/-! ### Sub-atomic refinement of `KummerCharacterUnitLift`

The substantive obligation to build a `KummerCharacterUnitLift` factors as
three independent sub-atoms:

* **per-element data** — a function
  `R.kummerComponent χ → (S.components.component χ).Carrier`;
* **multiplicativity** — the function respects the group operation;
* **injectivity** — the function separates Kummer classes.

We expose this factoring via the structure `KummerCharacterUnitLiftRecipe`
plus the constructor `KummerCharacterUnitLift.ofRecipe`. This isolates the
purely group-theoretic packaging from the substantive Kummer-theoretic work
(which constructs the recipe).
-/

/-- **Sub-atomic recipe for `KummerCharacterUnitLift`.**

Packages the three independent obligations needed to construct a
`KummerCharacterUnitLift`:

* `toFun` — the per-element lift,
* `map_one` and `map_mul` — multiplicativity,
* `injective` — injectivity.

A `KummerCharacterUnitLiftRecipe` is a `KummerCharacterUnitLift` modulo the
final packaging step. The substantive Kummer-theoretic content lives
entirely in producing `toFun` together with its three properties. -/
structure KummerCharacterUnitLiftRecipe
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    (R : KummerPairingRawComparison (p := p) (K := K) N T)
    (S : CyclotomicUnitModPStructure (p := p) K)
    (χ : MulChar (ZMod p)ˣ ℚ) where
  /-- The per-element lift. -/
  toFun : R.kummerComponent χ → (S.components.component χ).Carrier
  /-- Identity is preserved. -/
  map_one : toFun 1 = 1
  /-- Multiplication is preserved. -/
  map_mul : ∀ x y, toFun (x * y) = toFun x * toFun y
  /-- The lift is injective. -/
  injective : Function.Injective toFun

namespace KummerCharacterUnitLiftRecipe

variable {N : NondegenerateKummerPairing (p := p) (K := K) P}
variable {T : KummerPairingTwistData (p := p) (K := K) N}
variable {R : KummerPairingRawComparison (p := p) (K := K) N T}
variable {S : CyclotomicUnitModPStructure (p := p) K}

/-- Promote a recipe to a `MonoidHom`. -/
def toMonoidHom {χ : MulChar (ZMod p)ˣ ℚ}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ) :
    R.kummerComponent χ →* (S.components.component χ).Carrier where
  toFun := Rec.toFun
  map_one' := Rec.map_one
  map_mul' := Rec.map_mul

omit [IsCyclotomicExtension {p} ℚ K] in
/-- The underlying function of `toMonoidHom` is `toFun`. -/
@[simp] theorem toMonoidHom_apply {χ : MulChar (ZMod p)ˣ ℚ}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ)
    (x : R.kummerComponent χ) :
    Rec.toMonoidHom x = Rec.toFun x := rfl

omit [IsCyclotomicExtension {p} ℚ K] in
/-- The bundled `MonoidHom` derived from a recipe is automatically injective.

This is the "the embedded hom is injective" lemma: the recipe's injectivity
data transfers directly to the bundled `MonoidHom` via the definitional
agreement between `toMonoidHom` and `toFun`. -/
theorem toMonoidHom_injective
    {χ : MulChar (ZMod p)ˣ ℚ}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ) :
    Function.Injective Rec.toMonoidHom :=
  Rec.injective

/-- **Bundled `MonoidHom + injective` form** of a recipe.

Packages the `toMonoidHom` and `toMonoidHom_injective` data into a single
subtype, mirroring the shape consumed by `postcompMonoidHom` and
`precompMonoidHom`. -/
def toMonoidHomInjective {χ : MulChar (ZMod p)ˣ ℚ}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ) :
    { f : R.kummerComponent χ →* (S.components.component χ).Carrier //
        Function.Injective f } :=
  ⟨Rec.toMonoidHom, Rec.toMonoidHom_injective⟩

omit [IsCyclotomicExtension {p} ℚ K] in
/-- The first projection of `toMonoidHomInjective` is `toMonoidHom`. -/
@[simp] theorem toMonoidHomInjective_val {χ : MulChar (ZMod p)ˣ ℚ}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ) :
    (Rec.toMonoidHomInjective : R.kummerComponent χ →*
        (S.components.component χ).Carrier) = Rec.toMonoidHom := rfl

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **Extensionality**: two recipes with equal `toFun` are equal.

Since the remaining fields (`map_one`, `map_mul`, `injective`) are propositions
once `toFun` is fixed, equality of `toFun` suffices. -/
@[ext] theorem ext {χ : MulChar (ZMod p)ˣ ℚ}
    {Rec Rec' : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ}
    (h : Rec.toFun = Rec'.toFun) : Rec = Rec' := by
  cases Rec
  cases Rec'
  congr

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **Pointwise extensionality**: two recipes are equal whenever they agree
on every input. -/
theorem ext_iff_pointwise {χ : MulChar (ZMod p)ˣ ℚ}
    {Rec Rec' : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ} :
    Rec = Rec' ↔ ∀ x, Rec.toFun x = Rec'.toFun x :=
  ⟨fun h _ ↦ by rw [h], fun h ↦ ext (funext h)⟩

end KummerCharacterUnitLiftRecipe

/-- **Sub-atomic constructor** for `KummerCharacterUnitLift` from a recipe. -/
def KummerCharacterUnitLift.ofRecipe
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ) :
    KummerCharacterUnitLift (p := p) (K := K) R S χ where
  lift := Rec.toMonoidHom
  lift_injective := Rec.injective

/-- **Recipe-driven discharge** of `HomPromotion`.

Refines the substantive content of a non-trivial `HomPromotion` into a
per-`(C, Ext, UnitDecompositionData)` constructor of a recipe, which is
then packaged into a `KummerCharacterUnitLift`. -/
def KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    (R : KummerPairingRawComparison (p := p) (K := K) N T)
    (S : CyclotomicUnitModPStructure (p := p) K)
    (χ : MulChar (ZMod p)ˣ ℚ) : Prop :=
  ∀ (C : CyclotomicFieldClassGroupPSylowComponent (p := p) K),
    C.character = χ →
    ∀ (Ext : ComponentUnramifiedCyclicDegreePExtension.{u, v} (p := p) K χ C)
      (_ : KummerPipelinePerExtension.UnitDecompositionData Ext),
      Nonempty (KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ)

/-- A `PerExtensionRecipe` discharges `HomPromotion` by packaging each recipe
into a `KummerCharacterUnitLift`. -/
theorem KummerCharacterUnitLift.HomPromotion.ofPerExtensionRecipe
    {N : NondegenerateKummerPairing (p := p) (K := K) P}
    {T : KummerPairingTwistData (p := p) (K := K) N}
    {R : KummerPairingRawComparison (p := p) (K := K) N T}
    {S : CyclotomicUnitModPStructure (p := p) K}
    {χ : MulChar (ZMod p)ˣ ℚ}
    (recipe :
      KummerCharacterUnitLift.HomPromotion.PerExtensionRecipe.{u, v}
        (p := p) (K := K) R S χ) :
    KummerCharacterUnitLift.HomPromotion.{u, v} (p := p) (K := K) R S χ :=
  fun C hCχ Ext data ↦
    let ⟨Rec⟩ := recipe C hCχ Ext data
    ⟨KummerCharacterUnitLift.ofRecipe (p := p) (K := K) (R := R) (S := S)
      (χ := χ) Rec⟩

/-! ### Concrete recipe constructors

The following constructors expose the most common ways to *build* a
`KummerCharacterUnitLiftRecipe` from minimal mathematical data:

* **`KummerCharacterUnitLiftRecipe.trivial`** — the trivial recipe sending
  every Kummer-component element to the identity in the target carrier.
  Injective when the source is a subsingleton; vacuous otherwise.
* **`KummerCharacterUnitLiftRecipe.ofMonoidHom`** — wrap a pre-built
  injective `MonoidHom` as a recipe (the free direction).
* **`KummerCharacterUnitLiftRecipe.ofPointwiseUnit`** — assemble a recipe
  from a per-element function `R.kummerComponent χ → CyclotomicUnitGroup K`
  (a `(𝓞_K)ˣ`-valued lift) that lands in the χ-component carrier of
  `S.components`, together with multiplicativity and injectivity data.
  This is the *concrete pattern* that the Kummer-correspondence supplies:
  given a unit `u_χ ∈ (𝓞_K)ˣ` per Kummer class, the χ-component recipe
  is the obvious composition `[γ] ↦ [u_χ]` modulo `p`-th powers.
-/

namespace KummerCharacterUnitLiftRecipe

variable {N : NondegenerateKummerPairing (p := p) (K := K) P}
variable {T : KummerPairingTwistData (p := p) (K := K) N}
variable {R : KummerPairingRawComparison (p := p) (K := K) N T}
variable {S : CyclotomicUnitModPStructure (p := p) K}

/-- **Trivial recipe**: when the Kummer-side χ-component is a subsingleton,
the constant `1` map is a recipe. Multiplicativity is automatic, and
injectivity follows from the subsingleton hypothesis.

This is the recipe-level analogue of
`KummerCharacterUnitLift.ofKummerComponentSubsingleton` and is the natural
input feeding the trivial-case discharge of `PerExtensionRecipe`. -/
def trivial {χ : MulChar (ZMod p)ˣ ℚ}
    [Subsingleton (R.kummerComponent χ : Type _)] :
    KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ where
  toFun := fun _ ↦ 1
  map_one := rfl
  map_mul := fun _ _ ↦ by simp only [mul_one]
  injective := Function.injective_of_subsingleton _

/-- **Free direction**: a pre-built injective `MonoidHom` packages directly
into a recipe. The `toFun` is the underlying function and the three
properties unfold from the hom data plus the injectivity hypothesis. -/
def ofMonoidHom {χ : MulChar (ZMod p)ˣ ℚ}
    (f : R.kummerComponent χ →* (S.components.component χ).Carrier)
    (hf : Function.Injective f) :
    KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ where
  toFun := f
  map_one := f.map_one
  map_mul := f.map_mul
  injective := hf

omit [IsCyclotomicExtension {p} ℚ K] in
/-- The recipe assembled from `ofMonoidHom` round-trips through `toMonoidHom`. -/
@[simp] theorem toMonoidHom_ofMonoidHom {χ : MulChar (ZMod p)ˣ ℚ}
    (f : R.kummerComponent χ →* (S.components.component χ).Carrier)
    (hf : Function.Injective f) :
    (ofMonoidHom (R := R) (S := S) (χ := χ) f hf).toMonoidHom = f := by
  ext x; rfl

/-- **Concrete constructor `ofPointwiseUnit`**.

Given a per-Kummer-class function `liftFun` into the χ-component carrier of
the unit-quotient structure, together with multiplicativity (`liftFun_mul`)
and injectivity (`liftFun_injective`) data, assemble a recipe.

`liftFun_one` is automatically derivable from `liftFun_mul` together with
the cancellation property of the target group, but we supply it explicitly
to keep the constructor robust to unfolding of the source group structure
(the trivial-case `liftFun ≡ 1` recipe goes through this constructor too).

Mathematically, this is the shape produced by the unramified Kummer
correspondence: each Kummer class `[γ_χ] ∈ R.kummerComponent χ` is sent
to its unit factor `[u_χ]` in `(𝓞_K)ˣ/((𝓞_K)ˣ)^p`, projected into the
χ-component of the unit quotient. -/
def ofPointwiseUnit {χ : MulChar (ZMod p)ˣ ℚ}
    (liftFun : R.kummerComponent χ → (S.components.component χ).Carrier)
    (liftFun_one : liftFun 1 = 1)
    (liftFun_mul :
      ∀ x y : R.kummerComponent χ, liftFun (x * y) = liftFun x * liftFun y)
    (liftFun_injective : Function.Injective liftFun) :
    KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ where
  toFun := liftFun
  map_one := liftFun_one
  map_mul := liftFun_mul
  injective := liftFun_injective

/-! ### Refined / atomic constructors for `KummerCharacterUnitLiftRecipe`

The following batch of constructors expose more fine-grained, structural
ways to *build* a recipe from common categorical/algebraic data:

* **`ofMulEquiv`** — promote a `MulEquiv` between source and target into
  a recipe. Injectivity is automatic (`MulEquiv.injective`) and
  multiplicativity comes for free from the `MulEquiv` data.

* **`refl`** — the identity-style recipe constructed from `MulEquiv.refl`,
  for the (rare) case where the source and target are literally the same
  type. This is the categorical identity element of the recipe API.

* **`ofMonoidHomEquiv`** — given a `MulEquiv` between source and target
  *together with* an explicit injective `MonoidHom` derived from it,
  package the result as a recipe. This is a refinement over
  `ofMulEquiv` that lets the caller plug in a precomputed `MonoidHom`
  rather than the bundled `MulEquiv.toMonoidHom`.

* **`compose`** — pre-compose a recipe with a `MulEquiv` on the source
  and post-compose with a `MulEquiv` on the target simultaneously.
  Useful when transporting a recipe across a pair of isomorphisms.

* **`congrSource`** / **`congrTarget`** — change the source / target
  via a `MulEquiv` while preserving the recipe data. These are the
  unilateral specialisations of `compose`.

* **`postcompMonoidHom`** — post-compose a recipe with an injective
  `MonoidHom` on the target (yielding a `MonoidHom + injective` pair
  instead of a recipe, since the target type changes).

* **`precompMonoidHom`** — pre-compose a recipe with an injective
  `MonoidHom` on the source (likewise yielding a `MonoidHom +
  injective` pair).

These constructors are all *purely structural*: they assume the
substantive Kummer-theoretic content is already encoded in the input
data and merely repackage it.
-/

/-- **From a `MulEquiv`**: a multiplicative equivalence between the
Kummer χ-component and the unit-quotient χ-component packages into a
recipe whose `toFun` is the underlying function and whose properties
follow from the `MulEquiv` data plus its injectivity. -/
def ofMulEquiv {χ : MulChar (ZMod p)ˣ ℚ}
    (e : R.kummerComponent χ ≃* (S.components.component χ).Carrier) :
    KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ where
  toFun := e
  map_one := e.map_one
  map_mul := e.map_mul
  injective := e.injective

omit [IsCyclotomicExtension {p} ℚ K] in
/-- The recipe assembled from `ofMulEquiv` round-trips through `toMonoidHom`. -/
@[simp] theorem toMonoidHom_ofMulEquiv {χ : MulChar (ZMod p)ˣ ℚ}
    (e : R.kummerComponent χ ≃* (S.components.component χ).Carrier) :
    (ofMulEquiv (R := R) (S := S) (χ := χ) e).toMonoidHom = e.toMonoidHom := by
  ext x; rfl

/-- **Identity recipe** (`refl`): the recipe constructed from a
`MulEquiv` between the Kummer χ-component and the unit-quotient
χ-component, viewed as the *identity-style* recipe — it ignores any
substantive Kummer-theoretic content and returns the equivalence as the
recipe's `toFun`.

This is the categorical identity of the recipe API: under any
identification of source and target via a `MulEquiv`, the recipe is
"the identity of that identification".  It is definitionally
synonymous with `ofMulEquiv` but exists as a distinct name to mark the
"do nothing" usage pattern.

In synthetic contexts where the source and target are literally the
same type (e.g.\ via an upstream definitional rewrite), the caller can
supply `MulEquiv.refl _` and obtain the literal identity recipe. -/
def refl {χ : MulChar (ZMod p)ˣ ℚ}
    (e : R.kummerComponent χ ≃* (S.components.component χ).Carrier) :
    KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ :=
  ofMulEquiv (R := R) (S := S) (χ := χ) e

omit [IsCyclotomicExtension {p} ℚ K] in
/-- `refl` agrees with `ofMulEquiv` on the underlying function. -/
@[simp] theorem refl_toFun {χ : MulChar (ZMod p)ˣ ℚ}
    (e : R.kummerComponent χ ≃* (S.components.component χ).Carrier) :
    (refl (R := R) (S := S) (χ := χ) e).toFun = e := rfl

omit [IsCyclotomicExtension {p} ℚ K] in
/-- `refl` and `ofMulEquiv` are the same recipe. -/
theorem refl_eq_ofMulEquiv
    {χ : MulChar (ZMod p)ˣ ℚ}
    (e : R.kummerComponent χ ≃* (S.components.component χ).Carrier) :
    refl (R := R) (S := S) (χ := χ) e =
      ofMulEquiv (R := R) (S := S) (χ := χ) e := rfl

/-- **From a `MulEquiv` plus a precomputed `MonoidHom`**: the equivalence
provides injectivity, while the supplied `MonoidHom` provides the
underlying function. The two are required to agree pointwise via
`hAgree`.

This is the most permissive bundling: it lets the caller plug in any
`MonoidHom` known to come from an injective `MulEquiv` without forcing
the caller to use `MulEquiv.toMonoidHom` explicitly. -/
def ofMonoidHomEquiv {χ : MulChar (ZMod p)ˣ ℚ}
    (f : R.kummerComponent χ →* (S.components.component χ).Carrier)
    (e : R.kummerComponent χ ≃* (S.components.component χ).Carrier)
    (hAgree : ∀ x, f x = e x) :
    KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ where
  toFun := f
  map_one := f.map_one
  map_mul := f.map_mul
  injective := fun x y hxy ↦ e.injective (by
    rw [← hAgree x, ← hAgree y]; exact hxy)

/-- **Source-congruence**: replace the source via a `MulEquiv`
`e : R'.kummerComponent χ ≃* R.kummerComponent χ`.

When the Kummer-side χ-component of one comparison is `MulEquiv`-isomorphic
to that of another, a recipe for the second transports into a recipe for
the first.  This is the natural "renaming of the Kummer side" operation. -/
def congrSource {χ : MulChar (ZMod p)ˣ ℚ}
    {R' : KummerPairingRawComparison (p := p) (K := K) N T}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ)
    (e : R'.kummerComponent χ ≃* R.kummerComponent χ) :
    KummerCharacterUnitLiftRecipe (p := p) (K := K) R' S χ where
  toFun := fun x ↦ Rec.toFun (e x)
  map_one := by simp only [_root_.map_one, Rec.map_one]
  map_mul := fun x y ↦ by simp only [_root_.map_mul, Rec.map_mul]
  injective := fun x y h ↦ e.injective (Rec.injective h)

/-- **Target-congruence**: replace the target via a `MulEquiv`
`e : (S.components.component χ).Carrier ≃* (S'.components.component χ).Carrier`.

When the unit-quotient χ-components of two structures are `MulEquiv`-isomorphic,
a recipe targeting the first transports into a recipe targeting the second. -/
def congrTarget {χ : MulChar (ZMod p)ˣ ℚ}
    {S' : CyclotomicUnitModPStructure (p := p) K}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ)
    (e : (S.components.component χ).Carrier ≃*
      (S'.components.component χ).Carrier) :
    KummerCharacterUnitLiftRecipe (p := p) (K := K) R S' χ where
  toFun := fun x ↦ e (Rec.toFun x)
  map_one := by simp only [Rec.map_one, _root_.map_one]
  map_mul := fun x y ↦ by simp only [Rec.map_mul, _root_.map_mul]
  injective := fun x y h ↦ Rec.injective (e.injective h)

/-- **Bilateral congruence**: simultaneously change source and target via
`MulEquiv`s. This is the composite of `congrSource` and `congrTarget`. -/
def compose {χ : MulChar (ZMod p)ˣ ℚ}
    {R' : KummerPairingRawComparison (p := p) (K := K) N T}
    {S' : CyclotomicUnitModPStructure (p := p) K}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ)
    (eSource : R'.kummerComponent χ ≃* R.kummerComponent χ)
    (eTarget : (S.components.component χ).Carrier ≃*
      (S'.components.component χ).Carrier) :
    KummerCharacterUnitLiftRecipe (p := p) (K := K) R' S' χ :=
  (Rec.congrSource (R' := R') eSource).congrTarget (S' := S') eTarget

/-- **Post-compose** with an injective `MonoidHom` on the target.

Given a recipe and an injective hom `g : (S.components.component χ).Carrier →* H'`,
the composition `g ∘ Rec.toFun` is an injective hom into `H'`, packaged
as a `MonoidHom + injective` pair. This is *not* a
`KummerCharacterUnitLiftRecipe` because the target shape changes. -/
def postcompMonoidHom {χ : MulChar (ZMod p)ˣ ℚ}
    (Rec : KummerCharacterUnitLiftRecipe (p := p) (K := K) R S χ)
    {H' : Type*} [Group H']
    (g : (S.components.component χ).Carrier →* H') (hg : Function.Injective g) :
    { f : R.kummerComponent χ →* H' // Function.Injective f } :=
  ⟨g.comp Rec.toMonoidHom, hg.comp Rec.injective⟩

end KummerCharacterUnitLiftRecipe
end KummerToUnitQuotientComposer
end BernoulliRegular

end
