import PadicLFunctions.Iwasawa.StructureTheory.PseudoIso
import Mathlib.RingTheory.PowerSeries.Ideal
import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.DiscreteValuationRing.TFAE
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.Ideal.AssociatedPrime.Finiteness

/-!
# The structure theorem for finitely generated Λ-modules  (S13-S3)

Washington, *Introduction to Cyclotomic Fields*, Thm 13.12 (= RJW TeX 3637–3642,
stated there without proof): every finitely generated `Λ = 𝒪⟦T⟧`-module is
pseudo-isomorphic to a canonical sum of a free part and cyclic prime-power parts.

This is the one genuinely deep build of Stage S.  `Λ` is **not** a PID (it has
Krull dimension `2`), so mathlib's PID structure theorem (`Module.equiv_directSum_of_isTorsion`)
does *not* apply directly.  The standard proof — decomposed **at execution** (board
ticket S13-S3 is a cluster) — runs:

* **S3a**: `Λ` is a Noetherian, integrally closed (Krull) regular local domain of
  dimension `2`, hence a UFD.  (mathlib `PowerSeries` over a complete DVR.)
* **S3b**: each height-one prime `𝔭 ⊂ Λ` localises to a DVR `Λ_𝔭` (hence a PID).
* **S3c**: over each `Λ_𝔭`, mathlib's `Module.equiv_directSum_of_isTorsion` gives
  the elementary divisors (the PID structure theorem — *reuse*).
* **S3d**: the pseudo-isomorphism gluing over the finite support of height-one
  primes; the finite kernel/cokernel is the pseudo-null discrepancy.  **This is the
  genuinely new content** — `Λ`-modules are not `⊕`-decomposable on the nose,
  unlike over a PID.

## Main declarations

* `Iwasawa.fg_pseudoIso_canonical`: the structure theorem in clean prime-power
  form — `M ~ Λ^r × ⨁ Λ/(gᵢ^eᵢ)` with each `gᵢ` prime.
* `Iwasawa.fg_pseudoIso_washington`: the refined Washington normal form, separating
  the uniformiser-power factors `Λ/(ϖ^nᵢ)` (the μ-part) from the
  distinguished-irreducible-power factors `Λ/(fⱼ^mⱼ)` (the λ-part), via Weierstrass
  preparation (S13-S1).  This is RJW TeX 3637–3642 / Washington Thm 13.12 verbatim.
* `Iwasawa.iwasawaAlgebra_isNoetherianRing`: foundation stub S3a.
-/

noncomputable section

open DirectSum

namespace Iwasawa

variable (𝒪 : Type*) [CommRing 𝒪]

local notation "Λ" => IwasawaAlgebra 𝒪

/-- **S3a (foundation)**: the Iwasawa algebra `Λ = 𝒪⟦T⟧` is a Noetherian ring (when
`𝒪` is).  Part of the ring-theory input to the structure theorem (`Λ` is in fact a
2-dimensional regular local UFD when `𝒪` is a complete DVR). -/
theorem iwasawaAlgebra_isNoetherianRing [IsNoetherianRing 𝒪] :
    IsNoetherianRing (IwasawaAlgebra 𝒪) :=
  inferInstance

/-- **S3a (foundation)**: when `𝒪` is an integral domain, so is `Λ = 𝒪⟦T⟧`. -/
theorem iwasawaAlgebra_isDomain [IsDomain 𝒪] : IsDomain (IwasawaAlgebra 𝒪) :=
  inferInstance

/-- **S3a (foundation)**: when `𝒪` is a discrete valuation ring (a PID domain, e.g.
`𝒪 = ℤ_p`), the Iwasawa algebra `Λ = 𝒪⟦T⟧` is a unique factorisation monoid.  This is
the UFD input to the structure theorem (every height-one prime of `Λ` is principal,
generated either by the uniformiser of `𝒪` or by a distinguished irreducible). -/
theorem iwasawaAlgebra_uniqueFactorizationMonoid [IsDomain 𝒪] [IsPrincipalIdealRing 𝒪] :
    UniqueFactorizationMonoid (IwasawaAlgebra 𝒪) :=
  inferInstance

/-- **S13-S3b**: the localisation of the UFD `Λ = 𝒪⟦T⟧` at a height-one prime ideal `(π)`
(`π` a prime element) is a discrete valuation ring.  This is the geometric input to the
structure theorem: at each height-one prime `Λ` localises to a DVR, where mathlib's PID
structure theorem (`Module.equiv_directSum_of_isTorsion`) applies.  A localisation at a
prime is local; localisation of a Noetherian domain is a Noetherian domain; the maximal
ideal is the principal ideal generated by `π`; a Noetherian local domain with nonzero
principal maximal ideal is a DVR. -/
theorem iwasawaAlgebra_localization_atPrime_isDVR
    [IsDomain 𝒪] [IsPrincipalIdealRing 𝒪]
    {π : IwasawaAlgebra 𝒪} (hπ : Prime π)
    [(Ideal.span {π} : Ideal (IwasawaAlgebra 𝒪)).IsPrime] :
    IsDiscreteValuationRing
      (Localization.AtPrime (Ideal.span {π} : Ideal (IwasawaAlgebra 𝒪))) := by
  haveI : IsNoetherianRing (Localization.AtPrime (Ideal.span {π} : Ideal (IwasawaAlgebra 𝒪))) :=
    IsLocalization.isNoetherianRing (Ideal.span {π}).primeCompl _ inferInstance
  haveI : IsDomain (Localization.AtPrime (Ideal.span {π} : Ideal (IwasawaAlgebra 𝒪))) :=
    inferInstance
  -- the maximal ideal is principal, generated by the image of `π`
  have hprinc : (IsLocalRing.maximalIdeal
      (Localization.AtPrime (Ideal.span {π} : Ideal (IwasawaAlgebra 𝒪)))).IsPrincipal := by
    rw [← Localization.AtPrime.map_eq_maximalIdeal, Ideal.map_span, Set.image_singleton]
    exact ⟨⟨_, rfl⟩⟩
  -- `π` maps to a nonzero element (the localisation map is injective on the domain `Λ`)
  have hinj : Function.Injective
      (algebraMap (IwasawaAlgebra 𝒪) (Localization.AtPrime (Ideal.span {π}))) :=
    IsLocalization.injective _ (Ideal.primeCompl_le_nonZeroDivisors (Ideal.span {π}))
  have hπ0 : (algebraMap (IwasawaAlgebra 𝒪) (Localization.AtPrime (Ideal.span {π}))) π ≠ 0 :=
    fun h => hπ.ne_zero (hinj (by rwa [map_zero]))
  -- hence the maximal ideal is nonzero, so the localisation is not a field
  have hnf : ¬ IsField (Localization.AtPrime (Ideal.span {π} : Ideal (IwasawaAlgebra 𝒪))) := by
    rw [IsLocalRing.isField_iff_maximalIdeal_eq]
    intro hbot
    refine hπ0 ?_
    have hmem : (algebraMap (IwasawaAlgebra 𝒪) (Localization.AtPrime (Ideal.span {π}))) π
        ∈ IsLocalRing.maximalIdeal (Localization.AtPrime (Ideal.span {π})) := by
      rw [← Localization.AtPrime.map_eq_maximalIdeal]
      exact Ideal.mem_map_of_mem _ (Ideal.mem_span_singleton_self π)
    rwa [hbot, Ideal.mem_bot] at hmem
  exact ((IsDiscreteValuationRing.TFAE
    (Localization.AtPrime (Ideal.span {π} : Ideal (IwasawaAlgebra 𝒪))) hnf).out 4 0).mp hprinc

/-- **S13-S3d (support finiteness)**: a finitely generated `Λ`-module has only finitely
many associated primes.  These cut out the finite set of height-one primes over which the
structure theorem's local (DVR) pieces live — the index set of the eventual direct sum. -/
theorem iwasawaAlgebra_associatedPrimes_finite [IsNoetherianRing 𝒪]
    (M : Type*) [AddCommGroup M] [Module (IwasawaAlgebra 𝒪) M]
    [Module.Finite (IwasawaAlgebra 𝒪) M] :
    (associatedPrimes (IwasawaAlgebra 𝒪) M).Finite :=
  associatedPrimes.finite (IwasawaAlgebra 𝒪) M

/-- **The structure theorem (clean form), S13-S3 / Washington Thm 13.12.**
Every finitely generated `Λ`-module `M` is pseudo-isomorphic to `Λ^r ⊕ ⨁ᵢ Λ/(gᵢ^eᵢ)`
for a free rank `r` and finitely many cyclic prime-power quotients (`gᵢ` prime in
`Λ`).  For a *torsion* module `r = 0`.  (RJW TeX 3637–3642.)

The **finite residue field** hypothesis `[Finite (ResidueField 𝒪)]` is essential: since
`IsPseudoIso` uses finite (cardinality) kernel/cokernel, the conclusion forces pseudo-null
modules to be finite, which holds iff `𝒪/𝔪` is finite (the standing case `𝒪 = ℤ_p`,
`ResidueField = 𝔽_p`).  Without it the statement is false — e.g. `M = Λ/𝔪` over `𝒪 = k⟦s⟧`
with `k` infinite is f.g. torsion but admits no pseudo-isomorphism to any such sum. -/
theorem fg_pseudoIso_canonical
    [IsLocalRing 𝒪] [Finite (IsLocalRing.ResidueField 𝒪)]
    (M : Type*) [AddCommGroup M] [Module (IwasawaAlgebra 𝒪) M]
    [Module.Finite (IwasawaAlgebra 𝒪) M] :
    ∃ (r k : ℕ) (g : Fin k → IwasawaAlgebra 𝒪) (e : Fin k → ℕ),
      (∀ i, Prime (g i)) ∧
      IsPseudoIso 𝒪 M
        ((Fin r → IwasawaAlgebra 𝒪) ×
          ⨁ i : Fin k, IwasawaAlgebra 𝒪 ⧸ Ideal.span {g i ^ e i}) := by
  sorry

variable [IsLocalRing 𝒪]

/-- **S3a (foundation)**: when `𝒪` is a local ring, so is `Λ = 𝒪⟦T⟧` (its maximal ideal
is `(𝔪, T)`).  This is the local ring whose module theory the structure theorem
describes. -/
theorem iwasawaAlgebra_isLocalRing : IsLocalRing (IwasawaAlgebra 𝒪) :=
  inferInstance

/-- **The structure theorem (Washington normal form), S13-S3.**
The refinement of `fg_pseudoIso_canonical` via Weierstrass preparation (S13-S1):
every finitely generated `Λ`-module is pseudo-isomorphic to
`Λ^r ⊕ ⨁ᵢ Λ/(ϖ^nᵢ) ⊕ ⨁ⱼ Λ/(fⱼ^mⱼ)`, where `ϖ` is a uniformiser of `𝒪` (the μ-part)
and the `fⱼ` are distinguished irreducible polynomials (the λ-part).  This is RJW
TeX 3637–3642 / Washington, *Cyclotomic Fields*, Thm 13.12, verbatim. -/
theorem fg_pseudoIso_washington [Finite (IsLocalRing.ResidueField 𝒪)]
    (ϖ : 𝒪) (hϖ : Irreducible ϖ)
    (M : Type*) [AddCommGroup M] [Module (IwasawaAlgebra 𝒪) M]
    [Module.Finite (IwasawaAlgebra 𝒪) M] :
    ∃ (r s t : ℕ) (n : Fin s → ℕ) (f : Fin t → Polynomial 𝒪) (m : Fin t → ℕ),
      (∀ j, IsDistinguished 𝒪 (f j) ∧ Irreducible (f j)) ∧
      IsPseudoIso 𝒪 M
        ((Fin r → IwasawaAlgebra 𝒪) ×
          (⨁ i : Fin s, IwasawaAlgebra 𝒪 ⧸
            Ideal.span {(algebraMap 𝒪 (IwasawaAlgebra 𝒪) ϖ) ^ n i}) ×
          (⨁ j : Fin t, IwasawaAlgebra 𝒪 ⧸
            Ideal.span {((f j : IwasawaAlgebra 𝒪)) ^ m j})) := by
  sorry

end Iwasawa
