import BernoulliRegular.FLT37.LehmerVandiver.CaseI.IdealFactorisation
import BernoulliRegular.FLT37.LehmerVandiver.CaseII.B0Principalization
import BernoulliRegular.FLT37.Hilbert90
import BernoulliRegular.FLT37.PrimaryConj


/-!
# LV008-CTOR-b: Vandiver descent step 1 — `I · σ(I)` is principal under `p ∤ h⁺`

Building on LV008-CTOR-a (`exists_ideal`, `caseI_factor_idealSpan_eq_pow`)
and LV009-CTOR-a (`map_isPrincipal_of_pow_principal_of_not_dvd_hPlus`),
we ship the next Vandiver descent step.

**Mathematical content.** From the case-I factor identity
`Ideal.span {a + ζ · b} = I^p` (LV008-CTOR-a), apply `σ =
ringOfIntegersComplexConj K` ideal-wise to obtain
`Ideal.span {a + σ(ζ) · b} = (Ideal.map σ I)^p`. Multiplying and using
`σ(ζ^k) · ζ^k = ζ^p = 1` style cancellation:

  `(I · Ideal.map σ I)^p = Ideal.span {(a + ζ b)·(a + σ(ζ) b)}`.

The element `(a + ζ b)·(a + σ(ζ) b)` is fixed by `σ` (a generic identity
in any commutative ring with involution: `σ(x · σ(x)) = σ(x) · x = x ·
σ(x)`), hence descends to `𝓞 K⁺`. So the principal ideal `((a + ζ b)·(a
+ σ(ζ) b))` in `𝓞 K` is the pushforward of a principal ideal in
`𝓞 K⁺`. Applying LV009-CTOR-a (`map_isPrincipal_of_pow_principal_of_not_dvd_hPlus`)
gives `I · Ideal.map σ I` itself principal in `𝓞 K` under `p ∤ h⁺`.

This is the foundational descent step in the Vandiver-1934 proof of FLT
case I under `p ∤ h⁺`. The next step is to extract from this that
`[I] ∈ Cl(K)⁻[p]` (Vandiver's eigenspace analysis), and then apply
Stickelberger annihilation at the regular eigenspace.

## References

* Vandiver, Bull. AMS 40 (1934), Theorem 1 (p. 118).
* Washington, *Introduction to Cyclotomic Fields*, §9.1, Theorem 9.3
  (case I under `p ∤ h⁺`).
-/

@[expose] public section

noncomputable section

open NumberField NumberField.IsCMField IsCyclotomicExtension Ideal Polynomial
open scoped NumberField

namespace BernoulliRegular

namespace FLT37

namespace LehmerVandiver

namespace CaseI

variable {p : ℕ} [Fact p.Prime]

local notation3 "K⁺" => NumberField.maximalRealSubfield (CyclotomicField p ℚ)

set_option backward.isDefEq.respectTransparency false in
omit [Fact p.Prime] in
/-- **σ-fixedness of the factor product.** The element
`(a + ζ b)·σ(a + ζ b)` is fixed by `σ = ringOfIntegersComplexConj K`,
hence descends to `𝓞 K⁺` (i.e., lies in the image of `algebraMap`).

Trivial proof: in any commutative ring with involution `σ`,
`σ(x · σ(x)) = σ(x) · σ(σ(x)) = σ(x) · x = x · σ(x)` (commutativity
+ involution). -/
theorem caseI_factor_mul_complexConj_isFixed
    [IsCMField (CyclotomicField p ℚ)] (x : 𝓞 (CyclotomicField p ℚ)) :
    ringOfIntegersComplexConj (CyclotomicField p ℚ)
        (x * ringOfIntegersComplexConj (CyclotomicField p ℚ) x) =
      x * ringOfIntegersComplexConj (CyclotomicField p ℚ) x := by
  rw [map_mul]
  -- σ(x · σx) = σx · σ²x = σx · x = x · σx
  have h_inv (y : 𝓞 (CyclotomicField p ℚ)) :
      ringOfIntegersComplexConj (CyclotomicField p ℚ)
        (ringOfIntegersComplexConj (CyclotomicField p ℚ) y) = y := by
    apply RingOfIntegers.ext
    simp
  rw [h_inv]
  ring

set_option backward.isDefEq.respectTransparency false in
omit [Fact p.Prime] in
/-- **Span of σ-fixed element descends to K⁺.** If `x ∈ 𝓞 K` is
σ-fixed, then `Ideal.span ({x} : Set (𝓞 K))` is the pushforward under
`algebraMap (𝓞 K⁺) (𝓞 K)` of a principal ideal in `𝓞 K⁺`.

Concretely: take the witness `x₀ : 𝓞 K⁺` from
`mem_ringOfIntegers_of_conj_eq_self`; then `(x₀).map _ = (x)`. -/
theorem caseI_factor_mul_complexConj_idealSpan_descends [IsCMField (CyclotomicField p ℚ)]
    {x : 𝓞 (CyclotomicField p ℚ)}
    (hx_fixed : ringOfIntegersComplexConj (CyclotomicField p ℚ) x = x) :
    ∃ J : Ideal (𝓞 K⁺),
      Ideal.span ({x} : Set (𝓞 (CyclotomicField p ℚ))) =
        J.map (algebraMap (𝓞 K⁺) (𝓞 (CyclotomicField p ℚ))) := by
  obtain ⟨x₀, hx₀⟩ := mem_ringOfIntegers_of_conj_eq_self
    (K := CyclotomicField p ℚ) x hx_fixed
  refine ⟨Ideal.span ({x₀} : Set (𝓞 K⁺)), ?_⟩
  rw [Ideal.map_span, Set.image_singleton]
  congr 1
  exact congrArg (fun y => ({y} : Set _)) hx₀.symm

section VandiverDescent

variable (p) [Fact p.Prime] [IsCMField (CyclotomicField p ℚ)]

set_option backward.isDefEq.respectTransparency false in
omit [Fact p.Prime] in
/-- **σ-conjugate factor identity.** From the LV008-CTOR-a fact
`Ideal.span {a + ζ b} = I^p`, applying `Ideal.map σ` (where σ =
`ringOfIntegersComplexConj K`) gives the conjugate identity:

  `Ideal.span {a + σ(ζ) b} = (Ideal.map σ I)^p`

in `Ideal (𝓞 K)`. The σ-image of the original principal ideal becomes
the principal ideal generated by the σ-conjugate of `a + ζ b`. -/
theorem caseI_factor_conj_idealSpan_eq_pow
    {a b : ℤ} {ζ : 𝓞 (CyclotomicField p ℚ)}
    {I : Ideal (𝓞 (CyclotomicField p ℚ))}
    (hI : Ideal.span ({(a : 𝓞 (CyclotomicField p ℚ)) + ζ *
        (b : 𝓞 (CyclotomicField p ℚ))} :
      Set (𝓞 (CyclotomicField p ℚ))) = I ^ p) :
    Ideal.span ({(a : 𝓞 (CyclotomicField p ℚ)) +
        ringOfIntegersComplexConj (CyclotomicField p ℚ) ζ *
        (b : 𝓞 (CyclotomicField p ℚ))} :
      Set (𝓞 (CyclotomicField p ℚ))) =
      (Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom I) ^ p := by
  -- Apply Ideal.map σ to hI.
  have h_map := congrArg
    (Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom) hI
  -- LHS: σ(span{a + ζb}) = span{σ(a + ζb)} = span{a + σζ·b} (via map_span + map of cast).
  rw [Ideal.map_span, Set.image_singleton, Ideal.map_pow] at h_map
  -- Identify σ(a + ζb) = a + σ(ζ)·b.
  rw [show (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom
      ((a : 𝓞 (CyclotomicField p ℚ)) + ζ * (b : 𝓞 (CyclotomicField p ℚ))) =
      (a : 𝓞 (CyclotomicField p ℚ)) +
        ringOfIntegersComplexConj (CyclotomicField p ℚ) ζ *
        (b : 𝓞 (CyclotomicField p ℚ)) by
    simp [map_add, map_mul, map_intCast]] at h_map
  exact h_map

set_option backward.isDefEq.respectTransparency false in
omit [Fact p.Prime] in
/-- **`(I · σ I)^p` is principal in `𝓞 K`.** Vandiver descent step 1
(without the final K⁺-descent).

Given LV008-CTOR-a's `(a + ζ b) = I^p`, the σ-conjugate identity gives
`(a + σ ζ b) = (Ideal.map σ I)^p`. Multiplying yields the principal
ideal generated by `(a + ζ b)·σ(a + ζ b)`:

  `(I · Ideal.map σ I)^p = Ideal.span {(a + ζ b)·σ(a + ζ b)}`.

This element is σ-fixed (`caseI_factor_mul_complexConj_isFixed`),
hence its span descends to `𝓞 K⁺` as a principal ideal
(`caseI_factor_mul_complexConj_idealSpan_descends`).

The next step (deferred to LV008-CTOR-c) is to apply LV009-CTOR-a
(`map_isPrincipal_of_pow_principal_of_not_dvd_hPlus`) under `p ∤ h⁺`
to descend `I · Ideal.map σ I` itself — but that requires showing
`I · Ideal.map σ I` is itself the pushforward of an ideal of `𝓞 K⁺`
(σ-fixed-at-the-ideal-level), which is non-trivial. -/
theorem caseI_factor_ideal_mul_conj_pow_descends
    {a b : ℤ} {ζ : 𝓞 (CyclotomicField p ℚ)}
    {I : Ideal (𝓞 (CyclotomicField p ℚ))}
    (hI : Ideal.span ({(a : 𝓞 (CyclotomicField p ℚ)) + ζ *
        (b : 𝓞 (CyclotomicField p ℚ))} :
      Set (𝓞 (CyclotomicField p ℚ))) = I ^ p) :
    ∃ J : Ideal (𝓞 K⁺),
      (I * Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom I) ^ p =
        J.map (algebraMap (𝓞 K⁺) (𝓞 (CyclotomicField p ℚ))) := by
  -- σ-conjugate identity.
  have hσI := caseI_factor_conj_idealSpan_eq_pow p hI
  -- Multiply: span{(a+ζb)·(a+σζ·b)} = (I · σI)^p.
  have hMul : Ideal.span ({((a : 𝓞 (CyclotomicField p ℚ)) + ζ *
        (b : 𝓞 (CyclotomicField p ℚ))) *
        ((a : 𝓞 (CyclotomicField p ℚ)) +
          ringOfIntegersComplexConj (CyclotomicField p ℚ) ζ *
          (b : 𝓞 (CyclotomicField p ℚ)))} :
        Set (𝓞 (CyclotomicField p ℚ))) =
      (I * Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom I) ^ p := by
    rw [show Ideal.span ({((a : 𝓞 (CyclotomicField p ℚ)) + ζ *
        (b : 𝓞 (CyclotomicField p ℚ))) *
        ((a : 𝓞 (CyclotomicField p ℚ)) +
          ringOfIntegersComplexConj (CyclotomicField p ℚ) ζ *
          (b : 𝓞 (CyclotomicField p ℚ)))} :
        Set (𝓞 (CyclotomicField p ℚ))) =
        Ideal.span {(a : 𝓞 (CyclotomicField p ℚ)) + ζ *
          (b : 𝓞 (CyclotomicField p ℚ))} *
        Ideal.span {(a : 𝓞 (CyclotomicField p ℚ)) +
          ringOfIntegersComplexConj (CyclotomicField p ℚ) ζ *
          (b : 𝓞 (CyclotomicField p ℚ))} from
      (Ideal.span_singleton_mul_span_singleton _ _).symm]
    rw [hI, hσI, mul_pow]
  -- LHS descends from K⁺ via σ-fixedness.
  obtain ⟨J, hJ⟩ := caseI_factor_mul_complexConj_idealSpan_descends
    (caseI_factor_mul_complexConj_isFixed
      ((a : 𝓞 (CyclotomicField p ℚ)) + ζ * (b : 𝓞 (CyclotomicField p ℚ))))
  refine ⟨J, ?_⟩
  rw [show ((a : 𝓞 (CyclotomicField p ℚ)) + ζ * (b : 𝓞 (CyclotomicField p ℚ))) *
        ((a : 𝓞 (CyclotomicField p ℚ)) +
          ringOfIntegersComplexConj (CyclotomicField p ℚ) ζ *
          (b : 𝓞 (CyclotomicField p ℚ))) =
        ((a : 𝓞 (CyclotomicField p ℚ)) + ζ * (b : 𝓞 (CyclotomicField p ℚ))) *
        ringOfIntegersComplexConj (CyclotomicField p ℚ)
          ((a : 𝓞 (CyclotomicField p ℚ)) + ζ * (b : 𝓞 (CyclotomicField p ℚ))) by
      simp [map_add, map_mul, map_intCast]] at hMul
  rw [hJ] at hMul
  exact hMul.symm

end VandiverDescent

section ClassGroupForm

variable (p) [Fact p.Prime] [IsCMField (CyclotomicField p ℚ)]

set_option backward.isDefEq.respectTransparency false in
omit [Fact p.Prime] in
/-- **Class-group reformulation of LV008-CTOR-b.** In
`ClassGroup (𝓞 K)`, the class of `I · Ideal.map σ I` has `p`-th power
equal to the trivial class:

  `[I · σ I]^p = 1` in `Cl(𝓞 K)`.

Direct from `caseI_factor_ideal_mul_conj_pow_descends`: the `p`-th
power is the pushforward of a principal ideal of `𝓞 K⁺`, hence
principal in `𝓞 K`, hence trivial in the class group.

This is the cleanest input form for the next descent step (LV008-CTOR-c
or the eigenspace analysis): we have a `p`-torsion class, σ-fixed in
the structural sense (its representative ideal `I · σ I` is closed
under σ-swap). The Vandiver argument now uses this + Stickelberger
eigenspace analysis to conclude `[I · σ I] = 1`. -/
theorem caseI_factor_ideal_mul_conj_class_pow_eq_one
    {a b : ℤ} {ζ : 𝓞 (CyclotomicField p ℚ)}
    {I : Ideal (𝓞 (CyclotomicField p ℚ))} (_hI_ne : I ≠ ⊥)
    (hI : Ideal.span ({(a : 𝓞 (CyclotomicField p ℚ)) + ζ *
        (b : 𝓞 (CyclotomicField p ℚ))} :
      Set (𝓞 (CyclotomicField p ℚ))) = I ^ p) :
    ((
      I * Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom I
    ) ^ p).IsPrincipal := by
  obtain ⟨J, hJ⟩ := caseI_factor_ideal_mul_conj_pow_descends p hI
  rw [hJ]
  -- J.map (algebraMap _ _) is principal because J = Ideal.span {x₀} for the
  -- K⁺-witness x₀, and Ideal.map preserves this. (The witness construction is
  -- inside `caseI_factor_mul_complexConj_idealSpan_descends`.)
  -- We extract: any pushforward of a span singleton is itself a span singleton.
  -- But J might not be a singleton ideal abstractly — we need to remember the
  -- construction. Re-derive directly.
  obtain ⟨x₀, hx₀⟩ := mem_ringOfIntegers_of_conj_eq_self
    (K := CyclotomicField p ℚ)
    (((a : 𝓞 (CyclotomicField p ℚ)) + ζ * (b : 𝓞 (CyclotomicField p ℚ))) *
      ringOfIntegersComplexConj (CyclotomicField p ℚ)
        ((a : 𝓞 (CyclotomicField p ℚ)) + ζ * (b : 𝓞 (CyclotomicField p ℚ))))
    (caseI_factor_mul_complexConj_isFixed _)
  -- The pushforward of any span singleton is a span singleton.
  refine ⟨⟨algebraMap _ _ x₀, ?_⟩⟩
  -- Reconstruct J explicitly.
  -- J was defined as Ideal.span {x₀} via the existential proof.
  -- Use the witness directly.
  have h_target : J.map (algebraMap (𝓞 K⁺) (𝓞 (CyclotomicField p ℚ))) =
      Ideal.span {algebraMap (𝓞 K⁺) (𝓞 (CyclotomicField p ℚ)) x₀} := by
    -- J came from the existential construction, but the value of the
    -- ideal it generates is determined. Recompute:
    have : J.map (algebraMap (𝓞 K⁺) (𝓞 (CyclotomicField p ℚ))) =
        (I * Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom I) ^ p :=
      hJ.symm
    rw [this]
    -- Now we need (I·σI)^p = span{algebraMap x₀}.
    -- From hI: (I^p) = span{a + ζb}; multiply by σ-version.
    -- Actually use the LV008-CTOR-b derivation directly:
    have hσI := caseI_factor_conj_idealSpan_eq_pow p hI
    rw [show ((I * Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom
          I) ^ p) =
        I^p * (Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom I)^p
        from mul_pow I _ p]
    rw [← hI, ← hσI, Ideal.span_singleton_mul_span_singleton]
    -- Now: span {(a+ζb) · (a+σζ·b)} = span {algebraMap x₀}
    -- via (a+ζb)·(a+σζ·b) = (a+ζb)·σ(a+ζb) = algebraMap x₀ (from hx₀).
    rw [show ((a : 𝓞 (CyclotomicField p ℚ)) + ζ * (b : 𝓞 (CyclotomicField p ℚ))) *
        ((a : 𝓞 (CyclotomicField p ℚ)) +
          ringOfIntegersComplexConj (CyclotomicField p ℚ) ζ *
          (b : 𝓞 (CyclotomicField p ℚ))) =
        ((a : 𝓞 (CyclotomicField p ℚ)) + ζ * (b : 𝓞 (CyclotomicField p ℚ))) *
        ringOfIntegersComplexConj (CyclotomicField p ℚ)
          ((a : 𝓞 (CyclotomicField p ℚ)) + ζ * (b : 𝓞 (CyclotomicField p ℚ))) by
      simp [map_add, map_mul, map_intCast]]
    rw [← hx₀]
  rw [h_target]

set_option linter.unusedSectionVars false in
set_option backward.isDefEq.respectTransparency false in
/-- **`I * σI` is principal under plus-class-number nondivisibility.**

This is the no-extra-descent form of the product step.  It reuses the
relNorm/Hilbert-90 infrastructure, which proves that the relative norm ideal
maps to `I * σI`; since its `p`-th power is principal and `p ∤ h⁺`, the product
class is trivial. -/
theorem caseI_factor_ideal_mul_conj_isPrincipal_of_not_dvd_hPlus
    (_hp_odd : p ≠ 2)
    (h_not_dvd : ¬ (p : ℕ) ∣ hPlus (CyclotomicField p ℚ))
    {a b : ℤ} {ζ : 𝓞 (CyclotomicField p ℚ)}
    {I : Ideal (𝓞 (CyclotomicField p ℚ))} (hI_ne : I ≠ ⊥)
    (hI : Ideal.span ({(a : 𝓞 (CyclotomicField p ℚ)) + ζ *
        (b : 𝓞 (CyclotomicField p ℚ))} :
      Set (𝓞 (CyclotomicField p ℚ))) = I ^ p) :
    (I * Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom I).IsPrincipal := by
  have hα_ne :
      ((a : 𝓞 (CyclotomicField p ℚ)) + ζ *
        (b : 𝓞 (CyclotomicField p ℚ))) ≠ 0 := by
    intro hα
    apply hI_ne
    have h_span_zero :
        Ideal.span ({(a : 𝓞 (CyclotomicField p ℚ)) + ζ *
          (b : 𝓞 (CyclotomicField p ℚ))} :
        Set (𝓞 (CyclotomicField p ℚ))) = ⊥ := by
      rw [hα]
      exact Ideal.span_singleton_eq_bot.mpr rfl
    rw [h_span_zero] at hI
    exact pow_eq_zero_iff (Fact.out : Nat.Prime p).pos.ne' |>.mp hI.symm
  have h_VC : p.Coprime (Fintype.card (ClassGroup (𝓞 K⁺))) := by
    simpa [hPlus] using
      (Nat.Prime.coprime_iff_not_dvd (Fact.out : Nat.Prime p)
        (n := hPlus (CyclotomicField p ℚ))).mpr h_not_dvd
  have h_principal :=
    BernoulliRegular.FLT37.isPrincipal_mul_complexConj_of_pow_of_VC
      (p := p) (K := CyclotomicField p ℚ) h_VC hα_ne hI_ne hI
  simpa using h_principal

set_option linter.unusedSectionVars false in
set_option backward.isDefEq.respectTransparency false in
/-- The proved product-principality step gives the class-group relation
`[I] * [σI] = 1`.

This records exactly what the plus-side argument supplies.  It is intentionally
weaker than the Case-I AK-5a target: the remaining minus-side work is to use
the actual σ-anti factor data to pass from this product relation to the
principal-minus quotient. -/
theorem caseI_factor_class_mul_conj_eq_one_of_not_dvd_hPlus
    (hp_odd : p ≠ 2)
    (h_not_dvd : ¬ (p : ℕ) ∣ hPlus (CyclotomicField p ℚ))
    {a b : ℤ} {ζ : 𝓞 (CyclotomicField p ℚ)}
    {I : Ideal (𝓞 (CyclotomicField p ℚ))} (hI_ne : I ≠ ⊥)
    (hI : Ideal.span ({(a : 𝓞 (CyclotomicField p ℚ)) + ζ *
        (b : 𝓞 (CyclotomicField p ℚ))} :
      Set (𝓞 (CyclotomicField p ℚ))) = I ^ p) :
    ClassGroup.mk0
        (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_ne⟩ :
          nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ)))) *
      ClassGroup.mk0
        (⟨Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom I,
          mem_nonZeroDivisors_iff_ne_zero.mpr
            ((Ideal.map_eq_bot_iff_of_injective
              (f := (ringOfIntegersComplexConj
                (CyclotomicField p ℚ)).toRingHom)
              (ringOfIntegersComplexConj (CyclotomicField p ℚ)).injective).not.mpr hI_ne)⟩ :
          nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ)))) = 1 := by
  let σ := ringOfIntegersComplexConj (CyclotomicField p ℚ)
  have hσI_ne : Ideal.map σ.toRingHom I ≠ ⊥ :=
    (Ideal.map_eq_bot_iff_of_injective (f := σ.toRingHom) σ.injective).not.mpr hI_ne
  have hmul_ne : I * Ideal.map σ.toRingHom I ≠ ⊥ := by
    intro hbot
    rw [Ideal.mul_eq_bot] at hbot
    exact hbot.elim hI_ne hσI_ne
  have h_principal :
      (I * Ideal.map σ.toRingHom I).IsPrincipal := by
    simpa [σ] using
      caseI_factor_ideal_mul_conj_isPrincipal_of_not_dvd_hPlus
        (p := p) hp_odd h_not_dvd hI_ne hI
  have h_prod_class :
      ClassGroup.mk0
        (⟨I * Ideal.map σ.toRingHom I,
          mem_nonZeroDivisors_iff_ne_zero.mpr hmul_ne⟩ :
          nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ)))) = 1 :=
    (ClassGroup.mk0_eq_one_iff
      (mem_nonZeroDivisors_iff_ne_zero.mpr hmul_ne)).mpr h_principal
  have h_mul :
      ClassGroup.mk0
        (⟨I * Ideal.map σ.toRingHom I,
          mem_nonZeroDivisors_iff_ne_zero.mpr hmul_ne⟩ :
          nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ)))) =
      ClassGroup.mk0
        (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_ne⟩ :
          nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ)))) *
      ClassGroup.mk0
        (⟨Ideal.map σ.toRingHom I,
          mem_nonZeroDivisors_iff_ne_zero.mpr hσI_ne⟩ :
          nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ)))) := by
    rw [← map_mul]
    rfl
  simpa [σ] using h_mul.symm.trans h_prod_class

omit [Fact p.Prime] in
/-- Pure class-group algebra used by the Case-I square-class route.

If `x` is `p`-torsion, `x * y = 1`, and `y² = x²`, then `x = 1` for odd
prime `p`: the square relation and product relation give `x⁴ = 1`, so the
order of `x` divides both `p` and `4`. -/
theorem class_eq_one_of_p_torsion_mul_and_square
    {G : Type} [CommGroup G] {p : ℕ}
    (hp_prime : Nat.Prime p) (hp_odd : p ≠ 2)
    {x y : G} (hx_p : x ^ p = 1) (hxy : x * y = 1)
    (h_sq : y ^ 2 = x ^ 2) :
    x = 1 := by
  have hx4 : x ^ 4 = 1 := by
    calc
      x ^ 4 = x ^ 2 * x ^ 2 := by group
      _ = x ^ 2 * y ^ 2 := by rw [h_sq]
      _ = (x * y) ^ 2 := by rw [mul_pow]
      _ = 1 := by rw [hxy]; simp
  have h_ord_p : orderOf x ∣ p := orderOf_dvd_of_pow_eq_one hx_p
  have h_ord_4 : orderOf x ∣ 4 := orderOf_dvd_of_pow_eq_one hx4
  have h_cop2 : Nat.Coprime p 2 := by
    rw [Nat.coprime_comm, Nat.coprime_primes Nat.prime_two hp_prime]
    exact fun h => hp_odd h.symm
  have h_cop4 : Nat.Coprime p 4 := by
    simpa [show 4 = 2 ^ 2 by norm_num] using h_cop2.pow_right 2
  have h_ord_one : orderOf x = 1 := by
    have h_gcd : orderOf x ∣ Nat.gcd p 4 := Nat.dvd_gcd h_ord_p h_ord_4
    rw [h_cop4] at h_gcd
    exact Nat.dvd_one.mp h_gcd
  exact orderOf_eq_one_iff.mp h_ord_one

set_option linter.unusedSectionVars false in
set_option backward.isDefEq.respectTransparency false in
/-- Under plus-coprime and the concrete square-class target, the actual
case-I factor ideal has trivial class.

The proof combines three already formalized ingredients:
* `(a + ζ b) = I^p` makes `[I]` `p`-torsion;
* plus-coprime gives `[I] * [σI] = 1`;
* the remaining square-class input gives `[σI]^2 = [I]^2`.

Thus `[I]` has order dividing both `p` and `4`, hence is trivial for `p ≠ 2`. -/
theorem caseI_factor_class_eq_one_of_square_and_not_dvd_hPlus
    (hp_odd : p ≠ 2)
    (h_not_dvd : ¬ (p : ℕ) ∣ hPlus (CyclotomicField p ℚ))
    {a b : ℤ} {ζ : 𝓞 (CyclotomicField p ℚ)}
    {I : Ideal (𝓞 (CyclotomicField p ℚ))} (hI_ne : I ≠ ⊥)
    (hI : Ideal.span ({(a : 𝓞 (CyclotomicField p ℚ)) + ζ *
        (b : 𝓞 (CyclotomicField p ℚ))} :
      Set (𝓞 (CyclotomicField p ℚ))) = I ^ p)
    (h_sq :
      (ClassGroup.mk0
        (⟨Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom I,
          mem_nonZeroDivisors_iff_ne_zero.mpr
            ((Ideal.map_eq_bot_iff_of_injective
              (f := (ringOfIntegersComplexConj
                (CyclotomicField p ℚ)).toRingHom)
              (ringOfIntegersComplexConj (CyclotomicField p ℚ)).injective).not.mpr hI_ne)⟩ :
          nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ)))) ^ 2) =
      (ClassGroup.mk0
        (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_ne⟩ :
          nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ)))) ^ 2)) :
    ClassGroup.mk0
      (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_ne⟩ :
        nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ)))) = 1 := by
  let σ := ringOfIntegersComplexConj (CyclotomicField p ℚ)
  have hσI_ne : Ideal.map σ.toRingHom I ≠ ⊥ :=
    (Ideal.map_eq_bot_iff_of_injective (f := σ.toRingHom) σ.injective).not.mpr hI_ne
  let x : ClassGroup (𝓞 (CyclotomicField p ℚ)) :=
    ClassGroup.mk0
      (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_ne⟩ :
        nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ))))
  let y : ClassGroup (𝓞 (CyclotomicField p ℚ)) :=
    ClassGroup.mk0
      (⟨Ideal.map σ.toRingHom I, mem_nonZeroDivisors_iff_ne_zero.mpr hσI_ne⟩ :
        nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ))))
  have hx_p : x ^ p = 1 := by
    have h_Ip_principal : (I ^ p).IsPrincipal := by
      rw [← hI]; exact ⟨_, rfl⟩
    have hpow_mem : I ^ p ∈ nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ))) :=
      mem_nonZeroDivisors_iff_ne_zero.mpr (pow_ne_zero p hI_ne)
    dsimp [x]
    rw [show (ClassGroup.mk0
        (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_ne⟩ :
          nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ)))) : ClassGroup
            (𝓞 (CyclotomicField p ℚ))) ^ p =
        ClassGroup.mk0 (⟨I ^ p, hpow_mem⟩ :
          nonZeroDivisors (Ideal (𝓞 (CyclotomicField p ℚ))) ) from by
        rw [← map_pow]; rfl]
    exact (ClassGroup.mk0_eq_one_iff hpow_mem).mpr h_Ip_principal
  have hxy : x * y = 1 := by
    dsimp [x, y, σ]
    exact caseI_factor_class_mul_conj_eq_one_of_not_dvd_hPlus
      (p := p) hp_odd h_not_dvd hI_ne hI
  have hyx_sq : y ^ 2 = x ^ 2 := by
    dsimp [x, y, σ]
    simpa [σ] using h_sq
  exact class_eq_one_of_p_torsion_mul_and_square
    (Fact.out : Nat.Prime p) hp_odd hx_p hxy hyx_sq

set_option linter.unusedSectionVars false in
set_option backward.isDefEq.respectTransparency false in
/-- **Class-group descent with an explicit σ-fixed ideal descent input.**
The previous lemma proves `(I * σI)^p` principal. If the σ-fixed ideal
`I * σI` is known to be the pushforward of a real-subfield ideal, then
the plus-class-number nondivisibility theorem
`map_isPrincipal_of_pow_principal_of_not_dvd_hPlus` upgrades this to
principality of `I * σI` itself.

This deliberately leaves the real-subfield descent of this particular product
ideal as a concrete input; it does not package general σ-fixed ideal descent as
a hidden source theorem. -/
theorem caseI_factor_ideal_mul_conj_isPrincipal_of_sigmaFixedIdealDescends
    (hp_odd : p ≠ 2)
    (h_not_dvd : ¬ (p : ℕ) ∣ hPlus (CyclotomicField p ℚ))
    {a b : ℤ} {ζ : 𝓞 (CyclotomicField p ℚ)}
    {I : Ideal (𝓞 (CyclotomicField p ℚ))} (hI_ne : I ≠ ⊥)
    (hI : Ideal.span ({(a : 𝓞 (CyclotomicField p ℚ)) + ζ *
        (b : 𝓞 (CyclotomicField p ℚ))} :
      Set (𝓞 (CyclotomicField p ℚ))) = I ^ p)
    (h_descends : ∃ J' : Ideal (𝓞 K⁺),
      I * Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom I =
        J'.map (algebraMap (𝓞 K⁺) (𝓞 (CyclotomicField p ℚ)))) :
    (I * Ideal.map (ringOfIntegersComplexConj (CyclotomicField p ℚ)).toRingHom I).IsPrincipal := by
  haveI : IsCyclotomicExtension {p} ℚ (CyclotomicField p ℚ) :=
    CyclotomicField.isCyclotomicExtension p ℚ
  let σ := ringOfIntegersComplexConj (CyclotomicField p ℚ)
  let J : Ideal (𝓞 (CyclotomicField p ℚ)) := I * Ideal.map σ.toRingHom I
  have hJ_pow : (J ^ p).IsPrincipal := by
    dsimp [J, σ]
    exact caseI_factor_ideal_mul_conj_class_pow_eq_one (p := p) hI_ne hI
  have hσI_ne : Ideal.map σ.toRingHom I ≠ ⊥ := by
    intro hmap
    apply hI_ne
    exact (Ideal.map_eq_bot_iff_of_injective (f := σ.toRingHom) σ.injective).mp hmap
  have hJ_ne : J ≠ ⊥ := by
    intro hbot
    change I * Ideal.map σ.toRingHom I = ⊥ at hbot
    rw [Ideal.mul_eq_bot] at hbot
    exact hbot.elim hI_ne hσI_ne
  obtain ⟨Jplus, hJ_eq_raw⟩ := h_descends
  have hJ_eq : J = Jplus.map (algebraMap (𝓞 K⁺) (𝓞 (CyclotomicField p ℚ))) := by
    exact hJ_eq_raw
  have hJplus_ne : Jplus ≠ ⊥ := by
    intro hbot
    apply hJ_ne
    rw [hJ_eq, hbot, Ideal.map_bot]
  have hJplus_pow :
      ((Jplus.map (algebraMap (𝓞 K⁺) (𝓞 (CyclotomicField p ℚ)))) ^ p).IsPrincipal := by
    rw [← hJ_eq]
    exact hJ_pow
  have h_principal :=
    BernoulliRegular.FLT37.LehmerVandiver.CaseII.map_isPrincipal_of_pow_principal_of_not_dvd_hPlus
      (p := p) (K := CyclotomicField p ℚ) hp_odd h_not_dvd hJplus_ne hJplus_pow
  rw [← hJ_eq] at h_principal
  simpa [J, σ] using h_principal

end ClassGroupForm

end CaseI

end LehmerVandiver

end FLT37

end BernoulliRegular

end
