import BernoulliRegular.FLT37.LehmerVandiver.CaseI.ClassEqDischarge
import BernoulliRegular.FLT37.LehmerVandiver.CaseI.IsPrincipalUnderHPlus
import BernoulliRegular.Reflection.ResidueSymbol.Furtwaengler.Uniformizer
import BernoulliRegular.TotallyRealSubfield.ZetaPrime

/-!
# Proved auxiliary lemmas ported from pre-origin-merge

This file collects proven case-I auxiliary lemmas that were developed
on the local 9-sorry decomposition branch (`pre-origin-merge`). The
decomposition strategy on that branch differs from the canonical
PollaczekForward / Stage2KummerRatioK / CaseIIPrincipalDischarge /
AdaptedKummersLemma chain on origin, but several of the proved
sub-lemmas are universally useful infrastructure.

## Contents

* `lambda_assoc_pi_sq` — the σ-fixed prime element `(1-ζ)·(1-ζ^{p-1})`
  in `𝓞 K` is associated to `(1-ζ)²`. Cyclotomic algebra.

* `vπ_algMap_Kplus` — for nonzero σ-fixed `δ ∈ 𝓞 K`, the multiplicity
  `v_π(δ) = 2 · v_λ(δ)` where `π = 1-ζ` and `λ = (1-ζ)·(1-ζ^{p-1})`
  is the σ-fixed prime element. Uses shipped
  `multiplicity_zetaPrime_algebraMap_even`.

* `caseI_classes_pTorsion_from_principal_ideal` — Chunk A:
  `[I]^p = 1` and `[σI]^p = 1` from `(a + ζb) = I^p`.

* `caseI_sigmaAntiClass_trivial_from_p_and_sq_torsion` — Chunk E:
  Bezout combination of `[σI]^p = [I]^p` and `[σI]² = [I]²` to
  `[σI] = [I]` under p odd.

* `caseIClassEqDischarge_of_factor_class_square_eq` — packages the preceding
  two class-group chunks into a Case-I discharge from the concrete square-class
  target for the actual FLT factor ideals.

* `caseI_class_p_ne_two_of_FLT_data` — `p ≠ 2` from case-I FLT data
  `(a, b, c, p ∤ abc, a^p+b^p=c^p)` via mod-2 contradiction.

* `p_dvd_zeta_pow_sub_one_implies_eq_one` — a local cyclotomic
  uniformizer fact: `p ∣ ζ^k - 1` forces `ζ^k = 1`.

* `sub_one_sq_dvd_pow_sub_one_sub_mul_sub_one` and
  `zeta_sub_one_sq_dvd_p_of_three_le` — first-order Taylor and
  uniformizer divisibility facts used by the Kummer congruence step.

* `exists_intCast_residue_unit_mod_zeta_sub_one` — every unit has a
  nonzero integer representative modulo `ζ - 1`.

* `dvd_p_intCast_descends_to_real_subfield` — divisibility by `p` descends
  from `𝓞 K` to `𝓞 K⁺` for elements already in the real subfield.

These are direct ports from the pre-origin-merge
`CaseI/ZetaAdicDescent.lean` development.
-/

@[expose] public section

noncomputable section

open NumberField NumberField.IsCMField IsCyclotomicExtension

namespace BernoulliRegular

namespace FLT37

namespace LehmerVandiver

namespace CaseI

set_option backward.isDefEq.respectTransparency false in
/-- Taylor expansion of `x^m` around `1`, modulo `(x - 1)^2`.

This is the first-order binomial congruence
`x^m ≡ 1 + m * (x - 1) [MOD (x - 1)^2]`, packaged as divisibility. -/
theorem sub_one_sq_dvd_pow_sub_one_sub_mul_sub_one
    {R : Type*} [CommRing R] (x : R) (m : ℕ) :
    (x - 1) ^ 2 ∣ (x ^ m - 1 - m * (x - 1)) := by
  induction m with
  | zero =>
      simp
  | succ k ih =>
      have h_decomp :
          x ^ (k + 1) - 1 - ((k + 1 : ℕ) : R) * (x - 1) =
            (x ^ k - 1 - (k : ℕ) * (x - 1)) + (x - 1) * (x ^ k - 1) := by
        push_cast
        ring
      rw [h_decomp]
      refine dvd_add ih ?_
      have h_geom : (x - 1) ∣ (x ^ k - 1) := by
        simpa using sub_dvd_pow_sub_pow x 1 k
      obtain ⟨q, hq⟩ := h_geom
      refine ⟨q, ?_⟩
      rw [hq]
      ring

/-- In a cyclotomic domain with a primitive `p`-th root `ζ`, if `3 ≤ p`,
then `(ζ - 1)^2` divides `p`. -/
theorem zeta_sub_one_sq_dvd_p_of_three_le
    {p : ℕ} [Fact p.Prime] {R : Type*} [CommRing R] [IsDomain R]
    {ζ : R} (hζ : IsPrimitiveRoot ζ p) (hp_three : 3 ≤ p) :
    (ζ - 1) ^ 2 ∣ ((p : ℕ) : R) := by
  have h_assoc : Associated ((p : ℕ) : R) ((ζ - 1) ^ (p - 1)) :=
    BernoulliRegular.Furtwaengler.associated_ell_zeta_sub_one_pow hζ
  have h_pow_dvd : (ζ - 1) ^ 2 ∣ (ζ - 1) ^ (p - 1) := by
    apply pow_dvd_pow
    omega
  exact h_pow_dvd.trans h_assoc.symm.dvd

variable (p : ℕ) [Fact p.Prime]
variable (K : Type) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
  [NumberField.IsCMField K]

omit [NumberField.IsCMField K] in
/-- Every unit in `𝓞 K` has a nonzero integer representative modulo `ζ - 1`.

The proof writes the unit in the integral power basis generated by `ζ`; modulo
`ζ - 1`, every power of `ζ` is congruent to `1`, so the residue is the sum of
the integer coefficients.  If that sum were divisible by `p`, then `ζ - 1`
would divide the unit itself, contradicting that `ζ - 1` is prime. -/
theorem exists_intCast_residue_unit_mod_zeta_sub_one
    {ζ : 𝓞 K} (hζ : IsPrimitiveRoot ζ p)
    (u : (𝓞 K)ˣ) :
    ∃ n : ℤ, ¬ (p : ℤ) ∣ n ∧
      (ζ - 1) ∣ ((u : 𝓞 K) - (n : 𝓞 K)) := by
  classical
  have hp_prime : Nat.Prime p := Fact.out
  haveI : NeZero p := ⟨hp_prime.ne_zero⟩
  have hζ_K : IsPrimitiveRoot ((ζ : K)) p :=
    hζ.map_of_injective NumberField.RingOfIntegers.coe_injective
  have h_toInt_eq : hζ_K.toInteger = ζ := rfl
  set B := hζ_K.integralPowerBasis with hB_def
  have h_gen_eq : B.gen = ζ := by
    rw [hB_def, IsPrimitiveRoot.integralPowerBasis_gen, h_toInt_eq]
  set a : Fin B.dim → ℤ := fun i ↦ B.basis.repr (u : 𝓞 K) i with ha_def
  have h_repr : ∑ i : Fin B.dim, a i • ζ ^ (i : ℕ) = (u : 𝓞 K) := by
    have hsum := B.basis.sum_repr (u : 𝓞 K)
    simp_rw [PowerBasis.basis_eq_pow, h_gen_eq] at hsum
    convert hsum using 1
  set n : ℤ := ∑ i : Fin B.dim, a i with hn_def
  have h_zeta_sub_one_dvd_diff :
      (ζ - 1) ∣ ((u : 𝓞 K) - ((n : ℤ) : 𝓞 K)) := by
    rw [← h_repr]
    have h_n_eq : ((n : ℤ) : 𝓞 K) = ∑ i : Fin B.dim, ((a i : ℤ) : 𝓞 K) := by
      rw [hn_def]
      push_cast
      rfl
    rw [h_n_eq, ← Finset.sum_sub_distrib]
    refine Finset.dvd_sum (fun i _ ↦ ?_)
    rw [zsmul_eq_mul]
    rw [show (a i : 𝓞 K) * ζ ^ (i : ℕ) - (a i : 𝓞 K) =
        (a i : 𝓞 K) * (ζ ^ (i : ℕ) - 1) by ring]
    exact (sub_dvd_pow_sub_pow ζ 1 _).mul_left _ |>.trans
      (by rw [one_pow])
  refine ⟨n, ?_, h_zeta_sub_one_dvd_diff⟩
  intro h_p_dvd_n
  have h_zeta_sub_one_dvd_p : (ζ - 1) ∣ ((p : ℕ) : 𝓞 K) := by
    have := hζ_K.toInteger_sub_one_dvd_prime'
    rw [h_toInt_eq] at this
    exact_mod_cast this
  have h_zeta_sub_one_dvd_n : (ζ - 1) ∣ ((n : ℤ) : 𝓞 K) := by
    obtain ⟨m, hm⟩ := h_p_dvd_n
    rw [hm]
    push_cast
    exact h_zeta_sub_one_dvd_p.mul_right _
  have h_zeta_sub_one_dvd_u : (ζ - 1) ∣ (u : 𝓞 K) := by
    have := dvd_add h_zeta_sub_one_dvd_diff h_zeta_sub_one_dvd_n
    simpa using this
  have h_prime : Prime (ζ - 1) := by
    have := hζ_K.zeta_sub_one_prime'
    rwa [h_toInt_eq] at this
  exact h_prime.not_unit (isUnit_of_dvd_unit h_zeta_sub_one_dvd_u u.isUnit)

omit [IsCyclotomicExtension {p} ℚ K] in
/-- Divisibility by `p` descends from `𝓞 K` to `𝓞 K⁺` for real-subfield
elements.

If `p ∣ algebraMap u_real - n` upstairs in `𝓞 K`, then the quotient is fixed
by complex conjugation and therefore comes from `𝓞 K⁺`; injectivity of the
algebra map gives the divisibility downstairs. -/
theorem dvd_p_intCast_descends_to_real_subfield
    (u_real : 𝓞 (NumberField.maximalRealSubfield K)) (n : ℤ)
    (h_dvd_K : ((p : ℕ) : 𝓞 K) ∣
        ((algebraMap (𝓞 (NumberField.maximalRealSubfield K)) (𝓞 K) u_real : 𝓞 K)
          - ((n : ℤ) : 𝓞 K))) :
    ((p : ℕ) : 𝓞 (NumberField.maximalRealSubfield K)) ∣
      ((u_real : 𝓞 (NumberField.maximalRealSubfield K)) -
        ((n : ℤ) : 𝓞 (NumberField.maximalRealSubfield K))) := by
  classical
  have hp_prime : Nat.Prime p := Fact.out
  obtain ⟨k, hk⟩ := h_dvd_K
  have hp_ne_zero : ((p : ℕ) : 𝓞 K) ≠ 0 := by
    exact_mod_cast hp_prime.ne_zero
  have h_conj_rhs :
      ringOfIntegersComplexConj K
          ((algebraMap (𝓞 (NumberField.maximalRealSubfield K)) (𝓞 K) u_real : 𝓞 K)
            - ((n : ℤ) : 𝓞 K)) =
        (algebraMap (𝓞 (NumberField.maximalRealSubfield K)) (𝓞 K) u_real : 𝓞 K)
          - ((n : ℤ) : 𝓞 K) := by
    rw [map_sub, map_intCast]
    congr 1
    exact (ringOfIntegersComplexConj_eq_self_iff K _).mpr ⟨u_real, rfl⟩
  have h_conj_pk :
      ringOfIntegersComplexConj K (((p : ℕ) : 𝓞 K) * k) =
        ((p : ℕ) : 𝓞 K) * k := by
    rw [← hk]
    exact h_conj_rhs
  have h_conj_k : ringOfIntegersComplexConj K k = k := by
    have h_eq : ((p : ℕ) : 𝓞 K) * ringOfIntegersComplexConj K k =
        ((p : ℕ) : 𝓞 K) * k := by
      have hpk := h_conj_pk
      rw [map_mul, map_natCast] at hpk
      exact hpk
    exact mul_left_cancel₀ hp_ne_zero h_eq
  obtain ⟨k', hk'⟩ :=
    (ringOfIntegersComplexConj_eq_self_iff K k).mp h_conj_k
  refine ⟨k', ?_⟩
  apply FaithfulSMul.algebraMap_injective
        (𝓞 (NumberField.maximalRealSubfield K)) (𝓞 K)
  rw [map_mul, map_natCast, map_sub, map_intCast, hk', hk]

omit [NumberField.IsCMField K] in
/-- If `p` divides `ζ^k - 1` in `𝓞 K`, then `ζ^k = 1`.

The key point is that `p` is associated to `(ζ - 1)^(p - 1)`.  If
`ζ^k ≠ 1`, reducing `k` modulo `p` makes `ζ^k - 1` associated to `ζ - 1`,
so `(ζ - 1)^(p - 1)` would divide `ζ - 1`; since `p > 2`, this would force
`ζ - 1` to be a unit, contradicting primality. -/
theorem p_dvd_zeta_pow_sub_one_implies_eq_one
    {ζ : 𝓞 K} (hζ : IsPrimitiveRoot ζ p) (hp_two : 2 < p) (k : ℕ)
    (hdvd : ((p : ℕ) : 𝓞 K) ∣ (ζ ^ k - 1)) :
    ζ ^ k = 1 := by
  classical
  have hp_prime : Nat.Prime p := Fact.out
  haveI : NeZero p := ⟨hp_prime.ne_zero⟩
  have hζ_K : IsPrimitiveRoot ((ζ : K)) p :=
    hζ.map_of_injective NumberField.RingOfIntegers.coe_injective
  have h_toInt : hζ_K.toInteger = ζ := rfl
  by_contra h_ne_one
  have h_pow_mod : ζ ^ k = ζ ^ (k % p) := by
    conv_lhs => rw [← Nat.div_add_mod k p]
    rw [pow_add, pow_mul, hζ.pow_eq_one, one_pow, one_mul]
  set j := k % p with hj_def
  rw [h_pow_mod] at hdvd h_ne_one
  have hj_lt : j < p := Nat.mod_lt _ hp_prime.pos
  have hj_pos : 0 < j := by
    rcases Nat.eq_zero_or_pos j with hj | hj
    · rw [hj, pow_zero] at h_ne_one
      exact (h_ne_one rfl).elim
    · exact hj
  have hcoprime : Nat.Coprime j p :=
    (hp_prime.coprime_iff_not_dvd).mpr
      (fun h ↦ Nat.not_lt.mpr (Nat.le_of_dvd hj_pos h) hj_lt) |>.symm
  have h_assoc : Associated ((ζ : 𝓞 K) - 1) (ζ ^ j - 1) :=
    hζ.associated_sub_one_pow_sub_one_of_coprime hcoprime
  have h_p_assoc : Associated ((p : ℕ) : 𝓞 K) ((ζ - 1) ^ (p - 1)) :=
    BernoulliRegular.Furtwaengler.associated_ell_zeta_sub_one_pow hζ
  have h_prime : Prime ((ζ : 𝓞 K) - 1) := by
    have := hζ_K.zeta_sub_one_prime'
    rwa [h_toInt] at this
  have h_ne_zero : ((ζ : 𝓞 K) - 1) ≠ 0 := h_prime.ne_zero
  have h_p_dvd_zeta : ((p : ℕ) : 𝓞 K) ∣ ((ζ : 𝓞 K) - 1) :=
    hdvd.trans h_assoc.symm.dvd
  have h_pow_dvd : ((ζ : 𝓞 K) - 1) ^ (p - 1) ∣ ((ζ : 𝓞 K) - 1) :=
    h_p_assoc.symm.dvd.trans h_p_dvd_zeta
  obtain ⟨c, hc⟩ := h_pow_dvd
  have hp_succ : p - 1 = (p - 2) + 1 := by omega
  have h_factor : ((ζ : 𝓞 K) - 1) ^ (p - 1) =
      ((ζ : 𝓞 K) - 1) * ((ζ : 𝓞 K) - 1) ^ (p - 2) := by
    rw [hp_succ, pow_succ, mul_comm]
  rw [h_factor, mul_assoc] at hc
  have h_unit_pow : IsUnit (((ζ : 𝓞 K) - 1) ^ (p - 2)) := by
    have h_eq : ((ζ : 𝓞 K) - 1) * 1 =
        ((ζ : 𝓞 K) - 1) * (((ζ : 𝓞 K) - 1) ^ (p - 2) * c) := by
      rw [mul_one]
      exact hc
    have h_cancel : (1 : 𝓞 K) = ((ζ : 𝓞 K) - 1) ^ (p - 2) * c :=
      mul_left_cancel₀ h_ne_zero h_eq
    exact IsUnit.of_mul_eq_one _ h_cancel.symm
  have hp_minus_two_ne : p - 2 ≠ 0 := by omega
  have h_unit_zeta : IsUnit ((ζ : 𝓞 K) - 1) :=
    (isUnit_pow_iff hp_minus_two_ne).mp h_unit_pow
  exact h_prime.not_unit h_unit_zeta

omit [Fact (Nat.Prime p)] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
  [IsCMField K] in
/-- **`lambda_assoc_pi_sq`**: λ = (1-ζ)·(1-ζ^{p-1}) ~ π² where π = 1-ζ.

Pure cyclotomic-algebra fact: with `ζ` a primitive p-th root,
`(1-ζ^{p-1})` is associated to `(1-ζ)` via mathlib's
`associated_sub_one_pow_sub_one_of_coprime` (gcd(p-1, p) = 1).
Multiplying both by (1-ζ) and using `(1-ζ)² = (1-ζ)·(1-ζ)` gives
the associated identity. -/
theorem lambda_assoc_pi_sq
    {ζ : 𝓞 K} (hζ : IsPrimitiveRoot ζ p)
    (hp_pos : 0 < p) :
    Associated
      ((1 - ζ) * (1 - ζ^(p - 1)) : 𝓞 K)
      ((1 - ζ : 𝓞 K)^2) := by
  have h_cop : (p - 1).Coprime p := by
    have hp_eq : p = (p - 1) + 1 := (Nat.sub_one_add_one_eq_of_pos hp_pos).symm
    rw [Nat.Coprime, hp_eq]; simp
  have h_assoc : Associated (ζ - 1 : 𝓞 K) (ζ ^ (p - 1) - 1) :=
    hζ.associated_sub_one_pow_sub_one_of_coprime h_cop
  have h_neg : Associated (1 - ζ : 𝓞 K) (1 - ζ ^ (p - 1)) := by
    have := h_assoc.neg_right
    simpa [neg_sub] using this.neg_left
  have h_mul : Associated ((1 - ζ : 𝓞 K) * (1 - ζ)) ((1 - ζ : 𝓞 K) * (1 - ζ^(p - 1))) :=
    h_neg.mul_left (1 - ζ : 𝓞 K)
  have h_sq : (1 - ζ : 𝓞 K) * (1 - ζ) = (1 - ζ : 𝓞 K)^2 := by ring
  rw [h_sq] at h_mul
  exact h_mul.symm

/-- **`vπ_algMap_Kplus`**: for nonzero σ-fixed δ ∈ 𝓞 K,
`multiplicity (1-ζ) δ = 2 · multiplicity ((1-ζ)·(1-ζ^{p-1})) δ`.

Combines:
* Shipped `multiplicity_zetaPrime_algebraMap_even` (Even multiplicity
  at `(zeta_spec).toInteger - 1` for σ-fixed elements).
* Associated chain `(zeta_spec.toInteger - 1) ~ (ζ - 1) ~ (1 - ζ)` via
  `IsPrimitiveRoot.isPrimitiveRoot_iff` + `associated_sub_one_pow_sub_one_of_coprime`.
* `lambda_assoc_pi_sq` to translate `(1-ζ)²` into `(1-ζ)·(1-ζ^{p-1})`.
* Multiplicity-of-square = floor(multiplicity / 2) for even multiplicity. -/
theorem vπ_algMap_Kplus
    {ζ : 𝓞 K} (hζ : IsPrimitiveRoot ζ p)
    (hp_pos : 0 < p) (hp_odd : p ≠ 2)
    {δ : 𝓞 K} (hδ : δ ≠ 0)
    (h_σ_fixed : (ringOfIntegersComplexConj K).toRingEquiv.toRingHom δ = δ) :
    multiplicity (1 - ζ : 𝓞 K) δ =
    2 * multiplicity ((1 - ζ) * (1 - ζ^(p - 1)) : 𝓞 K) δ := by
  have h_assoc : Associated
      ((1 - ζ) * (1 - ζ^(p - 1)) : 𝓞 K) ((1 - ζ : 𝓞 K)^2) :=
    lambda_assoc_pi_sq p K hζ hp_pos
  have h_mult_eq : multiplicity ((1 - ζ) * (1 - ζ^(p - 1)) : 𝓞 K) δ =
      multiplicity ((1 - ζ : 𝓞 K)^2) δ := by
    have := multiplicity_eq_of_associated_left (c := δ) h_assoc
    exact this.symm
  rw [h_mult_eq]
  have h_even : Even (multiplicity (1 - ζ : 𝓞 K) δ) := by
    have h_σ_alg : ringOfIntegersComplexConj K δ = δ := h_σ_fixed
    have h_range : δ ∈ Set.range
        (algebraMap (𝓞 (NumberField.maximalRealSubfield K)) (𝓞 K)) :=
      (ringOfIntegersComplexConj_eq_self_iff (K := K) δ).mp h_σ_alg
    obtain ⟨y, hy⟩ := h_range
    have hy_ne : y ≠ 0 := by
      intro h_zero
      apply hδ
      rw [← hy, h_zero, map_zero]
    have h_even_spec :=
      multiplicity_zetaPrime_algebraMap_even (p := p) (K := K) hp_odd y hy_ne
    rw [hy] at h_even_spec
    haveI : NeZero p := ⟨(Fact.out : Nat.Prime p).ne_zero⟩
    have hzs_prim : IsPrimitiveRoot
        (((IsCyclotomicExtension.zeta_spec p ℚ K).toInteger : 𝓞 K)) p :=
      (IsCyclotomicExtension.zeta_spec p ℚ K).toInteger_isPrimitiveRoot
    obtain ⟨j, _hj_lt, hj_cop, hj_eq⟩ := hzs_prim.isPrimitiveRoot_iff.mp hζ
    have h_assoc_spec :
        Associated
          (((IsCyclotomicExtension.zeta_spec p ℚ K).toInteger : 𝓞 K) - 1) (ζ - 1) := by
      rw [← hj_eq]
      exact hzs_prim.associated_sub_one_pow_sub_one_of_coprime hj_cop
    have h_neg : Associated (ζ - 1 : 𝓞 K) (1 - ζ) :=
      ⟨-1, by push_cast; ring⟩
    have h_chain : Associated
        (((IsCyclotomicExtension.zeta_spec p ℚ K).toInteger : 𝓞 K) - 1)
        ((1 - ζ : 𝓞 K)) := h_assoc_spec.trans h_neg
    have h_eq : multiplicity
        (((IsCyclotomicExtension.zeta_spec p ℚ K).toInteger : 𝓞 K) - 1) δ =
        multiplicity (1 - ζ : 𝓞 K) δ :=
      multiplicity_eq_of_associated_left h_chain.symm
    rw [h_eq] at h_even_spec
    exact h_even_spec
  have hp_prime_inst : Nat.Prime p := Fact.out
  have hπ_prime : Prime (1 - ζ : 𝓞 K) := by
    haveI : NeZero p := ⟨hp_prime_inst.ne_zero⟩
    have hzs_prim : IsPrimitiveRoot
        (((IsCyclotomicExtension.zeta_spec p ℚ K).toInteger : 𝓞 K)) p :=
      (IsCyclotomicExtension.zeta_spec p ℚ K).toInteger_isPrimitiveRoot
    obtain ⟨j, _hj_lt, hj_cop, hj_eq⟩ := hzs_prim.isPrimitiveRoot_iff.mp hζ
    have h_assoc_spec :
        Associated
          (((IsCyclotomicExtension.zeta_spec p ℚ K).toInteger : 𝓞 K) - 1) (ζ - 1) := by
      rw [← hj_eq]
      exact hzs_prim.associated_sub_one_pow_sub_one_of_coprime hj_cop
    have h_neg : Associated (ζ - 1 : 𝓞 K) (1 - ζ) :=
      ⟨-1, by push_cast; ring⟩
    exact ((h_assoc_spec.trans h_neg).prime_iff).mp
      (IsCyclotomicExtension.zeta_spec p ℚ K).zeta_sub_one_prime'
  have h_fin : FiniteMultiplicity (1 - ζ : 𝓞 K) δ :=
    FiniteMultiplicity.of_prime_left hπ_prime hδ
  obtain ⟨m, hm⟩ := h_even
  have h_2m : multiplicity (1 - ζ : 𝓞 K) δ = 2 * m := by rw [hm]; ring
  have h_pow_2 : ∀ k : ℕ, ((1 - ζ : 𝓞 K)^2)^k = (1 - ζ : 𝓞 K)^(2*k) := fun k ↦ by
    rw [← pow_mul]
  have h_fin_sq : FiniteMultiplicity ((1 - ζ : 𝓞 K)^2) δ := by
    refine ⟨m + 1, ?_⟩
    intro h_dvd
    rw [h_pow_2] at h_dvd
    have h_le := h_fin.pow_dvd_iff_le_multiplicity.mp h_dvd
    rw [h_2m] at h_le
    omega
  have h_mult_sq : multiplicity ((1 - ζ : 𝓞 K)^2) δ = m := by
    rw [h_fin_sq.multiplicity_eq_iff]
    refine ⟨?_, ?_⟩
    · rw [h_pow_2]
      apply h_fin.pow_dvd_iff_le_multiplicity.mpr
      rw [h_2m]
    · intro h_dvd
      rw [h_pow_2] at h_dvd
      have h_le := h_fin.pow_dvd_iff_le_multiplicity.mp h_dvd
      rw [h_2m] at h_le
      omega
  rw [h_2m, h_mult_sq]

variable {p K}

omit [Fact (Nat.Prime p)] [IsCyclotomicExtension {p} ℚ K] in
/-- **Chunk A**: case-I `[I]^p = 1` and `[σI]^p = 1` from `(a+ζb) = I^p`. -/
theorem caseI_classes_pTorsion_from_principal_ideal
    {a b : ℤ} {ζ : 𝓞 K} (_hζ : IsPrimitiveRoot ζ p)
    {I : Ideal (𝓞 K)} (hI_nz : I ≠ ⊥)
    (hI : Ideal.span ({(a : 𝓞 K) + ζ * (b : 𝓞 K)} : Set (𝓞 K)) = I ^ p) :
    (ClassGroup.mk0
        (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_nz⟩
          : nonZeroDivisors (Ideal (𝓞 K)))) ^ p = 1 ∧
    (ClassGroup.mk0
        (⟨I.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom,
          mem_nonZeroDivisors_iff_ne_zero.mpr
            ((map_ne_bot_iff_complexConj K I).mpr hI_nz)⟩
          : nonZeroDivisors (Ideal (𝓞 K)))) ^ p = 1 := by
  refine ⟨?_, ?_⟩
  · have h_Ip_principal : (I ^ p).IsPrincipal := by
      rw [← hI]; exact ⟨_, rfl⟩
    have hpow_mem : I ^ p ∈ nonZeroDivisors (Ideal (𝓞 K)) :=
      mem_nonZeroDivisors_iff_ne_zero.mpr (pow_ne_zero p hI_nz)
    rw [show (ClassGroup.mk0
        (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_nz⟩
          : nonZeroDivisors (Ideal (𝓞 K)))) ^ p =
        ClassGroup.mk0 (⟨I ^ p, hpow_mem⟩
          : nonZeroDivisors (Ideal (𝓞 K))) from by rw [← map_pow]; rfl]
    exact (ClassGroup.mk0_eq_one_iff hpow_mem).mpr h_Ip_principal
  · set σI : Ideal (𝓞 K) :=
      I.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom with hσI_def
    have hσI_nz : σI ≠ ⊥ := (map_ne_bot_iff_complexConj K I).mpr hI_nz
    have h_σIp_principal : (σI ^ p).IsPrincipal := by
      refine ⟨(ringOfIntegersComplexConj K).toRingEquiv.toRingHom
        ((a : 𝓞 K) + ζ * (b : 𝓞 K)), ?_⟩
      rw [hσI_def, ← Ideal.map_pow, ← hI, Ideal.map_span,
        Set.image_singleton]
    have hpow_mem : σI ^ p ∈ nonZeroDivisors (Ideal (𝓞 K)) :=
      mem_nonZeroDivisors_iff_ne_zero.mpr (pow_ne_zero p hσI_nz)
    rw [show (ClassGroup.mk0
        (⟨σI, mem_nonZeroDivisors_iff_ne_zero.mpr hσI_nz⟩
          : nonZeroDivisors (Ideal (𝓞 K)))) ^ p =
        ClassGroup.mk0 (⟨σI ^ p, hpow_mem⟩
          : nonZeroDivisors (Ideal (𝓞 K))) from by rw [← map_pow]; rfl]
    exact (ClassGroup.mk0_eq_one_iff hpow_mem).mpr h_σIp_principal

omit [IsCyclotomicExtension {p} ℚ K] in
/-- **Chunk E**: under `p` odd, `[σI]^p = [I]^p` plus `[σI]² = [I]²`
gives `[σI] = [I]`.

Bezout combination: setting `x := [σI]·[I]⁻¹`, the two hypotheses say
`x^p = 1` and `x^2 = 1`. With `gcd(p, 2) = 1` for p odd prime, the
order of x divides 1, hence x = 1. -/
theorem caseI_sigmaAntiClass_trivial_from_p_and_sq_torsion
    (hp_odd : p ≠ 2)
    {I : Ideal (𝓞 K)} (hI_nz : I ≠ ⊥)
    (h_pTorsion :
      (ClassGroup.mk0
          (⟨I.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom,
            mem_nonZeroDivisors_iff_ne_zero.mpr
              ((map_ne_bot_iff_complexConj K I).mpr hI_nz)⟩
            : nonZeroDivisors (Ideal (𝓞 K)))) ^ p =
      (ClassGroup.mk0
          (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_nz⟩
            : nonZeroDivisors (Ideal (𝓞 K)))) ^ p)
    (h_sqEq :
      (ClassGroup.mk0
          (⟨I.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom,
            mem_nonZeroDivisors_iff_ne_zero.mpr
              ((map_ne_bot_iff_complexConj K I).mpr hI_nz)⟩
            : nonZeroDivisors (Ideal (𝓞 K)))) ^ 2 =
      (ClassGroup.mk0
          (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_nz⟩
            : nonZeroDivisors (Ideal (𝓞 K)))) ^ 2) :
    ClassGroup.mk0
        (⟨I.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom,
          mem_nonZeroDivisors_iff_ne_zero.mpr
            ((map_ne_bot_iff_complexConj K I).mpr hI_nz)⟩
          : nonZeroDivisors (Ideal (𝓞 K))) =
      ClassGroup.mk0
        (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_nz⟩
          : nonZeroDivisors (Ideal (𝓞 K))) := by
  set I_cls : ClassGroup (𝓞 K) :=
    ClassGroup.mk0
      (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_nz⟩
        : nonZeroDivisors (Ideal (𝓞 K))) with hI_cls
  set σI_cls : ClassGroup (𝓞 K) :=
    ClassGroup.mk0
      (⟨I.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom,
        mem_nonZeroDivisors_iff_ne_zero.mpr
          ((map_ne_bot_iff_complexConj K I).mpr hI_nz)⟩
        : nonZeroDivisors (Ideal (𝓞 K))) with hσI_cls
  set x : ClassGroup (𝓞 K) := σI_cls * I_cls⁻¹ with hx_def
  have hx_pTorsion : x ^ p = 1 := by
    rw [hx_def, mul_pow, h_pTorsion, inv_pow, mul_inv_cancel]
  have hx_sqEq : x ^ 2 = 1 := by
    rw [hx_def, mul_pow, h_sqEq, inv_pow, mul_inv_cancel]
  have h_ord_p : orderOf x ∣ p := orderOf_dvd_of_pow_eq_one hx_pTorsion
  have h_ord_2 : orderOf x ∣ 2 := orderOf_dvd_of_pow_eq_one hx_sqEq
  have hp_prime : Nat.Prime p := Fact.out
  have h_cop : Nat.Coprime p 2 := by
    rw [Nat.coprime_comm, Nat.coprime_primes Nat.prime_two hp_prime]
    exact fun h ↦ hp_odd h.symm
  have h_ord_one : orderOf x = 1 := by
    have h_gcd : orderOf x ∣ Nat.gcd p 2 := Nat.dvd_gcd h_ord_p h_ord_2
    rw [h_cop] at h_gcd
    exact Nat.dvd_one.mp h_gcd
  have hx_eq_one : x = 1 := orderOf_eq_one_iff.mp h_ord_one
  rw [hx_def] at hx_eq_one
  exact (mul_inv_eq_one).mp hx_eq_one

omit [Fact (Nat.Prime p)] [IsCyclotomicExtension {p} ℚ K] in
/-- The actual case-I factor relation supplies the p-power equality needed by
`caseI_sigmaAntiClass_trivial_from_p_and_sq_torsion`.

This is just Chunk A repackaged in the equality shape consumed by Chunk E. -/
theorem caseI_conj_class_pow_eq_factor_class_pow
    {a b : ℤ} {ζ : 𝓞 K} (hζ : IsPrimitiveRoot ζ p)
    {I : Ideal (𝓞 K)} (hI_nz : I ≠ ⊥)
    (hI : Ideal.span ({(a : 𝓞 K) + ζ * (b : 𝓞 K)} : Set (𝓞 K)) = I ^ p) :
    (ClassGroup.mk0
        (⟨I.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom,
          mem_nonZeroDivisors_iff_ne_zero.mpr
            ((map_ne_bot_iff_complexConj K I).mpr hI_nz)⟩
          : nonZeroDivisors (Ideal (𝓞 K)))) ^ p =
      (ClassGroup.mk0
        (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_nz⟩
          : nonZeroDivisors (Ideal (𝓞 K)))) ^ p := by
  have h_torsion :=
    caseI_classes_pTorsion_from_principal_ideal
      (p := p) (K := K) hζ hI_nz hI
  exact h_torsion.2.trans h_torsion.1.symm

/-- Case-I class equality follows from the concrete square-class target.

For every actual FLT case-I factor ideal, the factor relation already proves
`[σI]^p = [I]^p`.  Therefore, under `p ≠ 2`, it remains only to prove the
specific square-class equality `[σI]^2 = [I]^2`; the Bezout argument then gives
the `CaseIClassEqDischarge` predicate used by the downstream AK-5a reduction. -/
theorem caseIClassEqDischarge_of_factor_class_square_eq
    (hp_odd : p ≠ 2)
    (h_sq :
      ∀ {a b c : ℤ}, ({a, b, c} : Finset ℤ).gcd id = 1 →
        ¬ (p : ℤ) ∣ a * b * c → a ^ p + b ^ p = c ^ p →
        ∀ {ζ : 𝓞 K}, IsPrimitiveRoot ζ p →
        ∀ {I : Ideal (𝓞 K)}, (hI_nz : I ≠ ⊥) →
          Ideal.span ({(a : 𝓞 K) + ζ * (b : 𝓞 K)} : Set (𝓞 K)) = I ^ p →
          (ClassGroup.mk0
              (⟨I.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom,
                mem_nonZeroDivisors_iff_ne_zero.mpr
                  ((map_ne_bot_iff_complexConj K I).mpr hI_nz)⟩
                : nonZeroDivisors (Ideal (𝓞 K)))) ^ 2 =
            (ClassGroup.mk0
              (⟨I, mem_nonZeroDivisors_iff_ne_zero.mpr hI_nz⟩
                : nonZeroDivisors (Ideal (𝓞 K)))) ^ 2) :
    CaseIClassEqDischarge p K := by
  intro a b c hgcd hcaseI heq ζ hζ I hI_nz hI
  exact caseI_sigmaAntiClass_trivial_from_p_and_sq_torsion
    (p := p) (K := K) hp_odd hI_nz
    (caseI_conj_class_pow_eq_factor_class_pow
      (p := p) (K := K) hζ hI_nz hI)
    (h_sq hgcd hcaseI heq hζ hI_nz hI)

omit [Fact (Nat.Prime p)] in
/-- **`caseI_class_p_ne_two_of_FLT_data`**: case-I FLT data forces p ≠ 2.

At p = 2: a²+b²=c² with 2 ∤ a·b·c. All odd ⟹ a²,b²,c² ≡ 1 mod 2;
a²+b² ≡ 0 mod 2, c² ≡ 1 mod 2; contradiction. -/
theorem caseI_class_p_ne_two_of_FLT_data
    {a b c : ℤ}
    (h_ndvd_abc : ¬ (p : ℤ) ∣ a * b * c)
    (h_eq : a ^ p + b ^ p = c ^ p) :
    p ≠ 2 := by
  intro hp_eq
  rw [hp_eq] at h_eq h_ndvd_abc
  have ha_odd : a % 2 ≠ 0 := by
    intro h
    apply h_ndvd_abc
    exact ((Int.dvd_of_emod_eq_zero h).mul_right _).mul_right _
  have hb_odd : b % 2 ≠ 0 := by
    intro h
    apply h_ndvd_abc
    exact ((Int.dvd_of_emod_eq_zero h).mul_left _).mul_right _
  have hc_odd : c % 2 ≠ 0 := by
    intro h
    apply h_ndvd_abc
    exact (Int.dvd_of_emod_eq_zero h).mul_left _
  have h_a_sq : a^2 % 2 = 1 := by
    have := Int.emod_two_eq_zero_or_one a
    rcases this with h | h
    · exact absurd h ha_odd
    · have : a^2 % 2 = (a*a) % 2 := by ring_nf
      rw [this, Int.mul_emod, h]; decide
  have h_b_sq : b^2 % 2 = 1 := by
    have := Int.emod_two_eq_zero_or_one b
    rcases this with h | h
    · exact absurd h hb_odd
    · have : b^2 % 2 = (b*b) % 2 := by ring_nf
      rw [this, Int.mul_emod, h]; decide
  have h_c_sq : c^2 % 2 = 1 := by
    have := Int.emod_two_eq_zero_or_one c
    rcases this with h | h
    · exact absurd h hc_odd
    · have : c^2 % 2 = (c*c) % 2 := by ring_nf
      rw [this, Int.mul_emod, h]; decide
  have : (a^2 + b^2) % 2 = c^2 % 2 := by rw [h_eq]
  omega

end CaseI

end LehmerVandiver

end FLT37

end BernoulliRegular

end
