/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import Mathlib.RingTheory.TensorProduct.Quotient
import Mathlib.RingTheory.TensorProduct.Maps
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.Polynomial.Basic

/-!
# `AdjoinRoot` commutes with base change (WP-D3c-2a)

`μ_N` over a field `k` is `Spec (AdjoinRoot ((X : k[X])^N − 1))`
(`GroupScheme/MuN.lean`'s `muNSpecFieldIso`), so transporting the field-level Weil pairing
along a map of fields `k → k'` needs `AdjoinRoot` to commute with base change. That is the
content here, for an arbitrary monic-or-not polynomial and an arbitrary algebra:

`k' ⊗[k] (k[X] ⧸ (f))  ≅  k'[X] ⧸ (f.map)`.

The proof is the standard three-step chain — `polyEquivTensor` to recognise `k'[X]` as
`k' ⊗[k] k[X]`, `Algebra.TensorProduct.cancelBaseChange` to move the tensor over `k[X]`, and
`Algebra.TensorProduct.quotIdealMapEquivTensorQuot` to identify the quotient.
-/

universe u

namespace ModularCurves

open Polynomial TensorProduct

variable (R S : Type u) [CommRing R] [CommRing S] [Algebra R S]

/-- The `R[X]`-algebra structure on `S[X]` induced by `R → S`, as a scoped instance for this
file's chain (mathlib has `Polynomial.mapRingHom` but no such `Algebra` instance). -/
@[reducible] noncomputable def polyAlgebra : Algebra R[X] S[X] :=
  (Polynomial.mapRingHom (algebraMap R S)).toAlgebra

attribute [local instance] polyAlgebra

/-- The tower `R → R[X] → S[X]` is scalar. -/
theorem isScalarTower_poly : @IsScalarTower R R[X] S[X] _ _ _ := by
  refine IsScalarTower.of_algebraMap_eq fun r => ?_
  show algebraMap R S[X] r = (Polynomial.mapRingHom (algebraMap R S)) (algebraMap R R[X] r)
  rw [Polynomial.algebraMap_apply, Polynomial.algebraMap_apply]
  simp

attribute [local instance] isScalarTower_poly

/-- **(WP-D3c-2a)** Mapping `X ^ N − 1` along `R → S` gives `X ^ N − 1`. -/
theorem map_X_pow_sub_one (N : ℕ) :
    ((X : R[X]) ^ N - 1).map (algebraMap R S) = (X : S[X]) ^ N - 1 := by
  simp

variable {R S}

/-- **(WP-D3c-2a)** The ideal generated by the image of `f` is the image of the ideal
generated by `f` — the bridge between `AdjoinRoot (f.map …)` and the `Ideal.map` form that
`Algebra.TensorProduct.quotIdealMapEquivTensorQuot` produces. -/
theorem span_map_eq_map_span (f : R[X]) :
    Ideal.span {f.map (algebraMap R S)} =
      Ideal.map (algebraMap R[X] S[X]) (Ideal.span {f}) := by
  rw [Ideal.map_span, Set.image_singleton]
  rfl

/-- **(WP-D3c-2a)** The quotient of `S[X]` by the mapped polynomial is the base change of the
quotient of `R[X]`. Stated with the explicit quotient rather than `AdjoinRoot`, because
`AdjoinRoot f` carries no `Module R[X]` instance (only the `R`-algebra structure through
`AdjoinRoot.of`), while `R[X] ⧸ Ideal.span {f}` — to which it is definitionally equal — does.

This is the half of the chain that `Algebra.TensorProduct.quotIdealMapEquivTensorQuot`
supplies directly. -/
noncomputable def quotSpanMapEquivTensor (f : R[X]) :
    (S[X] ⧸ Ideal.span {f.map (algebraMap R S)}) ≃ₐ[S[X]]
      TensorProduct R[X] S[X] (R[X] ⧸ Ideal.span {f}) :=
  (Ideal.quotientEquivAlgOfEq S[X] (span_map_eq_map_span (S := S) f)).trans
    (Algebra.TensorProduct.quotIdealMapEquivTensorQuot S[X] (Ideal.span {f}))

end ModularCurves
