/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import Mathlib.GroupTheory.Torsion
import Mathlib.Data.ZMod.Basic
import Mathlib.SetTheory.Cardinal.Finite

/-!
# Two generators of an `N²`-element torsion group have exact order `N` (WP-D1a, algebra half)

A naive full level-`N` structure says only that `P` and `Q` *generate* the `N`-torsion; a
naive `Γ₁(N)`-structure demands that `P` have *exact order* `N`. The bridge between them is
a counting argument, and this file is its group-theoretic half, stated for an arbitrary
additive abelian group so that no geometry is involved:

if every `N`-torsion element lies in the subgroup generated by `P` and `Q`, and the
`N`-torsion has exactly `N²` elements, then neither generator can have order `< N` — an
element of order `d` would confine the whole subgroup to at most `d · N` elements.

The geometric half (that `E[N](k̄)` has `N²` elements) is supplied downstream from
`HasseWeil`'s `torsion_genN_addEquiv` through the fibre-point dictionary.
-/

namespace ModularCurves

variable {A : Type*} [AddCommGroup A]

/-- Every element of the subgroup generated by `P` and `Q`, when `P` is killed by `d` and
`Q` by `n`, is `i • P + j • Q` for `i < d` and `j < n`. -/
theorem exists_lt_smul_add_smul_of_mem_closure_pair {P Q : A} {d n : ℕ}
    (hd : 0 < d) (hn : 0 < n) (hdP : (d : ℤ) • P = 0) (hnQ : (n : ℤ) • Q = 0)
    {x : A} (hx : x ∈ AddSubgroup.closure ({P, Q} : Set A)) :
    ∃ i < d, ∃ j < n, x = (i : ℤ) • P + (j : ℤ) • Q := by
  obtain ⟨m, k, hmk⟩ := AddSubgroup.mem_closure_pair.mp hx
  refine ⟨(m % (d : ℤ)).toNat, ?_, (k % (n : ℤ)).toNat, ?_, ?_⟩
  · have h1 : m % (d : ℤ) < (d : ℤ) := Int.emod_lt_of_pos m (by exact_mod_cast hd)
    omega
  · have h1 : k % (n : ℤ) < (n : ℤ) := Int.emod_lt_of_pos k (by exact_mod_cast hn)
    omega
  · have hmP : ((m % (d : ℤ)).toNat : ℤ) • P = m • P := by
      rw [Int.toNat_of_nonneg (Int.emod_nonneg m (by exact_mod_cast hd.ne'))]
      conv_rhs => rw [← Int.mul_ediv_add_emod m (d : ℤ)]
      rw [add_smul, mul_smul, smul_comm, hdP, smul_zero, zero_add]
    have hkQ : ((k % (n : ℤ)).toNat : ℤ) • Q = k • Q := by
      rw [Int.toNat_of_nonneg (Int.emod_nonneg k (by exact_mod_cast hn.ne'))]
      conv_rhs => rw [← Int.mul_ediv_add_emod k (n : ℤ)]
      rw [add_smul, mul_smul, smul_comm, hnQ, smul_zero, zero_add]
    rw [hmP, hkQ, hmk]

/-- **(WP-D1a, algebra half)** If `P` and `Q` generate the `N`-torsion of `A`, and `P` is
killed by `d` while `Q` is killed by `n`, then the `N`-torsion has at most `d · n` elements.

Applied with `n = N`, this is the counting step: an element of order `d < N` would confine
the `N`-torsion to `d · N < N²` elements. -/
theorem ncard_torsion_le_of_closure_pair {P Q : A} {d n : ℕ}
    (hd : 0 < d) (hn : 0 < n) (hdP : (d : ℤ) • P = 0) (hnQ : (n : ℤ) • Q = 0)
    (N : ℕ) (hgen : ∀ x : A, (N : ℤ) • x = 0 → x ∈ AddSubgroup.closure ({P, Q} : Set A)) :
    {x : A | (N : ℤ) • x = 0}.ncard ≤ d * n := by
  classical
  set f : Fin d × Fin n → A := fun p => ((p.1 : ℕ) : ℤ) • P + ((p.2 : ℕ) : ℤ) • Q with hf
  have hsub : {x : A | (N : ℤ) • x = 0} ⊆ Set.range f := by
    intro x hx
    obtain ⟨i, hi, j, hj, hxij⟩ :=
      exists_lt_smul_add_smul_of_mem_closure_pair hd hn hdP hnQ (hgen x hx)
    exact ⟨(⟨i, hi⟩, ⟨j, hj⟩), hxij.symm⟩
  calc {x : A | (N : ℤ) • x = 0}.ncard
      ≤ (Set.range f).ncard := Set.ncard_le_ncard hsub (Set.finite_range f)
    _ = (f '' Set.univ).ncard := by rw [Set.image_univ]
    _ ≤ (Set.univ : Set (Fin d × Fin n)).ncard := Set.ncard_image_le Set.finite_univ
    _ = d * n := by simp

/-- **(WP-D1a, algebra half — the usable form)** Two generators of an `N²`-element
`N`-torsion group both have exact order `N`. -/
theorem smul_ne_zero_of_closure_pair_of_ncard {P Q : A} {N : ℕ} (hN : 0 < N)
    (hQ : (N : ℤ) • Q = 0)
    (hgen : ∀ x : A, (N : ℤ) • x = 0 → x ∈ AddSubgroup.closure ({P, Q} : Set A))
    (hcard : {x : A | (N : ℤ) • x = 0}.ncard = N * N)
    {d : ℕ} (hd : 0 < d) (hdN : d < N) : (d : ℤ) • P ≠ 0 := by
  intro hdP
  have hle := ncard_torsion_le_of_closure_pair hd hN hdP hQ N hgen
  rw [hcard] at hle
  exact absurd hle (Nat.not_le.mpr ((Nat.mul_lt_mul_right hN).mpr hdN))

end ModularCurves
