import Mathlib.RingTheory.FinitePresentation
import Mathlib.RingTheory.Flat.FaithfullyFlat.Algebra
import Mathlib.RingTheory.RingHom.FaithfullyFlat
import Mathlib.RingTheory.TensorProduct.Basic
import Mathlib.RingTheory.TensorProduct.Maps
import Mathlib.RingTheory.FiniteStability
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.Tactic.Algebraize
import ModularCurves.ForMathlib.FaithfullyFlatEqualizer

/-!
# [02KL-CORE]: finite presentation reflects along a faithfully flat, finitely presented composite

Campaign file for the sorried gate `RingHom.FinitePresentation.of_comp_of_faithfullyFlat`
(`ForMathlib/SmoothDescent.lean`, Stacks **02KK** = Descent, Lemma 35.14.1):

> Let `R → A → B` be ring maps. Assume `R → B` is of finite presentation and `A → B`
> faithfully flat and of finite presentation. Then `R → A` is of finite presentation.

Decomposition of record: `.mathlib-quality/decomposition-02kl-core.md` (board v10.99a).
Architecture ("ENDING-1", concrete filtered systems, no category-theory transport):

* `Algebra.IsFilteredAlgColimit` — the three-field concrete colimit predicate;
* **[KL-0]** `Algebra.FinitePresentation.of_retract` — retracts of FP algebras are FP
  (the `(3) ⟹ (1)` endgame of Stacks 00QO);
* **[KL-1]** `Algebra.PresentationSystem` — the canonical presentation system of an
  algebra: FP stages `R[x_s]/J` indexed by finite variable sets and FG relation
  sub-ideals, with colimit `A` (Stacks 10.127.2);
* **[KL-2]** `exists_spreadData` — an FP algebra over the colimit descends to a stage
  presentation, with stage models and colimit recovery (flatless half of Stacks 02JO(2));
* **[KL-3]** `SpreadData.exists_flat_stage` — **flat at a large stage** (Stacks
  02JO(1)+(3); the boss: ℤ-model reduction + noetherian local criterion + flat-locus
  openness + quasicompact glue);
* **[KL-4]** `SpreadData.exists_faithfullyFlat_stage` — faithfully flat at a large stage
  (patch topology: Chevalley image, stage-image patch-closedness, fibre contraction);
* **[KL-5]** stage-factoring/agreement for FP/FT sources + the tensor-of-systems colimit
  + the Amitsur endgame (project `Module.FaithfullyFlat.mem_range_algebraMap_iff_tmul_eq`),
  assembling `Algebra.FinitePresentation.of_comp_of_faithfullyFlat` and the `RingHom`
  wrapper `RingHom.FinitePresentation.of_comp_of_faithfullyFlat'` (primed to avoid a name
  clash with the registered gate; the gate flips to this on completion, board-coordinated).
-/

universe u

open TensorProduct

namespace Algebra

/-! ## The concrete filtered-colimit predicate -/

/-- `A` is exhibited as the filtered colimit of the directed system `𝒮` of `R`-algebras
along transition maps `t` and cocone maps `u`: transitions are functorial and compatible,
every element of `A` comes from a stage, and two stage elements agreeing in `A` agree at a
later stage. This is the concrete (choice-free interface) form of "filtered colimit of
rings"; it deliberately avoids `CategoryTheory.IsColimit` transport. -/
structure IsFilteredAlgColimit (R : Type u) [CommRing R] {ι : Type u} [Preorder ι]
    (𝒮 : ι → Type u) [∀ i, CommRing (𝒮 i)] [∀ i, Algebra R (𝒮 i)]
    (t : ∀ ⦃i j : ι⦄, i ≤ j → (𝒮 i →ₐ[R] 𝒮 j))
    (A : Type u) [CommRing A] [Algebra R A]
    (u : ∀ i, 𝒮 i →ₐ[R] A) : Prop where
  directed : IsDirected ι (· ≤ ·)
  nonempty : Nonempty ι
  t_trans : ∀ ⦃i j k : ι⦄ (hij : i ≤ j) (hjk : j ≤ k) (x : 𝒮 i),
    t hjk (t hij x) = t (hij.trans hjk) x
  compat : ∀ ⦃i j : ι⦄ (h : i ≤ j) (x : 𝒮 i), u j (t h x) = u i x
  jointly_surjective : ∀ a : A, ∃ (i : ι) (x : 𝒮 i), u i x = a
  eq_at_stage : ∀ ⦃i : ι⦄ (x y : 𝒮 i), u i x = u i y → ∃ (j : ι) (h : i ≤ j), t h x = t h y

/-! ## [KL-0] Retracts of finitely presented algebras are finitely presented -/

/-- **[KL-0] (inside Stacks 00QO, (3) ⟹ (1)).** A retract of a finitely presented
`R`-algebra is finitely presented: if `ρ ∘ σ = id` with `B` FP, then `A` is FP.

Proof sketch: `ρ` is surjective, and `ker ρ` is generated by the finitely many elements
`bⱼ - σ(ρ(bⱼ))` for `bⱼ` algebra generators of `B` (mod that ideal, `q ∘ (σ ∘ ρ)` and `q`
are `R`-algebra maps agreeing on generators, hence equal; so `ρ b = 0` forces
`q b = q (σ (ρ b)) = 0`). Conclude by `FinitePresentation.quotient` and transport along
`Ideal.quotientKerAlgEquivOfSurjective`. -/
theorem FinitePresentation.of_retract {R A B : Type u} [CommRing R] [CommRing A] [CommRing B]
    [Algebra R A] [Algebra R B] [FinitePresentation R B]
    (σ : A →ₐ[R] B) (ρ : B →ₐ[R] A) (hρσ : ρ.comp σ = AlgHom.id R A) :
    FinitePresentation R A := by
  classical
  have hρσ' : ∀ a : A, ρ (σ a) = a := fun a => AlgHom.congr_fun hρσ a
  have hρ : Function.Surjective ρ := fun a => ⟨σ a, hρσ' a⟩
  -- a finite algebra generating set of `B`
  obtain ⟨s, hs⟩ := (Algebra.FiniteType.of_finitePresentation : Algebra.FiniteType R B).out
  -- the finitely generated candidate for `ker ρ`
  set J : Ideal B := Ideal.span ((fun b => b - σ (ρ b)) '' ↑s) with hJ
  have hJfg : J.FG := ⟨s.image fun b => b - σ (ρ b), by rw [hJ, Finset.coe_image]⟩
  -- `J ≤ ker ρ`
  have hJle : J ≤ RingHom.ker ρ := by
    rw [hJ, Ideal.span_le]
    rintro - ⟨b, -, rfl⟩
    simp only [SetLike.mem_coe, RingHom.mem_ker, map_sub, hρσ' (ρ b), sub_self]
  -- `ker ρ ≤ J`: mod `J`, the endomorphism `σ ∘ ρ` is the identity on generators
  have hker : RingHom.ker ρ = J := by
    refine le_antisymm (fun x hx => ?_) hJle
    have hq : (Ideal.Quotient.mkₐ R J).comp (σ.comp ρ) = Ideal.Quotient.mkₐ R J := by
      have hle : Algebra.adjoin R (↑s : Set B) ≤
          AlgHom.equalizer ((Ideal.Quotient.mkₐ R J).comp (σ.comp ρ))
            (Ideal.Quotient.mkₐ R J) := by
        refine Algebra.adjoin_le fun b hb => ?_
        show Ideal.Quotient.mkₐ R J (σ (ρ b)) = Ideal.Quotient.mkₐ R J b
        rw [eq_comm, ← sub_eq_zero, ← map_sub]
        exact Ideal.Quotient.eq_zero_iff_mem.2 (Ideal.subset_span ⟨b, hb, rfl⟩)
      refine AlgHom.ext fun b => ?_
      exact hle (hs ▸ Algebra.mem_top : b ∈ Algebra.adjoin R (↑s : Set B))
    have hx0 : Ideal.Quotient.mkₐ R J x = 0 := by
      have := AlgHom.congr_fun hq x
      simp only [AlgHom.comp_apply] at this
      rw [← this, RingHom.mem_ker.1 hx, map_zero, map_zero]
    exact Ideal.Quotient.eq_zero_iff_mem.1 hx0
  -- conclude: `A ≃ B ⧸ ker ρ = B ⧸ J`, a quotient of an FP algebra by an FG ideal
  haveI : FinitePresentation R (B ⧸ J) := FinitePresentation.quotient hJfg
  exact FinitePresentation.equiv
    ((Ideal.quotientEquivAlgOfEq R hker.symm).trans
      (Ideal.quotientKerAlgEquivOfSurjective hρ))

/-! ## [KL-1] The canonical presentation system of an algebra -/

namespace PresentationSystem

variable (R A : Type u) [CommRing R] [CommRing A] [Algebra R A]

/-- **[KL-1] index.** A stage of the canonical presentation system of the `R`-algebra `A`:
a finite set `vars` of elements of `A` and a finitely generated ideal of relations among
them that genuinely hold in `A` (i.e. is contained in the kernel of evaluation). -/
structure Index : Type u where
  vars : Finset A
  rels : Ideal (MvPolynomial {a // a ∈ vars} R)
  rels_fg : rels.FG
  rels_le : rels ≤ RingHom.ker
    (MvPolynomial.aeval (Subtype.val : {a // a ∈ vars} → A) :
      MvPolynomial {a // a ∈ vars} R →ₐ[R] A)

variable {R A}

/-- The inclusion of variable subtypes along a containment of variable sets. -/
def Index.incl {s t : Finset A} (h : s ⊆ t) :
    {a // a ∈ s} → {a // a ∈ t} :=
  fun x => ⟨x.1, h x.2⟩

/-- The inclusion along a reflexive containment is the identity (structure eta +
proof irrelevance make this definitional). -/
theorem Index.incl_rfl {s : Finset A} (h : s ⊆ s) :
    Index.incl h = (_root_.id : {a // a ∈ s} → {a // a ∈ s}) := rfl

/-- Inclusions compose (definitionally, by proof irrelevance). -/
theorem Index.incl_comp {s t v : Finset A} (h₁ : s ⊆ t) (h₂ : t ⊆ v) :
    Index.incl (h₁.trans h₂) = Index.incl h₂ ∘ Index.incl h₁ := rfl

/-- The inclusion does not depend on the containment proof. -/
theorem Index.incl_irrel {s t : Finset A} (h h' : s ⊆ t) :
    Index.incl h = Index.incl h' := rfl

/-- Mapping an ideal along the rename by a reflexive inclusion is the identity. -/
theorem Index.map_rename_incl_rfl {s : Finset A} (h : s ⊆ s)
    (I : Ideal (MvPolynomial {a // a ∈ s} R)) :
    I.map (MvPolynomial.rename (Index.incl h) : _ →ₐ[R] _) = I := by
  rw [Index.incl_rfl, MvPolynomial.rename_id]
  exact (show I.map (AlgHom.id R _) = I.map (RingHom.id _) from rfl).trans (Ideal.map_id I)

/-- The sup of two finitely generated ideals is finitely generated (native `Ideal.FG`
spelling). -/
private theorem fg_sup {B' : Type u} [CommRing B'] {I J : Ideal B'}
    (hI : I.FG) (hJ : J.FG) : (I ⊔ J).FG := by
  classical
  obtain ⟨S, rfl⟩ := hI
  obtain ⟨T, rfl⟩ := hJ
  exact ⟨S ∪ T, by rw [Finset.coe_union, Ideal.span_union]⟩

/-- The image of a finitely generated ideal along a variable rename is finitely
generated (native `Ideal.FG` spelling, `AlgHom`-instance `Ideal.map`). -/
theorem Index.fg_map {s t : Finset A} (h : s ⊆ t)
    {I : Ideal (MvPolynomial {a // a ∈ s} R)} (hI : I.FG) :
    (I.map (MvPolynomial.rename (Index.incl h) : _ →ₐ[R] _)).FG := by
  classical
  obtain ⟨S, rfl⟩ := hI
  exact ⟨S.image ⇑(MvPolynomial.rename (Index.incl h) : _ →ₐ[R] _),
    by rw [Finset.coe_image, Ideal.map_span]⟩

instance : Preorder (Index R A) where
  le P Q := ∃ h : P.vars ⊆ Q.vars,
    P.rels.map (MvPolynomial.rename (Index.incl h) : _ →ₐ[R] _) ≤ Q.rels
  le_refl P := ⟨subset_rfl, le_of_eq (Index.map_rename_incl_rfl subset_rfl P.rels)⟩
  le_trans P Q S := by
    rintro ⟨h₁, hm₁⟩ ⟨h₂, hm₂⟩
    refine ⟨h₁.trans h₂, ?_⟩
    have hcomp : P.rels.map (MvPolynomial.rename (Index.incl (h₁.trans h₂)) : _ →ₐ[R] _)
        = (P.rels.map (MvPolynomial.rename (Index.incl h₁) : _ →ₐ[R] _)).map
            (MvPolynomial.rename (Index.incl h₂) : _ →ₐ[R] _) := by
      rw [Ideal.map_mapₐ, MvPolynomial.rename_comp_rename, ← Index.incl_comp h₁ h₂]
    rw [hcomp]
    exact le_trans (Ideal.map_mono hm₁) hm₂

/-- Renamed relation ideals still evaluate to zero: the image of `P.rels` along any
variable inclusion is contained in the evaluation kernel at the larger variable set. -/
theorem Index.map_incl_le_ker (P : Index R A) {t : Finset A} (h : P.vars ⊆ t) :
    P.rels.map (MvPolynomial.rename (Index.incl h) : _ →ₐ[R] _)
      ≤ RingHom.ker (MvPolynomial.aeval (Subtype.val : {a // a ∈ t} → A) :
          MvPolynomial {a // a ∈ t} R →ₐ[R] A) := by
  rw [Ideal.map_le_iff_le_comap]
  intro x hx
  have hker : MvPolynomial.aeval (Subtype.val : {a // a ∈ P.vars} → A) x = 0 :=
    RingHom.mem_ker.1 (P.rels_le hx)
  rw [Ideal.mem_comap, RingHom.mem_ker, MvPolynomial.aeval_rename]
  exact hker

/-- **[KL-1] union refinement**: the join of two stages — union the variables, sum the
transported relation ideals. -/
noncomputable def Index.sup [DecidableEq A] (P Q : Index R A) : Index R A where
  vars := P.vars ∪ Q.vars
  rels := P.rels.map (MvPolynomial.rename
        (Index.incl (Finset.subset_union_left : P.vars ⊆ P.vars ∪ Q.vars)) : _ →ₐ[R] _)
      ⊔ Q.rels.map (MvPolynomial.rename
        (Index.incl (Finset.subset_union_right : Q.vars ⊆ P.vars ∪ Q.vars)) : _ →ₐ[R] _)
  rels_fg := fg_sup (Index.fg_map Finset.subset_union_left P.rels_fg)
    (Index.fg_map Finset.subset_union_right Q.rels_fg)
  rels_le := sup_le (P.map_incl_le_ker Finset.subset_union_left)
    (Q.map_incl_le_ker Finset.subset_union_right)

theorem Index.le_sup_left [DecidableEq A] (P Q : Index R A) : P ≤ Index.sup P Q :=
  ⟨Finset.subset_union_left, _root_.le_sup_left⟩

theorem Index.le_sup_right [DecidableEq A] (P Q : Index R A) : Q ≤ Index.sup P Q :=
  ⟨Finset.subset_union_right, _root_.le_sup_right⟩

/-- **[KL-1] one-relation enlargement**: adjoin a single vanishing relation to a stage. -/
noncomputable def Index.enlarge (P : Index R A) (r : MvPolynomial {a // a ∈ P.vars} R)
    (hr : r ∈ RingHom.ker (MvPolynomial.aeval (Subtype.val : {a // a ∈ P.vars} → A) :
      MvPolynomial {a // a ∈ P.vars} R →ₐ[R] A)) : Index R A where
  vars := P.vars
  rels := P.rels ⊔ Ideal.span {r}
  rels_fg := fg_sup P.rels_fg ⟨{r}, by rw [Finset.coe_singleton]⟩
  rels_le := sup_le P.rels_le ((Ideal.span_le).2 (Set.singleton_subset_iff.2 hr))

theorem Index.le_enlarge (P : Index R A) (r : MvPolynomial {a // a ∈ P.vars} R)
    (hr : r ∈ RingHom.ker (MvPolynomial.aeval (Subtype.val : {a // a ∈ P.vars} → A) :
      MvPolynomial {a // a ∈ P.vars} R →ₐ[R] A)) : P ≤ P.enlarge r hr := by
  refine ⟨subset_rfl, ?_⟩
  show P.rels.map (MvPolynomial.rename (Index.incl (subset_rfl : P.vars ⊆ P.vars)) : _ →ₐ[R] _)
    ≤ P.rels ⊔ Ideal.span {r}
  rw [Index.map_rename_incl_rfl]
  exact _root_.le_sup_left


variable (R A)

/-- **[KL-1] stages.** The stage algebra at an index: the free algebra on the variables
modulo the recorded relations. Finitely presented over `R` by construction
(`stage_finitePresentation`). -/
abbrev stage (P : Index R A) : Type u :=
  MvPolynomial {a // a ∈ P.vars} R ⧸ P.rels

/-- **[KL-1] transitions**: rename along the variable inclusion, descended to quotients.
(The inclusion function is proof-irrelevant, so functoriality is honest.) -/
noncomputable def transition ⦃P Q : Index R A⦄ (h : P ≤ Q) :
    stage R A P →ₐ[R] stage R A Q :=
  Ideal.Quotient.liftₐ P.rels
    ((Ideal.Quotient.mkₐ R Q.rels).comp (MvPolynomial.rename (Index.incl h.choose)))
    (fun a ha => by
      have hmem : MvPolynomial.rename (Index.incl h.choose) a
          ∈ P.rels.map (MvPolynomial.rename (Index.incl h.choose) : _ →ₐ[R] _) :=
        Ideal.mem_map_of_mem _ ha
      simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk]
      exact Ideal.Quotient.eq_zero_iff_mem.2 (h.choose_spec hmem))

/-- **[KL-1] cocone**: evaluation of variables in `A`, descended to the stage. -/
noncomputable def colimMap (P : Index R A) : stage R A P →ₐ[R] A :=
  Ideal.Quotient.liftₐ P.rels (MvPolynomial.aeval (Subtype.val : {a // a ∈ P.vars} → A))
    (fun _ ha => (RingHom.mem_ker).1 (P.rels_le ha))

/-- The transition map on residue classes: rename, then project (stated for an arbitrary
containment proof — the inclusion is proof-irrelevant). -/
theorem transition_mk ⦃P Q : Index R A⦄ (h : P ≤ Q) (hsub : P.vars ⊆ Q.vars)
    (p : MvPolynomial {a // a ∈ P.vars} R) :
    transition R A h (Ideal.Quotient.mk P.rels p)
      = Ideal.Quotient.mk Q.rels (MvPolynomial.rename (Index.incl hsub) p) := by
  rw [Index.incl_irrel hsub h.choose]
  exact Ideal.Quotient.lift_mk P.rels _ _

/-- The cocone map on residue classes: evaluate the variables. -/
theorem colimMap_mk (P : Index R A) (p : MvPolynomial {a // a ∈ P.vars} R) :
    colimMap R A P (Ideal.Quotient.mk P.rels p)
      = MvPolynomial.aeval (Subtype.val : {a // a ∈ P.vars} → A) p :=
  Ideal.Quotient.lift_mk P.rels _ _

/-- **[KL-1a].** Every stage of the canonical presentation system is finitely presented
over `R` (`MvPolynomial` on a finite type, quotient by an FG ideal). -/
theorem stage_finitePresentation (P : Index R A) :
    FinitePresentation R (stage R A P) :=
  show FinitePresentation R (MvPolynomial {a // a ∈ P.vars} R ⧸ P.rels) from
    FinitePresentation.quotient P.rels_fg

/-- **[KL-1b] (Stacks 10.127.2).** The canonical presentation system is a filtered
colimit presentation of `A`: directed (union of variables, sum of transported relations),
jointly surjective (`a` is hit by the stage `({a}, ⊥)`), with equality at a later stage
(a vanishing lift of a difference is itself a relation — enlarge the relation ideal by it). -/
theorem isFilteredAlgColimit :
    IsFilteredAlgColimit R (stage R A) (transition R A) A (colimMap R A) := by
  classical
  constructor
  -- directed: union refinement
  · exact ⟨fun P Q => ⟨Index.sup P Q, Index.le_sup_left P Q, Index.le_sup_right P Q⟩⟩
  -- nonempty: the empty stage
  · exact ⟨⟨∅, ⊥, ⟨∅, by simp⟩, bot_le⟩⟩
  -- functoriality of transitions
  · intro P Q S hPQ hQS x
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    rw [transition_mk R A hPQ hPQ.choose, transition_mk R A hQS hQS.choose,
      transition_mk R A (hPQ.trans hQS) (hPQ.choose.trans hQS.choose),
      MvPolynomial.rename_rename]
    rfl
  -- cocone compatibility
  · intro P Q h x
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    rw [transition_mk R A h h.choose, colimMap_mk, colimMap_mk, MvPolynomial.aeval_rename]
    rfl
  -- joint surjectivity: `a` is the class of its own variable at the singleton stage
  · intro a
    refine ⟨⟨{a}, ⊥, ⟨∅, by simp⟩, bot_le⟩,
      Ideal.Quotient.mk _ (MvPolynomial.X ⟨a, Finset.mem_singleton_self a⟩), ?_⟩
    rw [colimMap_mk, MvPolynomial.aeval_X]
  -- equality at a later stage: enlarge the relations by the vanishing difference
  · intro P x y hxy
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    obtain ⟨q, rfl⟩ := Ideal.Quotient.mk_surjective y
    rw [colimMap_mk, colimMap_mk] at hxy
    have hpq : p - q ∈ RingHom.ker
        (MvPolynomial.aeval (Subtype.val : {a // a ∈ P.vars} → A) :
          MvPolynomial {a // a ∈ P.vars} R →ₐ[R] A) := by
      rw [RingHom.mem_ker, map_sub, sub_eq_zero]
      exact hxy
    -- the enlarged stage
    refine ⟨P.enlarge (p - q) hpq, P.le_enlarge (p - q) hpq, ?_⟩
    rw [transition_mk R A (P.le_enlarge (p - q) hpq) subset_rfl p,
      transition_mk R A (P.le_enlarge (p - q) hpq) subset_rfl q, Ideal.Quotient.eq,
      ← map_sub]
    show MvPolynomial.rename (Index.incl (subset_rfl : P.vars ⊆ P.vars)) (p - q)
      ∈ P.rels ⊔ Ideal.span {p - q}
    rw [Index.incl_rfl, MvPolynomial.rename_id_apply]
    exact Ideal.mem_sup_right (Ideal.subset_span rfl)

end PresentationSystem

/-! ## [KL-2] Spreading out a finitely presented algebra over a filtered system -/

section Spread

variable {R : Type u} [CommRing R] {ι : Type u} [Preorder ι]
  {𝒮 : ι → Type u} [∀ i, CommRing (𝒮 i)] [∀ i, Algebra R (𝒮 i)]
  {t : ∀ ⦃i j : ι⦄, i ≤ j → (𝒮 i →ₐ[R] 𝒮 j)}
  {A : Type u} [CommRing A] [Algebra R A] {u : ∀ i, 𝒮 i →ₐ[R] A}

/-- Finitely many elements of the colimit lift jointly to a common stage. -/
theorem IsFilteredAlgColimit.exists_common_lift (H : IsFilteredAlgColimit R 𝒮 t A u)
    {κ : Type*} [Finite κ] (a : κ → A) :
    ∃ (i : ι) (x : κ → 𝒮 i), ∀ k, u i (x k) = a k := by
  classical
  cases nonempty_fintype κ
  haveI := H.directed
  haveI := H.nonempty
  choose idx xk hxk using fun k => H.jointly_surjective (a k)
  obtain ⟨i, hi⟩ := (Finset.univ.image idx).exists_le
  exact ⟨i,
    fun k => t (hi (idx k) (Finset.mem_image_of_mem idx (Finset.mem_univ k))) (xk k),
    fun k => by rw [H.compat, hxk]⟩

/-- Finitely many stage equalities that hold in the colimit hold at a common later
stage. -/
theorem IsFilteredAlgColimit.exists_common_eq (H : IsFilteredAlgColimit R 𝒮 t A u)
    {κ : Type*} [Finite κ] ⦃i : ι⦄ (x y : κ → 𝒮 i) (hxy : ∀ k, u i (x k) = u i (y k)) :
    ∃ (j : ι) (h : i ≤ j), ∀ k, t h (x k) = t h (y k) := by
  classical
  cases nonempty_fintype κ
  haveI := H.directed
  haveI := H.nonempty
  choose jdx hj he using fun k => H.eq_at_stage (x k) (y k) (hxy k)
  obtain ⟨j₀, hj₀⟩ := (insert i (Finset.univ.image jdx)).exists_le
  have hij : i ≤ j₀ := hj₀ i (Finset.mem_insert_self i _)
  refine ⟨j₀, hij, fun k => ?_⟩
  have h' : jdx k ≤ j₀ :=
    hj₀ (jdx k) (Finset.mem_insert_of_mem (Finset.mem_image_of_mem jdx (Finset.mem_univ k)))
  show t ((hj k).trans h') (x k) = t ((hj k).trans h') (y k)
  rw [← H.t_trans (hj k) h', ← H.t_trans (hj k) h', he k]

variable (𝒮 t u) in
/-- **[KL-2] spread data.** A presentation of the `A`-algebra `B` descended to the stage
`i₀` of a filtered system with colimit `A`: `m` variables, `k` relation polynomials `g`
with coefficients in `𝒮 i₀`, whose pushforward to `A` presents `B`. The stage models are
`spreadStage` below. -/
structure SpreadData (B : Type u) [CommRing B] [Algebra A B] where
  i₀ : ι
  m : ℕ
  k : ℕ
  g : Fin k → MvPolynomial (Fin m) (𝒮 i₀)
  equiv : Nonempty
    ((MvPolynomial (Fin m) A ⧸
      Ideal.span (Set.range fun j => MvPolynomial.map ((u i₀).toRingHom) (g j))) ≃ₐ[A] B)

variable (B : Type u) [CommRing B] [Algebra A B]

/-- **[KL-2] (flatless half of Stacks 02JO(2)).** A finitely presented algebra over the
colimit of a filtered system descends to spread data at some stage: choose a presentation
`B ≅ A[y]/(ḡ)`, lift the finitely many coefficients of the `ḡ` jointly to a common stage
(joint surjectivity + directedness), and correct the finitely many coefficient equalities
at a later stage (`eq_at_stage`). -/
theorem exists_spreadData (H : IsFilteredAlgColimit R 𝒮 t A u)
    [FinitePresentation A B] : Nonempty (SpreadData 𝒮 u B) := by
  classical
  obtain ⟨m, π, hπ, hker⟩ := ‹FinitePresentation A B›.out
  obtain ⟨G, hG⟩ := hker
  have hG' : Ideal.span (G : Set (MvPolynomial (Fin m) A)) = RingHom.ker π := hG
  set k := Fintype.card ↥G with hk
  set e : ↥G ≃ Fin k := Fintype.equivFin ↥G with he
  -- jointly lift every coefficient of every generator to a common stage
  obtain ⟨i₀, x, hx⟩ := H.exists_common_lift
    (fun d : Σ j : Fin k, ↥((e.symm j : MvPolynomial (Fin m) A).support) =>
      (e.symm d.1 : MvPolynomial (Fin m) A).coeff d.2)
  -- reconstruct the generators over the stage
  set g : Fin k → MvPolynomial (Fin m) (𝒮 i₀) := fun j =>
    ∑ d ∈ (e.symm j : MvPolynomial (Fin m) A).support.attach,
      MvPolynomial.monomial d.1 (x ⟨j, d⟩) with hg
  have hmap : ∀ j, MvPolynomial.map ((u i₀).toRingHom) (g j)
      = (e.symm j : MvPolynomial (Fin m) A) := by
    intro j
    rw [hg]
    calc (MvPolynomial.map ((u i₀).toRingHom))
          (∑ d ∈ (e.symm j : MvPolynomial (Fin m) A).support.attach,
            MvPolynomial.monomial d.1 (x ⟨j, d⟩))
        = ∑ d ∈ (e.symm j : MvPolynomial (Fin m) A).support.attach,
            MvPolynomial.monomial d.1
              ((e.symm j : MvPolynomial (Fin m) A).coeff d.1) := by
          rw [map_sum]
          exact Finset.sum_congr rfl fun d _ => by
            rw [MvPolynomial.map_monomial]
            exact congrArg _ (hx ⟨j, d⟩)
      _ = ∑ d ∈ (e.symm j : MvPolynomial (Fin m) A).support,
            MvPolynomial.monomial d
              ((e.symm j : MvPolynomial (Fin m) A).coeff d) :=
          Finset.sum_attach _ (fun d => MvPolynomial.monomial d
            ((e.symm j : MvPolynomial (Fin m) A).coeff d))
      _ = (e.symm j : MvPolynomial (Fin m) A) :=
          MvPolynomial.support_sum_monomial_coeff _
  have hrange : (Set.range fun j => MvPolynomial.map ((u i₀).toRingHom) (g j))
      = (G : Set (MvPolynomial (Fin m) A)) := by
    rw [funext hmap]
    exact Set.ext fun p =>
      ⟨fun ⟨j, hj⟩ => hj ▸ (e.symm j).2, fun hp => ⟨e ⟨p, hp⟩, by simp⟩⟩
  have hspan : Ideal.span (Set.range fun j => MvPolynomial.map ((u i₀).toRingHom) (g j))
      = RingHom.ker π := by rw [hrange, hG']
  exact ⟨⟨i₀, m, k, g,
    ⟨(Ideal.quotientEquivAlgOfEq A hspan).trans (Ideal.quotientKerAlgEquivOfSurjective hπ)⟩⟩⟩

variable {B}

/-- **[KL-2] stage models**: the descended presentation instantiated at any later stage. -/
abbrev SpreadData.spreadStage (D : SpreadData 𝒮 u B) ⦃i : ι⦄ (h : D.i₀ ≤ i) : Type u :=
  MvPolynomial (Fin D.m) (𝒮 i) ⧸
    Ideal.span (Set.range fun j => MvPolynomial.map (t h).toRingHom (D.g j))

/-- **[KL-2a].** Each stage model is finitely presented over its stage base. -/
theorem SpreadData.spreadStage_finitePresentation (D : SpreadData 𝒮 u B)
    ⦃i : ι⦄ (h : D.i₀ ≤ i) :
    FinitePresentation (𝒮 i) (D.spreadStage (t := t) h) := by
  classical
  have hfg : (Ideal.span (Set.range fun j => MvPolynomial.map (t h).toRingHom (D.g j))).FG :=
    ⟨Finset.univ.image fun j => MvPolynomial.map (t h).toRingHom (D.g j), by
      rw [Finset.coe_image, Finset.coe_univ, Set.image_univ]⟩
  exact FinitePresentation.quotient hfg

/-- **[KL-2b].** Base change of a stage model along a later transition is the later stage
model: `𝒮 j ⊗[𝒮 i] spreadStage i ≃ spreadStage j` (as `𝒮 j`-algebras). -/
theorem SpreadData.spreadStage_baseChange (D : SpreadData 𝒮 u B)
    ⦃i j : ι⦄ (hij : i ≤ j) (h : D.i₀ ≤ i) (H : IsFilteredAlgColimit R 𝒮 t A u) :
    letI : Algebra (𝒮 i) (𝒮 j) := (t hij).toRingHom.toAlgebra
    Nonempty ((𝒮 j ⊗[𝒮 i] D.spreadStage (t := t) h) ≃ₐ[𝒮 j]
      D.spreadStage (t := t) (h.trans hij)) := by
  sorry

/-- **[KL-2c].** Base change of a stage model to the colimit recovers `B`:
`A ⊗[𝒮 i] spreadStage i ≃ B` (as `A`-algebras). -/
theorem SpreadData.baseChange_colim (D : SpreadData 𝒮 u B)
    ⦃i : ι⦄ (h : D.i₀ ≤ i) (H : IsFilteredAlgColimit R 𝒮 t A u) :
    letI : Algebra (𝒮 i) A := (u i).toRingHom.toAlgebra
    Nonempty ((A ⊗[𝒮 i] D.spreadStage (t := t) h) ≃ₐ[A] B) := by
  sorry

/-! ## [KL-3] Flatness at a large stage — THE BOSS (Stacks 02JO(1)+(3)) -/

/-- **[KL-3] (Stacks 02JO = Algebra 10.168.1, scoped).** If the colimit algebra `B` is
flat over `A`, then some later stage model is flat over its stage base. Internals (own
sub-decomposition on reach; tickets [KL-3a–d]): reduce to a finite-type-ℤ (noetherian)
model under `𝒮 i₀` by re-instantiating [KL-1]+[KL-2] over `ℤ`; per-prime flatness at a
large stage by the noetherian local criterion; openness of the flat(=free) locus at
noetherian stages; quasicompact glue; transport back along stage factoring. -/
theorem SpreadData.exists_flat_stage (D : SpreadData 𝒮 u B)
    (H : IsFilteredAlgColimit R 𝒮 t A u) [Algebra R B] [IsScalarTower R A B]
    [Module.Flat A B] :
    ∃ (i : ι) (h : D.i₀ ≤ i), Module.Flat (𝒮 i) (D.spreadStage (t := t) h) := by
  sorry

/-! ## [KL-4] Faithful flatness at a large stage (the 01UA leg) -/

/-- **[KL-4].** If moreover `B` is faithfully flat over `A`, some later stage model is
faithfully flat over its stage base. Route: fibre nonvanishing at stage `i` depends only
on the contraction of the prime to `𝒮 i₁` (base-change collapse of the fibre); the target
locus `W = range (comap (𝒮 i₁ → spreadStage i₁))` is constructible (Chevalley;
`PrimeSpectrum.isConstructible_range_comap`) hence patch-open; the stage images
`range (comap (𝒮 i₁ → 𝒮 i))` are patch-closed; their directed intersection lies in `W`
by the 1 ≠ 0-at-a-stage fibre argument and faithful flatness at the colimit; patch
compactness (`compactSpace_withConstructibleTopology`) gives one stage with image ⊆ `W`,
which is Spec-surjectivity there; flat + Spec-surjective = faithfully flat. -/
theorem SpreadData.exists_faithfullyFlat_stage (D : SpreadData 𝒮 u B)
    (H : IsFilteredAlgColimit R 𝒮 t A u) [Algebra R B] [IsScalarTower R A B]
    [Module.FaithfullyFlat A B] :
    ∃ (i : ι) (h : D.i₀ ≤ i), Module.FaithfullyFlat (𝒮 i) (D.spreadStage (t := t) h) := by
  sorry

/-! ## [KL-5] Stage factoring, stage agreement, and the assembly -/

/-- **[KL-5a] (concrete Stacks 00QO, (1) ⟹ (2) surjectivity).** An `R`-algebra map from a
finitely presented algebra into the colimit of a filtered system factors through a stage.
(Concrete twin of `RingHom.EssFiniteType.exists_eq_comp_ι_app_of_isColimit`.) -/
theorem IsFilteredAlgColimit.exists_factor_of_finitePresentation
    (H : IsFilteredAlgColimit R 𝒮 t A u) (B : Type u) [CommRing B] [Algebra R B]
    [FinitePresentation R B] (f : B →ₐ[R] A) :
    ∃ (i : ι) (f' : B →ₐ[R] 𝒮 i), (u i).comp f' = f := by
  classical
  obtain ⟨n, π, hπ, hker⟩ := ‹FinitePresentation R B›.out
  obtain ⟨i₀, x, hx⟩ := H.exists_common_lift fun k => f (π (MvPolynomial.X k))
  set ψ₀ : MvPolynomial (Fin n) R →ₐ[R] 𝒮 i₀ := MvPolynomial.aeval x with hψ₀
  have hcomm : (u i₀).comp ψ₀ = f.comp π := by
    apply MvPolynomial.algHom_ext
    intro k
    simp [hψ₀, hx k]
  obtain ⟨G, hG⟩ := hker
  have hG' : Ideal.span (G : Set (MvPolynomial (Fin n) R)) = RingHom.ker π := hG
  obtain ⟨i₁, h₁, hkill⟩ := H.exists_common_eq (fun l : ↥G => ψ₀ (l : MvPolynomial (Fin n) R))
    (fun _ : ↥G => 0) (fun l => by
      have hl : (l : MvPolynomial (Fin n) R) ∈ RingHom.ker π := by
        rw [← hG']; exact Ideal.subset_span l.2
      have hc := AlgHom.congr_fun hcomm (l : MvPolynomial (Fin n) R)
      rw [AlgHom.comp_apply, AlgHom.comp_apply] at hc
      rw [map_zero, hc, RingHom.mem_ker.1 hl, map_zero])
  have hkerle : ∀ p ∈ RingHom.ker π, ((t h₁).comp ψ₀) p = 0 := by
    intro p hp
    rw [← hG'] at hp
    have hle : Ideal.span (G : Set (MvPolynomial (Fin n) R))
        ≤ RingHom.ker ((t h₁).comp ψ₀ : MvPolynomial (Fin n) R →ₐ[R] 𝒮 i₁) := by
      rw [Ideal.span_le]
      intro g hg
      rw [SetLike.mem_coe, RingHom.mem_ker]
      have hkg := hkill ⟨g, hg⟩
      rw [map_zero] at hkg
      simpa using hkg
    exact RingHom.mem_ker.1 (hle hp)
  refine ⟨i₁, (Ideal.Quotient.liftₐ (RingHom.ker π) ((t h₁).comp ψ₀) hkerle).comp
    (Ideal.quotientKerAlgEquivOfSurjective hπ).symm.toAlgHom, ?_⟩
  apply AlgHom.ext
  intro b
  obtain ⟨p, rfl⟩ := hπ b
  have hsymm : (Ideal.quotientKerAlgEquivOfSurjective hπ).symm (π p)
      = Ideal.Quotient.mk (RingHom.ker π) p := by
    rw [AlgEquiv.symm_apply_eq, Ideal.quotientKerAlgEquivOfSurjective_mk]
  simp only [AlgHom.comp_apply, AlgEquiv.coe_toAlgHom]
  rw [hsymm]
  have hlift : (Ideal.Quotient.liftₐ (RingHom.ker π) ((t h₁).comp ψ₀) hkerle)
      (Ideal.Quotient.mk (RingHom.ker π) p) = (t h₁) (ψ₀ p) :=
    Ideal.Quotient.lift_mk (RingHom.ker π) _ _
  rw [hlift, H.compat h₁ (ψ₀ p)]
  have hc := AlgHom.congr_fun hcomm p
  rw [AlgHom.comp_apply, AlgHom.comp_apply] at hc
  exact hc

/-- **[KL-5b] (concrete Stacks 00QO injectivity).** Two `R`-algebra maps from a
finite-type algebra into a stage that agree in the colimit agree at a later stage.
(Concrete twin of `RingHom.EssFiniteType.exists_comp_map_eq_of_isColimit`.) -/
theorem IsFilteredAlgColimit.exists_eq_at_stage_of_finiteType
    (H : IsFilteredAlgColimit R 𝒮 t A u) (B : Type u) [CommRing B] [Algebra R B]
    [FiniteType R B] ⦃i : ι⦄ (f g : B →ₐ[R] 𝒮 i)
    (hfg : (u i).comp f = (u i).comp g) :
    ∃ (j : ι) (h : i ≤ j), (t h).comp f = (t h).comp g := by
  classical
  obtain ⟨s, hs⟩ := (inferInstance : FiniteType R B).out
  obtain ⟨j, h, he⟩ := H.exists_common_eq (fun b : ↥s => f (b : B)) (fun b : ↥s => g (b : B))
    (fun b => AlgHom.congr_fun hfg (b : B))
  refine ⟨j, h, ?_⟩
  have hle : Algebra.adjoin R (↑s : Set B)
      ≤ AlgHom.equalizer ((t h).comp f) ((t h).comp g) :=
    Algebra.adjoin_le fun b hb => he ⟨b, hb⟩
  exact AlgHom.ext fun b => hle (hs ▸ Algebra.mem_top)


/-! ### Presented systems over a filtered base ([KL-2d]) -/

/-- Transition composition, `RingHom` form. -/
theorem IsFilteredAlgColimit.t_comp (H : IsFilteredAlgColimit R 𝒮 t A u)
    ⦃i j k : ι⦄ (hij : i ≤ j) (hjk : j ≤ k) :
    (t hjk).toRingHom.comp (t hij).toRingHom = (t (hij.trans hjk)).toRingHom :=
  RingHom.ext fun x => H.t_trans hij hjk x

/-- Cocone compatibility, `RingHom` form. -/
theorem IsFilteredAlgColimit.u_comp (H : IsFilteredAlgColimit R 𝒮 t A u)
    ⦃i j : ι⦄ (hij : i ≤ j) :
    (u j).toRingHom.comp (t hij).toRingHom = (u i).toRingHom :=
  RingHom.ext fun x => H.compat hij x

section Presented

variable {σ : Type} [Fintype σ] {κ : Type} [Fintype κ] {i₀ : ι}

/-- Coefficientwise stage-lifting: every polynomial over the colimit is the pushforward
of a stage polynomial. -/
theorem IsFilteredAlgColimit.exists_map_poly (H : IsFilteredAlgColimit R 𝒮 t A u)
    (P : MvPolynomial σ A) :
    ∃ (i : ι) (P' : MvPolynomial σ (𝒮 i)), MvPolynomial.map (u i).toRingHom P' = P := by
  classical
  obtain ⟨i, x, hx⟩ := H.exists_common_lift (fun d : ↥P.support => P.coeff d)
  refine ⟨i, ∑ d ∈ P.support.attach, MvPolynomial.monomial d.1 (x d), ?_⟩
  calc (MvPolynomial.map (u i).toRingHom)
        (∑ d ∈ P.support.attach, MvPolynomial.monomial d.1 (x d))
      = ∑ d ∈ P.support.attach, MvPolynomial.monomial d.1 (P.coeff d.1) := by
        rw [map_sum]
        exact Finset.sum_congr rfl fun d _ => by
          rw [MvPolynomial.map_monomial]; exact congrArg _ (hx d)
    _ = ∑ d ∈ P.support, MvPolynomial.monomial d (P.coeff d) :=
        Finset.sum_attach _ (fun d => MvPolynomial.monomial d (P.coeff d))
    _ = P := MvPolynomial.support_sum_monomial_coeff P

/-- Coefficientwise stage-equality: stage polynomials with equal pushforwards agree at a
later stage. -/
theorem IsFilteredAlgColimit.exists_map_poly_eq (H : IsFilteredAlgColimit R 𝒮 t A u)
    ⦃i : ι⦄ (P Q : MvPolynomial σ (𝒮 i))
    (hPQ : MvPolynomial.map (u i).toRingHom P = MvPolynomial.map (u i).toRingHom Q) :
    ∃ (j : ι) (h : i ≤ j),
      MvPolynomial.map (t h).toRingHom P = MvPolynomial.map (t h).toRingHom Q := by
  classical
  obtain ⟨j, h, he⟩ := H.exists_common_eq
    (fun d : ↥(P.support ∪ Q.support) => P.coeff d)
    (fun d : ↥(P.support ∪ Q.support) => Q.coeff d)
    (fun d => by
      have hc := congrArg (MvPolynomial.coeff d.1) hPQ
      rwa [MvPolynomial.coeff_map, MvPolynomial.coeff_map] at hc)
  refine ⟨j, h, MvPolynomial.ext _ _ fun d => ?_⟩
  rw [MvPolynomial.coeff_map, MvPolynomial.coeff_map]
  by_cases hd : d ∈ P.support ∪ Q.support
  · exact he ⟨d, hd⟩
  · rw [Finset.mem_union, not_or, MvPolynomial.mem_support_iff, not_not,
      MvPolynomial.mem_support_iff, not_not] at hd
    rw [hd.1, hd.2]

variable (t) in
/-- **[KL-2d] transitions** of a presented system: push the presentation forward along a
base transition. -/
noncomputable def presentedT (H : IsFilteredAlgColimit R 𝒮 t A u)
    (gen : κ → MvPolynomial σ (𝒮 i₀)) :
    ∀ ⦃P Q : {i : ι // i₀ ≤ i}⦄, P ≤ Q →
      ((MvPolynomial σ (𝒮 P.1) ⧸
          Ideal.span (Set.range fun j => MvPolynomial.map (t P.2).toRingHom (gen j))) →ₐ[R]
        (MvPolynomial σ (𝒮 Q.1) ⧸
          Ideal.span (Set.range fun j => MvPolynomial.map (t Q.2).toRingHom (gen j)))) :=
  fun P Q hPQ => Ideal.Quotient.liftₐ _
    ((Ideal.Quotient.mkₐ R _).comp (MvPolynomial.mapAlgHom (t hPQ)))
    (fun p hp => by
      have h1 := Ideal.mem_map_of_mem (MvPolynomial.map (t hPQ).toRingHom) hp
      rw [Ideal.map_span, ← Set.range_comp] at h1
      have h2 : (MvPolynomial.map (t hPQ).toRingHom ∘
            fun j => MvPolynomial.map (t P.2).toRingHom (gen j))
          = fun j => MvPolynomial.map (t Q.2).toRingHom (gen j) := by
        funext j
        rw [Function.comp_apply, MvPolynomial.map_map, H.t_comp]
      rw [h2] at h1
      simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk]
      have hcoe : MvPolynomial.mapAlgHom (R := R) (σ := σ) (t hPQ) p
          = MvPolynomial.map (t hPQ).toRingHom p := rfl
      rw [hcoe]
      exact Ideal.Quotient.eq_zero_iff_mem.2 h1)

variable (t u) in
/-- **[KL-2d] cocone maps** of a presented system: push the presentation to the colimit. -/
noncomputable def presentedU (H : IsFilteredAlgColimit R 𝒮 t A u)
    (gen : κ → MvPolynomial σ (𝒮 i₀)) :
    ∀ P : {i : ι // i₀ ≤ i},
      (MvPolynomial σ (𝒮 P.1) ⧸
          Ideal.span (Set.range fun j => MvPolynomial.map (t P.2).toRingHom (gen j))) →ₐ[R]
        (MvPolynomial σ A ⧸
          Ideal.span (Set.range fun j => MvPolynomial.map (u i₀).toRingHom (gen j))) :=
  fun P => Ideal.Quotient.liftₐ _
    ((Ideal.Quotient.mkₐ R _).comp (MvPolynomial.mapAlgHom (u P.1)))
    (fun p hp => by
      have h1 := Ideal.mem_map_of_mem (MvPolynomial.map (u P.1).toRingHom) hp
      rw [Ideal.map_span, ← Set.range_comp] at h1
      have h2 : (MvPolynomial.map (u P.1).toRingHom ∘
            fun j => MvPolynomial.map (t P.2).toRingHom (gen j))
          = fun j => MvPolynomial.map (u i₀).toRingHom (gen j) := by
        funext j
        rw [Function.comp_apply, MvPolynomial.map_map, H.u_comp]
      rw [h2] at h1
      simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk]
      have hcoe : MvPolynomial.mapAlgHom (R := R) (σ := σ) (u P.1) p
          = MvPolynomial.map (u P.1).toRingHom p := rfl
      rw [hcoe]
      exact Ideal.Quotient.eq_zero_iff_mem.2 h1)

theorem presentedT_mk (H : IsFilteredAlgColimit R 𝒮 t A u)
    (gen : κ → MvPolynomial σ (𝒮 i₀)) ⦃P Q : {i : ι // i₀ ≤ i}⦄ (h : P ≤ Q)
    (p : MvPolynomial σ (𝒮 P.1)) :
    presentedT t H gen h (Ideal.Quotient.mk _ p)
      = Ideal.Quotient.mk _ (MvPolynomial.map (t h).toRingHom p) :=
  Ideal.Quotient.lift_mk _ _ _

theorem presentedU_mk (H : IsFilteredAlgColimit R 𝒮 t A u)
    (gen : κ → MvPolynomial σ (𝒮 i₀)) (P : {i : ι // i₀ ≤ i})
    (p : MvPolynomial σ (𝒮 P.1)) :
    presentedU t u H gen P (Ideal.Quotient.mk _ p)
      = Ideal.Quotient.mk _ (MvPolynomial.map (u P.1).toRingHom p) :=
  Ideal.Quotient.lift_mk _ _ _

/-- **[KL-2d].** A presented system over a filtered base is itself a filtered colimit
presentation of the corresponding presented algebra over the colimit. -/
theorem isFilteredAlgColimit_presented (H : IsFilteredAlgColimit R 𝒮 t A u)
    (gen : κ → MvPolynomial σ (𝒮 i₀)) :
    IsFilteredAlgColimit R
      (fun P : {i : ι // i₀ ≤ i} => MvPolynomial σ (𝒮 P.1) ⧸
        Ideal.span (Set.range fun j => MvPolynomial.map (t P.2).toRingHom (gen j)))
      (presentedT t H gen)
      (MvPolynomial σ A ⧸
        Ideal.span (Set.range fun j => MvPolynomial.map (u i₀).toRingHom (gen j)))
      (presentedU t u H gen) := by
  classical
  haveI := H.directed
  haveI := H.nonempty
  constructor
  -- directedness of the tail
  · exact ⟨fun P Q => by
      obtain ⟨k, hPk, hQk⟩ := directed_of (· ≤ ·) P.1 Q.1
      exact ⟨⟨k, P.2.trans hPk⟩, hPk, hQk⟩⟩
  · exact ⟨⟨i₀, le_rfl⟩⟩
  -- functoriality
  · intro P Q S hPQ hQS x
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    rw [presentedT_mk, presentedT_mk, presentedT_mk, MvPolynomial.map_map, H.t_comp]
  -- compatibility
  · intro P Q h x
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    rw [presentedT_mk, presentedU_mk, presentedU_mk, MvPolynomial.map_map, H.u_comp]
  -- joint surjectivity
  · intro a
    obtain ⟨q, rfl⟩ := Ideal.Quotient.mk_surjective a
    obtain ⟨i, P', hP'⟩ := H.exists_map_poly q
    obtain ⟨k, hik, hi₀k⟩ := directed_of (· ≤ ·) i i₀
    refine ⟨⟨k, hi₀k⟩, Ideal.Quotient.mk _ (MvPolynomial.map (t hik).toRingHom P'), ?_⟩
    rw [presentedU_mk, MvPolynomial.map_map, H.u_comp, hP']
  -- equality at a later stage
  · intro P x y hxy
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    obtain ⟨q, rfl⟩ := Ideal.Quotient.mk_surjective y
    rw [presentedU_mk, presentedU_mk, Ideal.Quotient.eq, ← map_sub] at hxy
    rw [Ideal.mem_span_range_iff_exists_fun] at hxy
    obtain ⟨c, hc⟩ := hxy
    -- lift the coefficients of the span representation to a stage
    choose ci cP hcP using fun j => H.exists_map_poly (c j)
    obtain ⟨i₁, hi₁⟩ := (insert P.1 (Finset.univ.image ci)).exists_le
    have hPi₁ : P.1 ≤ i₁ := hi₁ P.1 (Finset.mem_insert_self _ _)
    -- the two sides of the span identity, transported to stage i₁
    set lhs : MvPolynomial σ (𝒮 i₁) := ∑ j, MvPolynomial.map
        (t (hi₁ (ci j) (Finset.mem_insert_of_mem
          (Finset.mem_image_of_mem ci (Finset.mem_univ j))))).toRingHom (cP j)
        * MvPolynomial.map (t (P.2.trans hPi₁)).toRingHom (gen j) with hlhs
    have hmaplhs : MvPolynomial.map (u i₁).toRingHom lhs
        = MvPolynomial.map (u P.1).toRingHom (p - q) := by
      rw [hlhs, map_sum, ← hc]
      refine Finset.sum_congr rfl fun j _ => ?_
      rw [map_mul, MvPolynomial.map_map, MvPolynomial.map_map, H.u_comp, H.u_comp, hcP]
    -- equality of polynomials at a later stage
    obtain ⟨i₂, hi₂, he⟩ := H.exists_map_poly_eq lhs
      (MvPolynomial.map (t hPi₁).toRingHom (p - q))
      (by rw [hmaplhs, MvPolynomial.map_map, H.u_comp])
    refine ⟨⟨i₂, P.2.trans (hPi₁.trans hi₂)⟩, hPi₁.trans hi₂, ?_⟩
    rw [presentedT_mk, presentedT_mk, Ideal.Quotient.eq, ← map_sub]
    rw [← H.t_comp hPi₁ hi₂, ← MvPolynomial.map_map, ← he, hlhs, map_sum]
    refine sum_mem fun j _ => ?_
    rw [map_mul, MvPolynomial.map_map, H.t_comp]
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨j, by rw [MvPolynomial.map_map, H.t_comp]⟩)

end Presented

/-- **[KL-2e].** Transport of a filtered colimit presentation along an isomorphism of the
colimit. -/
theorem IsFilteredAlgColimit.congr (H : IsFilteredAlgColimit R 𝒮 t A u)
    {A' : Type u} [CommRing A'] [Algebra R A'] (e : A ≃ₐ[R] A') :
    IsFilteredAlgColimit R 𝒮 t A' (fun i => (e : A →ₐ[R] A').comp (u i)) where
  directed := H.directed
  nonempty := H.nonempty
  t_trans := H.t_trans
  compat := by intro i j h x; simp [H.compat h x]
  jointly_surjective := by
    intro a
    obtain ⟨i, x, hx⟩ := H.jointly_surjective (e.symm a)
    exact ⟨i, x, by simp [hx]⟩
  eq_at_stage := by
    intro i x y hxy
    exact H.eq_at_stage x y (e.injective (by simpa using hxy))

end Spread

/-! ### Concatenation of presentations ([KL-5c]) -/

section Concat

variable {S : Type u} [CommRing S] {σ₁ σ₂ κ₁ κ₂ : Type}
variable (g₁ : κ₁ → MvPolynomial σ₁ S) (g₂ : κ₂ → MvPolynomial σ₂ S)

/-- The concatenated presentation: disjoint unions of variables and of relations. -/
noncomputable abbrev concatGen : κ₁ ⊕ κ₂ → MvPolynomial (σ₁ ⊕ σ₂) S :=
  Sum.elim (fun j => MvPolynomial.rename Sum.inl (g₁ j))
    (fun j => MvPolynomial.rename Sum.inr (g₂ j))

/-- Left inclusion of presented algebras into the concatenated presentation. -/
noncomputable def concatInl :
    (MvPolynomial σ₁ S ⧸ Ideal.span (Set.range g₁)) →ₐ[S]
      (MvPolynomial (σ₁ ⊕ σ₂) S ⧸ Ideal.span (Set.range (concatGen g₁ g₂))) :=
  Ideal.Quotient.liftₐ _ ((Ideal.Quotient.mkₐ S _).comp
    (MvPolynomial.rename (Sum.inl : σ₁ → σ₁ ⊕ σ₂)))
    (fun p hp => by
      have h1 := Ideal.mem_map_of_mem
        (MvPolynomial.rename (Sum.inl : σ₁ → σ₁ ⊕ σ₂) : _ →ₐ[S] _) hp
      rw [Ideal.map_span, ← Set.range_comp] at h1
      simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk]
      refine Ideal.Quotient.eq_zero_iff_mem.2 (Ideal.span_mono ?_ h1)
      rintro - ⟨j, rfl⟩
      exact ⟨Sum.inl j, rfl⟩)

/-- Right inclusion of presented algebras into the concatenated presentation. -/
noncomputable def concatInr :
    (MvPolynomial σ₂ S ⧸ Ideal.span (Set.range g₂)) →ₐ[S]
      (MvPolynomial (σ₁ ⊕ σ₂) S ⧸ Ideal.span (Set.range (concatGen g₁ g₂))) :=
  Ideal.Quotient.liftₐ _ ((Ideal.Quotient.mkₐ S _).comp
    (MvPolynomial.rename (Sum.inr : σ₂ → σ₁ ⊕ σ₂)))
    (fun p hp => by
      have h1 := Ideal.mem_map_of_mem
        (MvPolynomial.rename (Sum.inr : σ₂ → σ₁ ⊕ σ₂) : _ →ₐ[S] _) hp
      rw [Ideal.map_span, ← Set.range_comp] at h1
      simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk]
      refine Ideal.Quotient.eq_zero_iff_mem.2 (Ideal.span_mono ?_ h1)
      rintro - ⟨j, rfl⟩
      exact ⟨Sum.inr j, rfl⟩)

theorem concatInl_mk (p : MvPolynomial σ₁ S) :
    concatInl g₁ g₂ (Ideal.Quotient.mk _ p)
      = Ideal.Quotient.mk _ (MvPolynomial.rename Sum.inl p) :=
  Ideal.Quotient.lift_mk _ _ _

theorem concatInr_mk (p : MvPolynomial σ₂ S) :
    concatInr g₁ g₂ (Ideal.Quotient.mk _ p)
      = Ideal.Quotient.mk _ (MvPolynomial.rename Sum.inr p) :=
  Ideal.Quotient.lift_mk _ _ _

open TensorProduct in
/-- The concatenated presentation maps to the tensor product: variables to pure tensors. -/
noncomputable def concatToTensor :
    (MvPolynomial (σ₁ ⊕ σ₂) S ⧸ Ideal.span (Set.range (concatGen g₁ g₂))) →ₐ[S]
      ((MvPolynomial σ₁ S ⧸ Ideal.span (Set.range g₁)) ⊗[S]
        (MvPolynomial σ₂ S ⧸ Ideal.span (Set.range g₂))) :=
  Ideal.Quotient.liftₐ _ (MvPolynomial.aeval (Sum.elim
      (fun v => Ideal.Quotient.mk (Ideal.span (Set.range g₁)) (MvPolynomial.X v) ⊗ₜ[S]
        (1 : MvPolynomial σ₂ S ⧸ Ideal.span (Set.range g₂)))
      (fun w => (1 : MvPolynomial σ₁ S ⧸ Ideal.span (Set.range g₁)) ⊗ₜ[S]
        Ideal.Quotient.mk (Ideal.span (Set.range g₂)) (MvPolynomial.X w))))
    (by
      intro p hp
      refine (Ideal.span_le.2 ?_ : Ideal.span (Set.range (concatGen g₁ g₂)) ≤ RingHom.ker _) hp
      rintro - ⟨j, rfl⟩
      rw [SetLike.mem_coe, RingHom.mem_ker]
      cases j with
      | inl j =>
        have hL : (MvPolynomial.aeval (Sum.elim
              (fun v => Ideal.Quotient.mk (Ideal.span (Set.range g₁)) (MvPolynomial.X v) ⊗ₜ[S]
                (1 : MvPolynomial σ₂ S ⧸ Ideal.span (Set.range g₂)))
              (fun w => (1 : MvPolynomial σ₁ S ⧸ Ideal.span (Set.range g₁)) ⊗ₜ[S]
                Ideal.Quotient.mk (Ideal.span (Set.range g₂)) (MvPolynomial.X w))) :
                MvPolynomial (σ₁ ⊕ σ₂) S →ₐ[S] _).comp
            (MvPolynomial.rename (Sum.inl : σ₁ → σ₁ ⊕ σ₂))
            = (Algebra.TensorProduct.includeLeft :
                (MvPolynomial σ₁ S ⧸ Ideal.span (Set.range g₁)) →ₐ[S] _).comp
              (Ideal.Quotient.mkₐ S (Ideal.span (Set.range g₁))) := by
          apply MvPolynomial.algHom_ext
          intro v
          simp [MvPolynomial.aeval_rename]
        have hthis := AlgHom.congr_fun hL (g₁ j)
        simp only [AlgHom.comp_apply] at hthis
        have hj : concatGen g₁ g₂ (Sum.inl j) = MvPolynomial.rename Sum.inl (g₁ j) := rfl
        have hz : Ideal.Quotient.mk (Ideal.span (Set.range g₁)) (g₁ j) = 0 :=
          Ideal.Quotient.eq_zero_iff_mem.2 (Ideal.subset_span ⟨j, rfl⟩)
        rw [hj, hthis, Ideal.Quotient.mkₐ_eq_mk, hz, map_zero]
      | inr j =>
        have hR : (MvPolynomial.aeval (Sum.elim
              (fun v => Ideal.Quotient.mk (Ideal.span (Set.range g₁)) (MvPolynomial.X v) ⊗ₜ[S]
                (1 : MvPolynomial σ₂ S ⧸ Ideal.span (Set.range g₂)))
              (fun w => (1 : MvPolynomial σ₁ S ⧸ Ideal.span (Set.range g₁)) ⊗ₜ[S]
                Ideal.Quotient.mk (Ideal.span (Set.range g₂)) (MvPolynomial.X w))) :
                MvPolynomial (σ₁ ⊕ σ₂) S →ₐ[S] _).comp
            (MvPolynomial.rename (Sum.inr : σ₂ → σ₁ ⊕ σ₂))
            = (Algebra.TensorProduct.includeRight :
                (MvPolynomial σ₂ S ⧸ Ideal.span (Set.range g₂)) →ₐ[S] _).comp
              (Ideal.Quotient.mkₐ S (Ideal.span (Set.range g₂))) := by
          apply MvPolynomial.algHom_ext
          intro w
          simp [MvPolynomial.aeval_rename]
        have hthis := AlgHom.congr_fun hR (g₂ j)
        simp only [AlgHom.comp_apply] at hthis
        have hj : concatGen g₁ g₂ (Sum.inr j) = MvPolynomial.rename Sum.inr (g₂ j) := rfl
        have hz : Ideal.Quotient.mk (Ideal.span (Set.range g₂)) (g₂ j) = 0 :=
          Ideal.Quotient.eq_zero_iff_mem.2 (Ideal.subset_span ⟨j, rfl⟩)
        rw [hj, hthis, Ideal.Quotient.mkₐ_eq_mk, hz, map_zero])

open TensorProduct in
theorem concatToTensor_mk (h : MvPolynomial (σ₁ ⊕ σ₂) S) :
    concatToTensor g₁ g₂ (Ideal.Quotient.mk _ h)
      = MvPolynomial.aeval (Sum.elim
          (fun v => Ideal.Quotient.mk (Ideal.span (Set.range g₁)) (MvPolynomial.X v) ⊗ₜ[S]
            (1 : MvPolynomial σ₂ S ⧸ Ideal.span (Set.range g₂)))
          (fun w => (1 : MvPolynomial σ₁ S ⧸ Ideal.span (Set.range g₁)) ⊗ₜ[S]
            Ideal.Quotient.mk (Ideal.span (Set.range g₂)) (MvPolynomial.X w))) h :=
  Ideal.Quotient.lift_mk _ _ _

theorem concatToTensor_comp_concatInl :
    (concatToTensor g₁ g₂).comp (concatInl g₁ g₂) = Algebra.TensorProduct.includeLeft := by
  apply Ideal.Quotient.algHom_ext
  apply MvPolynomial.algHom_ext
  intro v
  simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk]
  rw [concatInl_mk, MvPolynomial.rename_X, concatToTensor_mk, MvPolynomial.aeval_X,
    Sum.elim_inl]
  rfl

theorem concatToTensor_comp_concatInr :
    (concatToTensor g₁ g₂).comp (concatInr g₁ g₂) = Algebra.TensorProduct.includeRight := by
  apply Ideal.Quotient.algHom_ext
  apply MvPolynomial.algHom_ext
  intro w
  simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk]
  rw [concatInr_mk, MvPolynomial.rename_X, concatToTensor_mk, MvPolynomial.aeval_X,
    Sum.elim_inr]
  rfl

open TensorProduct in
/-- **[KL-5c].** The concatenated presentation realizes the tensor product of the two
presented algebras, intertwining the inclusions with `includeLeft`/`includeRight`
(`concatToTensor_comp_concatInl/r`). -/
noncomputable def concatEquiv :
    (MvPolynomial (σ₁ ⊕ σ₂) S ⧸ Ideal.span (Set.range (concatGen g₁ g₂))) ≃ₐ[S]
      ((MvPolynomial σ₁ S ⧸ Ideal.span (Set.range g₁)) ⊗[S]
        (MvPolynomial σ₂ S ⧸ Ideal.span (Set.range g₂))) :=
  AlgEquiv.ofAlgHom (concatToTensor g₁ g₂)
    (Algebra.TensorProduct.productMap (concatInl g₁ g₂) (concatInr g₁ g₂))
    (by
      apply Algebra.TensorProduct.ext'
      intro a b
      obtain ⟨pa, rfl⟩ := Ideal.Quotient.mk_surjective a
      obtain ⟨pb, rfl⟩ := Ideal.Quotient.mk_surjective b
      have hpm : Algebra.TensorProduct.productMap (concatInl g₁ g₂) (concatInr g₁ g₂)
          (Ideal.Quotient.mk _ pa ⊗ₜ[S] Ideal.Quotient.mk _ pb)
          = concatInl g₁ g₂ (Ideal.Quotient.mk _ pa)
            * concatInr g₁ g₂ (Ideal.Quotient.mk _ pb) := rfl
      rw [AlgHom.comp_apply, AlgHom.id_apply, hpm, map_mul]
      have hA : concatToTensor g₁ g₂ (concatInl g₁ g₂ (Ideal.Quotient.mk _ pa))
          = Algebra.TensorProduct.includeLeft (R := S)
              (Ideal.Quotient.mk (Ideal.span (Set.range g₁)) pa) :=
        AlgHom.congr_fun (concatToTensor_comp_concatInl g₁ g₂)
          (Ideal.Quotient.mk (Ideal.span (Set.range g₁)) pa)
      have hB : concatToTensor g₁ g₂ (concatInr g₁ g₂ (Ideal.Quotient.mk _ pb))
          = Algebra.TensorProduct.includeRight (R := S)
              (Ideal.Quotient.mk (Ideal.span (Set.range g₂)) pb) :=
        AlgHom.congr_fun (concatToTensor_comp_concatInr g₁ g₂)
          (Ideal.Quotient.mk (Ideal.span (Set.range g₂)) pb)
      rw [hA, hB, Algebra.TensorProduct.includeLeft_apply,
        Algebra.TensorProduct.includeRight_apply, Algebra.TensorProduct.tmul_mul_tmul,
        mul_one, one_mul])
    (by
      apply Ideal.Quotient.algHom_ext
      apply MvPolynomial.algHom_ext
      intro v
      simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk, AlgHom.coe_id, id_eq]
      cases v with
      | inl v =>
        have h1 : (Ideal.Quotient.mk (Ideal.span (Set.range (concatGen g₁ g₂))))
            (MvPolynomial.X (Sum.inl v))
            = concatInl g₁ g₂ (Ideal.Quotient.mk _ (MvPolynomial.X v)) := by
          rw [concatInl_mk, MvPolynomial.rename_X]
        rw [h1]
        have h2 : concatToTensor g₁ g₂
            (concatInl g₁ g₂ (Ideal.Quotient.mk _ (MvPolynomial.X v)))
            = Algebra.TensorProduct.includeLeft (R := S)
                (Ideal.Quotient.mk (Ideal.span (Set.range g₁)) (MvPolynomial.X v)) :=
          AlgHom.congr_fun (concatToTensor_comp_concatInl g₁ g₂)
            (Ideal.Quotient.mk (Ideal.span (Set.range g₁)) (MvPolynomial.X v))
        rw [h2, Algebra.TensorProduct.includeLeft_apply]
        have h3 : Algebra.TensorProduct.productMap (concatInl g₁ g₂) (concatInr g₁ g₂)
            (Ideal.Quotient.mk (Ideal.span (Set.range g₁)) (MvPolynomial.X v) ⊗ₜ[S] 1)
            = concatInl g₁ g₂ (Ideal.Quotient.mk _ (MvPolynomial.X v))
              * concatInr g₁ g₂ 1 := rfl
        rw [h3, map_one, mul_one, concatInl_mk, MvPolynomial.rename_X]
      | inr w =>
        have h1 : (Ideal.Quotient.mk (Ideal.span (Set.range (concatGen g₁ g₂))))
            (MvPolynomial.X (Sum.inr w))
            = concatInr g₁ g₂ (Ideal.Quotient.mk _ (MvPolynomial.X w)) := by
          rw [concatInr_mk, MvPolynomial.rename_X]
        rw [h1]
        have h2 : concatToTensor g₁ g₂
            (concatInr g₁ g₂ (Ideal.Quotient.mk _ (MvPolynomial.X w)))
            = Algebra.TensorProduct.includeRight (R := S)
                (Ideal.Quotient.mk (Ideal.span (Set.range g₂)) (MvPolynomial.X w)) :=
          AlgHom.congr_fun (concatToTensor_comp_concatInr g₁ g₂)
            (Ideal.Quotient.mk (Ideal.span (Set.range g₂)) (MvPolynomial.X w))
        rw [h2, Algebra.TensorProduct.includeRight_apply]
        have h3 : Algebra.TensorProduct.productMap (concatInl g₁ g₂) (concatInr g₁ g₂)
            ((1 : MvPolynomial σ₁ S ⧸ Ideal.span (Set.range g₁)) ⊗ₜ[S]
              Ideal.Quotient.mk (Ideal.span (Set.range g₂)) (MvPolynomial.X w))
            = concatInl g₁ g₂ 1
              * concatInr g₁ g₂ (Ideal.Quotient.mk _ (MvPolynomial.X w)) := rfl
        rw [h3, map_one, one_mul, concatInr_mk, MvPolynomial.rename_X])

end Concat

/-! ### Variable-doubling maps and their naturality ([KL-5] infrastructure) -/

section Assembly

variable {R : Type u} [CommRing R] {ι : Type u} [Preorder ι]
  {𝒮 : ι → Type u} [∀ i, CommRing (𝒮 i)] [∀ i, Algebra R (𝒮 i)]
  {t : ∀ ⦃i j : ι⦄, i ≤ j → (𝒮 i →ₐ[R] 𝒮 j)}
  {A : Type u} [CommRing A] [Algebra R A] {u : ∀ i, 𝒮 i →ₐ[R] A}
  {σ κ : Type} [Fintype σ] [Fintype κ] {i₀ : ι}
  (gen : κ → MvPolynomial σ (𝒮 i₀))
  {W : Type u} [CommRing W] [Algebra R W]

/-- Left variable-doubling on a presented model over any receiving algebra. -/
noncomputable def doubleInl (w : 𝒮 i₀ →ₐ[R] W) :
    (MvPolynomial σ W ⧸ Ideal.span (Set.range fun j =>
        MvPolynomial.map w.toRingHom (gen j))) →ₐ[R]
      (MvPolynomial (σ ⊕ σ) W ⧸ Ideal.span (Set.range fun j =>
        MvPolynomial.map w.toRingHom (concatGen gen gen j))) :=
  Ideal.Quotient.liftₐ _ ((Ideal.Quotient.mkₐ R _).comp
    ((MvPolynomial.rename (Sum.inl : σ → σ ⊕ σ) : _ →ₐ[W] _).restrictScalars R))
    (fun p hp => by
      have h1 := Ideal.mem_map_of_mem
        (MvPolynomial.rename (Sum.inl : σ → σ ⊕ σ) : _ →ₐ[W] _) hp
      rw [Ideal.map_span, ← Set.range_comp] at h1
      simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk]
      refine Ideal.Quotient.eq_zero_iff_mem.2 (Ideal.span_mono ?_ h1)
      rintro - ⟨j, rfl⟩
      refine ⟨Sum.inl j, ?_⟩
      show MvPolynomial.map w.toRingHom (MvPolynomial.rename Sum.inl (gen j))
        = MvPolynomial.rename Sum.inl (MvPolynomial.map w.toRingHom (gen j))
      exact MvPolynomial.map_rename _ _ _)

/-- Right variable-doubling on a presented model over any receiving algebra. -/
noncomputable def doubleInr (w : 𝒮 i₀ →ₐ[R] W) :
    (MvPolynomial σ W ⧸ Ideal.span (Set.range fun j =>
        MvPolynomial.map w.toRingHom (gen j))) →ₐ[R]
      (MvPolynomial (σ ⊕ σ) W ⧸ Ideal.span (Set.range fun j =>
        MvPolynomial.map w.toRingHom (concatGen gen gen j))) :=
  Ideal.Quotient.liftₐ _ ((Ideal.Quotient.mkₐ R _).comp
    ((MvPolynomial.rename (Sum.inr : σ → σ ⊕ σ) : _ →ₐ[W] _).restrictScalars R))
    (fun p hp => by
      have h1 := Ideal.mem_map_of_mem
        (MvPolynomial.rename (Sum.inr : σ → σ ⊕ σ) : _ →ₐ[W] _) hp
      rw [Ideal.map_span, ← Set.range_comp] at h1
      simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk]
      refine Ideal.Quotient.eq_zero_iff_mem.2 (Ideal.span_mono ?_ h1)
      rintro - ⟨j, rfl⟩
      refine ⟨Sum.inr j, ?_⟩
      show MvPolynomial.map w.toRingHom (MvPolynomial.rename Sum.inr (gen j))
        = MvPolynomial.rename Sum.inr (MvPolynomial.map w.toRingHom (gen j))
      exact MvPolynomial.map_rename _ _ _)

theorem doubleInl_mk (w : 𝒮 i₀ →ₐ[R] W) (p : MvPolynomial σ W) :
    doubleInl gen w (Ideal.Quotient.mk _ p)
      = Ideal.Quotient.mk _ (MvPolynomial.rename Sum.inl p) :=
  Ideal.Quotient.lift_mk _ _ _

theorem doubleInr_mk (w : 𝒮 i₀ →ₐ[R] W) (p : MvPolynomial σ W) :
    doubleInr gen w (Ideal.Quotient.mk _ p)
      = Ideal.Quotient.mk _ (MvPolynomial.rename Sum.inr p) :=
  Ideal.Quotient.lift_mk _ _ _

/-- Naturality of left doubling along stage transitions. -/
theorem presentedT_comp_doubleInl (H : IsFilteredAlgColimit R 𝒮 t A u)
    ⦃P Q : {i : ι // i₀ ≤ i}⦄ (h : P ≤ Q) :
    (presentedT t H (concatGen gen gen) h).comp (doubleInl gen (t P.2))
      = (doubleInl gen (t Q.2)).comp (presentedT t H gen h) := by
  apply AlgHom.ext
  intro x
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
  rw [AlgHom.comp_apply, AlgHom.comp_apply, doubleInl_mk, presentedT_mk, presentedT_mk,
    doubleInl_mk, MvPolynomial.map_rename]

/-- Naturality of right doubling along stage transitions. -/
theorem presentedT_comp_doubleInr (H : IsFilteredAlgColimit R 𝒮 t A u)
    ⦃P Q : {i : ι // i₀ ≤ i}⦄ (h : P ≤ Q) :
    (presentedT t H (concatGen gen gen) h).comp (doubleInr gen (t P.2))
      = (doubleInr gen (t Q.2)).comp (presentedT t H gen h) := by
  apply AlgHom.ext
  intro x
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
  rw [AlgHom.comp_apply, AlgHom.comp_apply, doubleInr_mk, presentedT_mk, presentedT_mk,
    doubleInr_mk, MvPolynomial.map_rename]

/-- Naturality of left doubling along the cocone maps. -/
theorem presentedU_comp_doubleInl (H : IsFilteredAlgColimit R 𝒮 t A u)
    (P : {i : ι // i₀ ≤ i}) :
    (presentedU t u H (concatGen gen gen) P).comp (doubleInl gen (t P.2))
      = (doubleInl gen (u i₀)).comp (presentedU t u H gen P) := by
  apply AlgHom.ext
  intro x
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
  rw [AlgHom.comp_apply, AlgHom.comp_apply, doubleInl_mk, presentedU_mk, presentedU_mk,
    doubleInl_mk, MvPolynomial.map_rename]

/-- Naturality of right doubling along the cocone maps. -/
theorem presentedU_comp_doubleInr (H : IsFilteredAlgColimit R 𝒮 t A u)
    (P : {i : ι // i₀ ≤ i}) :
    (presentedU t u H (concatGen gen gen) P).comp (doubleInr gen (t P.2))
      = (doubleInr gen (u i₀)).comp (presentedU t u H gen P) := by
  apply AlgHom.ext
  intro x
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
  rw [AlgHom.comp_apply, AlgHom.comp_apply, doubleInr_mk, presentedU_mk, presentedU_mk,
    doubleInr_mk, MvPolynomial.map_rename]

end Assembly



/-! ### The target statements -/

/-- **[02KL-CORE], algebra form (Stacks 02KK = Descent 35.14.1).** If `B` is a faithfully
flat, finitely presented `A`-algebra and `B` is finitely presented over `R`, then `A` is
finitely presented over `R`.

Assembly ([KL-5], prose §4 of the decomposition): run the canonical presentation system
of `A` ([KL-1]); spread `B` to stage models ([KL-2]) that are faithfully flat over their
bases at a large stage ([KL-3]+[KL-4]); factor `id_B` through a stage `β` and fix the two
`p, q`-squares at a later common stage ([KL-5a]+[KL-5b] on `B` and `C = B ⊗[A] B` — both
FP over `R`); then `β ∘ χ : A → B_i` equalizes `p_i, q_i` on the nose (transport of
`χ(a) ⊗ 1 = 1 ⊗ χ(a)`), so it lands in `range (𝒮 i → B_i)` by the Amitsur equalizer at
base `𝒮 i` (project `Module.FaithfullyFlat.mem_range_algebraMap_iff_tmul_eq`), yielding a
section of `u i : 𝒮 i → A`; conclude by [KL-0]. -/
theorem FinitePresentation.of_comp_of_faithfullyFlat
    (R A B : Type u) [CommRing R] [CommRing A] [CommRing B]
    [Algebra R A] [Algebra A B] [Algebra R B] [IsScalarTower R A B]
    [Module.FaithfullyFlat A B] [FinitePresentation A B] [FinitePresentation R B] :
    FinitePresentation R A := by
  sorry

end Algebra

/-- **[02KL-CORE], `RingHom` form** — matches the registered gate
`RingHom.FinitePresentation.of_comp_of_faithfullyFlat` (`ForMathlib/SmoothDescent.lean`;
primed name to avoid the clash until the gate is flipped, board-coordinated). -/
theorem RingHom.FinitePresentation.of_comp_of_faithfullyFlat'
    {R S T : Type u} [CommRing R] [CommRing S] [CommRing T]
    {φ : R →+* S} {χ : S →+* T} (hff : χ.FaithfullyFlat) (hfp : χ.FinitePresentation)
    (h : (χ.comp φ).FinitePresentation) : φ.FinitePresentation := by
  algebraize [φ, χ, χ.comp φ]
  haveI : Module.FaithfullyFlat S T := hff
  haveI : Algebra.FinitePresentation S T := hfp
  haveI : Algebra.FinitePresentation R T := h
  exact Algebra.FinitePresentation.of_comp_of_faithfullyFlat R S T
