import Mathlib.RingTheory.FinitePresentation
import Mathlib.RingTheory.Flat.FaithfullyFlat.Algebra
import Mathlib.RingTheory.RingHom.FaithfullyFlat
import Mathlib.RingTheory.TensorProduct.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.Tactic.Algebraize
import ModularCurves.ForMathlib.FaithfullyFlatEqualizer

/-!
# [02KL-CORE]: finite presentation reflects along a faithfully flat, finitely presented composite

Campaign file for the sorried gate `RingHom.FinitePresentation.of_comp_of_faithfullyFlat`
(`ForMathlib/SmoothDescent.lean`, Stacks **02KK** = Descent, Lemma 35.14.1):

> Let `R → A → B` be ring maps. Assume `R → B` is of finite presentation and `A → B`
> faithfully flat and of finite presentation. Then `R → A` is of finite presentation.

Decomposition of record: `.mathlib-quality/decomposition-02kl-core.md` (board v10.99a).
Architecture ("ENDING-1", concrete filtered systems, no category-theory transport):

* `Algebra.IsFilteredAlgColimit` — the three-field concrete colimit predicate;
* **[KL-0]** `Algebra.FinitePresentation.of_retract` — retracts of FP algebras are FP
  (the `(3) ⟹ (1)` endgame of Stacks 00QO);
* **[KL-1]** `Algebra.PresentationSystem` — the canonical presentation system of an
  algebra: FP stages `R[x_s]/J` indexed by finite variable sets and FG relation
  sub-ideals, with colimit `A` (Stacks 10.127.2);
* **[KL-2]** `exists_spreadData` — an FP algebra over the colimit descends to a stage
  presentation, with stage models and colimit recovery (flatless half of Stacks 02JO(2));
* **[KL-3]** `SpreadData.exists_flat_stage` — **flat at a large stage** (Stacks
  02JO(1)+(3); the boss: ℤ-model reduction + noetherian local criterion + flat-locus
  openness + quasicompact glue);
* **[KL-4]** `SpreadData.exists_faithfullyFlat_stage` — faithfully flat at a large stage
  (patch topology: Chevalley image, stage-image patch-closedness, fibre contraction);
* **[KL-5]** stage-factoring/agreement for FP/FT sources + the tensor-of-systems colimit
  + the Amitsur endgame (project `Module.FaithfullyFlat.mem_range_algebraMap_iff_tmul_eq`),
  assembling `Algebra.FinitePresentation.of_comp_of_faithfullyFlat` and the `RingHom`
  wrapper `RingHom.FinitePresentation.of_comp_of_faithfullyFlat'` (primed to avoid a name
  clash with the registered gate; the gate flips to this on completion, board-coordinated).
-/

universe u

open TensorProduct

namespace Algebra

/-! ## The concrete filtered-colimit predicate -/

/-- `A` is exhibited as the filtered colimit of the directed system `𝒮` of `R`-algebras
along transition maps `t` and cocone maps `u`: transitions are functorial and compatible,
every element of `A` comes from a stage, and two stage elements agreeing in `A` agree at a
later stage. This is the concrete (choice-free interface) form of "filtered colimit of
rings"; it deliberately avoids `CategoryTheory.IsColimit` transport. -/
structure IsFilteredAlgColimit (R : Type u) [CommRing R] {ι : Type u} [Preorder ι]
    (𝒮 : ι → Type u) [∀ i, CommRing (𝒮 i)] [∀ i, Algebra R (𝒮 i)]
    (t : ∀ ⦃i j : ι⦄, i ≤ j → (𝒮 i →ₐ[R] 𝒮 j))
    (A : Type u) [CommRing A] [Algebra R A]
    (u : ∀ i, 𝒮 i →ₐ[R] A) : Prop where
  directed : IsDirected ι (· ≤ ·)
  nonempty : Nonempty ι
  t_trans : ∀ ⦃i j k : ι⦄ (hij : i ≤ j) (hjk : j ≤ k) (x : 𝒮 i),
    t hjk (t hij x) = t (hij.trans hjk) x
  compat : ∀ ⦃i j : ι⦄ (h : i ≤ j) (x : 𝒮 i), u j (t h x) = u i x
  jointly_surjective : ∀ a : A, ∃ (i : ι) (x : 𝒮 i), u i x = a
  eq_at_stage : ∀ ⦃i : ι⦄ (x y : 𝒮 i), u i x = u i y → ∃ (j : ι) (h : i ≤ j), t h x = t h y

/-! ## [KL-0] Retracts of finitely presented algebras are finitely presented -/

/-- **[KL-0] (inside Stacks 00QO, (3) ⟹ (1)).** A retract of a finitely presented
`R`-algebra is finitely presented: if `ρ ∘ σ = id` with `B` FP, then `A` is FP.

Proof sketch: `ρ` is surjective, and `ker ρ` is generated by the finitely many elements
`bⱼ - σ(ρ(bⱼ))` for `bⱼ` algebra generators of `B` (mod that ideal, `q ∘ (σ ∘ ρ)` and `q`
are `R`-algebra maps agreeing on generators, hence equal; so `ρ b = 0` forces
`q b = q (σ (ρ b)) = 0`). Conclude by `FinitePresentation.quotient` and transport along
`Ideal.quotientKerAlgEquivOfSurjective`. -/
theorem FinitePresentation.of_retract {R A B : Type u} [CommRing R] [CommRing A] [CommRing B]
    [Algebra R A] [Algebra R B] [FinitePresentation R B]
    (σ : A →ₐ[R] B) (ρ : B →ₐ[R] A) (hρσ : ρ.comp σ = AlgHom.id R A) :
    FinitePresentation R A := by
  sorry

/-! ## [KL-1] The canonical presentation system of an algebra -/

namespace PresentationSystem

variable (R A : Type u) [CommRing R] [CommRing A] [Algebra R A]

/-- **[KL-1] index.** A stage of the canonical presentation system of the `R`-algebra `A`:
a finite set `vars` of elements of `A` and a finitely generated ideal of relations among
them that genuinely hold in `A` (i.e. is contained in the kernel of evaluation). -/
structure Index : Type u where
  vars : Finset A
  rels : Ideal (MvPolynomial {a // a ∈ vars} R)
  rels_fg : rels.FG
  rels_le : rels ≤ RingHom.ker
    (MvPolynomial.aeval (Subtype.val : {a // a ∈ vars} → A) :
      MvPolynomial {a // a ∈ vars} R →ₐ[R] A)

variable {R A}

/-- The inclusion of variable subtypes along a containment of variable sets. -/
def Index.incl {P Q : Index R A} (h : P.vars ⊆ Q.vars) :
    {a // a ∈ P.vars} → {a // a ∈ Q.vars} :=
  fun x => ⟨x.1, h x.2⟩

instance : Preorder (Index R A) where
  le P Q := ∃ h : P.vars ⊆ Q.vars,
    P.rels.map (MvPolynomial.rename (Index.incl h) : _ →ₐ[R] _).toRingHom ≤ Q.rels
  le_refl P := by
    refine ⟨subset_rfl, ?_⟩
    sorry
  le_trans P Q S hPQ hQS := by
    sorry

variable (R A)

/-- **[KL-1] stages.** The stage algebra at an index: the free algebra on the variables
modulo the recorded relations. Finitely presented over `R` by construction
(`stage_finitePresentation`). -/
def stage (P : Index R A) : Type u :=
  MvPolynomial {a // a ∈ P.vars} R ⧸ P.rels

noncomputable instance (P : Index R A) : CommRing (stage R A P) :=
  inferInstanceAs (CommRing (MvPolynomial _ R ⧸ P.rels))

noncomputable instance (P : Index R A) : Algebra R (stage R A P) :=
  inferInstanceAs (Algebra R (MvPolynomial _ R ⧸ P.rels))

/-- **[KL-1] transitions**: rename along the variable inclusion, descended to quotients.
(The inclusion function is proof-irrelevant, so functoriality is honest.) -/
noncomputable def transition ⦃P Q : Index R A⦄ (h : P ≤ Q) :
    stage R A P →ₐ[R] stage R A Q :=
  Ideal.quotientMapₐ Q.rels (MvPolynomial.rename (Index.incl h.choose))
    (by sorry)

/-- **[KL-1] cocone**: evaluation of variables in `A`, descended to the stage. -/
noncomputable def colimMap (P : Index R A) : stage R A P →ₐ[R] A :=
  Ideal.Quotient.liftₐ P.rels (MvPolynomial.aeval (Subtype.val : {a // a ∈ P.vars} → A))
    (fun _ ha => (RingHom.mem_ker).1 (P.rels_le ha))

/-- **[KL-1a].** Every stage of the canonical presentation system is finitely presented
over `R` (`MvPolynomial` on a finite type, quotient by an FG ideal). -/
theorem stage_finitePresentation (P : Index R A) :
    FinitePresentation R (stage R A P) := by
  sorry

/-- **[KL-1b] (Stacks 10.127.2).** The canonical presentation system is a filtered
colimit presentation of `A`: directed (union of variables, sum of transported relations),
jointly surjective (`a` is hit by the stage `({a}, ⊥)`), with equality at a later stage
(a vanishing lift of a difference is itself a relation — enlarge the relation ideal by it). -/
theorem isFilteredAlgColimit :
    IsFilteredAlgColimit R (stage R A) (transition R A) A (colimMap R A) := by
  sorry

end PresentationSystem

/-! ## [KL-2] Spreading out a finitely presented algebra over a filtered system -/

section Spread

variable {R : Type u} [CommRing R] {ι : Type u} [Preorder ι]
  {𝒮 : ι → Type u} [∀ i, CommRing (𝒮 i)] [∀ i, Algebra R (𝒮 i)]
  {t : ∀ ⦃i j : ι⦄, i ≤ j → (𝒮 i →ₐ[R] 𝒮 j)}
  {A : Type u} [CommRing A] [Algebra R A] {u : ∀ i, 𝒮 i →ₐ[R] A}

variable (𝒮 t u) in
/-- **[KL-2] spread data.** A presentation of the `A`-algebra `B` descended to the stage
`i₀` of a filtered system with colimit `A`: `m` variables, `k` relation polynomials `g`
with coefficients in `𝒮 i₀`, whose pushforward to `A` presents `B`. The stage models are
`spreadStage` below. -/
structure SpreadData (B : Type u) [CommRing B] [Algebra A B] where
  i₀ : ι
  m : ℕ
  k : ℕ
  g : Fin k → MvPolynomial (Fin m) (𝒮 i₀)
  equiv : Nonempty
    ((MvPolynomial (Fin m) A ⧸
      Ideal.span (Set.range fun j => MvPolynomial.map ((u i₀).toRingHom) (g j))) ≃ₐ[A] B)

variable (B : Type u) [CommRing B] [Algebra A B]

/-- **[KL-2] (flatless half of Stacks 02JO(2)).** A finitely presented algebra over the
colimit of a filtered system descends to spread data at some stage: choose a presentation
`B ≅ A[y]/(ḡ)`, lift the finitely many coefficients of the `ḡ` jointly to a common stage
(joint surjectivity + directedness), and correct the finitely many coefficient equalities
at a later stage (`eq_at_stage`). -/
theorem exists_spreadData (H : IsFilteredAlgColimit R 𝒮 t A u)
    [FinitePresentation A B] : Nonempty (SpreadData 𝒮 u B) := by
  sorry

variable {B}

/-- **[KL-2] stage models**: the descended presentation instantiated at any later stage. -/
def SpreadData.spreadStage (D : SpreadData 𝒮 u B) ⦃i : ι⦄ (h : D.i₀ ≤ i) : Type u :=
  MvPolynomial (Fin D.m) (𝒮 i) ⧸
    Ideal.span (Set.range fun j => MvPolynomial.map (t h).toRingHom (D.g j))

noncomputable instance (D : SpreadData 𝒮 u B) ⦃i : ι⦄ (h : D.i₀ ≤ i) :
    CommRing (D.spreadStage (t := t) h) :=
  inferInstanceAs (CommRing (MvPolynomial _ _ ⧸ _))

noncomputable instance (D : SpreadData 𝒮 u B) ⦃i : ι⦄ (h : D.i₀ ≤ i) :
    Algebra (𝒮 i) (D.spreadStage (t := t) h) :=
  inferInstanceAs (Algebra (𝒮 i) (MvPolynomial _ _ ⧸ _))

/-- **[KL-2a].** Each stage model is finitely presented over its stage base. -/
theorem SpreadData.spreadStage_finitePresentation (D : SpreadData 𝒮 u B)
    ⦃i : ι⦄ (h : D.i₀ ≤ i) :
    FinitePresentation (𝒮 i) (D.spreadStage (t := t) h) := by
  sorry

/-- **[KL-2b].** Base change of a stage model along a later transition is the later stage
model: `𝒮 j ⊗[𝒮 i] spreadStage i ≃ spreadStage j` (as `𝒮 j`-algebras). -/
theorem SpreadData.spreadStage_baseChange (D : SpreadData 𝒮 u B)
    ⦃i j : ι⦄ (hij : i ≤ j) (h : D.i₀ ≤ i) (H : IsFilteredAlgColimit R 𝒮 t A u) :
    letI : Algebra (𝒮 i) (𝒮 j) := (t hij).toRingHom.toAlgebra
    Nonempty ((𝒮 j ⊗[𝒮 i] D.spreadStage (t := t) h) ≃ₐ[𝒮 j]
      D.spreadStage (t := t) (h.trans hij)) := by
  sorry

/-- **[KL-2c].** Base change of a stage model to the colimit recovers `B`:
`A ⊗[𝒮 i] spreadStage i ≃ B` (as `A`-algebras). -/
theorem SpreadData.baseChange_colim (D : SpreadData 𝒮 u B)
    ⦃i : ι⦄ (h : D.i₀ ≤ i) (H : IsFilteredAlgColimit R 𝒮 t A u) :
    letI : Algebra (𝒮 i) A := (u i).toRingHom.toAlgebra
    Nonempty ((A ⊗[𝒮 i] D.spreadStage (t := t) h) ≃ₐ[A] B) := by
  sorry

/-! ## [KL-3] Flatness at a large stage — THE BOSS (Stacks 02JO(1)+(3)) -/

/-- **[KL-3] (Stacks 02JO = Algebra 10.168.1, scoped).** If the colimit algebra `B` is
flat over `A`, then some later stage model is flat over its stage base. Internals (own
sub-decomposition on reach; tickets [KL-3a–d]): reduce to a finite-type-ℤ (noetherian)
model under `𝒮 i₀` by re-instantiating [KL-1]+[KL-2] over `ℤ`; per-prime flatness at a
large stage by the noetherian local criterion; openness of the flat(=free) locus at
noetherian stages; quasicompact glue; transport back along stage factoring. -/
theorem SpreadData.exists_flat_stage (D : SpreadData 𝒮 u B)
    (H : IsFilteredAlgColimit R 𝒮 t A u) [Algebra R B] [IsScalarTower R A B]
    [Module.Flat A B] :
    ∃ (i : ι) (h : D.i₀ ≤ i), Module.Flat (𝒮 i) (D.spreadStage (t := t) h) := by
  sorry

/-! ## [KL-4] Faithful flatness at a large stage (the 01UA leg) -/

/-- **[KL-4].** If moreover `B` is faithfully flat over `A`, some later stage model is
faithfully flat over its stage base. Route: fibre nonvanishing at stage `i` depends only
on the contraction of the prime to `𝒮 i₁` (base-change collapse of the fibre); the target
locus `W = range (comap (𝒮 i₁ → spreadStage i₁))` is constructible (Chevalley;
`PrimeSpectrum.isConstructible_range_comap`) hence patch-open; the stage images
`range (comap (𝒮 i₁ → 𝒮 i))` are patch-closed; their directed intersection lies in `W`
by the 1 ≠ 0-at-a-stage fibre argument and faithful flatness at the colimit; patch
compactness (`compactSpace_withConstructibleTopology`) gives one stage with image ⊆ `W`,
which is Spec-surjectivity there; flat + Spec-surjective = faithfully flat. -/
theorem SpreadData.exists_faithfullyFlat_stage (D : SpreadData 𝒮 u B)
    (H : IsFilteredAlgColimit R 𝒮 t A u) [Algebra R B] [IsScalarTower R A B]
    [Module.FaithfullyFlat A B] :
    ∃ (i : ι) (h : D.i₀ ≤ i), Module.FaithfullyFlat (𝒮 i) (D.spreadStage (t := t) h) := by
  sorry

/-! ## [KL-5] Stage factoring, stage agreement, and the assembly -/

variable (𝒮 t u) in
/-- **[KL-5a] (concrete Stacks 00QO, (1) ⟹ (2) surjectivity).** An `R`-algebra map from a
finitely presented algebra into the colimit of a filtered system factors through a stage.
(Concrete twin of `RingHom.EssFiniteType.exists_eq_comp_ι_app_of_isColimit`.) -/
theorem IsFilteredAlgColimit.exists_factor_of_finitePresentation
    (H : IsFilteredAlgColimit R 𝒮 t A u) (B : Type u) [CommRing B] [Algebra R B]
    [FinitePresentation R B] (f : B →ₐ[R] A) :
    ∃ (i : ι) (f' : B →ₐ[R] 𝒮 i), (u i).comp f' = f := by
  sorry

variable (𝒮 t u) in
/-- **[KL-5b] (concrete Stacks 00QO injectivity).** Two `R`-algebra maps from a
finite-type algebra into a stage that agree in the colimit agree at a later stage.
(Concrete twin of `RingHom.EssFiniteType.exists_comp_map_eq_of_isColimit`.) -/
theorem IsFilteredAlgColimit.exists_eq_at_stage_of_finiteType
    (H : IsFilteredAlgColimit R 𝒮 t A u) (B : Type u) [CommRing B] [Algebra R B]
    [FiniteType R B] ⦃i : ι⦄ (f g : B →ₐ[R] 𝒮 i)
    (hfg : (u i).comp f = (u i).comp g) :
    ∃ (j : ι) (h : i ≤ j), (t h).comp f = (t h).comp g := by
  sorry

end Spread

/-! ### The target statements -/

/-- **[02KL-CORE], algebra form (Stacks 02KK = Descent 35.14.1).** If `B` is a faithfully
flat, finitely presented `A`-algebra and `B` is finitely presented over `R`, then `A` is
finitely presented over `R`.

Assembly ([KL-5], prose §4 of the decomposition): run the canonical presentation system
of `A` ([KL-1]); spread `B` to stage models ([KL-2]) that are faithfully flat over their
bases at a large stage ([KL-3]+[KL-4]); factor `id_B` through a stage `β` and fix the two
`p, q`-squares at a later common stage ([KL-5a]+[KL-5b] on `B` and `C = B ⊗[A] B` — both
FP over `R`); then `β ∘ χ : A → B_i` equalizes `p_i, q_i` on the nose (transport of
`χ(a) ⊗ 1 = 1 ⊗ χ(a)`), so it lands in `range (𝒮 i → B_i)` by the Amitsur equalizer at
base `𝒮 i` (project `Module.FaithfullyFlat.mem_range_algebraMap_iff_tmul_eq`), yielding a
section of `u i : 𝒮 i → A`; conclude by [KL-0]. -/
theorem FinitePresentation.of_comp_of_faithfullyFlat
    (R A B : Type u) [CommRing R] [CommRing A] [CommRing B]
    [Algebra R A] [Algebra A B] [Algebra R B] [IsScalarTower R A B]
    [Module.FaithfullyFlat A B] [FinitePresentation A B] [FinitePresentation R B] :
    FinitePresentation R A := by
  sorry

end Algebra

/-- **[02KL-CORE], `RingHom` form** — matches the registered gate
`RingHom.FinitePresentation.of_comp_of_faithfullyFlat` (`ForMathlib/SmoothDescent.lean`;
primed name to avoid the clash until the gate is flipped, board-coordinated). -/
theorem RingHom.FinitePresentation.of_comp_of_faithfullyFlat'
    {R S T : Type u} [CommRing R] [CommRing S] [CommRing T]
    {φ : R →+* S} {χ : S →+* T} (hff : χ.FaithfullyFlat) (hfp : χ.FinitePresentation)
    (h : (χ.comp φ).FinitePresentation) : φ.FinitePresentation := by
  algebraize [φ, χ, χ.comp φ]
  haveI : Module.FaithfullyFlat S T := hff
  haveI : Algebra.FinitePresentation S T := hfp
  haveI : Algebra.FinitePresentation R T := h
  exact Algebra.FinitePresentation.of_comp_of_faithfullyFlat R S T
