/-
Copyright (c) 2026 The AINTLIB contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: AINTLIB ModularCurves project

ForMathlib (OURS, not vendored): upstream candidate.
-/
import Mathlib.LinearAlgebra.Matrix.Rank
import Mathlib.RingTheory.Ideal.BigOperators

/-!
# Ideal of minors of a map of finite free modules (Stacks 00N1 / 07ZA) — [T-FIT]

The ideal `I_r(φ)` generated by all `r × r` minors of `φ : Sᵃ → Sᵇ` in the standard bases.  ABSENT
from mathlib (only `Matrix` cofactor/adjugate minors as scalars exist).  This is the prerequisite
object for the Buchsbaum–Eisenbud acyclicity criterion (`ForMathlib.BuchsbaumEisenbud`) and for the
openness of the fibre-exact locus (Stacks 00RB).

## Main definitions / results

* `Matrix.idealOfMinors r M` — the ideal generated by the `r × r` minors of a matrix `M` (the
  basis-free core).  A minor with a repeated row or column is `0`, so quantifying over *all*
  functions `Fin r → …` (not just embeddings) yields the same ideal and makes every proof local.
* `LinearMap.idealOfMinors r φ` — the ideal of `r × r` minors of `φ` in the standard bases (the
  ticket target: `Matrix.idealOfMinors` of `LinearMap.toMatrix (Pi.basisFun …)`).
* `LinearMap.idealOfMinors_antitone` — `I_{r+1}(φ) ⊆ I_r(φ)` (Laplace expansion).
* `Matrix.idealOfMinors_map` — **base change**: minors commute with a ring hom `f : S →+* S'`,
  `(idealOfMinors r M).map f = idealOfMinors r (M.map f)`.  Usable verbatim for a localisation
  `S → Localization T` and for a fibre `S → S/𝔭 → κ(𝔭)`.
* `Matrix.idealOfMinors_eq_bot_iff` — `I_r(M) = ⊥ ↔` every `r × r` minor vanishes.
* `Matrix.idealOfMinors_eq_bot_iff_rank_lt` — **McCoy over a field**: `I_r(M) = ⊥ ↔ M.rank < r`.
* `Matrix.idealOfMinors_le_ker_iff_rank_lt` — the McCoy-rank **locus bridge**: for `f : S →+* K`
  to a field, `I_r(M) ≤ ker f ↔ (M.map f).rank < r`.  Specialising `f` to the residue map
  `S → κ(𝔮)` (kernel `𝔮`) gives `I_r(M) ⊆ 𝔮 ↔ rank_{κ(𝔮)}(M ⊗ κ(𝔮)) < r`, the connection 00RB
  needs to `PrimeSpectrum.zeroLocus`.

The single hard direction of McCoy (`r ≤ M.rank ⟹ some r × r minor ≠ 0`) is isolated as
`Matrix.exists_det_submatrix_ne_zero_of_le_rank` — see its docstring for the exact gap.
-/

open TensorProduct

noncomputable section

namespace Matrix

variable {S S' : Type*} [CommRing S] [CommRing S'] {a b : ℕ}

/-- Ideal of `r × r` minors of a matrix `M` (Stacks 00N1 `I_r`, Fitting-type): the ideal generated
by the determinants of all `r × r` submatrices of `M`.  We quantify over *all* index functions
`Fin r → Fin b`, `Fin r → Fin a`; a repeated row or column makes the minor `0 ∈ I`, so this is the
same ideal as the one generated by minors indexed by embeddings, and it keeps every proof local. -/
def idealOfMinors (r : ℕ) (M : Matrix (Fin b) (Fin a) S) : Ideal S :=
  Ideal.span { d | ∃ (ri : Fin r → Fin b) (ci : Fin r → Fin a), d = (M.submatrix ri ci).det }

/-- Each `r × r` minor of `M` lies in `idealOfMinors r M`. -/
theorem det_submatrix_mem_idealOfMinors (r : ℕ) (M : Matrix (Fin b) (Fin a) S)
    (ri : Fin r → Fin b) (ci : Fin r → Fin a) :
    (M.submatrix ri ci).det ∈ idealOfMinors r M :=
  Ideal.subset_span ⟨ri, ci, rfl⟩

/-- To bound `idealOfMinors r M` above by an ideal `I` it suffices that every `r × r` minor lies in
`I`. -/
theorem idealOfMinors_le {r : ℕ} {M : Matrix (Fin b) (Fin a) S} {I : Ideal S}
    (h : ∀ (ri : Fin r → Fin b) (ci : Fin r → Fin a), (M.submatrix ri ci).det ∈ I) :
    idealOfMinors r M ≤ I := by
  refine Ideal.span_le.mpr ?_
  rintro x ⟨ri, ci, rfl⟩
  exact h ri ci

/-- The `0`-th minor ideal is the unit ideal (the empty minor is `1`). -/
@[simp]
theorem idealOfMinors_zero (M : Matrix (Fin b) (Fin a) S) : idealOfMinors 0 M = ⊤ := by
  rw [Ideal.eq_top_iff_one]
  have h := det_submatrix_mem_idealOfMinors 0 M Fin.elim0 Fin.elim0
  rwa [det_isEmpty] at h

/-- **[T-FIT.antitone]** Larger minors generate a smaller ideal: `I_{r+1}(M) ⊆ I_r(M)`.  Proof:
Laplace-expand each `(r+1) × (r+1)` minor along its first row; every cofactor is an `r × r` minor
(`submatrix_submatrix`), so the whole determinant is an `S`-combination of `r × r` minors. -/
theorem idealOfMinors_succ_le (r : ℕ) (M : Matrix (Fin b) (Fin a) S) :
    idealOfMinors (r + 1) M ≤ idealOfMinors r M := by
  refine idealOfMinors_le fun ri ci => ?_
  rw [det_succ_row (M.submatrix ri ci) 0]
  refine Ideal.sum_mem _ fun j _ => ?_
  refine Ideal.mul_mem_left _ _ ?_
  rw [submatrix_submatrix]
  exact det_submatrix_mem_idealOfMinors r M _ _

/-- Minor ideals are antitone in the size: `I_s(M) ⊆ I_r(M)` whenever `r ≤ s`. -/
theorem idealOfMinors_antitone (M : Matrix (Fin b) (Fin a) S) :
    Antitone fun r => idealOfMinors r M := by
  refine antitone_nat_of_succ_le fun r => idealOfMinors_succ_le r M

/-- A single `r × r` minor commutes with a ring hom `f : S →+* S'`. -/
theorem map_det_submatrix (f : S →+* S') {r : ℕ} (M : Matrix (Fin b) (Fin a) S)
    (ri : Fin r → Fin b) (ci : Fin r → Fin a) :
    f ((M.submatrix ri ci).det) = ((M.map f).submatrix ri ci).det := by
  rw [RingHom.map_det, submatrix_map, RingHom.mapMatrix_apply]

/-- **Base change / ring-hom compatibility.**  The formation of the ideal of minors commutes with a
ring hom `f : S →+* S'`: `(idealOfMinors r M).map f = idealOfMinors r (M.map f)`.  Determinants
commute with `f` (`RingHom.map_det`) and `f` commutes with `submatrix` (`submatrix_map`), so the
image of the generating set is exactly the generating set of the base-changed matrix.

This is the clean form used downstream for a localisation `f = algebraMap S (Localization T)` and
for a fibre `f = S → κ(𝔭)` (Stacks 00RB). -/
theorem idealOfMinors_map (f : S →+* S') (r : ℕ) (M : Matrix (Fin b) (Fin a) S) :
    (idealOfMinors r M).map f = idealOfMinors r (M.map f) := by
  rw [idealOfMinors, idealOfMinors, Ideal.map_span]
  refine congrArg Ideal.span ?_
  ext d
  simp only [Set.mem_image, Set.mem_setOf_eq]
  constructor
  · rintro ⟨_, ⟨ri, ci, rfl⟩, rfl⟩
    exact ⟨ri, ci, map_det_submatrix f M ri ci⟩
  · rintro ⟨ri, ci, rfl⟩
    exact ⟨_, ⟨ri, ci, rfl⟩, map_det_submatrix f M ri ci⟩

/-- `idealOfMinors r M` is trivial iff every `r × r` minor of `M` vanishes. -/
theorem idealOfMinors_eq_bot_iff (r : ℕ) (M : Matrix (Fin b) (Fin a) S) :
    idealOfMinors r M = ⊥ ↔
      ∀ (ri : Fin r → Fin b) (ci : Fin r → Fin a), (M.submatrix ri ci).det = 0 := by
  rw [idealOfMinors, Ideal.span_eq_bot]
  constructor
  · exact fun h ri ci => h _ ⟨ri, ci, rfl⟩
  · rintro h x ⟨ri, ci, rfl⟩
    exact h ri ci

section Field

variable {K : Type*} [Field K]

/-- **McCoy, easy direction** (over a field): a nonzero `r × r` minor forces `r ≤ M.rank`.  The
`r × r` submatrix has a unit determinant, hence rank `r` (`rank_of_isUnit`), and taking a submatrix
cannot increase the rank (`rank_submatrix_le`). -/
theorem le_rank_of_det_submatrix_ne_zero {r : ℕ} (M : Matrix (Fin b) (Fin a) K)
    (ri : Fin r → Fin b) (ci : Fin r → Fin a) (h : (M.submatrix ri ci).det ≠ 0) :
    r ≤ M.rank := by
  have hunit : IsUnit (M.submatrix ri ci) :=
    (isUnit_iff_isUnit_det _).mpr (isUnit_iff_ne_zero.mpr h)
  have hrank : (M.submatrix ri ci).rank = r := by
    rw [rank_of_isUnit _ hunit, Fintype.card_fin]
  calc r = (M.submatrix ri ci).rank := hrank.symm
    _ ≤ M.rank := rank_submatrix_le M ri ci

/-- From a finite family `v` over a field whose span has `finrank ≥ r`, one can select `r` of the
`v i` — an injective reindexing `g : Fin r → Fin p` — on which `v` is linearly independent.  Take a
maximal linearly independent subfamily (`exists_linearIndependent'`, of cardinality `= finrank`),
then embed `Fin r` into its index set. -/
theorem exists_injective_comp_linearIndependent {V : Type*} [AddCommGroup V] [Module K V]
    {p : ℕ} (v : Fin p → V) {r : ℕ}
    (hr : r ≤ Module.finrank K (Submodule.span K (Set.range v))) :
    ∃ g : Fin r → Fin p, Function.Injective g ∧ LinearIndependent K (v ∘ g) := by
  obtain ⟨κ, α, hα_inj, hα_span, hα_li⟩ := exists_linearIndependent' (K := K) v
  have hκ : Fintype κ := Fintype.ofInjective α hα_inj
  have hcard : Module.finrank K (Submodule.span K (Set.range v)) = Fintype.card κ := by
    rw [← hα_span, finrank_span_eq_card hα_li]
  obtain ⟨g⟩ : Nonempty (Fin r ↪ κ) :=
    Function.Embedding.nonempty_of_card_le (by rw [Fintype.card_fin]; exact hr.trans hcard.le)
  exact ⟨fun i => α (g i), hα_inj.comp g.injective, hα_li.comp _ g.injective⟩

/-- **McCoy, hard direction** (over a field): if `r ≤ M.rank` then some `r × r` minor of `M` is
nonzero.  Equivalently, the *determinantal rank* (the largest size of a nonvanishing minor) is at
least the linear rank `M.rank = dim (column span)`.

Proof: from `r ≤ M.rank = dim (column span)` pick `r` linearly independent columns `ci`
(`exists_injective_comp_linearIndependent`); the `b × r` block `M.submatrix id ci` then has rank
`r`, so (row rank = rank over a field) it has `r` linearly independent rows `ri`; the resulting
square block `M.submatrix ri ci` has linearly independent rows, hence is a unit
(`linearIndependent_rows_iff_isUnit`), so its determinant is nonzero.

Stacks: the ideal of minors `I(φ)` and its rank characterisation underlie **00N1** (Buchsbaum–
Eisenbud, Prop 10.102.9).  Classical statement: McCoy's theorem — over a field the rank equals the
largest size of a nonvanishing minor. -/
theorem exists_det_submatrix_ne_zero_of_le_rank {r : ℕ} (M : Matrix (Fin b) (Fin a) K)
    (h : r ≤ M.rank) :
    ∃ (ri : Fin r → Fin b) (ci : Fin r → Fin a), (M.submatrix ri ci).det ≠ 0 := by
  -- pick `r` linearly independent columns
  have hcol : r ≤ Module.finrank K (Submodule.span K (Set.range M.col)) := by
    rwa [← rank_eq_finrank_span_cols]
  obtain ⟨ci, -, hci⟩ := exists_injective_comp_linearIndependent M.col hcol
  have hNcol : (M.submatrix (id : Fin b → Fin b) ci).col = M.col ∘ ci := rfl
  -- the `b × r` block then has rank `r`
  have hNrank : r ≤ (M.submatrix (id : Fin b → Fin b) ci).rank := by
    rw [rank_eq_finrank_span_cols, hNcol, finrank_span_eq_card hci, Fintype.card_fin]
  -- pick `r` linearly independent rows of that block
  have hrow : r ≤ Module.finrank K
      (Submodule.span K (Set.range (M.submatrix (id : Fin b → Fin b) ci).row)) := by
    rwa [← rank_eq_finrank_span_row]
  obtain ⟨ri, -, hri⟩ :=
    exists_injective_comp_linearIndependent (M.submatrix (id : Fin b → Fin b) ci).row hrow
  -- the square block `M.submatrix ri ci` has linearly independent rows, hence unit determinant
  refine ⟨ri, ci, ?_⟩
  have hProw : (M.submatrix ri ci).row = (M.submatrix (id : Fin b → Fin b) ci).row ∘ ri := rfl
  have hunit : IsUnit (M.submatrix ri ci) := by
    rw [← linearIndependent_rows_iff_isUnit, hProw]; exact hri
  exact isUnit_iff_ne_zero.mp ((isUnit_iff_isUnit_det _).mp hunit)

/-- **McCoy over a field.**  The `r`-th minor ideal is trivial iff the rank drops below `r`:
`idealOfMinors r M = ⊥ ↔ M.rank < r`.  Combines the two directions above with
`idealOfMinors_eq_bot_iff`. -/
theorem idealOfMinors_eq_bot_iff_rank_lt (r : ℕ) (M : Matrix (Fin b) (Fin a) K) :
    idealOfMinors r M = ⊥ ↔ M.rank < r := by
  rw [idealOfMinors_eq_bot_iff]
  constructor
  · intro h
    by_contra hlt
    obtain ⟨ri, ci, hne⟩ := exists_det_submatrix_ne_zero_of_le_rank M (not_lt.mp hlt)
    exact hne (h ri ci)
  · intro hlt ri ci
    by_contra hne
    exact absurd (le_rank_of_det_submatrix_ne_zero M ri ci hne) (not_le.mpr hlt)

/-- **McCoy-rank locus bridge.**  For a ring hom `f : S →+* K` to a field, the `r`-th minor ideal of
`M` is contained in `ker f` iff the base-changed matrix `M.map f` has rank `< r`:
`idealOfMinors r M ≤ ker f ↔ (M.map f).rank < r`.

Specialising `f` to the residue map `S → κ(𝔮)` (whose kernel is `𝔮`) gives
`idealOfMinors r M ⊆ 𝔮 ↔ rank_{κ(𝔮)}(M ⊗ κ(𝔮)) < r`, i.e. via `PrimeSpectrum.mem_zeroLocus`,
`𝔮 ∈ zeroLocus (idealOfMinors r M) ↔ rank_{κ(𝔮)} < r` — the connection to the (open) rank-drop
loci used by Stacks 00RB. -/
theorem idealOfMinors_le_ker_iff_rank_lt (f : S →+* K) (r : ℕ) (M : Matrix (Fin b) (Fin a) S) :
    idealOfMinors r M ≤ RingHom.ker f ↔ (M.map f).rank < r := by
  rw [← Ideal.map_eq_bot_iff_le_ker, idealOfMinors_map, idealOfMinors_eq_bot_iff_rank_lt]

end Field

end Matrix

/-- Ideal of `r × r` minors of `φ : Sᵃ → Sᵇ` (Stacks 00N1 `I_r(φ)`, Fitting-type): the ideal
generated by the determinants of all `r × r` submatrices of the matrix of `φ` in the standard bases.
Defined as `Matrix.idealOfMinors` of `LinearMap.toMatrix (Pi.basisFun …)`. -/
def LinearMap.idealOfMinors {S : Type*} [CommRing S] {a b : ℕ}
    (r : ℕ) (φ : (Fin a → S) →ₗ[S] (Fin b → S)) : Ideal S :=
  Matrix.idealOfMinors r
    (LinearMap.toMatrix (Pi.basisFun S (Fin a)) (Pi.basisFun S (Fin b)) φ)

/-- Unfolding: `LinearMap.idealOfMinors r φ` is the minor ideal of the standard-bases matrix of `φ`.
Lets downstream code pass to the basis-free `Matrix.idealOfMinors` API. -/
theorem LinearMap.idealOfMinors_eq {S : Type*} [CommRing S] {a b : ℕ}
    (r : ℕ) (φ : (Fin a → S) →ₗ[S] (Fin b → S)) :
    LinearMap.idealOfMinors r φ =
      Matrix.idealOfMinors r
        (LinearMap.toMatrix (Pi.basisFun S (Fin a)) (Pi.basisFun S (Fin b)) φ) :=
  rfl

/-- **[T-FIT.antitone]** Larger minors generate a smaller ideal: `I_{r+1}(φ) ⊆ I_r(φ)` (Laplace
expansion).  A basic property feeding the McCoy-rank bookkeeping in the acyclicity criterion. -/
theorem LinearMap.idealOfMinors_antitone {S : Type*} [CommRing S] {a b : ℕ}
    (r : ℕ) (φ : (Fin a → S) →ₗ[S] (Fin b → S)) :
    LinearMap.idealOfMinors (r + 1) φ ≤ LinearMap.idealOfMinors r φ :=
  Matrix.idealOfMinors_succ_le r _

end
