/-
Copyright (c) 2026 The AINTLIB contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: AINTLIB ModularCurves project

ForMathlib (OURS, not vendored): upstream candidate. Ticket T-Q2 (statements; the
proofs are KM A7.1.1 = SGA III Exp. V Thm 4.1 territory and are deliberately left
as WIP `sorry`s per the ticket scope).
-/
import ModularCurves.ForMathlib.InvariantBaseChange
import Mathlib.RingTheory.Etale.Basic
import Mathlib.RingTheory.Smooth.Fiber
import Mathlib.RingTheory.Finiteness.Nakayama

/-!
# Free actions and the étale-torsor theorem (Katz–Mazur A7.1.1/A7.1.2) — statements

KM's freeness condition for a finite group `G` acting on an `R`-algebra `A`
(A7.1.1): *"G acts freely on A in the sense that for any non-zero R-algebra R', and
any element g ≠ id of G, g operates without fixed points on the set
Hom_{R-alg}(A, R')."* Under this condition:

* `IsFreeAlgebraAction` — the freeness predicate;
* `MulSemiringAction.torsorMul` — the multiplication comparison
  `A ⊗[Aᴳ] A → (G → A)`, `x ⊗ y ↦ (x·(g•y))_g`;
* `Module.Finite.of_isFreeAlgebraAction`, `Algebra.Etale.of_isFreeAlgebraAction`,
  `torsorMul_bijective_of_isFreeAlgebraAction` — KM A7.1.1: `A` is a finite étale
  `G`-torsor over `Aᴳ` (three single-conclusion statements; the torsor condition is
  the bijectivity of `torsorMul`);
* `fixedPointsBaseChange_bijective_of_isFreeAlgebraAction` — KM A7.1.2: free
  actions satisfy the base-change property `∗(A, G, R)` for every `R'`.

Proofs (`sorry`d, WIP): KM defers A7.1.1 to [SGA III, Exposé V, Thm 4.1] or
[Demazure–Gabriel, III §2, 6.1] — *"In the absence of noetherian hypotheses, this is
rather delicate."* A7.1.2 follows by faithfully flat descent along `Aᴳ → A` from the
torsor triviality; it becomes provable here once A7.1.1 lands.

The stabilizer dictionary: freeness in the above sense says exactly that no
`g ≠ 1` fixes any point of `Spec A` valued in any ring — for modular curves this is
the "no elliptic points" condition under which the level quotients stay schemes.
-/

universe u

open TensorProduct

variable (G : Type*) [Group G]
variable (R A : Type u)
variable [CommRing R] [CommRing A] [Algebra R A]
variable [MulSemiringAction G A] [SMulCommClass G R A] [SMulCommClass R G A]

/-- **KM A7.1.1's freeness condition**: `G` acts freely on the `R`-algebra `A` if for
every nonzero `R`-algebra `R'` no `g ≠ 1` fixes an `R`-algebra point
`A →ₐ[R] R'`. (Verbatim: "for any non-zero R-algebra R', and any element g ≠ id of
G, g operates without fixed points on the set Hom_{R-alg}(A, R')".) -/
def IsFreeAlgebraAction : Prop :=
  ∀ g : G, g ≠ 1 → ∀ (R' : Type u) [CommRing R'] [Algebra R R'] [Nontrivial R']
    (φ : A →ₐ[R] R'), ∃ a : A, φ (g • a) ≠ φ a

/-- **(T-Q2-A711, step 1 — the Chase–Harrison–Rosenberg bridge; PROVEN)** KM's freeness
condition implies the pointwise CHR condition: at every prime `𝔭` of `A` and every `g ≠ 1`
there is `a : A` with `g • a - a ∉ 𝔭`.

Take KM's `R' := A ⧸ 𝔭` (nonzero because `𝔭` is prime) and `φ :=` the quotient map. This is
the hypothesis under which the classical Galois theory of commutative rings
(Chase–Harrison–Rosenberg, Auslander–Goldman) proves `A ⊗_{Aᴳ} A ≅ ∏_G A` and étaleness —
i.e. the route by which `torsorMul_bijective_of_isFreeAlgebraAction` and
`Algebra.Etale.of_isFreeAlgebraAction` below will be discharged, KM's own reference being
[SGA III, Exp. V, Thm 4.1] (not in `refs/`). -/
theorem chr_of_isFreeAlgebraAction (hfree : IsFreeAlgebraAction G R A)
    (p : Ideal A) [hp : p.IsPrime] (g : G) (hg : g ≠ 1) :
    ∃ a : A, g • a - a ∉ p := by
  haveI : Nontrivial (A ⧸ p) := Ideal.Quotient.nontrivial_iff.mpr hp.ne_top
  obtain ⟨a, ha⟩ := hfree g hg (A ⧸ p) (Ideal.Quotient.mkₐ R p)
  refine ⟨a, fun hmem => ha ?_⟩
  have h0 : (Ideal.Quotient.mkₐ R p) (g • a - a) = 0 := by
    rw [Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem]
    exact hmem
  rw [map_sub, sub_eq_zero] at h0
  exact h0

/-- **(T-Q2-A711, step 2)** For `g ≠ 1` the ideal generated by the "displacements"
`g • a - a` is the unit ideal: otherwise it lies in a maximal ideal, contradicting
`chr_of_isFreeAlgebraAction` there. -/
theorem span_displacement_eq_top (hfree : IsFreeAlgebraAction G R A) (g : G) (hg : g ≠ 1) :
    Ideal.span (Set.range fun a : A => g • a - a) = ⊤ := by
  by_contra hne
  obtain ⟨m, hm, hle⟩ := Ideal.exists_le_maximal _ hne
  haveI : m.IsPrime := hm.isPrime
  obtain ⟨a, ha⟩ := chr_of_isFreeAlgebraAction G R A hfree m g hg
  exact ha (hle (Ideal.subset_span ⟨a, rfl⟩))

namespace MulSemiringAction

/-- The torsor-multiplication comparison map `A ⊗[Aᴳ] A → (G → A)`,
`x ⊗ y ↦ (x · (g • y))_g` (KM A7.1.1: "the natural map A ⊗_{A^G} A → ∏_{g∈G} A,
x⊗y ↦ (⋯, x⊗g(y), ⋯)"). Its bijectivity is the `G`-torsor condition for
`Aᴳ → A`. -/
noncomputable def torsorMul :
    A ⊗[FixedPoints.subalgebra R A G] A →ₐ[FixedPoints.subalgebra R A G] (G → A) :=
  Algebra.TensorProduct.lift
    (Pi.constAlgHom (FixedPoints.subalgebra R A G) G A)
    (AlgHom.pi fun g => MulSemiringAction.toAlgHom (FixedPoints.subalgebra R A G) A g)
    (fun _ _ => Commute.all _ _)

omit [SMulCommClass R G A] in
@[simp]
theorem torsorMul_tmul (x y : A) (g : G) :
    torsorMul G R A (x ⊗ₜ y) g = x * g • y := rfl

end MulSemiringAction

variable [Finite G]

section GaloisCoordinates

variable [Fintype G] [DecidableEq G]

/-- **(T-Q2-A711, step 3)** For each `g ≠ 1` there is `w ∈ A ⊗_{Aᴳ} A` whose comparison
image vanishes at `1` and is `1` at `g`. Built from `1 = ∑ cₐ · (g • a − a)`
(`span_displacement_eq_top`) as `w = ∑ cₐ ⊗ a − cₐ·a ⊗ 1`. -/
theorem exists_torsorMul_eq_zero_one (hfree : IsFreeAlgebraAction G R A) (g : G) (hg : g ≠ 1) :
    ∃ w : A ⊗[FixedPoints.subalgebra R A G] A,
      MulSemiringAction.torsorMul G R A w 1 = 0 ∧
      MulSemiringAction.torsorMul G R A w g = 1 := by
  have h1 : (1 : A) ∈ Ideal.span (Set.range fun a : A => g • a - a) := by
    rw [span_displacement_eq_top G R A hfree g hg]; trivial
  rw [Finsupp.mem_span_range_iff_exists_finsupp] at h1
  obtain ⟨c, hc⟩ := h1
  refine ⟨c.sum fun a ca => (ca ⊗ₜ[FixedPoints.subalgebra R A G] a
      - (ca * a) ⊗ₜ[FixedPoints.subalgebra R A G] (1 : A)), ?_, ?_⟩
  · rw [Finsupp.sum, map_sum]
    simp only [Finset.sum_apply, map_sub, Pi.sub_apply, MulSemiringAction.torsorMul_tmul,
      one_smul, mul_one]
    simp
  · rw [Finsupp.sum, map_sum]
    simp only [Finset.sum_apply, map_sub, Pi.sub_apply, MulSemiringAction.torsorMul_tmul,
      smul_one, mul_one]
    rw [← hc, Finsupp.sum]
    refine Finset.sum_congr rfl fun a _ => ?_
    rw [smul_eq_mul, mul_sub]

/-- **(T-Q2-A711, step 4 — the separability idempotent / Galois coordinates)** For a free
action of a finite group there is a finite family `(aᵢ, bᵢ)` with
`∑ᵢ aᵢ · (g • bᵢ) = δ_{g,1}` for every `g ∈ G`.

Construction (Chase–Harrison–Rosenberg; the same content as SGA III Exp. V Thm 4.1 (iv),
whose proof runs through semi-local rings and Lemme 4.2 — avoided here): with `w_g` from
`exists_torsorMul_eq_zero_one`, the element `e = ∏_{g ≠ 1} (1 − w_g)` of the ring
`A ⊗_{Aᴳ} A` has comparison image the indicator of `1 ∈ G`, because `torsorMul` is a ring
homomorphism into the product ring `G → A`. Writing `e` as a finite sum of pure tensors
(`TensorProduct.exists_finset`) reads off the coordinates. -/
theorem exists_galoisCoords (hfree : IsFreeAlgebraAction G R A) :
    ∃ S : Finset (A × A), ∀ g : G,
      (∑ p ∈ S, p.1 * (g • p.2)) = if g = 1 then 1 else 0 := by
  classical
  choose w hw1 hwg using fun (g : G) (hg : g ≠ 1) => exists_torsorMul_eq_zero_one G R A hfree g hg
  set e : A ⊗[FixedPoints.subalgebra R A G] A :=
    ∏ h ∈ (Finset.univ.erase (1 : G)).attach,
      (1 - w h.1 (Finset.ne_of_mem_erase h.2)) with he
  have hev : ∀ g : G, MulSemiringAction.torsorMul G R A e g = if g = 1 then 1 else 0 := by
    intro g
    have hprod : MulSemiringAction.torsorMul G R A e g
        = ∏ h ∈ (Finset.univ.erase (1 : G)).attach,
            (1 - MulSemiringAction.torsorMul G R A (w h.1 (Finset.ne_of_mem_erase h.2)) g) := by
      rw [he, map_prod]
      simp [Finset.prod_apply]
    rw [hprod]
    by_cases hg : g = 1
    · subst hg
      refine (Finset.prod_eq_one fun h _ => ?_).trans (by simp)
      rw [hw1 h.1 (Finset.ne_of_mem_erase h.2), sub_zero]
    · rw [if_neg hg]
      refine Finset.prod_eq_zero (i := ⟨g, Finset.mem_erase.mpr ⟨hg, Finset.mem_univ g⟩⟩)
        (Finset.mem_attach _ _) ?_
      rw [hwg g hg, sub_self]
  obtain ⟨S, hS⟩ := TensorProduct.exists_finset e
  refine ⟨S, fun g => ?_⟩
  have hg := hev g
  rw [hS, map_sum] at hg
  simpa [Finset.sum_apply, MulSemiringAction.torsorMul_tmul] using hg

end GaloisCoordinates

/-- The `G`-trace `a ↦ ∑_g g • a`, valued in the invariants. -/
def traceInvariants [Fintype G] (a : A) : FixedPoints.subalgebra R A G :=
  ⟨∑ g : G, g • a, by
    intro h
    show h • (∑ g : G, g • a) = ∑ g : G, g • a
    rw [Finset.smul_sum]
    have hre : ∀ g : G, h • (g • a) = (h * g) • a := fun g => (mul_smul h g a).symm
    simp only [hre]
    exact Fintype.sum_bijective (h * ·) (Group.mulLeft_bijective h) _ _ (fun _ => rfl)⟩

/-- **(T-Q2-A711, step 6 — the dual-basis identity)** The Galois coordinates are a *dual
basis* of `A` over `Aᴳ` with respect to the trace: `∑ᵢ aᵢ · tr(bᵢ · x) = x`.

Indeed `∑ᵢ aᵢ · tr(bᵢx) = ∑_g (∑ᵢ aᵢ (g•bᵢ)) (g•x) = ∑_g δ_{g,1} (g•x) = x`. This is the
classical statement that a Galois extension of commutative rings is finitely generated
projective over its invariants (Chase–Harrison–Rosenberg). -/
theorem galoisCoords_dual [Fintype G] [DecidableEq G] {S : Finset (A × A)}
    (hS : ∀ g : G, (∑ p ∈ S, p.1 * (g • p.2)) = if g = 1 then 1 else 0) (x : A) :
    (∑ p ∈ S, p.1 * (traceInvariants G R A (p.2 * x) : A)) = x := by
  classical
  have hexp : ∀ p : A × A, (traceInvariants G R A (p.2 * x) : A) = ∑ g : G, g • (p.2 * x) :=
    fun _ => rfl
  simp only [hexp, Finset.mul_sum]
  rw [Finset.sum_comm]
  have hterm : ∀ g : G, (∑ p ∈ S, p.1 * (g • (p.2 * x)))
      = (∑ p ∈ S, p.1 * (g • p.2)) * (g • x) := by
    intro g
    rw [Finset.sum_mul]
    refine Finset.sum_congr rfl fun p _ => ?_
    rw [smul_mul', mul_assoc]
  simp only [hterm, hS]
  rw [Finset.sum_eq_single (1 : G)]
  · simp
  · intro g _ hg; rw [if_neg hg, zero_mul]
  · intro hc; exact absurd (Finset.mem_univ (1 : G)) hc

/-- **KM A7.1.1, finiteness part; PROVEN** — for a free action of a finite group, `A` is a
finite `Aᴳ`-module: the dual-basis identity `x = ∑ᵢ tr(bᵢ·x) • aᵢ` exhibits the finitely
many `aᵢ` of `exists_galoisCoords` as generators.

Note this is *derived*, not hypothesized — the flagged "finite locally free of rank `|G|`"
content of SGA III Exp. V §5 comes out of the Galois coordinates. -/
theorem Module.Finite.of_isFreeAlgebraAction (hfree : IsFreeAlgebraAction G R A) :
    Module.Finite (FixedPoints.subalgebra R A G) A := by
  classical
  haveI : Fintype G := Fintype.ofFinite G
  obtain ⟨S, hS⟩ := exists_galoisCoords G R A hfree
  refine ⟨⟨S.image Prod.fst, ?_⟩⟩
  rw [eq_top_iff]
  intro x _
  rw [← galoisCoords_dual G R A hS x]
  refine Submodule.sum_mem _ fun p hp => ?_
  have hsm : p.1 * (traceInvariants G R A (p.2 * x) : A)
      = (traceInvariants G R A (p.2 * x)) • p.1 := by
    show _ = (traceInvariants G R A (p.2 * x) : A) * p.1
    ring
  rw [hsm]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Finset.mem_coe.mpr
    (Finset.mem_image.mpr ⟨p, hp, rfl⟩)))

/-- The `G`-trace as an `Aᴳ`-linear map `A → Aᴳ` (the bundled form of `traceInvariants`). -/
noncomputable def traceLinear [Fintype G] :
    A →ₗ[FixedPoints.subalgebra R A G] FixedPoints.subalgebra R A G where
  toFun a := traceInvariants G R A a
  map_add' a b := by
    ext
    show (∑ g : G, g • (a + b)) = (∑ g : G, g • a) + ∑ g : G, g • b
    simp [Finset.sum_add_distrib, smul_add]
  map_smul' c a := by
    ext
    show (∑ g : G, g • ((c : A) * a)) = (c : A) * ∑ g : G, g • a
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun g _ => ?_
    rw [smul_mul', c.2 g]

/-- **(T-Q2-A711, step 9 — projectivity; PROVEN)** For a free action of a finite group, `A`
is a projective `Aᴳ`-module: `galoisCoords_dual` *is* a dual basis, so
`x ↦ ∑ᵢ single aᵢ (tr(bᵢ·x))` splits the canonical surjection `(A →₀ Aᴳ) ↠ A`.

Together with `Module.Finite.of_isFreeAlgebraAction` this says `A` is **finitely generated
projective** over `Aᴳ` (hence flat, hence faithfully flat) — the module-theoretic content of
KM A7.1.1 / SGA III Exp. V Thm 4.1, obtained without either source's machinery. It is also
the input for the remaining `Algebra.FinitePresentation` gap ([A711-FP], see below). -/
theorem Module.Projective.of_isFreeAlgebraAction (hfree : IsFreeAlgebraAction G R A) :
    Module.Projective (FixedPoints.subalgebra R A G) A := by
  classical
  haveI : Fintype G := Fintype.ofFinite G
  obtain ⟨S, hS⟩ := exists_galoisCoords G R A hfree
  rw [Module.projective_def']
  refine ⟨∑ p ∈ S, (Finsupp.lsingle p.1).comp
      (traceLinear G R A ∘ₗ (LinearMap.mulLeft (FixedPoints.subalgebra R A G) p.2)), ?_⟩
  ext x
  simp only [LinearMap.coe_comp, Function.comp_apply, LinearMap.id_apply,
    LinearMap.coe_sum, Finset.sum_apply, map_sum, Finsupp.lsingle_apply,
    Finsupp.linearCombination_single, id_eq, LinearMap.mulLeft_apply]
  refine Eq.trans ?_ (galoisCoords_dual G R A hS x)
  refine Finset.sum_congr rfl fun p _ => ?_
  show (traceInvariants G R A (p.2 * x) : A) * p.1
      = p.1 * (traceInvariants G R A (p.2 * x) : A)
  ring

/-- **(T-Q2-A711, step 11 — surjectivity of the trace; PROVEN)** For a free action of a
finite group there is `c : A` with `tr(c) = 1`; hence `Aᴳ ↪ A` splits as `Aᴳ`-modules via
`a ↦ tr(c · a)`.

Proof: the image of `tr` is an ideal `I` of `Aᴳ`; the dual-basis identity at `x` shows
`x = ∑ᵢ tr(bᵢ x) • aᵢ`, so `⊤ ≤ I • ⊤` as `Aᴳ`-submodules of `A` whenever `I ⊆ 𝔪`; since `A`
is a *finite* `Aᴳ`-module (`Module.Finite.of_isFreeAlgebraAction`), Nakayama produces
`r ≡ 1 mod 𝔪` with `r · A = 0`, so `r = 0` and `1 ∈ 𝔪` — contradiction. Hence `I = ⊤`.

This is the input for **[A711-BC]** (KM A7.1.2): averaging by `c` retracts `A ⊗_R R'` onto
its `G`-invariants inside the image of `Aᴳ ⊗_R R'`. -/
theorem exists_traceInvariants_eq_one [Fintype G] (hfree : IsFreeAlgebraAction G R A) :
    ∃ c : A, traceLinear G R A c = 1 := by
  classical
  haveI : Module.Finite (FixedPoints.subalgebra R A G) A :=
    Module.Finite.of_isFreeAlgebraAction G R A hfree
  obtain ⟨S, hS⟩ := exists_galoisCoords G R A hfree
  have h1 : (1 : FixedPoints.subalgebra R A G) ∈ LinearMap.range (traceLinear G R A) := by
    by_contra hnot
    have hne : (LinearMap.range (traceLinear G R A) :
        Submodule (FixedPoints.subalgebra R A G) (FixedPoints.subalgebra R A G)) ≠ ⊤ := by
      intro hc; exact hnot (hc ▸ Submodule.mem_top)
    obtain ⟨m, hm, hle⟩ := Ideal.exists_le_maximal (LinearMap.range (traceLinear G R A)) hne
    have hsub : (⊤ : Submodule (FixedPoints.subalgebra R A G) A)
        ≤ m • (⊤ : Submodule (FixedPoints.subalgebra R A G) A) := by
      intro x _
      have hx : (∑ p ∈ S, (traceLinear G R A (p.2 * x)) • p.1) = x := by
        refine Eq.trans ?_ (galoisCoords_dual G R A hS x)
        refine Finset.sum_congr rfl fun p _ => ?_
        show (traceInvariants G R A (p.2 * x) : A) * p.1
            = p.1 * (traceInvariants G R A (p.2 * x) : A)
        ring
      rw [← hx]
      refine Submodule.sum_mem _ fun p _ => ?_
      exact Submodule.smul_mem_smul (hle ⟨p.2 * x, rfl⟩) Submodule.mem_top
    obtain ⟨r, hr, hr0⟩ := Submodule.exists_sub_one_mem_and_smul_eq_zero_of_fg_of_le_smul
      m ⊤ Module.Finite.fg_top hsub
    have hzero : (r : A) = 0 := by
      have hone := hr0 1 Submodule.mem_top
      simpa [Algebra.smul_def] using hone
    have hr' : r = 0 := Subtype.ext hzero
    rw [hr', zero_sub] at hr
    exact hm.ne_top (Ideal.eq_top_of_isUnit_mem m (by simpa using hr) isUnit_one.neg)
  obtain ⟨c, hc⟩ := h1
  exact ⟨c, hc⟩

/-- **(Additive Hilbert 90; PROVEN)** For a free action of a finite group, every additive
`1`-cocycle `a : G → A` (i.e. `a(gh) = a(g) + g • a(h)`) is a coboundary: `a(g) = d − g • d`
for `d = ∑_h a(h) · (h • c)` with `tr(c) = 1`. In other words `H¹(G, A⁺) = 0`.

`(g • d) = ∑_h (a(gh) − a(g))·(gh • c) = d − a(g)·tr(c) = d − a(g)`.

This is the additive half of the descent obstruction for Weierstrass models: the `(r, s, t)`
part of a `VariableChange`-valued cocycle is always trivializable. (The multiplicative `u`
part is *not* — its obstruction is an invertible module, see [T-E5c-ROUTE-A] on the board.) -/
theorem exists_sub_smul_eq_of_isCocycle [Fintype G] (hfree : IsFreeAlgebraAction G R A)
    (a : G → A) (hcocycle : ∀ g h : G, a (g * h) = a g + g • a h) :
    ∃ d : A, ∀ g : G, a g = d - g • d := by
  classical
  obtain ⟨c, hc⟩ := exists_traceInvariants_eq_one G R A hfree
  have hc' : (∑ g : G, g • c) = 1 := congrArg Subtype.val hc
  refine ⟨∑ h : G, a h * (h • c), fun g => ?_⟩
  have hgd : g • (∑ h : G, a h * (h • c)) = (∑ h : G, a h * (h • c)) - a g := by
    rw [Finset.smul_sum]
    have hterm : ∀ h : G, g • (a h * (h • c)) = (a (g * h) - a g) * ((g * h) • c) := by
      intro h
      rw [smul_mul', ← mul_smul, hcocycle g h]
      ring_nf
    simp only [hterm, sub_mul]
    rw [Finset.sum_sub_distrib]
    congr 1
    · exact Fintype.sum_bijective (g * ·) (Group.mulLeft_bijective g) _ _ (fun _ => rfl)
    · rw [← Finset.mul_sum]
      have hre : (∑ h : G, (g * h) • c) = ∑ h : G, h • c :=
        Fintype.sum_bijective (g * ·) (Group.mulLeft_bijective g) _ _ (fun _ => rfl)
      rw [hre, hc', mul_one]
  rw [hgd]
  ring

/-! ### [A711-DESC] Galois descent of twisted modules (route (a), step a5-ii)

For a `1`-cocycle `w : G → Aˣ` (`w(gh) = w(g) · g•w(h)`), the **twisted invariants**
`M_w = {a : A | ∀ g, g • a = w(g) · a}` form an `Aᴳ`-submodule of `A`. When the class of `w`
is locally trivial, a generator of `M_w` is a unit `d` with `w(g) = (g•d)·d⁻¹`, which is
exactly what trivializes the `u`-part of a `VariableChange` cocycle and hence descends the
Weierstrass model (see `[T-E5c-ROUTE-A]` on the board). The Galois coordinates do the work
a third time: `ρ(x) = ∑_g w(g)⁻¹ · (g • x)` retracts `A` onto `M_w`. -/

/-- Cocycle bookkeeping: `h • w(g)⁻¹ = w(hg)⁻¹ · w(h)`. -/
theorem smul_cocycle_inv (w : G → Aˣ)
    (hw : ∀ g h : G, ((w (g * h) : A)) = (w g : A) * g • (w h : A)) (g h : G) :
    h • (((w g)⁻¹ : Aˣ) : A) = (((w (h * g))⁻¹ : Aˣ) : A) * (w h : A) := by
  have hmul : (h • (((w g)⁻¹ : Aˣ) : A)) * (w (h * g) : A) = (w h : A) := by
    rw [hw h g, ← mul_assoc]
    rw [show (h • (((w g)⁻¹ : Aˣ) : A)) * (w h : A)
        = (w h : A) * (h • (((w g)⁻¹ : Aˣ) : A)) by ring]
    rw [mul_assoc, ← smul_mul' h]
    rw [show ((((w g)⁻¹ : Aˣ) : A) * (w g : A)) = 1 from (w g).inv_mul]
    rw [smul_one, mul_one]
  have hc := congrArg (fun z => z * ((((w (h * g))⁻¹ : Aˣ)) : A)) hmul
  simp only [mul_assoc] at hc
  rw [(w (h * g)).mul_inv, mul_one] at hc
  rw [hc]; ring

/-- The `w`-twisted invariants, an `Aᴳ`-submodule of `A`. -/
def twistedInvariants (w : G → Aˣ) : Submodule (FixedPoints.subalgebra R A G) A where
  carrier := {a : A | ∀ g : G, g • a = (w g : A) * a}
  zero_mem' := by intro g; simp
  add_mem' := by
    intro a b ha hb g
    rw [smul_add, ha g, hb g, mul_add]
  smul_mem' := by
    intro b a ha g
    show g • ((b : A) * a) = (w g : A) * ((b : A) * a)
    rw [smul_mul', b.2 g, ha g]
    ring

/-- The twisted average `ρ(x) = ∑_g w(g)⁻¹ · (g • x)` lands in the twisted invariants. -/
theorem twistedAvg_mem [Fintype G] (w : G → Aˣ)
    (hw : ∀ g h : G, ((w (g * h) : A)) = (w g : A) * g • (w h : A)) (x : A) :
    (∑ g : G, (((w g)⁻¹ : Aˣ) : A) * g • x) ∈ twistedInvariants G R A w := by
  intro h
  rw [Finset.smul_sum, show (w h : A) * (∑ g : G, (((w g)⁻¹ : Aˣ) : A) * g • x)
      = ∑ g : G, (w h : A) * ((((w g)⁻¹ : Aˣ) : A) * g • x) from Finset.mul_sum ..]
  have hterm : ∀ g : G, h • ((((w g)⁻¹ : Aˣ) : A) * g • x)
      = (w h : A) * ((((w (h * g))⁻¹ : Aˣ) : A) * (h * g) • x) := by
    intro g
    rw [smul_mul', smul_cocycle_inv (G := G) (A := A) w hw g h, ← mul_smul]
    ring
  simp only [hterm]
  exact Fintype.sum_bijective (h * ·) (Group.mulLeft_bijective h)
    (fun g => (w h : A) * ((((w (h * g))⁻¹ : Aˣ) : A) * (h * g) • x))
    (fun k => (w h : A) * ((((w k)⁻¹ : Aˣ) : A) * k • x)) (fun _ => rfl)

/-- The twisted average as an `Aᴳ`-linear map `A → M_w`. -/
noncomputable def twistedAvg [Fintype G] (w : G → Aˣ)
    (hw : ∀ g h : G, ((w (g * h) : A)) = (w g : A) * g • (w h : A)) :
    A →ₗ[FixedPoints.subalgebra R A G] twistedInvariants G R A w where
  toFun x := ⟨∑ g : G, (((w g)⁻¹ : Aˣ) : A) * g • x, twistedAvg_mem G R A w hw x⟩
  map_add' x y := by
    ext
    show (∑ g : G, (((w g)⁻¹ : Aˣ) : A) * g • (x + y))
      = (∑ g : G, (((w g)⁻¹ : Aˣ) : A) * g • x) + ∑ g : G, (((w g)⁻¹ : Aˣ) : A) * g • y
    simp [smul_add, mul_add, Finset.sum_add_distrib]
  map_smul' b x := by
    ext
    show (∑ g : G, (((w g)⁻¹ : Aˣ) : A) * g • ((b : A) * x))
      = (b : A) * ∑ g : G, (((w g)⁻¹ : Aˣ) : A) * g • x
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun g _ => ?_
    rw [smul_mul', b.2 g]
    ring

/-- **(A711-DESC, the retraction)** With `tr(c) = 1`, the twisted average retracts `A` onto
`M_w` along `m ↦ c · m`: for `m ∈ M_w`, `ρ(c · m) = m`.

`ρ(c·m) = ∑_g w(g)⁻¹ (g•c)(g•m) = ∑_g w(g)⁻¹ (g•c) w(g) m = tr(c)·m = m`. Hence `M_w` is a
**direct summand of `A`** as an `Aᴳ`-module — in particular finitely generated (and
projective, since `A` is). -/
theorem twistedAvg_smul_eq [Fintype G] (w : G → Aˣ)
    (hw : ∀ g h : G, ((w (g * h) : A)) = (w g : A) * g • (w h : A))
    (c : A) (hc : (∑ g : G, g • c) = 1) (m : twistedInvariants G R A w) :
    twistedAvg G R A w hw (c * (m : A)) = m := by
  ext
  show (∑ g : G, (((w g)⁻¹ : Aˣ) : A) * g • (c * (m : A))) = (m : A)
  have hterm : ∀ g : G, (((w g)⁻¹ : Aˣ) : A) * g • (c * (m : A)) = (g • c) * (m : A) := by
    intro g
    rw [smul_mul', m.2 g]
    rw [show (((w g)⁻¹ : Aˣ) : A) * ((g • c) * ((w g : A) * (m : A)))
        = (g • c) * ((((w g)⁻¹ : Aˣ) : A) * (w g : A)) * (m : A) by ring,
      (w g).inv_mul, mul_one]
  simp only [hterm, ← Finset.sum_mul, hc, one_mul]

/-- **(A711-DESC)** The twisted invariants are a finite `Aᴳ`-module (a quotient of `A`). -/
theorem twistedInvariants_finite [Fintype G] (hfree : IsFreeAlgebraAction G R A)
    (w : G → Aˣ) (hw : ∀ g h : G, ((w (g * h) : A)) = (w g : A) * g • (w h : A)) :
    Module.Finite (FixedPoints.subalgebra R A G) (twistedInvariants G R A w) := by
  haveI : Module.Finite (FixedPoints.subalgebra R A G) A :=
    Module.Finite.of_isFreeAlgebraAction G R A hfree
  obtain ⟨c, hc⟩ := exists_traceInvariants_eq_one G R A hfree
  have hc' : (∑ g : G, g • c) = 1 := congrArg Subtype.val hc
  refine Module.Finite.of_surjective (twistedAvg G R A w hw) fun m => ?_
  exact ⟨c * (m : A), twistedAvg_smul_eq G R A w hw c hc' m⟩

/-- A `1`-cocycle is normalised: `w(1) = 1`. -/
theorem cocycle_one (w : G → Aˣ)
    (hw : ∀ g h : G, ((w (g * h) : A)) = (w g : A) * g • (w h : A)) : ((w 1 : A)) = 1 := by
  have h := hw 1 1
  rw [mul_one, one_smul] at h
  have h2 := congrArg (fun z => (((w 1)⁻¹ : Aˣ) : A) * z) h
  simp only [← mul_assoc, (w 1).inv_mul, one_mul] at h2
  exact h2.symm

/-- The multiplication map `A ⊗_{Aᴳ} M_w → A`, `a ⊗ m ↦ a · m`. -/
noncomputable def twistedMul (w : G → Aˣ) :
    A ⊗[FixedPoints.subalgebra R A G] (twistedInvariants G R A w)
      →ₗ[FixedPoints.subalgebra R A G] A :=
  TensorProduct.lift ((LinearMap.mul (FixedPoints.subalgebra R A G) A).compl₂
    (twistedInvariants G R A w).subtype)

@[simp] theorem twistedMul_tmul (w : G → Aˣ) (a : A) (m : twistedInvariants G R A w) :
    twistedMul G R A w (a ⊗ₜ[FixedPoints.subalgebra R A G] m) = a * (m : A) := rfl

/-- **(A711-DESC, the descent isomorphism; PROVEN)** For a free action of a finite group and
a `1`-cocycle `w : G → Aˣ`, multiplication `A ⊗_{Aᴳ} M_w → A` is **bijective**: the twisted
invariants are an *invertible* `Aᴳ`-module trivialised by `A`.

This is Galois descent of (rank-one) modules, obtained from the Galois coordinates for the
third time. The inverse is `x ↦ ∑ᵢ aᵢ ⊗ ρ(bᵢ · x)` with `ρ` the twisted average:
* `mult ∘ inv = id` collapses `∑_g w(g)⁻¹ · δ_{g,1} · (g • x)` to `w(1)⁻¹ x = x`;
* `inv ∘ mult = id` on `a ⊗ m` uses `ρ(bᵢ a m) = tr(bᵢ a) · m` (the `w(g)⁻¹ · w(g)` cancel
  because `m` is twisted-invariant) and then the dual basis `∑ᵢ aᵢ · tr(bᵢ a) = a`.

Consequence for `[T-E5c-ROUTE-A]`: `M_w` is finitely generated projective of rank one, so
Zariski-locally on `Spec Aᴳ` it has a generator `d`, which multiplication forces to be a
**unit** of `A`; then `g • d = w(g) · d`, i.e. the cocycle is locally a coboundary and the
Weierstrass model descends. -/
theorem twistedMul_bijective [Fintype G] [DecidableEq G] (hfree : IsFreeAlgebraAction G R A)
    (w : G → Aˣ) (hw : ∀ g h : G, ((w (g * h) : A)) = (w g : A) * g • (w h : A)) :
    Function.Bijective (twistedMul G R A w) := by
  classical
  obtain ⟨S, hS⟩ := exists_galoisCoords G R A hfree
  set inv : A → A ⊗[FixedPoints.subalgebra R A G] (twistedInvariants G R A w) :=
    fun x => ∑ p ∈ S, p.1 ⊗ₜ[FixedPoints.subalgebra R A G] (twistedAvg G R A w hw (p.2 * x))
    with hinv
  -- right inverse
  have hright : ∀ x : A, twistedMul G R A w (inv x) = x := by
    intro x
    rw [hinv, map_sum]
    have hterm : ∀ p : A × A, twistedMul G R A w
        (p.1 ⊗ₜ[FixedPoints.subalgebra R A G] (twistedAvg G R A w hw (p.2 * x)))
          = ∑ g : G, (((w g)⁻¹ : Aˣ) : A) * (p.1 * (g • p.2) * (g • x)) := by
      intro p
      rw [twistedMul_tmul]
      show p.1 * (∑ g : G, (((w g)⁻¹ : Aˣ) : A) * g • (p.2 * x)) = _
      rw [Finset.mul_sum]
      refine Finset.sum_congr rfl fun g _ => ?_
      rw [smul_mul']
      ring
    simp only [hterm]
    rw [Finset.sum_comm]
    have hg : ∀ g : G, (∑ p ∈ S, (((w g)⁻¹ : Aˣ) : A) * (p.1 * (g • p.2) * (g • x)))
        = (((w g)⁻¹ : Aˣ) : A) * ((if g = 1 then (1 : A) else 0) * (g • x)) := by
      intro g
      rw [← hS g, Finset.sum_mul, Finset.mul_sum]
    simp only [hg]
    rw [Finset.sum_eq_single (1 : G)]
    · have hw1 : w 1 = 1 := Units.ext (cocycle_one (G := G) (A := A) w hw)
      rw [if_pos rfl, one_mul, one_smul, hw1]
      simp
    · intro g _ hg1; rw [if_neg hg1, zero_mul, mul_zero]
    · intro hc; exact absurd (Finset.mem_univ (1 : G)) hc
  -- additivity of `inv`
  have hadd : ∀ x y : A, inv (x + y) = inv x + inv y := by
    intro x y
    rw [hinv, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun p _ => ?_
    rw [← TensorProduct.tmul_add]
    congr 1
    rw [mul_add, map_add]
  -- left inverse
  have hleft : ∀ z : A ⊗[FixedPoints.subalgebra R A G] (twistedInvariants G R A w),
      inv (twistedMul G R A w z) = z := by
    intro z
    induction z using TensorProduct.induction_on with
    | zero => simp [hinv]
    | add z₁ z₂ h₁ h₂ => rw [map_add, hadd, h₁, h₂]
    | tmul a m =>
      rw [twistedMul_tmul, hinv]
      have hrho : ∀ p : A × A, twistedAvg G R A w hw (p.2 * (a * (m : A)))
          = (traceInvariants G R A (p.2 * a)) • m := by
        intro p
        ext
        show (∑ g : G, (((w g)⁻¹ : Aˣ) : A) * g • (p.2 * (a * (m : A))))
            = (traceInvariants G R A (p.2 * a) : A) * (m : A)
        have hterm : ∀ g : G, (((w g)⁻¹ : Aˣ) : A) * g • (p.2 * (a * (m : A)))
            = (g • (p.2 * a)) * (m : A) := by
          intro g
          rw [smul_mul', smul_mul', m.2 g]
          rw [show (((w g)⁻¹ : Aˣ) : A) * ((g • p.2) * ((g • a) * ((w g : A) * (m : A))))
              = ((g • p.2) * (g • a)) * ((((w g)⁻¹ : Aˣ) : A) * (w g : A)) * (m : A) by ring,
            (w g).inv_mul, mul_one]
          rw [smul_mul']
        simp only [hterm, ← Finset.sum_mul]
        rfl
      simp only [hrho]
      have hmove : ∀ p : A × A,
          p.1 ⊗ₜ[FixedPoints.subalgebra R A G]
              ((traceInvariants G R A (p.2 * a)) • m)
            = ((traceInvariants G R A (p.2 * a) : A) * p.1)
                ⊗ₜ[FixedPoints.subalgebra R A G] m := by
        intro p
        rw [TensorProduct.tmul_smul]
        rfl
      simp only [hmove]
      rw [← TensorProduct.sum_tmul]
      congr 1
      show (∑ p ∈ S, (traceInvariants G R A (p.2 * a) : A) * p.1) = a
      refine Eq.trans ?_ (galoisCoords_dual G R A hS a)
      refine Finset.sum_congr rfl fun p _ => ?_
      ring
  exact ⟨Function.LeftInverse.injective hleft, fun x => ⟨inv x, hright x⟩⟩

/-- **KM A7.1.1, étaleness part, general base** — for a free action, `A` is étale over the
invariants.

**Status (fable-P4, 2026-07-08).** PROVEN over a noetherian invariant ring:
`Algebra.Etale.of_isFreeAlgebraAction_of_isNoetherianRing`. The general statement is blocked
on **exactly one** mathlib gap, tracked as **[A711-FP]**: there is no constructor giving
*algebra-level* `Algebra.FinitePresentation` from a **module-finite projective** algebra over
a **non-noetherian** base (Stacks 00QQ/05GH). Everything else is unconditional
(`FormallyUnramified`, `Module.Finite`, `Module.Projective` ⟹ `Module.Flat`), and mathlib's
`Algebra.Etale.of_formallyUnramified_of_flat` (Stacks 08WD) assembles them. NOT a B2 — the
statement is true; only the substrate is missing. Sorry retained with the plan attached. -/
theorem Algebra.Etale.of_isFreeAlgebraAction (hfree : IsFreeAlgebraAction G R A) :
    Algebra.Etale (FixedPoints.subalgebra R A G) A := by
  sorry

/-- The candidate inverse of `torsorMul`, built from Galois coordinates `S`:
`x ↦ ∑ᵢ aᵢ ⊗ (∑_g g⁻¹ • (x g · bᵢ))`. -/
noncomputable def galoisInv [Fintype G] (S : Finset (A × A)) (x : G → A) :
    A ⊗[FixedPoints.subalgebra R A G] A :=
  ∑ p ∈ S, p.1 ⊗ₜ[FixedPoints.subalgebra R A G] (∑ g : G, g⁻¹ • (x g * p.2))

/-- **(T-Q2-A711, step 5 — KM A7.1.1, torsor part; PROVEN)** For a free action of a finite
group the multiplication comparison `A ⊗[Aᴳ] A ≅ ∏_G A` is bijective — `Spec A` is a
`G`-torsor over `Spec Aᴳ`.

This is SGA III Exp. V Thm 4.1 (iv) — *"`X₁ ⟶ X₀ ×_Y X₀` est un isomorphisme"* — obtained
by the Chase–Harrison–Rosenberg route: the Galois coordinates of `exists_galoisCoords`
give an explicit two-sided inverse `galoisInv`, so neither SGA's semi-local reduction, nor
its Lemme 4.2, nor its faithfully-flat residue-field enlargement is needed (none of the
three has a mathlib substrate — there is no `IsSemilocalRing`). No finiteness of `A` over
`Aᴳ` is used either.

`galoisInv ∘ torsorMul = id` is where the trace enters: on a pure tensor `u ⊗ v` the inner
sum is `tr(u · bᵢ) · v` with `tr(u · bᵢ)` invariant, so it crosses the tensor to give
`(∑ᵢ tr(u · bᵢ) · aᵢ) ⊗ v = u ⊗ v` by the coordinate identity again. -/
theorem torsorMul_bijective_of_isFreeAlgebraAction
    (hfree : IsFreeAlgebraAction G R A) :
    Function.Bijective (MulSemiringAction.torsorMul G R A) := by
  classical
  haveI : Fintype G := Fintype.ofFinite G
  obtain ⟨S, hS⟩ := exists_galoisCoords G R A hfree
  -- `galoisInv S` is a right inverse
  have hright : ∀ x : G → A,
      MulSemiringAction.torsorMul G R A (galoisInv G R A S x) = x := by
    intro x
    funext h
    rw [galoisInv, map_sum]
    simp only [Finset.sum_apply, MulSemiringAction.torsorMul_tmul, Finset.smul_sum,
      Finset.mul_sum]
    rw [Finset.sum_comm]
    have hterm : ∀ g : G, (∑ p ∈ S, p.1 * (h • g⁻¹ • (x g * p.2)))
        = ((h * g⁻¹) • x g) * (if (h * g⁻¹) = 1 then 1 else 0) := by
      intro g
      rw [← hS (h * g⁻¹), Finset.mul_sum]
      refine Finset.sum_congr rfl fun p _ => ?_
      rw [← mul_smul, smul_mul']
      ring
    simp only [hterm]
    rw [Finset.sum_eq_single h]
    · simp
    · intro g _ hgh
      have hne : h * g⁻¹ ≠ 1 := fun hc => hgh (mul_inv_eq_one.mp hc).symm
      simp [hne]
    · intro hc
      exact absurd (Finset.mem_univ h) hc
  -- `galoisInv S` is additive, so it suffices to check the left inverse on pure tensors
  have hadd : ∀ x y : G → A, galoisInv G R A S (x + y)
      = galoisInv G R A S x + galoisInv G R A S y := by
    intro x y
    rw [galoisInv, galoisInv, galoisInv, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun p _ => ?_
    rw [← TensorProduct.tmul_add, ← Finset.sum_add_distrib]
    refine congrArg _ (Finset.sum_congr rfl fun g _ => ?_)
    rw [Pi.add_apply, add_mul, smul_add]
  have hleft : ∀ y : A ⊗[FixedPoints.subalgebra R A G] A,
      galoisInv G R A S (MulSemiringAction.torsorMul G R A y) = y := by
    intro y
    induction y using TensorProduct.induction_on with
    | zero => simp [galoisInv]
    | add y₁ y₂ h₁ h₂ => rw [map_add, hadd, h₁, h₂]
    | tmul u v =>
      rw [galoisInv]
      have hterm : ∀ p : A × A,
          (∑ g : G, g⁻¹ • ((MulSemiringAction.torsorMul G R A
              (u ⊗ₜ[FixedPoints.subalgebra R A G] v) : G → A) g * p.2))
            = (traceInvariants G R A (u * p.2) : A) * v := by
        intro p
        have hinner : ∀ g : G, g⁻¹ • ((MulSemiringAction.torsorMul G R A
            (u ⊗ₜ[FixedPoints.subalgebra R A G] v) : G → A) g * p.2)
              = (g⁻¹ • (u * p.2)) * v := by
          intro g
          rw [MulSemiringAction.torsorMul_tmul,
            show u * g • v * p.2 = (u * p.2) * (g • v) by ring, smul_mul', smul_smul,
            inv_mul_cancel, one_smul]
        simp only [hinner, ← Finset.sum_mul]
        congr 1
        show (∑ g : G, g⁻¹ • (u * p.2)) = ∑ g : G, g • (u * p.2)
        exact Fintype.sum_bijective (·⁻¹) (Equiv.inv G).bijective _ _ (fun _ => rfl)
      simp only [hterm]
      have hmove : ∀ p : A × A,
          p.1 ⊗ₜ[FixedPoints.subalgebra R A G] ((traceInvariants G R A (u * p.2) : A) * v)
            = ((traceInvariants G R A (u * p.2) : A) * p.1)
                ⊗ₜ[FixedPoints.subalgebra R A G] v := by
        intro p
        show p.1 ⊗ₜ[FixedPoints.subalgebra R A G]
            ((traceInvariants G R A (u * p.2)) • v) = _
        rw [TensorProduct.tmul_smul]
        rfl
      simp only [hmove]
      rw [← TensorProduct.sum_tmul]
      congr 1
      show (∑ p ∈ S, (∑ g : G, g • (u * p.2)) * p.1) = u
      have hswap : (∑ p ∈ S, (∑ g : G, g • (u * p.2)) * p.1)
          = ∑ g : G, (g • u) * (∑ p ∈ S, p.1 * (g • p.2)) := by
        simp only [Finset.sum_mul]
        rw [Finset.sum_comm]
        refine Finset.sum_congr rfl fun g _ => ?_
        rw [Finset.mul_sum]
        refine Finset.sum_congr rfl fun p _ => ?_
        rw [smul_mul']
        ring
      rw [hswap, Finset.sum_eq_single (1 : G)]
      · rw [hS (1 : G)]; simp
      · intro g _ hg; rw [hS g, if_neg hg, mul_zero]
      · intro hc; exact absurd (Finset.mem_univ (1 : G)) hc
  exact ⟨Function.LeftInverse.injective hleft, fun x => ⟨galoisInv G R A S x, hright x⟩⟩

/-- **KM A7.1.2** (statement): free actions satisfy base change for rings of
invariants — `∗(A, G, R, R')` for every `R'`. (KM's proof: extend scalars of the
étale torsor and use `(A ⊗ R')^G = A^G ⊗ R'` for trivializable torsors.) WIP
`sorry`; becomes provable here once A7.1.1 lands. -/
theorem fixedPointsBaseChange_bijective_of_isFreeAlgebraAction
    (hfree : IsFreeAlgebraAction G R A)
    (R' : Type u) [CommRing R'] [Algebra R R'] :
    Function.Bijective
      (fixedPointsBaseChange (G := G) (R := R) (A := A) (R' := R')) := by
  sorry

/-- **(T-Q2-A711, step 7 — the separability idempotent, in its classical form)** For a free
action of a finite group there is `e ∈ A ⊗_{Aᴳ} A` with `mult(e) = 1` and
`(1 ⊗ x − x ⊗ 1) · e = 0` for every `x` — i.e. `A` is a *separable* `Aᴳ`-algebra.

`e := ∑ᵢ aᵢ ⊗ bᵢ` is the element already built in `exists_galoisCoords`. Both properties
are read off through `torsorMul`: its `1`-component is the multiplication map, and the
annihilation identity holds because `torsorMul` is an injective ring homomorphism
(`torsorMul_bijective_of_isFreeAlgebraAction`) sending `(1 ⊗ x − x ⊗ 1) · e` to
`g ↦ (g • x − x) · δ_{g,1} = 0`. -/
theorem exists_separabilityIdempotent (hfree : IsFreeAlgebraAction G R A) :
    ∃ e : A ⊗[FixedPoints.subalgebra R A G] A,
      (Algebra.TensorProduct.lmul' (FixedPoints.subalgebra R A G) (S := A)) e = 1 ∧
      ∀ x : A, ((1 : A) ⊗ₜ[FixedPoints.subalgebra R A G] x
        - x ⊗ₜ[FixedPoints.subalgebra R A G] (1 : A)) * e = 0 := by
  classical
  haveI : Fintype G := Fintype.ofFinite G
  obtain ⟨S, hS⟩ := exists_galoisCoords G R A hfree
  refine ⟨∑ p ∈ S, p.1 ⊗ₜ[FixedPoints.subalgebra R A G] p.2, ?_, ?_⟩
  · rw [map_sum]
    simpa using hS 1
  · intro x
    refine (torsorMul_bijective_of_isFreeAlgebraAction G R A hfree).1 ?_
    rw [map_zero, map_mul, map_sub, map_sum]
    funext g
    simp only [Pi.mul_apply, Pi.sub_apply, Finset.sum_apply, Pi.zero_apply,
      MulSemiringAction.torsorMul_tmul, one_mul, smul_one, mul_one]
    rw [hS g]
    by_cases hg : g = 1
    · subst hg; simp
    · rw [if_neg hg, mul_zero]

/-- **(T-Q2-A711, step 8 — KM A7.1.1, unramifiedness; PROVEN)** For a free action of a
finite group, `A` is formally unramified over `Aᴳ`.

`Ω[A⁄Aᴳ] = I/I²` with `I = ker(A ⊗ A → A)`. For every `x`, the element
`v = 1 ⊗ x − x ⊗ 1` lies in `I`, and `1 − e ∈ I` as well (`mult(e) = 1`); the separability
identity `v · e = 0` gives `v = v · (1 − e) ∈ I·I = I²`, so `D x = 0`. Since the image of
`D` spans `Ω`, it vanishes. -/
theorem Algebra.FormallyUnramified.of_isFreeAlgebraAction (hfree : IsFreeAlgebraAction G R A) :
    Algebra.FormallyUnramified (FixedPoints.subalgebra R A G) A := by
  obtain ⟨e, hmul, hann⟩ := exists_separabilityIdempotent G R A hfree
  let B := FixedPoints.subalgebra R A G
  have hD : ∀ x : A, KaehlerDifferential.D B A x = 0 := by
    intro x
    have hmem : (1 : A) ⊗ₜ[B] x - x ⊗ₜ[B] (1:A) ∈ KaehlerDifferential.ideal B A :=
      KaehlerDifferential.one_smul_sub_smul_one_mem_ideal B x
    have h1e : (1 : A ⊗[B] A) - e ∈ KaehlerDifferential.ideal B A := by
      show _ ∈ RingHom.ker _
      rw [RingHom.mem_ker, map_sub, hmul, map_one, sub_self]
    have hfac : ((1:A) ⊗ₜ[B] x - x ⊗ₜ[B] (1:A))
        = ((1:A) ⊗ₜ[B] x - x ⊗ₜ[B] (1:A)) * ((1 : A ⊗[B] A) - e) := by
      rw [mul_sub, mul_one, hann x, sub_zero]
    have hsq : ((1:A) ⊗ₜ[B] x - x ⊗ₜ[B] (1:A)) ∈ (KaehlerDifferential.ideal B A) ^ 2 := by
      rw [pow_two, hfac]
      exact Ideal.mul_mem_mul hmem h1e
    show (KaehlerDifferential.ideal B A).toCotangent ⟨_, hmem⟩ = 0
    rw [Ideal.toCotangent_eq_zero]
    exact hsq
  have htop : (⊤ : Submodule A (Ω[A⁄B])) = ⊥ := by
    rw [← KaehlerDifferential.span_range_derivation, Submodule.span_eq_bot]
    rintro _ ⟨x, rfl⟩
    exact hD x
  refine ⟨?_⟩
  constructor
  intro a b
  have ha : a ∈ (⊥ : Submodule A (Ω[A⁄B])) := htop ▸ Submodule.mem_top
  have hb : b ∈ (⊥ : Submodule A (Ω[A⁄B])) := htop ▸ Submodule.mem_top
  rw [Submodule.mem_bot] at ha hb
  rw [ha, hb]

/-- **(T-Q2-A711, step 10 — KM A7.1.1, étaleness over a noetherian invariant ring; PROVEN)**
For a free action of a finite group with `Aᴳ` noetherian, `A` is étale over `Aᴳ`.

All three inputs of mathlib's `Algebra.Etale.of_formallyUnramified_of_flat`
(Stacks 08WD (3)⟹(1)) are now in hand:
* `FormallyUnramified` — `Algebra.FormallyUnramified.of_isFreeAlgebraAction` (separability
  idempotent, no hypotheses);
* `Module.Flat` — from `Module.Projective.of_isFreeAlgebraAction` (dual basis), again with
  no hypotheses;
* `Algebra.FinitePresentation` — the *only* place noetherianity is used: `Module.Finite`
  gives `Algebra.FiniteType`, and over a noetherian base finite type = finite presentation
  (`Algebra.FinitePresentation.of_finiteType`).

The `[IsNoetherianRing …]` hypothesis is a **drop-in scaffold** (the T-E4a-noeth precedent,
owner-authorized 2026-07-08): every consumer in the `Y(N)` pipeline has noetherian invariant
rings. Removing it is exactly the tracked gap **[A711-FP]** — algebra-level finite
presentation of a module-finite projective algebra over a non-noetherian base (Stacks
00QQ/05GH), which is what KM means by *"in the absence of noetherian hypotheses, this is
rather delicate."* Note **[A711-SM] dissolved**: mathlib derives `Smooth` from
unramified + flat + finitely presented, so "separable ⟹ formally smooth" is never needed. -/
theorem Algebra.Etale.of_isFreeAlgebraAction_of_isNoetherianRing
    [IsNoetherianRing (FixedPoints.subalgebra R A G)] (hfree : IsFreeAlgebraAction G R A) :
    Algebra.Etale (FixedPoints.subalgebra R A G) A := by
  haveI : Module.Finite (FixedPoints.subalgebra R A G) A :=
    Module.Finite.of_isFreeAlgebraAction G R A hfree
  haveI : Module.Projective (FixedPoints.subalgebra R A G) A :=
    Module.Projective.of_isFreeAlgebraAction G R A hfree
  haveI : Module.Flat (FixedPoints.subalgebra R A G) A := Module.Flat.of_projective
  haveI : Algebra.FiniteType (FixedPoints.subalgebra R A G) A := inferInstance
  haveI : Algebra.FinitePresentation (FixedPoints.subalgebra R A G) A :=
    (Algebra.FinitePresentation.of_finiteType).mp inferInstance
  haveI : Algebra.FormallyUnramified (FixedPoints.subalgebra R A G) A :=
    Algebra.FormallyUnramified.of_isFreeAlgebraAction G R A hfree
  exact Algebra.Etale.of_formallyUnramified_of_flat
