/-
Copyright (c) 2026 The AINTLIB contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: AINTLIB ModularCurves project

ForMathlib (OURS, not vendored): upstream candidate. Ticket T-Q2 (statements; the
proofs are KM A7.1.1 = SGA III Exp. V Thm 4.1 territory and are deliberately left
as WIP `sorry`s per the ticket scope).
-/
import ModularCurves.ForMathlib.InvariantBaseChange
import Mathlib.RingTheory.Etale.Basic

/-!
# Free actions and the étale-torsor theorem (Katz–Mazur A7.1.1/A7.1.2) — statements

KM's freeness condition for a finite group `G` acting on an `R`-algebra `A`
(A7.1.1): *"G acts freely on A in the sense that for any non-zero R-algebra R', and
any element g ≠ id of G, g operates without fixed points on the set
Hom_{R-alg}(A, R')."* Under this condition:

* `IsFreeAlgebraAction` — the freeness predicate;
* `MulSemiringAction.torsorMul` — the multiplication comparison
  `A ⊗[Aᴳ] A → (G → A)`, `x ⊗ y ↦ (x·(g•y))_g`;
* `Module.Finite.of_isFreeAlgebraAction`, `Algebra.Etale.of_isFreeAlgebraAction`,
  `torsorMul_bijective_of_isFreeAlgebraAction` — KM A7.1.1: `A` is a finite étale
  `G`-torsor over `Aᴳ` (three single-conclusion statements; the torsor condition is
  the bijectivity of `torsorMul`);
* `fixedPointsBaseChange_bijective_of_isFreeAlgebraAction` — KM A7.1.2: free
  actions satisfy the base-change property `∗(A, G, R)` for every `R'`.

Proofs (`sorry`d, WIP): KM defers A7.1.1 to [SGA III, Exposé V, Thm 4.1] or
[Demazure–Gabriel, III §2, 6.1] — *"In the absence of noetherian hypotheses, this is
rather delicate."* A7.1.2 follows by faithfully flat descent along `Aᴳ → A` from the
torsor triviality; it becomes provable here once A7.1.1 lands.

The stabilizer dictionary: freeness in the above sense says exactly that no
`g ≠ 1` fixes any point of `Spec A` valued in any ring — for modular curves this is
the "no elliptic points" condition under which the level quotients stay schemes.
-/

universe u

open TensorProduct

variable (G : Type*) [Group G]
variable (R A : Type u)
variable [CommRing R] [CommRing A] [Algebra R A]
variable [MulSemiringAction G A] [SMulCommClass G R A] [SMulCommClass R G A]

/-- **KM A7.1.1's freeness condition**: `G` acts freely on the `R`-algebra `A` if for
every nonzero `R`-algebra `R'` no `g ≠ 1` fixes an `R`-algebra point
`A →ₐ[R] R'`. (Verbatim: "for any non-zero R-algebra R', and any element g ≠ id of
G, g operates without fixed points on the set Hom_{R-alg}(A, R')".) -/
def IsFreeAlgebraAction : Prop :=
  ∀ g : G, g ≠ 1 → ∀ (R' : Type u) [CommRing R'] [Algebra R R'] [Nontrivial R']
    (φ : A →ₐ[R] R'), ∃ a : A, φ (g • a) ≠ φ a

/-- **(T-Q2-A711, step 1 — the Chase–Harrison–Rosenberg bridge; PROVEN)** KM's freeness
condition implies the pointwise CHR condition: at every prime `𝔭` of `A` and every `g ≠ 1`
there is `a : A` with `g • a - a ∉ 𝔭`.

Take KM's `R' := A ⧸ 𝔭` (nonzero because `𝔭` is prime) and `φ :=` the quotient map. This is
the hypothesis under which the classical Galois theory of commutative rings
(Chase–Harrison–Rosenberg, Auslander–Goldman) proves `A ⊗_{Aᴳ} A ≅ ∏_G A` and étaleness —
i.e. the route by which `torsorMul_bijective_of_isFreeAlgebraAction` and
`Algebra.Etale.of_isFreeAlgebraAction` below will be discharged, KM's own reference being
[SGA III, Exp. V, Thm 4.1] (not in `refs/`). -/
theorem chr_of_isFreeAlgebraAction (hfree : IsFreeAlgebraAction G R A)
    (p : Ideal A) [hp : p.IsPrime] (g : G) (hg : g ≠ 1) :
    ∃ a : A, g • a - a ∉ p := by
  haveI : Nontrivial (A ⧸ p) := Ideal.Quotient.nontrivial_iff.mpr hp.ne_top
  obtain ⟨a, ha⟩ := hfree g hg (A ⧸ p) (Ideal.Quotient.mkₐ R p)
  refine ⟨a, fun hmem => ha ?_⟩
  have h0 : (Ideal.Quotient.mkₐ R p) (g • a - a) = 0 := by
    rw [Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem]
    exact hmem
  rw [map_sub, sub_eq_zero] at h0
  exact h0

/-- **(T-Q2-A711, step 2)** For `g ≠ 1` the ideal generated by the "displacements"
`g • a - a` is the unit ideal: otherwise it lies in a maximal ideal, contradicting
`chr_of_isFreeAlgebraAction` there. -/
theorem span_displacement_eq_top (hfree : IsFreeAlgebraAction G R A) (g : G) (hg : g ≠ 1) :
    Ideal.span (Set.range fun a : A => g • a - a) = ⊤ := by
  by_contra hne
  obtain ⟨m, hm, hle⟩ := Ideal.exists_le_maximal _ hne
  haveI : m.IsPrime := hm.isPrime
  obtain ⟨a, ha⟩ := chr_of_isFreeAlgebraAction G R A hfree m g hg
  exact ha (hle (Ideal.subset_span ⟨a, rfl⟩))

namespace MulSemiringAction

/-- The torsor-multiplication comparison map `A ⊗[Aᴳ] A → (G → A)`,
`x ⊗ y ↦ (x · (g • y))_g` (KM A7.1.1: "the natural map A ⊗_{A^G} A → ∏_{g∈G} A,
x⊗y ↦ (⋯, x⊗g(y), ⋯)"). Its bijectivity is the `G`-torsor condition for
`Aᴳ → A`. -/
noncomputable def torsorMul :
    A ⊗[FixedPoints.subalgebra R A G] A →ₐ[FixedPoints.subalgebra R A G] (G → A) :=
  Algebra.TensorProduct.lift
    (Pi.constAlgHom (FixedPoints.subalgebra R A G) G A)
    (AlgHom.pi fun g => MulSemiringAction.toAlgHom (FixedPoints.subalgebra R A G) A g)
    (fun _ _ => Commute.all _ _)

omit [SMulCommClass R G A] in
@[simp]
theorem torsorMul_tmul (x y : A) (g : G) :
    torsorMul G R A (x ⊗ₜ y) g = x * g • y := rfl

end MulSemiringAction

variable [Finite G]

section GaloisCoordinates

variable [Fintype G] [DecidableEq G]

/-- **(T-Q2-A711, step 3)** For each `g ≠ 1` there is `w ∈ A ⊗_{Aᴳ} A` whose comparison
image vanishes at `1` and is `1` at `g`. Built from `1 = ∑ cₐ · (g • a − a)`
(`span_displacement_eq_top`) as `w = ∑ cₐ ⊗ a − cₐ·a ⊗ 1`. -/
theorem exists_torsorMul_eq_zero_one (hfree : IsFreeAlgebraAction G R A) (g : G) (hg : g ≠ 1) :
    ∃ w : A ⊗[FixedPoints.subalgebra R A G] A,
      MulSemiringAction.torsorMul G R A w 1 = 0 ∧
      MulSemiringAction.torsorMul G R A w g = 1 := by
  have h1 : (1 : A) ∈ Ideal.span (Set.range fun a : A => g • a - a) := by
    rw [span_displacement_eq_top G R A hfree g hg]; trivial
  rw [Finsupp.mem_span_range_iff_exists_finsupp] at h1
  obtain ⟨c, hc⟩ := h1
  refine ⟨c.sum fun a ca => (ca ⊗ₜ[FixedPoints.subalgebra R A G] a
      - (ca * a) ⊗ₜ[FixedPoints.subalgebra R A G] (1 : A)), ?_, ?_⟩
  · rw [Finsupp.sum, map_sum]
    simp only [Finset.sum_apply, map_sub, Pi.sub_apply, MulSemiringAction.torsorMul_tmul,
      one_smul, mul_one]
    simp
  · rw [Finsupp.sum, map_sum]
    simp only [Finset.sum_apply, map_sub, Pi.sub_apply, MulSemiringAction.torsorMul_tmul,
      smul_one, mul_one]
    rw [← hc, Finsupp.sum]
    refine Finset.sum_congr rfl fun a _ => ?_
    rw [smul_eq_mul, mul_sub]

/-- **(T-Q2-A711, step 4 — the separability idempotent / Galois coordinates)** For a free
action of a finite group there is a finite family `(aᵢ, bᵢ)` with
`∑ᵢ aᵢ · (g • bᵢ) = δ_{g,1}` for every `g ∈ G`.

Construction (Chase–Harrison–Rosenberg; the same content as SGA III Exp. V Thm 4.1 (iv),
whose proof runs through semi-local rings and Lemme 4.2 — avoided here): with `w_g` from
`exists_torsorMul_eq_zero_one`, the element `e = ∏_{g ≠ 1} (1 − w_g)` of the ring
`A ⊗_{Aᴳ} A` has comparison image the indicator of `1 ∈ G`, because `torsorMul` is a ring
homomorphism into the product ring `G → A`. Writing `e` as a finite sum of pure tensors
(`TensorProduct.exists_finset`) reads off the coordinates. -/
theorem exists_galoisCoords (hfree : IsFreeAlgebraAction G R A) :
    ∃ S : Finset (A × A), ∀ g : G,
      (∑ p ∈ S, p.1 * (g • p.2)) = if g = 1 then 1 else 0 := by
  classical
  choose w hw1 hwg using fun (g : G) (hg : g ≠ 1) => exists_torsorMul_eq_zero_one G R A hfree g hg
  set e : A ⊗[FixedPoints.subalgebra R A G] A :=
    ∏ h ∈ (Finset.univ.erase (1 : G)).attach,
      (1 - w h.1 (Finset.ne_of_mem_erase h.2)) with he
  have hev : ∀ g : G, MulSemiringAction.torsorMul G R A e g = if g = 1 then 1 else 0 := by
    intro g
    have hprod : MulSemiringAction.torsorMul G R A e g
        = ∏ h ∈ (Finset.univ.erase (1 : G)).attach,
            (1 - MulSemiringAction.torsorMul G R A (w h.1 (Finset.ne_of_mem_erase h.2)) g) := by
      rw [he, map_prod]
      simp [Finset.prod_apply]
    rw [hprod]
    by_cases hg : g = 1
    · subst hg
      refine (Finset.prod_eq_one fun h _ => ?_).trans (by simp)
      rw [hw1 h.1 (Finset.ne_of_mem_erase h.2), sub_zero]
    · rw [if_neg hg]
      refine Finset.prod_eq_zero (i := ⟨g, Finset.mem_erase.mpr ⟨hg, Finset.mem_univ g⟩⟩)
        (Finset.mem_attach _ _) ?_
      rw [hwg g hg, sub_self]
  obtain ⟨S, hS⟩ := TensorProduct.exists_finset e
  refine ⟨S, fun g => ?_⟩
  have hg := hev g
  rw [hS, map_sum] at hg
  simpa [Finset.sum_apply, MulSemiringAction.torsorMul_tmul] using hg

end GaloisCoordinates

/-- **KM A7.1.1, finiteness part** (statement; proof: SGA III Exp. V Thm 4.1):
for a free action, `A` is finite over the invariants. WIP `sorry` per ticket
T-Q2's statement-only scope. -/
theorem Module.Finite.of_isFreeAlgebraAction (hfree : IsFreeAlgebraAction G R A) :
    Module.Finite (FixedPoints.subalgebra R A G) A := by
  sorry

/-- **KM A7.1.1, étaleness part** (statement; proof: SGA III Exp. V Thm 4.1;
"In the absence of noetherian hypotheses, this is rather delicate"): for a free
action, `A` is étale over the invariants. WIP `sorry` per ticket T-Q2's
statement-only scope. -/
theorem Algebra.Etale.of_isFreeAlgebraAction (hfree : IsFreeAlgebraAction G R A) :
    Algebra.Etale (FixedPoints.subalgebra R A G) A := by
  sorry

/-- The `G`-trace `a ↦ ∑_g g • a`, valued in the invariants. -/
def traceInvariants [Fintype G] (a : A) : FixedPoints.subalgebra R A G :=
  ⟨∑ g : G, g • a, by
    intro h
    show h • (∑ g : G, g • a) = ∑ g : G, g • a
    rw [Finset.smul_sum]
    have hre : ∀ g : G, h • (g • a) = (h * g) • a := fun g => (mul_smul h g a).symm
    simp only [hre]
    exact Fintype.sum_bijective (h * ·) (Group.mulLeft_bijective h) _ _ (fun _ => rfl)⟩

/-- The candidate inverse of `torsorMul`, built from Galois coordinates `S`:
`x ↦ ∑ᵢ aᵢ ⊗ (∑_g g⁻¹ • (x g · bᵢ))`. -/
noncomputable def galoisInv [Fintype G] (S : Finset (A × A)) (x : G → A) :
    A ⊗[FixedPoints.subalgebra R A G] A :=
  ∑ p ∈ S, p.1 ⊗ₜ[FixedPoints.subalgebra R A G] (∑ g : G, g⁻¹ • (x g * p.2))

/-- **(T-Q2-A711, step 5 — KM A7.1.1, torsor part; PROVEN)** For a free action of a finite
group the multiplication comparison `A ⊗[Aᴳ] A ≅ ∏_G A` is bijective — `Spec A` is a
`G`-torsor over `Spec Aᴳ`.

This is SGA III Exp. V Thm 4.1 (iv) — *"`X₁ ⟶ X₀ ×_Y X₀` est un isomorphisme"* — obtained
by the Chase–Harrison–Rosenberg route: the Galois coordinates of `exists_galoisCoords`
give an explicit two-sided inverse `galoisInv`, so neither SGA's semi-local reduction, nor
its Lemme 4.2, nor its faithfully-flat residue-field enlargement is needed (none of the
three has a mathlib substrate — there is no `IsSemilocalRing`). No finiteness of `A` over
`Aᴳ` is used either.

`galoisInv ∘ torsorMul = id` is where the trace enters: on a pure tensor `u ⊗ v` the inner
sum is `tr(u · bᵢ) · v` with `tr(u · bᵢ)` invariant, so it crosses the tensor to give
`(∑ᵢ tr(u · bᵢ) · aᵢ) ⊗ v = u ⊗ v` by the coordinate identity again. -/
theorem torsorMul_bijective_of_isFreeAlgebraAction [Fintype G] [DecidableEq G]
    (hfree : IsFreeAlgebraAction G R A) :
    Function.Bijective (MulSemiringAction.torsorMul G R A) := by
  classical
  obtain ⟨S, hS⟩ := exists_galoisCoords G R A hfree
  -- `galoisInv S` is a right inverse
  have hright : ∀ x : G → A,
      MulSemiringAction.torsorMul G R A (galoisInv G R A S x) = x := by
    intro x
    funext h
    rw [galoisInv, map_sum]
    simp only [Finset.sum_apply, MulSemiringAction.torsorMul_tmul, Finset.smul_sum,
      Finset.mul_sum]
    rw [Finset.sum_comm]
    have hterm : ∀ g : G, (∑ p ∈ S, p.1 * (h • g⁻¹ • (x g * p.2)))
        = ((h * g⁻¹) • x g) * (if (h * g⁻¹) = 1 then 1 else 0) := by
      intro g
      rw [← hS (h * g⁻¹), Finset.mul_sum]
      refine Finset.sum_congr rfl fun p _ => ?_
      rw [← mul_smul, smul_mul']
      ring
    simp only [hterm]
    rw [Finset.sum_eq_single h]
    · simp
    · intro g _ hgh
      have hne : h * g⁻¹ ≠ 1 := fun hc => hgh (mul_inv_eq_one.mp hc).symm
      simp [hne]
    · intro hc
      exact absurd (Finset.mem_univ h) hc
  -- `galoisInv S` is additive, so it suffices to check the left inverse on pure tensors
  have hadd : ∀ x y : G → A, galoisInv G R A S (x + y)
      = galoisInv G R A S x + galoisInv G R A S y := by
    intro x y
    rw [galoisInv, galoisInv, galoisInv, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun p _ => ?_
    rw [← TensorProduct.tmul_add, ← Finset.sum_add_distrib]
    refine congrArg _ (Finset.sum_congr rfl fun g _ => ?_)
    rw [Pi.add_apply, add_mul, smul_add]
  have hleft : ∀ y : A ⊗[FixedPoints.subalgebra R A G] A,
      galoisInv G R A S (MulSemiringAction.torsorMul G R A y) = y := by
    intro y
    induction y using TensorProduct.induction_on with
    | zero => simp [galoisInv]
    | add y₁ y₂ h₁ h₂ => rw [map_add, hadd, h₁, h₂]
    | tmul u v =>
      rw [galoisInv]
      have hterm : ∀ p : A × A,
          (∑ g : G, g⁻¹ • ((MulSemiringAction.torsorMul G R A
              (u ⊗ₜ[FixedPoints.subalgebra R A G] v) : G → A) g * p.2))
            = (traceInvariants G R A (u * p.2) : A) * v := by
        intro p
        have hinner : ∀ g : G, g⁻¹ • ((MulSemiringAction.torsorMul G R A
            (u ⊗ₜ[FixedPoints.subalgebra R A G] v) : G → A) g * p.2)
              = (g⁻¹ • (u * p.2)) * v := by
          intro g
          rw [MulSemiringAction.torsorMul_tmul,
            show u * g • v * p.2 = (u * p.2) * (g • v) by ring, smul_mul', smul_smul,
            inv_mul_cancel, one_smul]
        simp only [hinner, ← Finset.sum_mul]
        congr 1
        show (∑ g : G, g⁻¹ • (u * p.2)) = ∑ g : G, g • (u * p.2)
        exact Fintype.sum_bijective (·⁻¹) (Equiv.inv G).bijective _ _ (fun _ => rfl)
      simp only [hterm]
      have hmove : ∀ p : A × A,
          p.1 ⊗ₜ[FixedPoints.subalgebra R A G] ((traceInvariants G R A (u * p.2) : A) * v)
            = ((traceInvariants G R A (u * p.2) : A) * p.1)
                ⊗ₜ[FixedPoints.subalgebra R A G] v := by
        intro p
        show p.1 ⊗ₜ[FixedPoints.subalgebra R A G]
            ((traceInvariants G R A (u * p.2)) • v) = _
        rw [TensorProduct.tmul_smul]
        rfl
      simp only [hmove]
      rw [← TensorProduct.sum_tmul]
      congr 1
      show (∑ p ∈ S, (∑ g : G, g • (u * p.2)) * p.1) = u
      have hswap : (∑ p ∈ S, (∑ g : G, g • (u * p.2)) * p.1)
          = ∑ g : G, (g • u) * (∑ p ∈ S, p.1 * (g • p.2)) := by
        simp only [Finset.sum_mul]
        rw [Finset.sum_comm]
        refine Finset.sum_congr rfl fun g _ => ?_
        rw [Finset.mul_sum]
        refine Finset.sum_congr rfl fun p _ => ?_
        rw [smul_mul']
        ring
      rw [hswap, Finset.sum_eq_single (1 : G)]
      · rw [hS (1 : G)]; simp
      · intro g _ hg; rw [hS g, if_neg hg, mul_zero]
      · intro hc; exact absurd (Finset.mem_univ (1 : G)) hc
  exact ⟨Function.LeftInverse.injective hleft, fun x => ⟨galoisInv G R A S x, hright x⟩⟩

/-- **KM A7.1.2** (statement): free actions satisfy base change for rings of
invariants — `∗(A, G, R, R')` for every `R'`. (KM's proof: extend scalars of the
étale torsor and use `(A ⊗ R')^G = A^G ⊗ R'` for trivializable torsors.) WIP
`sorry`; becomes provable here once A7.1.1 lands. -/
theorem fixedPointsBaseChange_bijective_of_isFreeAlgebraAction
    (hfree : IsFreeAlgebraAction G R A)
    (R' : Type u) [CommRing R'] [Algebra R R'] :
    Function.Bijective
      (fixedPointsBaseChange (G := G) (R := R) (A := A) (R' := R')) := by
  sorry
