/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import ModularCurves.ForMathlib.RegularLocalDomain

/-!
# Cutting down the Krull dimension by finitely many equations (T-SMOOTH-REG brick 1)

Krull's principal ideal theorem gives the *upper* bound `dim R/xR ≤ dim R`; the bound the
smoothness argument needs is the *lower* one:

> `dim R ≤ dim (R ⧸ I) + n` whenever `I` is generated by `n` elements of `𝔪`.

The one-element case is `ringKrullDim_le_ringKrullDim_quotient_span_singleton_succ`
(`ForMathlib/RegularLocalDomain.lean`, itself mathlib's
`ringKrullDim_le_ringKrullDim_quotSMulTop_succ`). This file iterates it over a finite
generating set. It is the step that turns "`S` is a quotient of `k[x_1, …, x_{n+m}]` by `m`
equations" into "`dim S_𝔪 ≥ n`".

Stacks 00KW / Matsumura Thm. 13.6.
-/

universe u

open IsLocalRing

namespace ModularCurves

/-- **(T-SMOOTH-REG brick 1, the induction)** In a Noetherian local ring, quotienting by an
ideal generated by at most `n` elements of the maximal ideal drops the Krull dimension by at
most `n`. The ring is universally quantified *inside* the induction so that the step can
pass to the intermediate quotient `R ⧸ (x)`. -/
theorem ringKrullDim_le_ringKrullDim_quotient_span_add_card :
    ∀ (n : ℕ) (R : Type u) [CommRing R] [IsNoetherianRing R] [IsLocalRing R]
      (s : Finset R), (↑s : Set R) ⊆ (maximalIdeal R : Set R) → s.card ≤ n →
      ringKrullDim R ≤ ringKrullDim (R ⧸ Ideal.span (↑s : Set R)) + n := by
  intro n
  induction n with
  | zero =>
    intro R _ _ _ s hs hcard
    have hempty : s = ∅ := Finset.card_eq_zero.mp (Nat.le_zero.mp hcard)
    subst hempty
    have hbot : Ideal.span ((∅ : Finset R) : Set R) = ⊥ := by simp
    have he : ringKrullDim (R ⧸ Ideal.span ((∅ : Finset R) : Set R)) = ringKrullDim R :=
      ringKrullDim_eq_of_ringEquiv
        ((Ideal.quotEquivOfEq hbot).trans (RingEquiv.quotientBot R))
    rw [he, Nat.cast_zero, add_zero]
  | succ n ih =>
    intro R _ _ _ s hs hcard
    classical
    rcases Finset.eq_empty_or_nonempty s with rfl | ⟨x, hxs⟩
    · have hbot : Ideal.span ((∅ : Finset R) : Set R) = ⊥ := by simp
      have he : ringKrullDim (R ⧸ Ideal.span ((∅ : Finset R) : Set R)) = ringKrullDim R :=
        ringKrullDim_eq_of_ringEquiv
          ((Ideal.quotEquivOfEq hbot).trans (RingEquiv.quotientBot R))
      rw [he]
      exact le_add_of_nonneg_right (by positivity)
    · set t : Finset R := s.erase x with ht
      have hst : s = insert x t := by rw [ht, Finset.insert_erase hxs]
      have hxm : x ∈ maximalIdeal R := hs (by exact_mod_cast hxs)
      have htm : (↑t : Set R) ⊆ (maximalIdeal R : Set R) :=
        fun y hy => hs (Finset.erase_subset _ _ (by exact_mod_cast hy))
      have htcard : t.card ≤ n := by
        have hpos : 1 ≤ s.card := Finset.card_pos.mpr ⟨x, hxs⟩
        rw [ht, Finset.card_erase_of_mem hxs]
        omega
      -- the intermediate quotient `Q = R ⧸ (x)` is again Noetherian local
      haveI : Nontrivial (R ⧸ Ideal.span ({x} : Set R)) :=
        Ideal.Quotient.nontrivial_iff.mpr (by
          refine fun htop => (maximalIdeal.isMaximal R).ne_top ?_
          rw [eq_top_iff, ← htop]
          exact Ideal.span_le.mpr (by simpa using hxm))
      haveI : IsLocalRing (R ⧸ Ideal.span ({x} : Set R)) :=
        IsLocalRing.of_surjective' (Ideal.Quotient.mk _) Ideal.Quotient.mk_surjective
      set t' : Finset (R ⧸ Ideal.span ({x} : Set R)) :=
        t.image (Ideal.Quotient.mk (Ideal.span ({x} : Set R))) with ht'
      have ht'm : (↑t' : Set (R ⧸ Ideal.span ({x} : Set R))) ⊆
          (maximalIdeal (R ⧸ Ideal.span ({x} : Set R)) : Set _) := by
        intro y hy
        simp only [ht', Finset.coe_image, Set.mem_image, Finset.mem_coe] at hy
        obtain ⟨z, hz, rfl⟩ := hy
        rw [SetLike.mem_coe, ← IsLocalRing.map_maximalIdeal_of_surjective
          (Ideal.Quotient.mk (Ideal.span ({x} : Set R))) Ideal.Quotient.mk_surjective]
        exact Ideal.mem_map_of_mem _ (htm (by exact_mod_cast hz))
      have hstep := ih (R ⧸ Ideal.span ({x} : Set R)) t' ht'm
        (le_trans Finset.card_image_le htcard)
      -- identify `(R ⧸ (x)) ⧸ (t')` with `R ⧸ span s`
      have hmapspan : Ideal.span (↑t' : Set (R ⧸ Ideal.span ({x} : Set R))) =
          (Ideal.span (↑t : Set R)).map (Ideal.Quotient.mk (Ideal.span ({x} : Set R))) := by
        rw [Ideal.map_span, ht', Finset.coe_image]
      have hsup : Ideal.span ({x} : Set R) ⊔ Ideal.span (↑t : Set R) =
          Ideal.span (↑s : Set R) := by
        rw [← Ideal.span_union, hst, Finset.coe_insert, Set.insert_eq]
      have hiso : ringKrullDim ((R ⧸ Ideal.span ({x} : Set R)) ⧸
            Ideal.span (↑t' : Set (R ⧸ Ideal.span ({x} : Set R)))) =
          ringKrullDim (R ⧸ Ideal.span (↑s : Set R)) := by
        rw [hmapspan]
        refine Eq.trans (ringKrullDim_eq_of_ringEquiv
          (DoubleQuot.quotQuotEquivQuotSup _ _)) ?_
        rw [hsup]
      rw [hiso] at hstep
      calc ringKrullDim R
          ≤ ringKrullDim (R ⧸ Ideal.span ({x} : Set R)) + 1 :=
            ringKrullDim_le_ringKrullDim_quotient_span_singleton_succ R hxm
        _ ≤ (ringKrullDim (R ⧸ Ideal.span (↑s : Set R)) + n) + 1 := by
            gcongr
        _ = ringKrullDim (R ⧸ Ideal.span (↑s : Set R)) + (n + 1 : ℕ) := by
            push_cast
            rw [add_assoc]

end ModularCurves
