/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import ModularCurves.ForMathlib.RegularLocalDomain

/-!
# Cutting down the Krull dimension by finitely many equations (T-SMOOTH-REG brick 1)

Krull's principal ideal theorem gives the *upper* bound `dim R/xR ≤ dim R`; the bound the
smoothness argument needs is the *lower* one:

> `dim R ≤ dim (R ⧸ I) + n` whenever `I` is generated by `n` elements of `𝔪`.

The one-element case is `ringKrullDim_le_ringKrullDim_quotient_span_singleton_succ`
(`ForMathlib/RegularLocalDomain.lean`, itself mathlib's
`ringKrullDim_le_ringKrullDim_quotSMulTop_succ`). This file iterates it over a finite
generating set. It is the step that turns "`S` is a quotient of `k[x_1, …, x_{n+m}]` by `m`
equations" into "`dim S_𝔪 ≥ n`".

Stacks 00KW / Matsumura Thm. 13.6.
-/

universe u

open IsLocalRing

namespace ModularCurves

/-- **(T-SMOOTH-REG brick 1, the induction)** In a Noetherian local ring, quotienting by an
ideal generated by at most `n` elements of the maximal ideal drops the Krull dimension by at
most `n`. The ring is universally quantified *inside* the induction so that the step can
pass to the intermediate quotient `R ⧸ (x)`. -/
theorem ringKrullDim_le_ringKrullDim_quotient_span_add_card :
    ∀ (n : ℕ) (R : Type u) [CommRing R] [IsNoetherianRing R] [IsLocalRing R]
      (s : Finset R), (↑s : Set R) ⊆ (maximalIdeal R : Set R) → s.card ≤ n →
      ringKrullDim R ≤ ringKrullDim (R ⧸ Ideal.span (↑s : Set R)) + n := by
  intro n
  induction n with
  | zero =>
    intro R _ _ _ s hs hcard
    have hempty : s = ∅ := Finset.card_eq_zero.mp (Nat.le_zero.mp hcard)
    subst hempty
    have hbot : Ideal.span ((∅ : Finset R) : Set R) = ⊥ := by simp
    have he : ringKrullDim (R ⧸ Ideal.span ((∅ : Finset R) : Set R)) = ringKrullDim R :=
      ringKrullDim_eq_of_ringEquiv
        ((Ideal.quotEquivOfEq hbot).trans (RingEquiv.quotientBot R))
    rw [he, Nat.cast_zero, add_zero]
  | succ n ih =>
    intro R _ _ _ s hs hcard
    classical
    rcases Finset.eq_empty_or_nonempty s with rfl | ⟨x, hxs⟩
    · have hbot : Ideal.span ((∅ : Finset R) : Set R) = ⊥ := by simp
      have he : ringKrullDim (R ⧸ Ideal.span ((∅ : Finset R) : Set R)) = ringKrullDim R :=
        ringKrullDim_eq_of_ringEquiv
          ((Ideal.quotEquivOfEq hbot).trans (RingEquiv.quotientBot R))
      rw [he]
      exact le_add_of_nonneg_right (by positivity)
    · set t : Finset R := s.erase x with ht
      have hst : s = insert x t := by rw [ht, Finset.insert_erase hxs]
      have hxm : x ∈ maximalIdeal R := hs (by exact_mod_cast hxs)
      have htm : (↑t : Set R) ⊆ (maximalIdeal R : Set R) :=
        fun y hy => hs (Finset.erase_subset _ _ (by exact_mod_cast hy))
      have htcard : t.card ≤ n := by
        have hpos : 1 ≤ s.card := Finset.card_pos.mpr ⟨x, hxs⟩
        rw [ht, Finset.card_erase_of_mem hxs]
        omega
      -- the intermediate quotient `Q = R ⧸ (x)` is again Noetherian local
      haveI : Nontrivial (R ⧸ Ideal.span ({x} : Set R)) :=
        Ideal.Quotient.nontrivial_iff.mpr (by
          refine fun htop => (maximalIdeal.isMaximal R).ne_top ?_
          rw [eq_top_iff, ← htop]
          exact Ideal.span_le.mpr (by simpa using hxm))
      haveI : IsLocalRing (R ⧸ Ideal.span ({x} : Set R)) :=
        IsLocalRing.of_surjective' (Ideal.Quotient.mk _) Ideal.Quotient.mk_surjective
      set t' : Finset (R ⧸ Ideal.span ({x} : Set R)) :=
        t.image (Ideal.Quotient.mk (Ideal.span ({x} : Set R))) with ht'
      have ht'm : (↑t' : Set (R ⧸ Ideal.span ({x} : Set R))) ⊆
          (maximalIdeal (R ⧸ Ideal.span ({x} : Set R)) : Set _) := by
        intro y hy
        simp only [ht', Finset.coe_image, Set.mem_image, Finset.mem_coe] at hy
        obtain ⟨z, hz, rfl⟩ := hy
        rw [SetLike.mem_coe, ← IsLocalRing.map_maximalIdeal_of_surjective
          (Ideal.Quotient.mk (Ideal.span ({x} : Set R))) Ideal.Quotient.mk_surjective]
        exact Ideal.mem_map_of_mem _ (htm (by exact_mod_cast hz))
      have hstep := ih (R ⧸ Ideal.span ({x} : Set R)) t' ht'm
        (le_trans Finset.card_image_le htcard)
      -- identify `(R ⧸ (x)) ⧸ (t')` with `R ⧸ span s`
      have hmapspan : Ideal.span (↑t' : Set (R ⧸ Ideal.span ({x} : Set R))) =
          (Ideal.span (↑t : Set R)).map (Ideal.Quotient.mk (Ideal.span ({x} : Set R))) := by
        rw [Ideal.map_span, ht', Finset.coe_image]
      have hsup : Ideal.span ({x} : Set R) ⊔ Ideal.span (↑t : Set R) =
          Ideal.span (↑s : Set R) := by
        rw [← Ideal.span_union, hst, Finset.coe_insert, Set.insert_eq]
      have hiso : ringKrullDim ((R ⧸ Ideal.span ({x} : Set R)) ⧸
            Ideal.span (↑t' : Set (R ⧸ Ideal.span ({x} : Set R)))) =
          ringKrullDim (R ⧸ Ideal.span (↑s : Set R)) := by
        rw [hmapspan]
        refine Eq.trans (ringKrullDim_eq_of_ringEquiv
          (DoubleQuot.quotQuotEquivQuotSup _ _)) ?_
        rw [hsup]
      rw [hiso] at hstep
      calc ringKrullDim R
          ≤ ringKrullDim (R ⧸ Ideal.span ({x} : Set R)) + 1 :=
            ringKrullDim_le_ringKrullDim_quotient_span_singleton_succ R hxm
        _ ≤ (ringKrullDim (R ⧸ Ideal.span (↑s : Set R)) + n) + 1 := by
            gcongr
        _ = ringKrullDim (R ⧸ Ideal.span (↑s : Set R)) + (n + 1 : ℕ) := by
            push_cast
            rw [add_assoc]


/-- **(T-SMOOTH-REG brick 3 ★)** Cutting a Noetherian ring by an ideal generated by `#s`
elements drops the height of a prime by at most `#s`: if `𝔪` is a prime of `P ⧸ I` and
`𝔮 = 𝔪 ∩ P` is its contraction, then `height 𝔮 ≤ height 𝔪 + #s`.

This is the local form of `ringKrullDim_le_ringKrullDim_quotient_span_add_card`, obtained
by localizing at `𝔮`: `P_𝔮 ⧸ I·P_𝔮` is the localization of `P ⧸ I` at `𝔪`
(`IsLocalization.of_surjective`), and the Krull dimensions of the two local rings are the
two heights (`IsLocalization.AtPrime.ringKrullDim_eq_height`). -/
theorem height_comap_le_height_add_card {P : Type u} [CommRing P] [IsNoetherianRing P]
    {I : Ideal P} {s : Finset P} (hs : Ideal.span (↑s : Set P) = I)
    (𝔪 : Ideal (P ⧸ I)) [h𝔪 : 𝔪.IsPrime] :
    (𝔪.comap (Ideal.Quotient.mk I)).height ≤ 𝔪.height + s.card := by
  classical
  set 𝔮 : Ideal P := 𝔪.comap (Ideal.Quotient.mk I) with h𝔮def
  haveI : 𝔮.IsPrime := Ideal.comap_isPrime _ _
  have hI𝔮 : I ≤ 𝔮 := by
    intro x hx
    show Ideal.Quotient.mk I x ∈ 𝔪
    rw [Ideal.Quotient.eq_zero_iff_mem.mpr hx]
    exact Submodule.zero_mem _
  set B := Localization.AtPrime 𝔮 with hBdef
  haveI : IsNoetherianRing B := IsLocalization.isNoetherianRing 𝔮.primeCompl B inferInstance
  -- the images of `s` generate `I·B` and lie in the maximal ideal
  set s' : Finset B := s.image (algebraMap P B) with hs'def
  have hmax : 𝔮.map (algebraMap P B) = IsLocalRing.maximalIdeal B :=
    IsLocalization.AtPrime.map_eq_maximalIdeal 𝔮 B
  have hs'sub : (↑s' : Set B) ⊆ (IsLocalRing.maximalIdeal B : Set B) := by
    intro y hy
    simp only [hs'def, Finset.coe_image, Set.mem_image, Finset.mem_coe] at hy
    obtain ⟨x, hx, rfl⟩ := hy
    rw [SetLike.mem_coe, ← hmax]
    exact Ideal.mem_map_of_mem _ (hI𝔮 (hs ▸ Ideal.subset_span (by exact_mod_cast hx)))
  have hspan' : Ideal.span (↑s' : Set B) = I.map (algebraMap P B) := by
    rw [← hs, Ideal.map_span, hs'def, Finset.coe_image]
  -- brick 1 at `B`
  have h1 := ringKrullDim_le_ringKrullDim_quotient_span_add_card s'.card B s' hs'sub le_rfl
  rw [hspan'] at h1
  -- the two Krull dimensions are the two heights
  have hdimB : ringKrullDim B = (𝔮.height : WithBot ℕ∞) :=
    IsLocalization.AtPrime.ringKrullDim_eq_height 𝔮 B
  have hsub : Algebra.algebraMapSubmonoid (P ⧸ I) 𝔮.primeCompl = 𝔪.primeCompl := by
    refine Submonoid.ext fun y => ?_
    constructor
    · rintro ⟨z, hz, hzy⟩
      intro hmem
      refine hz ?_
      show Ideal.Quotient.mk I z ∈ 𝔪
      rw [show Ideal.Quotient.mk I z = y from hzy]
      exact hmem
    · intro hy
      obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective y
      exact ⟨x, hy, rfl⟩
  haveI : IsLocalization 𝔪.primeCompl (B ⧸ I.map (algebraMap P B)) :=
    hsub ▸ (inferInstance :
      IsLocalization (Algebra.algebraMapSubmonoid (P ⧸ I) 𝔮.primeCompl)
        (B ⧸ I.map (algebraMap P B)))
  have hdimQ : ringKrullDim (B ⧸ I.map (algebraMap P B)) = (𝔪.height : WithBot ℕ∞) :=
    IsLocalization.AtPrime.ringKrullDim_eq_height 𝔪 _
  rw [hdimB, hdimQ] at h1
  have hcard : (s'.card : WithBot ℕ∞) ≤ (s.card : WithBot ℕ∞) := by
    exact_mod_cast Nat.cast_le (α := ℕ∞).mpr (Finset.card_image_le (f := algebraMap P B))
  have : (𝔮.height : WithBot ℕ∞) ≤ (𝔪.height : WithBot ℕ∞) + (s.card : WithBot ℕ∞) :=
    le_trans h1 (by gcongr)
  exact_mod_cast this

/-- Heights are invariant under a ring isomorphism. -/
theorem height_comap_ringEquiv {R S : Type u} [CommRing R] [CommRing S] (e : R ≃+* S)
    (J : Ideal S) [hJ : J.IsPrime] :
    (J.comap (e : R →+* S)).height = J.height := by
  haveI : (J.comap (e : R →+* S)).IsPrime := Ideal.comap_isPrime _ _
  have h := Order.height_orderIso (PrimeSpectrum.comapEquiv e.symm) ⟨J, hJ⟩
  have hl : ((PrimeSpectrum.comapEquiv e.symm) ⟨J, hJ⟩ : PrimeSpectrum R) =
      ⟨J.comap (e : R →+* S), inferInstance⟩ := rfl
  rw [hl] at h
  exact (PrimeSpectrum.height_eq_orderHeight
      (⟨J.comap (e : R →+* S), inferInstance⟩ : PrimeSpectrum R)).trans
    (h.trans (PrimeSpectrum.height_eq_orderHeight (⟨J, hJ⟩ : PrimeSpectrum S)).symm)

/-- **(T-SMOOTH-REG brick 3', the surjection form)** For a surjection `f : P ↠ A` whose
kernel is generated by `#s` elements, `height (𝔪 ∩ P) ≤ height 𝔪 + #s`. -/
theorem height_comap_le_height_add_card_of_surjective {P A : Type u} [CommRing P]
    [CommRing A] [IsNoetherianRing P] (f : P →+* A) (hf : Function.Surjective f)
    {s : Finset P} (hs : Ideal.span (↑s : Set P) = RingHom.ker f) (𝔪 : Ideal A)
    [𝔪.IsPrime] : (𝔪.comap f).height ≤ 𝔪.height + s.card := by
  classical
  set e : P ⧸ RingHom.ker f ≃+* A := RingHom.quotientKerEquivOfSurjective hf with he
  set 𝔪' : Ideal (P ⧸ RingHom.ker f) := 𝔪.comap (e : (P ⧸ RingHom.ker f) →+* A) with h𝔪'
  haveI : 𝔪'.IsPrime := Ideal.comap_isPrime _ _
  have hmk : (e : (P ⧸ RingHom.ker f) →+* A).comp (Ideal.Quotient.mk (RingHom.ker f)) = f :=
    RingHom.ext fun x => rfl
  have h3 : 𝔪'.comap (Ideal.Quotient.mk (RingHom.ker f)) = 𝔪.comap f := by
    rw [h𝔪', Ideal.comap_comap, hmk]
  have h1 := height_comap_le_height_add_card hs 𝔪'
  rw [h3, height_comap_ringEquiv e 𝔪] at h1
  exact h1

end ModularCurves
