/-
Copyright (c) 2026 The AINTLIB contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: AINTLIB ModularCurves project

ForMathlib (OURS, not vendored): upstream candidate.
-/
import ModularCurves.ForMathlib.MvPolynomialProjectiveClosure

/-!
# Coordinate hyperplanes in projective space

This file constructs the coordinate hyperplane `X_j = 0` as the `Proj` of the
corresponding homogeneous quotient. Its ideal sheaf will be the concrete model
of `O(-1)` used in the projective-space cohomology calculation.
-/

namespace MvPolynomial

open AlgebraicGeometry HomogeneousIdeal

noncomputable section

universe u

variable {R : Type u} {σ : Type*} [CommRing R]

attribute [local instance] MvPolynomial.gradedAlgebra

/-- The homogeneous ideal generated by one projective coordinate. -/
def coordinateHyperplaneIdeal (j : σ) :
    HomogeneousIdeal (homogeneousSubmodule σ R) :=
  ⟨Ideal.span {X j}, Ideal.homogeneous_span _ _ fun x hx => by
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact ⟨1, X_mem_homogeneousSubmodule_one R j⟩⟩

@[simp]
lemma coordinateHyperplaneIdeal_toIdeal (j : σ) :
    (coordinateHyperplaneIdeal (R := R) j).toIdeal = Ideal.span {X j} :=
  rfl

/-- The coordinate hyperplane as a projective homogeneous quotient. -/
abbrev coordinateHyperplane (j : σ) :=
  Proj (quotientGrading (coordinateHyperplaneIdeal (R := R) j))

/-- The coordinate hyperplane embedded in polynomial projective space. -/
def coordinateHyperplaneι (j : σ) :
    coordinateHyperplane (R := R) j ⟶ Proj (homogeneousSubmodule σ R) :=
  Proj.map (quotientGradingHom (coordinateHyperplaneIdeal (R := R) j))
    (quotientGradingHom_irrelevant_le (coordinateHyperplaneIdeal (R := R) j))

/-- A coordinate hyperplane is a closed subscheme of polynomial projective space. -/
lemma coordinateHyperplaneι_isClosedImmersion (j : σ) :
    IsClosedImmersion (coordinateHyperplaneι (R := R) j) :=
  isClosedImmersion_proj_map_quotientGradingHom
    (coordinateHyperplaneIdeal (R := R) j)

end

end MvPolynomial
