/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.Ideal.MinimalPrime.Basic
import Mathlib.RingTheory.Nakayama
import Mathlib.RingTheory.Ideal.MinimalPrime.Noetherian
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Square
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.RingHom.Flat
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.KrullDimension.Regular

/-!
# Regular local rings are domains (T-REG)

**(T-G4a-SUB2 prerequisite.)** Mathlib currently ships only
`Mathlib/RingTheory/RegularLocalRing/Defs.lean` — the definition
`(maximalIdeal R).spanFinrank = ringKrullDim R`, the cotangent-space reformulation, and
transport along ring equivalences. Nothing about the *theory* of regular local rings is
available; in particular `IsRegularLocalRing R → IsDomain R` (Matsumura, *Commutative Ring
Theory*, Thm 14.3) is absent, and it is exactly what the geometric-irreducibility leaf
`irreducibleSpace_of_connectedSpace_of_smooth` needs (smooth ⟹ regular ⟹ the local rings
are domains ⟹ the irreducible components are disjoint).

This file develops the pieces, bottom-up. The argument is the classical induction on
`dim R`:

* `dim R = 0` — then `𝔪` is generated by `0` elements, so `𝔪 = ⊥` and `R` is a field.
* `dim R > 0` — pick `x ∈ 𝔪 \ (𝔪² ∪ ⋃ᵢ 𝔭ᵢ)` (`𝔭ᵢ` the minimal primes) by prime avoidance;
  `R/xR` is regular local of dimension `dim R − 1`, hence a domain by induction, hence
  `xR` is prime; a minimal prime `𝔭 ⊆ xR` satisfies `𝔭 = x𝔭` (as `x ∉ 𝔭`), so `𝔭 = ⊥` by
  Nakayama and `R` is a domain.

All four steps are formalised here; the file culminates in
`ModularCurves.IsRegularLocalRing.isDomain`.
-/

universe u

open IsLocalRing Pointwise

namespace ModularCurves

/-- **(T-REG-1)** A regular local ring of Krull dimension `0` is a field: regularity says
`𝔪` is generated by `dim R = 0` elements, i.e. `𝔪 = ⊥`. -/
theorem isField_of_isRegularLocalRing_of_ringKrullDim_eq_zero (R : Type u) [CommRing R]
    [IsRegularLocalRing R] (h : ringKrullDim R = 0) : IsField R := by
  have hfg : (maximalIdeal R).FG := IsNoetherian.noetherian _
  have hspan : (maximalIdeal R).spanFinrank = 0 := by
    have := IsRegularLocalRing.spanFinrank_maximalIdeal (R := R)
    rw [h] at this
    exact_mod_cast this
  exact isField_iff_maximalIdeal_eq.mpr
    ((Submodule.spanFinrank_eq_zero_iff_eq_bot hfg).mp hspan)

/-- **(T-REG-1')** Hence a regular local ring of Krull dimension `0` is a domain. -/
theorem isDomain_of_isRegularLocalRing_of_ringKrullDim_eq_zero (R : Type u) [CommRing R]
    [IsRegularLocalRing R] (h : ringKrullDim R = 0) : IsDomain R :=
  letI := (isField_of_isRegularLocalRing_of_ringKrullDim_eq_zero R h).toField
  Field.isDomain

/-- **(T-REG-2)** The regular-parameter choice. In a Noetherian local ring of positive
Krull dimension there is `x ∈ 𝔪` lying outside `𝔪²` **and** outside every minimal prime:
`𝔪 ⊄ 𝔪²` (`IsLocalRing.maximalIdeal_sq_lt_of_ringKrullDim_ne_zero`), `𝔪 ⊄ 𝔭` for `𝔭` minimal (else `𝔪` itself is
minimal, i.e. `height 𝔪 = 0 = dim R`), the minimal primes are finitely many
(`Ideal.finite_minimalPrimes_of_isNoetherianRing`), so prime avoidance
(`Ideal.subset_union_prime`, with `𝔪²` as the one allowed non-prime member) applies. -/
theorem exists_mem_maximalIdeal_notMem_sq_notMem_minimalPrimes (R : Type u) [CommRing R]
    [IsNoetherianRing R] [IsLocalRing R] (h : 0 < ringKrullDim R) :
    ∃ x ∈ maximalIdeal R, x ∉ (maximalIdeal R) ^ 2 ∧ ∀ p ∈ minimalPrimes R, x ∉ p := by
  classical
  -- the finite family: the minimal primes together with `𝔪²`
  have hfin : (minimalPrimes R).Finite := by
    simpa [minimalPrimes] using (⊥ : Ideal R).finite_minimalPrimes_of_isNoetherianRing
  set s : Finset (Ideal R) := insert ((maximalIdeal R) ^ 2) hfin.toFinset with hs
  -- every member other than `𝔪²` is prime
  have hp : ∀ i ∈ s, i ≠ (maximalIdeal R) ^ 2 → i ≠ (maximalIdeal R) ^ 2 → i.IsPrime := by
    intro i hi hne _
    have hi' : i ∈ hfin.toFinset := (Finset.mem_insert.mp hi).resolve_left hne
    exact (hfin.mem_toFinset.mp hi').1.1
  -- `𝔪` is contained in no member
  have hnotle : ¬ ∃ i ∈ s, maximalIdeal R ≤ i := by
    rintro ⟨i, hi, hle⟩
    rcases Finset.mem_insert.mp hi with rfl | hi'
    · exact absurd hle (not_le_of_gt (IsLocalRing.maximalIdeal_sq_lt_of_ringKrullDim_ne_zero (ne_of_gt h)))
    · -- `𝔪 ≤ 𝔭` with `𝔭` minimal forces `𝔪 = 𝔭`, hence `dim R = height 𝔪 = 0`
      have hmem : i ∈ minimalPrimes R := hfin.mem_toFinset.mp hi'
      have hile : i ≤ maximalIdeal R := by
        haveI := hmem.1.1
        exact IsLocalRing.le_maximalIdeal (fun hc => hmem.1.1.ne_top hc)
      have hEq : maximalIdeal R = i := le_antisymm hle hile
      have hmin : maximalIdeal R ∈ minimalPrimes R := hEq ▸ hmem
      have hzero : (maximalIdeal R).height = 0 := by
        haveI : (maximalIdeal R).IsPrime := inferInstance
        exact Ideal.height_eq_zero_iff.mpr hmin
      have hdim : ringKrullDim R = 0 := by
        rw [← IsLocalRing.maximalIdeal_height_eq_ringKrullDim, hzero]
        rfl
      exact absurd hdim (ne_of_gt h)
  -- prime avoidance
  have hsub : ¬ ((maximalIdeal R : Set R) ⊆ ⋃ i ∈ (s : Set (Ideal R)), (i : Set R)) := by
    rw [Ideal.subset_union_prime ((maximalIdeal R) ^ 2) ((maximalIdeal R) ^ 2) hp]
    exact hnotle
  obtain ⟨x, hxm, hxni⟩ := Set.not_subset.mp hsub
  refine ⟨x, hxm, ?_, ?_⟩
  · intro hx2
    exact hxni (Set.mem_biUnion (Finset.mem_insert_self _ _) hx2)
  · intro p hpmin hxp
    exact hxni (Set.mem_biUnion
      (Finset.mem_insert_of_mem (hfin.mem_toFinset.mpr hpmin)) hxp)

/-- **(T-REG-4, the closing step)** If some `x ∈ 𝔪` generates a **prime** ideal and lies
outside every minimal prime, then `R` is a domain: a minimal prime `𝔭 ≤ xR` satisfies
`𝔭 ≤ xR • 𝔭` (write `a = x·b` for `a ∈ 𝔭`; `x ∉ 𝔭` forces `b ∈ 𝔭`), so `𝔭 = ⊥` by
Nakayama, and `⊥` prime means `R` is a domain. -/
theorem isDomain_of_isPrime_span_singleton (R : Type u) [CommRing R] [IsNoetherianRing R]
    [IsLocalRing R] {x : R} (hx : x ∈ maximalIdeal R)
    (hprime : (Ideal.span {x} : Ideal R).IsPrime)
    (hmin : ∀ p ∈ minimalPrimes R, x ∉ p) : IsDomain R := by
  classical
  obtain ⟨p, hpmin, hple⟩ :=
    Ideal.exists_minimalPrimes_le (I := (⊥ : Ideal R)) (J := Ideal.span {x}) bot_le
  haveI : p.IsPrime := hpmin.1.1
  have hxp : x ∉ p := hmin p (by simpa [minimalPrimes] using hpmin)
  have hstep : p ≤ (Ideal.span {x} : Ideal R) • p := by
    intro a ha
    obtain ⟨b, rfl⟩ := Ideal.mem_span_singleton'.mp (hple ha)
    have hb : b ∈ p := (hpmin.1.1.mem_or_mem ha).resolve_right hxp
    rw [Ideal.smul_eq_mul, mul_comm b x]
    exact Ideal.mul_mem_mul (Ideal.mem_span_singleton_self x) hb
  have hfg : p.FG := IsNoetherian.noetherian _
  have hjac : (Ideal.span {x} : Ideal R) ≤ Ideal.jacobson (⊥ : Ideal R) := by
    rw [IsLocalRing.jacobson_eq_maximalIdeal (⊥ : Ideal R) bot_ne_top]
    exact (Ideal.span_singleton_le_iff_mem _).mpr hx
  have hbot : p = ⊥ :=
    Submodule.eq_bot_of_le_smul_of_le_jacobson_bot _ p hfg hstep hjac
  haveI hbp : (⊥ : Ideal R).IsPrime := hbot ▸ hpmin.1.1
  haveI : IsDomain (R ⧸ (⊥ : Ideal R)) := (Ideal.Quotient.isDomain_iff_prime ⊥).mpr hbp
  exact (RingEquiv.quotientBot R).symm.isDomain

/-- **(T-REG-3a, the dimension half)** Cutting a Noetherian local ring by one element of
the maximal ideal drops the Krull dimension by at most one. (Mathlib's
`ringKrullDim_le_ringKrullDim_quotSMulTop_succ` phrased for `Ideal.span {x}`.) -/
theorem ringKrullDim_le_ringKrullDim_quotient_span_singleton_succ (R : Type u) [CommRing R]
    [IsNoetherianRing R] [IsLocalRing R] {x : R} (hx : x ∈ maximalIdeal R) :
    ringKrullDim R ≤ ringKrullDim (R ⧸ Ideal.span {x}) + 1 := by
  have h := ringKrullDim_le_ringKrullDim_quotSMulTop_succ (R := R) hx
  have hspan : (x • (⊤ : Ideal R) : Ideal R) = Ideal.span {x} := by
    rw [← Submodule.singleton_set_smul (⊤ : Ideal R) x, Submodule.set_smul_top_eq_span]
  rwa [hspan] at h

/-- **(T-REG-3b, the generator count)** If `x ∈ 𝔪 \ 𝔪²` then `𝔪` has a minimal generating
set through `x`, so its image in `R ⧸ xR` needs one generator fewer.

Elementary argument (no cotangent spaces): write `x = ∑ c_g g` over a generating set `G`
of `𝔪` of minimal size; not every `c_g` can lie in `𝔪` (else `x ∈ 𝔪²`), so some `c_{g₀}` is
a unit, whence `g₀` is recovered from `x` and `G \ {g₀}` — i.e. `𝔪 = span (x ∷ G \ {g₀})`.
Modulo `x` the `|G| − 1` remaining generators suffice. -/
theorem spanFinrank_map_maximalIdeal_succ_le (R : Type u) [CommRing R]
    [IsNoetherianRing R] [IsLocalRing R] {x : R} (hx : x ∈ maximalIdeal R)
    (hx2 : x ∉ (maximalIdeal R) ^ 2) :
    ((maximalIdeal R).map (Ideal.Quotient.mk (Ideal.span {x}))).spanFinrank + 1 ≤
      (maximalIdeal R).spanFinrank := by
  classical
  -- a minimal generating set `G` of `𝔪`
  have hfg : (maximalIdeal R).FG := IsNoetherian.noetherian _
  obtain ⟨G, hGcard, hGspan⟩ := Submodule.FG.exists_span_finset_card_eq_spanFinrank hfg
  have hGle : ∀ g ∈ G, g ∈ maximalIdeal R := fun g hg => hGspan ▸ Ideal.subset_span hg
  obtain ⟨c, -, hc⟩ := Submodule.mem_span_finset.mp (hGspan ▸ hx)
  -- some coefficient is a unit
  obtain ⟨g₀, hg₀G, hg₀u⟩ : ∃ g₀ ∈ G, IsUnit (c g₀) := by
    by_contra hcon
    push Not at hcon
    refine hx2 ?_
    rw [← hc, pow_two]
    refine Ideal.sum_mem _ (fun g hg => ?_)
    rw [smul_eq_mul]
    exact Ideal.mul_mem_mul (((IsLocalRing.mem_maximalIdeal _).mpr (hcon g hg))) (hGle g hg)
  -- `𝔪` is generated by `x` together with `G \ {g₀}`
  have hspan2 : Ideal.span (insert x ((G.erase g₀ : Finset R) : Set R)) = maximalIdeal R := by
    refine le_antisymm ?_ ?_
    · rw [Ideal.span_le]
      rintro z hz
      rcases Set.mem_insert_iff.mp hz with rfl | hz'
      · exact hx
      · exact hGle z (Finset.mem_of_mem_erase (by simpa [and_comm] using hz'))
    · rw [← hGspan, Ideal.span_le]
      intro g hg
      by_cases hgg : g = g₀
      · subst hgg
        have hsum : (c g) • g = x - ∑ h ∈ G.erase g, c h • h := by
          rw [← hc, ← Finset.add_sum_erase G (fun h => c h • h) hg]
          ring
        have hmem : x - ∑ h ∈ G.erase g, c h • h ∈
            Ideal.span (insert x ((G.erase g : Finset R) : Set R)) := by
          refine Submodule.sub_mem _ (Ideal.subset_span (Set.mem_insert _ _)) ?_
          refine Ideal.sum_mem _ (fun h hh => ?_)
          rw [smul_eq_mul]
          exact Ideal.mul_mem_left _ _
            (Ideal.subset_span (Set.mem_insert_of_mem _ (by simp [and_comm] at hh ⊢; exact hh)))
        have hsmul := (Ideal.span (insert x ((G.erase g : Finset R) : Set R))).smul_mem
          ((hg₀u.unit⁻¹ : Rˣ) : R) (hsum ▸ hmem)
        rwa [smul_smul, show ((hg₀u.unit⁻¹ : Rˣ) : R) * c g = 1 from by
          simp, one_smul] at hsmul
      · refine Ideal.subset_span (Set.mem_insert_of_mem _ ?_)
        simp only [Finset.coe_erase, Set.mem_sdiff, Set.mem_singleton_iff]
        exact ⟨hg, hgg⟩
  -- push to the quotient: the image of `x` dies
  have hmapspan : (maximalIdeal R).map (Ideal.Quotient.mk (Ideal.span {x})) =
      Ideal.span ((Ideal.Quotient.mk (Ideal.span {x})) ''
        ((G.erase g₀ : Finset R) : Set R)) := by
    rw [← hspan2, Ideal.map_span, Set.image_insert_eq,
      show (Ideal.Quotient.mk (Ideal.span {x})) x = 0 from
        Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton_self x),
      Ideal.span_insert_zero]
  -- count
  have hle : ((maximalIdeal R).map (Ideal.Quotient.mk (Ideal.span {x}))).spanFinrank ≤
      (G.erase g₀).card := by
    rw [hmapspan]
    refine le_trans (Submodule.spanFinrank_span_le_ncard_of_finite
      ((G.erase g₀ : Finset R).finite_toSet.image _)) ?_
    refine le_trans (Set.ncard_image_le ((G.erase g₀ : Finset R).finite_toSet)) (le_of_eq ?_)
    simp [Set.ncard_eq_toFinset_card', Finset.erase_eq]
  have hcard : (G.erase g₀).card + 1 = G.card := by
    rw [Finset.card_erase_of_mem hg₀G]
    exact Nat.succ_pred_eq_of_pos (Finset.card_pos.mpr ⟨g₀, hg₀G⟩)
  omega

/-- (Implementation) The `WithBot ℕ∞` arithmetic of the sandwich
`s + 1 ≤ n`, `n ≤ D + 1`, `D ≤ s`  ⟹  `s ≤ D`. -/
private theorem le_of_sandwich {D : WithBot ℕ∞} {s n : ℕ} (h1 : D ≤ (s : WithBot ℕ∞))
    (h2 : (n : WithBot ℕ∞) ≤ D + 1) (h3 : s + 1 ≤ n) : (s : WithBot ℕ∞) ≤ D := by
  induction D using WithBot.recBotCoe with
  | bot =>
    rw [WithBot.bot_add] at h2
    exact absurd h2 (by simp)
  | coe D =>
    induction D using WithTop.recTopCoe with
    | top =>
      refine absurd h1 (not_le_of_gt ?_)
      exact WithBot.coe_lt_coe.mpr (ENat.coe_lt_top s)
    | coe m =>
      have hcast : ((m + 1 : ℕ) : WithBot ℕ∞) = ((m : ℕ∞) : WithBot ℕ∞) + 1 := by
        rfl
      have hnm : n ≤ m + 1 := by
        have hle : ((n : ℕ) : WithBot ℕ∞) ≤ ((m + 1 : ℕ) : WithBot ℕ∞) := by
          rw [hcast]; exact h2
        exact_mod_cast hle
      have : s ≤ m := by omega
      exact_mod_cast Nat.cast_le.mpr this

/-- **(T-REG ★)** A regular local ring is a domain (Matsumura, *Commutative Ring Theory*,
Theorem 14.3; Stacks 00NP). Absent from mathlib, which ships only the definition.

Induction on the minimal number of generators `n` of `𝔪` (= `dim R` by regularity):
`n = 0` gives a field; otherwise cut by a regular parameter `x` (T-REG-2), observe that
`R ⧸ xR` is again regular local with one generator fewer (T-REG-3a/3b + the sandwich),
conclude it is a domain by induction, so `xR` is prime, and close with T-REG-4. -/
theorem isDomain_of_isRegularLocalRing : ∀ (n : ℕ) (R : Type u) [CommRing R]
    [IsRegularLocalRing R], (maximalIdeal R).spanFinrank = n → IsDomain R := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro R _ _ hn
    rcases Nat.eq_zero_or_pos n with rfl | hpos
    · refine isDomain_of_isRegularLocalRing_of_ringKrullDim_eq_zero R ?_
      rw [← IsRegularLocalRing.spanFinrank_maximalIdeal (R := R), hn]
      rfl
    · -- positive dimension: cut by a regular parameter
      have hdimpos : 0 < ringKrullDim R := by
        rw [← IsRegularLocalRing.spanFinrank_maximalIdeal (R := R), hn]
        exact_mod_cast Nat.cast_pos.mpr hpos
      obtain ⟨x, hx, hx2, hxmin⟩ :=
        exists_mem_maximalIdeal_notMem_sq_notMem_minimalPrimes R hdimpos
      -- the quotient is local
      have hne : (Ideal.span {x} : Ideal R) ≠ ⊤ :=
        fun hc => (IsLocalRing.maximalIdeal.isMaximal R).ne_top
          (top_le_iff.mp (hc ▸ (Ideal.span_singleton_le_iff_mem _).mpr hx))
      haveI : Nontrivial (R ⧸ Ideal.span {x}) := Ideal.Quotient.nontrivial_iff.mpr hne
      haveI : IsLocalRing (R ⧸ Ideal.span {x}) :=
        IsLocalRing.of_surjective' (Ideal.Quotient.mk _) Ideal.Quotient.mk_surjective
      haveI : IsLocalHom (Ideal.Quotient.mk (Ideal.span {x})) :=
        IsLocalHom.of_surjective _ Ideal.Quotient.mk_surjective
      have hmax : (maximalIdeal R).map (Ideal.Quotient.mk (Ideal.span {x})) =
          maximalIdeal (R ⧸ Ideal.span {x}) := by
        ext z
        obtain ⟨z, rfl⟩ := Ideal.Quotient.mk_surjective z
        simp [sup_eq_left.mpr ((Ideal.span_singleton_le_iff_mem _).mpr hx)]
      -- one generator fewer
      have hs : (maximalIdeal (R ⧸ Ideal.span {x})).spanFinrank + 1 ≤ n := by
        rw [← hmax, ← hn]
        exact spanFinrank_map_maximalIdeal_succ_le R hx hx2
      -- the sandwich makes the quotient regular
      have hdimle : ringKrullDim (R ⧸ Ideal.span {x}) ≤
          ((maximalIdeal (R ⧸ Ideal.span {x})).spanFinrank : WithBot ℕ∞) :=
        ringKrullDim_le_spanFinrank_maximalIdeal _
      have hdimR : ringKrullDim R = (n : WithBot ℕ∞) := by
        have hreg := IsRegularLocalRing.spanFinrank_maximalIdeal (R := R)
        rw [hn] at hreg
        exact hreg.symm
      have hdimge : (n : WithBot ℕ∞) ≤ ringKrullDim (R ⧸ Ideal.span {x}) + 1 := by
        rw [← hdimR]
        exact ringKrullDim_le_ringKrullDim_quotient_span_singleton_succ R hx
      haveI : IsRegularLocalRing (R ⧸ Ideal.span {x}) :=
        IsRegularLocalRing.of_spanFinrank_maximalIdeal_le _
          (le_of_sandwich hdimle hdimge hs)
      -- induction, then the closing step
      haveI : IsDomain (R ⧸ Ideal.span {x}) :=
        ih ((maximalIdeal (R ⧸ Ideal.span {x})).spanFinrank) (by omega) _ rfl
      exact isDomain_of_isPrime_span_singleton R hx
        ((Ideal.Quotient.isDomain_iff_prime _).mp inferInstance) hxmin

/-- **(T-REG ★, instance form)** A regular local ring is a domain. -/
theorem IsRegularLocalRing.isDomain (R : Type u) [CommRing R] [IsRegularLocalRing R] :
    IsDomain R :=
  isDomain_of_isRegularLocalRing _ R rfl

/-! ## Regularity ascends along unramified flat local extensions (T-SMOOTH-REG core) -/

/-- **(T-SMOOTH-REG core ★)** Let `A → B` be a **flat** local homomorphism of Noetherian
local rings with `𝔪_A · B = 𝔪_B` (i.e. unramified — the situation of an étale extension).
If `A` is regular, so is `B`.

Two inputs: `Ideal.height_eq_height_add_of_liesOver_of_hasGoingDown` (Matsumura 13.B
Th. 19(2), via going-down for flat maps) makes the dimensions agree, because the fibre
ring `B ⧸ 𝔪_A B = B ⧸ 𝔪_B` is a field; and `Ideal.spanFinrank_map_le_of_fg` says `𝔪_B`
needs no more generators than `𝔪_A`. Regularity is then the sandwich
`dim B = dim A = spanFinrank 𝔪_A ≥ spanFinrank 𝔪_B ≥ dim B`. -/
theorem isRegularLocalRing_of_flat_of_map_maximalIdeal (A B : Type u) [CommRing A]
    [CommRing B] [Algebra A B] [IsRegularLocalRing A] [IsLocalRing B] [IsNoetherianRing B]
    [Module.Flat A B]
    (hlo : (maximalIdeal A).map (algebraMap A B) = maximalIdeal B) :
    IsRegularLocalRing B := by
  haveI : Algebra.HasGoingDown A B := Algebra.HasGoingDown.of_flat
  -- `𝔪_B` lies over `𝔪_A`
  haveI hover : (maximalIdeal B).LiesOver (maximalIdeal A) := by
    refine ⟨le_antisymm ?_ ?_⟩
    · rw [Ideal.under_def]
      intro a ha
      exact Ideal.mem_comap.mpr (hlo ▸ Ideal.mem_map_of_mem _ ha)
    · exact IsLocalRing.le_maximalIdeal (fun hc => by
        have h1 : (1 : B) ∈ maximalIdeal B := by
          have : (1 : A) ∈ (maximalIdeal B).under A := hc ▸ Submodule.mem_top
          simpa using this
        exact (maximalIdeal.isMaximal B).ne_top (Ideal.eq_top_of_isUnit_mem _ h1 isUnit_one))
  -- the fibre term of the height formula vanishes
  have hfib : ((maximalIdeal B).map
      (Ideal.Quotient.mk ((maximalIdeal A).map (algebraMap A B)))).height = 0 := by
    rw [congrArg (fun I : Ideal B => I.map
      (Ideal.Quotient.mk ((maximalIdeal A).map (algebraMap A B)))) hlo.symm,
      Ideal.map_quotient_self]
    haveI : Nontrivial (B ⧸ (maximalIdeal A).map (algebraMap A B)) :=
      Ideal.Quotient.nontrivial_iff.mpr (by
        rw [hlo]; exact (maximalIdeal.isMaximal B).ne_top)
    exact Ideal.height_bot
  -- hence the dimensions agree
  have hheight : (maximalIdeal B).height = (maximalIdeal A).height := by
    rw [Ideal.height_eq_height_add_of_liesOver_of_hasGoingDown (maximalIdeal A)
      (maximalIdeal B), hfib, add_zero]
  -- and `𝔪_B` needs no more generators than `𝔪_A`
  have hgen : (maximalIdeal B).spanFinrank ≤ (maximalIdeal A).spanFinrank := by
    have h := Ideal.spanFinrank_map_le_of_fg (algebraMap A B)
      (I := maximalIdeal A) (IsNoetherian.noetherian _)
    rwa [hlo] at h
  -- the sandwich
  refine IsRegularLocalRing.of_spanFinrank_maximalIdeal_le B ?_
  rw [← IsLocalRing.maximalIdeal_height_eq_ringKrullDim, hheight,
    IsLocalRing.maximalIdeal_height_eq_ringKrullDim,
    ← IsRegularLocalRing.spanFinrank_maximalIdeal (R := A)]
  exact_mod_cast Nat.cast_le.mpr hgen

end ModularCurves
