/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.Ideal.MinimalPrime.Basic
import Mathlib.RingTheory.Nakayama
import Mathlib.RingTheory.Ideal.MinimalPrime.Noetherian
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Square
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem
import Mathlib.RingTheory.KrullDimension.Regular

/-!
# Regular local rings are domains (T-REG)

**(T-G4a-SUB2 prerequisite.)** Mathlib currently ships only
`Mathlib/RingTheory/RegularLocalRing/Defs.lean` — the definition
`(maximalIdeal R).spanFinrank = ringKrullDim R`, the cotangent-space reformulation, and
transport along ring equivalences. Nothing about the *theory* of regular local rings is
available; in particular `IsRegularLocalRing R → IsDomain R` (Matsumura, *Commutative Ring
Theory*, Thm 14.3) is absent, and it is exactly what the geometric-irreducibility leaf
`irreducibleSpace_of_connectedSpace_of_smooth` needs (smooth ⟹ regular ⟹ the local rings
are domains ⟹ the irreducible components are disjoint).

This file develops the pieces, bottom-up. The argument is the classical induction on
`dim R`:

* `dim R = 0` — then `𝔪` is generated by `0` elements, so `𝔪 = ⊥` and `R` is a field.
* `dim R > 0` — pick `x ∈ 𝔪 \ (𝔪² ∪ ⋃ᵢ 𝔭ᵢ)` (`𝔭ᵢ` the minimal primes) by prime avoidance;
  `R/xR` is regular local of dimension `dim R − 1`, hence a domain by induction, hence
  `xR` is prime; a minimal prime `𝔭 ⊆ xR` satisfies `𝔭 = x𝔭` (as `x ∉ 𝔭`), so `𝔭 = ⊥` by
  Nakayama and `R` is a domain.

Landed so far: the `dim 0` base case, the prime-avoidance choice of the regular parameter
`x`, and the closing Nakayama step (`xR` prime + `x` off the minimal primes => domain).
-/

universe u

open IsLocalRing Pointwise

namespace ModularCurves

/-- **(T-REG-1)** A regular local ring of Krull dimension `0` is a field: regularity says
`𝔪` is generated by `dim R = 0` elements, i.e. `𝔪 = ⊥`. -/
theorem isField_of_isRegularLocalRing_of_ringKrullDim_eq_zero (R : Type u) [CommRing R]
    [IsRegularLocalRing R] (h : ringKrullDim R = 0) : IsField R := by
  have hfg : (maximalIdeal R).FG := IsNoetherian.noetherian _
  have hspan : (maximalIdeal R).spanFinrank = 0 := by
    have := IsRegularLocalRing.spanFinrank_maximalIdeal (R := R)
    rw [h] at this
    exact_mod_cast this
  exact isField_iff_maximalIdeal_eq.mpr
    ((Submodule.spanFinrank_eq_zero_iff_eq_bot hfg).mp hspan)

/-- **(T-REG-1')** Hence a regular local ring of Krull dimension `0` is a domain. -/
theorem isDomain_of_isRegularLocalRing_of_ringKrullDim_eq_zero (R : Type u) [CommRing R]
    [IsRegularLocalRing R] (h : ringKrullDim R = 0) : IsDomain R :=
  letI := (isField_of_isRegularLocalRing_of_ringKrullDim_eq_zero R h).toField
  Field.isDomain

/-- **(T-REG-2)** The regular-parameter choice. In a Noetherian local ring of positive
Krull dimension there is `x ∈ 𝔪` lying outside `𝔪²` **and** outside every minimal prime:
`𝔪 ⊄ 𝔪²` (`IsLocalRing.maximalIdeal_sq_lt_of_ringKrullDim_ne_zero`), `𝔪 ⊄ 𝔭` for `𝔭` minimal (else `𝔪` itself is
minimal, i.e. `height 𝔪 = 0 = dim R`), the minimal primes are finitely many
(`Ideal.finite_minimalPrimes_of_isNoetherianRing`), so prime avoidance
(`Ideal.subset_union_prime`, with `𝔪²` as the one allowed non-prime member) applies. -/
theorem exists_mem_maximalIdeal_notMem_sq_notMem_minimalPrimes (R : Type u) [CommRing R]
    [IsNoetherianRing R] [IsLocalRing R] (h : 0 < ringKrullDim R) :
    ∃ x ∈ maximalIdeal R, x ∉ (maximalIdeal R) ^ 2 ∧ ∀ p ∈ minimalPrimes R, x ∉ p := by
  classical
  -- the finite family: the minimal primes together with `𝔪²`
  have hfin : (minimalPrimes R).Finite := by
    simpa [minimalPrimes] using (⊥ : Ideal R).finite_minimalPrimes_of_isNoetherianRing
  set s : Finset (Ideal R) := insert ((maximalIdeal R) ^ 2) hfin.toFinset with hs
  -- every member other than `𝔪²` is prime
  have hp : ∀ i ∈ s, i ≠ (maximalIdeal R) ^ 2 → i ≠ (maximalIdeal R) ^ 2 → i.IsPrime := by
    intro i hi hne _
    have hi' : i ∈ hfin.toFinset := (Finset.mem_insert.mp hi).resolve_left hne
    exact (hfin.mem_toFinset.mp hi').1.1
  -- `𝔪` is contained in no member
  have hnotle : ¬ ∃ i ∈ s, maximalIdeal R ≤ i := by
    rintro ⟨i, hi, hle⟩
    rcases Finset.mem_insert.mp hi with rfl | hi'
    · exact absurd hle (not_le_of_gt (IsLocalRing.maximalIdeal_sq_lt_of_ringKrullDim_ne_zero (ne_of_gt h)))
    · -- `𝔪 ≤ 𝔭` with `𝔭` minimal forces `𝔪 = 𝔭`, hence `dim R = height 𝔪 = 0`
      have hmem : i ∈ minimalPrimes R := hfin.mem_toFinset.mp hi'
      have hile : i ≤ maximalIdeal R := by
        haveI := hmem.1.1
        exact IsLocalRing.le_maximalIdeal (fun hc => hmem.1.1.ne_top hc)
      have hEq : maximalIdeal R = i := le_antisymm hle hile
      have hmin : maximalIdeal R ∈ minimalPrimes R := hEq ▸ hmem
      have hzero : (maximalIdeal R).height = 0 := by
        haveI : (maximalIdeal R).IsPrime := inferInstance
        exact Ideal.height_eq_zero_iff.mpr hmin
      have hdim : ringKrullDim R = 0 := by
        rw [← IsLocalRing.maximalIdeal_height_eq_ringKrullDim, hzero]
        rfl
      exact absurd hdim (ne_of_gt h)
  -- prime avoidance
  have hsub : ¬ ((maximalIdeal R : Set R) ⊆ ⋃ i ∈ (s : Set (Ideal R)), (i : Set R)) := by
    rw [Ideal.subset_union_prime ((maximalIdeal R) ^ 2) ((maximalIdeal R) ^ 2) hp]
    exact hnotle
  obtain ⟨x, hxm, hxni⟩ := Set.not_subset.mp hsub
  refine ⟨x, hxm, ?_, ?_⟩
  · intro hx2
    exact hxni (Set.mem_biUnion (Finset.mem_insert_self _ _) hx2)
  · intro p hpmin hxp
    exact hxni (Set.mem_biUnion
      (Finset.mem_insert_of_mem (hfin.mem_toFinset.mpr hpmin)) hxp)

/-- **(T-REG-4, the closing step)** If some `x ∈ 𝔪` generates a **prime** ideal and lies
outside every minimal prime, then `R` is a domain: a minimal prime `𝔭 ≤ xR` satisfies
`𝔭 ≤ xR • 𝔭` (write `a = x·b` for `a ∈ 𝔭`; `x ∉ 𝔭` forces `b ∈ 𝔭`), so `𝔭 = ⊥` by
Nakayama, and `⊥` prime means `R` is a domain. -/
theorem isDomain_of_isPrime_span_singleton (R : Type u) [CommRing R] [IsNoetherianRing R]
    [IsLocalRing R] {x : R} (hx : x ∈ maximalIdeal R)
    (hprime : (Ideal.span {x} : Ideal R).IsPrime)
    (hmin : ∀ p ∈ minimalPrimes R, x ∉ p) : IsDomain R := by
  classical
  obtain ⟨p, hpmin, hple⟩ :=
    Ideal.exists_minimalPrimes_le (I := (⊥ : Ideal R)) (J := Ideal.span {x}) bot_le
  haveI : p.IsPrime := hpmin.1.1
  have hxp : x ∉ p := hmin p (by simpa [minimalPrimes] using hpmin)
  have hstep : p ≤ (Ideal.span {x} : Ideal R) • p := by
    intro a ha
    obtain ⟨b, rfl⟩ := Ideal.mem_span_singleton'.mp (hple ha)
    have hb : b ∈ p := (hpmin.1.1.mem_or_mem ha).resolve_right hxp
    rw [Ideal.smul_eq_mul, mul_comm b x]
    exact Ideal.mul_mem_mul (Ideal.mem_span_singleton_self x) hb
  have hfg : p.FG := IsNoetherian.noetherian _
  have hjac : (Ideal.span {x} : Ideal R) ≤ Ideal.jacobson (⊥ : Ideal R) := by
    rw [IsLocalRing.jacobson_eq_maximalIdeal (⊥ : Ideal R) bot_ne_top]
    exact (Ideal.span_singleton_le_iff_mem _).mpr hx
  have hbot : p = ⊥ :=
    Submodule.eq_bot_of_le_smul_of_le_jacobson_bot _ p hfg hstep hjac
  haveI hbp : (⊥ : Ideal R).IsPrime := hbot ▸ hpmin.1.1
  haveI : IsDomain (R ⧸ (⊥ : Ideal R)) := (Ideal.Quotient.isDomain_iff_prime ⊥).mpr hbp
  exact (RingEquiv.quotientBot R).symm.isDomain

/-- **(T-REG-3a, the dimension half)** Cutting a Noetherian local ring by one element of
the maximal ideal drops the Krull dimension by at most one. (Mathlib's
`ringKrullDim_le_ringKrullDim_quotSMulTop_succ` phrased for `Ideal.span {x}`.) -/
theorem ringKrullDim_le_ringKrullDim_quotient_span_singleton_succ (R : Type u) [CommRing R]
    [IsNoetherianRing R] [IsLocalRing R] {x : R} (hx : x ∈ maximalIdeal R) :
    ringKrullDim R ≤ ringKrullDim (R ⧸ Ideal.span {x}) + 1 := by
  have h := ringKrullDim_le_ringKrullDim_quotSMulTop_succ (R := R) hx
  have hspan : (x • (⊤ : Ideal R) : Ideal R) = Ideal.span {x} := by
    rw [← Submodule.singleton_set_smul (⊤ : Ideal R) x, Submodule.set_smul_top_eq_span]
  rwa [hspan] at h

end ModularCurves
