/-
Copyright (c) 2026 The AINTLIB contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: AINTLIB ModularCurves project

ForMathlib (OURS, not vendored): upstream candidate. Ticket T-D11 (T-D23 revived).
-/
import Mathlib.RingTheory.Smooth.StandardSmoothCotangent
import Mathlib.RingTheory.Etale.Field
import Mathlib.RingTheory.Smooth.Flat
import Mathlib.RingTheory.Etale.Kaehler
import Mathlib.RingTheory.DiscreteValuationRing.TFAE
import ModularCurves.ForMathlib.PrincipalMaximalDVR

/-!
# Stalks of standard-smooth curves over a field are discrete valuation rings

For `A` a standard-smooth `k`-algebra of relative dimension `1` over a field `k`, the
local rings of `Spec A` at points of any finite closed subscheme are discrete valuation
rings, and consequently:

* `ModularCurves.exists_span_nonZeroDivisor_map_localizationAtPrime`: an ideal `I ≤ q`
  with finite-dimensional quotient `A ⧸ I` localizes at `q` to a principal ideal
  generated by a nonzerodivisor.
* `ModularCurves.mem_nonZeroDivisors_of_finite_quotient`: an element `f` with
  finite-dimensional quotient `A ⧸ (f)` is a nonzerodivisor.

The route avoids all regularity theory: near any prime, a Kähler-differential
coordinate `g` (with `dg` generating the rank-one module `Ω[A⁄k]`) exhibits an
away-localization of `A` as formally smooth over `k[X]` via the Jacobi–Zariski sequence,
hence smooth, hence flat; étale-fibre analysis over `k[X]` (`RingTheory/Etale/Field`)
identifies the maximal ideal of the stalk as the extension of the (principal) maximal
ideal downstairs, and the principal-maximal-ideal criterion
(`ModularCurves.ForMathlib.PrincipalMaximalDVR`) concludes. The finiteness hypothesis
kills the generic (field-stalk) case: `k[X]` embeds torsion-freely into the stalk,
which in that case is a localization of the finite-dimensional algebra `A ⧸ I`.
-/

universe u

namespace ModularCurves

variable (k A : Type u) [Field k] [CommRing A] [Algebra k A]
  [Algebra.IsStandardSmoothOfRelativeDimension 1 k A]

/-- **Stalkwise principality on a standard-smooth curve over a field**: an ideal `I`
contained in a prime `q`, with `A ⧸ I` finite-dimensional over `k`, generates a
principal ideal with nonzerodivisor generator in the local ring at `q` (which is a
discrete valuation ring). -/
theorem exists_span_nonZeroDivisor_map_localizationAtPrime (q : Ideal A) [q.IsPrime]
    (I : Ideal A) (hIq : I ≤ q) (hfin : Module.Finite k (A ⧸ I)) :
    ∃ f : Localization.AtPrime q,
      I.map (algebraMap A (Localization.AtPrime q)) = Ideal.span {f} ∧
      f ∈ nonZeroDivisors (Localization.AtPrime q) := by
  sorry

/-- On a standard-smooth curve over a field, an element cutting out a
finite-dimensional quotient is a nonzerodivisor (its vanishing locus misses every
generic point; stalkwise the local rings are fields or discrete valuation rings). -/
theorem mem_nonZeroDivisors_of_finite_quotient (f : A)
    (hfin : Module.Finite k (A ⧸ Ideal.span {f})) : f ∈ nonZeroDivisors A := by
  sorry

end ModularCurves
