module

public import BernoulliRegular.Stickelberger
public import BernoulliRegular.GaussSum.PrimeFactorization.Valuation

/-!
# Assemble the prime-above-`p` factorisation of the lifted Gauss sum

Let

`L = ℚ(ζ_{p(p-1)})`.

The valuation file packages the exponent of each prime above `(p)` in the
principal ideal generated by `gaussSumIntegers p L χ`.  In this file we bundle
those local exponents into the global ideal factorisation needed for the
Stickelberger chain.

For `T027d4c`, the right indexing set is the finite set `primesAboveP p L`.
The later ticket `T027d4d` rewrites this factorisation into the exact
Stickelberger indexing conventions.
-/

@[expose] public section

noncomputable section

open NumberField
open scoped Pointwise

namespace BernoulliRegular

section Assembly

variable (p : ℕ) [hp : Fact p.Prime]
  (L : Type*) [Field L] [NumberField L] [IsCyclotomicExtension {p * (p - 1)} ℚ L]

local notation "𝔭" => (Ideal.span ({(p : ℤ)} : Set ℤ))
local instance : NeZero (p - 1) := ⟨Nat.sub_ne_zero_of_lt hp.out.one_lt⟩

/-- The character-side Galois lift sends the canonical lifted Gauss sum to the
lift of the transformed character. -/
lemma sigmaOfCharacterUnit_smul_gaussSumLift
    (b : (ZMod (p - 1))ˣ) (χ : DirichletCharacter ℂ p) :
    sigmaOfCharacterUnit (p := p) L b • gaussSumLift p L χ =
      gaussSumLift p L (χ ^ (b : ZMod (p - 1)).val) := by
  apply (stickelbergerEmbedding p L).injective
  calc
    stickelbergerEmbedding p L
        (sigmaOfCharacterUnit (p := p) L b • gaussSumLift p L χ)
        =
        characterSideEmbedding (p := p) (L := L) b (gaussSumLift p L χ) := by
          simpa [AlgEquiv.smul_def] using congrArg
            (fun f : L →ₐ[ℚ] ℂ => f (gaussSumLift p L χ))
            (stickelbergerEmbedding_comp_sigmaOfCharacterUnit_eq_characterSideEmbedding
              (p := p) (L := L) b)
    _ = gaussSum (χ ^ (b : ZMod (p - 1)).val) (ZMod.stdAddChar : AddChar (ZMod p) ℂ) :=
          characterSideEmbedding_gaussSumLift (p := p) (L := L) b χ
    _ = stickelbergerEmbedding p L (gaussSumLift p L (χ ^ (b : ZMod (p - 1)).val)) :=
          (stickelbergerEmbedding_gaussSumLift (p := p) (L := L)
            (χ ^ (b : ZMod (p - 1)).val)).symm

/-- The character-side Galois lift transports the integral Gauss-sum lift to the
integral lift of the transformed character. -/
lemma sigmaOfCharacterUnit_smul_gaussSumIntegers
    (b : (ZMod (p - 1))ˣ) (χ : DirichletCharacter ℂ p) :
    sigmaOfCharacterUnit (p := p) L b • gaussSumIntegers p L χ =
      gaussSumIntegers p L (χ ^ (b : ZMod (p - 1)).val) := by
  ext
  exact sigmaOfCharacterUnit_smul_gaussSumLift (p := p) (L := L) b χ

/-- The character-side Galois lift transports the principal ideal generated by
the lifted Gauss sum to the corresponding transformed-character ideal. -/
lemma sigmaOfCharacterUnit_smul_gaussSumIdeal
    (b : (ZMod (p - 1))ˣ) (χ : DirichletCharacter ℂ p) :
    sigmaOfCharacterUnit (p := p) L b • gaussSumIdeal (p := p) (L := L) χ =
      gaussSumIdeal (p := p) (L := L) (χ ^ (b : ZMod (p - 1)).val) := by
  unfold gaussSumIdeal
  rw [Ideal.pointwise_smul_def, Ideal.map_span, Set.image_singleton]
  exact congrArg (fun x : 𝓞 L => Ideal.span ({x} : Set (𝓞 L)))
    (sigmaOfCharacterUnit_smul_gaussSumIntegers (p := p) (L := L) b χ)

/-- Under the distinguished complex embedding, the additive-side Galois lift
of the explicit root-sum model realizes the additive-character shift
`stdAddChar.mulShift a`. -/
lemma stickelbergerEmbedding_sigmaOfUnit_smul_gaussSumLiftRootSum
    (a : (ZMod p)ˣ) (χ : DirichletCharacter ℂ p) :
    stickelbergerEmbedding p L
        (sigmaOfUnit (p := p) L a • gaussSumLiftRootSum (p := p) (L := L) χ) =
      gaussSum χ ((ZMod.stdAddChar : AddChar (ZMod p) ℂ).mulShift a) := by
  let ζchar : L := ((gaussSumLiftCharacterRoot (p := p) L : 𝓞 L) : L)
  let ζadd : L := ((gaussSumLiftAdditiveRoot (p := p) L : 𝓞 L) : L)
  have hcharroot :
      stickelbergerEmbedding p L ((sigmaOfUnit (p := p) L a) ζchar) =
        stickelbergerComplexCharacterRoot (p := p) := by
    change stickelbergerEmbedding p L
        (((sigmaOfUnit (p := p) L a • gaussSumLiftCharacterRoot (p := p) L : 𝓞 L) : L)) =
      stickelbergerComplexCharacterRoot (p := p)
    rw [sigmaOfUnit_smul_gaussSumLiftCharacterRoot,
      stickelbergerEmbedding_gaussSumLiftCharacterRoot]
  have haddroot :
      stickelbergerEmbedding p L ((sigmaOfUnit (p := p) L a) ζadd) =
        (stickelbergerComplexRoot p ^ (p - 1)) ^ (a : ZMod p).val := by
    change stickelbergerEmbedding p L
        (((sigmaOfUnit (p := p) L a • gaussSumLiftAdditiveRoot (p := p) L : 𝓞 L) : L)) =
      (stickelbergerComplexRoot p ^ (p - 1)) ^ (a : ZMod p).val
    rw [sigmaOfUnit_smul_gaussSumLiftAdditiveRoot]
    calc
      stickelbergerEmbedding p L
          (((gaussSumLiftAdditiveRoot (p := p) L ^ (a : ZMod p).val : 𝓞 L) : L))
          =
          (stickelbergerEmbedding p L
            (((gaussSumLiftAdditiveRoot (p := p) L : 𝓞 L) : L))) ^ (a : ZMod p).val :=
              map_pow (stickelbergerEmbedding p L)
                (((gaussSumLiftAdditiveRoot (p := p) L : 𝓞 L) : L))
                ((a : ZMod p).val)
      _ = (stickelbergerComplexRoot p ^ (p - 1)) ^ (a : ZMod p).val := by
            rw [stickelbergerEmbedding_gaussSumLiftAdditiveRoot]
  have hF0 :
      (fun x : ZMod p =>
        χ x * ((ZMod.stdAddChar : AddChar (ZMod p) ℂ).mulShift a) x) 0 = 0 := by
    simp [MulChar.map_nonunit _ (show ¬ IsUnit (0 : ZMod p) by simp)]
  calc
    stickelbergerEmbedding p L
        (sigmaOfUnit (p := p) L a • gaussSumLiftRootSum (p := p) (L := L) χ)
        =
        ∑ m : Fin (p - 1),
          χ (((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p) *
            ((ZMod.stdAddChar : AddChar (ZMod p) ℂ).mulShift a)
              ((((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p)) := by
            change stickelbergerEmbedding p L
                ((sigmaOfUnit (p := p) L a)
                  (gaussSumLiftRootSum (p := p) (L := L) χ))
              = _
            unfold gaussSumLiftRootSum
            let term : Fin (p - 1) → L := fun m =>
              ζchar ^ ((stickelbergerCharacterExponent (p := p) χ : ℕ) * (m : ℕ)) *
                ζadd ^ ((((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p).val)
            have hsum :
                (sigmaOfUnit (p := p) L a) (∑ m : Fin (p - 1), term m) =
                  ∑ m : Fin (p - 1), (sigmaOfUnit (p := p) L a) (term m) :=
              (sigmaOfUnit (p := p) L a).map_sum term Finset.univ
            rw [hsum, map_sum]
            apply Finset.sum_congr rfl
            intro m _
            dsimp [term]
            have hmul :
                (sigmaOfUnit (p := p) L a)
                    (ζchar ^ ((stickelbergerCharacterExponent (p := p) χ : ℕ) * (m : ℕ)) *
                      ζadd ^
                        ((((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p).val))
                  =
                  (sigmaOfUnit (p := p) L a)
                    (ζchar ^ ((stickelbergerCharacterExponent (p := p) χ : ℕ) * (m : ℕ))) *
                  (sigmaOfUnit (p := p) L a)
                    (ζadd ^
                      ((((characterUnitGenerator (p := p)) ^ (m : ℕ) :
                          (ZMod p)ˣ) : ZMod p).val)) :=
              (sigmaOfUnit (p := p) L a).map_mul _ _
            have hpow_char :
                (sigmaOfUnit (p := p) L a)
                    (ζchar ^ ((stickelbergerCharacterExponent (p := p) χ : ℕ) * (m : ℕ)))
                  =
                ((sigmaOfUnit (p := p) L a) ζchar) ^
                  ((stickelbergerCharacterExponent (p := p) χ : ℕ) * (m : ℕ)) :=
              (sigmaOfUnit (p := p) L a).map_pow ζchar
                ((stickelbergerCharacterExponent (p := p) χ : ℕ) * (m : ℕ))
            have hpow_add :
                (sigmaOfUnit (p := p) L a)
                    (ζadd ^
                      ((((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p).val))
                  =
                ((sigmaOfUnit (p := p) L a) ζadd) ^
                  ((((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p).val) :=
              (sigmaOfUnit (p := p) L a).map_pow ζadd
                ((((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p).val)
            have hchar :
                χ (((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p) =
                  stickelbergerComplexCharacterRoot (p := p) ^
                    ((stickelbergerCharacterExponent (p := p) χ : ℕ) * (m : ℕ)) :=
              stickelbergerComplexCharacter_apply_characterUnitGeneratorPow (p := p) χ (m : ℕ)
            have hadd :
                ((ZMod.stdAddChar : AddChar (ZMod p) ℂ).mulShift a)
                    ((((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p)) =
                  ((stickelbergerComplexRoot p ^ (p - 1)) ^ (a : ZMod p).val) ^
                    ((((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p).val) := by
              simpa using
                (stdAddChar_mulShift_eq_stickelbergerAdditiveRootPow_mul (p := p)
                  (a := (a : ZMod p))
                  (x := (((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p)))
            have hmul' := congrArg (stickelbergerEmbedding p L) hmul
            have hpow_char' := congrArg (stickelbergerEmbedding p L) hpow_char
            have hpow_add' := congrArg (stickelbergerEmbedding p L) hpow_add
            calc
              (stickelbergerEmbedding p L)
                  ((sigmaOfUnit (p := p) L a)
                    (ζchar ^ ((stickelbergerCharacterExponent (p := p) χ : ℕ) * (m : ℕ)) *
                      ζadd ^
                        ((((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p).val)))
                  =
                  (stickelbergerEmbedding p L)
                    (((sigmaOfUnit (p := p) L a)
                        (ζchar ^ ((stickelbergerCharacterExponent (p := p) χ : ℕ) * (m : ℕ)))) *
                      ((sigmaOfUnit (p := p) L a)
                        (ζadd ^
                          ((((characterUnitGenerator (p := p)) ^ (m : ℕ) :
                              (ZMod p)ˣ) : ZMod p).val)))) := hmul'
              _ = χ (((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p) *
                    ((ZMod.stdAddChar : AddChar (ZMod p) ℂ).mulShift a)
                      ((((characterUnitGenerator (p := p)) ^ (m : ℕ) : (ZMod p)ˣ) : ZMod p)) := by
                    rw [map_mul, hpow_char', hpow_add', map_pow, map_pow, hcharroot, haddroot,
                      ← hchar, ← hadd]
    _ = ∑ x : ZMod p, χ x * ((ZMod.stdAddChar : AddChar (ZMod p) ℂ).mulShift a) x :=
          (sum_zmod_eq_sum_characterUnitGeneratorPowers (p := p)
            (F := fun x : ZMod p =>
              χ x * ((ZMod.stdAddChar : AddChar (ZMod p) ℂ).mulShift a) x) hF0).symm
    _ = gaussSum χ ((ZMod.stdAddChar : AddChar (ZMod p) ℂ).mulShift a) := rfl

/-- The additive-side Galois lift acts on `gaussSumLift` by the lifted scalar
`χ⁻¹(a)`. -/
lemma sigmaOfUnit_smul_gaussSumLift
    {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) (a : (ZMod p)ˣ) :
    sigmaOfUnit (p := p) L a • gaussSumLift p L χ =
      (((gaussSumLiftCharacterValue (p := p) (L := L) χ⁻¹ a : 𝓞 L) : L)) *
        gaussSumLift p L χ := by
  apply (stickelbergerEmbedding p L).injective
  calc
    stickelbergerEmbedding p L (sigmaOfUnit (p := p) L a • gaussSumLift p L χ)
        =
        stickelbergerEmbedding p L
          (sigmaOfUnit (p := p) L a • gaussSumLiftRootSum (p := p) (L := L) χ) := by
            rw [gaussSumLift_eq_gaussSumLiftRootSum (p := p) (L := L)]
    _ = gaussSum χ ((ZMod.stdAddChar : AddChar (ZMod p) ℂ).mulShift a) :=
          stickelbergerEmbedding_sigmaOfUnit_smul_gaussSumLiftRootSum
              (p := p) (L := L) a χ
    _ = χ⁻¹ (a : ZMod p) * gaussSum χ (ZMod.stdAddChar : AddChar (ZMod p) ℂ) :=
          gaussSum_stdAddChar_mulShift (p := p) hχ (a : ZMod p)
    _ = stickelbergerEmbedding p L
          ((((gaussSumLiftCharacterValue (p := p) (L := L) χ⁻¹ a : 𝓞 L) : L)) *
            gaussSumLift p L χ) := by
          rw [map_mul, stickelbergerEmbedding_gaussSumLiftCharacterValue,
            stickelbergerEmbedding_gaussSumLift]

/-- The additive-side Galois lift transports the integral Gauss-sum lift by
the lifted scalar `χ⁻¹(a)`. -/
lemma sigmaOfUnit_smul_gaussSumIntegers
    {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) (a : (ZMod p)ˣ) :
    sigmaOfUnit (p := p) L a • gaussSumIntegers p L χ =
      gaussSumLiftCharacterValue (p := p) (L := L) χ⁻¹ a *
        gaussSumIntegers p L χ := by
  ext
  change sigmaOfUnit (p := p) L a • gaussSumLift p L χ =
    (((gaussSumLiftCharacterValue (p := p) (L := L) χ⁻¹ a *
        gaussSumIntegers p L χ : 𝓞 L) : L))
  rw [RingOfIntegers.coe_eq_algebraMap, map_mul, ← RingOfIntegers.coe_eq_algebraMap,
    ← RingOfIntegers.coe_eq_algebraMap, gaussSumIntegers_val]
  exact sigmaOfUnit_smul_gaussSumLift (p := p) (L := L) hχ a

/-- The additive-side Galois lifts preserve the principal ideal generated by
the lifted Gauss sum. -/
lemma sigmaOfUnit_smul_gaussSumIdeal
    {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) (a : (ZMod p)ˣ) :
    sigmaOfUnit (p := p) L a • gaussSumIdeal (p := p) (L := L) χ =
      gaussSumIdeal (p := p) (L := L) χ := by
  unfold gaussSumIdeal
  rw [Ideal.pointwise_smul_def, Ideal.map_span, Set.image_singleton]
  change
    Ideal.span ({sigmaOfUnit (p := p) L a • gaussSumIntegers p L χ} : Set (𝓞 L)) =
      Ideal.span ({gaussSumIntegers p L χ} : Set (𝓞 L))
  rw [sigmaOfUnit_smul_gaussSumIntegers (p := p) (L := L) hχ a]
  exact Ideal.span_singleton_mul_left_unit
    (gaussSumLiftCharacterValue_isUnit (p := p) (L := L) χ⁻¹ a)
    (gaussSumIntegers p L χ)

/-- Transport the exponent of the distinguished prime along the character-side
Galois action. The exponent of `σ_b(P₀)` in the factorization of the transformed
Gauss-sum ideal is the distinguished-prime exponent of the original
character. -/
lemma sigmaOfCharacterUnitPrimeExponent_eq_distinguishedPrimeExponent
    (b : (ZMod (p - 1))ˣ) {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) :
    primeAbovePExponent (p := p) (L := L)
        (sigmaOfCharacterUnit (p := p) L b • distinguishedPrimeAboveP p L)
        (χ ^ (b : ZMod (p - 1)).val) =
      distinguishedPrimeExponent (p := p) (L := L) χ := by
  let σ := sigmaOfCharacterUnit (p := p) L b
  let e : Ideal (𝓞 L) ≃* Ideal (𝓞 L) :=
    MulSemiringAction.toRingEquiv Gal(L / ℚ) (Ideal (𝓞 L)) σ
  have hIχ :
      gaussSumIdeal (p := p) (L := L) χ ≠ ⊥ :=
    gaussSumIdeal_ne_bot (p := p) (L := L) hχ
  have hIχσ :
      gaussSumIdeal (p := p) (L := L) (χ ^ (b : ZMod (p - 1)).val) ≠ ⊥ := by
    rw [← sigmaOfCharacterUnit_smul_gaussSumIdeal (p := p) (L := L) b χ,
      Ideal.pointwise_smul_def]
    exact (Ideal.map_eq_bot_iff_of_injective
      (f := MulSemiringAction.toRingHom Gal(L / ℚ) (𝓞 L) σ)
      (MulSemiringAction.toRingEquiv Gal(L / ℚ) (𝓞 L) σ).injective).not.mpr hIχ
  have hP0_irr : Irreducible (distinguishedPrimeAboveP p L) :=
    (Ideal.prime_of_isPrime
      (primeAboveP_ne_bot (p := p) (L := L) (P := distinguishedPrimeAboveP p L))
      inferInstance).irreducible
  have hσP0_irr :
      Irreducible (σ • distinguishedPrimeAboveP p L) :=
    (Ideal.prime_of_isPrime
      (primeAboveP_ne_bot (p := p) (L := L) (P := σ • distinguishedPrimeAboveP p L))
      inferInstance).irreducible
  have hemul :
      emultiplicity (σ • distinguishedPrimeAboveP p L)
          (gaussSumIdeal (p := p) (L := L) (χ ^ (b : ZMod (p - 1)).val)) =
        emultiplicity (distinguishedPrimeAboveP p L)
          (gaussSumIdeal (p := p) (L := L) χ) := by
    simpa [σ, e, sigmaOfCharacterUnit_smul_gaussSumIdeal] using
      (emultiplicity_map_eq e
        (a := distinguishedPrimeAboveP p L)
        (b := gaussSumIdeal (p := p) (L := L) χ))
  rw [UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors hσP0_irr hIχσ,
    UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors hP0_irr hIχ,
    normalize_eq (σ • distinguishedPrimeAboveP p L),
    normalize_eq (distinguishedPrimeAboveP p L)] at hemul
  simpa [σ, primeAbovePExponent, distinguishedPrimeExponent] using hemul

end Assembly

end BernoulliRegular
