import Verso
import VersoManual
import VersoBlueprint
import VersoBlueprint.Commands.Graph
import VersoBlueprint.Commands.Summary
import «Adic spaces».HuberRings
import «Adic spaces».ValuationSpectrum
import «Adic spaces».ContinuousValuations
import «Adic spaces».AffinoidRings
import «Adic spaces».AdicSpectrum
import «Adic spaces».RationalSubsets
import «Adic spaces».AnalyticPoints
import «Adic spaces».TateAlgebra

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Adic Spaces — Lean blueprint" =>

This is the blueprint for the [`Adic-Spaces`](https://github.com/CBirkbeck/Adic-Spaces)
formalisation (Birkbeck) of _Huber's theory of adic spaces_ — the point-set
foundations of $`p`-adic geometry and perfectoid spaces, following Wedhorn's
_Adic Spaces_ notes. It develops Huber rings and Tate rings, the valuation spectrum
$`\mathrm{Spv}`, continuous valuations, rings of integral elements, the adic spectrum
$`\mathrm{Spa}`, its rational subsets and analytic locus, Tate algebras, and (in
progress) the structure sheaf.

Each node carries a `(lean := …)` reference to the actual declaration in the
`«Adic spaces»` library, so Verso reads its completion status directly from Lean.
The dependency graph at the foot of the page records how the constructions build on
one another.

# Huber rings and Tate rings

:::definition "huber-ring" (lean := "PairOfDefinition, IsHuberRing")
A topological ring $`A` is a _Huber ring_ (or _$`f`-adic ring_) if it admits a
_pair of definition_: an open subring $`A_0 \subseteq A` together with a finitely
generated ideal $`I \subseteq A_0` such that the powers $`I^n` form a neighbourhood
basis of $`0` in $`A_0`. In `Adic-Spaces` the pair is the structure
$`\texttt{PairOfDefinition}` and the predicate is the class $`\texttt{IsHuberRing}`.
Following Wedhorn §6.
:::

:::definition "tate-ring" (lean := "IsTateRing")
A _Tate ring_ is a Huber ring ({uses "huber-ring"}[]) containing a _topologically
nilpotent unit_ $`\varpi \in A^\times` with $`\varpi^n \to 0` — a
_pseudo-uniformiser_, playing the role of a uniformising parameter in
non-archimedean geometry. In `Adic-Spaces` this is the class $`\texttt{IsTateRing}`.
Following Wedhorn Definition 6.10.
:::

# The valuation spectrum and continuous valuations

:::definition "valuation-spectrum" (lean := "ValuationSpectrum, ValuationSpectrum.basicOpen, ValuationSpectrum.supp")
The _valuation spectrum_ $`\mathrm{Spv}(A)` of a commutative ring $`A` is the set of
equivalence classes of valuations on $`A`, presented as valuative relations. Its
topology is generated by the _basic open sets_
$$`\mathrm{Spv}(A)\!\left(\tfrac{f}{s}\right) = \{\, v : v(f) \le v(s) \ne 0 \,\},`
and the _support_ $`v \mapsto \{a : v(a) = 0\}` is a continuous map to
$`\mathrm{Spec}(A)`. In `Adic-Spaces`: $`\texttt{ValuationSpectrum}`,
$`\texttt{basicOpen}`, $`\texttt{supp}`. Following Wedhorn Definition 4.1.
:::

:::definition "continuous-valuation" (lean := "Valuation.IsContinuous, ValuationSpectrum.Cont")
A valuation $`v` on a topological ring $`A` is _continuous_ if for every
$`\gamma` the set $`\{\, a : v(a) < \gamma \,\}` is open ({uses "valuation-spectrum"}[]).
The continuous points form the subspace
$`\mathrm{Cont}(A) \subseteq \mathrm{Spv}(A)` ($`\texttt{Cont}`). Following Wedhorn
Definition 7.7.
:::

# The adic spectrum

:::definition "affinoid-ring" (lean := "ValuationSpectrum.IsRingOfIntegralElements, ValuationSpectrum.IsAffinoidRing")
For a topological ring $`A`, a subring $`A^{+} \subseteq A` is a _ring of integral
elements_ ($`\texttt{IsRingOfIntegralElements}`) if it is open, integrally closed in
$`A`, and contained in the power-bounded subring $`A^{\circ}` ({uses "huber-ring"}[]).
The pair $`(A, A^{+})` is then an _affinoid ring_ (Huber pair),
$`\texttt{IsAffinoidRing}`. Every ring of integral elements automatically contains all
topologically nilpotent elements. Following Wedhorn Definition 7.14.
:::

:::definition "adic-spectrum" (lean := "ValuationSpectrum.Spa, ValuationSpectrum.PlusSubring")
Let $`(A, A^{+})` be an affinoid ring ({uses "affinoid-ring"}[]). The _adic spectrum_
is the set of continuous valuations bounded by $`1` on $`A^{+}`:
$$`\mathrm{Spa}(A, A^{+}) = \{\, v \in \mathrm{Cont}(A) : v(f) \le 1 \text{ for all } f \in A^{+} \,\}`
({uses "continuous-valuation"}[]). In `Adic-Spaces`: $`\texttt{Spa}` (with the
integral subring packaged by the class $`\texttt{PlusSubring}`). This is the
fundamental functor of Huber's theory. Following Wedhorn Definition 7.23.
:::

:::definition "rational-subsets" (lean := "ValuationSpectrum.rationalOpen, ValuationSpectrum.IsRationalSubset")
For $`f_1, \dots, f_n, s \in A` generating an open ideal, the _rational subset_
$$`R\!\left(\tfrac{f_1, \dots, f_n}{s}\right) = \{\, v \in \mathrm{Spa}(A, A^{+}) : v(f_i) \le v(s) \ne 0 \,\}`
is the basic open of $`\mathrm{Spa}` cut out by $`\texttt{rationalOpen}`
({uses "adic-spectrum"}[]); $`\texttt{IsRationalSubset}` is the predicate on sets that
arise this way. Following Wedhorn Definition 7.29.
:::

:::theorem "rational-subsets-inter" (lean := "ValuationSpectrum.IsRationalSubset.inter")
The intersection of two rational subsets is again rational
({uses "rational-subsets"}[]): rational subsets form a basis of the topology of
$`\mathrm{Spa}(A, A^{+})` closed under finite intersection.
:::

:::proof "rational-subsets-inter"
Given $`R(f_i/s)` and $`R(g_j/t)`, their intersection is $`R(f_i g_j / st)`: a point
$`v` lies in both iff $`v(f_i) \le v(s)` and $`v(g_j) \le v(t)` with $`v(s), v(t) \ne 0`,
which by multiplicativity of $`v` is exactly $`v(f_i g_j) \le v(st) \ne 0`. The
numerator family of the product still generates an open ideal, so the intersection is
again a rational subset.
:::

:::definition "analytic-points" (lean := "ValuationSpectrum.IsAnalytic, ValuationSpectrum.IsTateRing.isAnalytic")
A point $`v \in \mathrm{Spa}(A, A^{+})` is _analytic_ if its support $`\ker v` is not
open — equivalently, some topologically nilpotent element is sent to a nonzero value
({uses "adic-spectrum"}[]). In `Adic-Spaces`, $`\texttt{IsAnalytic}`; when $`A` is a
Tate ring ({uses "tate-ring"}[]) _every_ point is analytic
($`\texttt{IsTateRing.isAnalytic}`), because the pseudo-uniformiser $`\varpi` is a unit
and so cannot lie in any support.
:::

# Tate algebras and the structure sheaf

:::definition "tate-algebra" (lean := "TateAlgebra")
The _Tate algebra_ $`A\langle X \rangle` over a Tate ring $`A`
({uses "tate-ring"}[]) is the ring of _restricted power series_ — those
$`\sum_n a_n X^n` whose coefficients are eventually small ($`a_n \to 0`). It is the
ring of functions on the closed unit disc and the building block of the structure
sheaf on rational subsets ({uses "rational-subsets"}[]). In `Adic-Spaces`:
$`\texttt{TateAlgebra}`. Following Wedhorn Definition 7.29.
:::

:::theorem "structure-sheaf"
_(Tate's acyclicity theorem / the structure sheaf.)_ For a strongly noetherian Tate
ring, the structure presheaf $`\mathcal{O}_X` on the rational subsets
({uses "rational-subsets"}[], {uses "tate-algebra"}[]) of $`X = \mathrm{Spa}(A, A^{+})`
is a _sheaf_: the Čech complex of a rational cover is exact (Tate acyclicity), so
sections glue. This makes $`(\mathrm{Spa}(A, A^{+}), \mathcal{O}_X)` an _adic space_.
In `Adic-Spaces`: $`\texttt{structurePresheaf\_isSheaf}` (`Adic spaces/StructureSheaf.lean`)
— _in progress_ (the Laurent-cover acyclicity and the gluing refinement carry the
remaining `sorry`s).
:::

# Dependency graph

{blueprint_graph}

# Progress summary

{blueprint_summary}
