import Verso
import VersoManual
import VersoBlueprint
import VersoBlueprint.Commands.Graph
import VersoBlueprint.Commands.Summary
import «Adic spaces».HuberRings
import «Adic spaces».ValuationSpectrum
import «Adic spaces».AffinoidRings
import «Adic spaces».AdicSpectrum
import «Adic spaces».TateAlgebra

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Adic Spaces — Lean blueprint" =>

This is the blueprint for the [`Adic-Spaces`](https://github.com/CBirkbeck/Adic-Spaces)
formalisation (Birkbeck) of *Huber's theory of adic spaces* — the foundations of
$`p`-adic geometry and perfectoid spaces, following Wedhorn's notes. It develops
Huber rings and Tate rings, the valuation spectrum $`\mathrm{Spv}`, rings of
integral elements, the adic spectrum $`\mathrm{Spa}`, Tate algebras, and (in
progress) the structure sheaf.

Each node carries a `(lean := …)` reference to the actual declaration in the
`«Adic spaces»` library, so Verso reads its completion status directly from Lean
— green once the declaration is fully proved, blue while it still contains
`sorry`. The dependency graph at the foot of the page records which results feed
into which.

# Huber rings and Tate rings

:::definition "huber-ring" (lean := "PairOfDefinition, IsHuberRing")
A topological ring $`A` is a *Huber ring* (or *$`f`-adic ring*) if it admits a
*pair of definition*: an open subring $`A_0 \subseteq A` together with a finitely
generated ideal $`I \subseteq A_0` such that the subspace topology on $`A_0`
equals the $`I`-adic topology — equivalently, the powers $`I^n` form a
neighbourhood basis of $`0` in $`A_0`. In `Adic-Spaces` the pair is the structure
$`\texttt{PairOfDefinition}` and the predicate is the class
$`\texttt{IsHuberRing}`. Following Wedhorn §6.
:::

:::definition "tate-ring" (lean := "IsTateRing")
A *Tate ring* is a Huber ring ({uses "huber-ring"}[]) that contains a
*topologically nilpotent unit* $`u \in A^\times` with $`u^n \to 0` — a
*pseudo-uniformiser*, the role of a uniformising parameter in non-archimedean
geometry. In `Adic-Spaces` this is the class $`\texttt{IsTateRing}`. Following
Wedhorn Definition 6.10.
:::

# The valuation spectrum

:::definition "valuation-spectrum" (lean := "ValuationSpectrum, ValuationSpectrum.basicOpen, ValuationSpectrum.supp")
The *valuation spectrum* $`\mathrm{Spv}(A)` of a commutative ring $`A` is the set
of equivalence classes of valuations on $`A`. A point is presented as a valuative
relation; the topology is generated by the *basic open sets*
$$`\mathrm{Spv}(A)(f/s) = \{ v : v(f) \le v(s) \ne 0 \},`
and the *support* map $`v \mapsto \{a : v(a) = 0\}` is continuous into
$`\mathrm{Spec}(A)`. In `Adic-Spaces` these are $`\texttt{ValuationSpectrum}`,
$`\texttt{basicOpen}`, and $`\texttt{supp}`. Following Wedhorn Definition 4.1.
:::

# The adic spectrum

:::definition "affinoid-ring" (lean := "ValuationSpectrum.IsRingOfIntegralElements")
For a topological ring $`A`, a subring $`A^{+} \subseteq A` is a *ring of integral
elements* ($`\texttt{IsRingOfIntegralElements}`) if it is open, integrally closed
in $`A`, and contained in the power-bounded subring $`A^{\circ}`
({uses "huber-ring"}[]). The pair $`(A, A^{+})` is then an *affinoid ring* (Huber
pair). Following Wedhorn Definition 7.14.
:::

:::definition "adic-spectrum" (lean := "ValuationSpectrum.Spa, ValuationSpectrum.PlusSubring")
Let $`(A, A^{+})` be an affinoid ring ({uses "affinoid-ring"}[]). The *adic
spectrum* is
$$`\mathrm{Spa}(A, A^{+}) = \{ v \in \mathrm{Cont}(A) : v(f) \le 1 \text{ for all } f \in A^{+} \},`
the continuous valuations bounded by $`1` on $`A^{+}` ({uses "valuation-spectrum"}[]).
In `Adic-Spaces` this is $`\texttt{ValuationSpectrum.Spa}` (with the integral
subring packaged by the class $`\texttt{PlusSubring}`). This is the fundamental
functor of Huber's theory. Following Wedhorn Definition 7.23.
:::

# Tate algebras and the structure sheaf

:::definition "tate-algebra" (lean := "TateAlgebra")
The *Tate algebra* $`A\langle X \rangle` over a Tate ring $`A`
({uses "tate-ring"}[]) is the ring of restricted power series — those whose
coefficients tend to $`0` — the building block of the structure sheaf on rational
subsets of $`\mathrm{Spa}(A, A^{+})`. In `Adic-Spaces` this is
$`\texttt{TateAlgebra}`. Following Wedhorn Definition 7.29.
:::

:::theorem "structure-sheaf"
*(Tate's acyclicity theorem / the structure sheaf.)* For a strongly noetherian
Tate ring, the structure presheaf $`\mathcal{O}_X` on the rational subsets of
$`X = \mathrm{Spa}(A, A^{+})` ({uses "adic-spectrum"}[], {uses "tate-algebra"}[])
is a *sheaf*: the Čech complex of a rational cover is exact (Tate acyclicity),
so sections glue. This makes $`(\mathrm{Spa}(A, A^{+}), \mathcal{O}_X)` an
*adic space*.
In `Adic-Spaces`: $`\texttt{structurePresheaf\_isSheaf}` (`Adic spaces/StructureSheaf.lean`)
— *in progress* (the Laurent-cover acyclicity and the gluing refinement carry the
remaining `sorry`s).
:::

# Dependency graph

{blueprint_graph}

# Progress summary

{blueprint_summary}
