/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LeanModularForms contributors
-/
import LeanModularForms.HeckeRIngs.GL2.AdjointTheory
import LeanModularForms.HeckeRIngs.GL2.Gamma1Pair
import LeanModularForms.HeckeRIngs.GL2.Newforms.Basic
import LeanModularForms.HeckeRIngs.GL2.Newforms.FullEigenform

/-!
# The integral Hecke algebra and Hecke-eigenvalue arithmetic

This file builds the **integral Hecke algebra** `heckeAlgℤ N k` — the `ℤ`-subalgebra of
`End_ℂ(S_k(Γ₁N))` generated by the cusp Hecke operators `T_n` (the `U_p` at bad primes) together
with the diamond operators — and, modulo the single finiteness input `heckeAlgℤ_finite` (FIH,
justified by the integral modular-symbol / Eichler–Shimura realization), derives that the Fourier
coefficients of a newform are algebraic integers and that the coefficient field is a number field.

## Main definitions
* `heckeEnd N k n` — the `n`-th cusp Hecke operator as a `ℂ`-linear endomorphism.
* `heckeAlgℤ N k` — the integral Hecke algebra (a `ℤ`-subalgebra of `End_ℂ(S_k(Γ₁N))`).
-/

namespace HeckeRing.GL2

open CongruenceSubgroup Matrix.SpecialLinearGroup CuspForm
open HeckeRing.GL2.Unified
open scoped MatrixGroups ModularForm Pointwise DirectSum

variable {N : ℕ} [NeZero N] {k : ℤ}

/-- The `n`-th cusp Hecke operator `T_n` (`U_p` at primes dividing `N`) as a `ℂ`-linear
endomorphism of the cusp-form space. -/
noncomputable def heckeEnd (N : ℕ) [NeZero N] (k : ℤ) (n : ℕ+) :
    Module.End ℂ (CuspForm ((Gamma1 N).map (mapGL ℝ)) k) :=
  { toFun := heckeT_n_cusp k n.val
    map_add' := heckeT_n_cusp_add n.val
    map_smul' := fun c f => heckeT_n_cusp_smul n.val c f }

/-- The **integral Hecke algebra**: the `ℤ`-subalgebra of `End_ℂ(S_k(Γ₁N))` generated by all the
cusp Hecke operators and the diamond operators. -/
noncomputable def heckeAlgℤ (N : ℕ) [NeZero N] (k : ℤ) :
    Subalgebra ℤ (Module.End ℂ (CuspForm ((Gamma1 N).map (mapGL ℝ)) k)) :=
  Algebra.adjoin ℤ (Set.range (heckeEnd N k) ∪ Set.range (diamondOpCusp (N := N) k))

theorem heckeEnd_mem (n : ℕ+) : heckeEnd N k n ∈ heckeAlgℤ N k :=
  Algebra.subset_adjoin (Or.inl ⟨n, rfl⟩)

theorem diamondOpCusp_mem (d : (ZMod N)ˣ) : diamondOpCusp k d ∈ heckeAlgℤ N k :=
  Algebra.subset_adjoin (Or.inr ⟨d, rfl⟩)

/-! ### [T003] The newform eigensystem ring hom `newformEigenHom`

A `Newform f` is a simultaneous eigenvector of every generator of `heckeAlgℤ` — the cusp Hecke
operators `T_n` (all `n`, by `Newform.isFullEigenform` = DS Thm 5.8.2(a)) and the diamond
operators `⟨d⟩` (by the Nebentypus character `χ`).  The eigenline-preserving endomorphisms form a
subalgebra, so *every* element of `heckeAlgℤ` acts on `f` by a scalar; the eigenvalue map
`heckeAlgℤ → ℂ` is a ring homomorphism. -/

/-- A newform is nonzero: its normalised first Fourier coefficient is `1 ≠ 0`. -/
theorem Newform.toCuspForm_ne_zero (f : Newform N k) : f.toCuspForm ≠ 0 := fun h => by
  simpa only [h, CuspForm.coe_zero, UpperHalfPlane.qExpansion_zero, map_zero, zero_ne_one]
    using f.isNorm

/-- Every element of `heckeAlgℤ` maps the newform `f` into its eigenline `ℂ ∙ f`: the
generators do (`isFullEigenform` for Hecke ops, the character `χ` for diamonds) and the
eigenline-preserving endomorphisms form a subalgebra. -/
theorem Newform.heckeAlg_smul_mem_span (f : Newform N k)
    {T : Module.End ℂ (CuspForm ((Gamma1 N).map (mapGL ℝ)) k)} (hT : T ∈ heckeAlgℤ N k) :
    T f.toCuspForm ∈ Submodule.span ℂ {f.toCuspForm} := by
  obtain ⟨a, ha⟩ := f.isFullEigenform
  induction hT using Algebra.adjoin_induction with
  | mem T hT =>
    rcases hT with ⟨n, rfl⟩ | ⟨d, rfl⟩
    · rw [show (heckeEnd N k n) f.toCuspForm = heckeT_n_cusp k n.val f.toCuspForm from rfl, ha n]
      exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)
    · rw [show (diamondOpCusp k d) f.toCuspForm = diamondOpCuspHom k d f.toCuspForm from rfl,
        diamondOpCusp_apply_charSpace k f.χ d
          (cuspFormCharSpace_of_toModularForm'_mem f.mem_charSpace)]
      exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)
  | algebraMap r =>
    rw [Algebra.algebraMap_eq_smul_one, LinearMap.smul_apply, Module.End.one_apply]
    exact zsmul_mem (Submodule.mem_span_singleton_self _) r
  | add x y _ _ ihx ihy =>
    rw [LinearMap.add_apply]
    exact Submodule.add_mem _ ihx ihy
  | mul x y _ _ ihx ihy =>
    rw [Module.End.mul_apply]
    obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp ihy
    rw [← hc, map_smul]
    exact Submodule.smul_mem _ _ ihx

/-- The scalar by which `T ∈ heckeAlgℤ` acts on the newform eigenline `ℂ ∙ f`. -/
noncomputable def Newform.eigenScalar (f : Newform N k) (T : heckeAlgℤ N k) : ℂ :=
  (Submodule.mem_span_singleton.mp (f.heckeAlg_smul_mem_span T.2)).choose

theorem Newform.eigenScalar_smul (f : Newform N k) (T : heckeAlgℤ N k) :
    f.eigenScalar T • f.toCuspForm = (T : Module.End ℂ _) f.toCuspForm :=
  (Submodule.mem_span_singleton.mp (f.heckeAlg_smul_mem_span T.2)).choose_spec

/-- The eigenline scalar is unique (`f ≠ 0`): any `c` with `c • f = T f` equals `eigenScalar T`. -/
theorem Newform.eigenScalar_eq (f : Newform N k) (T : heckeAlgℤ N k) {c : ℂ}
    (h : c • f.toCuspForm = (T : Module.End ℂ _) f.toCuspForm) : f.eigenScalar T = c :=
  smul_left_injective ℂ f.toCuspForm_ne_zero <|
    show f.eigenScalar T • f.toCuspForm = c • f.toCuspForm by rw [f.eigenScalar_smul T, ← h]

/-- **[T003]** The newform eigensystem ring homomorphism `heckeAlgℤ → ℂ`: it sends each Hecke
operator to the scalar by which it acts on the simultaneous eigenvector `f`. -/
noncomputable def newformEigenHom (f : Newform N k) : heckeAlgℤ N k →+* ℂ where
  toFun := f.eigenScalar
  map_one' := f.eigenScalar_eq 1 (by simp)
  map_mul' T₁ T₂ := f.eigenScalar_eq (T₁ * T₂) (by
    rw [Subalgebra.coe_mul, Module.End.mul_apply, ← f.eigenScalar_smul T₂, map_smul,
      ← f.eigenScalar_smul T₁, smul_smul, mul_comm (f.eigenScalar T₂) (f.eigenScalar T₁)])
  map_zero' := f.eigenScalar_eq 0 (by simp)
  map_add' T₁ T₂ := f.eigenScalar_eq (T₁ + T₂) (by
    rw [Subalgebra.coe_add, LinearMap.add_apply, ← f.eigenScalar_smul T₁,
      ← f.eigenScalar_smul T₂, add_smul])

/-- On a coprime cusp Hecke operator, `newformEigenHom` returns the classical eigenvalue. -/
theorem newformEigenHom_heckeEnd (f : Newform N k) (n : ℕ+) (hn : Nat.Coprime n.val N) :
    newformEigenHom f ⟨heckeEnd N k n, heckeEnd_mem n⟩ = f.eigenvalue n := by
  refine f.eigenScalar_eq _ ?_
  show f.eigenvalue n • f.toCuspForm = heckeT_n_cusp k n.val f.toCuspForm
  rw [f.isEigen n hn]

/-! ### [T002 / FIH] The isolated finiteness input + the eigenvalue ring `O_f`

`heckeAlgℤ_finite` is the single deep classical input (the integral Hecke algebra is a finite
`ℤ`-module).  Our generators `ℤ[Tₙ, ⟨d⟩]` match the source Hecke algebra exactly (Shimura
Thm 3.34(1) p.70; Miyake Thm 4.5.9 p.142).  Module-finiteness comes from the action on a
**full-rank** Hecke-stable free `ℤ`-lattice `Λ ⊆ S_k(Γ₁N)`: `heckeAlgℤ ↪ End_ℤ(Λ) ≅ M_r(ℤ)`
(Shimura (3.5.20)+ρ₀ p.84, the faithful integral representation; the lattice realized by the
integral `q`-expansion basis Shimura Thm 3.52 p.85 / Miyake Thm 4.5.19(2) p.152; DS weight-2
analogue Defn 6.5.2 + Ex 6.5.1 via `H₁(X₁N,ℤ)`).
The deep content is the lattice's **maximal rank** (`Λ ⊗ ℂ = S_k`, the rationality / q-expansion
principle) — absent from mathlib.  It is stated as a `sorry` instance here; everything downstream
consumes it as a black box. -/

/-- A **full-rank** (Shimura (3.5.20) "maximal rank"), Hecke-stable, finite free `ℤ`-lattice
inside `S_k(Γ₁N)`.  `spanning` (`Λ ⊗ ℂ = S_k`) is the deep content; faithfulness of the
`heckeAlgℤ`-action is *derived* from it, never assumed. -/
structure HeckeStableLattice (N : ℕ) [NeZero N] (k : ℤ) where
  /-- The underlying `ℤ`-submodule of cusp forms. -/
  toSubmodule : Submodule ℤ (CuspForm ((Gamma1 N).map (mapGL ℝ)) k)
  /-- The lattice is `ℤ`-free. -/
  free : Module.Free ℤ toSubmodule
  /-- The lattice is finitely generated over `ℤ`. -/
  finite : Module.Finite ℤ toSubmodule
  /-- **Maximal rank**: the `ℂ`-span is everything (the rationality / `q`-expansion principle). -/
  spanning : Submodule.span ℂ (toSubmodule : Set (CuspForm ((Gamma1 N).map (mapGL ℝ)) k)) = ⊤
  /-- The lattice is stable under every element of the integral Hecke algebra. -/
  stable : ∀ T ∈ heckeAlgℤ N k, ∀ x ∈ toSubmodule, T x ∈ toSubmodule

/-- **(FIH — T002, the single isolated research input)** A full-rank Hecke-stable `ℤ`-lattice in
`S_k(Γ₁N)` exists: the integral Eichler–Shimura / integral-`q`-expansion basis (Shimura Thm 3.52
p.85, Miyake Thm 4.5.19(2) p.152; DS weight-2 `H₁(X₁N,ℤ)`).  Absent from mathlib; the one
`sorry`. -/
theorem exists_HeckeStableLattice (N : ℕ) [NeZero N] (k : ℤ) :
    Nonempty (HeckeStableLattice N k) := sorry

/-- **[T002-L1, the bounded endgame]** The integral Hecke algebra is a finite `ℤ`-module — the
faithful integral representation on a full-rank Hecke-stable lattice (Shimura (3.5.20)+ρ₀ p.84; DS
Ex 6.5.1: `heckeAlgℤ ↪ End_ℤ(Λ) ≅ M_r(ℤ)`, a sub-`ℤ`-module of a finite free module).  Faithfulness
is *derived* from `spanning` (full rank).

This is the lattice route.  The live `Module.Finite ℤ (heckeAlgℤ N k)` *instance* is installed in
`Labels/HeckeAlgFiniteFinal.lean` (downstream), where the `k ≥ 2` case is rerouted through the
integral modular-symbol period map (`heckeAlgℤ_finite_of_period`) and only the `k < 2` case is taken
from this lattice route. -/
theorem heckeAlgℤ_finite_of_lattice (N : ℕ) [NeZero N] (k : ℤ) :
    Module.Finite ℤ (heckeAlgℤ N k) := by
  obtain ⟨H⟩ := exists_HeckeStableLattice N k
  haveI := H.free
  haveI := H.finite
  -- the restriction `ℤ`-linear map `Φ : heckeAlgℤ → End_ℤ(Λ)`, `T ↦ T|_Λ`
  let Φ : heckeAlgℤ N k →ₗ[ℤ] (H.toSubmodule →ₗ[ℤ] H.toSubmodule) :=
    { toFun := fun T => (T.1.restrictScalars ℤ).restrict (fun x hx => H.stable T.1 T.2 x hx)
      map_add' := fun T₁ T₂ => by ext x; rfl
      map_smul' := fun c T => by ext x; rfl }
  -- `Φ` is injective: `T|_Λ = 0` ⟹ `T = 0` on `span ℂ Λ = ⊤` (full rank ⟹ faithful)
  have hinj : Function.Injective Φ := by
    intro T₁ T₂ hT
    refine Subtype.ext (LinearMap.ext_on H.spanning (fun x hx => ?_))
    exact congrArg Subtype.val (LinearMap.congr_fun hT ⟨x, hx⟩)
  -- `End_ℤ(Λ)` is module-finite (Λ finite free), so its sub-`ℤ`-module `heckeAlgℤ` is too
  exact Module.Finite.of_injective Φ hinj

end HeckeRing.GL2
