module

public import BernoulliRegular.TotallyRealSubfield

/-!
# Primary elements of cyclotomic rings of integers (ticket FLT37b2, scaffold)

For a prime `p`, an element `α ∈ 𝒪_K` of the cyclotomic ring is **primary**
when it is congruent to a rational integer modulo `(ζ - 1)^{2p}`. Following
Vandiver, this is the standard hypothesis under which an `ℓ`-th power ideal
generated by `α` descends through complex conjugation.

This file isolates the definition `IsPrimary` and its basic lemmas. The
deeper consequences — primarity forces `[(α)]` to be `σ`-fixed in the class
group, and hence to descend via `classGroupMap_injective` — are treated in
the companion ticket FLT37b3 once the descent skeleton FLT37b1 is plugged in.

## References

* Washington, *Introduction to Cyclotomic Fields*, §6.4 (definition).
* Borevich–Shafarevich, *Number Theory*, §4.9 (use in Vandiver Lemma 1).
* `FltRegular.NumberTheory.Cyclotomic.MoreLemmas`
  (`zeta_sub_one_dvd_Int_iff`, `exists_zeta_sub_one_dvd_sub_Int`).
-/

@[expose] public section

noncomputable section

open NumberField IsCyclotomicExtension
open scoped NumberField nonZeroDivisors

namespace BernoulliRegular

namespace FLT37

section CyclotomicSetup

variable (p : ℕ) [hp : Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

local notation3 "ζ" => IsCyclotomicExtension.zeta p ℚ K

/-- The element `ζ - 1 ∈ 𝒪_K`, where `ζ` is the standard primitive `p`-th
root of unity supplied by `IsCyclotomicExtension`. This is a uniformizer at
the unique prime above `p`. -/
noncomputable def zetaSubOne : 𝓞 K :=
  (zeta_spec p ℚ K).toInteger - 1

variable {p K} in
@[simp]
theorem zetaSubOne_def :
    (zetaSubOne p K : 𝓞 K) = (zeta_spec p ℚ K).toInteger - 1 :=
  rfl

/-- The image of `zetaSubOne p K` in `K` via the algebra map is `ζ - 1`. -/
theorem algebraMap_zetaSubOne :
    algebraMap (𝓞 K) K (zetaSubOne p K) = ζ - 1 := by
  rw [zetaSubOne_def]
  push_cast
  rfl

/-- **Norm of `ζ - 1` (rational form).** For an odd prime `p` and the cyclotomic
field `K = ℚ(ζ_p)`, the field-level norm of `ζ - 1` is `p`. -/
theorem zetaSubOne_norm_rat (hp_odd : p ≠ 2) :
    Algebra.norm ℚ (algebraMap (𝓞 K) K (zetaSubOne p K)) = (p : ℚ) := by
  rw [algebraMap_zetaSubOne]
  have h_irr := Polynomial.cyclotomic.irreducible_rat hp.1.pos
  have h_norm := (zeta_spec p ℚ K).sub_one_norm_isPrimePow hp.1.isPrimePow h_irr hp_odd
  rw [h_norm, Nat.Prime.minFac_eq hp.1]

/-- **Integer norm of `ζ - 1`.** For an odd prime `p`, the integer norm of
`zetaSubOne p K` (the algebraic integer norm `𝓞 K → ℤ`) is `p`. -/
theorem zetaSubOne_intNorm (hp_odd : p ≠ 2) :
    Algebra.intNorm ℤ (𝓞 K) (zetaSubOne p K) = (p : ℤ) := by
  apply (algebraMap ℤ ℚ).injective_int
  rw [Algebra.algebraMap_intNorm (K := ℚ) (L := K),
    zetaSubOne_norm_rat p K hp_odd]
  push_cast
  rfl

/-- **Integer norm of `ζ - 1` (Algebra.norm form).** Equivalent restatement
using `Algebra.norm ℤ : 𝓞 K → ℤ` directly. -/
theorem zetaSubOne_norm_int (hp_odd : p ≠ 2) :
    Algebra.norm ℤ (zetaSubOne p K) = (p : ℤ) := by
  have h_rat := zetaSubOne_norm_rat p K hp_odd
  have h_coe : ((Algebra.norm ℤ (zetaSubOne p K) : ℤ) : ℚ) =
      Algebra.norm ℚ (algebraMap (𝓞 K) K (zetaSubOne p K)) :=
    Algebra.coe_norm_int _
  rw [h_rat] at h_coe
  exact_mod_cast h_coe

/-- **Integer norm of `(ζ - 1)^n`.** Powers of `zetaSubOne` have integer
norm `p^n`. -/
theorem zetaSubOne_pow_norm_int (hp_odd : p ≠ 2) (n : ℕ) :
    Algebra.norm ℤ (zetaSubOne p K ^ n) = (p : ℤ) ^ n := by
  rw [map_pow, zetaSubOne_norm_int p K hp_odd]

/-- `zetaSubOne p K` is a prime element of `𝓞 K`. -/
theorem zetaSubOne_prime : Prime (zetaSubOne p K) :=
  (zeta_spec p ℚ K).zeta_sub_one_prime'

/-- `zetaSubOne p K` is non-zero. -/
theorem zetaSubOne_ne_zero : zetaSubOne p K ≠ 0 :=
  (zetaSubOne_prime p K).ne_zero

/-- `zetaSubOne p K` is not a unit. -/
theorem zetaSubOne_not_isUnit : ¬ IsUnit (zetaSubOne p K) :=
  (zetaSubOne_prime p K).not_unit

/-- The principal ideal generated by `zetaSubOne p K` is exactly `zetaPrime p K`. -/
theorem span_zetaSubOne_eq_zetaPrime :
    Ideal.span ({zetaSubOne p K} : Set (𝓞 K)) = BernoulliRegular.zetaPrime p K := rfl

/-- **Norm of `ζ^k - 1`.** For an odd prime `p` and `k` coprime to `p`,
the field-level norm of `ζ^k - 1` over `ℚ` is `p`. -/
theorem zeta_pow_sub_one_norm_rat (hp_odd : p ≠ 2) (k : ℕ) (hk : k.Coprime p) :
    Algebra.norm ℚ (ζ ^ k - 1) = (p : ℚ) := by
  have hζk : IsPrimitiveRoot (ζ ^ k) p :=
    (zeta_spec p ℚ K).pow_of_coprime k hk
  have h_irr := Polynomial.cyclotomic.irreducible_rat hp.1.pos
  rw [hζk.sub_one_norm_isPrimePow hp.1.isPrimePow h_irr hp_odd, Nat.Prime.minFac_eq hp.1]

variable {K}

/-- An element `α ∈ 𝒪_K` is **primary** when it is congruent to some rational
integer modulo `(ζ - 1)^{2p}`. -/
def IsPrimary (α : 𝓞 K) : Prop :=
  ∃ a : ℤ, (zetaSubOne p K) ^ (2 * p) ∣ α - (a : 𝓞 K)

/-- An element `α ∈ 𝒪_K` is **semi-primary** when it is congruent to some
rational integer modulo `(ζ - 1)^2`.

This is the congruence strength used in the classical principal-unit-factor
argument: the stronger project convention `IsPrimary`, modulo
`(ζ - 1)^{2p}`, implies this immediately. -/
def IsSemiPrimary (α : 𝓞 K) : Prop :=
  ∃ a : ℤ, (zetaSubOne p K) ^ 2 ∣ α - (a : 𝓞 K)

namespace IsSemiPrimary

variable {p}

/-- Every rational integer is semi-primary. -/
theorem of_intCast (a : ℤ) : IsSemiPrimary p (K := K) (a : 𝓞 K) :=
  ⟨a, by simp⟩

/-- Every natural number cast is semi-primary. -/
theorem of_natCast (a : ℕ) : IsSemiPrimary p (K := K) (a : 𝓞 K) := by
  have : ((a : ℤ) : 𝓞 K) = (a : 𝓞 K) := by push_cast; rfl
  exact this ▸ of_intCast (a : ℤ)

/-- Zero is semi-primary. -/
theorem zero : IsSemiPrimary p (K := K) 0 :=
  ⟨0, by simp⟩

/-- One is semi-primary. -/
theorem one : IsSemiPrimary p (K := K) 1 :=
  ⟨1, by simp⟩

/-- The negation of a semi-primary element is semi-primary. -/
theorem neg {α : 𝓞 K} (hα : IsSemiPrimary p α) : IsSemiPrimary p (-α) := by
  obtain ⟨a, ha⟩ := hα
  refine ⟨-a, ?_⟩
  have : (-α) - ((-a : ℤ) : 𝓞 K) = -(α - (a : 𝓞 K)) := by push_cast; ring
  rw [this]
  exact ha.neg_right

/-- `IsSemiPrimary` is preserved by `Neg.neg` in both directions. -/
@[simp]
theorem neg_iff {α : 𝓞 K} : IsSemiPrimary p (-α) ↔ IsSemiPrimary p α :=
  ⟨fun h => by simpa using h.neg, fun h => h.neg⟩

/-- The sum of two semi-primary elements is semi-primary. -/
theorem add {α β : 𝓞 K} (hα : IsSemiPrimary p α) (hβ : IsSemiPrimary p β) :
    IsSemiPrimary p (α + β) := by
  obtain ⟨a, ha⟩ := hα
  obtain ⟨b, hb⟩ := hβ
  refine ⟨a + b, ?_⟩
  have : (α + β) - ((a + b : ℤ) : 𝓞 K) =
      (α - (a : 𝓞 K)) + (β - (b : 𝓞 K)) := by push_cast; ring
  rw [this]
  exact dvd_add ha hb

/-- The product of two semi-primary elements is semi-primary. -/
theorem mul {α β : 𝓞 K} (hα : IsSemiPrimary p α) (hβ : IsSemiPrimary p β) :
    IsSemiPrimary p (α * β) := by
  obtain ⟨a, ha⟩ := hα
  obtain ⟨b, hb⟩ := hβ
  refine ⟨a * b, ?_⟩
  have heq : α * β - ((a * b : ℤ) : 𝓞 K) =
      (α - (a : 𝓞 K)) * β + (a : 𝓞 K) * (β - (b : 𝓞 K)) := by
    push_cast; ring
  rw [heq]
  exact dvd_add (ha.mul_right _) (hb.mul_left _)

/-- The difference of two semi-primary elements is semi-primary. -/
theorem sub {α β : 𝓞 K} (hα : IsSemiPrimary p α) (hβ : IsSemiPrimary p β) :
    IsSemiPrimary p (α - β) := by
  rw [sub_eq_add_neg]
  exact hα.add hβ.neg

/-- The product of a semi-primary element and an integer cast is
semi-primary. -/
theorem int_mul {α : 𝓞 K} (hα : IsSemiPrimary p α) (a : ℤ) :
    IsSemiPrimary p ((a : 𝓞 K) * α) :=
  (of_intCast a).mul hα

/-- The product of an integer cast and a semi-primary element is
semi-primary. -/
theorem mul_int {α : 𝓞 K} (hα : IsSemiPrimary p α) (a : ℤ) :
    IsSemiPrimary p (α * (a : 𝓞 K)) :=
  hα.mul (of_intCast a)

end IsSemiPrimary

namespace IsPrimary

variable {p}

/-- Every rational integer is primary. -/
theorem of_intCast (a : ℤ) : IsPrimary p (K := K) (a : 𝓞 K) :=
  ⟨a, by simp⟩

/-- Every natural number cast is primary. -/
theorem of_natCast (a : ℕ) : IsPrimary p (K := K) (a : 𝓞 K) := by
  have : ((a : ℤ) : 𝓞 K) = (a : 𝓞 K) := by push_cast; rfl
  exact this ▸ of_intCast (a : ℤ)

/-- Zero is primary. -/
theorem zero : IsPrimary p (K := K) 0 :=
  ⟨0, by simp⟩

/-- One is primary. -/
theorem one : IsPrimary p (K := K) 1 :=
  ⟨1, by simp⟩

/-- The negation of a primary element is primary. -/
theorem neg {α : 𝓞 K} (hα : IsPrimary p α) : IsPrimary p (-α) := by
  obtain ⟨a, ha⟩ := hα
  refine ⟨-a, ?_⟩
  have : (-α) - ((-a : ℤ) : 𝓞 K) = -(α - (a : 𝓞 K)) := by push_cast; ring
  rw [this]
  exact ha.neg_right

/-- `IsPrimary` is preserved by `Neg.neg` in both directions. -/
@[simp]
theorem neg_iff {α : 𝓞 K} : IsPrimary p (-α) ↔ IsPrimary p α :=
  ⟨fun h => by simpa using h.neg, fun h => h.neg⟩

/-- The sum of two primary elements is primary. -/
theorem add {α β : 𝓞 K} (hα : IsPrimary p α) (hβ : IsPrimary p β) :
    IsPrimary p (α + β) := by
  obtain ⟨a, ha⟩ := hα
  obtain ⟨b, hb⟩ := hβ
  refine ⟨a + b, ?_⟩
  have : (α + β) - ((a + b : ℤ) : 𝓞 K) = (α - (a : 𝓞 K)) + (β - (b : 𝓞 K)) := by
    push_cast; ring
  rw [this]
  exact dvd_add ha hb

/-- The product of two primary elements is primary. -/
theorem mul {α β : 𝓞 K} (hα : IsPrimary p α) (hβ : IsPrimary p β) :
    IsPrimary p (α * β) := by
  obtain ⟨a, ha⟩ := hα
  obtain ⟨b, hb⟩ := hβ
  refine ⟨a * b, ?_⟩
  have heq : α * β - ((a * b : ℤ) : 𝓞 K) =
      (α - (a : 𝓞 K)) * β + (a : 𝓞 K) * (β - (b : 𝓞 K)) := by
    push_cast; ring
  rw [heq]
  exact dvd_add (ha.mul_right _) (hb.mul_left _)

/-- The difference of two primary elements is primary. -/
theorem sub {α β : 𝓞 K} (hα : IsPrimary p α) (hβ : IsPrimary p β) :
    IsPrimary p (α - β) := by
  rw [sub_eq_add_neg]
  exact hα.add hβ.neg

/-- A primary element raised to a natural-number power is primary. -/
theorem pow {α : 𝓞 K} (hα : IsPrimary p α) (n : ℕ) :
    IsPrimary p (α ^ n) := by
  induction n with
  | zero => simpa using IsPrimary.one
  | succ n ih => rw [pow_succ]; exact ih.mul hα

/-- The product of a primary element and an integer cast is primary. -/
theorem int_mul {α : 𝓞 K} (hα : IsPrimary p α) (a : ℤ) :
    IsPrimary p ((a : 𝓞 K) * α) :=
  (of_intCast a).mul hα

/-- The product of an integer cast and a primary element is primary. -/
theorem mul_int {α : 𝓞 K} (hα : IsPrimary p α) (a : ℤ) :
    IsPrimary p (α * (a : 𝓞 K)) :=
  hα.mul (of_intCast a)

/-- A primary element is congruent to *some* rational integer modulo
`(ζ - 1)^{2p}` — the witness is the integer `a` from the definition. -/
theorem exists_int_dvd_sub {α : 𝓞 K} (hα : IsPrimary p α) :
    ∃ a : ℤ, (zetaSubOne p K) ^ (2 * p) ∣ α - (a : 𝓞 K) := hα

/-- A primary element is congruent to *some* rational integer modulo any
lesser power of `(ζ - 1)`: from `α - a ∈ ((ζ-1))^{2p}` follows
`α - a ∈ ((ζ-1))^k` for every `k ≤ 2p`. -/
theorem exists_int_dvd_sub_of_le {α : 𝓞 K} (hα : IsPrimary p α)
    {k : ℕ} (hk : k ≤ 2 * p) :
    ∃ a : ℤ, (zetaSubOne p K) ^ k ∣ α - (a : 𝓞 K) := by
  obtain ⟨a, ha⟩ := hα
  exact ⟨a, dvd_trans (pow_dvd_pow _ hk) ha⟩

/-- The project-level strong primary congruence implies the classical
semi-primary congruence. -/
theorem toIsSemiPrimary {α : 𝓞 K} (hα : IsPrimary p α) :
    IsSemiPrimary p (K := K) α := by
  have hp_one : 1 ≤ p := hp.1.pos
  have hle : 2 ≤ 2 * p := by
    simpa using Nat.mul_le_mul_left 2 hp_one
  exact exists_int_dvd_sub_of_le hα hle

/-- A primary element is congruent to *some* rational integer modulo `(ζ - 1)`. -/
theorem exists_int_zetaSubOne_dvd_sub {α : 𝓞 K} (hα : IsPrimary p α) :
    ∃ a : ℤ, (zetaSubOne p K) ∣ α - (a : 𝓞 K) := by
  have hp_pos : 0 < 2 * p := by have := hp.1.pos; omega
  obtain ⟨a, ha⟩ := exists_int_dvd_sub_of_le hα (show 1 ≤ 2 * p from hp_pos)
  exact ⟨a, by rwa [pow_one] at ha⟩

/-- Ideal-form of primarity: `α - a ∈ zetaPrime^{2p}`, equivalent to
`(zeta - 1)^{2p} ∣ α - a`. -/
theorem exists_int_mem_zetaPrime_pow_sub {α : 𝓞 K} (hα : IsPrimary p α) :
    ∃ a : ℤ, α - (a : 𝓞 K) ∈ BernoulliRegular.zetaPrime p K ^ (2 * p) := by
  obtain ⟨a, ha⟩ := hα
  refine ⟨a, ?_⟩
  rw [show BernoulliRegular.zetaPrime p K ^ (2 * p) =
    Ideal.span ({zetaSubOne p K ^ (2 * p)} : Set (𝓞 K)) by
      rw [← span_zetaSubOne_eq_zetaPrime, Ideal.span_singleton_pow]]
  exact Ideal.mem_span_singleton.mpr ha

/-- **Constructive form of primarity:** for primary `α`, there exists an
integer `a` and an element `η ∈ 𝓞 K` such that `α = a + (ζ-1)^{2p} · η`. -/
theorem exists_int_eq_add_zetaSubOne_pow_mul {α : 𝓞 K} (hα : IsPrimary p α) :
    ∃ (a : ℤ) (η : 𝓞 K), α = (a : 𝓞 K) + zetaSubOne p K ^ (2 * p) * η := by
  obtain ⟨a, η, hη⟩ := hα
  refine ⟨a, η, ?_⟩
  linear_combination hη

/-- **Constructive characterization of `IsPrimary`:** `IsPrimary p α` iff
there exist `a : ℤ` and `η : 𝓞 K` with `α = a + (ζ-1)^{2p} · η`. -/
theorem isPrimary_iff_exists_int_eq_add_zetaSubOne_pow_mul {α : 𝓞 K} :
    IsPrimary p α ↔ ∃ (a : ℤ) (η : 𝓞 K),
      α = (a : 𝓞 K) + zetaSubOne p K ^ (2 * p) * η := by
  refine ⟨exists_int_eq_add_zetaSubOne_pow_mul, fun ⟨a, η, hα⟩ => ⟨a, η, ?_⟩⟩
  linear_combination hα

end IsPrimary

/-!
## Hyperprimary elements (REF-18c2d-main-a)

A stronger condition needed for the symmetric Kummer–Furtwängler
reciprocity. An element `α ∈ 𝒪_K` is **hyperprimary** when it is
locally a `p`-th power at the prime `λ = 1 - ζ_p`, i.e.
`α ∈ K_λ^{×p}`.

The reviewer-recommended encoding is the literal local-field form
`α ∈ K_λ^{×p}`. As a working substitute (until the local-field
equivalence is formalised), we use the classical **congruence form**:

  `α ≡ β^p (mod λ^{p+1})` for some `β ∈ 𝒪_K`.

Reference: Lemmermeyer, *Reciprocity Laws*, §11; Ireland–Rosen,
Ch. 14.

The exact equivalence between the congruence form and the local
`p`-th-power condition (and the precise exponent) is a separate
ticket; the current definition is the working hypothesis used by
`kummer_furtwaengler_reciprocity_hyperprimary` (REF-18c2d-main-c)
and `singular_hyperprimary_principal_symbol_eq_zero`
(REF-18c2d-main-d).
-/

/-- An element `α ∈ 𝒪_K` is **hyperprimary** when it is congruent to a
`p`-th power modulo `λ^{p+1}`, where `λ = 1 - ζ_p`.

This is the working congruence form of the local `p`-th-power
condition `α ∈ K_λ^{×p}`. The precise local-field equivalence is
deferred to a separate ticket. -/
def IsHyperprimary (α : 𝓞 K) : Prop :=
  ∃ β : 𝓞 K, zetaSubOne p K ^ (p + 1) ∣ α - β ^ p

namespace IsHyperprimary

/-- Every `p`-th power is hyperprimary. -/
theorem of_pow (β : 𝓞 K) : IsHyperprimary p (K := K) (β ^ p) :=
  ⟨β, by simp⟩

/-- One is hyperprimary. -/
theorem one : IsHyperprimary p (K := K) 1 := by
  refine ⟨1, ?_⟩
  simp

/-- The product of two hyperprimary elements is hyperprimary. -/
theorem mul {α γ : 𝓞 K} (hα : IsHyperprimary p α) (hγ : IsHyperprimary p γ) :
    IsHyperprimary p (α * γ) := by
  obtain ⟨β, hβ⟩ := hα
  obtain ⟨δ, hδ⟩ := hγ
  refine ⟨β * δ, ?_⟩
  -- α γ - (β δ)^p = α γ - β^p δ^p
  --             = α γ - α δ^p + α δ^p - β^p δ^p
  --             = α (γ - δ^p) + δ^p (α - β^p).
  have hsplit : α * γ - (β * δ) ^ p
      = α * (γ - δ ^ p) + δ ^ p * (α - β ^ p) := by
    ring
  rw [hsplit]
  exact dvd_add (Dvd.dvd.mul_left hδ _) (Dvd.dvd.mul_left hβ _)

/-- The hyperprimarity congruence in additive form. -/
theorem exists_pow_add_zetaSubOne_pow_mul {α : 𝓞 K} (h : IsHyperprimary p α) :
    ∃ (β : 𝓞 K) (η : 𝓞 K),
      α = β ^ p + zetaSubOne p K ^ (p + 1) * η := by
  obtain ⟨β, hβ⟩ := h
  obtain ⟨η, hη⟩ := hβ
  exact ⟨β, η, by linear_combination hη⟩

/-- Zero is hyperprimary (`0 = 0^p`). -/
theorem zero : IsHyperprimary p (K := K) 0 := by
  refine ⟨0, ?_⟩
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  simp [zero_pow (NeZero.ne p)]

/-- A hyperprimary times a `p`-th power is hyperprimary. -/
theorem mul_pow_p {α : 𝓞 K} (hα : IsHyperprimary p α) (γ : 𝓞 K) :
    IsHyperprimary p (α * γ ^ p) :=
  IsHyperprimary.mul (p := p) (K := K) hα (IsHyperprimary.of_pow (p := p) γ)

/-- A hyperprimary raised to any natural power is hyperprimary. -/
theorem pow {α : 𝓞 K} (h : IsHyperprimary p α) (n : ℕ) :
    IsHyperprimary p (α ^ n) := by
  induction n with
  | zero =>
    rw [pow_zero]
    exact IsHyperprimary.one (K := K) p
  | succ k ih =>
    rw [pow_succ]
    exact IsHyperprimary.mul (p := p) (K := K) ih h

/-- `-α` is hyperprimary when α is and p is odd (so that `(-β)^p = -β^p`). -/
theorem neg {α : 𝓞 K} (hα : IsHyperprimary p α) (hp_odd : Odd p) :
    IsHyperprimary p (-α) := by
  obtain ⟨β, hβ⟩ := hα
  refine ⟨-β, ?_⟩
  -- (-β)^p = -β^p for p odd. -α - (-β)^p = -α + β^p = -(α - β^p).
  rw [show -α - (-β) ^ p = -(α - β ^ p) from by
        rw [Odd.neg_pow hp_odd]; ring]
  exact hβ.neg_right

/-- `IsHyperprimary` is invariant under negation when p is odd. -/
theorem neg_iff {α : 𝓞 K} (hp_odd : Odd p) :
    IsHyperprimary p (-α) ↔ IsHyperprimary p α :=
  ⟨fun h => by
    have := IsHyperprimary.neg (p := p) (K := K) h hp_odd
    simpa using this,
   fun h => IsHyperprimary.neg (p := p) (K := K) h hp_odd⟩

end IsHyperprimary

end CyclotomicSetup

end FLT37

end BernoulliRegular

end
