module

public import BernoulliRegular.FLT37.PrimaryConj
public import FltRegular.CaseII.AuxLemmas

/-!
# Class-group descent of primary `(α)` (ticket FLT37b2b2)

For primary `α ∈ 𝓞 K` with `(α) = 𝔞^p`, we want to conclude that the class
`[𝔞]` in `Cl(𝓞 K)` is `σ`-fixed, hence descends to `Cl(𝓞 K⁺)` and (under
Vandiver's conjecture) is trivial.

This file collects the **σ-equivariance of ideal equations** at the
`Ideal (𝓞 K)` level (FLT37b2b2-a). The deeper Kummer-style argument
(`σ α / α = u · v^p`) and the descent through the class group are
deferred to FLT37b2b2-b/c/d/e.

## References

* Washington, *Introduction to Cyclotomic Fields*, §6.4.
* Borevich–Shafarevich, *Number Theory*, §4.9.
-/

@[expose] public section

noncomputable section

open NumberField NumberField.IsCMField IsCyclotomicExtension
open scoped NumberField nonZeroDivisors

namespace BernoulliRegular

namespace FLT37

section IdealEquivariance

variable (p : ℕ) [hp : Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- Applying complex conjugation to an ideal equation `(α) = 𝔞^n` yields
`(σ α) = (σ 𝔞)^n`. The proof is just `Ideal.map_pow` and
`Ideal.map_span` for a ring iso. -/
theorem complexConj_ideal_pow_eq [IsCMField K] {α : 𝓞 K}
    {𝔞 : Ideal (𝓞 K)} {n : ℕ}
    (h : Ideal.span ({α} : Set (𝓞 K)) = 𝔞 ^ n) :
    Ideal.span ({ringOfIntegersComplexConj K α} : Set (𝓞 K)) =
      (𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom) ^ n := by
  have := congrArg
    (Ideal.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom) h
  rwa [Ideal.map_span, Set.image_singleton, Ideal.map_pow] at this

/-- A ring iso preserves non-zero-ideal-ness: `(I.map σ) ≠ ⊥ ↔ I ≠ ⊥`. -/
theorem map_ne_bot_iff_complexConj [IsCMField K] (𝔞 : Ideal (𝓞 K)) :
    𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom ≠ ⊥ ↔ 𝔞 ≠ ⊥ :=
  not_congr <| Ideal.map_eq_bot_iff_of_injective
    (f := (ringOfIntegersComplexConj K).toRingEquiv.toRingHom)
    (ringOfIntegersComplexConj K).injective

/-- The image of a non-zero ideal under complex conjugation is non-zero. -/
theorem map_complexConj_ne_bot [IsCMField K] {𝔞 : Ideal (𝓞 K)} (h𝔞 : 𝔞 ≠ ⊥) :
    𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom ≠ ⊥ :=
  (map_ne_bot_iff_complexConj K 𝔞).mpr h𝔞

/-- The image of `𝔞^n` under complex conjugation is `(σ 𝔞)^n`. -/
theorem map_complexConj_pow [IsCMField K] (𝔞 : Ideal (𝓞 K)) (n : ℕ) :
    (𝔞 ^ n).map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom =
      (𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom) ^ n :=
  Ideal.map_pow _ _ _

/-- If `(σ 𝔞)^n` is principal in `𝓞 K`, so is `𝔞^n` — because complex
conjugation is a ring iso, hence sends principal ideals back to principal
ideals. -/
theorem isPrincipal_pow_of_complexConj_isPrincipal_pow [IsCMField K]
    {𝔞 : Ideal (𝓞 K)} {n : ℕ}
    (h : ((𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom) ^ n).IsPrincipal) :
    (𝔞 ^ n).IsPrincipal := by
  rw [← map_complexConj_pow] at h
  have hsymm : ((𝔞 ^ n).map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom).map
      (ringOfIntegersComplexConj K).symm.toRingEquiv.toRingHom = 𝔞 ^ n := by
    rw [Ideal.map_map]
    simp only [AlgEquiv.symm_toRingEquiv, RingEquiv.symm_toRingHom_comp_toRingHom,
      Ideal.map_id]
  rw [← hsymm]
  exact Submodule.IsPrincipal.map_ringHom _ h

/-- For `(α) = 𝔞^p`, the principal ideal `(σα · α) = (σ𝔞 · 𝔞)^p`. Direct
consequence of `complexConj_ideal_pow_eq` and `Ideal.span_singleton_mul`. -/
theorem ideal_self_mul_complexConj_eq_pow [IsCMField K]
    {α : 𝓞 K} {𝔞 : Ideal (𝓞 K)} {n : ℕ}
    (h : Ideal.span ({α} : Set (𝓞 K)) = 𝔞 ^ n) :
    Ideal.span ({(ringOfIntegersComplexConj K α : 𝓞 K) * α} : Set (𝓞 K)) =
      (𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom * 𝔞) ^ n := by
  rw [← Ideal.span_singleton_mul_span_singleton, complexConj_ideal_pow_eq K h, h, ← mul_pow]

/-- For `(α) = 𝔞^p`, the σ-image `(σ𝔞)^p` is principal (generated by `σα`),
hence the class `[σ𝔞]^p = 1` in `Cl(𝓞 K)`. -/
theorem isPrincipal_complexConj_pow_of_pow [IsCMField K]
    {α : 𝓞 K} {𝔞 : Ideal (𝓞 K)} {n : ℕ}
    (h : Ideal.span ({α} : Set (𝓞 K)) = 𝔞 ^ n) :
    ((𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom) ^ n).IsPrincipal :=
  ⟨ringOfIntegersComplexConj K α, (complexConj_ideal_pow_eq K h).symm⟩

end IdealEquivariance

/-! ## Class equality from a Kummer-style element relation (FLT37b2b2-c)

If `(α) = 𝔞^p` and there exist a unit `u : (𝓞 K)ˣ` together with elements
`a, b ∈ 𝓞 K` (representing `v = a/b` in `K`) satisfying the
denominators-cleared form `σ α · b^p = u · a^p · α`, then taking ideals
yields `(σ 𝔞 · (b))^p = ((a) · 𝔞)^p`. By unique factorisation in a
Dedekind domain, `σ 𝔞 · (b) = (a) · 𝔞`, which is exactly the
`ClassGroup.mk0_eq_mk0_iff` characterisation of `[σ 𝔞] = [𝔞]`. -/

section ClassEqualityFromKummer

variable (p : ℕ) [hp : Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

omit hp [IsCyclotomicExtension {p} ℚ K] in
/-- From the cleared-denominator Kummer relation
`σ α · b^p = u · a^p · α`, taking principal ideals yields the
ideal-level equation `(σ 𝔞 · (b))^p = ((a) · 𝔞)^p`. -/
theorem ideal_pow_eq_pow_of_kummer_relation [IsCMField K]
    {α : 𝓞 K} {𝔞 : Ideal (𝓞 K)} (h : Ideal.span ({α} : Set (𝓞 K)) = 𝔞 ^ p)
    (u : (𝓞 K)ˣ) (a b : 𝓞 K)
    (hkummer : (ringOfIntegersComplexConj K α : 𝓞 K) * b ^ p =
      (u : 𝓞 K) * a ^ p * α) :
    (𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom *
        Ideal.span ({b} : Set (𝓞 K))) ^ p =
      (Ideal.span ({a} : Set (𝓞 K)) * 𝔞) ^ p := by
  -- (σ α) = (σ 𝔞)^p
  have h_conj : Ideal.span ({ringOfIntegersComplexConj K α} : Set (𝓞 K)) =
      (𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom) ^ p :=
    complexConj_ideal_pow_eq K h
  -- LHS as ideal: (σ α · b^p) = (σ α) · (b^p) = (σ 𝔞)^p · (b)^p = ((σ 𝔞) · (b))^p
  have hLHS : Ideal.span ({(ringOfIntegersComplexConj K α : 𝓞 K) * b ^ p} : Set (𝓞 K)) =
      (𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom *
        Ideal.span ({b} : Set (𝓞 K))) ^ p := by
    rw [show Ideal.span ({(ringOfIntegersComplexConj K α : 𝓞 K) * b ^ p} : Set (𝓞 K)) =
        Ideal.span ({ringOfIntegersComplexConj K α} : Set (𝓞 K)) *
          Ideal.span ({b ^ p} : Set (𝓞 K)) from
      (Ideal.span_singleton_mul_span_singleton _ _).symm,
      h_conj, ← Ideal.span_singleton_pow, ← mul_pow]
  -- RHS as ideal: (u · a^p · α) = (1) · (a)^p · (α) = (a)^p · 𝔞^p = ((a) · 𝔞)^p
  have hRHS : Ideal.span ({(u : 𝓞 K) * a ^ p * α} : Set (𝓞 K)) =
      (Ideal.span ({a} : Set (𝓞 K)) * 𝔞) ^ p := by
    have hu : Ideal.span ({(u : 𝓞 K)} : Set (𝓞 K)) = ⊤ := by
      rw [Ideal.span_singleton_eq_top]; exact u.isUnit
    rw [show (u : 𝓞 K) * a ^ p * α = (u : 𝓞 K) * (a ^ p * α) by ring]
    rw [show Ideal.span ({(u : 𝓞 K) * (a ^ p * α)} : Set (𝓞 K)) =
        Ideal.span ({(u : 𝓞 K)} : Set (𝓞 K)) *
          Ideal.span ({a ^ p * α} : Set (𝓞 K)) from
      (Ideal.span_singleton_mul_span_singleton _ _).symm, hu, Ideal.top_mul]
    rw [show Ideal.span ({a ^ p * α} : Set (𝓞 K)) =
        Ideal.span ({a ^ p} : Set (𝓞 K)) * Ideal.span ({α} : Set (𝓞 K)) from
      (Ideal.span_singleton_mul_span_singleton _ _).symm]
    rw [h, ← Ideal.span_singleton_pow, mul_pow]
  -- Combine
  rw [← hLHS, ← hRHS, hkummer]

/-- The ideal-level relation `σ 𝔞 · (b) = (a) · 𝔞` in a Dedekind domain
implies the class-group equality `[σ 𝔞] = [𝔞]`. -/
theorem classGroup_mk0_eq_complexConj_of_ideal_eq [IsCMField K]
    {𝔞 : Ideal (𝓞 K)} (h𝔞_nz : 𝔞 ≠ ⊥) (a b : 𝓞 K) (ha : a ≠ 0) (hb : b ≠ 0)
    (h : 𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom *
        Ideal.span ({b} : Set (𝓞 K)) =
      Ideal.span ({a} : Set (𝓞 K)) * 𝔞) :
    ClassGroup.mk0
        ⟨𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom,
          mem_nonZeroDivisors_iff_ne_zero.mpr (map_complexConj_ne_bot K h𝔞_nz)⟩ =
      ClassGroup.mk0 ⟨𝔞, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔞_nz⟩ := by
  refine ClassGroup.mk0_eq_mk0_iff.mpr ⟨b, a, hb, ha, ?_⟩
  change Ideal.span ({b} : Set (𝓞 K)) *
    (𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom) =
      Ideal.span ({a} : Set (𝓞 K)) * 𝔞
  rw [mul_comm (Ideal.span _) (Ideal.map _ _)]
  exact h

omit hp [IsCyclotomicExtension {p} ℚ K] in
/-- **Cancellation of `n`-th powers of ideals in a Dedekind domain.**
For ideals `I, J` in `𝓞 K` and `n > 0`, `I^n = J^n → I = J`. Direct
consequence of the unique-factorization-monoid structure on `Ideal (𝓞 K)`
via `pow_dvd_pow_iff_dvd` (from `FltRegular.CaseII.AuxLemmas`). -/
theorem ideal_eq_of_pow_eq_of_pow_pos [IsCMField K]
    {I J : Ideal (𝓞 K)} {n : ℕ} (hn : 0 < n)
    (h : I ^ n = J ^ n) :
  I = J := by
  apply le_antisymm
  · rw [← Ideal.dvd_iff_le, ← UniqueFactorizationMonoid.pow_dvd_pow_iff_dvd hn.ne']
    exact h.symm.dvd
  · rw [← Ideal.dvd_iff_le, ← UniqueFactorizationMonoid.pow_dvd_pow_iff_dvd hn.ne']
    exact h.dvd

omit hp [IsCyclotomicExtension {p} ℚ K] in
/-- **From the cleared Kummer relation, the ideal equation.** Given the
Kummer relation `σα · b^p = u · a^p · α` (cleared denominators), with
`(α) = 𝔞^p`, `p > 0`, we directly derive `σ𝔞 · (b) = (a) · 𝔞`. This
combines `ideal_pow_eq_pow_of_kummer_relation` with `pow`-cancellation. -/
theorem ideal_eq_of_kummer_relation [IsCMField K]
    {α : 𝓞 K} {𝔞 : Ideal (𝓞 K)} (h : Ideal.span ({α} : Set (𝓞 K)) = 𝔞 ^ p)
    (hp_pos : 0 < p) (u : (𝓞 K)ˣ) (a b : 𝓞 K)
    (hkummer : (ringOfIntegersComplexConj K α : 𝓞 K) * b ^ p =
      (u : 𝓞 K) * a ^ p * α) :
    𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom *
        Ideal.span ({b} : Set (𝓞 K)) =
      Ideal.span ({a} : Set (𝓞 K)) * 𝔞 :=
  ideal_eq_of_pow_eq_of_pow_pos K hp_pos
    (ideal_pow_eq_pow_of_kummer_relation p K h u a b hkummer)

omit hp [IsCyclotomicExtension {p} ℚ K] in
/-- **Class equality from the cleared Kummer relation.** Given primary
`α` with `(α) = 𝔞^p`, `p > 0`, `𝔞 ≠ ⊥`, and the Kummer relation
`σα · b^p = u · a^p · α` with `a, b ≠ 0`, conclude `[σ𝔞] = [𝔞]` in
`Cl(𝓞 K)`. Composes `ideal_eq_of_kummer_relation` with
`classGroup_mk0_eq_complexConj_of_ideal_eq`. -/
theorem classGroup_mk0_eq_complexConj_of_kummer_relation [IsCMField K]
    {α : 𝓞 K} {𝔞 : Ideal (𝓞 K)} (h𝔞_nz : 𝔞 ≠ ⊥)
    (h : Ideal.span ({α} : Set (𝓞 K)) = 𝔞 ^ p)
    (hp_pos : 0 < p) (u : (𝓞 K)ˣ) (a b : 𝓞 K) (ha : a ≠ 0) (hb : b ≠ 0)
    (hkummer : (ringOfIntegersComplexConj K α : 𝓞 K) * b ^ p =
      (u : 𝓞 K) * a ^ p * α) :
    ClassGroup.mk0
        ⟨𝔞.map (ringOfIntegersComplexConj K).toRingEquiv.toRingHom,
          mem_nonZeroDivisors_iff_ne_zero.mpr (map_complexConj_ne_bot K h𝔞_nz)⟩ =
      ClassGroup.mk0 ⟨𝔞, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔞_nz⟩ :=
  classGroup_mk0_eq_complexConj_of_ideal_eq K h𝔞_nz a b ha hb
    (ideal_eq_of_kummer_relation p K h hp_pos u a b hkummer)

end ClassEqualityFromKummer

/-! ## Class descent via the `(p+1)/2` trick (FLT37b2b2-d, partial)

For `p` odd, the involution `σ` decomposes `Cl(𝓞 K)_p` into `±1` eigenspaces.
A `σ`-fixed `p`-torsion class `[𝔞]` automatically lies in the `+1` eigenspace,
and (away from `2`-torsion, which is trivial in the `p`-Sylow for `p` odd) the
`+1` eigenspace agrees with the image of `classGroupMap : Cl(𝓞 K⁺) → Cl(𝓞 K)`.

The argument we formalise here uses the auxiliary class `[𝔞 · σ𝔞] = [𝔞]²` and
the `(p+1)/2` trick: assuming that `[𝔞]²` is in the image of `classGroupMap`,
we can recover `[𝔞]` by raising to `(p+1)/2`.

The unconditional descent of `[𝔞 · σ𝔞]` to `Cl(𝓞 K⁺)` (the actual b2b2-d
content) requires Galois descent at the ideal level for `σ`-fixed ideals;
that step is left for a follow-up using the project's
`MulSemiringAction Gal(K/K⁺) (𝓞 K)` infrastructure. -/

section ClassDescent

variable (p : ℕ) [hp : Fact p.Prime] (hp_odd : p ≠ 2)
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

include hp_odd in
omit [IsCyclotomicExtension {p} ℚ K] in
/-- If `[𝔞]^p = 1` (so `[𝔞]` lies in the `p`-torsion of `Cl(𝓞 K)`) and
`[𝔞]²` is in the image of `classGroupMap`, then so is `[𝔞]` itself,
via the explicit preimage `𝔠₀^{(p+1)/2}`. -/
theorem classGroup_mk0_in_image_classGroupMap_of_sq_in_image
    [IsCMField K]
    {𝔞 : Ideal (𝓞 K)} (h𝔞_nz : 𝔞 ≠ ⊥)
    (h_pow : ClassGroup.mk0 (⟨𝔞, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔞_nz⟩ :
        (Ideal (𝓞 K))⁰) ^ p = 1)
    (h_sq_in_image : ∃ 𝔠₀ : ClassGroup (𝓞 (K⁺)),
      classGroupMap K 𝔠₀ =
        ClassGroup.mk0 (⟨𝔞, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔞_nz⟩ :
          (Ideal (𝓞 K))⁰) ^ 2) :
    ∃ 𝔠 : ClassGroup (𝓞 (K⁺)),
      classGroupMap K 𝔠 =
        ClassGroup.mk0 (⟨𝔞, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔞_nz⟩ :
          (Ideal (𝓞 K))⁰) := by
  obtain ⟨𝔠₀, h𝔠₀⟩ := h_sq_in_image
  refine ⟨𝔠₀ ^ ((p + 1) / 2), ?_⟩
  rw [map_pow, h𝔠₀, ← pow_mul]
  have h2 : 2 * ((p + 1) / 2) = p + 1 := by
    obtain ⟨k, hk⟩ := hp.1.odd_of_ne_two hp_odd
    rw [hk]
    have : (2 * k + 1 + 1) / 2 = k + 1 := by omega
    rw [this]; ring
  rw [h2, pow_succ, h_pow, one_mul]

include hp_odd in
/-- **FLT37b2b2-e: closing under Vandiver's conjecture.** If `[𝔞]^p = 1`,
`[𝔞] ∈ image classGroupMap`, and `p ∤ h(K⁺)`, then `[𝔞] = 1` in `Cl(𝓞 K)`. -/
theorem classGroup_mk0_eq_one_of_in_image_of_VC [IsCMField K]
    (h_VC : p.Coprime (Fintype.card (ClassGroup (𝓞 (K⁺)))))
    {𝔞 : Ideal (𝓞 K)} (h𝔞_nz : 𝔞 ≠ ⊥)
    (h_pow : ClassGroup.mk0 (⟨𝔞, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔞_nz⟩ :
        (Ideal (𝓞 K))⁰) ^ p = 1)
    (h_in_image : ∃ 𝔠 : ClassGroup (𝓞 (K⁺)),
      classGroupMap K 𝔠 =
        ClassGroup.mk0 (⟨𝔞, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔞_nz⟩ :
          (Ideal (𝓞 K))⁰)) :
    ClassGroup.mk0 (⟨𝔞, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔞_nz⟩ :
      (Ideal (𝓞 K))⁰) = 1 := by
  obtain ⟨𝔠, h𝔠⟩ := h_in_image
  rw [← h𝔠]
  have h𝔠_pow : 𝔠 ^ p = 1 := by
    apply classGroupMap_injective (p := p) (hp_odd := hp_odd) (K := K)
    rw [map_pow, h𝔠, h_pow, map_one]
  have h𝔠_one : 𝔠 = 1 := by
    have : orderOf 𝔠 ∣ Nat.gcd p (Fintype.card (ClassGroup (𝓞 (K⁺)))) := by
      rw [Nat.dvd_gcd_iff]
      exact ⟨orderOf_dvd_of_pow_eq_one h𝔠_pow, orderOf_dvd_card⟩
    rw [h_VC] at this
    rw [← orderOf_eq_one_iff, Nat.dvd_one.mp this]
  rw [h𝔠_one, map_one]

include hp_odd in
/-- **Vandiver Lemma 1 from class equality.** Given `[σ 𝔞] = [𝔞]` in
`Cl(𝓞 K)` (the conclusion of FLT37b2b2-c) plus `[𝔞]^p = 1` (from
`(α) = 𝔞^p`), under Vandiver's conjecture and assuming the explicit
descent witness for `[𝔞]² ∈ image classGroupMap`, we conclude
`𝔞.IsPrincipal`.

This composes FLT37b2b2-d-easy + FLT37b2b2-e. The remaining gap is
the unconditional descent of `[𝔞]² = [𝔞 · σ𝔞]`
(FLT37b2b2-d-descent). -/
theorem isPrincipal_of_class_eq_complexConj_of_VC [IsCMField K]
    (h_VC : p.Coprime (Fintype.card (ClassGroup (𝓞 (K⁺)))))
    {𝔞 : Ideal (𝓞 K)} (h𝔞_nz : 𝔞 ≠ ⊥)
    (h_pow : ClassGroup.mk0 (⟨𝔞, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔞_nz⟩ :
        (Ideal (𝓞 K))⁰) ^ p = 1)
    (h_sq_in_image : ∃ 𝔠₀ : ClassGroup (𝓞 (K⁺)),
      classGroupMap K 𝔠₀ =
        ClassGroup.mk0 (⟨𝔞, mem_nonZeroDivisors_iff_ne_zero.mpr h𝔞_nz⟩ :
          (Ideal (𝓞 K))⁰) ^ 2) :
    𝔞.IsPrincipal := by
  have h_in_image := classGroup_mk0_in_image_classGroupMap_of_sq_in_image
    (p := p) (hp_odd := hp_odd) (K := K) h𝔞_nz h_pow h_sq_in_image
  have h_class_one := classGroup_mk0_eq_one_of_in_image_of_VC
    (p := p) (hp_odd := hp_odd) (K := K) h_VC h𝔞_nz h_pow h_in_image
  rwa [ClassGroup.mk0_eq_one_iff] at h_class_one

end ClassDescent

end FLT37

end BernoulliRegular

end
