module

public import Mathlib.NumberTheory.KummerDedekind
public import Mathlib.Algebra.Module.Torsion.Basic
public import Mathlib.RingTheory.Localization.Integer
public import BernoulliRegular.Reflection.WeakSplitting.SplitsCompletely

/-!
# Dedekind-Kummer cardinality bridge for complete splitting

This file contains a small generic bridge from the actual
Kummer-Dedekind theorem in mathlib to the project's `SplitsCompletely`
predicate.  It is intentionally stated as a cardinality theorem: if the
reduction of the minimal polynomial has as many distinct factors as the field
degree, then the prime splits completely.
-/

@[expose] public section

noncomputable section

open Ideal Polynomial KummerDedekind UniqueFactorizationMonoid
open scoped nonZeroDivisors

namespace BernoulliRegular
namespace Reflection
namespace Kummer

set_option linter.unusedSectionVars false

attribute [local instance] Ideal.Quotient.field

section PolynomialFactorCount

variable {F : Type*} [Field F] [DecidableEq F]

noncomputable local instance fieldNormalizationMonoid : NormalizationMonoid F :=
  (CommGroupWithZero.instNormalizedGCDMonoid F).toNormalizationMonoid

/-- For a split polynomial over a field, distinct normalized
irreducible factors are exactly the monic linear factors attached to its
roots. -/
theorem normalizedFactors_toFinset_eq_roots_image_of_splits
    {f : F[X]} (hf0 : f ≠ 0) (hsplit : f.Splits) :
    (normalizedFactors f).toFinset =
      f.roots.toFinset.image (fun a : F => X - C a) := by
  classical
  ext g
  rw [Finset.mem_image]
  constructor
  · intro hg
    have hg' := (Polynomial.mem_normalizedFactors_iff (p := g) (q := f) hf0).mp
      (Multiset.mem_toFinset.mp hg)
    obtain ⟨hgirr, hgmonic, hgdvd⟩ := hg'
    have hgsplit : g.Splits := hsplit.of_dvd hf0 hgdvd
    have hgdeg : g.natDegree = 1 := hgsplit.natDegree_eq_one_of_irreducible hgirr
    let a : F := -g.coeff 0
    have hg_eq : g = X - C a := by
      rw [hgmonic.eq_X_add_C hgdeg]
      simp [a, sub_eq_add_neg]
    refine ⟨a, ?_, ?_⟩
    · rw [Multiset.mem_toFinset, mem_roots hf0]
      rw [← dvd_iff_isRoot]
      simpa [← hg_eq] using hgdvd
    · exact hg_eq.symm
  · rintro ⟨a, ha, rfl⟩
    rw [Multiset.mem_toFinset]
    rw [Polynomial.mem_normalizedFactors_iff (q := f) hf0]
    refine ⟨irreducible_X_sub_C a, monic_X_sub_C a, ?_⟩
    rw [dvd_iff_isRoot]
    exact (mem_roots hf0).mp (Multiset.mem_toFinset.mp ha)

/-- A monic separable split polynomial has as many distinct normalized factors
as its degree. -/
theorem normalizedFactors_toFinset_card_eq_natDegree_of_monic_splits_separable
    {f : F[X]} (hf0 : f ≠ 0) (hsplit : f.Splits)
    (hsep : f.Separable) :
    (normalizedFactors f).toFinset.card = f.natDegree := by
  classical
  rw [normalizedFactors_toFinset_eq_roots_image_of_splits hf0 hsplit]
  have hinj : Set.InjOn (fun a : F => X - C a) (f.roots.toFinset : Set F) := by
    intro a _ b _ h
    simpa using congrArg (fun g : F[X] => -g.coeff 0) h
  rw [Finset.card_image_iff.mpr hinj]
  rw [Multiset.toFinset_card_of_nodup (nodup_roots hsep)]
  exact hsplit.natDegree_eq_card_roots.symm

/-- The factor-count form needed by the Kummer-Dedekind bridge for
`X^n - a`: if it is separable and split over the residue field, then its
distinct normalized factor count is `n`. -/
theorem normalizedFactors_X_pow_sub_C_card_eq
    {n : ℕ} {a : F} (hn : 0 < n) (ha : a ≠ 0)
    (hnF : (n : F) ≠ 0) (hsplit : (X ^ n - C a : F[X]).Splits) :
    (normalizedFactors (X ^ n - C a : F[X])).toFinset.card = n := by
  have hf0 : (X ^ n - C a : F[X]) ≠ 0 := X_pow_sub_C_ne_zero hn a
  have hsep : (X ^ n - C a : F[X]).Separable :=
    (X_pow_sub_C_separable_iff hn ha).mpr hnF
  rw [normalizedFactors_toFinset_card_eq_natDegree_of_monic_splits_separable
    hf0 hsplit hsep]
  exact natDegree_X_pow_sub_C

end PolynomialFactorCount

variable {R S K L : Type*}
variable [CommRing R] [IsDomain R] [IsDedekindDomain R] [IsIntegrallyClosed R]
variable [CommRing S] [IsDedekindDomain S] [Algebra R S]
variable [Module.Finite R S] [Module.IsTorsionFree R S]
variable [Field K] [Field L]
variable [Algebra R K] [IsFractionRing R K]
variable [Algebra S L] [IsFractionRing S L]
variable [Algebra R L] [Algebra K L]
variable [IsScalarTower R S L] [IsScalarTower R K L]

section PolynomialDenominatorClearing

/-- A polynomial over the fraction field can be evaluated at `x` after clearing
all coefficients by one nonzero scalar from the base ring.  The resulting
multiple lies in the base `R`-algebra generated by `x`.

This is the coefficient-clearing ingredient used later for the conductor
quotient `O_L / O_K[x]`: once the field extension is generated by `x`, every
field element is a polynomial in `x` with fraction-field coefficients, and this
lemma clears those coefficients. -/
theorem exists_nonZero_smul_aeval_mem_adjoin
    (x : L) (f : K[X]) :
    ∃ r : R⁰,
      algebraMap R L (r : R) * aeval x f ∈
        Algebra.adjoin R ({x} : Set L) := by
  classical
  obtain ⟨r, hr⟩ :=
    IsLocalization.exist_integer_multiples (M := R⁰)
      (R := R) (S := K) f.support f.coeff
  refine ⟨r, ?_⟩
  rw [Polynomial.as_sum_support_C_mul_X_pow f]
  simp only [map_sum, map_mul, map_pow, aeval_C, aeval_X]
  rw [Finset.mul_sum]
  refine Subalgebra.sum_mem _ fun i hi => ?_
  rcases hr i hi with ⟨c, hc⟩
  have hcL :
      algebraMap R L c =
        algebraMap R L (r : R) * algebraMap K L (f.coeff i) := by
    have hmap := congrArg (algebraMap K L) hc
    simpa [Algebra.smul_def, IsScalarTower.algebraMap_apply R K L] using hmap
  rw [← mul_assoc, ← hcL]
  exact Subalgebra.mul_mem _
    (Subalgebra.algebraMap_mem (Algebra.adjoin R ({x} : Set L)) c)
    (Subalgebra.pow_mem _ (Algebra.subset_adjoin (by simp)) i)

/-- If the fraction field extension is generated by `x`, then the quotient of
`S` by the `R`-order `R[x]` is torsion over `R`.

For a representative `b : S`, write its image in `L` as a polynomial in the
image of `x` with coefficients in the fraction field `K`; the previous lemma
clears those coefficients by one nonzero scalar from `R`, putting the multiple
of `b` in `R[x]`. -/
theorem quotient_adjoin_isTorsion_of_field_adjoin_eq_top
    {x : S}
    (h_adjoin :
      Algebra.adjoin K ({algebraMap S L x} : Set L) = ⊤) :
    Module.IsTorsion R
      (S ⧸ (Algebra.adjoin R ({x} : Set S)).toSubmodule) := by
  intro z
  induction z using Quotient.inductionOn' with
  | h b =>
      have hb_mem :
          algebraMap S L b ∈
            Algebra.adjoin K ({algebraMap S L x} : Set L) := by
        rw [h_adjoin]
        simp
      rw [Algebra.adjoin_singleton_eq_range_aeval] at hb_mem
      rcases hb_mem with ⟨f, hf⟩
      obtain ⟨r, hr⟩ :=
        exists_nonZero_smul_aeval_mem_adjoin
          (R := R) (K := K) (L := L) (algebraMap S L x) f
      refine ⟨r, ?_⟩
      let A : Subalgebra R S := Algebra.adjoin R ({x} : Set S)
      let N : Submodule R S := A.toSubmodule
      have hmap :
          A.map (IsScalarTower.toAlgHom R S L) =
            Algebra.adjoin R ({algebraMap S L x} : Set L) := by
        rw [AlgHom.map_adjoin]
        simp
      have hr' :
          algebraMap S L ((r : R) • b) ∈
            Algebra.adjoin R ({algebraMap S L x} : Set L) := by
        have hf' :
            aeval (algebraMap S L x) f = algebraMap S L b := by
          simpa using hf
        rw [hf'] at hr
        simpa [Algebra.smul_def, IsScalarTower.algebraMap_apply R S L] using hr
      rw [← hmap] at hr'
      rcases hr' with ⟨y, hy, hy_eq⟩
      have hbN : (r : R) • b ∈ N := by
        change (r : R) • b ∈ A.toSubmodule
        have hy_eq' : y = (r : R) • b :=
          IsFractionRing.injective S L hy_eq
        simpa [hy_eq'] using hy
      change (r : R) • (Submodule.Quotient.mk b : S ⧸ N) = (0 : S ⧸ N)
      rw [← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero]
      simpa [N]

end PolynomialDenominatorClearing

section ConductorNonzero

/-- If the quotient `S / R[x]` is a finite torsion `R`-module, then the
conductor of `R[x]` has nonzero contraction to `R`.

This is the exact algebraic denominator-clearing input behind the
Kummer-Dedekind conductor bad set: a nonzero element of `R` annihilating
`S / R[x]` multiplies every element of `S` into `R[x]`, hence lies in the
contracted conductor. -/
theorem conductor_comap_ne_bot_of_finite_torsion_quotient
    {x : S}
    [Module.Finite R (S ⧸ (Algebra.adjoin R ({x} : Set S)).toSubmodule)]
    (htors :
      Module.IsTorsion R
        (S ⧸ (Algebra.adjoin R ({x} : Set S)).toSubmodule)) :
    (conductor R x).comap (algebraMap R S) ≠ ⊥ := by
  classical
  let A : Subalgebra R S := Algebra.adjoin R ({x} : Set S)
  let N : Submodule R S := A.toSubmodule
  obtain ⟨r, hrann, hrnz⟩ :=
    (Submodule.annihilator_top_inter_nonZeroDivisors
      (R := R) (M := S ⧸ N) (by simpa [A, N] using htors))
  have hrmem : r ∈ (conductor R x).comap (algebraMap R S) := by
    rw [Ideal.mem_comap, mem_conductor_iff]
    intro b
    change algebraMap R S r * b ∈ Algebra.adjoin R ({x} : Set S)
    have hzero : r • (Submodule.Quotient.mk b : S ⧸ N) = 0 :=
      (Submodule.mem_annihilator.mp hrann) (Submodule.Quotient.mk b) (by trivial)
    have hbN : r • b ∈ N := by
      rw [← Submodule.Quotient.mk_eq_zero]
      simpa [N] using hzero
    simpa [A, N, Algebra.smul_def] using hbN
  refine ((conductor R x).comap (algebraMap R S)).ne_bot_iff.mpr ⟨r, hrmem, ?_⟩
  exact mem_nonZeroDivisors_iff_ne_zero.mp hrnz

end ConductorNonzero

noncomputable local instance quotientField {I : Ideal R} [I.IsMaximal] : Field (R ⧸ I) :=
  Ideal.Quotient.field I

noncomputable local instance quotientDecidableEq {I : Ideal R} : DecidableEq (R ⧸ I) :=
  Classical.decEq _

@[reducible] noncomputable local instance quotientNormalizationMonoid {I : Ideal R} [I.IsMaximal] :
    NormalizationMonoid (R ⧸ I) := by
  letI : Field (R ⧸ I) := Ideal.Quotient.field I
  exact (CommGroupWithZero.instNormalizedGCDMonoid (R ⧸ I)).toNormalizationMonoid

noncomputable local instance quotientPolynomialDecidableEq {I : Ideal R} :
    DecidableEq (R ⧸ I)[X] :=
  Classical.decEq _

/-- A normalized ideal factor of a nonzero ideal in a Dedekind domain is prime. -/
theorem isPrime_of_mem_normalizedFactors_ideal
    {I P : Ideal R} (hI : I ≠ ⊥)
    (hP : P ∈ (normalizedFactors I).toFinset) :
    P.IsPrime :=
  ((Ideal.mem_normalizedFactors_iff hI).mp (Multiset.mem_toFinset.mp hP)).1

/-- A normalized ideal factor of a nonzero ideal in a Dedekind domain is nonzero. -/
theorem ne_bot_of_mem_normalizedFactors_ideal
    {I P : Ideal R} (hI : I ≠ ⊥)
    (hP : P ∈ (normalizedFactors I).toFinset) :
    P ≠ ⊥ := by
  have hle : I ≤ P :=
    ((Ideal.mem_normalizedFactors_iff hI).mp (Multiset.mem_toFinset.mp hP)).2
  intro hPbot
  exact hI (le_bot_iff.mp (hPbot ▸ hle))

/-- A nonzero prime outside the normalized factor set of a nonzero ideal is
coprime to that ideal. -/
theorem sup_eq_top_of_isPrime_not_mem_normalizedFactors
    {I P : Ideal R} (hI : I ≠ ⊥) [hPprime : P.IsPrime] (hP_ne : P ≠ ⊥)
    (hP_not_mem : P ∉ (normalizedFactors I).toFinset) :
    I ⊔ P = ⊤ := by
  have hPmax : P.IsMaximal := Ideal.IsPrime.isMaximal hPprime hP_ne
  by_contra hsup
  have hEq : P = I ⊔ P := hPmax.eq_of_le hsup le_sup_right
  have hle : I ≤ P := le_sup_left.trans_eq hEq.symm
  have hmem : P ∈ normalizedFactors I :=
    (Ideal.mem_normalizedFactors_iff hI).mpr ⟨hPprime, hle⟩
  exact hP_not_mem (Multiset.mem_toFinset.mpr hmem)

/-- Kummer-Dedekind identifies the finite set of primes above `I` with the
finite set of distinct irreducible factors of the reduced minimal polynomial,
provided the conductor is coprime to `I`. -/
theorem primesOverFinset_card_eq_reduced_minpoly_factor_card
    {I : Ideal R} [I.IsMaximal] (hI0 : I ≠ ⊥) {x : S}
    (hxcond : (conductor R x).comap (algebraMap R S) ⊔ I = ⊤)
    (hxint : IsIntegral R x) :
    (IsDedekindDomain.primesOverFinset I S).card =
      (normalizedFactors ((minpoly R x).map (Ideal.Quotient.mk I))).toFinset.card := by
  classical
  have hKD :=
    normalizedFactors_ideal_map_eq_normalizedFactors_min_poly_mk_map
      (R := R) (S := S) (x := x) (I := I) inferInstance hI0 hxcond hxint
  unfold IsDedekindDomain.primesOverFinset
  rw [factors_eq_normalizedFactors, hKD]
  rw [Multiset.toFinset_map]
  have h_image :
      (Finset.image
          (fun f : {d : (R ⧸ I)[X] |
              d ∈ normalizedFactors (Polynomial.map (Ideal.Quotient.mk I) (minpoly R x))} ↦
            (((normalizedFactorsMapEquivNormalizedFactorsMinPolyMk
              (R := R) (S := S) (x := x) (I := I) inferInstance hI0 hxcond hxint).symm f :
                {J : Ideal S | J ∈ normalizedFactors (Ideal.map (algebraMap R S) I)}) :
              Ideal S))
          (normalizedFactors ((minpoly R x).map (Ideal.Quotient.mk I))).attach.toFinset).card =
        (normalizedFactors ((minpoly R x).map (Ideal.Quotient.mk I))).attach.toFinset.card :=
    Finset.card_image_iff.mpr fun a _ b _ h =>
      (normalizedFactorsMapEquivNormalizedFactorsMinPolyMk
        (R := R) (S := S) (x := x) (I := I) inferInstance hI0 hxcond hxint).symm.injective
          (Subtype.ext h)
  let m : Multiset (R ⧸ I)[X] :=
    normalizedFactors ((minpoly R x).map (Ideal.Quotient.mk I))
  have h_attach : m.attach.toFinset.card = m.toFinset.card := by
    have h_val :
        (Finset.image (fun f : {g // g ∈ m} => (f : (R ⧸ I)[X]))
          m.attach.toFinset).card = m.attach.toFinset.card :=
      Finset.card_image_iff.mpr fun a _ b _ h => Subtype.ext h
    rw [← h_val, ← Multiset.toFinset_map, Multiset.attach_map_val]
  exact h_image.trans h_attach

/-- A direct complete-splitting criterion from Kummer-Dedekind: if the reduced
minimal polynomial has `finrank K L` distinct factors, then the prime splits
completely in `S`. -/
theorem splitsCompletely_of_reduced_minpoly_factor_card_eq_finrank
    {I : Ideal R} [I.IsMaximal] (hI0 : I ≠ ⊥) {x : S}
    (hxcond : (conductor R x).comap (algebraMap R S) ⊔ I = ⊤)
    (hxint : IsIntegral R x)
    (hcard :
      (normalizedFactors ((minpoly R x).map (Ideal.Quotient.mk I))).toFinset.card =
        Module.finrank K L) :
    BernoulliRegular.Ideal.SplitsCompletely S I := by
  rw [BernoulliRegular.Ideal.splitsCompletely_iff_card_primesOverFinset_eq_finrank
    (S := S) (K := K) (L := L) hI0]
  exact (primesOverFinset_card_eq_reduced_minpoly_factor_card
    (R := R) (S := S) hI0 hxcond hxint).trans hcard

end Kummer
end Reflection
end BernoulliRegular

end
