module

public import BernoulliRegular.UnitQuotient.LogEmbeddingAction
public import Mathlib.Algebra.MonoidAlgebra.Module
public import Mathlib.GroupTheory.QuotientGroup.Finite
public import Mathlib.LinearAlgebra.Finsupp.Pi

/-!
# Unit quotients: the even permutation representation

This file proves `REF-07c3`.

The finite representation-theory statement needed for the free unit part is:
the permutation representation of

```text
Delta / {±1}
```

is the regular representation of this quotient, so over a splitting
coefficient ring it decomposes with one copy of every quotient character.
Equivalently, on `Delta` itself, the plus idempotent for complex conjugation
is the sum of the even character idempotents; after subtracting the trivial
idempotent, only the nontrivial even characters remain.
-/

@[expose] public section

noncomputable section

namespace BernoulliRegular

open Finset MonoidAlgebra

set_option linter.unusedSectionVars false
set_option linter.unusedDecidableInType false

attribute [local instance] Fintype.ofFinite

variable (p : ℕ) [Fact p.Prime]

/-- The subgroup `{±1}` of `Delta = (ZMod p)^*`, generated by complex
conjugation. -/
abbrev CyclotomicEvenDeltaSubgroup : Subgroup (CyclotomicUnitDelta p) :=
  Subgroup.zpowers (-1 : CyclotomicUnitDelta p)

/-- The quotient `Delta / {±1}` indexing the real embeddings of `Q(zeta_p)^+`. -/
abbrev CyclotomicEvenDelta : Type :=
  CyclotomicUnitDelta p ⧸ CyclotomicEvenDeltaSubgroup p

/-- The quotient map `Delta -> Delta / {±1}`. -/
def cyclotomicEvenDeltaQuotient : CyclotomicUnitDelta p →* CyclotomicEvenDelta p :=
  QuotientGroup.mk' (CyclotomicEvenDeltaSubgroup p)

@[simp]
theorem cyclotomicEvenDeltaQuotient_apply (a : CyclotomicUnitDelta p) :
    cyclotomicEvenDeltaQuotient p a = QuotientGroup.mk a :=
  rfl

@[simp]
theorem cyclotomicEvenDeltaQuotient_neg_one :
    cyclotomicEvenDeltaQuotient p (-1 : CyclotomicUnitDelta p) = 1 :=
  (QuotientGroup.eq_one_iff (-1 : CyclotomicUnitDelta p)).2 (Subgroup.mem_zpowers _)

/-- **Negation invariance of the quotient map**: for any `a : (ZMod p)ˣ`,
`q(-a) = q(a)` in `(ZMod p)ˣ / ⟨-1⟩`. Direct consequence of
`q(-1) = 1` + the homomorphism property `q(-a) = q((-1) · a) = q(-1) · q(a)`. -/
@[simp]
theorem cyclotomicEvenDeltaQuotient_neg (a : CyclotomicUnitDelta p) :
    cyclotomicEvenDeltaQuotient p (-a) = cyclotomicEvenDeltaQuotient p a := by
  have h : -a = (-1 : CyclotomicUnitDelta p) * a := (neg_one_mul a).symm
  rw [h, map_mul, cyclotomicEvenDeltaQuotient_neg_one, one_mul]

/-- **Even function descent**: any function `f : (ZMod p)ˣ → R` satisfying
`f(-a) = f(a)` (= even under negation) descends to a function on the quotient
`(ZMod p)ˣ ⧸ ⟨-1⟩ = CyclotomicEvenDelta p`. This is the function-level analog
of the character-level `evenDeltaCharacterDescend`.

The well-definedness uses `(-1)^k ∈ {1, -1}` for any `k : ℤ` (which follows
from `(-1)^2 = 1` + `zpow_eq_zpow_emod'`). For `k % 2 = 0`, the equivalence
gives `b = a`; for `k % 2 = 1`, it gives `b = -a`, and `hf_even` resolves
the function value. -/
def evenFunctionDescend {R : Type*} (f : CyclotomicUnitDelta p → R)
    (hf_even : ∀ a : CyclotomicUnitDelta p, f (-a) = f a) :
    CyclotomicEvenDelta p → R :=
  fun q => q.liftOn f (fun a b hab => by
    have hab' : a⁻¹ * b ∈ CyclotomicEvenDeltaSubgroup p :=
      QuotientGroup.leftRel_apply.mp hab
    rw [CyclotomicEvenDeltaSubgroup, Subgroup.mem_zpowers_iff] at hab'
    obtain ⟨k, hk⟩ := hab'
    -- hk : (-1)^k = a⁻¹ * b, so b = a * (-1)^k
    have h_b : b = a * ((-1 : CyclotomicUnitDelta p) ^ k) := by
      rw [hk]; group
    -- Use that (-1)^2 = 1 to reduce k mod 2.
    have h_sq : ((-1 : CyclotomicUnitDelta p) ^ (2 : ℕ)) = 1 := by
      rw [sq, neg_one_mul, neg_neg]
    rw [zpow_eq_zpow_emod' k h_sq] at h_b
    -- k % 2 ∈ {0, 1}
    have h_mod : k % ((2 : ℕ) : ℤ) = 0 ∨ k % ((2 : ℕ) : ℤ) = 1 := by omega
    rcases h_mod with h0 | h1
    · rw [h0, zpow_zero, mul_one] at h_b
      rw [h_b]
    · rw [h1, zpow_one] at h_b
      rw [h_b, mul_neg_one, hf_even])

@[simp]
theorem evenFunctionDescend_apply_mk {R : Type*} (f : CyclotomicUnitDelta p → R)
    (hf_even : ∀ a : CyclotomicUnitDelta p, f (-a) = f a)
    (a : CyclotomicUnitDelta p) :
    evenFunctionDescend (p := p) f hf_even
        ((QuotientGroup.mk a) : CyclotomicEvenDelta p) = f a := by
  rfl

/-- A character of `Delta` is even when it is trivial on complex conjugation. -/
def IsEvenDeltaCharacter {R : Type*} [CommMonoidWithZero R]
    (χ : MulChar (CyclotomicUnitDelta p) R) : Prop :=
  χ (-1 : CyclotomicUnitDelta p) = 1

@[simp]
theorem isEvenDeltaCharacter_one {R : Type*} [CommMonoidWithZero R] :
    IsEvenDeltaCharacter (p := p) (1 : MulChar (CyclotomicUnitDelta p) R) :=
  MulChar.one_apply (Group.isUnit (-1 : CyclotomicUnitDelta p))

/-- Pull a character of `Delta / {±1}` back to an even character of `Delta`. -/
def evenDeltaCharacterPullback {R : Type*} [CommMonoidWithZero R]
    (χ : MulChar (CyclotomicEvenDelta p) R) :
    MulChar (CyclotomicUnitDelta p) R where
  toFun a := χ (cyclotomicEvenDeltaQuotient p a)
  map_one' := by simp [cyclotomicEvenDeltaQuotient]
  map_mul' a b := by simp [cyclotomicEvenDeltaQuotient, map_mul]
  map_nonunit' a ha := (ha (Group.isUnit a)).elim

@[simp]
theorem evenDeltaCharacterPullback_apply {R : Type*} [CommMonoidWithZero R]
    (χ : MulChar (CyclotomicEvenDelta p) R) (a : CyclotomicUnitDelta p) :
    evenDeltaCharacterPullback (p := p) χ a =
      χ (cyclotomicEvenDeltaQuotient p a) :=
  rfl

/-- Characters of `Delta / {±1}` pull back to even characters of `Delta`. -/
theorem evenDeltaCharacterPullback_even {R : Type*} [CommMonoidWithZero R]
    (χ : MulChar (CyclotomicEvenDelta p) R) :
    IsEvenDeltaCharacter (p := p) (evenDeltaCharacterPullback (p := p) χ) := by
  change χ (cyclotomicEvenDeltaQuotient p (-1 : CyclotomicUnitDelta p)) = 1
  rw [cyclotomicEvenDeltaQuotient_neg_one]
  exact MulChar.map_one χ

/-- An even character of `Delta` descends to a character of `Delta / {±1}`. -/
def evenDeltaCharacterDescend {R : Type*} [CommMonoidWithZero R]
    (χ : MulChar (CyclotomicUnitDelta p) R)
    (hχ_even : IsEvenDeltaCharacter (p := p) χ) :
    MulChar (CyclotomicEvenDelta p) R where
  __ := QuotientGroup.lift (CyclotomicEvenDeltaSubgroup p) χ.toMonoidHom (by
    apply Subgroup.zpowers_le_of_mem
    rw [MonoidHom.mem_ker]
    exact hχ_even)
  map_nonunit' a ha := (ha (Group.isUnit a)).elim

@[simp]
theorem evenDeltaCharacterDescend_apply_quotient {R : Type*} [CommMonoidWithZero R]
    (χ : MulChar (CyclotomicUnitDelta p) R)
    (hχ_even : IsEvenDeltaCharacter (p := p) χ) (a : CyclotomicUnitDelta p) :
    evenDeltaCharacterDescend (p := p) χ hχ_even
        (cyclotomicEvenDeltaQuotient p a) = χ a :=
  rfl

@[simp]
theorem evenDeltaCharacterPullback_descend {R : Type*} [CommMonoidWithZero R]
    (χ : MulChar (CyclotomicUnitDelta p) R)
    (hχ_even : IsEvenDeltaCharacter (p := p) χ) :
    evenDeltaCharacterPullback (p := p)
        (evenDeltaCharacterDescend (p := p) χ hχ_even) = χ := by
  ext a
  exact evenDeltaCharacterDescend_apply_quotient
    (p := p) χ hχ_even (a : CyclotomicUnitDelta p)

theorem evenDeltaCharacterDescend_ne_one {R : Type*} [CommMonoidWithZero R]
    (χ : MulChar (CyclotomicUnitDelta p) R)
    (hχ_even : IsEvenDeltaCharacter (p := p) χ)
    (hχ_ne : χ ≠ (1 : MulChar (CyclotomicUnitDelta p) R)) :
    evenDeltaCharacterDescend (p := p) χ hχ_even ≠ 1 := by
  intro h
  apply hχ_ne
  rw [← evenDeltaCharacterPullback_descend (p := p) χ hχ_even, h]
  ext a
  change (1 : MulChar (CyclotomicEvenDelta p) R)
      ((a : CyclotomicUnitDelta p) : CyclotomicEvenDelta p) =
    (1 : MulChar (CyclotomicUnitDelta p) R) (a : CyclotomicUnitDelta p)
  rw [MulChar.one_apply (R := CyclotomicEvenDelta p) (R' := R)
      (x := ((a : CyclotomicUnitDelta p) : CyclotomicEvenDelta p)) (Group.isUnit _),
    MulChar.one_apply (R := CyclotomicUnitDelta p) (R' := R)
      (x := (a : CyclotomicUnitDelta p)) (Group.isUnit _)]

/-- The full permutation representation of `Delta / {±1}`, written as
functions on the quotient, is linearly equivalent to the group algebra. -/
def evenDeltaRegularFunctionLinearEquiv (R : Type*) [Semiring R] :
    MonoidAlgebra R (CyclotomicEvenDelta p) ≃ₗ[R] (CyclotomicEvenDelta p → R) :=
  (MonoidAlgebra.coeffLinearEquiv R).trans
    (Finsupp.linearEquivFunOnFinite R R (CyclotomicEvenDelta p))

/-- The left regular permutation action of `Delta / {±1}` on functions on
`Delta / {±1}`. -/
def evenDeltaRegularPermutation (R : Type*) [Semiring R] (a : CyclotomicEvenDelta p) :
    (CyclotomicEvenDelta p → R) ≃ₗ[R] (CyclotomicEvenDelta p → R) where
  toFun f x := f (a⁻¹ * x)
  invFun f x := f (a * x)
  left_inv f := by
    ext x
    change f (a⁻¹ * (a * x)) = f x
    rw [← mul_assoc, inv_mul_cancel, one_mul]
  right_inv f := by
    ext x
    change f (a * (a⁻¹ * x)) = f x
    rw [← mul_assoc, mul_inv_cancel, one_mul]
  map_add' f g := by
    ext x
    rfl
  map_smul' c f := by
    ext x
    rfl

@[simp]
theorem evenDeltaRegularPermutation_apply {R : Type*} [Semiring R]
    (a : CyclotomicEvenDelta p) (f : CyclotomicEvenDelta p → R)
    (x : CyclotomicEvenDelta p) :
    evenDeltaRegularPermutation (p := p) R a f x = f (a⁻¹ * x) :=
  rfl

/-- The standard character vector in the regular permutation representation.
The inverse is chosen so that the left regular action has eigenvalue `χ a`
rather than `(χ a)⁻¹`. -/
def evenDeltaRegularCharacterFunction {R : Type*} [CommMonoidWithZero R]
    (χ : MulChar (CyclotomicEvenDelta p) R) :
    CyclotomicEvenDelta p → R :=
  fun x => χ x⁻¹

@[simp]
theorem evenDeltaRegularCharacterFunction_apply {R : Type*} [CommMonoidWithZero R]
    (χ : MulChar (CyclotomicEvenDelta p) R) (x : CyclotomicEvenDelta p) :
    evenDeltaRegularCharacterFunction (p := p) χ x = χ x⁻¹ :=
  rfl

/-- The `χ`-eigenspace for the regular permutation action. -/
def evenDeltaRegularCharacterEigenspace {R : Type*} [CommSemiring R]
    (χ : MulChar (CyclotomicEvenDelta p) R) :
    Submodule R (CyclotomicEvenDelta p → R) where
  carrier := {f | ∀ a x, f (a⁻¹ * x) = χ a * f x}
  zero_mem' := by
    intro a x
    simp
  add_mem' hf hg := by
    intro a x
    rw [Pi.add_apply, Pi.add_apply, hf a x, hg a x, mul_add]
  smul_mem' c f hf := by
    intro a x
    rw [Pi.smul_apply, Pi.smul_apply, hf a x]
    ring

theorem evenDeltaRegularCharacterFunction_mem_eigenspace {R : Type*} [CommSemiring R]
    (χ : MulChar (CyclotomicEvenDelta p) R) :
    evenDeltaRegularCharacterFunction (p := p) χ ∈
      evenDeltaRegularCharacterEigenspace (p := p) χ := by
  intro a x
  simp [evenDeltaRegularCharacterFunction, map_mul, mul_comm]

/-- In the regular representation, the `χ`-eigenspace is exactly the line
spanned by the character vector. -/
theorem evenDeltaRegularCharacterEigenspace_eq_span {R : Type*} [Field R]
    (χ : MulChar (CyclotomicEvenDelta p) R) :
    evenDeltaRegularCharacterEigenspace (p := p) χ =
      Submodule.span R {evenDeltaRegularCharacterFunction (p := p) χ} := by
  ext f
  constructor
  · intro hf
    rw [Submodule.mem_span_singleton]
    refine ⟨f 1, ?_⟩
    ext x
    have hx := hf x⁻¹ 1
    rw [inv_inv, mul_one] at hx
    rw [hx]
    simp [evenDeltaRegularCharacterFunction, mul_comm]
  · intro hf
    rw [Submodule.mem_span_singleton] at hf
    obtain ⟨c, rfl⟩ := hf
    exact Submodule.smul_mem _
      c (evenDeltaRegularCharacterFunction_mem_eigenspace (p := p) χ)

/-- Each character occurs with multiplicity one in the regular permutation
representation of `Delta / {±1}`. -/
theorem evenDeltaRegularCharacterEigenspace_finrank {R : Type*} [Field R]
    (χ : MulChar (CyclotomicEvenDelta p) R) :
    Module.finrank R (evenDeltaRegularCharacterEigenspace (p := p) χ) = 1 := by
  rw [evenDeltaRegularCharacterEigenspace_eq_span (p := p) χ]
  apply finrank_span_singleton
  intro h
  have h1 := congrFun h (1 : CyclotomicEvenDelta p)
  simp [evenDeltaRegularCharacterFunction] at h1

/-- Over a splitting coefficient ring, the regular representation of
`Delta / {±1}` decomposes as the product of its character idempotent
components. -/
def evenDeltaRegularRepresentationDecomposition
    (R : Type*) [CommRing R] [IsDomain R]
    [Invertible ((Fintype.card (CyclotomicEvenDelta p) : R))]
    [HasEnoughRootsOfUnity R (Monoid.exponent (CyclotomicEvenDelta p))] :
    MonoidAlgebra R (CyclotomicEvenDelta p) ≃+*
      ∀ χ : MulChar (CyclotomicEvenDelta p) R,
        (isIdempotentElem_charIdempotent (R := R) χ).Corner := by
  classical
  exact MonoidAlgebra.charComponentEquiv (G := CyclotomicEvenDelta p) (R := R)

section DeltaIdempotents

variable {R : Type*} [CommRing R] [IsDomain R]
variable [Invertible ((Fintype.card (CyclotomicUnitDelta p) : R))]
variable [HasEnoughRootsOfUnity R (Monoid.exponent (CyclotomicUnitDelta p))]
variable [Invertible (2 : R)]

open Classical in
/-- The plus idempotent for complex conjugation is the sum of the even
character idempotents of `Delta`. -/
theorem delta_plusIdempotent_eq_sum_even :
    plusIdempotent (R := R) (-1 : CyclotomicUnitDelta p) =
      ∑ χ ∈ (Finset.univ : Finset (MulChar (CyclotomicUnitDelta p) R)).filter
          (fun χ => IsEvenDeltaCharacter (p := p) χ),
        charIdempotent χ := by
  classical
  have hc : (-1 : CyclotomicUnitDelta p) * (-1 : CyclotomicUnitDelta p) = 1 := by
    ext
    simp
  simpa [IsEvenDeltaCharacter] using
    plusIdempotent_eq_sum_even (G := CyclotomicUnitDelta p) (R := R)
      (-1 : CyclotomicUnitDelta p) hc

open Classical in
/-- Removing the trivial idempotent from the plus part leaves exactly the
nontrivial even character idempotents. -/
theorem delta_plusIdempotent_sub_trivial_eq_sum_nontrivial_even :
    plusIdempotent (R := R) (-1 : CyclotomicUnitDelta p) -
        charIdempotent (1 : MulChar (CyclotomicUnitDelta p) R) =
      ∑ χ ∈ (Finset.univ : Finset (MulChar (CyclotomicUnitDelta p) R)).filter
          (fun χ => IsEvenDeltaCharacter (p := p) χ ∧
            χ ≠ (1 : MulChar (CyclotomicUnitDelta p) R)),
        charIdempotent χ := by
  classical
  rw [delta_plusIdempotent_eq_sum_even (p := p) (R := R)]
  have hsplit :
      (∑ χ ∈ (Finset.univ : Finset (MulChar (CyclotomicUnitDelta p) R)).filter
          (fun χ => IsEvenDeltaCharacter (p := p) χ),
        charIdempotent χ) =
        charIdempotent (1 : MulChar (CyclotomicUnitDelta p) R) +
          ∑ χ ∈ (Finset.univ : Finset (MulChar (CyclotomicUnitDelta p) R)).filter
              (fun χ => IsEvenDeltaCharacter (p := p) χ ∧
                χ ≠ (1 : MulChar (CyclotomicUnitDelta p) R)),
            charIdempotent χ := by
    calc
      (∑ χ ∈ (Finset.univ : Finset (MulChar (CyclotomicUnitDelta p) R)).filter
          (fun χ => IsEvenDeltaCharacter (p := p) χ),
        charIdempotent χ)
          = (∑ χ ∈ ((Finset.univ : Finset (MulChar (CyclotomicUnitDelta p) R)).filter
              (fun χ => IsEvenDeltaCharacter (p := p) χ)).filter
                (fun χ => χ = (1 : MulChar (CyclotomicUnitDelta p) R)),
              charIdempotent χ) +
            ∑ χ ∈ ((Finset.univ : Finset (MulChar (CyclotomicUnitDelta p) R)).filter
              (fun χ => IsEvenDeltaCharacter (p := p) χ)).filter
                (fun χ => ¬ χ = (1 : MulChar (CyclotomicUnitDelta p) R)),
              charIdempotent χ := by
              rw [Finset.sum_filter_add_sum_filter_not]
      _ = charIdempotent (1 : MulChar (CyclotomicUnitDelta p) R) +
          ∑ χ ∈ (Finset.univ : Finset (MulChar (CyclotomicUnitDelta p) R)).filter
              (fun χ => IsEvenDeltaCharacter (p := p) χ ∧
                χ ≠ (1 : MulChar (CyclotomicUnitDelta p) R)),
            charIdempotent χ := by
            have h_one_filter :
                ((Finset.univ : Finset (MulChar (CyclotomicUnitDelta p) R)).filter
                  (fun χ => IsEvenDeltaCharacter (p := p) χ)).filter
                    (fun χ => χ = (1 : MulChar (CyclotomicUnitDelta p) R)) =
                  {1} := by
              ext χ
              by_cases hχ : χ = (1 : MulChar (CyclotomicUnitDelta p) R)
              · subst χ
                simp
              · simp [hχ]
            have h_ne_filter :
                ((Finset.univ : Finset (MulChar (CyclotomicUnitDelta p) R)).filter
                  (fun χ => IsEvenDeltaCharacter (p := p) χ)).filter
                    (fun χ => ¬ χ = (1 : MulChar (CyclotomicUnitDelta p) R)) =
                  (Finset.univ : Finset (MulChar (CyclotomicUnitDelta p) R)).filter
                    (fun χ => IsEvenDeltaCharacter (p := p) χ ∧
                      χ ≠ (1 : MulChar (CyclotomicUnitDelta p) R)) := by
              ext χ
              simp [ne_eq]
            rw [h_one_filter, h_ne_filter]
            simp
  rw [hsplit]
  abel

end DeltaIdempotents

end BernoulliRegular

end
