module

public import BernoulliRegular.FLT37.Primary
public import BernoulliRegular.Reflection.ResidueSymbol.Furtwaengler.PthSymbolPrincipalCanonical

/-!
# Basic definitions for Eisenstein reciprocity

This file contains only the concrete objects and support hypotheses used by
the Eisenstein reciprocity bridge: rational-integer principal ideals,
absolute-norm principal ideals, and the coprimality conditions on denominators.
It deliberately contains no bundled reciprocity `Prop`.
-/

@[expose] public section

noncomputable section

open scoped NumberField

namespace BernoulliRegular

namespace Furtwaengler

variable {p : ℕ} [Fact p.Prime]
variable {K : Type*} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- Singular-primary input needed for the rational-integer consequence.

This is only the arithmetic data consumed in this file: nonzero `η`,
prime-to-`p`, primary, and `(η) = b^p`. -/
structure Ref18SingularInput (η : 𝓞 K) (b : Ideal (𝓞 K)) : Prop where
  eta_ne : η ≠ 0
  eta_p_top : Ideal.span ({η, (p : 𝓞 K)} : Set (𝓞 K)) = ⊤
  eta_primary : FLT37.IsPrimary p (K := K) η
  eta_eq_root_pow : Ideal.span ({η} : Set (𝓞 K)) = b ^ p

/-- The principal ideal of `𝓞 K` generated by a rational integer. -/
def rationalIntIdeal (a : ℤ) : Ideal (𝓞 K) :=
  Ideal.span ({algebraMap ℤ (𝓞 K) a} : Set (𝓞 K))

/-- The principal ideal generated by the absolute norm of an integral ideal. -/
def idealNormPrincipalIdeal (B : Ideal (𝓞 K)) : Ideal (𝓞 K) :=
  Ideal.span ({algebraMap ℤ (𝓞 K) (B.absNorm : ℤ)} : Set (𝓞 K))

/-- The canonical residue symbol with rational-integer denominator. -/
def pthSymbolAtInt_canonical (α : 𝓞 K) (a : ℤ) : ZMod p :=
  pthSymbolAtIdeal_canonical (p := p) (K := K) α (rationalIntIdeal (K := K) a)

@[simp] theorem pthSymbolAtInt_canonical_eq_atIdeal
    (α : 𝓞 K) (a : ℤ) :
    pthSymbolAtInt_canonical (p := p) (K := K) α a =
      pthSymbolAtIdeal_canonical (p := p) (K := K) α
        (rationalIntIdeal (K := K) a) :=
  rfl

/-- `α` is prime to the rational prime `p`. -/
def IsPrimeToP (α : 𝓞 K) : Prop :=
  α ≠ 0 ∧ Ideal.span ({α, (p : 𝓞 K)} : Set (𝓞 K)) = ⊤

/-- Coprimality hypotheses for the ideal-norm statement.

The first two coprimality conditions say that `B` is away from `(α)` and from
the rational prime `p`, separately.  This must not be collapsed to
`IsCoprime B (span {α, p})`: once `α` is prime to `p`, that span is `⊤` and
the condition would no longer exclude primes above `p` from the denominator.

The final condition records the support condition needed to read the
right-hand symbol `(NB / α)_p` as an honest coprime symbol; the canonical
symbol is total, but the mathematical support condition remains explicit. -/
def IsCoprimeToPAndAlpha (B : Ideal (𝓞 K)) (α : 𝓞 K) : Prop :=
  B ≠ ⊥ ∧
    IsCoprime B (Ideal.span ({α} : Set (𝓞 K))) ∧
      IsCoprime B (Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K))) ∧
        IsCoprime (idealNormPrincipalIdeal (K := K) B)
          (Ideal.span ({α} : Set (𝓞 K)))

/-- Coprimality hypotheses for rational-integer Eisenstein reciprocity. -/
def IsCoprimeToPAndAlphaInt (a : ℤ) (α : 𝓞 K) : Prop :=
  a ≠ 0 ∧
    IsCoprime (rationalIntIdeal (K := K) a)
      (Ideal.span ({α} : Set (𝓞 K))) ∧
    IsCoprime (rationalIntIdeal (K := K) a)
      (Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K)))

/-- A direct integer reciprocity equality gives the singular-primary
rational-integer vanishing needed downstream. -/
theorem singularPrimary_int_symbol_eq_zero_of_intReciprocity
    {η : 𝓞 K} {b : Ideal (𝓞 K)}
    (h_rec :
      ∀ a : ℤ, IsCoprimeToPAndAlphaInt (p := p) (K := K) a η →
        pthSymbolAtInt_canonical (p := p) (K := K) η a =
          pthSymbolAtIdeal_canonical (p := p) (K := K)
            (algebraMap ℤ (𝓞 K) a) (Ideal.span ({η} : Set (𝓞 K))))
    (h_sing : Ref18SingularInput (p := p) (K := K) η b)
    {a : ℤ}
    (ha : IsCoprimeToPAndAlphaInt (p := p) (K := K) a η) :
    pthSymbolAtInt_canonical (p := p) (K := K) η a = 0 := by
  rw [h_rec a ha, h_sing.eta_eq_root_pow]
  exact pthSymbolAtIdeal_canonical_pow_p_ideal_eq_zero
    (p := p) (K := K) (algebraMap ℤ (𝓞 K) a) b

end Furtwaengler

end BernoulliRegular

end
