module

public import BernoulliRegular.Reflection.ResidueSymbol.Furtwaengler.EisensteinReciprocityBasic

/-!
# Integer-denominator Eisenstein reciprocity from the ideal-norm form

This file restores the rational-integer denominator step of REF-21.6 without
reintroducing bundled routes.  The generic proof below is the elementary
norm/cancellation argument converting a concrete ideal-norm reciprocity
equality into the rational-integer equality.

-/

@[expose] public section

noncomputable section

open scoped NumberField

namespace BernoulliRegular

namespace Furtwaengler

variable {p : ℕ} [Fact p.Prime]
variable {K : Type*} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- The integral basis rank of the ring of integers of `ℚ(ζ_p)` is `p - 1`. -/
theorem cyclotomicRingOfIntegers_finrank_eq :
    Module.finrank ℤ (𝓞 K) = p - 1 := by
  rw [NumberField.RingOfIntegers.rank,
    IsCyclotomicExtension.finrank K
      (Polynomial.cyclotomic.irreducible_rat (Fact.out : Nat.Prime p).pos),
    Nat.totient_prime (Fact.out : Nat.Prime p)]

/-- The ideal generated by the absolute norm of the rational principal ideal
`(n)` is `(n)^(p-1)` in the `p`-th cyclotomic ring. -/
theorem idealNormPrincipalIdeal_rationalIntIdeal_natCast
    (n : ℕ) :
    idealNormPrincipalIdeal (K := K)
        (rationalIntIdeal (K := K) (n : ℤ)) =
      (rationalIntIdeal (K := K) (n : ℤ)) ^ (p - 1) := by
  classical
  have hnorm :
      Ideal.absNorm
          (Ideal.span ({algebraMap ℤ (𝓞 K) (n : ℤ)} : Set (𝓞 K))) =
        n ^ (p - 1) := by
    have hcast : algebraMap ℤ (𝓞 K) (n : ℤ) = (n : 𝓞 K) := by norm_num
    rw [hcast, Ideal.absNorm_span_natCast,
      cyclotomicRingOfIntegers_finrank_eq (p := p) (K := K)]
  unfold idealNormPrincipalIdeal rationalIntIdeal
  rw [hnorm]
  have hcast_n :
      algebraMap ℤ (𝓞 K) (n : ℤ) = (n : 𝓞 K) := by norm_num
  have hcast_pow :
      algebraMap ℤ (𝓞 K) ((n ^ (p - 1) : ℕ) : ℤ) =
        (n : 𝓞 K) ^ (p - 1) := by norm_num
  rw [hcast_pow, hcast_n, Ideal.span_singleton_pow]

/-- In `ZMod p`, multiplication by `p - 1` is cancellative because
`p - 1 = -1`. -/
theorem zmod_prime_sub_one_mul_cancel
    (hp_gt_two : 2 < p) {x y : ZMod p}
    (h : ((p - 1 : ℕ) : ZMod p) * x =
      ((p - 1 : ℕ) : ZMod p) * y) :
    x = y := by
  have hp_pos : 0 < p := lt_trans (by norm_num) hp_gt_two
  have hp_one : 1 ≤ p := Nat.succ_le_of_lt hp_pos
  have hscalar : ((p - 1 : ℕ) : ZMod p) = -1 := by
    rw [Nat.cast_sub hp_one, ZMod.natCast_self]
    norm_num
  have hneg : -x = -y := by
    simpa [hscalar] using h
  exact neg_injective hneg

/-- Coprimality of `(n)` with `(α)` excludes `n` from every normalized
factor of `(α)`. -/
theorem natCast_notMem_of_isCoprime_rationalIntIdeal
    {α : 𝓞 K} {n : ℕ}
    (hcop :
      IsCoprime (rationalIntIdeal (K := K) (n : ℤ))
        (Ideal.span ({α} : Set (𝓞 K))))
    {P : Ideal (𝓞 K)}
    (hP : P ∈ UniqueFactorizationMonoid.normalizedFactors
      (Ideal.span ({α} : Set (𝓞 K)))) :
    (n : 𝓞 K) ∉ P := by
  intro hn_mem
  obtain ⟨_, _hP_ne, hP_max⟩ := isPrime_of_mem_normalizedFactors hP
  have hn_span_le :
      rationalIntIdeal (K := K) (n : ℤ) ≤ P := by
    rw [rationalIntIdeal, Ideal.span_singleton_le_iff_mem]
    simpa using hn_mem
  have hα_span_le : Ideal.span ({α} : Set (𝓞 K)) ≤ P := by
    rw [← Ideal.dvd_iff_le]
    exact UniqueFactorizationMonoid.dvd_of_mem_normalizedFactors hP
  have htop_le : ⊤ ≤ P := by
    rw [← hcop.sup_eq]
    exact sup_le hn_span_le hα_span_le
  exact hP_max.ne_top (top_le_iff.mp htop_le)

/-- The ideal-norm equality implies rational-integer Eisenstein reciprocity for
nonnegative rational integers.  The cancellation is by the scalar `p - 1`,
not by a prime-by-prime vanishing statement. -/
theorem eisensteinReciprocityInt_natCast_of_idealNormReciprocity
    {α : 𝓞 K}
    (hIdeal :
      ∀ B : Ideal (𝓞 K), IsCoprimeToPAndAlpha (p := p) (K := K) B α →
        pthSymbolAtIdeal_canonical (p := p) (K := K) α
            (idealNormPrincipalIdeal (K := K) B) =
          pthSymbolAtIdeal_canonical (p := p) (K := K)
            (algebraMap ℤ (𝓞 K) (B.absNorm : ℤ))
            (Ideal.span ({α} : Set (𝓞 K))))
    (hp_gt_two : 2 < p)
    {n : ℕ}
    (ha : IsCoprimeToPAndAlphaInt (p := p) (K := K) (n : ℤ) α) :
    pthSymbolAtInt_canonical (p := p) (K := K) α (n : ℤ) =
      pthSymbolAtIdeal_canonical (p := p) (K := K)
        (n : 𝓞 K) (Ideal.span ({α} : Set (𝓞 K))) := by
  let B : Ideal (𝓞 K) := rationalIntIdeal (K := K) (n : ℤ)
  have hB_ne : B ≠ ⊥ := by
    have hn_ne_int : (n : ℤ) ≠ 0 := ha.1
    have hn_ne : (n : 𝓞 K) ≠ 0 := by
      have hmap_ne :
          algebraMap ℤ (𝓞 K) (n : ℤ) ≠ algebraMap ℤ (𝓞 K) 0 :=
        (FaithfulSMul.algebraMap_injective ℤ (𝓞 K)).ne hn_ne_int
      simpa using hmap_ne
    change rationalIntIdeal (K := K) (n : ℤ) ≠ ⊥
    rw [rationalIntIdeal, Ne, Ideal.span_singleton_eq_bot]
    simpa using hn_ne
  have hB_coprime : IsCoprimeToPAndAlpha (p := p) (K := K) B α := by
    refine ⟨hB_ne, ha.2.1, ha.2.2, ?_⟩
    have hnorm :=
      idealNormPrincipalIdeal_rationalIntIdeal_natCast (p := p) (K := K) n
    change IsCoprime (idealNormPrincipalIdeal (K := K) B)
      (Ideal.span ({α} : Set (𝓞 K)))
    change IsCoprime
      (idealNormPrincipalIdeal (K := K) (rationalIntIdeal (K := K) (n : ℤ)))
      (Ideal.span ({α} : Set (𝓞 K)))
    rw [hnorm]
    exact ha.2.1.pow_left
  have hrec := hIdeal B hB_coprime
  have hleft :
      pthSymbolAtIdeal_canonical (p := p) (K := K) α
          (idealNormPrincipalIdeal (K := K) B) =
        ((p - 1 : ℕ) : ZMod p) *
          pthSymbolAtInt_canonical (p := p) (K := K) α (n : ℤ) := by
    have hnorm :=
      idealNormPrincipalIdeal_rationalIntIdeal_natCast (p := p) (K := K) n
    change pthSymbolAtIdeal_canonical (p := p) (K := K) α
        (idealNormPrincipalIdeal (K := K) (rationalIntIdeal (K := K) (n : ℤ))) =
      ((p - 1 : ℕ) : ZMod p) *
        pthSymbolAtInt_canonical (p := p) (K := K) α (n : ℤ)
    rw [hnorm]
    change pthSymbolAtIdeal_canonical (p := p) (K := K) α
        ((rationalIntIdeal (K := K) (n : ℤ)) ^ (p - 1)) =
      ((p - 1 : ℕ) : ZMod p) *
        pthSymbolAtIdeal_canonical (p := p) (K := K) α
          (rationalIntIdeal (K := K) (n : ℤ))
    simpa using
      (pthSymbolAtIdeal_canonical_pow_ideal
        (p := p) (K := K) α (rationalIntIdeal (K := K) (n : ℤ)) (p - 1))
  have hB_abs :
      Ideal.absNorm B = n ^ (p - 1) := by
    have hnorm :
        Ideal.absNorm
            (Ideal.span ({algebraMap ℤ (𝓞 K) (n : ℤ)} : Set (𝓞 K))) =
          n ^ (p - 1) := by
      have hcast : algebraMap ℤ (𝓞 K) (n : ℤ) = (n : 𝓞 K) := by norm_num
      rw [hcast, Ideal.absNorm_span_natCast,
        cyclotomicRingOfIntegers_finrank_eq (p := p) (K := K)]
    change Ideal.absNorm (rationalIntIdeal (K := K) (n : ℤ)) = n ^ (p - 1)
    simpa [rationalIntIdeal] using hnorm
  have hsupport :
      ∀ P ∈ UniqueFactorizationMonoid.normalizedFactors
          (Ideal.span ({α} : Set (𝓞 K))), (n : 𝓞 K) ∉ P := fun P hP =>
    natCast_notMem_of_isCoprime_rationalIntIdeal
        (K := K) ha.2.1 hP
  have hright :
      pthSymbolAtIdeal_canonical (p := p) (K := K)
          (algebraMap ℤ (𝓞 K) (B.absNorm : ℤ))
          (Ideal.span ({α} : Set (𝓞 K))) =
        ((p - 1 : ℕ) : ZMod p) *
          pthSymbolAtIdeal_canonical (p := p) (K := K)
            (n : 𝓞 K) (Ideal.span ({α} : Set (𝓞 K))) := by
    rw [hB_abs]
    have hcast_pow :
        algebraMap ℤ (𝓞 K) ((n ^ (p - 1) : ℕ) : ℤ) =
          (n : 𝓞 K) ^ (p - 1) := by norm_num
    rw [hcast_pow]
    change pthSymbolAtPrincipal_canonical (p := p) (K := K)
        ((n : 𝓞 K) ^ (p - 1)) α =
      ((p - 1 : ℕ) : ZMod p) *
        pthSymbolAtPrincipal_canonical (p := p) (K := K) (n : 𝓞 K) α
    simpa using
      (pthSymbolAtPrincipal_canonical_pow_left
        (p := p) (K := K) (n : 𝓞 K) α (p - 1) hsupport)
  have hscaled :
      ((p - 1 : ℕ) : ZMod p) *
          pthSymbolAtInt_canonical (p := p) (K := K) α (n : ℤ) =
        ((p - 1 : ℕ) : ZMod p) *
          pthSymbolAtIdeal_canonical (p := p) (K := K)
            (n : 𝓞 K) (Ideal.span ({α} : Set (𝓞 K))) := by
    rw [← hleft, ← hright]
    exact hrec
  exact zmod_prime_sub_one_mul_cancel (p := p) hp_gt_two hscaled

/-- The ideal-norm equality implies the rational-integer Eisenstein
reciprocity equality. -/
theorem eisensteinReciprocityInt_of_idealNormReciprocity
    {α : 𝓞 K}
    (hIdeal :
      ∀ B : Ideal (𝓞 K), IsCoprimeToPAndAlpha (p := p) (K := K) B α →
        pthSymbolAtIdeal_canonical (p := p) (K := K) α
            (idealNormPrincipalIdeal (K := K) B) =
          pthSymbolAtIdeal_canonical (p := p) (K := K)
            (algebraMap ℤ (𝓞 K) (B.absNorm : ℤ))
            (Ideal.span ({α} : Set (𝓞 K))))
    (hp_gt_two : 2 < p)
    {a : ℤ}
    (ha : IsCoprimeToPAndAlphaInt (p := p) (K := K) a α) :
    pthSymbolAtInt_canonical (p := p) (K := K) α a =
      pthSymbolAtIdeal_canonical (p := p) (K := K)
        (algebraMap ℤ (𝓞 K) a) (Ideal.span ({α} : Set (𝓞 K))) := by
  rcases a.eq_nat_or_neg with ⟨n, rfl | rfl⟩
  · simpa using
      (eisensteinReciprocityInt_natCast_of_idealNormReciprocity
        (p := p) (K := K) hIdeal hp_gt_two ha)
  · have hp_ne_two : p ≠ 2 := by omega
    have hp_odd : Odd p := (Fact.out : Nat.Prime p).odd_of_ne_two hp_ne_two
    have hrat_neg :
        rationalIntIdeal (K := K) (-(n : ℤ)) =
          rationalIntIdeal (K := K) (n : ℤ) := by
      unfold rationalIntIdeal
      have hcast_neg :
          algebraMap ℤ (𝓞 K) (-(n : ℤ)) = -(n : 𝓞 K) := by norm_num
      have hcast :
          algebraMap ℤ (𝓞 K) (n : ℤ) = (n : 𝓞 K) := by norm_num
      rw [hcast_neg, hcast, Ideal.span_singleton_neg]
    have ha_nat : IsCoprimeToPAndAlphaInt (p := p) (K := K) (n : ℤ) α := by
      refine ⟨?_, ?_, ?_⟩
      · exact fun hn_zero => ha.1 (by simp [hn_zero])
      · simpa [hrat_neg] using ha.2.1
      · simpa [hrat_neg] using ha.2.2
    have hnat :=
      eisensteinReciprocityInt_natCast_of_idealNormReciprocity
        (p := p) (K := K) hIdeal hp_gt_two ha_nat
    have hleft :
        pthSymbolAtInt_canonical (p := p) (K := K) α (-(n : ℤ)) =
          pthSymbolAtInt_canonical (p := p) (K := K) α (n : ℤ) := by
      simp [pthSymbolAtInt_canonical, rationalIntIdeal]
    have hright :
        pthSymbolAtIdeal_canonical (p := p) (K := K)
            (algebraMap ℤ (𝓞 K) (-(n : ℤ)))
            (Ideal.span ({α} : Set (𝓞 K))) =
          pthSymbolAtIdeal_canonical (p := p) (K := K)
            (algebraMap ℤ (𝓞 K) (n : ℤ))
            (Ideal.span ({α} : Set (𝓞 K))) := by
      have hcast_neg :
          algebraMap ℤ (𝓞 K) (-(n : ℤ)) = -(n : 𝓞 K) := by norm_num
      have hcast :
          algebraMap ℤ (𝓞 K) (n : ℤ) = (n : 𝓞 K) := by norm_num
      rw [hcast_neg, hcast]
      change pthSymbolAtIdeal_canonical (p := p) (K := K)
          (-(n : 𝓞 K)) (Ideal.span ({α} : Set (𝓞 K))) =
        pthSymbolAtIdeal_canonical (p := p) (K := K)
          (n : 𝓞 K) (Ideal.span ({α} : Set (𝓞 K)))
      exact
        pthSymbolAtIdeal_canonical_neg_uncond_of_odd
          (p := p) (K := K) hp_odd (n : 𝓞 K)
          (Ideal.span ({α} : Set (𝓞 K)))
    rw [hleft, hright]
    simpa using hnat

end Furtwaengler

end BernoulliRegular

end
