module

public import BernoulliRegular.Reflection.ResidueSymbol.Furtwaengler.TraceFormSetup
public import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
public import Mathlib.Algebra.BigOperators.Associated
public import Mathlib.Algebra.Ring.Associated
public import Mathlib.RingTheory.RootsOfUnity.CyclotomicUnits
public import Mathlib.RingTheory.Polynomial.Cyclotomic.Eval
public import FltRegular.NumberTheory.Cyclotomic.UnitLemmas


/-!
# Uniformizer fact derivation (REF-18c2c4-L2c3a-prove)

Provides a free-standing proof that `π = ζ_ℓ - 1` is a `Q`-uniformizer
in `R' = ℚ(ζ_p, ζ_ℓ)` for any prime `Q` of `𝓞 R'` above `ℓ`. This
derives the field `pi_not_mem_Q_sq` of `TraceFormStickelbergerSetup`
from cyclotomic ramification theory (mathlib's
`IsCyclotomicExtension.Rat.ramificationIdx_eq` with `n = ℓ · p`,
prime `ℓ`, `m = p`, `k = 0`).

Strategy:
1. Convert `IsCyclotomicExtension {p, ℓ} ℚ R'` to
   `IsCyclotomicExtension {ℓ · p} ℚ R'` via `IsPrimitiveRoot.pow_mul_pow_lcm`
   + `IsPrimitiveRoot.adjoin_pair_eq` + `isCyclotomicExtension_singleton_iff_eq_adjoin`.
2. Apply `IsCyclotomicExtension.Rat.ramificationIdx_eq` to get
   `ramificationIdx of ℓ in 𝓞 R' = ℓ - 1`.
3. The cyclotomic identity `ℓ = u · π^(ℓ-1)` (for some unit `u`)
   combined with the ramification index gives `v_Q(π) = 1`, hence
   `π ∉ Q^2`.
-/

@[expose] public section

noncomputable section

open scoped NumberField

namespace BernoulliRegular

namespace Furtwaengler

universe u v w

/-- Conversion: from `IsCyclotomicExtension {p, ℓ} ℚ R'` (set of two
distinct primes), derive `IsCyclotomicExtension {p · ℓ} ℚ R'`
(singleton on the product). For coprime `p, ℓ`, `ℚ(ζ_p, ζ_ℓ) = ℚ(ζ_{pℓ})`. -/
theorem isCyclotomicExtension_singleton_mul_of_pair
    {p ℓ : ℕ} [Fact p.Prime] [Fact ℓ.Prime] (hpℓ : p ≠ ℓ)
    {R' : Type w} [CommRing R'] [Algebra ℚ R']
    [hR' : IsCyclotomicExtension {p, ℓ} ℚ R'] :
    IsCyclotomicExtension {p * ℓ} ℚ R' := by
  haveI hp_prime : Nat.Prime p := Fact.out
  haveI hℓ_prime : Nat.Prime ℓ := Fact.out
  haveI : NeZero p := ⟨hp_prime.ne_zero⟩
  haveI : NeZero ℓ := ⟨hℓ_prime.ne_zero⟩
  haveI hpℓ_ne : NeZero (p * ℓ) := ⟨Nat.mul_ne_zero (NeZero.ne p) (NeZero.ne ℓ)⟩
  -- Get primitive p-th and ℓ-th roots from the {p, ℓ}-cyclotomic structure.
  have h_p_mem : (p : ℕ) ∈ ({p, ℓ} : Set ℕ) := Set.mem_insert _ _
  have h_ℓ_mem : (ℓ : ℕ) ∈ ({p, ℓ} : Set ℕ) :=
    Set.mem_insert_of_mem _ (Set.mem_singleton _)
  obtain ⟨ζ_p, hζ_p⟩ := hR'.1 h_p_mem (NeZero.ne p)
  obtain ⟨ζ_ℓ, hζ_ℓ⟩ := hR'.1 h_ℓ_mem (NeZero.ne ℓ)
  -- Coprime ⇒ lcm = product.
  have h_coprime : Nat.Coprime p ℓ :=
    (Nat.coprime_primes hp_prime hℓ_prime).mpr hpℓ
  have h_lcm : Nat.lcm p ℓ = p * ℓ := h_coprime.lcm_eq_mul
  -- Construct primitive (p · ℓ)-th root via pow_mul_pow_lcm.
  set ζ : R' := ζ_p ^ (p / Nat.factorizationLCMLeft p ℓ) *
                ζ_ℓ ^ (ℓ / Nat.factorizationLCMRight p ℓ) with hζ_def
  have hζ_lcm : IsPrimitiveRoot ζ (Nat.lcm p ℓ) :=
    IsPrimitiveRoot.pow_mul_pow_lcm hζ_p hζ_ℓ (NeZero.ne p) (NeZero.ne ℓ)
  have hζ : IsPrimitiveRoot ζ (p * ℓ) := h_lcm ▸ hζ_lcm
  -- Construct the IsCyclotomicExtension instance directly.
  refine ⟨?_, ?_⟩
  · -- Existence of primitive (p · ℓ)-th root.
    rintro n hn hn_ne
    rw [Set.mem_singleton_iff] at hn
    subst hn
    exact ⟨ζ, hζ⟩
  · -- R' is generated by (p · ℓ)-th roots over ℚ.
    intro x
    have hx_in_pair :=
      IsCyclotomicExtension.adjoin_roots (S := ({p, ℓ} : Set ℕ)) (A := ℚ) (B := R') x
    apply Algebra.adjoin_mono ?_ hx_in_pair
    rintro y ⟨n, hn_mem, hn_ne, hyn⟩
    refine ⟨p * ℓ, Set.mem_singleton _, NeZero.ne _, ?_⟩
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hn_mem
    rcases hn_mem with rfl | rfl
    · -- y^p = 1 ⟹ y^(p · ℓ) = 1
      rw [pow_mul, hyn, one_pow]
    · -- y^ℓ = 1 ⟹ y^(p · ℓ) = 1
      rw [mul_comm, pow_mul, hyn, one_pow]

/-- **`IsCMField` instance for cyclotomic pair**: when `R'` is a
cyclotomic extension of `ℚ` at `{p, ℓ}` for distinct primes `p, ℓ`,
`R'` is a CM field. Routes through the singleton-mul conversion to
conductor `p * ℓ`, then applies
`IsCyclotomicExtension.IsCMField` from flt-regular at conductor `p * ℓ`,
which is automatically `> 2` for primes `≥ 2` with `p ≠ ℓ`. -/
theorem isCMField_of_cyclotomicExtension_pair_primes
    {p ℓ : ℕ} [Fact p.Prime] [Fact ℓ.Prime] (hpℓ : p ≠ ℓ)
    {R' : Type w} [Field R'] [NumberField R']
    [hR' : IsCyclotomicExtension {p, ℓ} ℚ R'] :
    NumberField.IsCMField R' := by
  haveI hp_prime : Nat.Prime p := Fact.out
  haveI hℓ_prime : Nat.Prime ℓ := Fact.out
  haveI : IsCyclotomicExtension {p * ℓ} ℚ R' :=
    isCyclotomicExtension_singleton_mul_of_pair hpℓ
  haveI : NeZero (p * ℓ) :=
    ⟨Nat.mul_ne_zero hp_prime.ne_zero hℓ_prime.ne_zero⟩
  have h_pl_gt_two : 2 < p * ℓ := by
    have hp_ge_two : 2 ≤ p := hp_prime.two_le
    have hℓ_ge_two : 2 ≤ ℓ := hℓ_prime.two_le
    -- p * ℓ ≥ 2 * 2 = 4 > 2 unless p = ℓ = 2, but hpℓ : p ≠ ℓ excludes that.
    have h_four : 4 ≤ p * ℓ :=
      calc 4 = 2 * 2 := by norm_num
        _ ≤ p * ℓ := Nat.mul_le_mul hp_ge_two hℓ_ge_two
    omega
  exact IsCyclotomicExtension.Rat.isCMField (S := {p * ℓ}) R' ⟨p * ℓ, rfl, h_pl_gt_two⟩

/-- **Generic `CharP` witness for a ring-of-integers quotient**: for
any number field `F` and maximal `P ⊂ 𝓞 F` containing a rational prime
`ell`, the residue field has characteristic `ell`. No cyclotomic
hypothesis required. -/
theorem charP_residueField_of_natCast_mem
    {F : Type*} [Field F] [NumberField F]
    {ell : ℕ} [hℓ : Fact ell.Prime]
    (P : Ideal (𝓞 F)) [hP_max : P.IsMaximal]
    (hℓ_in_P : (ell : 𝓞 F) ∈ P) :
    CharP (𝓞 F ⧸ P) ell := by
  letI : Field (𝓞 F ⧸ P) := Ideal.Quotient.field P
  refine ⟨fun n => ?_⟩
  rw [show ((n : 𝓞 F ⧸ P)) = (Ideal.Quotient.mk P) ((n : 𝓞 F)) from
    (map_natCast _ _).symm]
  rw [Ideal.Quotient.eq_zero_iff_mem]
  constructor
  · intro h_mem
    have hℓ_in_comap : (ell : ℤ) ∈ Ideal.comap (algebraMap ℤ (𝓞 F)) P := by
      rw [Ideal.mem_comap]; simpa using hℓ_in_P
    have h_span_le : Ideal.span ({(ell : ℤ)} : Set ℤ) ≤ Ideal.under ℤ P := by
      rw [Ideal.span_le, Set.singleton_subset_iff]; exact hℓ_in_comap
    have hℓ_prime_int : Prime ((ell : ℤ)) := by
      rw [Int.prime_iff_natAbs_prime]; simpa using (Fact.out : ell.Prime)
    have h_span_max : (Ideal.span ({(ell : ℤ)} : Set ℤ)).IsMaximal :=
      PrincipalIdealRing.isMaximal_of_irreducible hℓ_prime_int.irreducible
    have h_under_ne_top : Ideal.under ℤ P ≠ ⊤ := by
      intro h
      have : (1 : ℤ) ∈ Ideal.under ℤ P := h ▸ Submodule.mem_top
      rw [Ideal.under, Ideal.mem_comap] at this
      have h_one : (1 : 𝓞 F) ∈ P := by
        simpa using this
      exact hP_max.ne_top (Ideal.eq_top_of_isUnit_mem _ h_one isUnit_one)
    have h_eq : Ideal.span ({(ell : ℤ)} : Set ℤ) = Ideal.under ℤ P :=
      h_span_max.eq_of_le h_under_ne_top h_span_le
    have hn_in_under : (n : ℤ) ∈ Ideal.under ℤ P := by
      rw [Ideal.under, Ideal.mem_comap]
      push_cast
      exact h_mem
    rw [← h_eq, Ideal.mem_span_singleton] at hn_in_under
    exact_mod_cast hn_in_under
  · intro h_dvd
    obtain ⟨k, rfl⟩ := h_dvd
    push_cast
    exact Ideal.mul_mem_right _ _ hℓ_in_P

/-- **Complex conjugation of a primitive `n`-th root in a CM field**:
for any CM field `F` and any `ζ : 𝓞 F` that is a primitive `n`-th root,
complex conjugation sends `ζ` to `ζ ^ (n - 1)` (i.e., its inverse).

This is the generic version of `complexConj_apply_zeta` (which was
specialized to the canonical cyclotomic root). It works for any
primitive `n`-th root in any CM field. -/
theorem ringOfIntegersComplexConj_primitiveRoot
    {n : ℕ} (hn_pos : 0 < n)
    {F : Type*} [Field F] [NumberField F] [NumberField.IsCMField F]
    {ζ : 𝓞 F} (hζ : IsPrimitiveRoot ζ n) :
    (NumberField.IsCMField.ringOfIntegersComplexConj F ζ : 𝓞 F) =
      (ζ : 𝓞 F) ^ (n - 1) := by
  haveI : NeZero n := ⟨hn_pos.ne'⟩
  -- ζ is a unit (primitive root in a domain).
  have hζ_unit : IsUnit ζ := hζ.isUnit hn_pos.ne'
  let u : (𝓞 F)ˣ := hζ_unit.unit
  have hu_val : (u : 𝓞 F) = ζ := IsUnit.unit_spec _
  -- u is in the torsion subgroup since u^n = 1.
  have hu_pow : u ^ n = 1 := by
    apply Units.ext
    rw [Units.val_pow_eq_pow_val, hu_val, Units.val_one]
    exact hζ.pow_eq_one
  have hu_torsion : u ∈ NumberField.Units.torsion F := by
    refine (CommGroup.mem_torsion _).2 ?_
    exact isOfFinOrder_iff_pow_eq_one.2 ⟨n, hn_pos, hu_pow⟩
  -- complexConj sends torsion to inverse.
  have hconj := NumberField.IsCMField.unitsComplexConj_torsion F ⟨u, hu_torsion⟩
  -- u⁻¹ = u ^ (n-1) since u^n = 1.
  have hu_inv : u⁻¹ = u ^ (n - 1) := by
    apply inv_eq_of_mul_eq_one_left
    rw [← pow_succ, Nat.sub_one_add_one hn_pos.ne']
    exact hu_pow
  -- Combine: ringOfIntegersComplexConj F ζ = u⁻¹ as integers, which equals u^(n-1) = ζ^(n-1).
  have h_ring_eq_units : (NumberField.IsCMField.ringOfIntegersComplexConj F ζ : 𝓞 F) =
      ((NumberField.IsCMField.unitsComplexConj F u : (𝓞 F)ˣ) : 𝓞 F) := by
    have : (NumberField.IsCMField.ringOfIntegersComplexConj F ζ : 𝓞 F) =
        (NumberField.IsCMField.ringOfIntegersComplexConj F (u : 𝓞 F) : 𝓞 F) := by
      rw [hu_val]
    rw [this]
    rfl
  rw [h_ring_eq_units, hconj]
  -- Goal: ↑↑⟨u, hu_torsion⟩⁻¹ = ζ ^ (n - 1)
  -- Note: torsion-subgroup inverse coerces to (𝓞 F)ˣ inverse on the underlying value.
  have h_torsion_inv :
      ((⟨u, hu_torsion⟩⁻¹ : NumberField.Units.torsion F) : (𝓞 F)ˣ) = u⁻¹ := rfl
  rw [h_torsion_inv, hu_inv, Units.val_pow_eq_pow_val, hu_val]

/-- **Upstairs complex conjugation lifts downstairs**, CM-field form.

For `K = ℚ(ζ_p)` with `p > 2`, complex conjugation on any CM upstairs field
`R'` restricts to the cyclotomic complex conjugation on `K`, provided the
integer algebra map `𝓞 K → 𝓞 R'` is faithful. This is the form needed by the
source-conductor REF-18 route, where the upstairs field is cyclotomic for
`ell * (#k - 1)` rather than literally pair-cyclotomic. -/
theorem upstairsComplexConj_lifts_downstairs_of_isCMField
    {p : ℕ} [hp : Fact p.Prime] (hp_gt_two : 2 < p)
    {K : Type v} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
    {R' : Type w} [Field R'] [NumberField R'] [Algebra K R']
    [IsScalarTower ℚ K R']
    [IsScalarTower ℤ (𝓞 K) (𝓞 R')]
    [NumberField.IsCMField R']
    [FaithfulSMul (𝓞 K) (𝓞 R')]
    (x : 𝓞 K) :
    haveI : NumberField.IsCMField K :=
      IsCyclotomicExtension.Rat.isCMField (S := {p}) K ⟨p, rfl, hp_gt_two⟩
    NumberField.IsCMField.ringOfIntegersComplexConj R'
        (algebraMap (𝓞 K) (𝓞 R') x) =
      algebraMap (𝓞 K) (𝓞 R')
        (NumberField.IsCMField.ringOfIntegersComplexConj K x) := by
  haveI : NumberField.IsCMField K :=
    IsCyclotomicExtension.Rat.isCMField (S := {p}) K ⟨p, rfl, hp_gt_two⟩
  have hp_pos : 0 < p := hp.1.pos
  -- Induction on x ∈ Algebra.adjoin ℤ {ζ_p} = ⊤.
  have hζ := IsCyclotomicExtension.zeta_spec p ℚ K
  have htop : Algebra.adjoin ℤ ({hζ.toInteger} : Set (𝓞 K)) = ⊤ :=
    IsCyclotomicExtension.Rat.adjoin_singleton_eq_top hζ
  have hx_in : x ∈ Algebra.adjoin ℤ ({hζ.toInteger} : Set (𝓞 K)) := htop ▸ trivial
  -- Helper: complexConj fixes integers (as a ring hom).
  have h_int_fix : ∀ (r : ℤ),
      (NumberField.IsCMField.ringOfIntegersComplexConj R') ((algebraMap ℤ (𝓞 R')) r) =
        (algebraMap ℤ (𝓞 R')) r := by
    intro r
    -- algebraMap ℤ (𝓞 R') r = (r : 𝓞 R'). complexConj is a ring hom, fixes intCast.
    rw [show (algebraMap ℤ (𝓞 R')) r = (r : 𝓞 R') from rfl]
    exact map_intCast (NumberField.IsCMField.ringOfIntegersComplexConj R').toRingEquiv r
  have h_int_fix_K : ∀ (r : ℤ),
      (NumberField.IsCMField.ringOfIntegersComplexConj K) ((algebraMap ℤ (𝓞 K)) r) =
        (algebraMap ℤ (𝓞 K)) r := by
    intro r
    rw [show (algebraMap ℤ (𝓞 K)) r = (r : 𝓞 K) from rfl]
    exact map_intCast (NumberField.IsCMField.ringOfIntegersComplexConj K).toRingEquiv r
  induction hx_in using Algebra.adjoin_induction with
  | mem y hy =>
    simp only [Set.mem_singleton_iff] at hy
    subst hy
    have h_K_conj : (NumberField.IsCMField.ringOfIntegersComplexConj K hζ.toInteger : 𝓞 K) =
        (hζ.toInteger : 𝓞 K) ^ (p - 1) :=
      ringOfIntegersComplexConj_primitiveRoot hp_pos hζ.toInteger_isPrimitiveRoot
    have h_R'_prim : IsPrimitiveRoot (algebraMap (𝓞 K) (𝓞 R') hζ.toInteger) p :=
      hζ.toInteger_isPrimitiveRoot.map_of_injective
        (FaithfulSMul.algebraMap_injective (𝓞 K) (𝓞 R'))
    have h_R'_conj : (NumberField.IsCMField.ringOfIntegersComplexConj R'
          (algebraMap (𝓞 K) (𝓞 R') hζ.toInteger) : 𝓞 R') =
        (algebraMap (𝓞 K) (𝓞 R') hζ.toInteger : 𝓞 R') ^ (p - 1) :=
      ringOfIntegersComplexConj_primitiveRoot hp_pos h_R'_prim
    apply NumberField.RingOfIntegers.ext
    rw [h_R'_conj]
    have h_RHS_subtype : (algebraMap (𝓞 K) (𝓞 R')
        (NumberField.IsCMField.ringOfIntegersComplexConj K hζ.toInteger) : 𝓞 R') =
        (algebraMap (𝓞 K) (𝓞 R') hζ.toInteger : 𝓞 R') ^ (p - 1) := by
      rw [← map_pow]
      exact congrArg _ h_K_conj
    exact congrArg ((↑·) : 𝓞 R' → R') h_RHS_subtype.symm
  | algebraMap r =>
    have h_tower :
        (algebraMap (𝓞 K) (𝓞 R')) ((algebraMap ℤ (𝓞 K)) r) =
          (algebraMap ℤ (𝓞 R')) r := by
      rw [← IsScalarTower.algebraMap_apply ℤ (𝓞 K) (𝓞 R')]
    rw [h_tower, h_int_fix r, h_int_fix_K r, h_tower]
  | add x y _ _ hpx hpy =>
    rw [map_add, map_add, hpx, hpy]
    rw [← map_add (algebraMap (𝓞 K) (𝓞 R')), ← map_add]
  | mul x y _ _ hpx hpy =>
    rw [map_mul, map_mul, hpx, hpy]
    rw [← map_mul (algebraMap (𝓞 K) (𝓞 R')), ← map_mul]

/-- **Upstairs complex conjugation lifts downstairs**: for cyclotomic
extensions with `K = ℚ(ζ_p)` (`p > 2`) and `R' = ℚ(ζ_p, ζ_ℓ)` for
distinct primes `p, ℓ`, the complex conjugation on `R'` restricts to
the complex conjugation on `K` via the algebra map.

This discharges the `h_upstairs_lifts_conj` hypothesis required by
`PhiPrimeElement.K2_2SourceData_phi_conj_mul_self_eq_absNorm_pow_of_upstairsComplexConj`
in our split-prime setting. -/
theorem upstairsComplexConj_lifts_downstairs
    {p ℓ : ℕ} [hp : Fact p.Prime] [Fact ℓ.Prime] (hpℓ : p ≠ ℓ) (hp_gt_two : 2 < p)
    {K : Type v} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
    {R' : Type w} [Field R'] [NumberField R'] [Algebra K R']
    [IsScalarTower ℚ K R'] [IsCyclotomicExtension {p, ℓ} ℚ R']
    [IsScalarTower ℤ (𝓞 K) (𝓞 R')]
    (x : 𝓞 K) :
    haveI : NumberField.IsCMField K :=
      IsCyclotomicExtension.Rat.isCMField (S := {p}) K ⟨p, rfl, hp_gt_two⟩
    haveI : NumberField.IsCMField R' :=
      isCMField_of_cyclotomicExtension_pair_primes (p := p) (ℓ := ℓ) hpℓ
    NumberField.IsCMField.ringOfIntegersComplexConj R'
        (algebraMap (𝓞 K) (𝓞 R') x) =
      algebraMap (𝓞 K) (𝓞 R')
        (NumberField.IsCMField.ringOfIntegersComplexConj K x) := by
  haveI : NumberField.IsCMField R' :=
    isCMField_of_cyclotomicExtension_pair_primes (p := p) (ℓ := ℓ) hpℓ
  haveI : FaithfulSMul (𝓞 K) (𝓞 R') :=
    FaithfulSMul.of_field_isFractionRing (𝓞 K) (𝓞 R') K R'
  exact
    upstairsComplexConj_lifts_downstairs_of_isCMField
      (p := p) hp_gt_two (K := K) (R' := R') x

/-- For `Q` with `(ℓ : R) ∈ Q` and `Q` non-zero, the prime under `Q` in
`ℤ` has absolute norm `ℓ`. -/
theorem absNorm_under_eq_of_ell_mem
    {ℓ : ℕ} [Fact ℓ.Prime] {R : Type*} [CommRing R] [IsDomain R]
    [IsDedekindDomain R] [Module.Free ℤ R] [Algebra.IsIntegral ℤ R]
    {Q : Ideal R} [Q.IsPrime] (hQ_ne : Q ≠ ⊥) (hℓ : (ℓ : R) ∈ Q) :
    Ideal.absNorm (Q.under ℤ) = ℓ := by
  haveI : NeZero Q := ⟨hQ_ne⟩
  have h_prime := Nat.absNorm_under_prime Q
  have h_dvd : Ideal.absNorm (Q.under ℤ) ∣ ℓ := by
    have h := (Int.cast_mem_ideal_iff (R := R) (I := Q) (d := (ℓ : ℤ))).mp
    have : (Ideal.absNorm (Q.under ℤ) : ℤ) ∣ (ℓ : ℤ) := by
      have hcast : ((ℓ : ℤ) : R) = (ℓ : R) := by push_cast; rfl
      rw [hcast] at h
      exact h hℓ
    exact_mod_cast this
  have hℓ_prime : Nat.Prime ℓ := Fact.out
  exact (Nat.prime_dvd_prime_iff_eq h_prime hℓ_prime).mp h_dvd

/-- Cyclotomic identity (sketch): for a primitive `ℓ`-th root of unity
`ζ` in a domain, `(↑ℓ : R)` is associated to `(ζ - 1)^(ℓ - 1)`.

**Proof outline:**
1. `Polynomial.eval_one_cyclotomic_prime` gives `Φ_ℓ(1) = ℓ` in `R`.
2. `Polynomial.cyclotomic_eq_prod_X_sub_primitiveRoots hζ` factors
   `Φ_ℓ = ∏_{μ ∈ primitiveRoots ℓ R} (X - C μ)`.
3. Evaluating at 1: `↑ℓ = ∏_{μ ∈ primitiveRoots ℓ R} (1 - μ)`.
4. For `ℓ` prime, every primitive `ℓ`-th root has the form `ζ^j` for
   some `1 ≤ j < ℓ` with `gcd(j, ℓ) = 1`.
5. `IsPrimitiveRoot.associated_sub_one_pow_sub_one_of_coprime` gives
   `(ζ^j - 1) ~ (ζ - 1)`, hence `(1 - ζ^j) ~ (1 - ζ)` (associated up
   to a sign unit).
6. Product: `↑ℓ ~ (1 - ζ)^(ℓ-1) ~ ((-1)^(ℓ-1)) (ζ - 1)^(ℓ-1)`,
   so `↑ℓ ~ (ζ - 1)^(ℓ-1)`. -/
theorem associated_ell_zeta_sub_one_pow
    {ℓ : ℕ} [Fact ℓ.Prime]
    {R : Type*} [CommRing R] [IsDomain R]
    {ζ : R} (hζ : IsPrimitiveRoot ζ ℓ) :
    Associated (ℓ : R) ((ζ - 1) ^ (ℓ - 1)) := by
  classical
  have hℓ_prime : Nat.Prime ℓ := Fact.out
  have hℓ_pos : 0 < ℓ := hℓ_prime.pos
  have h_eval :
      (ℓ : R) = ∏ μ ∈ primitiveRoots ℓ R, (1 - μ) := by
    have h := (Polynomial.eval_one_cyclotomic_prime (R := R) (p := ℓ)).symm
    rw [Polynomial.cyclotomic_eq_prod_X_sub_primitiveRoots hζ, Polynomial.eval_prod] at h
    simpa using h
  have h_prod :
      Associated (∏ μ ∈ primitiveRoots ℓ R, (1 - μ))
        (∏ μ ∈ primitiveRoots ℓ R, (ζ - 1)) := by
    refine Associated.prod (primitiveRoots ℓ R) (fun μ => 1 - μ) (fun _ => ζ - 1) ?_
    intro μ hμ
    have hμ_prim : IsPrimitiveRoot μ ℓ := (mem_primitiveRoots hℓ_pos).1 hμ
    obtain ⟨i, _hi_lt, hi_coprime, hζi⟩ := (hζ.isPrimitiveRoot_iff).1 hμ_prim
    have hassoc : Associated (ζ - 1) (μ - 1) := by
      rw [← hζi]
      exact hζ.associated_sub_one_pow_sub_one_of_coprime hi_coprime
    simpa [sub_eq_add_neg, add_comm] using hassoc.symm.neg_left
  have h_card : (primitiveRoots ℓ R).card = ℓ - 1 := by
    rw [hζ.card_primitiveRoots, Nat.totient_prime hℓ_prime]
  have h_prod_pow :
      Associated (∏ μ ∈ primitiveRoots ℓ R, (1 - μ)) ((ζ - 1) ^ (ℓ - 1)) := by
    simpa [Finset.prod_const, h_card] using h_prod
  simpa [h_eval] using h_prod_pow

/-- Membership in an ideal is invariant under replacing an element by an
associate. -/
theorem associated_mem_ideal_iff
    {R : Type*} [CommRing R] {a b : R} (h : Associated a b)
    {I : Ideal R} :
    a ∈ I ↔ b ∈ I := by
  obtain ⟨u, rfl⟩ := h
  constructor
  · intro ha
    exact Ideal.mul_mem_right (u : R) I ha
  · intro hb
    have hmem : (a * (u : R)) * ↑u⁻¹ ∈ I :=
      Ideal.mul_mem_right (↑u⁻¹ : R) I hb
    simpa [mul_assoc] using hmem

/-- For `Q` with `(ℓ : R) ∈ Q` and `Q` non-zero prime, `Q` lies over the
prime ideal `Ideal.span {↑ℓ}` of `ℤ`. -/
theorem liesOver_span_ell_of_ell_mem
    {ℓ : ℕ} [Fact ℓ.Prime] {R : Type*} [CommRing R] [IsDomain R]
    [IsDedekindDomain R] [Module.Free ℤ R] [Algebra.IsIntegral ℤ R]
    (Q : Ideal R) [Q.IsPrime] (hQ_ne : Q ≠ ⊥) (hℓ : (ℓ : R) ∈ Q) :
    Q.LiesOver (Ideal.span ({(ℓ : ℤ)} : Set ℤ)) := by
  have h_inst : Q.LiesOver (Ideal.span ({(Ideal.absNorm (Q.under ℤ) : ℤ)} : Set ℤ)) :=
    Int.liesOver_span_absNorm Q
  have h_eq : Ideal.absNorm (Q.under ℤ) = ℓ :=
    absNorm_under_eq_of_ell_mem hQ_ne hℓ
  rw [show ({(ℓ : ℤ)} : Set ℤ) = ({(Ideal.absNorm (Q.under ℤ) : ℤ)} : Set ℤ) by
    rw [h_eq]]
  exact h_inst

/-- **Main derivation (REF-18c2c4-L2c3a-prove):** for any prime `Q` of
`𝓞 R'` above `ℓ`, the element `ζ_ℓ - 1` is a uniformizer at `Q`, i.e.,
`(ζ_ℓ - 1) ∉ Q^2`.

Strategy:
1. Convert `IsCyclotomicExtension {p, ℓ} ℚ R'` to
   `IsCyclotomicExtension {p · ℓ} ℚ R'` (via
   `isCyclotomicExtension_singleton_mul_of_pair`).
2. Establish `Q.LiesOver (Ideal.span {↑ℓ})` (via
   `liesOver_span_ell_of_ell_mem`).
3. Apply `IsCyclotomicExtension.Rat.ramificationIdx_eq` with
   `n = ℓ · p`, prime `ℓ`, `k = 0`, `m = p` to get
   `ramificationIdx of ℓ in 𝓞 R' = ℓ - 1`.
4. Use the cyclotomic identity: from `Polynomial.eval_one_cyclotomic_prime`
   plus `Polynomial.cyclotomic_eq_prod_X_sub_primitiveRoots`,
   `(↑ℓ : 𝓞 R') = ∏_{i=1}^{ℓ-1} (1 - ζ^i) = u · (ζ - 1)^{ℓ-1}` for some
   unit `u` (using
   `IsPrimitiveRoot.associated_sub_one_pow_sub_one_of_coprime`).
5. Combine: if `(ζ - 1) ∈ Q^2`, then `(↑ℓ) = u · (ζ - 1)^{ℓ-1} ∈ Q^{2(ℓ-1)} ⊆ Q^ℓ`,
   contradicting `ramificationIdx = ℓ - 1` (which gives `(↑ℓ) ∉ Q^ℓ`). -/
theorem pi_not_mem_Q_sq_of_ramification
    {ℓ p : ℕ} [hℓ_fact : Fact ℓ.Prime] [hp_fact : Fact p.Prime] (hpℓ : p ≠ ℓ)
    {R' : Type w} [Field R'] [NumberField R']
    [IsCyclotomicExtension {p, ℓ} ℚ R']
    (zeta_ell_int : 𝓞 R')
    (hzeta_int : IsPrimitiveRoot zeta_ell_int ℓ)
    (Q : Ideal (𝓞 R')) [Q.IsPrime] (hQ_ne : Q ≠ ⊥)
    (hQ : (ℓ : 𝓞 R') ∈ Q) :
    zeta_ell_int - 1 ∉ Q ^ 2 := by
  -- Step 1: derive {ℓ · p}-cyclotomic structure on R'.
  haveI : IsCyclotomicExtension {ℓ * p} ℚ R' := by
    have h_swap : ({ℓ, p} : Set ℕ) = {p, ℓ} := by
      ext x; constructor <;> rintro (rfl | rfl) <;> simp
    have : IsCyclotomicExtension {p * ℓ} ℚ R' :=
      isCyclotomicExtension_singleton_mul_of_pair hpℓ
    rw [show ({ℓ * p} : Set ℕ) = ({p * ℓ} : Set ℕ) by rw [Nat.mul_comm]]
    exact this
  -- Step 2: establish LiesOver.
  haveI hQ_lies : Q.LiesOver (Ideal.span ({(ℓ : ℤ)} : Set ℤ)) :=
    liesOver_span_ell_of_ell_mem Q hQ_ne hQ
  haveI : NeZero (p : ℕ) := ⟨(Fact.out : Nat.Prime p).ne_zero⟩
  -- Step 3: apply ramificationIdx_eq with n = ℓ * p, prime ℓ, k = 0, m = p.
  have h_ne_dvd : ¬ ℓ ∣ p := fun hdvd => by
    have : ℓ = p :=
      (Nat.prime_dvd_prime_iff_eq (Fact.out : Nat.Prime ℓ)
        (Fact.out : Nat.Prime p)).mp hdvd
    exact hpℓ this.symm
  have h_n : (ℓ * p : ℕ) = ℓ ^ (0 + 1) * p := by simp [pow_one]
  have h_ram :
      Ideal.ramificationIdx (Ideal.span ({(ℓ : ℤ)} : Set ℤ)) Q = ℓ ^ 0 * (ℓ - 1) :=
    IsCyclotomicExtension.Rat.ramificationIdx_eq (n := ℓ * p) (p := ℓ)
      (k := 0) (m := p) (K := R') (P := Q) h_n h_ne_dvd
  simp only [pow_zero, one_mul] at h_ram
  -- Step 4: cyclotomic identity ↑ℓ ~ (ζ - 1)^(ℓ-1).
  obtain ⟨u, hu⟩ := (associated_ell_zeta_sub_one_pow hzeta_int).symm
  -- hu : (zeta_ell_int - 1)^(ℓ-1) * ↑u = ↑ℓ
  -- Step 5: contradiction. Suppose (ζ - 1) ∈ Q^2. Then (ζ - 1)^(ℓ-1) ∈ Q^(2(ℓ-1)).
  -- Hence (↑ℓ) = (ζ - 1)^(ℓ-1) · u ∈ Q^(2(ℓ-1)) ⊆ Q^ℓ.
  -- But ramificationIdx = ℓ - 1 means (↑ℓ) ∉ Q^ℓ. Contradiction.
  classical
  intro h_in_Q_sq
  have h_pi_pow : (zeta_ell_int - 1) ^ (ℓ - 1) ∈ (Q ^ 2) ^ (ℓ - 1) :=
    Ideal.pow_mem_pow h_in_Q_sq (ℓ - 1)
  rw [← pow_mul] at h_pi_pow
  have h_ell_in : (ℓ : 𝓞 R') ∈ Q ^ (2 * (ℓ - 1)) := by
    rw [← hu]
    exact Ideal.mul_mem_right _ _ h_pi_pow
  have hℓ_ge_two : 2 ≤ ℓ := (Fact.out : Nat.Prime ℓ).two_le
  have h_le : ℓ ≤ 2 * (ℓ - 1) := by omega
  have h_ell_in_Q_ell : (ℓ : 𝓞 R') ∈ Q ^ ℓ :=
    Ideal.pow_le_pow_right h_le h_ell_in
  -- Now use ramification = ℓ - 1 + count_normalizedFactors to derive a contradiction.
  -- ramificationIdx (span {↑ℓ}) Q = count Q (factors (span {(↑ℓ : 𝓞 R')})) = ℓ - 1.
  -- But (↑ℓ) ∈ Q^ℓ means span {↑ℓ} ⊆ Q^ℓ, so by Ideal.count_le_of_ideal_ge
  -- count Q (factors Q^ℓ) ≤ count Q (factors (span {↑ℓ})), i.e., ℓ ≤ ℓ - 1. Contradiction.
  have h_map_ne_bot :
      Ideal.map (algebraMap ℤ (𝓞 R')) (Ideal.span ({(ℓ : ℤ)} : Set ℤ)) ≠ ⊥ := by
    rw [Ideal.map_span]
    simp only [Set.image_singleton, eq_intCast]
    rw [Ne, Ideal.span_singleton_eq_bot]
    exact_mod_cast (Fact.out : Nat.Prime ℓ).ne_zero
  have h_ram_count :
      Ideal.ramificationIdx (Ideal.span ({(ℓ : ℤ)} : Set ℤ)) Q =
        Multiset.count Q (UniqueFactorizationMonoid.normalizedFactors
          (Ideal.map (algebraMap ℤ (𝓞 R')) (Ideal.span ({(ℓ : ℤ)} : Set ℤ)))) :=
    Ideal.IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count
      h_map_ne_bot (by infer_instance) hQ_ne
  rw [h_ram] at h_ram_count
  have h_map_eq :
      Ideal.map (algebraMap ℤ (𝓞 R')) (Ideal.span ({(ℓ : ℤ)} : Set ℤ)) =
        Ideal.span ({(ℓ : 𝓞 R')} : Set (𝓞 R')) := by
    rw [Ideal.map_span]; simp
  rw [h_map_eq] at h_ram_count
  have h_span_le : Ideal.span ({(ℓ : 𝓞 R')} : Set (𝓞 R')) ≤ Q ^ ℓ := by
    rw [Ideal.span_singleton_le_iff_mem]; exact h_ell_in_Q_ell
  have h_span_ne_bot : Ideal.span ({(ℓ : 𝓞 R')} : Set (𝓞 R')) ≠ ⊥ := by
    rw [Ne, Ideal.span_singleton_eq_bot]
    exact_mod_cast (Fact.out : Nat.Prime ℓ).ne_zero
  have hcount := Ideal.count_le_of_ideal_ge h_span_le h_span_ne_bot Q
  -- count Q (factors Q^ℓ) ≥ ℓ.
  have hQ_irr : Irreducible Q := (Ideal.prime_of_isPrime hQ_ne (by infer_instance)).irreducible
  have h_count_Qpow : ℓ ≤ Multiset.count Q
      (UniqueFactorizationMonoid.normalizedFactors (Q ^ ℓ)) := by
    rw [UniqueFactorizationMonoid.normalizedFactors_pow, Multiset.count_nsmul]
    have h1 : 1 ≤ Multiset.count Q
        (UniqueFactorizationMonoid.normalizedFactors Q) := by
      rw [UniqueFactorizationMonoid.normalizedFactors_irreducible hQ_irr,
        normalize_eq, Multiset.count_singleton_self]
    nlinarith
  rw [← h_ram_count] at hcount
  omega

namespace TraceFormStickelbergerSetup

variable {ℓ p : ℕ} [Fact (Nat.Prime ℓ)] [Fact (Nat.Prime p)]
variable {k : Type u} [Field k] [Fintype k] [Algebra (ZMod ℓ) k]
variable {K : Type v} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
variable {R' : Type w} [Field R'] [NumberField R'] [Algebra K R'] [IsScalarTower ℚ K R']
  [IsCyclotomicExtension {p, ℓ} ℚ R']

/-- The rational residue characteristic has `Q`-adic order at least `ℓ - 1`
in the mixed cyclotomic integer ring. This is the membership half of the
cyclotomic identity `ℓ ~ (ζ_ℓ - 1)^(ℓ-1)`. -/
theorem natCast_ell_mem_Q_pow_pred
    (S : TraceFormStickelbergerSetup ℓ p k K R') :
    (ℓ : 𝓞 R') ∈ S.Q ^ (ℓ - 1) := by
  have hassoc :
      Associated (ℓ : 𝓞 R') ((S.zeta_ell_int - 1) ^ (ℓ - 1)) :=
    associated_ell_zeta_sub_one_pow S.zeta_ell_int_isPrimitiveRoot
  have hzeta_mem : (S.zeta_ell_int - 1) ^ (ℓ - 1) ∈ S.Q ^ (ℓ - 1) := by
    have hζ_sub_mem : S.zeta_ell_int - 1 ∈ S.Q := by
      rw [← S.hπ]
      exact S.π_mem_Q
    exact Ideal.pow_mem_pow hζ_sub_mem (ℓ - 1)
  exact (associated_mem_ideal_iff hassoc).2 hzeta_mem

/-- Power form of `natCast_ell_mem_Q_pow_pred`. -/
theorem natCast_ell_pow_mem_Q_pow_mul_pred
    (S : TraceFormStickelbergerSetup ℓ p k K R') (m : ℕ) :
    (ℓ : 𝓞 R') ^ m ∈ S.Q ^ (m * (ℓ - 1)) := by
  have hpow : (ℓ : 𝓞 R') ^ m ∈ (S.Q ^ (ℓ - 1)) ^ m :=
    Ideal.pow_mem_pow S.natCast_ell_mem_Q_pow_pred m
  rw [← pow_mul] at hpow
  simpa [Nat.mul_comm] using hpow

/-- If a natural coefficient is divisible by `ℓ^m`, then its image in the
ring of integers lies in `Q^(m*(ℓ-1))`. This is the coefficient-valuation
bridge needed by the higher trace-binomial estimate. -/
theorem natCast_mem_Q_pow_mul_pred_of_ell_pow_dvd
    (S : TraceFormStickelbergerSetup ℓ p k K R') {c m : ℕ}
    (hc : ℓ ^ m ∣ c) :
    (c : 𝓞 R') ∈ S.Q ^ (m * (ℓ - 1)) := by
  rcases hc with ⟨t, rfl⟩
  have hpow := S.natCast_ell_pow_mem_Q_pow_mul_pred m
  have hmul : (ℓ : 𝓞 R') ^ m * (t : 𝓞 R') ∈ S.Q ^ (m * (ℓ - 1)) :=
    Ideal.mul_mem_right (t : 𝓞 R') (S.Q ^ (m * (ℓ - 1))) hpow
  simpa [Nat.cast_mul, Nat.cast_pow] using hmul

end TraceFormStickelbergerSetup

end Furtwaengler

end BernoulliRegular
