import HasseWeil.Curves.FiniteOverKx
import HasseWeil.Curves.CurveMap
import Mathlib.RingTheory.Algebraic.Integral
import Mathlib.RingTheory.Algebraic.Basic
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis

/-!
# Algebraicity of `F(C)` over `F[x]` for a smooth plane curve `C`

Every element of the function field `F(C)` of a smooth plane curve is
algebraic over the polynomial ring `F[X]` (acting on `F(C)` via the image
of the coordinate function `x`).

This is the foundational fact that Silverman II.2.4(a) uses to conclude
that a nonconstant curve map `φ : C₁ → C₂` induces a finite extension
`K(C₁) / φ*(K(C₂))`: the range of `φ.pullback` is an intermediate ring
containing the algebraic structure of `F[x]`, and transitivity does the rest.

This closes the *first piece* of the infrastructure needed for
T-II-INFRA-B-009 (Silverman II.2.4(a), `CurveMap.pullback_image_finite_codim`).
The full finiteness still requires transcendence-degree theory, which
mathlib provides via `IsTranscendenceBasis`/`trdeg` but whose bridge to our
subalgebra setting (`Algebra.adjoin F {C.coordX}`) needs additional
typeclass-plumbing. That bridge is tracked as a follow-up.

## Main results

- `SmoothPlaneCurve.isAlgebraic_polynomialX_functionField`: `F(C)` is
  algebraic over `F[X]` (instance). Consequence of
  `IsLocalization.isAlgebraic` + `Algebra.IsAlgebraic.of_finite` + transitivity.

## References

* [Silverman, *The Arithmetic of Elliptic Curves*], II.1, II.2.4
-/

namespace HasseWeil.Curves

namespace SmoothPlaneCurve

variable {F : Type*} [Field F] (C : SmoothPlaneCurve F)

/-- **`F(C)` is algebraic over `F[X]`**: every element of the function field
satisfies a polynomial with coefficients in `F[X]` (acting via `algebraMap`,
whose image is generated by `C.coordX`).

Proof: `F[X] → F(x) = FractionRing F[X]` is algebraic (localization is
algebraic over the base), `F(x) → F(C)` is algebraic (finite of rank 2), and
algebraicness is transitive. -/
instance isAlgebraic_polynomialX_functionField :
    Algebra.IsAlgebraic (Polynomial F) C.FunctionField := by
  haveI : Algebra.IsAlgebraic (Polynomial F) (FractionRing (Polynomial F)) :=
    IsLocalization.isAlgebraic _ (nonZeroDivisors _)
  haveI : Algebra.IsAlgebraic (FractionRing (Polynomial F)) C.FunctionField :=
    Algebra.IsAlgebraic.of_finite _ _
  exact Algebra.IsAlgebraic.trans (R := Polynomial F)
    (S := FractionRing (Polynomial F)) (A := C.FunctionField)

/-- Every element of `F(C)` is integral over `F[X]`: since `F[X]` is a field
(well, an integral domain), integrality and algebraicness coincide over it
only for the algebraic case when the ring is a field. Here, since `F[X]`
is an ID and `F(C)` is a domain, we can state integrality directly.

**Remark**: `F[X]` is NOT a field, so `IsAlgebraic` and `IsIntegral` over
`F[X]` are distinct notions in general; however, an element of `F(C)` that
is a root of any nonzero polynomial over `F[X]` is a root of SOME monic
polynomial (divide by the leading coefficient after clearing denominators
in the fraction field). We don't need this strengthening for the main
application. -/
instance isIntegral_fracPolynomialX_functionField :
    Algebra.IsIntegral (FractionRing (Polynomial F)) C.FunctionField := by
  haveI : Algebra.IsAlgebraic (FractionRing (Polynomial F)) C.FunctionField :=
    Algebra.IsAlgebraic.of_finite _ _
  exact Algebra.IsAlgebraic.isIntegral

/-! ### T-II-1-005: Uniformizer is not a `p`-th power in char `p > 0` -/

/-- **Silverman Exercise II.2.15 (⇐), char-`p` half**: if `t ∈ F(C)` is a
uniformizer at some smooth point `P`, then `t` is not a `p`-th power in
`F(C)` for any prime `p > 1`. This is half of Silverman II.1.4's separability
characterization of `F(C)/F(t)`.

Proof: `t = f^p` would give `ord_P(t) = p · ord_P(f)`, contradicting
`ord_P(t) = 1` whenever `p ≥ 2`. -/
theorem notMem_pthPowers_of_uniformizer {p : ℕ} (hp : 1 < p)
    {P : C.SmoothPoint} {t : C.FunctionField}
    (ht : Uniformizer C P t) (f : C.FunctionField) :
    t ≠ f ^ p := by
  intro hfp
  have ht_ne : t ≠ 0 := ht.ne_zero
  have hf_ne : f ≠ 0 := fun hf => ht_ne (by rw [hfp, hf, zero_pow (by omega)])
  have h_ord_t : C.ord_P P t = 1 := ht
  have h_ord_fp : C.ord_P P (f ^ p) = (p : ℕ) • C.ord_P P f :=
    C.ord_P_pow f p
  rw [hfp, h_ord_fp] at h_ord_t
  -- h_ord_t : p • ord_P f = 1 (in WithTop ℤ)
  have hord_f_ne_top : C.ord_P P f ≠ ⊤ := (C.ord_P_eq_top_iff f).not.mpr hf_ne
  obtain ⟨n, hn⟩ := WithTop.ne_top_iff_exists.mp hord_f_ne_top
  rw [← hn] at h_ord_t
  -- h_ord_t : p • ↑n = ↑1 in WithTop ℤ
  rw [← WithTop.coe_nsmul] at h_ord_t
  -- h_ord_t : ↑(p • n) = 1 in WithTop ℤ. Cast to ℤ.
  have h_int : (p : ℤ) * n = 1 := by
    have h_pn : p • n = (1 : ℤ) := by exact_mod_cast h_ord_t
    rw [Int.nsmul_eq_mul] at h_pn
    exact_mod_cast h_pn
  -- p ≥ 2 (from hp : 1 < p), n ∈ ℤ, p * n = 1 is impossible
  have hp_ge : (p : ℤ) ≥ 2 := by exact_mod_cast hp
  -- Split on sign of n
  rcases lt_trichotomy n 0 with hn_neg | hn_zero | hn_pos
  · -- n < 0: p * n ≤ p * (-1) = -p ≤ -2 ≠ 1
    nlinarith
  · -- n = 0: p * 0 = 0 ≠ 1
    rw [hn_zero, mul_zero] at h_int
    exact absurd h_int (by norm_num)
  · -- n > 0 so n ≥ 1: p * n ≥ p * 1 ≥ 2 ≠ 1
    nlinarith

/-! ### Transcendence degree of `F(C)` over `F`

`F(C)` is finite over `Frac(F[X]) = F(x)`, so trdeg = 1 by additivity of
transcendence degree across the tower `F → F[X] → F(x) → F(C)`. -/

/-- **trdeg F K(E) = 1 (axiom-clean)**: the function field of a smooth
plane curve has transcendence degree 1 over the base field.

Tower computation: `trdeg F (Polynomial F) = 1` (mathlib's
`Polynomial.trdeg_of_isDomain`), `trdeg (Polynomial F) (FractionRing
(Polynomial F)) = 0` (localization is algebraic over base), and
`trdeg (FractionRing (Polynomial F)) F(C) = 0` (`Module.Finite` from
`FiniteOverKx`). Apply `trdeg_add_eq` twice. -/
theorem functionField_trdeg_eq_one : Algebra.trdeg F C.FunctionField = 1 := by
  have h_fund : Algebra.trdeg F (FractionRing (Polynomial F)) = 1 := by
    have h_PF : Algebra.trdeg F (Polynomial F) = 1 := Polynomial.trdeg_of_isDomain
    haveI : Algebra.IsAlgebraic (Polynomial F) (FractionRing (Polynomial F)) :=
      IsLocalization.isAlgebraic _ (nonZeroDivisors _)
    have h_PF_to_F_X :
        Algebra.trdeg (Polynomial F) (FractionRing (Polynomial F)) = 0 := trdeg_eq_zero
    rw [← trdeg_add_eq F (Polynomial F) (A := FractionRing (Polynomial F))]
    rw [h_PF, h_PF_to_F_X, add_zero]
  haveI : Algebra.IsAlgebraic (FractionRing (Polynomial F)) C.FunctionField :=
    Algebra.IsAlgebraic.of_finite _ _
  have h_FX_to_KE : Algebra.trdeg (FractionRing (Polynomial F)) C.FunctionField = 0 :=
    trdeg_eq_zero
  rw [← trdeg_add_eq F (FractionRing (Polynomial F)) (A := C.FunctionField)]
  rw [h_fund, h_FX_to_KE, add_zero]

end SmoothPlaneCurve

end HasseWeil.Curves
