#!/usr/bin/env python3
"""
Extract Lean linear_combination multipliers for Φ_3 ∈ K[X³] proof in char 3.

Goal: ship `Φ_three_mem_expand_three_char_three` with explicit
linear_combination multipliers M_3 (for `(3 : K[X]) = 0`) and M_b (for
the char-3 b-relation `b₈ - (b₂·b₆ - b₄²) = 0`).

Setup:
* Witness g(X) = X³ + 2·b₂·b₄·X² + (2·b₂³·b₆ + b₂²·b₄² + b₂·b₄·b₆)·X +
                  (2·b₂·b₄·b₆² + b₄³·b₆ + b₆³)
* `expand 3 (g) = X⁹ + 2·b₂·b₄·X⁶ + (...) ·X³ + (constant)`.

We compute Φ_3 - expand 3 (g) over ℤ[X, b₂, b₄, b₆, b₈], then divide
by the ideal generated by `(3, b₈ - (b₂·b₆ - b₄²))` to extract the
two multipliers.
"""

from sympy import symbols, expand, Poly, div, simplify

X, b2, b4, b6, b8 = symbols('X b2 b4 b6 b8')

# Mathlib formulas (over ℤ, will reduce in linear_combination)
Psi_3 = 3*X**4 + b2*X**3 + 3*b4*X**2 + 3*b6*X + b8
PsiSq_3 = expand(Psi_3**2)
Psi_2_sq = 4*X**3 + b2*X**2 + 2*b4*X + b6
preP_4 = (2*X**6 + b2*X**5 + 5*b4*X**4 + 10*b6*X**3 + 10*b8*X**2
          + (b2*b8 - b4*b6)*X + (b4*b8 - b6**2))

Phi_3_full = expand(X * PsiSq_3 - preP_4 * Psi_2_sq)

# Witness g(X) = X³ + 2·b₂·b₄·X² + (2·b₂³·b₆ + b₂²·b₄² + b₂·b₄·b₆)·X +
#                (2·b₂·b₄·b₆² + b₄³·b₆ + b₆³)
g_coeff_X3 = 1
g_coeff_X2 = 2*b2*b4
g_coeff_X1 = 2*b2**3*b6 + b2**2*b4**2 + b2*b4*b6
g_coeff_X0 = 2*b2*b4*b6**2 + b4**3*b6 + b6**3
g_witness = (g_coeff_X3 * X**3 + g_coeff_X2 * X**2 +
             g_coeff_X1 * X + g_coeff_X0)

# expand 3 (g) substitutes X → X^3 in g
expand3_g = (g_coeff_X3 * X**9 + g_coeff_X2 * X**6 +
             g_coeff_X1 * X**3 + g_coeff_X0)

residual = expand(Phi_3_full - expand3_g)
print("=" * 70)
print("Residual = Φ_3 - expand 3 (g) over ℤ[X, b₂, b₄, b₆, b₈]")
print("=" * 70)
print(f"\n{residual}\n")

# We want: residual = M_3 * 3 + M_b * (b₈ - b₂·b₆ + b₄²)
# Strategy: substitute b₈ → b₂·b₆ - b₄² and what remains should be a multiple of 3.
residual_after_brel = expand(residual.subs(b8, b2*b6 - b4**2))
print("=" * 70)
print("Residual after substituting b₈ = b₂·b₆ - b₄²")
print("=" * 70)
print(f"\n{residual_after_brel}\n")

# This should be a multiple of 3.
residual_div_3 = expand(residual_after_brel / 3)
print(f"After dividing by 3:\n  {residual_div_3}\n")

# Verify: 3 * residual_div_3 = residual_after_brel
check = expand(3 * residual_div_3 - residual_after_brel)
print(f"Check (should be 0): {check}")

# Now we have:  residual = M_b * (b₈ - b₂·b₆ + b₄²) + 3 · M_3
# where M_3 = residual_div_3.
# To find M_b, compute (residual - 3 · M_3) / (b₈ - b₂·b₆ + b₄²).
# But we don't know M_3 directly — only after b-substitution.
# Strategy: residual_orig = residual itself. We know residual| b₈→b₂b₆-b₄² = 3·M_3.
# So residual - 3·M_3 = M_b · (b₈ - b₂·b₆ + b₄²).
# But M_3 has been computed AFTER b₈-substitution, so we need to find an M_3
# (possibly different) that works WITHOUT substitution. Actually, the cleanest
# linear_combination form treats both relations at once.

# Strategy 2: Use polynomial division.
# residual is a polynomial in (X, b₂, b₄, b₆, b₈). The element b₈ - b₂·b₆ + b₄²
# is linear in b₈. Divide by b₈ - b₂·b₆ + b₄² treating other vars as constants.

from sympy import Poly as P
# Treat b₈ as the "main" variable, rest as parameters
brel = b8 - (b2*b6 - b4**2)  # = b₈ - b₂·b₆ + b₄²
# Polynomial division: residual = q_b * brel + r_b where r_b has degree 0 in b₈.
# Since brel is monic in b₈, q_b is well-defined.
q_b, r_b = div(residual, brel, b8)
q_b = expand(q_b)
r_b = expand(r_b)
print("=" * 70)
print("Polynomial division of residual by (b₈ - b₂·b₆ + b₄²) in b₈")
print("=" * 70)
print(f"\nQuotient M_b (multiplier for b-relation):\n  {q_b}\n")
print(f"Remainder r_b (no b₈, must be a multiple of 3):\n  {r_b}\n")

# r_b should be 3 · M_3
r_b_div_3 = expand(r_b / 3)
print(f"M_3 = r_b / 3:\n  {r_b_div_3}\n")
check2 = expand(3 * r_b_div_3 - r_b)
print(f"Check (3·M_3 = r_b should be 0): {check2}")

# Final assembly: residual = M_b * (b₈ - b₂·b₆ + b₄²) + 3 · M_3
# In Lean: linear_combination (-M_b) * h_brel + (-M_3) * h_3
# Wait — sign. In Lean, h_3 : (3 : K[X]) = 0 means 3 · M_3 = 0 already. So
# residual = M_b · brel ↔ Φ_3 - expand 3 g = M_b · (b₈ - b₂·b₆ + b₄²).
# Lean: linear_combination M_b · h_brel + M_3 · h_3
# (depending on sign of brel hypothesis)

print("=" * 70)
print("Lean linear_combination form:")
print("=" * 70)
print(f"\n  Φ_3 = expand 3 (g) requires:")
print(f"    M_b * (b₈ - b₂·b₆ + b₄²) + 3 · M_3")
print(f"\n  M_b = {q_b}")
print(f"  M_3 = {r_b_div_3}")

# Sanity check: full reconstruction
recon = expand(q_b * brel + 3 * r_b_div_3)
print(f"\nReconstruction check (should equal residual): "
      f"{expand(recon - residual) == 0}")
