import BernoulliRegular.FLT37.PrimaryUnits
import Mathlib.NumberTheory.NumberField.CMField

/-!
# Cyclotomic-unit subgroup of `(𝓞 K)ˣ`

For `K = ℚ(ζ_p)` (`p` an odd prime), Sinnott's index formula relates the
"cyclotomic units" subgroup `C ⊆ (𝓞 K)ˣ` (Washington Definition 8.1)
to the class number `h(K)`: `[(𝓞 K)ˣ : C] = h(K)`.

This file defines:
* `cyclotomicUnitsSubgroup` — `C ⊆ (𝓞 K)ˣ`, the subgroup generated by
  the cyclotomic units `(1-ζ^k)/(1-ζ)` (`k` coprime to `p`) and the
  torsion subgroup (= roots of unity in `𝓞 K`).
* `cyclotomicUnitsPlus` — `C⁺ = C ∩ realUnits K`, the real cyclotomic
  units subgroup.

This is **Step (A)** of the Sinnott / Cor 8.19 bridge construction.
The generating elements `cyclotomicUnitUnit p K k` are already defined
in `BernoulliRegular/FLT37/PrimaryUnits.lean`.

## References

* Washington, *Introduction to Cyclotomic Fields*, 2nd ed., §8.1.
* Sinnott, *On the Stickelberger ideal and the circular units of a
  cyclotomic field*, Annals of Math. 108 (1978).
-/

@[expose] public section

noncomputable section

open NumberField NumberField.IsCMField

namespace BernoulliRegular

namespace FLT37

namespace Sinnott

variable (p : ℕ) [hp : Fact p.Prime]
variable (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- The set of cyclotomic units in `(𝓞 K)ˣ`: the units
`cyclotomicUnitUnit p K k = (1 - ζ^k)/(1 - ζ)` for `1 ≤ k < p` (with
`k.Coprime p` automatic for `1 ≤ k < p` and `p` prime).

The bound `k < p` avoids redundancy: `cyclotomicUnit k = cyclotomicUnit
(k mod p)` as elements of `𝓞 K` since `ζ^p = 1`. -/
def cyclotomicUnitsSet (hp_two : 2 ≤ p) : Set (𝓞 K)ˣ :=
  {u : (𝓞 K)ˣ | ∃ (k : ℕ) (hk : k.Coprime p) (_ : 1 ≤ k) (_ : k < p),
    u = cyclotomicUnitUnit p K k hk hp_two}

/-- **The cyclotomic-units subgroup `C ⊆ (𝓞 K)ˣ`** (Washington Def 8.1):
the subgroup generated by the cyclotomic units `(1-ζ^k)/(1-ζ)` for
`k.Coprime p`, together with the torsion subgroup (roots of unity).

For `K = ℚ(ζ_p)` with `p` odd, the torsion subgroup is generated by
`-1` and `ζ`, both of which are products of cyclotomic units up to
sign. Including torsion explicitly makes the index formula
`[(𝓞 K)ˣ : C] = h(K)` (Sinnott / Washington Thm 8.2) state cleanly. -/
def cyclotomicUnitsSubgroup (hp_two : 2 ≤ p) : Subgroup (𝓞 K)ˣ :=
  Subgroup.closure (cyclotomicUnitsSet p K hp_two) ⊔ NumberField.Units.torsion K

/-- **The real cyclotomic-units subgroup `C⁺ ⊆ (𝓞 K)ˣ`**:
the σ-fixed (= real) elements of `cyclotomicUnitsSubgroup`. By
`unitsComplexConj_eq_self_iff`, an element of `(𝓞 K)ˣ` is σ-fixed iff
it lies in `realUnits K = image of (𝓞 K⁺)ˣ`.

The Sinnott-style real index formula (Washington Thm 8.2) is
`[realUnits K : C⁺] = h⁺(K)`. -/
def cyclotomicUnitsPlus [IsCMField K] (hp_two : 2 ≤ p) : Subgroup (𝓞 K)ˣ :=
  cyclotomicUnitsSubgroup p K hp_two ⊓ realUnits K

/-- Membership in `cyclotomicUnitsSubgroup`: a cyclotomic unit
`cyclotomicUnitUnit p K k` is in `C` for `1 ≤ k < p` and `k.Coprime p`. -/
theorem cyclotomicUnitUnit_mem_cyclotomicUnitsSubgroup
    {k : ℕ} (hk : k.Coprime p) (hk_pos : 1 ≤ k) (hk_lt : k < p) (hp_two : 2 ≤ p) :
    cyclotomicUnitUnit p K k hk hp_two ∈ cyclotomicUnitsSubgroup p K hp_two :=
  Subgroup.mem_sup_left <| Subgroup.subset_closure ⟨k, hk, hk_pos, hk_lt, rfl⟩

/-- Membership: torsion units are in `C`. -/
theorem torsion_le_cyclotomicUnitsSubgroup (hp_two : 2 ≤ p) :
    NumberField.Units.torsion K ≤ cyclotomicUnitsSubgroup p K hp_two :=
  le_sup_right

end Sinnott

end FLT37

end BernoulliRegular

end
