module

public import Mathlib.RingTheory.ClassGroup
public import BernoulliRegular.Stickelberger.Integrality
public import BernoulliRegular.GaussSum.PrimeFactorization.JacobiSums.ClosedForm

/-!
# Stickelberger ideal actions

This file bridges the `T027` Gauss-sum prime factorisation package to the
ideal-action language used by the Stickelberger annihilation step.

The action here is the character-side group-ring action on the distinguished
prime above `p`: a group-ring coefficient at `b⁻¹` contributes the corresponding
power of `σ_b(P₀)`. The final theorem rewrites the `T027` group-ring
factorisation as an equality with the principal ideal generated by the lifted
Gauss sum.
-/

@[expose] public section

noncomputable section

open NumberField IsCyclotomicExtension
open scoped NumberField Pointwise nonZeroDivisors

namespace BernoulliRegular

section CharacterSideAction

variable (p : ℕ) [hp : Fact p.Prime]
  (L : Type*) [Field L] [NumberField L] [IsCyclotomicExtension {p * (p - 1)} ℚ L]

local instance : NeZero (p - 1) := ⟨Nat.sub_ne_zero_of_lt hp.out.one_lt⟩

/-- The character-side ideal action attached to an integer group-ring exponent.

The coefficient at `b⁻¹` acts on the translate `σ_b(P₀)` of the distinguished
prime above `p`. Coefficients are read using `Int.toNat`, matching the
nonnegative exponent convention already used by the `T027` factorisation API. -/
noncomputable def characterSideStickelbergerIdealAction
    (E : MonoidAlgebra ℤ (ZMod (p - 1))ˣ) : Ideal (𝓞 L) :=
  ∏ b : (ZMod (p - 1))ˣ,
    (sigmaOfCharacterUnit (p := p) L b • distinguishedPrimeAboveP p L) ^ (E b⁻¹).toNat

/-- The ideal-action definition is definitionally the group-ring-to-ideal
factorisation package from `T027`, after unfolding the character-side orbit
map. -/
@[simp] lemma characterSideStickelbergerIdealAction_eq_factorizationFromGroupRing
    (E : MonoidAlgebra ℤ (ZMod (p - 1))ˣ) :
    characterSideStickelbergerIdealAction (p := p) (L := L) E =
      characterSideIdealFactorizationFromGroupRing (p := p) (L := L) E := by
  simp [characterSideStickelbergerIdealAction,
    characterSideIdealFactorizationFromGroupRing, characterSidePrimeMap]

/-- `T032b1`: the closed-form `T027` group-ring factorisation, reinterpreted as
the character-side Stickelberger ideal action on the distinguished prime. -/
theorem gaussSumIdeal_eq_characterSideStickelbergerIdealAction
    (hp_odd : p ≠ 2) {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) :
    gaussSumIdeal (p := p) (L := L) χ =
      characterSideStickelbergerIdealAction (p := p) (L := L)
        (stickelbergerCharacterCoefficientGroupRingTarget (p := p) (L := L) χ) := by
  rw [characterSideStickelbergerIdealAction_eq_factorizationFromGroupRing]
  exact
    (gaussSumIdeal_stickelbergerCharacterGroupRingFactorizationTarget_of_normalizedBoundary
      (p := p) (L := L) hp_odd) χ hχ

/-- Equivalent principal-ideal form of `gaussSumIdeal_eq_characterSideStickelbergerIdealAction`.

This is the statement consumed by the next class-group step: the ideal action
coming from the Stickelberger group-ring exponent is represented by the
principal ideal generated by the integral lifted Gauss sum. -/
theorem characterSideStickelbergerIdealAction_eq_gaussSum_principal
    (hp_odd : p ≠ 2) {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) :
    characterSideStickelbergerIdealAction (p := p) (L := L)
        (stickelbergerCharacterCoefficientGroupRingTarget (p := p) (L := L) χ) =
      Ideal.span ({gaussSumIntegers p L χ} : Set (𝓞 L)) := by
  simpa [gaussSumIdeal] using
    (gaussSumIdeal_eq_characterSideStickelbergerIdealAction
      (p := p) (L := L) hp_odd hχ).symm

/-- The character-side Stickelberger action ideal attached to a nontrivial
character is nonzero, so it determines a class in the ideal class group. -/
lemma characterSideStickelbergerIdealAction_ne_bot
    (hp_odd : p ≠ 2) {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) :
    characterSideStickelbergerIdealAction (p := p) (L := L)
        (stickelbergerCharacterCoefficientGroupRingTarget (p := p) (L := L) χ) ≠ ⊥ := by
  rw [characterSideStickelbergerIdealAction_eq_gaussSum_principal
    (p := p) (L := L) hp_odd hχ]
  exact Ideal.span_singleton_eq_bot.not.mpr
    (gaussSumIntegers_ne_zero (p := p) (L := L) hχ)

/-- The nonzero ideal underlying the character-side Stickelberger action. -/
noncomputable def characterSideStickelbergerIdealActionClassIdeal
    (hp_odd : p ≠ 2) (χ : DirichletCharacter ℂ p) (hχ : χ ≠ 1) :
    (Ideal (𝓞 L))⁰ :=
  ⟨characterSideStickelbergerIdealAction (p := p) (L := L)
      (stickelbergerCharacterCoefficientGroupRingTarget (p := p) (L := L) χ),
    mem_nonZeroDivisors_iff_ne_zero.mpr
      (characterSideStickelbergerIdealAction_ne_bot (p := p) (L := L) hp_odd hχ)⟩

/-- The character-side Stickelberger action ideal is principal. -/
theorem characterSideStickelbergerIdealAction_isPrincipal
    (hp_odd : p ≠ 2) {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) :
    (characterSideStickelbergerIdealAction (p := p) (L := L)
        (stickelbergerCharacterCoefficientGroupRingTarget (p := p) (L := L) χ)).IsPrincipal := by
  rw [characterSideStickelbergerIdealAction_eq_gaussSum_principal
    (p := p) (L := L) hp_odd hχ]
  infer_instance

/-- `T032b2`: the class of the character-side Stickelberger action ideal is
trivial in the ideal class group. -/
theorem classGroup_mk0_characterSideStickelbergerIdealAction_eq_one
    (hp_odd : p ≠ 2) {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) :
    ClassGroup.mk0
        (characterSideStickelbergerIdealActionClassIdeal
          (p := p) (L := L) hp_odd χ hχ) =
      (1 : ClassGroup (𝓞 L)) := by
  rw [ClassGroup.mk0_eq_one_iff
    (characterSideStickelbergerIdealActionClassIdeal
      (p := p) (L := L) hp_odd χ hχ).2]
  exact characterSideStickelbergerIdealAction_isPrincipal
    (p := p) (L := L) hp_odd hχ

end CharacterSideAction

end BernoulliRegular

end
