/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import ModularCurves.Moduli.UniversalLevelThree
import ModularCurves.Moduli.Bootstrap
import ModularCurves.WeilPairing.UniversalRootThree

/-!
# The `GL₂(ℤ/3)`-action on the level-three moduli object (WP-D3c-N3)

The last input of the DS4 construction (`nonempty_weilPairing_of_root_of_det`,
`WeilPairing/DetCocycle.lean`) is that the chosen root of unity transforms by `det` under a
change of trivialisation. At level three the root is the *explicit* element `e3Zeta`
(`WeilPairing/UniversalRootThree.lean`), so the statement becomes a concrete identity in
`E3ModuliRing R` — but it needs the `GL₂(ℤ/3)`-action on that ring, which is what this file
supplies.

Nothing new is constructed: `gammaFullNaiveGlAut` (`Moduli/Bootstrap.lean`) already gives
`GL₂(ℤ/N)` acting on the naive full-level *moduli problem*, and `universalE3Obj` represents
that problem at `N = 3`. Transporting an automorphism of a representable functor to its
representing object is `Functor.RepresentableBy.ofIso` followed by
`Functor.RepresentableBy.uniqueUpToIso`.
-/

universe u

open CategoryTheory AlgebraicGeometry

namespace ModularCurves

/-- **(WP-D3c-N3 step 2γ)** A homomorphism into a group of exponent two kills every element of
order dividing three: `φ x = φ x ^ 3 = 1`.

This is the engine of "any homomorphism `GL₂(𝔽₃) → ℤ/2` factors through `det`": `SL₂(𝔽₃)` is
generated by the two elementary matrices, both of order three, so any such homomorphism is
trivial on `SL₂(𝔽₃)` and therefore factors through `GL₂/SL₂ ≅ (ℤ/3)ˣ`. -/
theorem map_eq_one_of_pow_three_eq_one {G H : Type*} [Group G] [Group H] (φ : G →* H)
    (hH : ∀ h : H, h ^ 2 = 1) {x : G} (hx : x ^ 3 = 1) : φ x = 1 := by
  have h3 : φ x ^ 3 = 1 := by rw [← map_pow, hx, map_one]
  rwa [pow_succ, hH, one_mul] at h3

/-- **(WP-D3c-N3 step 2β)** Two primitive cube roots of unity in a commutative ring differ by
the factorisation `x² + x + 1 = (x − z)(x − z²)`: the product of the two differences vanishes.

Over a domain this forces `w = z` or `w = z²`, which is the binary determination the
determinant law reduces to. Stated without a domain hypothesis because `E3ModuliRing R` is one
only for suitable `R`; the product form is what a general `R` supports. -/
theorem sub_mul_sub_sq_eq_zero_of_cyclotomic {A : Type*} [CommRing A] {z w : A}
    (hz : z ^ 2 + z + 1 = 0) (hw : w ^ 2 + w + 1 = 0) :
    (w - z) * (w - z ^ 2) = 0 := by
  linear_combination hw + (-w + z - 1) * hz

/-- **(WP-D3c-N3 step 2β)** …and over a domain the determination is binary. -/
theorem eq_or_eq_sq_of_cyclotomic {A : Type*} [CommRing A] [IsDomain A] {z w : A}
    (hz : z ^ 2 + z + 1 = 0) (hw : w ^ 2 + w + 1 = 0) :
    w = z ∨ w = z ^ 2 := by
  rcases mul_eq_zero.mp (sub_mul_sub_sq_eq_zero_of_cyclotomic hz hw) with h | h
  · exact Or.inl (sub_eq_zero.mp h)
  · exact Or.inr (sub_eq_zero.mp h)

variable (R : CommRingCat.{u})

/-- **(WP-D3c-N3)** The automorphism of the level-three moduli object induced by
`g ∈ GL₂(ℤ/3)`, obtained by transporting `gammaFullNaiveGlAut` through the representing
equivalence. -/
noncomputable def e3GlIso (hR : IsUnit (3 : R))
    (hL : (universalE3Obj R).curve.IsNaiveFullLevel 3
      (universalE3P R) (universalE3Q R))
    (hArb : ∀ (X : EllObj R) (L : X.curve.FullLevelPt 3), IsE3Datum X L)
    (g : Matrix.GeneralLinearGroup (Fin 2) (ZMod 3)) :
    universalE3Obj R ≅ universalE3Obj R :=
  (naiveLevelThreeRepresentableBy R hR hL hArb).uniqueUpToIso
    ((naiveLevelThreeRepresentableBy R hR hL hArb).ofIso (gammaFullNaiveGlAut R 3 g))

/-- **(WP-D3c-N3, the characterisation)** `e3GlIso g` classifies the universal level-three
structure **re-marked by `g⁻¹`**.

This is what makes the determinant law computable: composing with the classifying-map rules
`e3ClassifyingRingHom_gamma` / `_beta` turns the induced ring automorphism into the coordinate
transformation of the ℰ₃ normal form under `glSmul`. -/
theorem e3GlIso_hom_homEquiv (hR : IsUnit (3 : R))
    (hL : (universalE3Obj R).curve.IsNaiveFullLevel 3
      (universalE3P R) (universalE3Q R))
    (hArb : ∀ (X : EllObj R) (L : X.curve.FullLevelPt 3), IsE3Datum X L)
    (g : Matrix.GeneralLinearGroup (Fin 2) (ZMod 3)) :
    (naiveLevelThreeRepresentableBy R hR hL hArb).homEquiv (e3GlIso R hR hL hArb g).hom =
      (universalE3Obj R).curve.glSmul g⁻¹
        ((naiveLevelThreeRepresentableBy R hR hL hArb).homEquiv
          (𝟙 (universalE3Obj R))) := by
  show (naiveLevelThreeRepresentableBy R hR hL hArb).homEquiv
      (((naiveLevelThreeRepresentableBy R hR hL hArb).ofIso
          (gammaFullNaiveGlAut R 3 g)).homEquiv.symm
        ((naiveLevelThreeRepresentableBy R hR hL hArb).homEquiv
          (𝟙 (universalE3Obj R)))) = _
  exact (naiveLevelThreeRepresentableBy R hR hL hArb).homEquiv.apply_symm_apply _

/-- **(WP-D3c-N3)** The induced automorphism of the level-three moduli **scheme**. -/
noncomputable def e3GlBaseIso (hR : IsUnit (3 : R))
    (hL : (universalE3Obj R).curve.IsNaiveFullLevel 3
      (universalE3P R) (universalE3Q R))
    (hArb : ∀ (X : EllObj R) (L : X.curve.FullLevelPt 3), IsE3Datum X L)
    (g : Matrix.GeneralLinearGroup (Fin 2) (ZMod 3)) :
    Spec (CommRingCat.of (E3ModuliRing R)) ≅ Spec (CommRingCat.of (E3ModuliRing R)) where
  hom := (e3GlIso R hR hL hArb g).hom.baseHom
  inv := (e3GlIso R hR hL hArb g).inv.baseHom
  hom_inv_id := congrArg EllHom.baseHom (e3GlIso R hR hL hArb g).hom_inv_id
  inv_hom_id := congrArg EllHom.baseHom (e3GlIso R hR hL hArb g).inv_hom_id

/-- **(WP-D3c-N3)** …and hence of the ring `E3ModuliRing R`, read on global sections through
`Γ ∘ Spec`. This is the automorphism `σ_g` in which the determinant law
`σ_g (e3Zeta R) = e3Zeta R ^ (det g).val` is stated. -/
noncomputable def e3GlRingEquiv (hR : IsUnit (3 : R))
    (hL : (universalE3Obj R).curve.IsNaiveFullLevel 3
      (universalE3P R) (universalE3Q R))
    (hArb : ∀ (X : EllObj R) (L : X.curve.FullLevelPt 3), IsE3Datum X L)
    (g : Matrix.GeneralLinearGroup (Fin 2) (ZMod 3)) :
    E3ModuliRing R ≃+* E3ModuliRing R :=
  ((Scheme.ΓSpecIso (CommRingCat.of (E3ModuliRing R))).symm ≪≫
      Scheme.Γ.mapIso (e3GlBaseIso R hR hL hArb g).op ≪≫
      Scheme.ΓSpecIso (CommRingCat.of (E3ModuliRing R))).commRingCatIsoToRingEquiv

end ModularCurves
