module

public import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic
public import BernoulliRegular.Reflection.Local.Filtration


/-!
# Local cyclotomic roots of unity

This file starts the REF-10b root-of-unity layer for the local calculation.
It localizes the distinguished primitive `p`-th root of unity and proves that
the subgroup it generates lies in the first principal-unit step `U_1`.
-/

@[expose] public section

noncomputable section

open scoped NumberField

namespace BernoulliRegular
namespace Reflection
namespace Local

section CyclotomicSetup

variable (p : ℕ) [Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- The distinguished cyclotomic root of unity, viewed as a unit in the
localized ring at `lambda`. -/
noncomputable def localCyclotomicZetaUnit : localCyclotomicUnitGroup p K :=
  Units.map (algebraMap (𝓞 K) (localCyclotomicRing p K))
    (((IsCyclotomicExtension.zeta_spec p ℚ K).toInteger_isPrimitiveRoot.isUnit
      (NeZero.ne p)).unit)

@[simp]
theorem localCyclotomicZetaUnit_coe :
    ((localCyclotomicZetaUnit p K : localCyclotomicUnitGroup p K) :
        localCyclotomicRing p K) =
      algebraMap (𝓞 K) (localCyclotomicRing p K)
        (IsCyclotomicExtension.zeta_spec p ℚ K).toInteger := by
  rw [localCyclotomicZetaUnit, Units.coe_map, MonoidHom.coe_coe, IsUnit.unit_spec]

@[simp]
theorem localCyclotomicZetaUnit_pow_eq_one :
    localCyclotomicZetaUnit p K ^ p = 1 := by
  let hζ := IsCyclotomicExtension.zeta_spec p ℚ K
  rw [localCyclotomicZetaUnit, ← map_pow,
    (hζ.toInteger_isPrimitiveRoot.isUnit_unit (NeZero.ne p)).pow_eq_one, map_one]

/-- The cyclotomic `p`-power roots of unity inside the local unit group,
generated by the localized distinguished root `zeta_p`. -/
noncomputable def localCyclotomicMuP : Subgroup (localCyclotomicUnitGroup p K) :=
  Subgroup.zpowers (localCyclotomicZetaUnit p K)

theorem localCyclotomicZetaUnit_mem_muP :
    localCyclotomicZetaUnit p K ∈ localCyclotomicMuP p K :=
  Subgroup.mem_zpowers _

/-- Every element of the cyclotomic root-of-unity subgroup has `p`-th power one. -/
theorem localCyclotomicMuP_le_powMonoidHom_ker :
    localCyclotomicMuP p K ≤
      (powMonoidHom p : localCyclotomicUnitGroup p K →*
        localCyclotomicUnitGroup p K).ker := by
  rw [localCyclotomicMuP]
  exact Subgroup.zpowers_le_of_mem (by
    rw [MonoidHom.mem_ker]
    exact localCyclotomicZetaUnit_pow_eq_one p K)

theorem localCyclotomicMuP_pow_eq_one {u : localCyclotomicUnitGroup p K}
    (hu : u ∈ localCyclotomicMuP p K) :
    u ^ p = 1 := by
  have hker := localCyclotomicMuP_le_powMonoidHom_ker (p := p) (K := K) hu
  rw [MonoidHom.mem_ker] at hker
  exact hker

/-- The localized distinguished root is a principal unit. -/
theorem localCyclotomicZetaUnit_mem_principalUnitSubgroup_one :
    localCyclotomicZetaUnit p K ∈ principalUnitSubgroup p K 1 := by
  rw [mem_principalUnitSubgroup_iff]
  rw [pow_one]
  let hζ := IsCyclotomicExtension.zeta_spec p ℚ K
  change algebraMap (𝓞 K) (localCyclotomicRing p K) hζ.toInteger - 1 ∈
    localCyclotomicMaximalIdeal p K
  have hmem : hζ.toInteger - 1 ∈ cyclotomicLambda p K := by
    rw [cyclotomicLambda, zetaPrime]
    exact Ideal.mem_span_singleton_self ((hζ.toInteger : 𝓞 K) - 1)
  have hmap : algebraMap (𝓞 K) (localCyclotomicRing p K) (hζ.toInteger - 1) ∈
      localCyclotomicMaximalIdeal p K := by
    rw [← localCyclotomicMaximalIdeal_eq_map p K]
    exact Ideal.mem_map_of_mem (algebraMap (𝓞 K) (localCyclotomicRing p K)) hmem
  simpa using hmap

/-- The cyclotomic root-of-unity subgroup lies in `U_1`. -/
theorem localCyclotomicMuP_le_principalUnitSubgroup_one :
    localCyclotomicMuP p K ≤ principalUnitSubgroup p K 1 := by
  rw [localCyclotomicMuP]
  exact Subgroup.zpowers_le_of_mem
    (localCyclotomicZetaUnit_mem_principalUnitSubgroup_one (p := p) (K := K))

/-- The localized distinguished root is not in the second principal-unit step. -/
theorem localCyclotomicZetaUnit_not_mem_principalUnitSubgroup_two :
    localCyclotomicZetaUnit p K ∉ principalUnitSubgroup p K 2 := by
  rw [mem_principalUnitSubgroup_iff]
  let hζ := IsCyclotomicExtension.zeta_spec p ℚ K
  change ¬ (algebraMap (𝓞 K) (localCyclotomicRing p K) hζ.toInteger - 1 ∈
    localCyclotomicMaximalIdeal p K ^ 2)
  intro hmem
  have hπ_prime : Prime ((hζ.toInteger : 𝓞 K) - 1) := hζ.zeta_sub_one_prime'
  have hπ_ne : ((hζ.toInteger : 𝓞 K) - 1) ≠ 0 := hπ_prime.ne_zero
  have hmap : algebraMap (𝓞 K) (localCyclotomicRing p K)
      ((hζ.toInteger : 𝓞 K) - 1) ∈ localCyclotomicMaximalIdeal p K ^ 2 := by
    simpa using hmem
  rw [← localCyclotomicMaximalIdeal_eq_map p K] at hmap
  rw [← Ideal.map_pow] at hmap
  rw [IsLocalization.algebraMap_mem_map_algebraMap_iff
    (M := (cyclotomicLambda p K).primeCompl) (S := localCyclotomicRing p K)] at hmap
  rcases hmap with ⟨s, hs, hsπ⟩
  have hπ_sq_dvd : ((hζ.toInteger : 𝓞 K) - 1) ^ 2 ∣
      s * ((hζ.toInteger : 𝓞 K) - 1) := by
    simpa [cyclotomicLambda, zetaPrime, Ideal.span_singleton_pow,
      Ideal.mem_span_singleton] using hsπ
  have hπ_dvd_s : ((hζ.toInteger : 𝓞 K) - 1) ∣ s :=
    (mul_dvd_mul_iff_right hπ_ne).mp (by
      simpa [pow_two] using hπ_sq_dvd)
  have hs_mem : s ∈ cyclotomicLambda p K := by
    simpa [cyclotomicLambda, zetaPrime, Ideal.mem_span_singleton] using hπ_dvd_s
  exact hs hs_mem

/-- The root-of-unity subgroup contributes nontrivially modulo `U_2`. -/
theorem not_localCyclotomicMuP_le_principalUnitSubgroup_two :
    ¬ localCyclotomicMuP p K ≤ principalUnitSubgroup p K 2 := fun hle =>
  localCyclotomicZetaUnit_not_mem_principalUnitSubgroup_two (p := p) (K := K)
    (hle (localCyclotomicZetaUnit_mem_muP (p := p) (K := K)))

end CyclotomicSetup

end Local
end Reflection
end BernoulliRegular
