module

public import BernoulliRegular.Reflection.Kummer.ResidueSplitting
public import BernoulliRegular.Reflection.Kummer.DedekindSplitting
public import BernoulliRegular.Reflection.ResidueSymbol.Furtwaengler.CoprimeCanonicalCharacter
public import BernoulliRegular.Reflection.ResidueSymbol.Furtwaengler.CoprimeCanonicalCharacterGalois
public import BernoulliRegular.Reflection.ResidueSymbol.Furtwaengler.OneSidedKummerReciprocity

/-!
# From a trivial coprime class character to local Kummer splitting

This file combines the structural bad-set-coprime class character with the
canonical residue-symbol criterion.  It proves the local part of the
nontriviality argument: if the concrete class-group character attached to
`eta` is trivial, then at every admissible prime the polynomial `X^p - eta`
splits over the residue field.

The remaining global step is the Kummer-Dedekind bridge from this residue-field
splitting to complete splitting in the Kummer splitting field.
-/

@[expose] public section

noncomputable section

open scoped NumberField nonZeroDivisors
open Polynomial UniqueFactorizationMonoid

namespace BernoulliRegular
namespace Reflection
namespace Kummer

open BernoulliRegular.Furtwaengler

variable {p : ℕ} [Fact p.Prime]
variable {K : Type*} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

omit [Fact p.Prime] [IsCyclotomicExtension {p} ℚ K] in
/-- The splitting field of a polynomial over a number field is again a number
field.  This localizes the routine typeclass bridge used by the Kummer
nontriviality theorem. -/
theorem splittingField_X_pow_sub_C_numberField
    (η : K) :
    NumberField (SplittingField (X ^ p - C η)) :=
  NumberField.of_module_finite K (SplittingField (X ^ p - C η))

noncomputable local instance splittingFieldNumberField_coprimeCharacterSplitting
    (η : 𝓞 K) :
    NumberField (SplittingField (X ^ p - C (η : K))) :=
  splittingField_X_pow_sub_C_numberField (p := p) (K := K) (η := (η : K))

noncomputable local instance quotientField_coprimeCharacterSplitting {q : Ideal (𝓞 K)}
    [q.IsMaximal] :
    Field (𝓞 K ⧸ q) :=
  Ideal.Quotient.field q

noncomputable local instance quotientDecidableEq_coprimeCharacterSplitting {q : Ideal (𝓞 K)} :
    DecidableEq (𝓞 K ⧸ q) :=
  Classical.decEq _

@[reducible] noncomputable local instance quotientNormalizationMonoid_coprimeCharacterSplitting
    {q : Ideal (𝓞 K)} [q.IsMaximal] :
    NormalizationMonoid (𝓞 K ⧸ q) :=
  (CommGroupWithZero.instNormalizedGCDMonoid (𝓞 K ⧸ q)).toNormalizationMonoid

noncomputable local instance quotientUniqueFactorizationMonoid_coprimeCharacterSplitting
    {q : Ideal (𝓞 K)} [q.IsMaximal] :
    UniqueFactorizationMonoid (𝓞 K ⧸ q) := by
  infer_instance

noncomputable local instance quotientPolynomialNormalizationMonoid_coprimeCharacterSplitting
    {q : Ideal (𝓞 K)} [q.IsMaximal] :
    NormalizationMonoid (𝓞 K ⧸ q)[X] := by
  infer_instance

noncomputable local instance quotientPolynomialDecidableEq_coprimeCharacterSplitting
    {q : Ideal (𝓞 K)} :
    DecidableEq (𝓞 K ⧸ q)[X] :=
  quotientPolynomialDecidableEq (R := 𝓞 K) (I := q)

noncomputable local instance quotientPolynomialUniqueFactorizationMonoid_coprimeCharacterSplitting
    {q : Ideal (𝓞 K)} [q.IsMaximal] :
    UniqueFactorizationMonoid (𝓞 K ⧸ q)[X] := by
  infer_instance

/-- The base conductor ideal for the chosen integral Kummer root in the
splitting field of `X^p - eta`.  Its normalized factors are the finite
Kummer-Dedekind bad primes for that generator. -/
noncomputable def splittingFieldRootConductorComap
    (η : 𝓞 K)
    [NumberField (SplittingField (X ^ p - C (η : K)))] :
    Ideal (𝓞 K) :=
  (conductor (𝓞 K)
    (BernoulliRegular.Kummer.integralRootOfSplitsXPowSubC
      (K := K) (p := p) η (SplittingField (X ^ p - C (η : K))))).comap
      (algebraMap (𝓞 K) (𝓞 (SplittingField (X ^ p - C (η : K)))))

omit [IsCyclotomicExtension {p} ℚ K] in
/-- The conductor-comap bad ideal is nonzero once the quotient of the full
ring of integers by the order generated by the chosen Kummer root is finite
torsion over the base ring of integers.

This is a specialization of
`conductor_comap_ne_bot_of_finite_torsion_quotient`; it makes explicit that
the remaining conductor task is exactly the denominator-clearing statement for
`O_L / O_K[root]`. -/
theorem splittingFieldRootConductorComap_ne_bot_of_finite_torsion_quotient
    (η : 𝓞 K)
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    (htors :
      Module.IsTorsion (𝓞 K)
        (𝓞 (SplittingField (X ^ p - C (η : K))) ⧸
          (Algebra.adjoin (𝓞 K)
            ({BernoulliRegular.Kummer.integralRootOfSplitsXPowSubC
                (K := K) (p := p) η (SplittingField (X ^ p - C (η : K)))} :
              Set (𝓞 (SplittingField (X ^ p - C (η : K)))))).toSubmodule)) :
    splittingFieldRootConductorComap (p := p) (K := K) η ≠ ⊥ := by
  haveI : Module.Finite (𝓞 K) (𝓞 (SplittingField (X ^ p - C (η : K)))) :=
    Module.Finite.of_fg_top (IsNoetherian.noetherian
      (⊤ : Submodule (𝓞 K) (𝓞 (SplittingField (X ^ p - C (η : K))))))
  exact
    conductor_comap_ne_bot_of_finite_torsion_quotient
      (R := 𝓞 K) (S := 𝓞 (SplittingField (X ^ p - C (η : K))))
      (x := BernoulliRegular.Kummer.integralRootOfSplitsXPowSubC
        (K := K) (p := p) η (SplittingField (X ^ p - C (η : K))))
      htors

/-- The Kummer-Dedekind conductor-comap for the chosen root of
`X^p - eta` is nonzero.

The proof is explicit: when `eta` is not a global `p`-th power,
`X^p - eta` is irreducible; because the cyclotomic field contains `mu_p`,
the splitting field is generated by the chosen root.  The generic denominator
clearing theorem then shows that
`O_L / O_K[root]` is torsion, and the conductor-annihilator lemma gives a
nonzero contracted conductor. -/
theorem splittingFieldRootConductorComap_ne_bot
    (hp_ne_two : p ≠ 2)
    (η : 𝓞 K)
    (hη_not_pow : ¬ ∃ β : K, β ^ p = (η : K))
    [NumberField (SplittingField (X ^ p - C (η : K)))] :
    splittingFieldRootConductorComap (p := p) (K := K) η ≠ ⊥ := by
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  let L := SplittingField (X ^ p - C (η : K))
  let x : 𝓞 L :=
    BernoulliRegular.Kummer.integralRootOfSplitsXPowSubC
      (K := K) (p := p) η L
  have hζ : (primitiveRoots p K).Nonempty := by
    refine ⟨IsCyclotomicExtension.zeta p ℚ K, ?_⟩
    rw [mem_primitiveRoots (Fact.out : p.Prime).pos]
    exact IsCyclotomicExtension.zeta_spec p ℚ K
  have Hirred : Irreducible (X ^ p - C (η : K)) := by
    rw [show p = p ^ 1 from (pow_one p).symm]
    refine (X_pow_sub_C_irreducible_iff_of_prime_pow
      (Fact.out : p.Prime) hp_ne_two one_ne_zero).mpr ?_
    intro β hβ
    exact hη_not_pow ⟨β, hβ⟩
  have hroot :
      ((x : L) ^ p) = algebraMap K L (η : K) := by
    simpa [x, L, BernoulliRegular.Kummer.integralRootOfSplitsXPowSubC_coe]
      using rootOfSplitsXPowSubC_pow (n := p) (a := (η : K)) L
  have h_adjoin :
      Algebra.adjoin K ({algebraMap (𝓞 L) L x} : Set L) = ⊤ := by
    simpa [x, L, BernoulliRegular.Kummer.integralRootOfSplitsXPowSubC_coe]
      using
        Algebra.adjoin_root_eq_top_of_isSplittingField
          (K := K) (n := p) hζ Hirred (L := L) hroot
  haveI : Module.Finite (𝓞 K) (𝓞 L) :=
    Module.Finite.of_fg_top
      (IsNoetherian.noetherian (⊤ : Submodule (𝓞 K) (𝓞 L)))
  have htors :
      Module.IsTorsion (𝓞 K)
        (𝓞 L ⧸ (Algebra.adjoin (𝓞 K) ({x} : Set (𝓞 L))).toSubmodule) :=
    quotient_adjoin_isTorsion_of_field_adjoin_eq_top
      (R := 𝓞 K) (S := 𝓞 L) (K := K) (L := L) (x := x) h_adjoin
  exact
    splittingFieldRootConductorComap_ne_bot_of_finite_torsion_quotient
      (p := p) (K := K) η htors

/-- The finite bad set for the Kummer character attached to `eta`: primes
dividing `(eta)`, primes above `p`, and the Kummer-Dedekind conductor factors
for the chosen integral splitting-field root. -/
noncomputable def kummerCharacterBadSet
    (η : 𝓞 K)
    [NumberField (SplittingField (X ^ p - C (η : K)))] :
    Finset (Ideal (𝓞 K)) :=
  ((normalizedFactors (Ideal.span ({η} : Set (𝓞 K)))).toFinset ∪
    (normalizedFactors (Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K)))).toFinset) ∪
      (normalizedFactors (splittingFieldRootConductorComap (p := p) (K := K) η)).toFinset

omit [IsCyclotomicExtension {p} ℚ K] in
/-- Every ideal in the canonical Kummer-character bad set is prime. -/
theorem kummerCharacterBadSet_isPrime
    (η : 𝓞 K) (hη_ne : η ≠ 0)
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    (hcond_ne : splittingFieldRootConductorComap (p := p) (K := K) η ≠ ⊥) :
    ∀ P ∈ kummerCharacterBadSet (p := p) (K := K) η, P.IsPrime := by
  intro P hP
  have hη_span : Ideal.span ({η} : Set (𝓞 K)) ≠ ⊥ := by
    simpa [Ideal.span_singleton_eq_bot] using hη_ne
  have hp_ne : (p : 𝓞 K) ≠ 0 := by
    exact_mod_cast (Fact.out : p.Prime).ne_zero
  have hp_span : Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K)) ≠ ⊥ := by
    simpa [Ideal.span_singleton_eq_bot] using hp_ne
  rw [kummerCharacterBadSet, Finset.mem_union] at hP
  rcases hP with hP | hP
  · rw [Finset.mem_union] at hP
    rcases hP with hP | hP
    · exact isPrime_of_mem_normalizedFactors_ideal (R := 𝓞 K) hη_span hP
    · exact isPrime_of_mem_normalizedFactors_ideal (R := 𝓞 K) hp_span hP
  · exact isPrime_of_mem_normalizedFactors_ideal (R := 𝓞 K) hcond_ne hP

omit [IsCyclotomicExtension {p} ℚ K] in
/-- Every ideal in the canonical Kummer-character bad set is nonzero. -/
theorem kummerCharacterBadSet_ne_bot
    (η : 𝓞 K) (hη_ne : η ≠ 0)
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    (hcond_ne : splittingFieldRootConductorComap (p := p) (K := K) η ≠ ⊥) :
    ∀ P ∈ kummerCharacterBadSet (p := p) (K := K) η, P ≠ ⊥ := by
  intro P hP
  have hη_span : Ideal.span ({η} : Set (𝓞 K)) ≠ ⊥ := by
    simpa [Ideal.span_singleton_eq_bot] using hη_ne
  have hp_ne : (p : 𝓞 K) ≠ 0 := by
    exact_mod_cast (Fact.out : p.Prime).ne_zero
  have hp_span : Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K)) ≠ ⊥ := by
    simpa [Ideal.span_singleton_eq_bot] using hp_ne
  rw [kummerCharacterBadSet, Finset.mem_union] at hP
  rcases hP with hP | hP
  · rw [Finset.mem_union] at hP
    rcases hP with hP | hP
    · exact ne_bot_of_mem_normalizedFactors_ideal (R := 𝓞 K) hη_span hP
    · exact ne_bot_of_mem_normalizedFactors_ideal (R := 𝓞 K) hp_span hP
  · exact ne_bot_of_mem_normalizedFactors_ideal (R := 𝓞 K) hcond_ne hP

omit [IsCyclotomicExtension {p} ℚ K] in
/-- A nonzero prime outside the canonical bad set does not divide `eta`. -/
theorem not_mem_eta_of_not_mem_kummerCharacterBadSet
    (η : 𝓞 K) (hη_ne : η ≠ 0)
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    {P : Ideal (𝓞 K)} [P.IsPrime] (_hP_ne : P ≠ ⊥)
    (hP_not_mem : P ∉ kummerCharacterBadSet (p := p) (K := K) η) :
    η ∉ P := by
  intro hηP
  have hη_span : Ideal.span ({η} : Set (𝓞 K)) ≠ ⊥ := by
    simpa [Ideal.span_singleton_eq_bot] using hη_ne
  have hle : Ideal.span ({η} : Set (𝓞 K)) ≤ P := by
    rw [Ideal.span_le]
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    simpa [hx] using hηP
  have hmem : P ∈ (normalizedFactors (Ideal.span ({η} : Set (𝓞 K)))).toFinset :=
    Multiset.mem_toFinset.mpr
      ((Ideal.mem_normalizedFactors_iff hη_span).mpr ⟨inferInstance, hle⟩)
  exact hP_not_mem (by simp [kummerCharacterBadSet, hmem])

omit [IsCyclotomicExtension {p} ℚ K] in
/-- A nonzero prime outside the canonical bad set does not lie above `p`. -/
theorem not_mem_p_of_not_mem_kummerCharacterBadSet
    (η : 𝓞 K)
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    {P : Ideal (𝓞 K)} [P.IsPrime] (_hP_ne : P ≠ ⊥)
    (hP_not_mem : P ∉ kummerCharacterBadSet (p := p) (K := K) η) :
    (p : 𝓞 K) ∉ P := by
  intro hpP
  have hp_ne : (p : 𝓞 K) ≠ 0 := by
    exact_mod_cast (Fact.out : p.Prime).ne_zero
  have hp_span : Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K)) ≠ ⊥ := by
    simpa [Ideal.span_singleton_eq_bot] using hp_ne
  have hle : Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K)) ≤ P := by
    rw [Ideal.span_le]
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    simpa [hx] using hpP
  have hmem : P ∈ (normalizedFactors (Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K)))).toFinset :=
    Multiset.mem_toFinset.mpr
      ((Ideal.mem_normalizedFactors_iff hp_span).mpr ⟨inferInstance, hle⟩)
  exact hP_not_mem (by simp [kummerCharacterBadSet, hmem])

omit [IsCyclotomicExtension {p} ℚ K] in
/-- The canonical bad set contains the Kummer-Dedekind conductor factors. -/
theorem conductorFactors_subset_kummerCharacterBadSet
    (η : 𝓞 K)
    [NumberField (SplittingField (X ^ p - C (η : K)))] :
    (normalizedFactors (splittingFieldRootConductorComap (p := p) (K := K) η)).toFinset ⊆
      kummerCharacterBadSet (p := p) (K := K) η := by
  intro P hP
  simp [kummerCharacterBadSet, hP]

/-- In the cyclotomic field, a prime not above `p` has residue field size
congruent to `1` modulo `p`.  This is the residue-field form of the fact that
`mu_p` survives injectively in the residue field away from `p`. -/
theorem residue_card_sub_one_dvd_of_not_mem_p
    {q : Ideal (𝓞 K)} [hqprime : q.IsPrime] [hqmax : q.IsMaximal]
    (hq_ne : q ≠ ⊥) (hp_in : (p : 𝓞 K) ∉ q) :
    p ∣ Fintype.card (𝓞 K ⧸ q) - 1 := by
  classical
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  letI : Field (𝓞 K ⧸ q) := Ideal.Quotient.field q
  let ζq : (𝓞 K ⧸ q)ˣ := Furtwaengler.canonicalResidueZetaP (p := p) (K := K) q
  have hprim : IsPrimitiveRoot ζq p :=
    Furtwaengler.canonicalResidueZetaP_isPrimitiveRoot
      (p := p) (K := K) hq_ne hp_in
  have horder : orderOf ζq = p := hprim.eq_orderOf.symm
  have hdvd : orderOf ζq ∣ Fintype.card (𝓞 K ⧸ q)ˣ := orderOf_dvd_card
  rw [horder] at hdvd
  simpa [Fintype.card_units (α := 𝓞 K ⧸ q)] using hdvd

/-- A nonzero prime ideal outside a finite set of nonzero prime ideals is
coprime to every prime in that set. -/
theorem prime_coprime_finset_of_not_mem
    {q : Ideal (𝓞 K)} [hqprime : q.IsPrime]
    (S : Finset (Ideal (𝓞 K)))
    (hSprime : ∀ P ∈ S, P.IsPrime)
    (hS_ne : ∀ P ∈ S, P ≠ ⊥)
    (hq_ne : q ≠ ⊥) (hq_not_mem : q ∉ S) :
    ∀ Q ∈ S, IsCoprime q Q := by
  intro Q hQ
  rw [Ideal.isCoprime_iff_sup_eq]
  have hqmax : q.IsMaximal := Ideal.IsPrime.isMaximal hqprime hq_ne
  have hQmax : Q.IsMaximal := Ideal.IsPrime.isMaximal (hSprime Q hQ) (hS_ne Q hQ)
  exact Ideal.IsMaximal.coprime_of_ne hqmax hQmax (fun hqQ => hq_not_mem (hqQ ▸ hQ))

/-- Triviality of the canonical bad-set-coprime class character forces
`X^p - eta` to split over the residue field at every admissible prime.

The hypotheses `hη`, `hp_in`, and `hdiv` are the local good-prime conditions:
the prime does not divide `eta`, does not lie above `p`, and the residue field
has a primitive `p`-th root of unity.  In the cyclotomic application, `hp_in`
implies `hdiv`, but keeping `hdiv` explicit matches the canonical residue
symbol API. -/
theorem residue_X_pow_sub_C_splits_of_coprimeCanonicalClassGroupModPHom_eq_one
    (η : 𝓞 K) (S : Finset (Ideal (𝓞 K)))
    (hSprime : ∀ P ∈ S, P.IsPrime)
    (hS_ne : ∀ P ∈ S, P ≠ ⊥)
    (hclass :
      ∀ {I J : (Ideal (𝓞 K))⁰}
        (_hI : ∀ P ∈ S, IsCoprime (I : Ideal (𝓞 K)) P)
        (_hJ : ∀ P ∈ S, IsCoprime (J : Ideal (𝓞 K)) P),
        ClassGroup.mk0 I = ClassGroup.mk0 J →
        Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (I : Ideal (𝓞 K)) =
          Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (J : Ideal (𝓞 K)))
    (htriv :
      Furtwaengler.coprimeCanonicalClassGroupModPHom
          (p := p) (K := K) η S hSprime hS_ne hclass = 1)
    {q : Ideal (𝓞 K)} [hqprime : q.IsPrime] [hqmax : q.IsMaximal]
    (hq_ne : q ≠ ⊥)
    (hqS : ∀ Q ∈ S, IsCoprime q Q)
    (hη : η ∉ q)
    (hdiv : p ∣ Fintype.card (𝓞 K ⧸ q) - 1)
    (hp_in : (p : 𝓞 K) ∉ q) :
    (X ^ p - C (Ideal.Quotient.mk q η) : (𝓞 K ⧸ q)[X]).Splits := by
  have hsym :
      Furtwaengler.pthSymbolAtPrime_canonical (p := p) (K := K) η q = 0 :=
    Furtwaengler.pthSymbolAtPrime_canonical_eq_zero_of_coprimeCanonicalClassGroupModPHom_eq_one
      (p := p) (K := K) η S hSprime hS_ne hclass htriv hq_ne hqS
  exact residue_X_pow_sub_C_splits_of_pthSymbolAtPrime_canonical_eq_zero
    (p := p) (K := K) hq_ne hqmax hη hdiv hp_in hsym

/-- Version of
`residue_X_pow_sub_C_splits_of_coprimeCanonicalClassGroupModPHom_eq_one`
where the residue-field divisibility condition is derived from `q ∤ p`. -/
theorem residue_X_pow_sub_C_splits_of_coprimeCanonicalClassGroupModPHom_eq_one_of_not_mem_p
    (η : 𝓞 K) (S : Finset (Ideal (𝓞 K)))
    (hSprime : ∀ P ∈ S, P.IsPrime)
    (hS_ne : ∀ P ∈ S, P ≠ ⊥)
    (hclass :
      ∀ {I J : (Ideal (𝓞 K))⁰}
        (_hI : ∀ P ∈ S, IsCoprime (I : Ideal (𝓞 K)) P)
        (_hJ : ∀ P ∈ S, IsCoprime (J : Ideal (𝓞 K)) P),
        ClassGroup.mk0 I = ClassGroup.mk0 J →
        Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (I : Ideal (𝓞 K)) =
          Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (J : Ideal (𝓞 K)))
    (htriv :
      Furtwaengler.coprimeCanonicalClassGroupModPHom
          (p := p) (K := K) η S hSprime hS_ne hclass = 1)
    {q : Ideal (𝓞 K)} [hqprime : q.IsPrime]
    (hq_ne : q ≠ ⊥)
    (hqS : ∀ Q ∈ S, IsCoprime q Q)
    (hη : η ∉ q)
    (hp_in : (p : 𝓞 K) ∉ q) :
    (X ^ p - C (Ideal.Quotient.mk q η) : (𝓞 K ⧸ q)[X]).Splits := by
  haveI hqmax : q.IsMaximal := Ideal.IsPrime.isMaximal hqprime hq_ne
  have hdiv : p ∣ Fintype.card (𝓞 K ⧸ q) - 1 :=
    residue_card_sub_one_dvd_of_not_mem_p (p := p) (K := K) hq_ne hp_in
  exact residue_X_pow_sub_C_splits_of_coprimeCanonicalClassGroupModPHom_eq_one
    (p := p) (K := K) η S hSprime hS_ne hclass htriv hq_ne hqS hη hdiv hp_in

/-- Version of the local splitting theorem using only membership outside the
finite bad set. -/
theorem residue_X_pow_sub_C_splits_of_coprimeCanonicalClassGroupModPHom_eq_one_of_not_mem_bad
    (η : 𝓞 K) (S : Finset (Ideal (𝓞 K)))
    (hSprime : ∀ P ∈ S, P.IsPrime)
    (hS_ne : ∀ P ∈ S, P ≠ ⊥)
    (hclass :
      ∀ {I J : (Ideal (𝓞 K))⁰}
        (_hI : ∀ P ∈ S, IsCoprime (I : Ideal (𝓞 K)) P)
        (_hJ : ∀ P ∈ S, IsCoprime (J : Ideal (𝓞 K)) P),
        ClassGroup.mk0 I = ClassGroup.mk0 J →
        Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (I : Ideal (𝓞 K)) =
          Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (J : Ideal (𝓞 K)))
    (htriv :
      Furtwaengler.coprimeCanonicalClassGroupModPHom
          (p := p) (K := K) η S hSprime hS_ne hclass = 1)
    {q : Ideal (𝓞 K)} [hqprime : q.IsPrime]
    (hq_ne : q ≠ ⊥)
    (hq_not_mem : q ∉ S)
    (hη : η ∉ q)
    (hp_in : (p : 𝓞 K) ∉ q) :
    (X ^ p - C (Ideal.Quotient.mk q η) : (𝓞 K ⧸ q)[X]).Splits :=
  residue_X_pow_sub_C_splits_of_coprimeCanonicalClassGroupModPHom_eq_one_of_not_mem_p
    (p := p) (K := K) η S hSprime hS_ne hclass htriv hq_ne
    (prime_coprime_finset_of_not_mem (K := K) S hSprime hS_ne hq_ne hq_not_mem)
    hη hp_in

/-- Triviality of the bad-set-coprime class character gives the exact
factor-count input for the Kummer-Dedekind bridge at every good prime. -/
theorem reduced_X_pow_sub_C_factor_card_eq_of_trivial_coprimeCanonicalCharacter
    (η : 𝓞 K) (S : Finset (Ideal (𝓞 K)))
    (hSprime : ∀ P ∈ S, P.IsPrime)
    (hS_ne : ∀ P ∈ S, P ≠ ⊥)
    (hclass :
      ∀ {I J : (Ideal (𝓞 K))⁰}
        (_hI : ∀ P ∈ S, IsCoprime (I : Ideal (𝓞 K)) P)
        (_hJ : ∀ P ∈ S, IsCoprime (J : Ideal (𝓞 K)) P),
        ClassGroup.mk0 I = ClassGroup.mk0 J →
        Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (I : Ideal (𝓞 K)) =
          Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (J : Ideal (𝓞 K)))
    (htriv :
      Furtwaengler.coprimeCanonicalClassGroupModPHom
          (p := p) (K := K) η S hSprime hS_ne hclass = 1)
    {q : Ideal (𝓞 K)} [hqprime : q.IsPrime] [hqmax : q.IsMaximal]
    (hq_ne : q ≠ ⊥)
    (hq_not_mem : q ∉ S)
    (hη : η ∉ q)
    (hp_in : (p : 𝓞 K) ∉ q) :
    (normalizedFactors
      (X ^ p - C (Ideal.Quotient.mk q η) : (𝓞 K ⧸ q)[X])).toFinset.card = p := by
  classical
  have hsplit :
      (X ^ p - C (Ideal.Quotient.mk q η) : (𝓞 K ⧸ q)[X]).Splits :=
    residue_X_pow_sub_C_splits_of_coprimeCanonicalClassGroupModPHom_eq_one_of_not_mem_bad
      (p := p) (K := K) η S hSprime hS_ne hclass htriv hq_ne hq_not_mem hη hp_in
  have hηq : Ideal.Quotient.mk q η ≠ 0 := by
    simpa [Ideal.Quotient.eq_zero_iff_mem] using hη
  have hpq : (p : 𝓞 K ⧸ q) ≠ 0 := by
    change Ideal.Quotient.mk q (p : 𝓞 K) ≠ 0
    intro hpzero
    exact hp_in ((Ideal.Quotient.eq_zero_iff_mem).mp hpzero)
  convert normalizedFactors_X_pow_sub_C_card_eq
    (F := 𝓞 K ⧸ q) (n := p) (a := Ideal.Quotient.mk q η)
    (Fact.out : p.Prime).pos hηq hpq hsplit

/-- Conditional final local step for the nondegeneracy argument.  Once an
integral generator of the Kummer splitting field has reduced minimal polynomial
`X^p - eta`, the concrete trivial class-character hypothesis forces complete
splitting at every good prime by Kummer-Dedekind. -/
theorem splitsCompletely_of_trivial_coprimeCanonicalCharacter_of_minpoly
    (η : 𝓞 K) (S : Finset (Ideal (𝓞 K)))
    (hSprime : ∀ P ∈ S, P.IsPrime)
    (hS_ne : ∀ P ∈ S, P ≠ ⊥)
    (hclass :
      ∀ {I J : (Ideal (𝓞 K))⁰}
        (_hI : ∀ P ∈ S, IsCoprime (I : Ideal (𝓞 K)) P)
        (_hJ : ∀ P ∈ S, IsCoprime (J : Ideal (𝓞 K)) P),
        ClassGroup.mk0 I = ClassGroup.mk0 J →
        Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (I : Ideal (𝓞 K)) =
          Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (J : Ideal (𝓞 K)))
    (htriv :
      Furtwaengler.coprimeCanonicalClassGroupModPHom
          (p := p) (K := K) η S hSprime hS_ne hclass = 1)
    {L : Type*} [Field L] [NumberField L] [Algebra K L]
    [Module.Finite (𝓞 K) (𝓞 L)]
    {q : Ideal (𝓞 K)} [hqprime : q.IsPrime] [hqmax : q.IsMaximal]
    (hq_ne : q ≠ ⊥)
    (hq_not_mem : q ∉ S)
    (hη : η ∉ q)
    (hp_in : (p : 𝓞 K) ∉ q)
    {x : 𝓞 L}
    (hxcond : (conductor (𝓞 K) x).comap (algebraMap (𝓞 K) (𝓞 L)) ⊔ q = ⊤)
    (hxint : IsIntegral (𝓞 K) x)
    (hmin_red :
      (minpoly (𝓞 K) x).map (Ideal.Quotient.mk q) =
        (X ^ p - C (Ideal.Quotient.mk q η) : (𝓞 K ⧸ q)[X]))
    (hfinrank : Module.finrank K L = p) :
    BernoulliRegular.Ideal.SplitsCompletely (𝓞 L) q := by
  classical
  have hfactor :
      (normalizedFactors
        ((minpoly (𝓞 K) x).map (Ideal.Quotient.mk q))).toFinset.card =
        Module.finrank K L := by
    rw [hmin_red]
    exact
      (reduced_X_pow_sub_C_factor_card_eq_of_trivial_coprimeCanonicalCharacter
        (p := p) (K := K) η S hSprime hS_ne hclass htriv
        hq_ne hq_not_mem hη hp_in).trans hfinrank.symm
  exact splitsCompletely_of_reduced_minpoly_factor_card_eq_finrank
    (R := 𝓞 K) (S := 𝓞 L) (K := K) (L := L)
    hq_ne hxcond hxint hfactor

/-- The complete-splitting bridge specialized to the actual Kummer splitting
field.  The only remaining local arithmetic condition is the Kummer-Dedekind
conductor coprimality for the chosen integral root. -/
theorem splitsCompletely_splittingField_of_trivial_coprimeCanonicalCharacter
    (hp_ne_two : p ≠ 2)
    (η : 𝓞 K) (hη_not_pow : ¬ ∃ β : K, β ^ p = (η : K))
    (S : Finset (Ideal (𝓞 K)))
    (hSprime : ∀ P ∈ S, P.IsPrime)
    (hS_ne : ∀ P ∈ S, P ≠ ⊥)
    (hclass :
      ∀ {I J : (Ideal (𝓞 K))⁰}
        (_hI : ∀ P ∈ S, IsCoprime (I : Ideal (𝓞 K)) P)
        (_hJ : ∀ P ∈ S, IsCoprime (J : Ideal (𝓞 K)) P),
        ClassGroup.mk0 I = ClassGroup.mk0 J →
        Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (I : Ideal (𝓞 K)) =
          Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (J : Ideal (𝓞 K)))
    (htriv :
      Furtwaengler.coprimeCanonicalClassGroupModPHom
          (p := p) (K := K) η S hSprime hS_ne hclass = 1)
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    {q : Ideal (𝓞 K)} [hqprime : q.IsPrime] [hqmax : q.IsMaximal]
    (hq_ne : q ≠ ⊥)
    (hq_not_mem : q ∉ S)
    (hη : η ∉ q)
    (hp_in : (p : 𝓞 K) ∉ q)
    (hxcond :
      (conductor (𝓞 K)
          (BernoulliRegular.Kummer.integralRootOfSplitsXPowSubC
            (K := K) (p := p) η (SplittingField (X ^ p - C (η : K))))).comap
            (algebraMap (𝓞 K)
              (𝓞 (SplittingField (X ^ p - C (η : K))))) ⊔ q = ⊤) :
    BernoulliRegular.Ideal.SplitsCompletely
      (𝓞 (SplittingField (X ^ p - C (η : K)))) q := by
  haveI : NeZero p := ⟨(Fact.out : p.Prime).ne_zero⟩
  have hζ : (primitiveRoots p K).Nonempty := by
    refine ⟨IsCyclotomicExtension.zeta p ℚ K, ?_⟩
    rw [mem_primitiveRoots (Fact.out : p.Prime).pos]
    exact IsCyclotomicExtension.zeta_spec p ℚ K
  exact
    splitsCompletely_of_trivial_coprimeCanonicalCharacter_of_minpoly
      (p := p) (K := K) η S hSprime hS_ne hclass htriv
      (L := SplittingField (X ^ p - C (η : K)))
      hq_ne hq_not_mem hη hp_in
      hxcond
      (Algebra.IsIntegral.isIntegral
        (BernoulliRegular.Kummer.integralRootOfSplitsXPowSubC
          (K := K) (p := p) η (SplittingField (X ^ p - C (η : K)))))
      (BernoulliRegular.Kummer.minpoly_integralRootOfSplitsXPowSubC_map_quotient_eq_X_pow_sub_C
        (K := K) (p := p) (Fact.out : p.Prime) hp_ne_two η hη_not_pow
        (SplittingField (X ^ p - C (η : K))) q)
      (BernoulliRegular.Kummer.finrank_splittingField_eq_prime_of_not_isPow
        (K := K) (Fact.out : p.Prime) hp_ne_two hζ hη_not_pow)

/-- Specialization of the Kummer splitting bridge where the finite bad set is
known to contain the normalized prime factors of the Kummer-Dedekind conductor.
This removes the raw conductor-coprimality hypothesis from the call site. -/
theorem splitsCompletely_splittingField_of_trivial_coprimeCanonicalCharacter_of_condSubset
    (hp_ne_two : p ≠ 2)
    (η : 𝓞 K) (hη_not_pow : ¬ ∃ β : K, β ^ p = (η : K))
    (S : Finset (Ideal (𝓞 K)))
    (hSprime : ∀ P ∈ S, P.IsPrime)
    (hS_ne : ∀ P ∈ S, P ≠ ⊥)
    (hclass :
      ∀ {I J : (Ideal (𝓞 K))⁰}
        (_hI : ∀ P ∈ S, IsCoprime (I : Ideal (𝓞 K)) P)
        (_hJ : ∀ P ∈ S, IsCoprime (J : Ideal (𝓞 K)) P),
        ClassGroup.mk0 I = ClassGroup.mk0 J →
        Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (I : Ideal (𝓞 K)) =
          Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (J : Ideal (𝓞 K)))
    (htriv :
      Furtwaengler.coprimeCanonicalClassGroupModPHom
          (p := p) (K := K) η S hSprime hS_ne hclass = 1)
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    (hcond_ne : splittingFieldRootConductorComap (p := p) (K := K) η ≠ ⊥)
    (hcond_subset :
      (normalizedFactors (splittingFieldRootConductorComap (p := p) (K := K) η)).toFinset ⊆ S)
    {q : Ideal (𝓞 K)} [hqprime : q.IsPrime] [hqmax : q.IsMaximal]
    (hq_ne : q ≠ ⊥)
    (hq_not_mem : q ∉ S)
    (hη : η ∉ q)
    (hp_in : (p : 𝓞 K) ∉ q) :
    BernoulliRegular.Ideal.SplitsCompletely
      (𝓞 (SplittingField (X ^ p - C (η : K)))) q := by
  have hq_not_cond :
      q ∉ (normalizedFactors
        (splittingFieldRootConductorComap (p := p) (K := K) η)).toFinset :=
    fun hqmem => hq_not_mem (hcond_subset hqmem)
  have hxcond :
      splittingFieldRootConductorComap (p := p) (K := K) η ⊔ q = ⊤ :=
    sup_eq_top_of_isPrime_not_mem_normalizedFactors
      (R := 𝓞 K) hcond_ne hq_ne hq_not_cond
  exact
    splitsCompletely_splittingField_of_trivial_coprimeCanonicalCharacter
      (p := p) (K := K) hp_ne_two η hη_not_pow S hSprime hS_ne hclass htriv
      hq_ne hq_not_mem hη hp_in
      (by simpa [splittingFieldRootConductorComap] using hxcond)

/-- Triviality of the concrete coprime canonical character gives the
almost-all complete-splitting hypothesis for the Kummer splitting field, once
the finite bad set contains the primes above `p`, the primes dividing `eta`,
and the Kummer-Dedekind conductor factors. -/
theorem almostAll_splitsCompletely_splittingField_of_trivial_coprimeCanonicalCharacter
    (hp_ne_two : p ≠ 2)
    (η : 𝓞 K) (hη_not_pow : ¬ ∃ β : K, β ^ p = (η : K))
    (S : Finset (Ideal (𝓞 K)))
    (hSprime : ∀ P ∈ S, P.IsPrime)
    (hS_ne : ∀ P ∈ S, P ≠ ⊥)
    (hS_eta : ∀ {P : Ideal (𝓞 K)} [P.IsPrime], P ≠ ⊥ → P ∉ S → η ∉ P)
    (hS_p : ∀ {P : Ideal (𝓞 K)} [P.IsPrime], P ≠ ⊥ → P ∉ S → (p : 𝓞 K) ∉ P)
    (hclass :
      ∀ {I J : (Ideal (𝓞 K))⁰}
        (_hI : ∀ P ∈ S, IsCoprime (I : Ideal (𝓞 K)) P)
        (_hJ : ∀ P ∈ S, IsCoprime (J : Ideal (𝓞 K)) P),
        ClassGroup.mk0 I = ClassGroup.mk0 J →
        Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (I : Ideal (𝓞 K)) =
          Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (J : Ideal (𝓞 K)))
    (htriv :
      Furtwaengler.coprimeCanonicalClassGroupModPHom
          (p := p) (K := K) η S hSprime hS_ne hclass = 1)
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    (hcond_ne : splittingFieldRootConductorComap (p := p) (K := K) η ≠ ⊥)
    (hcond_subset :
      (normalizedFactors (splittingFieldRootConductorComap (p := p) (K := K) η)).toFinset ⊆ S) :
    ∀ q : ℕ, q.Prime →
      ∀ P ∈ (IsDedekindDomain.primesOverFinset (Ideal.span ({(q : ℤ)} : Set ℤ))
        (𝓞 K)) \ S,
        BernoulliRegular.Ideal.SplitsCompletely
          (𝓞 (SplittingField (X ^ p - C (η : K)))) P := by
  intro q hq P hP
  have hP_over :
      P ∈ IsDedekindDomain.primesOverFinset (Ideal.span ({(q : ℤ)} : Set ℤ)) (𝓞 K) :=
    (Finset.mem_sdiff.mp hP).1
  have hP_not_mem : P ∉ S := (Finset.mem_sdiff.mp hP).2
  haveI : Fact q.Prime := ⟨hq⟩
  have hq_ne : (Ideal.span ({(q : ℤ)} : Set ℤ)) ≠ ⊥ := by
    rw [Ne, Ideal.span_singleton_eq_bot]
    exact_mod_cast hq.ne_zero
  have hP_primesOver :
      P ∈ (Ideal.span ({(q : ℤ)} : Set ℤ)).primesOver (𝓞 K) :=
    (_root_.IsDedekindDomain.mem_primesOverFinset_iff hq_ne (𝓞 K)).mp hP_over
  haveI hPprime : P.IsPrime := hP_primesOver.1
  have hP_ne : P ≠ ⊥ := Ideal.ne_bot_of_mem_primesOver hq_ne hP_primesOver
  haveI hPmax : P.IsMaximal := Ideal.IsPrime.isMaximal hPprime hP_ne
  exact
    splitsCompletely_splittingField_of_trivial_coprimeCanonicalCharacter_of_condSubset
      (p := p) (K := K) hp_ne_two η hη_not_pow S hSprime hS_ne hclass htriv
      hcond_ne hcond_subset hP_ne hP_not_mem
      (hS_eta hP_ne hP_not_mem) (hS_p hP_ne hP_not_mem)

/-- Nontriviality engine for the concrete coprime canonical character.  Under
the explicit bad-set hypotheses, a trivial residue-symbol character would make
almost all primes split completely in the Kummer splitting field, forcing
`eta` to be a global `p`-th power. -/
theorem coprimeCanonicalClassGroupModPHom_ne_one_of_not_isPow
    (hp_ne_two : p ≠ 2)
    (η : 𝓞 K) (hη_not_pow : ¬ ∃ β : K, β ^ p = (η : K))
    (S : Finset (Ideal (𝓞 K)))
    (hSprime : ∀ P ∈ S, P.IsPrime)
    (hS_ne : ∀ P ∈ S, P ≠ ⊥)
    (hS_eta : ∀ {P : Ideal (𝓞 K)} [P.IsPrime], P ≠ ⊥ → P ∉ S → η ∉ P)
    (hS_p : ∀ {P : Ideal (𝓞 K)} [P.IsPrime], P ≠ ⊥ → P ∉ S → (p : 𝓞 K) ∉ P)
    (hclass :
      ∀ {I J : (Ideal (𝓞 K))⁰}
        (_hI : ∀ P ∈ S, IsCoprime (I : Ideal (𝓞 K)) P)
        (_hJ : ∀ P ∈ S, IsCoprime (J : Ideal (𝓞 K)) P),
        ClassGroup.mk0 I = ClassGroup.mk0 J →
        Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (I : Ideal (𝓞 K)) =
          Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (J : Ideal (𝓞 K)))
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    (hcond_ne : splittingFieldRootConductorComap (p := p) (K := K) η ≠ ⊥)
    (hcond_subset :
      (normalizedFactors (splittingFieldRootConductorComap (p := p) (K := K) η)).toFinset ⊆ S) :
    Furtwaengler.coprimeCanonicalClassGroupModPHom
        (p := p) (K := K) η S hSprime hS_ne hclass ≠ 1 := by
  intro htriv
  have hζ : (primitiveRoots p K).Nonempty := by
    refine ⟨IsCyclotomicExtension.zeta p ℚ K, ?_⟩
    rw [mem_primitiveRoots (Fact.out : p.Prime).pos]
    exact IsCyclotomicExtension.zeta_spec p ℚ K
  have hsplits :
      ∀ q : ℕ, q.Prime →
        ∀ P ∈ (IsDedekindDomain.primesOverFinset (Ideal.span ({(q : ℤ)} : Set ℤ))
          (𝓞 K)) \ S,
          BernoulliRegular.Ideal.SplitsCompletely
            (𝓞 (SplittingField (X ^ p - C (η : K)))) P :=
    almostAll_splitsCompletely_splittingField_of_trivial_coprimeCanonicalCharacter
      (p := p) (K := K) hp_ne_two η hη_not_pow S hSprime hS_ne hS_eta hS_p
      hclass htriv hcond_ne hcond_subset
  have hpow : ∃ β : K, β ^ p = (η : K) :=
    BernoulliRegular.Kummer.isPow_of_almost_all_split
      (K := K) (Fact.out : p.Prime) hp_ne_two hζ (η : K)
      S hS_ne hSprime hsplits
  exact hη_not_pow hpow

/-- Nontriviality of the concrete canonical character for the canonical Kummer
bad set attached to `eta`.  The remaining arithmetic input is exactly the
bad-set-coprime same-class invariance of the residue symbol, to be supplied
from principal-ideal vanishing. -/
theorem coprimeCanonicalClassGroupModPHom_ne_one_of_not_isPow_badSet
    (hp_ne_two : p ≠ 2)
    (η : 𝓞 K) (hη_ne : η ≠ 0)
    (hη_not_pow : ¬ ∃ β : K, β ^ p = (η : K))
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    (hclass :
      ∀ {I J : (Ideal (𝓞 K))⁰}
        (_hI : ∀ P ∈ kummerCharacterBadSet (p := p) (K := K) η,
          IsCoprime (I : Ideal (𝓞 K)) P)
        (_hJ : ∀ P ∈ kummerCharacterBadSet (p := p) (K := K) η,
          IsCoprime (J : Ideal (𝓞 K)) P),
        ClassGroup.mk0 I = ClassGroup.mk0 J →
        Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (I : Ideal (𝓞 K)) =
          Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
            (J : Ideal (𝓞 K))) :
    Furtwaengler.coprimeCanonicalClassGroupModPHom
        (p := p) (K := K) η
        (kummerCharacterBadSet (p := p) (K := K) η)
        (kummerCharacterBadSet_isPrime (p := p) (K := K) η hη_ne
          (splittingFieldRootConductorComap_ne_bot
            (p := p) (K := K) hp_ne_two η hη_not_pow))
        (kummerCharacterBadSet_ne_bot (p := p) (K := K) η hη_ne
          (splittingFieldRootConductorComap_ne_bot
            (p := p) (K := K) hp_ne_two η hη_not_pow))
        hclass ≠ 1 := by
  have hcond_ne : splittingFieldRootConductorComap (p := p) (K := K) η ≠ ⊥ :=
    splittingFieldRootConductorComap_ne_bot
      (p := p) (K := K) hp_ne_two η hη_not_pow
  exact
    coprimeCanonicalClassGroupModPHom_ne_one_of_not_isPow
      (p := p) (K := K) hp_ne_two η hη_not_pow
      (kummerCharacterBadSet (p := p) (K := K) η)
      (kummerCharacterBadSet_isPrime (p := p) (K := K) η hη_ne hcond_ne)
      (kummerCharacterBadSet_ne_bot (p := p) (K := K) η hη_ne hcond_ne)
      (fun hP_ne hP_not_mem =>
        not_mem_eta_of_not_mem_kummerCharacterBadSet
          (p := p) (K := K) η hη_ne hP_ne hP_not_mem)
      (fun hP_ne hP_not_mem =>
        not_mem_p_of_not_mem_kummerCharacterBadSet
          (p := p) (K := K) η hP_ne hP_not_mem)
      hclass hcond_ne
      (conductorFactors_subset_kummerCharacterBadSet (p := p) (K := K) η)

/-- Same nontriviality theorem for the canonical Kummer bad set, with the
same-class invariance input reduced to the principal-balancing equality
provided by fractional principal-ideal vanishing.

This is the shape needed by the weak-reflection character construction: for
bad-set-coprime representatives `I` and `J`, an equality `(x) I = (y) J`
should imply equality of the two principal symbols `(eta / (x))` and
`(eta / (y))`.  The previous theorem then supplies nontriviality of the
descended class-group character. -/
theorem coprimeCanonicalClassGroupModPHom_ne_one_of_not_isPow_badSet_of_principal_balance
    (hp_ne_two : p ≠ 2)
    (η : 𝓞 K) (hη_ne : η ≠ 0)
    (hη_not_pow : ¬ ∃ β : K, β ^ p = (η : K))
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    (hprincipal :
      ∀ {I J : (Ideal (𝓞 K))⁰}
        (_hI : ∀ P ∈ kummerCharacterBadSet (p := p) (K := K) η,
          IsCoprime (I : Ideal (𝓞 K)) P)
        (_hJ : ∀ P ∈ kummerCharacterBadSet (p := p) (K := K) η,
          IsCoprime (J : Ideal (𝓞 K)) P)
        (x y : 𝓞 K) (_hx : x ≠ 0) (_hy : y ≠ 0),
          Ideal.span ({x} : Set (𝓞 K)) * (I : Ideal (𝓞 K)) =
            Ideal.span ({y} : Set (𝓞 K)) * (J : Ideal (𝓞 K)) →
          Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
              (Ideal.span ({x} : Set (𝓞 K))) =
            Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
              (Ideal.span ({y} : Set (𝓞 K)))) :
    Furtwaengler.coprimeCanonicalClassGroupModPHom
        (p := p) (K := K) η
        (kummerCharacterBadSet (p := p) (K := K) η)
        (kummerCharacterBadSet_isPrime (p := p) (K := K) η hη_ne
          (splittingFieldRootConductorComap_ne_bot
            (p := p) (K := K) hp_ne_two η hη_not_pow))
        (kummerCharacterBadSet_ne_bot (p := p) (K := K) η hη_ne
          (splittingFieldRootConductorComap_ne_bot
            (p := p) (K := K) hp_ne_two η hη_not_pow))
        (fun {_ _} hI hJ hmk =>
          Furtwaengler.pthSymbolAtIdeal_canonical_eq_of_mk0_eq_of_coprime_principal_balance
            (p := p) (K := K) η
            (kummerCharacterBadSet (p := p) (K := K) η)
            hprincipal hI hJ hmk) ≠ 1 :=
  coprimeCanonicalClassGroupModPHom_ne_one_of_not_isPow_badSet
      (p := p) (K := K) hp_ne_two η hη_ne hη_not_pow
      (fun {_ _} hI hJ hmk =>
        Furtwaengler.pthSymbolAtIdeal_canonical_eq_of_mk0_eq_of_coprime_principal_balance
          (p := p) (K := K) η
          (kummerCharacterBadSet (p := p) (K := K) η)
          hprincipal hI hJ hmk)

/-- Same nontriviality theorem for the canonical Kummer bad set, with the
same-class invariance input derived from admissible principal-ideal vanishing.

This is the direct endpoint of the class-character construction: once
one-sided Kummer reciprocity supplies principal vanishing for every integral
principal denominator coprime to the bad set, the descended canonical
class-group character is nontrivial for every non-global-`p`th-power `eta`. -/
theorem coprimeCanonicalClassGroupModPHom_ne_one_of_not_isPow_badSet_of_coprime_vanishing
    (hp_ne_two : p ≠ 2)
    (η : 𝓞 K) (hη_ne : η ≠ 0)
    (hη_not_pow : ¬ ∃ β : K, β ^ p = (η : K))
    [NumberField (SplittingField (X ^ p - C (η : K)))]
    (hvanish :
      ∀ z : 𝓞 K, z ≠ 0 →
        (∀ P ∈ kummerCharacterBadSet (p := p) (K := K) η,
          IsCoprime (Ideal.span ({z} : Set (𝓞 K))) P) →
        Furtwaengler.pthSymbolAtIdeal_canonical (p := p) (K := K) η
          (Ideal.span ({z} : Set (𝓞 K))) = 0) :
    Furtwaengler.coprimeCanonicalClassGroupModPHom
        (p := p) (K := K) η
        (kummerCharacterBadSet (p := p) (K := K) η)
        (kummerCharacterBadSet_isPrime (p := p) (K := K) η hη_ne
          (splittingFieldRootConductorComap_ne_bot
            (p := p) (K := K) hp_ne_two η hη_not_pow))
        (kummerCharacterBadSet_ne_bot (p := p) (K := K) η hη_ne
          (splittingFieldRootConductorComap_ne_bot
            (p := p) (K := K) hp_ne_two η hη_not_pow))
        (fun {_ _} hI hJ hmk =>
          Furtwaengler.pthSymbolAtIdeal_canonical_eq_of_mk0_eq_of_coprime_vanishing
            (p := p) (K := K) η
            (kummerCharacterBadSet (p := p) (K := K) η)
            (kummerCharacterBadSet_isPrime (p := p) (K := K) η hη_ne
              (splittingFieldRootConductorComap_ne_bot
                (p := p) (K := K) hp_ne_two η hη_not_pow))
            (kummerCharacterBadSet_ne_bot (p := p) (K := K) η hη_ne
              (splittingFieldRootConductorComap_ne_bot
                (p := p) (K := K) hp_ne_two η hη_not_pow))
            hvanish hI hJ hmk) ≠ 1 :=
  coprimeCanonicalClassGroupModPHom_ne_one_of_not_isPow_badSet
      (p := p) (K := K) hp_ne_two η hη_ne hη_not_pow
      (fun {_ _} hI hJ hmk =>
        Furtwaengler.pthSymbolAtIdeal_canonical_eq_of_mk0_eq_of_coprime_vanishing
          (p := p) (K := K) η
          (kummerCharacterBadSet (p := p) (K := K) η)
          (kummerCharacterBadSet_isPrime (p := p) (K := K) η hη_ne
            (splittingFieldRootConductorComap_ne_bot
              (p := p) (K := K) hp_ne_two η hη_not_pow))
          (kummerCharacterBadSet_ne_bot (p := p) (K := K) η hη_ne
            (splittingFieldRootConductorComap_ne_bot
              (p := p) (K := K) hp_ne_two η hη_not_pow))
          hvanish hI hJ hmk)

/-- Nontriviality of the canonical Kummer bad-set character from the actual
locally-primary pseudo-unit hypotheses.

This combines the OSKR principal-vanishing corollary with the coprime
bad-set character construction and the Kummer splitting nontriviality engine.
The only reciprocity input is
`oneSidedKummerPrincipalReciprocity_canonical`, through
`locallyPrimaryPseudoUnit_principalSymbol_eq_zero_canonical_of_coprime_badSet`.
-/
theorem coprimeCanonicalClassGroupModPHom_ne_one_of_not_isPow_badSet_of_locallyPrimaryPseudoUnit
    (hp_ne_two : p ≠ 2) (hp_odd : Odd p)
    (η : 𝓞 K) (hη_ne : η ≠ 0)
    (hη_not_pow : ¬ ∃ β : K, β ^ p = (η : K))
    (B : Ideal (𝓞 K))
    (hη_prime_to_p :
      IsCoprime
        (Ideal.span ({η} : Set (𝓞 K)))
        (Ideal.span ({(p : 𝓞 K)} : Set (𝓞 K))))
    (hη_local : @Furtwaengler.IsLambdaLocalPthPower p _ K _ _ _ η)
    (hsing : Ideal.span ({η} : Set (𝓞 K)) = B ^ p)
    [NumberField (SplittingField (X ^ p - C (η : K)))] :
    Furtwaengler.coprimeCanonicalClassGroupModPHom
        (p := p) (K := K) η
        (kummerCharacterBadSet (p := p) (K := K) η)
        (kummerCharacterBadSet_isPrime (p := p) (K := K) η hη_ne
          (splittingFieldRootConductorComap_ne_bot
            (p := p) (K := K) hp_ne_two η hη_not_pow))
        (kummerCharacterBadSet_ne_bot (p := p) (K := K) η hη_ne
          (splittingFieldRootConductorComap_ne_bot
            (p := p) (K := K) hp_ne_two η hη_not_pow))
        (fun {_ _} hI hJ hmk =>
          Furtwaengler.pthSymbolAtIdeal_canonical_eq_of_mk0_eq_of_coprime_vanishing
            (p := p) (K := K) η
            (kummerCharacterBadSet (p := p) (K := K) η)
            (kummerCharacterBadSet_isPrime (p := p) (K := K) η hη_ne
              (splittingFieldRootConductorComap_ne_bot
                (p := p) (K := K) hp_ne_two η hη_not_pow))
            (kummerCharacterBadSet_ne_bot (p := p) (K := K) η hη_ne
              (splittingFieldRootConductorComap_ne_bot
                (p := p) (K := K) hp_ne_two η hη_not_pow))
            (fun z hz hzcop =>
              locallyPrimaryPseudoUnit_principalSymbol_eq_zero_canonical_of_coprime_badSet
                p hp_odd K B (kummerCharacterBadSet (p := p) (K := K) η)
                hη_ne hz hη_prime_to_p hη_local hsing
                (by intro P hP; simp [kummerCharacterBadSet, hP])
                (by intro P hP; simp [kummerCharacterBadSet, hP])
                hzcop)
            hI hJ hmk) ≠ 1 :=
  coprimeCanonicalClassGroupModPHom_ne_one_of_not_isPow_badSet_of_coprime_vanishing
      (p := p) (K := K) hp_ne_two η hη_ne hη_not_pow
      (fun z hz hzcop =>
        locallyPrimaryPseudoUnit_principalSymbol_eq_zero_canonical_of_coprime_badSet
          p hp_odd K B (kummerCharacterBadSet (p := p) (K := K) η)
          hη_ne hz hη_prime_to_p hη_local hsing
          (by intro P hP; simp [kummerCharacterBadSet, hP])
          (by intro P hP; simp [kummerCharacterBadSet, hP])
          hzcop)

end Kummer

end Reflection

end BernoulliRegular

end
