import BernoulliRegular.FLT37.LehmerVandiver.CaseI.BridgeAssembly
import BernoulliRegular.FLT37.LehmerVandiver.CaseII.PrincipalDischarge


/-!
# LV-route chain status: parametric reductions for FLT37

This file documents the parametric reduction chain for
`FermatLastTheoremFor 37` via the Lehmer-Vandiver / Washington 9.5
route, exposing all four "axiom-like" inputs as Props.

## Top-level reduction

```
FermatLastTheoremFor 37
  ⟸ fermatLastTheoremFor_thirtyseven_unconditional (final assembly)
    ├── exact Pollaczek K⁺ root source under 37 | h⁺
    ├── Case-I AK5a principal-minus theorem
    ├── NoSecondOrderIrregularPair 37 32 — 37³ ∤ B_{1184}
    └── CaseIIData37 strict descent step — Washington 9.4
```

## Followup expert review (2026-05-07) — recommended attack order

The 2026-05-07 reviewer followup recommended:

1. `T-PIVOT-1-REFRAME` first — reformulate `UnitQuotientComponentTrivial` as
   "`e_i` annihilates `(E⁺/C_S)_p-primary`" (the form Thaine consumes via
   Kučera Theorem 4.3). Small Lean change.
2. `T-Q1-RANK-ONE` next — the atomic rank-one lattice lemma
   `c ∉ p·E ⟺ (E/C)[p]=0`, plus Pollaczek-generator specialisation.
   **Substantive atomic content shipped 2026-05-07** in
   `BernoulliRegular/Thaine/RankOneComponent.lean`:
   * `rankOne_quotient_no_p_torsion_iff_generator_not_divisible` — pure
     ring-theoretic form `(¬ p ∣ a) ↔ ∀ x : R⧸(a), p • x = 0 → x = 0`
     for PID R, prime p, nonzero a.
   * `rankOne_module_quotient_no_p_torsion_iff_generator_not_p_divisible`
     — module-theoretic corollary parametrised by a Λ-linear iso
     `φ : E ≃ₗ[Λ] Λ` (the rank-1 identification used downstream).
   **Pollaczek specialisation shipped 2026-05-07** in
   `BernoulliRegular/Thaine/PollaczekRankOne.lean`:
   * `pollaczek_rankOne_specialisation` — parametric on the rank-one
     identification (φ, c, linkage), connects the K-side certificate
     to the eigenspace torsion vanishing via the module form of the
     atomic lemma.
3. `T-Q1-CSINNOTT` — Sinnott `C_S(K⁺)` = Washington `C_cl(K⁺)` for prime
   conductor. **Shipped 2026-05-07** in
   `BernoulliRegular/Thaine/CircularUnits.lean`:
   * `circularSubgroupKplus p K hp_three : Subgroup ((𝓞 K⁺)ˣ)` — unified
     definition serving as both `C_S` and `C_cl` for prime conductor,
     generated by `-1` and the `cyclotomicUnitFamilyKplus`.
4. `T-KELLNER-SECOND-ORDER` in parallel — discharge `37³ ∤ B_{1184}`.
   The small α-invariant data from Kellner Prop 2.7 is shipped, but the
   final target computation remains open.
   **Partially shipped 2026-05-07** in
   `BernoulliRegular/BernoulliFast/KellnerSecondOrder.lean`:
   * Numerical α-invariant verifications: `37² ∣ B_{32}.num - 111`
     (α_0 = 1) and `37² ∣ B_{68}.num + 37` (α_1 = 22), via
     `bernoulli_decide`.
   * `KellnerProp27_thirtyseven_thirtytwo` — the parametric Prop 2.7
     statement specialised to `(37, 32)`, with `s_unique = 7 ≠ 32`. This
     is now the explicit named `Prop` boundary for the `37³ ∤ B_{1184}`
     content; `noSecondOrderIrregularPair_thirtyseven_thirtytwo_of_kellner`
     discharges `NoSecondOrderIrregularPair 37 32` from it. The previous
     bare `sorry`-based `kellner_at_thirtytwo_not_dvd_pCubed` /
     `noSecondOrderIrregularPair_thirtyseven_thirtytwo` were removed; the
     FLT37 convenience endpoints now take `KellnerProp27_thirtyseven_thirtytwo`
     as an explicit hypothesis (sorry-free).
5. `T-THAINE-5-REFRAME` — `ThaineSingleCharCorollary` documented as
   Kučera Theorem 4.3 specialised to `θ = e_{32}` (docstring update
   2026-05-07).
6. **Higher-order Kummer infrastructure for Kellner Prop 2.7**
   (`KummerCongruence/HigherOrderBinomial.lean`,
   `KummerCongruence/VoronoiHigherOrder.lean`,
   `KummerCongruence/VoronoiHigherOrderFLT37.lean`):
   * `voronoi_sub_pow_quadratic_approx` / `_cubic_approx`: order-2 / 3
     binomial expansions in any commutative ring.
   * `voronoi_per_term_quadratic_bound`: per-term `mod p³` bound.
   * `voronoi_sum_mod_p_cubed` / `_Q`: order-2 Voronoi sum identity in
     ℤ_[p] / ℚ_[p].
   * `voronoi_congruence_mod_p_sq_of_faulhaber` / `voronoi_congruence_mod_p_sq`
     (k ≤ p−1) / `voronoi_congruence_mod_p_sq_extended` (k ≤ 2p−3,
     parametric on unrestricted Adams) — order-2 Voronoi congruence.
   * `bernoulli_mem_padicInt_of_p_not_dvd_den`: numerical bypass of the
     project's restricted-Adams cycle.
   * `faulhaber_term_mem_p_cubed` / `_extended` and the corresponding
     `sum_range_pow_sub_p_mul_bernoulli_weighted_p_cubed` /
     `_extended` order-2 Faulhaber bounds.
   * FLT37 instances `voronoi_congruence_mod_37_sq_thirtytwo`
     (k = 32) and `voronoi_congruence_mod_37_sq_sixtyeight` (k = 68)
     — the substantive mod-`37²` constraints on B_32 and B_68 needed
     for Kellner's α₀, α₁ chain.

`T-THAINE-3/4/5/6` substantive bodies (the Kučera 4.3 proof itself + the
Kolyvagin descent infrastructure) **stay black-boxed** until the rank-one
interface stabilises.

## Cor 8.19 bridge: Thaine route (post 2026-05-06 expert review)

The `Cor8_19Bridge 37 K_37 32` field is now discharged via Thaine's
annihilator theorem, not via Sinnott's regulator computation. Reviewer
recommendation: split the bridge into the four-field decomposition

```
FLT37UnitClassBridge 37 K_37 32
  ├── pollaczekUnitComponent : realLocalCert ⟹ (E⁺/C⁺)(ω^32, 37) trivial
  ├── thaineComponent : (E⁺/C⁺)(ω^32, 37) trivial ⟹ Cl(K⁺)(ω^32, 37) trivial
  ├── reflectionOtherComponents : UniqueIrregularIndex ⟹ ∀ j ≠ 32,
  │ Cl(K⁺)(ω^j, 37) trivial (via Spiegelungssatz + Herbrand–Ribet)
  └── hPlusOfComponents : ∀ j, Cl(K⁺)(ω^j, 37) trivial ⟹ ¬ 37 ∣ hPlus K
```

then chain via `cor8_19Bridge_of_unitClassBridge` (in
`PlusCoprime/Thaine/UnitClassBridge.lean`). The Thaine annihilator at
single character `ω^32` (the substantive remaining piece) avoids both the
Sinnott regulator determinant and the Iwasawa Main Conjecture; see
[Wash97 2nd ed §15] (Thaine/Kolyvagin/Rubin chapters), [Rubin00] *Euler
Systems*, and Kučera (single-character corollary). Foundational Sinnott
identities shipped earlier (full→half log-sin sum, χ-substitution,
matrix-eigenvalue, second-kind orthogonality) remain in
`PlusCoprime/Sinnott/{Determinant,AnalyticProof}.lean` as reusable library
lemmas — correct mathematics, no longer on the critical path.

## Case-I sub-chain (LV010 series, fully parametric)

```
CaseIBridge 37 K
  ⟸ caseIBridge_of_classEqDischarge (LV010-D, this session)
  ⇐ CaseIClassEqDischarge 37 K
      ⇐ caseIClassEqDischarge_of_stage2 (this session)
      ⇐ Stage2KummerRatioK 37 K
        ⇐ ⟨Stage 1 + Stage 2 (Kummer ratio descent)⟩
        Stage 1: caseI_exists_zeta_pow_weakPrimary (this session)
        Stage 2: open (Hilbert 90/92/94 descent)
```

Stage 1 ships the (ζ-1)² weak-primary normalization
(`caseI_exists_zeta_pow_weakPrimary`), regularity-free.

Stage 2 captures the substantive Kummer-ratio statement
(`Stage2KummerRatioK`); its discharge requires Kummer's lemma adapted
to `¬ p ∣ h⁺` via Hilbert 90 / Hilbert 92 / Hilbert 94 descent on
unramified Kummer extensions.

## Case-II sub-chain (fully parametric, shipped)

```
CaseIIBridge 37 K 32
  ⇐ caseIIBridge_of_discharges (this session)
  ⇐ {CaseIIPrincipalDischarge 37 K, AdaptedKummersLemma 37 K}
```

The full case-II inductive descent has been ported via ~17 small
lemmas: `a_div_principal_of_discharge`,
`isPrincipal_a_div_a_zero_of_discharge`,
`exists_not_dvd_spanSingleton_eq_a_div_a_zero_of_discharge`, the α/β
data + specs, `a_mul_denom_eq_a_zero_mul_num_of_discharge`,
`associated_eta_zero_of_discharge`, `associated_eta_zero_unit_*`,
`formula_of_discharge`, `exists_solution_of_discharge`,
`exists_solution'_of_discharges`, `not_exists_solution_of_discharges`,
`not_exists_solution'_of_discharges`, the Int-level versions, and
finally `caseII_of_discharges` + `caseIIBridge_of_discharges`.

Each port replaces flt-regular's regularity hypothesis with the
appropriate parametric Prop discharge.

Note: the abstract `CaseIIPrincipalDischarge` predicate is
mathematically too strong for irregular primes (Cl(K)⁻[p] non-trivial).
The refined `CaseIIPrincipalDischargeOnSpecific` (in
`SpecificDischarge.lean`) restricts to the specific fractional ideals
appearing in case-II setups; this is the correct mathematical target
for filling. The general → specific implication is shipped
(`caseIIPrincipalDischargeOnSpecific_of_general`).

## Status table

| Contract | Predicate | General | Regular |
|---|---|---|---|
| Real local certificate (LV004g) | `realLocalCert` (in bundle) | ✓ | ✓ |
| Thaine / Washington Cor 8.19 | `Cor8_19Bridge p K i` | open (Thaine) | ✓ (vacuous) |
| Vandiver case-I Kummer ratio | `Stage2KummerRatioK p K` | open | ✓ (vacuous) |
| Real Kummer's lemma engine | `RealKummerLemma p K` | open (not final Case-II path) | ✓ |
| Second-order Bernoulli (Kellner) | `NoSecondOrderIrregularPair p i` | user | n/a |
| Washington case II | `CaseIIBridge p K i` | open | ✓ |
| ↳ `caseIIBridge_of_discharges` | parametric form | ✓ | ✓ |
| ↳ `CaseIIPrincipalDischarge` | fractional-ideal principalization | open | ✓ |
| ↳ `AdaptedKummersLemma` | Kummer's lemma adapted | open | ✓ |

The "general" column tracks general-prime status. The "regular" column
tracks regular-prime status — under regularity, every contract is
discharged via either `flt_regular` (vacuously) or by direct
composition with proven engines (`hPlus_dvd_h`, `eq_pow_prime_of_unit_of_congruent`,
etc.). Regular-prime discharges shipped:

* `cor8_19Bridge_of_regular` (`PlusCoprime/Cor8_19Forward.lean`)
* `stage2KummerRatioK_of_regular` (`CaseI/Stage2Interface.lean`)
* `realKummerLemma_of_regular` (`CaseI/RealKummerLemma.lean`)
* `caseIBridge_of_regular` (`CaseI/Bridge.lean`)
* `caseIIBridge_of_regular` (`CaseII/ADivPrincipal.lean`)

The "open" rows in the general column are deep substantive contracts (each
chapter-length); the parametric reduction chain is fully shipped,
axiom-clean. For FLT37 (irregular at index 32) the substantive
remaining work is filling these for `¬p∣h⁺` instead of regularity.
The final Case-II route no longer imports or consumes the generic
`RealKummerLemma` adapter; it is shaped around the `CaseIIData37` strict
descent theorem and Washington's adjacent quotient expressions.

## Top-level FLT37 entry point (updated 2026-05-25)

`PlusCoprime/Unconditional.lean` ships
`fermatLastTheoremFor_thirtyseven_unconditional` as the consolidated
top-level FLT37 statement, modulo three structural placeholder sorries and
the exact second-order Bernoulli placeholder:

1. `flt37_pollaczekUnitPlusKplus_isPthPower_under_hPlus_dvd_placeholder`
   — exact Pollaczek source: under `37 | hPlus(K_37)`, the canonical
   K⁺ preimage `pollaczekUnitPlusKplus 37 K_37 32` is a 37-th power.
   The final path now uses the concrete no-root certificate directly to
   derive `¬ 37 | hPlus(K_37)`.

2. `flt37_caseI_AK_unramified_per_case_placeholder`
   — Case-I source: prove unramifiedness of the actual anti-Kummer lift for
   each FLT37 Case-I datum.  The private AK5a theorem is now a checked
   consequence of this per-case source plus the Pollaczek/Vandiver discharge,
   and the reduction from AK5a to `Stage2KummerRatioK` is already proved.

3. `caseII_descent_step_under_vandiver37`
   — Wash97 §9.4 Case-II strict descent on `CaseIIData37`, under
   `¬ 37 | hPlus(K_37)` and `NoSecondOrderIrregularPair 37 32`.
   This replaces the older final path through a separated real-ideal
   model placeholder and standalone adapted-Kummer placeholder.

4. `KellnerProp27_thirtyseven_thirtytwo`
   — the named parametric `Prop` carrying the second-order Bernoulli content
   `37³ ∤ B_{1184}.num` (= Kellner Prop 2.7 specialised to `(37, 32)`,
   `s_unique = 7 ≠ 32`). Direct computation of `B_{1184}` times out, and the
   underlying fact is genuinely Iwasawa-theoretic, so it is an explicit
   hypothesis rather than a `sorry`. The bare `sorry`-based
   `kellner_at_thirtytwo_not_dvd_pCubed` was removed
   (`noSecondOrderIrregularPair_thirtyseven_thirtytwo_of_kellner` discharges
   `NoSecondOrderIrregularPair 37 32` from the named `Prop`).

Also shipped axiom-clean alongside:

* `dvd_hMinus_thirtyseven_unconditional : (37 : ℕ) ∣ hMinus (CyclotomicField 37 ℚ)`
  — proven via Diekmann Theorem 42 (`p_dvd_hMinus_iff_p_dvd_some_bernoulli`)
  + the shipped fact `thirtyseven_dvd_bernoulli_thirtytwo_num` (37 | B_32).
  Independent of the chain composition; axiom hygiene `[propext,
  Classical.choice, Quot.sound]`.

The narrowest checked non-Bernoulli route is now also available in
`PlusCoprime/Unconditional.lean`:

* The theorem
  `...of_thaineHR_caseIAK5UnitCongr_adjacentWashingtonUnitPower...`
  consumes the field-level component identification, the single-character
  Thaine input, the boundary component at `36`, the Herbrand-range implication
  `componentNontrivial j -> 37 | numerator(B_j)` for even `j <= 34`, the direct
  AK-5 unit-form plus `(37 : O_K) | u - 1` target for actual case-I factor
  ideals, the adjacent Washington expression/span identities with nonzero
  derived from nondivisibility, the exact quotient-unit p-th-power source, and
  the explicit `NoSecondOrderIrregularPair 37 32`.
* The sibling theorem
  `...of_thaineHR_AK5Universal_adjacentWashingtonUnitPower...` uses the same
  Herbrand-reflection and Case-II surfaces, but consumes the universal AK-5
  unit-form/strong-primarity producer instead of the per-factor direct
  congruence target.

The old bundled reflection-other input is now a checked consequence of those
boundary/Herbrand inputs plus `UniqueIrregularIndex.thirtyseven_thirtytwo`; see
`reflectionOtherDischarge_thirtyseven_of_boundary_and_herbrandRibet`.

On the Case-II side, the adapted-unit source has also been split at the exact
unit used by the descent algebra.  The adjacent-generator consumers
`CaseIIData37.descent_step_of_adjacent_etaZeroSpanSingletons_and_unitPower`,
`CaseIIData37.descent_step_of_adjacent_integral_real_generators_and_unitPower`,
and `caseII_descent_step_of_adjacent_integral_real_generators_and_unitPower`
show that, once the two anchored generators are built, the remaining source
task is to prove the resulting quotient unit `ε₁ / ε₂` is a `37`-th power.
The same split now reaches the Washington-expression bridge and two
exact-Pollaczek final assemblies:
`caseIIBridge37_of_adjacent_washingtonExpr_oneConj_noNonzero_unitPower_via_descent`,
the direct AK5 unit-congruence endpoint, the universal AK5 endpoint, and the
new Herbrand-reflection universal AK5 endpoint.

This endpoint is only a checked composition. It does not discharge the
single-character Thaine theorem, the boundary/Herbrand reflection source, the
AK-5 unit/congruence source, or the Washington expression/adapted-unit source.

## References

* Diekmann (2023), §4 (LV-route).
* Washington, *Introduction to Cyclotomic Fields*, 2nd ed.,
  §§8.3 (Cor 8.19), 9.3 (Theorem 9.3 = Vandiver case I), 9.4
  (Theorem 9.4 = case II), §5.5 (Kummer's lemma).
* `BernoulliRegular/FLT37/Hilbert90.lean` — engine for class-equality
  → principalization under VC.
* flt-regular's `eq_pow_prime_of_unit_of_congruent`,
  `KummersLemma.isUnramified`, `dvd_card_classGroup_of_isUnramified_isCyclic`.
-/

@[expose] public section

namespace BernoulliRegular

/-- **FLT37 chain status.** Trivial reference theorem to ensure
imports compose; the substantive content is in the imported files'
parametric reduction theorems. -/
theorem flt37_chain_status :
    True := trivial

end BernoulliRegular

end
