/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import PadicLFunctions.IwasawaProof.Main

/-!
# Tower density: level-`n` image of the Galois-orbit subgroup (RJW §13, T1221)

This file records the **plus** cyclic-module generating subgroup `M⁺` of the unit tower `𝒰_∞`
and computes its level-`n` image under the coordinate map `s ↦ s.elems n : ℂ_[p]ˣ`.

The Teichmüller-corrected generator `wγ(a₀)` (`wGamma`) is already the *principal/plus*
generator, so the plus generating subgroup `M⁺ = ⟨σ_a · wγ(a₀) : a ∈ ℤ_p^×⟩` is the very same
subgroup as `cycloGenSubgroup` (`Main.lean`): the multiplicative subgroup generated by the
`𝒢`-translates of `wγ(a₀)`. We name it `cycloGenSubgroupPlus` (the spelling used by the §13
tower-density tickets T1221/T1223).

The image computation `elems_image_cycloGenSubgroupPlus` is the set-image (`Set.image`) form of
the banked subgroup-level identity `map_elemsMonoidHom_cycloGenSubgroup`
(`Subgroup.map (elemsMonoidHom p n) (cycloGenSubgroup p hp2) = cycloTranslateSubgroup p n
((wGamma p hp2).elems n)`), transported across `Subgroup.coe_map`. The coordinate map is the
banked `MonoidHom` `elemsMonoidHom p n` (levelwise multiplicative and unital, since
`(u*v).elems n = u.elems n * v.elems n` and `(1).elems n = 1` hold definitionally), whose
underlying function is `fun s => s.elems n`.
-/

open PadicLFunctions PadicLFunctions.Coleman

noncomputable section

namespace PadicLFunctions.Coleman

variable (p : ℕ) [hp : Fact p.Prime]

/-- **The plus cyclic-module generating subgroup** `M⁺ = ⟨σ_a · wγ(a₀) : a ∈ ℤ_p^×⟩` of `𝒰_∞`.
Since `wγ(a₀)` (`wGamma`) is already the Teichmüller-corrected *principal/plus* generator, `M⁺`
coincides with `cycloGenSubgroup` — the multiplicative subgroup generated by the `𝒢`-translates
of `wγ(a₀)`. Its closure is RJW's plus cyclic `Λ(𝒢^+)`-module `𝒞⁺_{∞,1}`
(LemmaGeneratorCinfty1(ii)). -/
def cycloGenSubgroupPlus (hp2 : p ≠ 2) : Subgroup (NormCompatUnits p) :=
  cycloGenSubgroup p hp2

/-- **T1221 — the level-`n` image of the plus generating subgroup** `M⁺` is exactly the
`𝒢_n`-translate subgroup of `wγ(a₀)`'s level-`n` coordinate. This is the `Set.image` form of the
banked subgroup-level identity `map_elemsMonoidHom_cycloGenSubgroup`, transported across
`Subgroup.coe_map`: `↑(map (elemsMonoidHom p n) M⁺) = (elemsMonoidHom p n) '' ↑M⁺`, and the
underlying function of `elemsMonoidHom p n` is `fun s => s.elems n`. -/
theorem elems_image_cycloGenSubgroupPlus (hp2 : p ≠ 2) (n : ℕ) :
    (fun s : NormCompatUnits p => (s.elems n : ℂ_[p]ˣ)) '' (cycloGenSubgroupPlus p hp2) =
      (cycloTranslateSubgroup p n ((wGamma p hp2).elems n) : Set ℂ_[p]ˣ) := by
  rw [cycloGenSubgroupPlus, ← map_elemsMonoidHom_cycloGenSubgroup p hp2 n, Subgroup.coe_map]
  rfl

end PadicLFunctions.Coleman
