/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import Mathlib.AlgebraicGeometry.IdealSheaf.Subscheme
import ModularCurves.Picard.PicComparison

/-!
# The ideal sheaf of a closed subscheme as a module (API gap AG-LB)

For `J : C.IdealSheafData`, the ideal sheaf `I(J) ⊆ 𝒪_C` as a sheaf of `𝒪_C`-modules:
sections over an arbitrary open `U` are the kernel of the subscheme inclusion's component
`Γ(C, U) ⟶ Γ(J.subscheme, ι⁻¹U)` (at affine opens this is `J.ideal` by
`ker_subschemeι_app`). This is the module-side interface KM 1.1.1 needs ("the ideal
sheaf `I(D) ⊂ O_X` is an invertible `O_X`-module") — the invertibility from local
principality is `isInvertible_idealModule` below, closing the AG-LB gap for the
divisor engine of `LevelStructure/CartierDivisor.lean`.

## Main definitions

* `AlgebraicGeometry.Scheme.Modules.idealModule`: the ideal sheaf of `J` as an object
  of `C.Modules`.
* `AlgebraicGeometry.Scheme.Modules.isInvertible_idealModule`: on a scheme, an ideal
  sheaf which is affine-locally generated by a single nonzerodivisor is an invertible
  module.
-/

universe u

open CategoryTheory

namespace AlgebraicGeometry.Scheme.Modules

variable {C : Scheme.{u}} (J : C.IdealSheafData)

/-- The sections of the ideal sheaf over an arbitrary open `U`: the kernel of the
subscheme inclusion's component at `U`. -/
noncomputable def idealSections (U : (TopologicalSpace.Opens ↥C)ᵒᵖ) :
    Ideal Γ(C, U.unop) :=
  RingHom.ker (J.subschemeι.app U.unop).hom

/-- Restriction preserves the ideal sections (naturality of the inclusion). -/
theorem idealSections_map {U V : (TopologicalSpace.Opens ↥C)ᵒᵖ} (i : U ⟶ V)
    {g : Γ(C, U.unop)} (hg : g ∈ idealSections J U) :
    C.presheaf.map i g ∈ idealSections J V := by
  have hg' : (J.subschemeι.app U.unop).hom g = 0 := hg
  have hnat := J.subschemeι.naturality (show Opposite.op U.unop ⟶ Opposite.op V.unop from i)
  refine RingHom.mem_ker.mpr ?_
  have h1 : (J.subschemeι.app V.unop).hom (C.presheaf.map i g) =
      (J.subscheme.presheaf.map
          ((TopologicalSpace.Opens.map J.subschemeι.base).map i.unop).op).hom
        ((J.subschemeι.app U.unop).hom g) :=
    congrArg (fun (φ : _ ⟶ _) => (ConcreteCategory.hom φ) g) hnat
  rw [h1, hg', map_zero]

/-- The ideal sheaf of `J` as a presheaf of abelian groups: sections are
`idealSections`, restrictions those of the structure sheaf. -/
noncomputable def idealPresheafAb : (TopologicalSpace.Opens ↥C)ᵒᵖ ⥤ AddCommGrpCat.{u} where
  obj U := AddCommGrpCat.of (idealSections J U)
  map {U V} i := AddCommGrpCat.ofHom
    { toFun := fun g => ⟨C.presheaf.map i g.1, idealSections_map J i g.2⟩
      map_zero' := by
        refine Subtype.ext ?_
        exact map_zero (ConcreteCategory.hom (C.presheaf.map i))
      map_add' := fun g g' => by
        refine Subtype.ext ?_
        exact map_add (ConcreteCategory.hom (C.presheaf.map i)) g.1 g'.1 }
  map_id U := by
    ext g
    show C.presheaf.map (𝟙 U) g.1 = g.1
    rw [CategoryTheory.Functor.map_id]
    rfl
  map_comp {U V W} i j := by
    ext g
    show C.presheaf.map (i ≫ j) g.1 = C.presheaf.map j (C.presheaf.map i g.1)
    rw [Functor.map_comp]
    rfl

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- The ideal sections as a subfunctor of the `Type`-valued structure sheaf. -/
noncomputable def idealSubfunctor :
    Subfunctor (C.sheaf.val ⋙ CategoryTheory.forget CommRingCat) where
  obj U := {g | (J.subschemeι.app U.unop).hom g = 0}
  map {U V} i := fun g hg =>
    RingHom.mem_ker.mp (idealSections_map J i (RingHom.mem_ker.mpr hg))

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- Vanishing under the subscheme inclusion is a local condition (separatedness of the
subscheme's structure sheaf, via germs), so the ideal subfunctor is a sheaf. -/
theorem idealSubfunctor_isSheaf :
    Presieve.IsSheaf (Opens.grothendieckTopology ↥C)
      (idealSubfunctor J).toFunctor := by
  apply ((idealSubfunctor J).isSheaf_iff
    ((isSheaf_iff_isSheaf_of_type _ _).mp
      ((Presheaf.isSheaf_iff_isSheaf_forget _ _ (CategoryTheory.forget CommRingCat)).mp
        C.sheaf.cond))).2
  intro U g hsieve
  show (J.subschemeι.app U.unop).hom g = 0
  rw [Opens.mem_grothendieckTopology] at hsieve
  refine TopCat.Presheaf.section_ext J.subscheme.sheaf _ _ _ (fun y hy => ?_)
  obtain ⟨V, f, hfV, hyV⟩ := hsieve (J.subschemeι.base y) hy
  have h0 : (J.subschemeι.app V).hom (C.presheaf.map f.op g) = 0 := hfV
  have h1 : J.subscheme.presheaf.map
        ((TopologicalSpace.Opens.map J.subschemeι.base).map f).op
        ((J.subschemeι.app U.unop).hom g) =
      (J.subschemeι.app V).hom (C.presheaf.map f.op g) :=
    (congrArg (fun (φ : _ ⟶ _) => (ConcreteCategory.hom φ) g)
      (J.subschemeι.naturality f.op)).symm
  have hyV' : y ∈ J.subschemeι ⁻¹ᵁ V := hyV
  calc J.subscheme.presheaf.germ (J.subschemeι ⁻¹ᵁ U.unop) y hy
        ((J.subschemeι.app U.unop).hom g)
      = J.subscheme.presheaf.germ (J.subschemeι ⁻¹ᵁ V) y hyV'
          (J.subscheme.presheaf.map
            ((TopologicalSpace.Opens.map J.subschemeι.base).map f).op
            ((J.subschemeι.app U.unop).hom g)) :=
        (J.subscheme.presheaf.germ_res_apply
          ((TopologicalSpace.Opens.map J.subschemeι.base).map f) y hyV' _).symm
    _ = J.subscheme.presheaf.germ (J.subschemeι ⁻¹ᵁ V) y hyV'
          ((J.subschemeι.app V).hom (C.presheaf.map f.op g)) :=
        congrArg _ h1
    _ = 0 := by rw [h0]; exact map_zero _
    _ = J.subscheme.presheaf.germ (J.subschemeι ⁻¹ᵁ U.unop) y hy 0 :=
        (map_zero _).symm

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
noncomputable instance (U : (TopologicalSpace.Opens ↥C)ᵒᵖ) :
    Module ((C.ringCatSheaf.obj).obj U) ((idealPresheafAb J).obj U) :=
  inferInstanceAs (Module Γ(C, U.unop) (idealSections J U))

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- The ideal sheaf of `J` as a presheaf of `𝒪_C`-modules. -/
noncomputable def idealPresheaf : _root_.PresheafOfModules (C.ringCatSheaf.obj) :=
  PresheafOfModules.ofPresheaf (idealPresheafAb J) (fun {U V} i r m => by
    refine Subtype.ext ?_
    let r' : Γ(C, U.unop) := r
    show C.presheaf.map i (r' * m.1) =
      C.presheaf.map i r' * C.presheaf.map i m.1
    exact map_mul (ConcreteCategory.hom (C.presheaf.map i)) r' m.1)

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- The comparison of the ideal presheaf's sections with the ideal subfunctor. -/
noncomputable def idealPresheafForgetIso :
    (idealPresheaf J).presheaf ⋙ CategoryTheory.forget AddCommGrpCat ≅ (idealSubfunctor J).toFunctor :=
  NatIso.ofComponents (fun U => Iso.refl _) (fun {U V} i => rfl)

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- **The ideal sheaf of `J` as a sheaf of `𝒪_C`-modules** (the object side of the
KM 1.1.1 interface "the ideal sheaf `I(D) ⊂ O_X` is an invertible `O_X`-module"). -/
noncomputable def idealModule : C.Modules where
  val := idealPresheaf J
  isSheaf := by
    apply (Presheaf.isSheaf_iff_isSheaf_forget _ _ (CategoryTheory.forget AddCommGrpCat)).mpr
    apply (isSheaf_iff_isSheaf_of_type _ _).mpr
    exact Presieve.isSheaf_iso _ (idealPresheafForgetIso J).symm
      (idealSubfunctor_isSheaf J)

section BasisLocal

variable {X : Scheme.{u}}

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- Basis variant of `sheafificationW_of_bijective_on_cover`: componentwise bijectivity
on a basis of opens makes a presheaf map a `sheafificationW`-member. -/
theorem sheafificationW_of_bijective_on_basis {A B : X.PresheafOfModules}
    (g : A ⟶ B) (Bs : Set X.Opens)
    (hBs : ∀ (x : ↥X) (U : X.Opens), x ∈ U → ∃ W ∈ Bs, x ∈ W ∧ W ≤ U)
    (hbij : ∀ W ∈ Bs, Function.Bijective (g.app (Opposite.op W))) :
    PresheafOfModules.sheafificationW (𝟙 X.ringCatSheaf.obj) g := by
  have hsieve : ∀ (V : (TopologicalSpace.Opens ↥X)ᵒᵖ) (S : Sieve V.unop),
      (∀ W ∈ Bs, ∀ (hWV : W ≤ V.unop), S (homOfLE hWV)) →
      S ∈ Opens.grothendieckTopology ↥X V.unop := by
    intro V S hS
    rw [Opens.mem_grothendieckTopology]
    intro x hx
    obtain ⟨W, hWB, hxW, hWV⟩ := hBs x V.unop hx
    exact ⟨W, homOfLE hWV, hS W hWB hWV, hxW⟩
  haveI hinj : Presheaf.IsLocallyInjective (Opens.grothendieckTopology ↥X)
      ((PresheafOfModules.toPresheaf _).map g) := by
    constructor
    intro V x y hxy
    refine hsieve V _ (fun W hWB hWV => ?_)
    refine (hbij W hWB).injective ?_
    have hnx := PresheafOfModules.naturality_apply g (homOfLE hWV).op x
    have hny := PresheafOfModules.naturality_apply g (homOfLE hWV).op y
    calc g.app (Opposite.op W) (A.map (homOfLE hWV).op x)
        = B.map (homOfLE hWV).op (g.app V x) := hnx
      _ = B.map (homOfLE hWV).op (g.app V y) := by
          rw [show g.app V x = g.app V y from hxy]
      _ = g.app (Opposite.op W) (A.map (homOfLE hWV).op y) := hny.symm
  haveI hsurj : Presheaf.IsLocallySurjective (Opens.grothendieckTopology ↥X)
      ((PresheafOfModules.toPresheaf _).map g) := by
    constructor
    intro V s
    refine hsieve (Opposite.op V) _ (fun W hWB hWV => ?_)
    obtain ⟨t, ht⟩ := (hbij W hWB).surjective (B.map (homOfLE hWV).op s)
    exact ⟨t, ht⟩
  exact (PresheafOfModules.sheafificationW_iff_isLocallyBijective _ g).mpr ⟨hinj, hsurj⟩

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- A morphism of `𝒪ₓ`-modules whose presheaf components are bijective on a basis of
opens is an isomorphism (sheafification inverts the locally bijective map; conjugate by
the counit). -/
theorem isIso_of_bijective_app_on_basis {A B : X.Modules} (g : A ⟶ B)
    (Bs : Set X.Opens)
    (hBs : ∀ (x : ↥X) (U : X.Opens), x ∈ U → ∃ W ∈ Bs, x ∈ W ∧ W ≤ U)
    (hbij : ∀ W ∈ Bs, Function.Bijective (g.val.app (Opposite.op W))) :
    IsIso g := by
  have hw := sheafificationW_of_bijective_on_basis g.val Bs hBs hbij
  rw [PresheafOfModules.sheafificationW_iff] at hw
  have hnat := (PresheafOfModules.sheafificationAdjunction
    (𝟙 X.ringCatSheaf.obj)).counit.naturality g
  have hg : g = (sheafifyValIso A).inv ≫
      (PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj)).map g.val ≫
      (sheafifyValIso B).hom := by
    rw [Iso.eq_inv_comp]
    exact hnat.symm
  rw [hg]
  haveI : IsIso ((PresheafOfModules.sheafification (𝟙 X.ringCatSheaf.obj)).map g.val) := hw
  infer_instance

end BasisLocal

section GenTriv

variable {C : Scheme.{u}} (J : C.IdealSheafData)

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- Multiplication by a section `f` of the ideal over `V`: a morphism from the structure
sheaf of `V` to the restriction of the ideal module. -/
noncomputable def idealGenHom (V : C.Opens) (f : Γ(C, V))
    (hf : f ∈ idealSections J (Opposite.op V)) :
    unitObj ↑V ⟶ (restrictFunctor V.ι).obj (idealModule J) :=
  ⟨{ app := fun W => ModuleCat.ofHom
      (Y := ((restrictFunctor V.ι).obj (idealModule J)).val.obj W)
      { toFun := fun g =>
          ⟨C.presheaf.map (homOfLE (V.ι_image_le W.unop)).op f *
              (V.ι.appIso W.unop).inv g,
            Ideal.mul_mem_right _ _
              (idealSections_map J (homOfLE (V.ι_image_le W.unop)).op hf)⟩
        map_add' := fun g g' => Subtype.ext (by
          show _ * (ConcreteCategory.hom (V.ι.appIso W.unop).inv) (g + g') = _
          rw [map_add, mul_add]
          rfl)
        map_smul' := fun r g => Subtype.ext (by
          show C.presheaf.map (homOfLE (V.ι_image_le W.unop)).op f *
              (ConcreteCategory.hom (V.ι.appIso W.unop).inv) (r * g) =
            (ConcreteCategory.hom (V.ι.appIso W.unop).inv) r *
              (C.presheaf.map (homOfLE (V.ι_image_le W.unop)).op f *
                (ConcreteCategory.hom (V.ι.appIso W.unop).inv) g)
          rw [map_mul]
          ring) }
     naturality := fun {W W'} i => by
      refine ModuleCat.hom_ext (LinearMap.ext fun g => ?_)
      refine Subtype.ext ?_
      have harr : (homOfLE (V.ι_image_le W.unop)).op ≫ V.ι.opensFunctor.op.map i =
          (homOfLE (V.ι_image_le W'.unop)).op := Subsingleton.elim _ _
      have h1 : C.presheaf.map (V.ι.opensFunctor.op.map i)
          (C.presheaf.map (homOfLE (V.ι_image_le W.unop)).op f) =
          C.presheaf.map (homOfLE (V.ι_image_le W'.unop)).op f := by
        rw [← harr, Functor.map_comp]
        rfl
      have h2 : C.presheaf.map (V.ι.opensFunctor.op.map i)
          ((V.ι.appIso W.unop).inv g) =
          (V.ι.appIso W'.unop).inv ((↑V : Scheme.{u}).presheaf.map i g) :=
        (congrArg (fun (φ : _ ⟶ _) => (ConcreteCategory.hom φ) g)
          (V.ι.appIso_inv_naturality i)).symm
      show C.presheaf.map (homOfLE (V.ι_image_le W'.unop)).op f *
            (V.ι.appIso W'.unop).inv ((↑V : Scheme.{u}).presheaf.map i g) =
          C.presheaf.map (V.ι.opensFunctor.op.map i)
            (C.presheaf.map (homOfLE (V.ι_image_le W.unop)).op f *
              (V.ι.appIso W.unop).inv g)
      rw [map_mul, h1, h2] }⟩

/-- In a localization away from `a`, multiplication by the image of a nonzerodivisor
is injective at zero. -/
private theorem away_mul_algebraMap_eq_zero {R S : Type u} [CommRing R] [CommRing S]
    [Algebra R S] (a : R) [IsLocalization.Away a S] {f : R}
    (hf : f ∈ nonZeroDivisors R) {z : S} (hz : z * algebraMap R S f = 0) : z = 0 := by
  obtain ⟨⟨y, s⟩, hys⟩ := IsLocalization.surj (Submonoid.powers a) z
  have h1 : algebraMap R S (y * f) = 0 := by
    calc algebraMap R S (y * f)
        = (z * algebraMap R S s) * algebraMap R S f := by rw [map_mul, hys]
      _ = (z * algebraMap R S f) * algebraMap R S s := by ring
      _ = 0 := by rw [hz, zero_mul]
  obtain ⟨c, hc⟩ := (IsLocalization.map_eq_zero_iff (Submonoid.powers a) S (y * f)).mp h1
  have h2 : (c : R) * y = 0 :=
    (mem_nonZeroDivisors_iff.mp hf).2 _ (by rw [mul_assoc]; exact hc)
  have h3 : algebraMap R S (c : R) * algebraMap R S y = 0 := by
    rw [← map_mul, h2, map_zero]
  have hyz : algebraMap R S y = 0 :=
    ((IsLocalization.map_units S c).mul_right_eq_zero).mp h3
  rw [hyz] at hys
  exact ((IsLocalization.map_units S s).mul_left_eq_zero).mp hys

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- On the preimage in `V` of a basic open of the affine `V`, multiplication by a
generating nonzerodivisor `f` of the ideal is bijective onto the ideal sections. -/
theorem bijective_idealGenHom_app (V : C.affineOpens) (f : Γ(C, V.1))
    (hspan : J.ideal V = Ideal.span {f})
    (hnzd : f ∈ nonZeroDivisors Γ(C, V.1))
    (hfmem : f ∈ idealSections J (Opposite.op V.1))
    (b : Γ(C, V.1)) (hb : C.basicOpen b ≤ V.1) :
    Function.Bijective ((idealGenHom J V.1 f hfmem).val.app
      (Opposite.op (V.1.ι ⁻¹ᵁ C.basicOpen b))) := by
  have hWeq : V.1.ι ''ᵁ (V.1.ι ⁻¹ᵁ C.basicOpen b) = C.basicOpen b := by
    rw [Scheme.Hom.image_preimage_eq_opensRange_inf, Scheme.Opens.opensRange_ι,
      inf_eq_right.mpr hb]
  -- the span identification at the literal basic open, transported to the image
  have hbase : idealSections J (Opposite.op (C.basicOpen b)) =
      Ideal.span {C.presheaf.map (homOfLE hb).op f} := by
    have h1 : idealSections J (Opposite.op (C.basicOpen b)) =
        J.ideal (C.affineBasicOpen b) := J.ker_subschemeι_app (C.affineBasicOpen b)
    have h2 := J.map_ideal_basicOpen V b
    rw [hspan, Ideal.map_span, Set.image_singleton] at h2
    rw [h1, ← h2]
  -- the transport isomorphism onto the literal basic open
  have hφbij : Function.Bijective (C.presheaf.map ((eqToHom hWeq.symm).op :
      Opposite.op (V.1.ι ''ᵁ (V.1.ι ⁻¹ᵁ C.basicOpen b)) ⟶ Opposite.op (C.basicOpen b))) :=
    (ConcreteCategory.isIso_iff_bijective _).mp inferInstance
  -- the localization structure at the image
  letI halg : Algebra Γ(C, V.1) Γ(C, V.1.ι ''ᵁ (V.1.ι ⁻¹ᵁ C.basicOpen b)) :=
    (C.presheaf.map (homOfLE
      (V.1.ι_image_le (V.1.ι ⁻¹ᵁ C.basicOpen b))).op).hom.toAlgebra
  haveI hloc : IsLocalization.Away b
      Γ(C, V.1.ι ''ᵁ (V.1.ι ⁻¹ᵁ C.basicOpen b)) :=
    V.2.isLocalization_of_eq_basicOpen b
      (homOfLE (V.1.ι_image_le (V.1.ι ⁻¹ᵁ C.basicOpen b))) hWeq
  constructor
  · -- injective: cancel the nonzerodivisor generator after the appIso equivalence
    intro g g' hgg
    have hval := congrArg Subtype.val hgg
    have hsub : ((V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).inv g -
        (V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).inv g') *
        C.presheaf.map (homOfLE
          (V.1.ι_image_le (V.1.ι ⁻¹ᵁ C.basicOpen b))).op f = 0 := by
      have hval' : C.presheaf.map (homOfLE
            (V.1.ι_image_le (V.1.ι ⁻¹ᵁ C.basicOpen b))).op f *
          (V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).inv g =
          C.presheaf.map (homOfLE
            (V.1.ι_image_le (V.1.ι ⁻¹ᵁ C.basicOpen b))).op f *
          (V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).inv g' := hval
      rw [sub_mul, mul_comm, mul_comm ((V.1.ι.appIso
        (V.1.ι ⁻¹ᵁ C.basicOpen b)).inv g') _, hval', sub_self]
    have hz := away_mul_algebraMap_eq_zero (S := Γ(C, V.1.ι ''ᵁ
        (V.1.ι ⁻¹ᵁ C.basicOpen b))) b hnzd hsub
    have hinv : (V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).inv g =
        (V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).inv g' := by
      have := sub_eq_zero.mp hz
      exact this
    have hbijinv : Function.Bijective
        ((V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).inv) :=
      (ConcreteCategory.isIso_iff_bijective _).mp inferInstance
    exact hbijinv.injective hinv
  · -- surjective: divide by the generator via the span membership
    intro z
    have hzmem : C.presheaf.map ((eqToHom hWeq.symm).op) (z : idealSections J
          (Opposite.op (V.1.ι ''ᵁ (V.1.ι ⁻¹ᵁ C.basicOpen b)))).1 ∈
        idealSections J (Opposite.op (C.basicOpen b)) :=
      idealSections_map J ((eqToHom hWeq.symm).op) (z : idealSections J
        (Opposite.op (V.1.ι ''ᵁ (V.1.ι ⁻¹ᵁ C.basicOpen b)))).2
    rw [hbase] at hzmem
    obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp hzmem
    obtain ⟨c₀, hc₀⟩ := hφbij.surjective c
    refine ⟨(V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).hom c₀, ?_⟩
    refine Subtype.ext ?_
    -- reduce to an equation after the injective transport
    refine hφbij.injective ?_
    have hcoh : C.presheaf.map ((eqToHom hWeq.symm).op)
        (C.presheaf.map (homOfLE
          (V.1.ι_image_le (V.1.ι ⁻¹ᵁ C.basicOpen b))).op f) =
        C.presheaf.map (homOfLE hb).op f := by
      refine Eq.trans ?_ (congrArg (fun (t : _ ⟶ _) => C.presheaf.map t f)
        (Subsingleton.elim ((homOfLE
          (V.1.ι_image_le (V.1.ι ⁻¹ᵁ C.basicOpen b))).op ≫ (eqToHom hWeq.symm).op)
          (homOfLE hb).op))
      exact (congrArg (fun (t : _ ⟶ _) => (ConcreteCategory.hom t) f)
        (C.presheaf.map_comp (homOfLE
          (V.1.ι_image_le (V.1.ι ⁻¹ᵁ C.basicOpen b))).op (eqToHom hWeq.symm).op)).symm
    have hih : (V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).inv
        ((V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).hom c₀) = c₀ := by
      have := (V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).hom_inv_id
      exact congrArg (fun (t : _ ⟶ _) => (ConcreteCategory.hom t) c₀) this
    show C.presheaf.map ((eqToHom hWeq.symm).op)
        (C.presheaf.map (homOfLE (V.1.ι_image_le (V.1.ι ⁻¹ᵁ C.basicOpen b))).op f *
          (V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).inv
            ((V.1.ι.appIso (V.1.ι ⁻¹ᵁ C.basicOpen b)).hom c₀)) = _
    rw [map_mul, hcoh, hih, hc₀, mul_comm]
    exact hc

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- **AG-LB (KM 1.1.1 interface):** an ideal sheaf which is affine-locally generated by
a single nonzerodivisor is an invertible `𝒪_C`-module. The hypothesis is exactly the
`locallyPrincipal` field of `ModularCurves.IsOfficialCartier`. -/
theorem isInvertible_idealModule
    (h : ∀ c : ↥C, ∃ V : C.affineOpens, c ∈ V.1 ∧ ∃ f : Γ(C, V.1),
      J.ideal V = Ideal.span {f} ∧ f ∈ nonZeroDivisors Γ(C, V.1)) :
    IsInvertible (idealModule J) := by
  choose V hcV f hspan hnzd using h
  refine ⟨↥C, fun c => (V c).1, ?_, fun c => ?_⟩
  · rw [eq_top_iff]
    exact fun x _ => TopologicalSpace.Opens.mem_iSup.mpr ⟨x, hcV x⟩
  · have hfmem : f c ∈ idealSections J (Opposite.op (V c).1) := by
      rw [show idealSections J (Opposite.op (V c).1) = J.ideal (V c) from
        J.ker_subschemeι_app (V c), hspan c]
      exact Ideal.mem_span_singleton_self (f c)
    haveI : IsIso (idealGenHom J (V c).1 (f c) hfmem) := by
      refine isIso_of_bijective_app_on_basis _
        {W | ∃ (b : Γ(C, (V c).1)) (_ : C.basicOpen b ≤ (V c).1),
          W = (V c).1.ι ⁻¹ᵁ C.basicOpen b} ?_ ?_
      · intro x U hxU
        have hxV : (V c).1.ι.base x ∈ (V c).1 := x.2
        obtain ⟨b, hble, hxb⟩ := (V c).2.exists_basicOpen_le
          (V := (V c).1.ι ''ᵁ U) ⟨(V c).1.ι.base x, ⟨x, hxU, rfl⟩⟩ hxV
        refine ⟨(V c).1.ι ⁻¹ᵁ C.basicOpen b,
          ⟨b, hble.trans ((V c).1.ι_image_le U), rfl⟩, hxb, ?_⟩
        calc (V c).1.ι ⁻¹ᵁ C.basicOpen b
            ≤ (V c).1.ι ⁻¹ᵁ ((V c).1.ι ''ᵁ U) := by
              exact fun y hy => hble hy
          _ = U := Scheme.Hom.preimage_image_eq _ U
      · rintro W ⟨b, hb, rfl⟩
        exact bijective_idealGenHom_app J (V c) (f c) (hspan c) (hnzd c) hfmem b hb
    exact ⟨(restrictFunctorIsoPullback (V c).1.ι).symm.app (idealModule J) ≪≫
      (asIso (idealGenHom J (V c).1 (f c) hfmem)).symm⟩

end GenTriv

end AlgebraicGeometry.Scheme.Modules
