/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import ModularCurves.Picard.DivisorClass

/-!
# Pullback compatibility of ideal modules (naturality layer for (2.16))

The enabling leaf for the naturality of `sectionToPicRel` in the base `T` (making the
GME (2.16) assembly a morphism into `picRelFunctor`): the module pullback of an ideal
module along a base-change projection is the ideal module of the comap ideal. The
divisor-level statement is the engine's `RelEffCartierDiv.baseChange_ideal`
(`(D.baseChange t).ideal = D.ideal.comap (pullback.fst π t)`); this file records the
module-level comparison. Locally principal case only — the comparison multiplies the
local generator through, mirroring `bijective_idealGenHom_app`.

Statement-only skeleton (next-session execution per board v10.166).
-/

universe u

open CategoryTheory AlgebraicGeometry AlgebraicGeometry.Scheme
  AlgebraicGeometry.Scheme.Modules

namespace AlgebraicGeometry.Scheme.Modules

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- **Pullback of a locally principal ideal module** (KM 1.1.2 shape: effective Cartier
divisors pull back to effective Cartier divisors along base change, at the level of
ideal modules): if `J` is affine-locally generated by a single nonzerodivisor and its
comap along `f` is too, the module pullback of `idealModule J` is the ideal module of
the comap. -/
theorem nonempty_pullback_idealModule {X' X : Scheme.{u}} (f : X' ⟶ X)
    (J : X.IdealSheafData)
    (h : ∀ c : ↥X, ∃ V : X.affineOpens, c ∈ V.1 ∧ ∃ g : Γ(X, V.1),
      J.ideal V = Ideal.span {g} ∧ g ∈ nonZeroDivisors Γ(X, V.1))
    (h' : ∀ c : ↥X', ∃ V : X'.affineOpens, c ∈ V.1 ∧ ∃ g : Γ(X', V.1),
      (J.comap f).ideal V = Ideal.span {g} ∧ g ∈ nonZeroDivisors Γ(X', V.1)) :
    Nonempty ((Modules.pullback f).obj (idealModule J) ≅ idealModule (J.comap f)) := by
  sorry

end AlgebraicGeometry.Scheme.Modules
