/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import ModularCurves.Picard.DivisorClass

/-!
# Pullback compatibility of ideal modules (naturality layer for (2.16))

The enabling leaf for the naturality of `sectionToPicRel` in the base `T` (making the
GME (2.16) assembly a morphism into `picRelFunctor`): the module pullback of an ideal
module along a base-change projection is the ideal module of the comap ideal. The
divisor-level statement is the engine's `RelEffCartierDiv.baseChange_ideal`
(`(D.baseChange t).ideal = D.ideal.comap (pullback.fst π t)`); this file records the
module-level comparison. Locally principal case only — the comparison multiplies the
local generator through, mirroring `bijective_idealGenHom_app`.

Statement-only skeleton (next-session execution per board v10.166).
-/

universe u

open CategoryTheory AlgebraicGeometry AlgebraicGeometry.Scheme
  AlgebraicGeometry.Scheme.Modules

namespace AlgebraicGeometry.Scheme.Modules

variable {X' X : Scheme.{u}} (f : X' ⟶ X) (J : X.IdealSheafData)

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- A section of the ideal pulls back to a section of the comap ideal:
`fst♯ (f♯ g) = snd♯ (ι♯ g) = 0` by the pullback square defining the comap. -/
theorem app_mem_idealSections_comap (U : (TopologicalSpace.Opens ↥X)ᵒᵖ)
    {g : Γ(X, U.unop)} (hg : g ∈ idealSections J U) :
    f.app U.unop g ∈ idealSections (J.comap f)
      (Opposite.op ((TopologicalSpace.Opens.map f.base).obj U.unop)) := by
  refine RingHom.mem_ker.mpr ?_
  have hι : (J.comap f).subschemeι =
      (J.comapIso f).hom ≫ Limits.pullback.fst f J.subschemeι := by
    rw [← Scheme.IdealSheafData.comapIso_inv_subschemeι J f, ← Category.assoc,
      Iso.hom_inv_id, Category.id_comp]
  have hstep1 : ((Limits.pullback.fst f J.subschemeι ≫ f).app U.unop).hom g = 0 := by
    rw [Scheme.Hom.congr_app Limits.pullback.condition U.unop]
    have hz : ((Limits.pullback.snd f J.subschemeι ≫ J.subschemeι).app U.unop).hom g
        = 0 := by
      show ((Limits.pullback.snd f J.subschemeι).app _).hom
        ((J.subschemeι.app U.unop).hom g) = 0
      rw [RingHom.mem_ker.mp hg]
      exact map_zero _
    show ((Limits.pullback f J.subschemeι).presheaf.map _).hom
      (((Limits.pullback.snd f J.subschemeι ≫ J.subschemeι).app U.unop).hom g) = 0
    rw [hz]
    exact map_zero _
  rw [hι]
  show ((J.comapIso f).hom.app _).hom
    (((Limits.pullback.fst f J.subschemeι).app _).hom ((f.app U.unop).hom g)) = 0
  have h1 : ((Limits.pullback.fst f J.subschemeι).app _).hom
      ((f.app U.unop).hom g) = 0 := hstep1
  rw [h1]
  exact map_zero _

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- The canonical morphism from the ideal presheaf to the pushforward of the comap
ideal presheaf: componentwise `g ↦ f♯ g`. -/
noncomputable def idealPushHom :
    idealPresheaf J ⟶
      (PresheafOfModules.pushforward.{u} f.toRingCatSheafHom.hom).obj
        (idealPresheaf (J.comap f)) where
  app U := ModuleCat.ofHom
    (Y := ((PresheafOfModules.pushforward.{u} f.toRingCatSheafHom.hom).obj
      (idealPresheaf (J.comap f))).obj U)
    { toFun := fun g => ⟨f.app U.unop g.1, app_mem_idealSections_comap f J U g.2⟩
      map_add' := fun g g' => Subtype.ext (by
        show (f.app U.unop).hom (g.1 + g'.1) = _
        rw [map_add]
        rfl)
      map_smul' := fun r g => Subtype.ext (by
        let r' : Γ(X, U.unop) := r
        show (f.app U.unop).hom (r' * g.1) =
          (f.app U.unop).hom r' * (f.app U.unop).hom g.1
        exact map_mul _ r' g.1) }
  naturality {U V} i := by
    refine ModuleCat.hom_ext (LinearMap.ext fun g => ?_)
    refine Subtype.ext ?_
    show (f.app V.unop).hom ((X.presheaf.map i).hom g.1) =
      (X'.presheaf.map ((TopologicalSpace.Opens.map f.base).map i.unop).op).hom
        ((f.app U.unop).hom g.1)
    have h1 : (X'.presheaf.map ((TopologicalSpace.Opens.map f.base).map i.unop).op).hom
        ((f.app U.unop).hom g.1) =
        (ConcreteCategory.hom (f.app U.unop ≫
          X'.presheaf.map ((TopologicalSpace.Opens.map f.base).map i.unop).op)) g.1 := rfl
    have h2 : (f.app V.unop).hom ((X.presheaf.map i).hom g.1) =
        (ConcreteCategory.hom (X.presheaf.map i ≫ f.app V.unop)) g.1 := rfl
    rw [h1, h2]
    exact congrArg (fun (ψ : _ ⟶ _) => (ConcreteCategory.hom ψ) g.1)
      (f.naturality i)

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- **Pullback of a locally principal ideal module** (KM 1.1.2 shape: effective Cartier
divisors pull back to effective Cartier divisors along base change, at the level of
ideal modules): if `J` is affine-locally generated by a single nonzerodivisor and its
comap along `f` is too, the module pullback of `idealModule J` is the ideal module of
the comap. -/
theorem nonempty_pullback_idealModule {X' X : Scheme.{u}} (f : X' ⟶ X)
    (J : X.IdealSheafData)
    (h : ∀ c : ↥X, ∃ V : X.affineOpens, c ∈ V.1 ∧ ∃ g : Γ(X, V.1),
      J.ideal V = Ideal.span {g} ∧ g ∈ nonZeroDivisors Γ(X, V.1))
    (h' : ∀ c : ↥X', ∃ V : X'.affineOpens, c ∈ V.1 ∧ ∃ g : Γ(X', V.1),
      (J.comap f).ideal V = Ideal.span {g} ∧ g ∈ nonZeroDivisors Γ(X', V.1)) :
    Nonempty ((Modules.pullback f).obj (idealModule J) ≅ idealModule (J.comap f)) := by
  sorry

end AlgebraicGeometry.Scheme.Modules
