/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import ModularCurves.Picard.PrincipalIdealModuleIso

/-!
# A product of ideal sheaves is the tensor product of the ideal modules (T10-mult)

Let `JA`, `JB` be ideal sheaves on a scheme `C` cutting out effective Cartier divisors, and let
`JC` be an ideal sheaf which is, chart by chart, generated by the *product* of the two local
generators. Then multiplication of sections is an isomorphism of `𝒪_C`-modules

  `I(JA) ⊗_{𝒪_C} I(JB) ≅ I(JC)`.

This is what turns a *sum of divisors* into a *tensor product of invertible modules*, hence what
makes the chord-tangent identity `div (ℓ / z) = (P) + (Q) − (P+Q) − (O)` usable on the module
side.

## Main results

* `AlgebraicGeometry.Scheme.Modules.ProductDivisorData`: the local data — one affine cover with
  nonzerodivisor generators `genA i` of `JA`, `genB i` of `JB`, and the hypothesis that
  `genA i * genB i` generates `JC`.
* `ProductDivisorData.mulPre` / `.mulHom` / `.mulIso`: multiplication of sections, as a morphism
  of presheaves of modules, then of sheaves of modules, then as an isomorphism.
* `nonempty_tensorObj_idealModule_iso_of_productDivisorData`: the `Nonempty (… ≅ …)` form.
* `nonempty_tensorObj_idealModule_iso_mul`: the specialisation to `JC = JA * JB`, using
  `Scheme.IdealSheafData.ideal_mul` and `Ideal.span_singleton_mul_span_singleton`.

## How the proof goes

`tensorObj M N` is the sheafification of the presheaf tensor product, so it suffices to give a
morphism of *presheaves* of modules `I(JA).val ⊗ I(JB).val ⟶ I(JC).val` and to check that it is
bijective on every open inside a member of a cover — `sheafificationW_of_bijective_on_cover`
then inverts it after sheafification. The morphism is `a ⊗ b ↦ a * b`; that this lands in `JC` at
all is itself a local statement (`mul_mem_idealSections`, via `mem_idealSections_of_locally`).

On an open `W` inside `chart i` all three ideal sheaves are free of rank one:
`restrict_gen_nonZeroDivisors_and_surjective` says that `genA i |_W` is a nonzerodivisor and that
the sections of `I(JA)` over `W` are exactly its multiples, and likewise for `genB i` and for
`genA i * genB i`. So every element of the presheaf tensor is of the shape
`(genA i · z) ⊗ genB i` (`exists_eq_tmul_gen`), multiplication sends it to `(genA i genB i) · z`,
and both injectivity and surjectivity fall out of the nonzerodivisor cancellation.
-/

universe u

open CategoryTheory Opposite MonoidalCategory

namespace AlgebraicGeometry.Scheme.Modules

variable {C : Scheme.{u}} (JA JB JC : C.IdealSheafData)

/-- The commutative ring structure on the sections of the structure sheaf, spelled through
`ringCatSheaf` — the form in which the presheaf-of-modules tensor product needs it. Instance
search does not see through the `sheafCompose` in `Scheme.ringCatSheaf`, so it is registered by
hand, as a `local instance` of this file, for the `ModuleCat` monoidal constructions below. It is
`inferInstanceAs` of the structure sheaf's own `CommRing`, so no diamond is created. -/
@[instance_reducible]
noncomputable def sectionsCommRing (C : Scheme.{u}) (W : (TopologicalSpace.Opens ↥C)ᵒᵖ) :
    CommRing ↑(C.ringCatSheaf.obj.obj W) :=
  inferInstanceAs (CommRing ↑(C.presheaf.obj W))

attribute [local instance] sectionsCommRing

/-- **The local data exhibiting `JC` as the product `JA · JB`.**

On each member `chart i` of an affine cover, `JA` is generated by a nonzerodivisor `genA i`, `JB`
by a nonzerodivisor `genB i`, and `JC` by their product. (For `JC = JA * JB` these hypotheses are
automatic from the first two — see `productDivisorDataMul` — but stating the product ideal sheaf
abstractly is what the divisor consumers need, since they meet `JC` as the ideal of a divisor
that has been *computed* to be the sum.) -/
structure ProductDivisorData where
  /-- The index type of the trivialising affine cover. -/
  Idx : Type u
  /-- The trivialising affine cover. -/
  chart : Idx → C.affineOpens
  /-- The charts cover the scheme. -/
  chart_cover : ⨆ i, (chart i).1 = ⊤
  /-- The local equation of the first divisor on `chart i`. -/
  genA : ∀ i, Γ(C, (chart i).1)
  /-- The local equation of the second divisor on `chart i`. -/
  genB : ∀ i, Γ(C, (chart i).1)
  /-- `genA i` generates `JA` on `chart i`. -/
  span_genA : ∀ i, JA.ideal (chart i) = Ideal.span {genA i}
  /-- `genB i` generates `JB` on `chart i`. -/
  span_genB : ∀ i, JB.ideal (chart i) = Ideal.span {genB i}
  /-- `genA i` is a nonzerodivisor, i.e. the first divisor is Cartier. -/
  genA_nzd : ∀ i, genA i ∈ nonZeroDivisors Γ(C, (chart i).1)
  /-- `genB i` is a nonzerodivisor, i.e. the second divisor is Cartier. -/
  genB_nzd : ∀ i, genB i ∈ nonZeroDivisors Γ(C, (chart i).1)
  /-- `JC` is the product: on `chart i` it is generated by `genA i * genB i`. -/
  span_prod : ∀ i, JC.ideal (chart i) = Ideal.span {genA i * genB i}

namespace ProductDivisorData

variable {JA JB JC} (D : ProductDivisorData JA JB JC)

/-- The `i`-th piece of the induced cover of an open `V`. -/
def part (V : C.Opens) (i : D.Idx) : C.Opens := V ⊓ (D.chart i).1

theorem part_le (V : C.Opens) (i : D.Idx) : D.part V i ≤ V := inf_le_left

theorem part_le_chart (V : C.Opens) (i : D.Idx) : D.part V i ≤ (D.chart i).1 := inf_le_right

theorem le_iSup_part (V : C.Opens) : V ≤ ⨆ i, D.part V i := by
  intro x hx
  have hxT : x ∈ ⨆ i, (D.chart i).1 := by rw [D.chart_cover]; trivial
  obtain ⟨i, hi⟩ := TopologicalSpace.Opens.mem_iSup.mp hxT
  exact TopologicalSpace.Opens.mem_iSup.mpr ⟨i, hx, hi⟩

/-- The product of the two local generators is a nonzerodivisor. -/
theorem prod_nzd (i : D.Idx) :
    D.genA i * D.genB i ∈ nonZeroDivisors Γ(C, (D.chart i).1) :=
  mul_mem (D.genA_nzd i) (D.genB_nzd i)

/-- On an open inside a chart, every section of `JA` is a multiple of the restricted generator. -/
theorem exists_genA_mul {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) {s : Γ(C, W)}
    (hs : s ∈ idealSections JA (op W)) : ∃ x : Γ(C, W), (D.genA i |_ₗ W ⟪hW⟫) * x = s :=
  (restrict_gen_nonZeroDivisors_and_surjective (D.chart i) (D.genA i) (D.span_genA i)
    (D.genA_nzd i) hW).2 s hs

/-- On an open inside a chart, every section of `JB` is a multiple of the restricted generator. -/
theorem exists_genB_mul {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) {s : Γ(C, W)}
    (hs : s ∈ idealSections JB (op W)) : ∃ x : Γ(C, W), (D.genB i |_ₗ W ⟪hW⟫) * x = s :=
  (restrict_gen_nonZeroDivisors_and_surjective (D.chart i) (D.genB i) (D.span_genB i)
    (D.genB_nzd i) hW).2 s hs

/-- On an open inside a chart, every section of `JC` is a multiple of the restricted product. -/
theorem exists_prod_mul {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) {s : Γ(C, W)}
    (hs : s ∈ idealSections JC (op W)) :
    ∃ x : Γ(C, W), ((D.genA i * D.genB i) |_ₗ W ⟪hW⟫) * x = s :=
  (restrict_gen_nonZeroDivisors_and_surjective (D.chart i) (D.genA i * D.genB i)
    (D.span_prod i) (D.prod_nzd i) hW).2 s hs

/-- The restricted product of generators is a nonzerodivisor. -/
theorem prod_restrict_nzd {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) :
    ((D.genA i * D.genB i) |_ₗ W ⟪hW⟫) ∈ nonZeroDivisors Γ(C, W) :=
  (restrict_gen_nonZeroDivisors_and_surjective (D.chart i) (D.genA i * D.genB i)
    (D.span_prod i) (D.prod_nzd i) hW).1

/-- The restricted generator of `JA` is a section of `JA`. -/
theorem genA_mem {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) :
    (D.genA i |_ₗ W ⟪hW⟫) ∈ idealSections JA (op W) :=
  idealSections_map JA (homOfLE hW).op (mem_idealSections_of_span (D.span_genA i))

/-- The restricted generator of `JB` is a section of `JB`. -/
theorem genB_mem {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) :
    (D.genB i |_ₗ W ⟪hW⟫) ∈ idealSections JB (op W) :=
  idealSections_map JB (homOfLE hW).op (mem_idealSections_of_span (D.span_genB i))

/-- The restricted product of generators is a section of `JC`. -/
theorem prod_mem {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) :
    ((D.genA i * D.genB i) |_ₗ W ⟪hW⟫) ∈ idealSections JC (op W) :=
  idealSections_map JC (homOfLE hW).op (mem_idealSections_of_span (D.span_prod i))

include D in
/-- **Multiplication lands in `JC`.** The product of a section of `JA` and a section of `JB` over
an arbitrary open is a section of `JC` — checked chart by chart, where both factors are explicit
multiples of the local generators. -/
theorem mul_mem_idealSections {V : C.Opens} {a b : Γ(C, V)}
    (ha : a ∈ idealSections JA (op V)) (hb : b ∈ idealSections JB (op V)) :
    a * b ∈ idealSections JC (op V) := by
  refine mem_idealSections_of_locally (D.part V) (D.part_le V) (D.le_iSup_part V) (fun i => ?_)
  obtain ⟨x, hx⟩ : ∃ x : Γ(C, D.part V i),
      (D.genA i |_ₗ D.part V i ⟪D.part_le_chart V i⟫) * x =
        a |_ₗ D.part V i ⟪D.part_le V i⟫ :=
    D.exists_genA_mul i (D.part_le_chart V i)
      (idealSections_map JA (homOfLE (D.part_le V i)).op ha)
  obtain ⟨y, hy⟩ : ∃ y : Γ(C, D.part V i),
      (D.genB i |_ₗ D.part V i ⟪D.part_le_chart V i⟫) * y =
        b |_ₗ D.part V i ⟪D.part_le V i⟫ :=
    D.exists_genB_mul i (D.part_le_chart V i)
      (idealSections_map JB (homOfLE (D.part_le V i)).op hb)
  have key : ((a * b) |_ₗ D.part V i ⟪D.part_le V i⟫) =
      (x * y) * ((D.genA i * D.genB i) |_ₗ D.part V i ⟪D.part_le_chart V i⟫) := by
    rw [restrict_mul, ← hx, ← hy, restrict_mul]
    ring
  rw [key]
  exact Ideal.mul_mem_left _ _ (D.prod_mem i (D.part_le_chart V i))

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- **Multiplication of sections, as a morphism of presheaves of modules**
`I(JA) ⊗ I(JB) ⟶ I(JC)`. -/
noncomputable def mulPre :
    (idealModule JA).val ⊗ (idealModule JB).val ⟶ (idealModule JC).val where
  app W := ModuleCat.MonoidalCategory.tensorLift
    (M₃ := (idealModule JC).val.obj W)
    (fun a b => ⟨a.1 * b.1, D.mul_mem_idealSections a.2 b.2⟩)
    (fun a a' b => Subtype.ext (by show (a.1 + a'.1) * b.1 = a.1 * b.1 + a'.1 * b.1; ring))
    (fun r a b => Subtype.ext (mul_assoc r a.1 b.1))
    (fun a b b' => Subtype.ext (by show a.1 * (b.1 + b'.1) = a.1 * b.1 + a.1 * b'.1; ring))
    (fun r a b => Subtype.ext (mul_left_comm a.1 r b.1))
  naturality {W W'} f := ModuleCat.MonoidalCategory.tensor_ext (fun a b => by
    refine Subtype.ext ?_
    exact (map_mul (ConcreteCategory.hom (C.presheaf.map f)) a.1 b.1).symm)

section LocalTriv

variable {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1)

/-- The section `genA i · z` of the ideal sheaf `JA` over an open `W` inside `chart i`. -/
noncomputable def secA (z : Γ(C, W)) : ↑((idealModule JA).val.obj (op W)) :=
  ⟨(D.genA i |_ₗ W ⟪hW⟫) * z, Ideal.mul_mem_right _ _ (D.genA_mem i hW)⟩

/-- The generating section `genB i` of the ideal sheaf `JB` over an open `W` inside `chart i`. -/
noncomputable def secB : ↑((idealModule JB).val.obj (op W)) :=
  ⟨D.genB i |_ₗ W ⟪hW⟫, D.genB_mem i hW⟩

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- **Every element of the presheaf tensor product is a pure tensor** `(genA i · z) ⊗ genB i`,
on an open inside a chart: both factors are free of rank one there, so a general sum of pure
tensors collapses onto the single generator `secB` of the second factor. -/
theorem exists_secA_tmul_secB
    (t : ↑(((idealModule JA).val ⊗ (idealModule JB).val).obj (op W))) :
    ∃ z : Γ(C, W), (D.secA i hW z ⊗ₜ[↑(C.ringCatSheaf.obj.obj (op W))] D.secB i hW :
      ↑(((idealModule JA).val ⊗ (idealModule JB).val).obj (op W))) = t := by
  refine TensorProduct.induction_on t ⟨0, ?_⟩ (fun a b => ?_) ?_
  · refine Eq.trans (congrArg (fun s => s ⊗ₜ[↑(C.ringCatSheaf.obj.obj (op W))] D.secB i hW)
      (show D.secA i hW 0 = 0 from Subtype.ext (mul_zero _))) ?_
    exact TensorProduct.zero_tmul _ _
  · obtain ⟨x, hx⟩ : ∃ x : Γ(C, W), (D.genA i |_ₗ W ⟪hW⟫) * x = a.1 :=
      D.exists_genA_mul i hW a.2
    obtain ⟨y, hy⟩ : ∃ y : Γ(C, W), (D.genB i |_ₗ W ⟪hW⟫) * y = b.1 :=
      D.exists_genB_mul i hW b.2
    refine ⟨x * y, ?_⟩
    have hb : b = (show ↑(C.ringCatSheaf.obj.obj (op W)) from y) • D.secB i hW :=
      Subtype.ext (by show b.1 = y * (D.genB i |_ₗ W ⟪hW⟫); rw [← hy]; ring)
    have ha : D.secA i hW (x * y) =
        (show ↑(C.ringCatSheaf.obj.obj (op W)) from y) • a :=
      Subtype.ext (by show (D.genA i |_ₗ W ⟪hW⟫) * (x * y) = y * a.1; rw [← hx]; ring)
    rw [hb, ha]
    exact TensorProduct.smul_tmul _ _ _
  · rintro t₁ t₂ ⟨z₁, h₁⟩ ⟨z₂, h₂⟩
    refine ⟨z₁ + z₂, ?_⟩
    refine Eq.trans (congrArg (fun s => s ⊗ₜ[↑(C.ringCatSheaf.obj.obj (op W))] D.secB i hW)
      (show D.secA i hW (z₁ + z₂) = D.secA i hW z₁ + D.secA i hW z₂ from
        Subtype.ext (mul_add _ _ _))) ?_
    rw [TensorProduct.add_tmul, h₁, h₂]

/-- Cancelling the restricted product of generators. -/
theorem eq_of_mul_prod_eq {x y : Γ(C, W)}
    (h : x * ((D.genA i * D.genB i) |_ₗ W ⟪hW⟫) = y * ((D.genA i * D.genB i) |_ₗ W ⟪hW⟫)) :
    x = y := by
  refine sub_eq_zero.mp ((mem_nonZeroDivisors_iff.mp (D.prod_restrict_nzd i hW)).2 (x - y) ?_)
  rw [sub_mul, h, sub_self]

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- The value of the multiplication morphism on the normal form `(genA i · z) ⊗ genB i`. -/
theorem mulPre_app_secA_tmul_secB (z : Γ(C, W)) :
    (D.mulPre.app (op W)
        (D.secA i hW z ⊗ₜ[↑(C.ringCatSheaf.obj.obj (op W))] D.secB i hW)).1 =
      z * ((D.genA i * D.genB i) |_ₗ W ⟪hW⟫) := by
  show (D.genA i |_ₗ W ⟪hW⟫) * z * (D.genB i |_ₗ W ⟪hW⟫) = _
  rw [restrict_mul]
  ring

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
include hW in
/-- **The local computation.** On an open inside a chart all three ideal sheaves are free of rank
one, and multiplication `I(JA)(W) ⊗ I(JB)(W) → I(JC)(W)` is bijective: injective because the
product of the generators is a nonzerodivisor, surjective because it generates. -/
theorem bijective_mulPre_app : Function.Bijective (D.mulPre.app (op W)) := by
  constructor
  · intro t t' h
    obtain ⟨z, hz⟩ := D.exists_secA_tmul_secB i hW t
    obtain ⟨z', hz'⟩ := D.exists_secA_tmul_secB i hW t'
    have hval : z * ((D.genA i * D.genB i) |_ₗ W ⟪hW⟫) =
        z' * ((D.genA i * D.genB i) |_ₗ W ⟪hW⟫) := by
      rw [← D.mulPre_app_secA_tmul_secB i hW z, ← D.mulPre_app_secA_tmul_secB i hW z', hz, hz', h]
    rw [← hz, ← hz', D.eq_of_mul_prod_eq i hW hval]
  · intro s
    obtain ⟨x, hx⟩ : ∃ x : Γ(C, W), ((D.genA i * D.genB i) |_ₗ W ⟪hW⟫) * x = s.1 :=
      D.exists_prod_mul i hW s.2
    refine ⟨D.secA i hW x ⊗ₜ[↑(C.ringCatSheaf.obj.obj (op W))] D.secB i hW, Subtype.ext ?_⟩
    rw [D.mulPre_app_secA_tmul_secB i hW x, ← hx]
    ring

end LocalTriv

include D in
/-- Multiplication of sections is a local isomorphism, hence inverted by sheafification. -/
theorem sheafificationW_mulPre :
    PresheafOfModules.sheafificationW (𝟙 C.ringCatSheaf.obj) D.mulPre :=
  sheafificationW_of_bijective_on_cover D.mulPre (fun i => (D.chart i).1) D.chart_cover
    (fun i _W hW => D.bijective_mulPre_app i hW)

include D in
/-- The sheafification of the multiplication morphism is an isomorphism. -/
theorem isIso_sheafification_mulPre :
    IsIso ((PresheafOfModules.sheafification (𝟙 C.ringCatSheaf.obj)).map D.mulPre) := by
  have hw := D.sheafificationW_mulPre
  rwa [PresheafOfModules.sheafificationW_iff] at hw

/-- **Multiplication of sections, as a morphism of `𝒪_C`-modules**
`I(JA) ⊗_{𝒪_C} I(JB) ⟶ I(JC)`. -/
noncomputable def mulHom : tensorObj (idealModule JA) (idealModule JB) ⟶ idealModule JC :=
  (PresheafOfModules.sheafification (𝟙 C.ringCatSheaf.obj)).map D.mulPre ≫
    (sheafifyValIso (idealModule JC)).hom

/-- **The product of two ideal sheaves is the tensor product of their ideal modules.** -/
noncomputable def mulIso : tensorObj (idealModule JA) (idealModule JB) ≅ idealModule JC :=
  letI := D.isIso_sheafification_mulPre
  (asIso ((PresheafOfModules.sheafification (𝟙 C.ringCatSheaf.obj)).map D.mulPre)).trans
    (sheafifyValIso (idealModule JC))

/-- **Commutativity of the product.** Exchanging the two factors is again product data. -/
def symm : ProductDivisorData JB JA JC where
  Idx := D.Idx
  chart := D.chart
  chart_cover := D.chart_cover
  genA := D.genB
  genB := D.genA
  span_genA := D.span_genB
  span_genB := D.span_genA
  genA_nzd := D.genB_nzd
  genB_nzd := D.genA_nzd
  span_prod i := by rw [D.span_prod i, mul_comm]

include D in
/-- The first divisor is Cartier, so `I(JA)` is an invertible `𝒪_C`-module. -/
theorem isInvertible_idealModule_fst : IsInvertible (idealModule JA) := by
  refine isInvertible_idealModule _ (fun c => ?_)
  have hcT : c ∈ ⨆ i, (D.chart i).1 := by rw [D.chart_cover]; trivial
  obtain ⟨i, hi⟩ := TopologicalSpace.Opens.mem_iSup.mp hcT
  exact ⟨D.chart i, hi, D.genA i, D.span_genA i, D.genA_nzd i⟩

include D in
/-- The second divisor is Cartier, so `I(JB)` is an invertible `𝒪_C`-module. -/
theorem isInvertible_idealModule_snd : IsInvertible (idealModule JB) :=
  D.symm.isInvertible_idealModule_fst

include D in
/-- The sum of the two divisors is Cartier, so `I(JC)` is an invertible `𝒪_C`-module. -/
theorem isInvertible_idealModule_prod : IsInvertible (idealModule JC) := by
  refine isInvertible_idealModule _ (fun c => ?_)
  have hcT : c ∈ ⨆ i, (D.chart i).1 := by rw [D.chart_cover]; trivial
  obtain ⟨i, hi⟩ := TopologicalSpace.Opens.mem_iSup.mp hcT
  exact ⟨D.chart i, hi, D.genA i * D.genB i, D.span_prod i, D.prod_nzd i⟩

end ProductDivisorData

variable {JA JB JC}

/-- **A locally principal product of ideal sheaves is the tensor product of the ideal modules
(T10-mult).** This is what turns a sum of divisors into a tensor product of invertible modules. -/
theorem nonempty_tensorObj_idealModule_iso_of_productDivisorData
    (D : ProductDivisorData JA JB JC) :
    Nonempty (tensorObj (idealModule JA) (idealModule JB) ≅ idealModule JC) := ⟨D.mulIso⟩

/-- The reversed form of `nonempty_tensorObj_idealModule_iso_of_productDivisorData`. -/
theorem nonempty_idealModule_iso_tensorObj_of_productDivisorData
    (D : ProductDivisorData JA JB JC) :
    Nonempty (idealModule JC ≅ tensorObj (idealModule JA) (idealModule JB)) := ⟨D.mulIso.symm⟩

variable (JA JB) in
/-- **The product data for the honest product ideal sheaf `JA * JB`.** The `span_prod` field is
automatic: `Scheme.IdealSheafData.ideal_mul` computes the ideal of a product chart by chart, and
`Ideal.span_singleton_mul_span_singleton` multiplies the two principal ideals. -/
def productDivisorDataMul {Idx : Type u} (chart : Idx → C.affineOpens)
    (chart_cover : ⨆ i, (chart i).1 = ⊤) (genA genB : ∀ i, Γ(C, (chart i).1))
    (span_genA : ∀ i, JA.ideal (chart i) = Ideal.span {genA i})
    (span_genB : ∀ i, JB.ideal (chart i) = Ideal.span {genB i})
    (genA_nzd : ∀ i, genA i ∈ nonZeroDivisors Γ(C, (chart i).1))
    (genB_nzd : ∀ i, genB i ∈ nonZeroDivisors Γ(C, (chart i).1)) :
    ProductDivisorData JA JB (JA * JB) where
  Idx := Idx
  chart := chart
  chart_cover := chart_cover
  genA := genA
  genB := genB
  span_genA := span_genA
  span_genB := span_genB
  genA_nzd := genA_nzd
  genB_nzd := genB_nzd
  span_prod i := by
    rw [show (JA * JB).ideal (chart i) = JA.ideal (chart i) * JB.ideal (chart i) from by
      rw [Scheme.IdealSheafData.ideal_mul]; rfl, span_genA, span_genB,
      Ideal.span_singleton_mul_span_singleton]

/-- **`I(JA · JB) ≅ I(JA) ⊗ I(JB)` for the product of ideal sheaves.** Both factors are assumed
locally principal by nonzerodivisors on one common affine cover, which is exactly what the
Cartier condition supplies. -/
theorem nonempty_tensorObj_idealModule_iso_mul {Idx : Type u} (chart : Idx → C.affineOpens)
    (chart_cover : ⨆ i, (chart i).1 = ⊤) (genA genB : ∀ i, Γ(C, (chart i).1))
    (span_genA : ∀ i, JA.ideal (chart i) = Ideal.span {genA i})
    (span_genB : ∀ i, JB.ideal (chart i) = Ideal.span {genB i})
    (genA_nzd : ∀ i, genA i ∈ nonZeroDivisors Γ(C, (chart i).1))
    (genB_nzd : ∀ i, genB i ∈ nonZeroDivisors Γ(C, (chart i).1)) :
    Nonempty (tensorObj (idealModule JA) (idealModule JB) ≅ idealModule (JA * JB)) :=
  ⟨(productDivisorDataMul JA JB chart chart_cover genA genB span_genA span_genB genA_nzd
    genB_nzd).mulIso⟩

end AlgebraicGeometry.Scheme.Modules
