/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import Mathlib.AlgebraicGeometry.IdealSheaf.Subscheme
import ModularCurves.Picard.PicComparison

/-!
# The ideal sheaf of a closed subscheme as a module (API gap AG-LB)

For `J : C.IdealSheafData`, the ideal sheaf `I(J) ⊆ 𝒪_C` as a sheaf of `𝒪_C`-modules:
sections over an arbitrary open `U` are the kernel of the subscheme inclusion's component
`Γ(C, U) ⟶ Γ(J.subscheme, ι⁻¹U)` (at affine opens this is `J.ideal` by
`ker_subschemeι_app`). This is the module-side interface KM 1.1.1 needs ("the ideal
sheaf `I(D) ⊂ O_X` is an invertible `O_X`-module") — the invertibility from local
principality is `isInvertible_idealModule` below, closing the AG-LB gap for the
divisor engine of `LevelStructure/CartierDivisor.lean`.

## Main definitions

* `AlgebraicGeometry.Scheme.Modules.idealModule`: the ideal sheaf of `J` as an object
  of `C.Modules`.
* `AlgebraicGeometry.Scheme.Modules.isInvertible_idealModule`: on a scheme, an ideal
  sheaf which is affine-locally generated by a single nonzerodivisor is an invertible
  module.
-/

universe u

open CategoryTheory

namespace AlgebraicGeometry.Scheme.Modules

variable {C : Scheme.{u}} (J : C.IdealSheafData)

/-- The sections of the ideal sheaf over an arbitrary open `U`: the kernel of the
subscheme inclusion's component at `U`. -/
noncomputable def idealSections (U : (TopologicalSpace.Opens ↥C)ᵒᵖ) :
    Ideal Γ(C, U.unop) :=
  RingHom.ker (J.subschemeι.app U.unop).hom

/-- Restriction preserves the ideal sections (naturality of the inclusion). -/
theorem idealSections_map {U V : (TopologicalSpace.Opens ↥C)ᵒᵖ} (i : U ⟶ V)
    {g : Γ(C, U.unop)} (hg : g ∈ idealSections J U) :
    C.presheaf.map i g ∈ idealSections J V := by
  have hg' : (J.subschemeι.app U.unop).hom g = 0 := hg
  have hnat := J.subschemeι.naturality (show Opposite.op U.unop ⟶ Opposite.op V.unop from i)
  refine RingHom.mem_ker.mpr ?_
  have h1 : (J.subschemeι.app V.unop).hom (C.presheaf.map i g) =
      (J.subscheme.presheaf.map
          ((TopologicalSpace.Opens.map J.subschemeι.base).map i.unop).op).hom
        ((J.subschemeι.app U.unop).hom g) :=
    congrArg (fun (φ : _ ⟶ _) => (ConcreteCategory.hom φ) g) hnat
  rw [h1, hg', map_zero]

/-- The ideal sheaf of `J` as a presheaf of abelian groups: sections are
`idealSections`, restrictions those of the structure sheaf. -/
noncomputable def idealPresheafAb : (TopologicalSpace.Opens ↥C)ᵒᵖ ⥤ AddCommGrpCat.{u} where
  obj U := AddCommGrpCat.of (idealSections J U)
  map {U V} i := AddCommGrpCat.ofHom
    { toFun := fun g => ⟨C.presheaf.map i g.1, idealSections_map J i g.2⟩
      map_zero' := by
        refine Subtype.ext ?_
        exact map_zero (ConcreteCategory.hom (C.presheaf.map i))
      map_add' := fun g g' => by
        refine Subtype.ext ?_
        exact map_add (ConcreteCategory.hom (C.presheaf.map i)) g.1 g'.1 }
  map_id U := by
    ext g
    show C.presheaf.map (𝟙 U) g.1 = g.1
    rw [CategoryTheory.Functor.map_id]
    rfl
  map_comp {U V W} i j := by
    ext g
    show C.presheaf.map (i ≫ j) g.1 = C.presheaf.map j (C.presheaf.map i g.1)
    rw [Functor.map_comp]
    rfl

end AlgebraicGeometry.Scheme.Modules
