/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import ModularCurves.Picard.IdealModule

/-!
# A principal divisor trivialises the corresponding ideal module (T10-cmp-core)

Let `J₁`, `J₂` be ideal sheaves on a scheme `C`, cutting out effective Cartier divisors `D₁`,
`D₂`. If there is a rational function `f` with `div f = D₁ − D₂`, then multiplication by `f`
carries `I(D₂) = J₂` isomorphically onto `I(D₁) = J₁` as sheaves of `𝒪_C`-modules. This is the
one step mathlib does not have for `Scheme.Modules`, and it is what turns *linear equivalence
of divisors* into *isomorphism of the associated invertible modules* (hence `Cl C → Pic C`, and
the Abel-map identities for elliptic curves).

## The formulation

A rational function is not a global section of anything on a scheme, so "`div f = D₁ − D₂`" is
stated by its local content and nothing else: `PrincipalDivisorData J₁ J₂` packages an affine
cover `chart i`, generators `num i` of `J₁` and `den i` of `J₂` on `chart i` (nonzerodivisors,
i.e. `D₁`, `D₂` are Cartier), and the **cocycle identity**

  `num i * den j = num j * den i`  on  `chart i ⊓ chart j`,

which is exactly "the local ratios `num i / den i` are one and the same rational function `f`",
cross-multiplied so that no function field or total quotient sheaf has to be constructed. This
keeps the statement valid on an arbitrary scheme — no integrality, separatedness, Noetherian or
curve hypothesis is used anywhere. (If `C` *is* integral and `f` lives in `C.functionField`,
the cocycle identity is the image of `f = num i / den i` under the injection
`Γ(C, chart i ⊓ chart j) ↪ K(C)`.)

## Main results

* `AlgebraicGeometry.Scheme.Modules.PrincipalDivisorData`: the local presentation of a rational
  function `f` with `div f = D₁ − D₂`.
* `AlgebraicGeometry.Scheme.Modules.PrincipalDivisorData.mulHom` / `.mulIso`: multiplication by
  `f`, as a morphism and then as an isomorphism `idealModule J₂ ≅ idealModule J₁`.
* `AlgebraicGeometry.Scheme.Modules.nonempty_idealModule_iso_of_principalDivisorData`: the
  `Nonempty (… ≅ …)` form, and `nonempty_tensorObj_idealModule_iso_of_principalDivisorData` its
  tensor version.
* `PrincipalDivisorData.isInvertible_idealModule_fst` / `.isInvertible_idealModule_snd`: both
  ideal modules are invertible, which is what the skeleton cancellation in
  `Picard/PicComparison.lean` needs.

Two by-products of independent interest, both about a single ideal sheaf:

* `restrict_gen_nonZeroDivisors_and_surjective`: a nonzerodivisor generator on an affine open
  stays a nonzerodivisor, and stays a generator, on *every* smaller open — not just on basic
  opens, which is all `bijective_idealGenHom_app` gives directly.
* `mem_idealSections_of_locally`: lying in an ideal sheaf is a local condition on sections.

## How the proof goes

`f` itself is never constructed. Instead the product `t = f · s` of a section `s` of `J₂` over
an arbitrary open `V` is *characterised* by the equations

  `t * den i = s * num i`  on  `V ⊓ chart i`   (`PrincipalDivisorData.IsMul`),

which determine `t` uniquely because each `den i` restricts to a nonzerodivisor
(`restrict_gen_nonZeroDivisors_and_surjective`, the component-wise upgrade of `idealGenHom`
being an isomorphism), and which produce `t` by gluing the local products `num i * xᵢ`, where
`s = den i * xᵢ` on `V ⊓ chart i`. Additivity, `𝒪_C`-linearity and naturality of `s ↦ t` are then
immediate from the uniqueness clause, and bijectivity on *every* open — no cover argument
needed — comes from running the same construction for `f⁻¹` (`PrincipalDivisorData.symm`).
-/

universe u

open CategoryTheory Opposite

namespace AlgebraicGeometry.Scheme.Modules

variable {C : Scheme.{u}}

/-- A generator of `J.ideal U` is a section of the ideal sheaf over `U`. -/
theorem mem_idealSections_of_span {J : C.IdealSheafData} {U : C.affineOpens} {r : Γ(C, U.1)}
    (hspan : J.ideal U = Ideal.span {r}) : r ∈ idealSections J (op U.1) := by
  rw [show idealSections J (op U.1) = J.ideal U from J.ker_subschemeι_app U, hspan]
  exact Ideal.mem_span_singleton_self r

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- On an affine open where the ideal sheaf is generated by a single nonzerodivisor,
multiplication by that generator is an isomorphism from the structure sheaf onto the
restricted ideal module. (This is the isomorphism used inside `isInvertible_idealModule`,
extracted so that its *component-wise* consequences are available.) -/
theorem isIso_idealGenHom {J : C.IdealSheafData} (U : C.affineOpens) (r : Γ(C, U.1))
    (hspan : J.ideal U = Ideal.span {r}) (hnzd : r ∈ nonZeroDivisors Γ(C, U.1)) :
    IsIso (idealGenHom J U.1 r (mem_idealSections_of_span hspan)) := by
  refine isIso_of_bijective_app_on_basis _
    {W | ∃ (b : Γ(C, U.1)) (_ : C.basicOpen b ≤ U.1), W = U.1.ι ⁻¹ᵁ C.basicOpen b} ?_ ?_
  · intro x V hxV
    have hxU : U.1.ι.base x ∈ U.1 := x.2
    obtain ⟨b, hble, hxb⟩ := U.2.exists_basicOpen_le
      (V := U.1.ι ''ᵁ V) ⟨U.1.ι.base x, ⟨x, hxV, rfl⟩⟩ hxU
    refine ⟨U.1.ι ⁻¹ᵁ C.basicOpen b, ⟨b, hble.trans (U.1.ι_image_le V), rfl⟩, hxb, ?_⟩
    calc U.1.ι ⁻¹ᵁ C.basicOpen b
        ≤ U.1.ι ⁻¹ᵁ (U.1.ι ''ᵁ V) := fun y hy => hble hy
      _ = V := Scheme.Hom.preimage_image_eq _ V
  · rintro W ⟨b, hb, rfl⟩
    exact bijective_idealGenHom_app J U r hspan hnzd (mem_idealSections_of_span hspan) b hb

/-- Restriction of a section is multiplicative. -/
theorem restrict_mul {A B : C.Opens} (h : B ≤ A) (x y : Γ(C, A)) :
    ((x * y) |_ₗ B ⟪h⟫) = (x |_ₗ B ⟪h⟫) * (y |_ₗ B ⟪h⟫) :=
  map_mul (ConcreteCategory.hom (C.presheaf.map (homOfLE h).op)) x y

/-- Restriction of a section is additive. -/
theorem restrict_add {A B : C.Opens} (h : B ≤ A) (x y : Γ(C, A)) :
    ((x + y) |_ₗ B ⟪h⟫) = (x |_ₗ B ⟪h⟫) + (y |_ₗ B ⟪h⟫) :=
  map_add (ConcreteCategory.hom (C.presheaf.map (homOfLE h).op)) x y

/-- Restriction of a section preserves zero. -/
theorem restrict_zero {A B : C.Opens} (h : B ≤ A) : ((0 : Γ(C, A)) |_ₗ B ⟪h⟫) = 0 :=
  map_zero (ConcreteCategory.hom (C.presheaf.map (homOfLE h).op))

/-- Transitivity of restriction, restated in the explicit-proof notation `|_ₗ _ ⟪_⟫` so that it
rewrites there. The content is mathlib's `TopCat.Presheaf.restrict_restrict`. -/
theorem restrict_restrict' {A B D : C.Opens} (h1 : B ≤ A) (h2 : D ≤ B) (x : Γ(C, A)) :
    ((x |_ₗ B ⟪h1⟫) |_ₗ D ⟪h2⟫) = x |_ₗ D ⟪h2.trans h1⟫ :=
  TopCat.Presheaf.restrict_restrict h2 h1 x

/-- Restricting along an equality of opens and back is the identity. -/
theorem restrict_restrict_of_eq {A B : C.Opens} (h : A = B) (x : Γ(C, A)) :
    ((x |_ₗ B ⟪h.ge⟫) |_ₗ A ⟪h.le⟫) = x :=
  (TopCat.Presheaf.restrict_restrict h.le h.ge x).trans (TopCat.Presheaf.restrict_self x)

variable {J : C.IdealSheafData}

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- The component of `idealGenHom` at an open of the affine chart, read in *ambient*
coordinates: multiplication by the restricted generator is injective, and hits exactly the
ideal sections. -/
private theorem gen_mul_bijective_image (U : C.affineOpens) (r : Γ(C, U.1))
    (hspan : J.ideal U = Ideal.span {r}) (hnzd : r ∈ nonZeroDivisors Γ(C, U.1))
    (W' : U.1.toScheme.Opens) :
    (∀ c c' : Γ(C, U.1.ι ''ᵁ W'), (r |_ₗ (U.1.ι ''ᵁ W') ⟪U.1.ι_image_le W'⟫) * c =
        (r |_ₗ (U.1.ι ''ᵁ W') ⟪U.1.ι_image_le W'⟫) * c' → c = c') ∧
      ∀ s ∈ idealSections J (op (U.1.ι ''ᵁ W')), ∃ c : Γ(C, U.1.ι ''ᵁ W'),
        (r |_ₗ (U.1.ι ''ᵁ W') ⟪U.1.ι_image_le W'⟫) * c = s := by
  haveI := isIso_idealGenHom U r hspan hnzd
  have hbij := (ConcreteCategory.isIso_iff_bijective
    ((idealGenHom J U.1 r (mem_idealSections_of_span hspan)).app W')).mp inferInstance
  have hform : ∀ g : Γ(U.1.toScheme, W'),
      (ConcreteCategory.hom
          (Hom.app (idealGenHom J U.1 r (mem_idealSections_of_span hspan)) W') g :
            idealSections J (op (U.1.ι ''ᵁ W'))).1 =
        (r |_ₗ (U.1.ι ''ᵁ W') ⟪U.1.ι_image_le W'⟫) * (U.1.ι.appIso W').inv g :=
    fun _ => rfl
  have hinv : ∀ c : Γ(C, U.1.ι ''ᵁ W'),
      (U.1.ι.appIso W').inv ((U.1.ι.appIso W').hom c) = c := fun c =>
    congrArg (fun t : _ ⟶ _ => (ConcreteCategory.hom t) c) (U.1.ι.appIso W').hom_inv_id
  refine ⟨fun c c' hcc => ?_, fun s hs => ?_⟩
  · have h1 : ConcreteCategory.hom
        (Hom.app (idealGenHom J U.1 r (mem_idealSections_of_span hspan)) W')
          ((U.1.ι.appIso W').hom c) =
        ConcreteCategory.hom
          (Hom.app (idealGenHom J U.1 r (mem_idealSections_of_span hspan)) W')
          ((U.1.ι.appIso W').hom c') := by
      refine Subtype.ext ?_
      rw [hform, hform, hinv, hinv]
      exact hcc
    calc c = (U.1.ι.appIso W').inv ((U.1.ι.appIso W').hom c) := (hinv c).symm
      _ = (U.1.ι.appIso W').inv ((U.1.ι.appIso W').hom c') := by rw [hbij.injective h1]
      _ = c' := hinv c'
  · obtain ⟨g, hg⟩ := hbij.surjective (⟨s, hs⟩ : idealSections J (op (U.1.ι ''ᵁ W')))
    exact ⟨(U.1.ι.appIso W').inv g, (hform g).symm.trans (congrArg Subtype.val hg)⟩

/-- Restriction along an equality of opens is injective. -/
theorem restrict_injective_of_eq {A B : C.Opens} (h : A = B) :
    Function.Injective (fun x : Γ(C, A) => (x |_ₗ B ⟪h.ge⟫)) := by
  intro x y hxy
  have hxy' := congrArg (fun z : Γ(C, B) => (z |_ₗ A ⟪h.le⟫)) hxy
  rw [restrict_restrict_of_eq h, restrict_restrict_of_eq h] at hxy'
  exact hxy'

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- **The local engine.** Let `r` be a nonzerodivisor generating the ideal sheaf `J` on an
affine open `U`. Then on *every* open `W ≤ U` the restricted generator is again a
nonzerodivisor, and the ideal sections over `W` are exactly its multiples.

Both halves come from the fact that `idealGenHom` is an isomorphism of sheaves (not merely
bijective on basic opens): its components at all opens are bijective. -/
theorem restrict_gen_nonZeroDivisors_and_surjective (U : C.affineOpens) (r : Γ(C, U.1))
    (hspan : J.ideal U = Ideal.span {r}) (hnzd : r ∈ nonZeroDivisors Γ(C, U.1))
    {W : C.Opens} (hW : W ≤ U.1) :
    (r |_ₗ W ⟪hW⟫) ∈ nonZeroDivisors Γ(C, W) ∧
      ∀ s ∈ idealSections J (op W), ∃ x : Γ(C, W), (r |_ₗ W ⟪hW⟫) * x = s := by
  have hWeq : U.1.ι ''ᵁ (U.1.ι ⁻¹ᵁ W) = W := by
    rw [Scheme.Hom.image_preimage_eq_opensRange_inf, Scheme.Opens.opensRange_ι,
      inf_eq_right.mpr hW]
  obtain ⟨hinj, hsurj⟩ := gen_mul_bijective_image U r hspan hnzd (U.1.ι ⁻¹ᵁ W)
  have hgen : ((r |_ₗ W ⟪hW⟫) |_ₗ (U.1.ι ''ᵁ (U.1.ι ⁻¹ᵁ W)) ⟪hWeq.le⟫) =
      r |_ₗ (U.1.ι ''ᵁ (U.1.ι ⁻¹ᵁ W)) ⟪U.1.ι_image_le _⟫ := restrict_restrict' _ _ r
  constructor
  · have key : ∀ x : Γ(C, W), (r |_ₗ W ⟪hW⟫) * x = 0 → x = 0 := by
      intro x hx
      refine restrict_injective_of_eq hWeq.symm ?_
      refine hinj _ _ ?_
      show _ * ((x : Γ(C, W)) |_ₗ _ ⟪hWeq.le⟫) = _ * ((0 : Γ(C, W)) |_ₗ _ ⟪hWeq.le⟫)
      rw [restrict_zero, mul_zero, ← hgen, ← restrict_mul, hx, restrict_zero]
    exact mem_nonZeroDivisors_iff.mpr ⟨key, fun x hx => key x (by rw [mul_comm]; exact hx)⟩
  · intro s hs
    obtain ⟨c, hc⟩ := hsurj (s |_ₗ _ ⟪hWeq.le⟫)
      (idealSections_map J (homOfLE hWeq.le).op hs)
    refine ⟨c |_ₗ W ⟪hWeq.ge⟫, ?_⟩
    have hres := congrArg (fun z : Γ(C, U.1.ι ''ᵁ (U.1.ι ⁻¹ᵁ W)) => (z |_ₗ W ⟪hWeq.ge⟫)) hc
    rw [restrict_mul, restrict_restrict', restrict_restrict_of_eq hWeq.symm] at hres
    exact hres

/-- **Membership in the ideal sections is a local condition.** (The ideal sheaf is the kernel
of a map of sheaves, so vanishing may be tested on germs; this is the section-level form of
`idealSubfunctor_isSheaf`.) -/
theorem mem_idealSections_of_locally {V : C.Opens} {κ : Type*} (W : κ → C.Opens)
    (hle : ∀ i, W i ≤ V) (hcover : V ≤ ⨆ i, W i) {t : Γ(C, V)}
    (h : ∀ i, (t |_ₗ W i ⟪hle i⟫) ∈ idealSections J (op (W i))) :
    t ∈ idealSections J (op V) := by
  refine RingHom.mem_ker.mpr ?_
  refine TopCat.Presheaf.section_ext J.subscheme.sheaf _ _ _ (fun y hy => ?_)
  obtain ⟨i, hi⟩ := TopologicalSpace.Opens.mem_iSup.mp (hcover hy)
  have hi' : y ∈ J.subschemeι ⁻¹ᵁ W i := hi
  have hnat : J.subscheme.presheaf.map
        ((TopologicalSpace.Opens.map J.subschemeι.base).map (homOfLE (hle i))).op
        ((J.subschemeι.app V).hom t) =
      (J.subschemeι.app (W i)).hom (t |_ₗ W i ⟪hle i⟫) :=
    (congrArg (fun (φ : _ ⟶ _) => (ConcreteCategory.hom φ) t)
      (J.subschemeι.naturality (homOfLE (hle i)).op)).symm
  calc J.subscheme.presheaf.germ (J.subschemeι ⁻¹ᵁ V) y hy ((J.subschemeι.app V).hom t)
      = J.subscheme.presheaf.germ (J.subschemeι ⁻¹ᵁ W i) y hi'
          (J.subscheme.presheaf.map
            ((TopologicalSpace.Opens.map J.subschemeι.base).map (homOfLE (hle i))).op
            ((J.subschemeι.app V).hom t)) :=
        (J.subscheme.presheaf.germ_res_apply
          ((TopologicalSpace.Opens.map J.subschemeι.base).map (homOfLE (hle i))) y hi' _).symm
    _ = J.subscheme.presheaf.germ (J.subschemeι ⁻¹ᵁ W i) y hi'
          ((J.subschemeι.app (W i)).hom (t |_ₗ W i ⟪hle i⟫)) := congrArg _ hnat
    _ = 0 := by rw [RingHom.mem_ker.mp (h i)]; exact map_zero _
    _ = J.subscheme.presheaf.germ (J.subschemeι ⁻¹ᵁ V) y hy 0 := (map_zero _).symm

/-! ## Principal divisors, presented by local equations -/

variable (J₁ J₂ : C.IdealSheafData)

/-- **The local data of a rational function `f` with `div f = D₁ − D₂`**, where `D₁` and `D₂`
are the effective divisors cut out by the ideal sheaves `J₁` and `J₂`.

On each member `chart i` of an affine cover, `J₁` is generated by a nonzerodivisor `num i` and
`J₂` by a nonzerodivisor `den i`; so on that chart `D₁ = div (num i)` and `D₂ = div (den i)`.
The `cocycle` field says the local ratios `num i / den i` agree on overlaps (cross-multiplied,
so that no total quotient ring is needed). Hence they patch to a single rational function `f`
with `div f = D₁ − D₂`, and multiplication by `f` carries `I(D₂)` onto `I(D₁)`. -/
structure PrincipalDivisorData where
  /-- The index type of the trivialising affine cover. -/
  Idx : Type u
  /-- The trivialising affine cover. -/
  chart : Idx → C.affineOpens
  /-- The charts cover the scheme. -/
  chart_cover : ⨆ i, (chart i).1 = ⊤
  /-- The local equation of `D₁` on `chart i`: the numerator of `f`. -/
  num : ∀ i, Γ(C, (chart i).1)
  /-- The local equation of `D₂` on `chart i`: the denominator of `f`. -/
  den : ∀ i, Γ(C, (chart i).1)
  /-- `num i` generates `J₁` on `chart i`. -/
  span_num : ∀ i, J₁.ideal (chart i) = Ideal.span {num i}
  /-- `den i` generates `J₂` on `chart i`. -/
  span_den : ∀ i, J₂.ideal (chart i) = Ideal.span {den i}
  /-- `num i` is a nonzerodivisor, i.e. `D₁` is a Cartier divisor. -/
  num_nzd : ∀ i, num i ∈ nonZeroDivisors Γ(C, (chart i).1)
  /-- `den i` is a nonzerodivisor, i.e. `D₂` is a Cartier divisor. -/
  den_nzd : ∀ i, den i ∈ nonZeroDivisors Γ(C, (chart i).1)
  /-- The local ratios agree on overlaps: `num i / den i = num j / den j`. -/
  cocycle : ∀ i j, (num i |_ₗ (chart i).1 ⊓ (chart j).1 ⟪inf_le_left⟫) *
      (den j |_ₗ (chart i).1 ⊓ (chart j).1 ⟪inf_le_right⟫) =
    (num j |_ₗ (chart i).1 ⊓ (chart j).1 ⟪inf_le_right⟫) *
      (den i |_ₗ (chart i).1 ⊓ (chart j).1 ⟪inf_le_left⟫)

namespace PrincipalDivisorData

variable {J₁ J₂} (D : PrincipalDivisorData J₁ J₂)

/-- The `i`-th piece of the induced cover of an open `V`. -/
def part (V : C.Opens) (i : D.Idx) : C.Opens := V ⊓ (D.chart i).1

theorem part_le (V : C.Opens) (i : D.Idx) : D.part V i ≤ V := inf_le_left

theorem part_le_chart (V : C.Opens) (i : D.Idx) : D.part V i ≤ (D.chart i).1 := inf_le_right

theorem le_iSup_part (V : C.Opens) : V ≤ ⨆ i, D.part V i := by
  intro x hx
  have hxT : x ∈ ⨆ i, (D.chart i).1 := by rw [D.chart_cover]; trivial
  obtain ⟨i, hi⟩ := TopologicalSpace.Opens.mem_iSup.mp hxT
  exact TopologicalSpace.Opens.mem_iSup.mpr ⟨i, hx, hi⟩

/-- **Inverting `f`.** The same cover and local equations with numerator and denominator
exchanged: the data of `f⁻¹`, whose divisor is `D₂ − D₁`. -/
def symm : PrincipalDivisorData J₂ J₁ where
  Idx := D.Idx
  chart := D.chart
  chart_cover := D.chart_cover
  num := D.den
  den := D.num
  span_num := D.span_den
  span_den := D.span_num
  num_nzd := D.den_nzd
  den_nzd := D.num_nzd
  cocycle i j := (mul_comm _ _).trans ((D.cocycle i j).symm.trans (mul_comm _ _))

/-- A restricted denominator is still a nonzerodivisor. -/
theorem den_restrict_nzd {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) :
    (D.den i |_ₗ W ⟪hW⟫) ∈ nonZeroDivisors Γ(C, W) :=
  (restrict_gen_nonZeroDivisors_and_surjective (D.chart i) (D.den i) (D.span_den i)
    (D.den_nzd i) hW).1

/-- Cancelling a restricted denominator. -/
theorem eq_of_mul_den_eq {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) {x y : Γ(C, W)}
    (h : x * (D.den i |_ₗ W ⟪hW⟫) = y * (D.den i |_ₗ W ⟪hW⟫)) : x = y := by
  refine sub_eq_zero.mp ((mem_nonZeroDivisors_iff.mp (D.den_restrict_nzd i hW)).2 (x - y) ?_)
  rw [sub_mul, h, sub_self]

/-- A restricted numerator is still a nonzerodivisor. -/
theorem num_restrict_nzd {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) :
    (D.num i |_ₗ W ⟪hW⟫) ∈ nonZeroDivisors Γ(C, W) := D.symm.den_restrict_nzd i hW

/-- Cancelling a restricted numerator. -/
theorem eq_of_mul_num_eq {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) {x y : Γ(C, W)}
    (h : x * (D.num i |_ₗ W ⟪hW⟫) = y * (D.num i |_ₗ W ⟪hW⟫)) : x = y :=
  D.symm.eq_of_mul_den_eq i hW h

/-- Every section of `J₂` over an open inside a chart is a multiple of the denominator. -/
theorem exists_den_mul {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) {s : Γ(C, W)}
    (hs : s ∈ idealSections J₂ (op W)) : ∃ x : Γ(C, W), (D.den i |_ₗ W ⟪hW⟫) * x = s :=
  (restrict_gen_nonZeroDivisors_and_surjective (D.chart i) (D.den i) (D.span_den i)
    (D.den_nzd i) hW).2 s hs

/-- The restricted numerator is a section of `J₁`. -/
theorem num_mem {W : C.Opens} (i : D.Idx) (hW : W ≤ (D.chart i).1) :
    (D.num i |_ₗ W ⟪hW⟫) ∈ idealSections J₁ (op W) :=
  idealSections_map J₁ (homOfLE hW).op (mem_idealSections_of_span (D.span_num i))

/-- `D.IsMul V s t` says that `t = f · s` over `V`, expressed without ever forming `f`: on each
chart piece, `t · den i = s · num i`. -/
def IsMul (V : C.Opens) (s t : Γ(C, V)) : Prop :=
  ∀ i, (t |_ₗ D.part V i ⟪D.part_le V i⟫) * (D.den i |_ₗ D.part V i ⟪D.part_le_chart V i⟫) =
    (s |_ₗ D.part V i ⟪D.part_le V i⟫) * (D.num i |_ₗ D.part V i ⟪D.part_le_chart V i⟫)

/-- Multiplication by `f` is single valued. -/
theorem isMul_unique {V : C.Opens} {s t t' : Γ(C, V)} (h : D.IsMul V s t)
    (h' : D.IsMul V s t') : t = t' := by
  refine C.sheaf.eq_of_locally_eq' (D.part V) V (fun i => homOfLE (D.part_le V i))
    (D.le_iSup_part V) t t' (fun i => ?_)
  exact D.eq_of_mul_den_eq i (D.part_le_chart V i) ((h i).trans (h' i).symm)

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- **The gluing datum is compatible.** The local products `num i · xᵢ` agree on overlaps: this
is where the cocycle condition (and the cancellability of `den j`) is used. -/
private theorem isMul_compat {V : C.Opens} (s : Γ(C, V)) (i j : D.Idx)
    (x : Γ(C, D.part V i)) (y : Γ(C, D.part V j))
    (hx : (D.den i |_ₗ D.part V i ⟪D.part_le_chart V i⟫) * x =
      s |_ₗ D.part V i ⟪D.part_le V i⟫)
    (hy : (D.den j |_ₗ D.part V j ⟪D.part_le_chart V j⟫) * y =
      s |_ₗ D.part V j ⟪D.part_le V j⟫) :
    (((D.num i |_ₗ D.part V i ⟪D.part_le_chart V i⟫) * x) |_ₗ
        D.part V i ⊓ D.part V j ⟪inf_le_left⟫) =
      (((D.num j |_ₗ D.part V j ⟪D.part_le_chart V j⟫) * y) |_ₗ
        D.part V i ⊓ D.part V j ⟪inf_le_right⟫) := by
  have hWi : D.part V i ⊓ D.part V j ≤ D.part V i := inf_le_left
  have hWj : D.part V i ⊓ D.part V j ≤ D.part V j := inf_le_right
  have hWci : D.part V i ⊓ D.part V j ≤ (D.chart i).1 := hWi.trans (D.part_le_chart V i)
  have hWcj : D.part V i ⊓ D.part V j ≤ (D.chart j).1 := hWj.trans (D.part_le_chart V j)
  have hWV : D.part V i ⊓ D.part V j ≤ V := hWi.trans (D.part_le V i)
  have hcoc : (D.num i |_ₗ _ ⟪hWci⟫) * (D.den j |_ₗ _ ⟪hWcj⟫) =
      (D.num j |_ₗ _ ⟪hWcj⟫) * (D.den i |_ₗ _ ⟪hWci⟫) := by
    have h := congrArg (fun z : Γ(C, (D.chart i).1 ⊓ (D.chart j).1) =>
      (z |_ₗ D.part V i ⊓ D.part V j ⟪le_inf hWci hWcj⟫)) (D.cocycle i j)
    simp only [restrict_mul, restrict_restrict'] at h
    exact h
  have hxW : (D.den i |_ₗ _ ⟪hWci⟫) * (x |_ₗ _ ⟪hWi⟫) = s |_ₗ _ ⟪hWV⟫ := by
    have h := congrArg (fun z : Γ(C, D.part V i) => (z |_ₗ _ ⟪hWi⟫)) hx
    simp only [restrict_mul, restrict_restrict'] at h
    exact h
  have hyW : (D.den j |_ₗ _ ⟪hWcj⟫) * (y |_ₗ _ ⟪hWj⟫) = s |_ₗ _ ⟪hWV⟫ := by
    have h := congrArg (fun z : Γ(C, D.part V j) => (z |_ₗ _ ⟪hWj⟫)) hy
    simp only [restrict_mul, restrict_restrict'] at h
    exact h
  refine D.eq_of_mul_den_eq j hWcj ?_
  simp only [restrict_mul, restrict_restrict']
  calc (D.num i |_ₗ _ ⟪hWci⟫) * (x |_ₗ _ ⟪hWi⟫) * (D.den j |_ₗ _ ⟪hWcj⟫)
      = ((D.num i |_ₗ _ ⟪hWci⟫) * (D.den j |_ₗ _ ⟪hWcj⟫)) * (x |_ₗ _ ⟪hWi⟫) := by ring
    _ = ((D.num j |_ₗ _ ⟪hWcj⟫) * (D.den i |_ₗ _ ⟪hWci⟫)) * (x |_ₗ _ ⟪hWi⟫) := by rw [hcoc]
    _ = (D.num j |_ₗ _ ⟪hWcj⟫) * ((D.den i |_ₗ _ ⟪hWci⟫) * (x |_ₗ _ ⟪hWi⟫)) := by ring
    _ = (D.num j |_ₗ _ ⟪hWcj⟫) * (s |_ₗ _ ⟪hWV⟫) := by rw [hxW]
    _ = (D.num j |_ₗ _ ⟪hWcj⟫) * ((D.den j |_ₗ _ ⟪hWcj⟫) * (y |_ₗ _ ⟪hWj⟫)) := by rw [hyW]
    _ = (D.num j |_ₗ _ ⟪hWcj⟫) * (y |_ₗ _ ⟪hWj⟫) * (D.den j |_ₗ _ ⟪hWcj⟫) := by ring

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- **Multiplication by `f` exists.** Any section of `J₂` over an open `V` has a (necessarily
unique) product with `f`, and that product is a section of `J₁`. -/
theorem exists_isMul {V : C.Opens} {s : Γ(C, V)} (hs : s ∈ idealSections J₂ (op V)) :
    ∃ t : Γ(C, V), D.IsMul V s t ∧ t ∈ idealSections J₁ (op V) := by
  have hloc : ∀ i, ∃ x : Γ(C, D.part V i),
      (D.den i |_ₗ D.part V i ⟪D.part_le_chart V i⟫) * x =
        s |_ₗ D.part V i ⟪D.part_le V i⟫ :=
    fun i => D.exists_den_mul i (D.part_le_chart V i)
      (idealSections_map J₂ (homOfLE (D.part_le V i)).op hs)
  choose x hx using hloc
  obtain ⟨t, ht, -⟩ := C.sheaf.existsUnique_gluing' (D.part V) V
    (fun i => homOfLE (D.part_le V i)) (D.le_iSup_part V)
    (fun i => (D.num i |_ₗ D.part V i ⟪D.part_le_chart V i⟫) * x i)
    (fun i j => D.isMul_compat s i j (x i) (x j) (hx i) (hx j))
  have ht' : ∀ i, (t |_ₗ D.part V i ⟪D.part_le V i⟫) =
      (D.num i |_ₗ D.part V i ⟪D.part_le_chart V i⟫) * x i := ht
  refine ⟨t, fun i => ?_, ?_⟩
  · rw [ht' i]
    calc ((D.num i |_ₗ _ ⟪D.part_le_chart V i⟫) * x i) * (D.den i |_ₗ _ ⟪D.part_le_chart V i⟫)
        = (D.num i |_ₗ _ ⟪D.part_le_chart V i⟫) *
            ((D.den i |_ₗ _ ⟪D.part_le_chart V i⟫) * x i) := by ring
      _ = (D.num i |_ₗ _ ⟪D.part_le_chart V i⟫) * (s |_ₗ _ ⟪D.part_le V i⟫) := by rw [hx i]
      _ = (s |_ₗ _ ⟪D.part_le V i⟫) * (D.num i |_ₗ _ ⟪D.part_le_chart V i⟫) := by ring
  · refine mem_idealSections_of_locally (D.part V) (D.part_le V) (D.le_iSup_part V) (fun i => ?_)
    rw [ht' i]
    exact Ideal.mul_mem_right _ _ (D.num_mem i (D.part_le_chart V i))

/-- Multiplication by `f` is additive. -/
theorem isMul_add {V : C.Opens} {s t s' t' : Γ(C, V)} (h : D.IsMul V s t)
    (h' : D.IsMul V s' t') : D.IsMul V (s + s') (t + t') := by
  intro i
  rw [restrict_add, restrict_add, add_mul, add_mul, h i, h' i]

/-- Multiplication by `f` is `Γ(C, V)`-linear. -/
theorem isMul_smul {V : C.Opens} (r : Γ(C, V)) {s t : Γ(C, V)} (h : D.IsMul V s t) :
    D.IsMul V (r * s) (r * t) := by
  intro i
  rw [restrict_mul, restrict_mul, mul_assoc, mul_assoc, h i]

/-- Multiplication by `f` commutes with restriction. -/
theorem isMul_restrict {V W : C.Opens} (hW : W ≤ V) {s t : Γ(C, V)} (h : D.IsMul V s t) :
    D.IsMul W (s |_ₗ W ⟪hW⟫) (t |_ₗ W ⟪hW⟫) := by
  intro i
  have hle : D.part W i ≤ D.part V i := le_inf ((D.part_le W i).trans hW) (D.part_le_chart W i)
  have hres := congrArg (fun z : Γ(C, D.part V i) => (z |_ₗ D.part W i ⟪hle⟫)) (h i)
  simp only [restrict_mul, restrict_restrict'] at hres
  simpa only [restrict_restrict'] using hres

/-- **The product of a section of `J₂` with `f`.** -/
noncomputable def mul (V : C.Opens) (s : idealSections J₂ (op V)) : idealSections J₁ (op V) :=
  ⟨(D.exists_isMul s.2).choose, (D.exists_isMul s.2).choose_spec.2⟩

theorem isMul_mul (V : C.Opens) (s : idealSections J₂ (op V)) :
    D.IsMul V s.1 (D.mul V s).1 := (D.exists_isMul s.2).choose_spec.1

theorem mul_eq_of_isMul {V : C.Opens} (s : idealSections J₂ (op V)) {t : Γ(C, V)}
    (h : D.IsMul V s.1 t) : (D.mul V s).1 = t :=
  D.isMul_unique (D.isMul_mul V s) h

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- **Multiplication by `f`, as a morphism of `𝒪_C`-modules `I(D₂) ⟶ I(D₁)`.** -/
noncomputable def mulHom : idealModule J₂ ⟶ idealModule J₁ :=
  ⟨{ app := fun W => ModuleCat.ofHom
      (Y := (idealModule J₁).val.obj W)
      { toFun := fun s => D.mul W.unop s
        map_add' := fun s s' => Subtype.ext (D.mul_eq_of_isMul (s + s')
          (D.isMul_add (D.isMul_mul W.unop s) (D.isMul_mul W.unop s')))
        map_smul' := fun r s => Subtype.ext (D.mul_eq_of_isMul (r • s)
          (D.isMul_smul r (D.isMul_mul W.unop s))) }
     naturality := fun {W W'} i => by
       refine ModuleCat.hom_ext (LinearMap.ext fun s => ?_)
       refine Subtype.ext ?_
       exact D.mul_eq_of_isMul _ (D.isMul_restrict i.unop.le (D.isMul_mul W.unop s)) }⟩

/-- Multiplication by `f` and by `f⁻¹` are inverse relations: the defining equation
`t · den = s · num` is symmetric in the two data. -/
theorem isMul_symm {V : C.Opens} {s t : Γ(C, V)} : D.symm.IsMul V t s ↔ D.IsMul V s t :=
  ⟨fun h i => (h i).symm, fun h i => (h i).symm⟩

theorem mul_injective (V : C.Opens) : Function.Injective (D.mul V) := by
  intro s s' h
  refine Subtype.ext ?_
  refine C.sheaf.eq_of_locally_eq' (D.part V) V (fun i => homOfLE (D.part_le V i))
    (D.le_iSup_part V) s.1 s'.1 (fun i => ?_)
  refine D.eq_of_mul_num_eq i (D.part_le_chart V i) ?_
  have e1 := D.isMul_mul V s i
  rw [h] at e1
  exact e1.symm.trans (D.isMul_mul V s' i)

theorem mul_surjective (V : C.Opens) : Function.Surjective (D.mul V) := fun t =>
  ⟨D.symm.mul V t, Subtype.ext (D.mul_eq_of_isMul _ (D.isMul_symm.mp (D.symm.isMul_mul V t)))⟩

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-- Multiplication by `f` is bijective on sections over *every* open — `f⁻¹` provides the
inverse — so it is an isomorphism of `𝒪_C`-modules. -/
theorem isIso_mulHom : IsIso D.mulHom := by
  refine Hom.isIso_iff_isIso_app.mpr (fun V => ?_)
  rw [ConcreteCategory.isIso_iff_bijective]
  exact ⟨D.mul_injective V, D.mul_surjective V⟩

/-- **Multiplication by `f` as an isomorphism `I(D₂) ≅ I(D₁)`.** -/
noncomputable def mulIso : idealModule J₂ ≅ idealModule J₁ :=
  letI := D.isIso_mulHom
  asIso D.mulHom

include D in
/-- `D₁` is Cartier, so `I(D₁)` is an invertible `𝒪_C`-module. -/
theorem isInvertible_idealModule_fst : IsInvertible (idealModule J₁) := by
  refine isInvertible_idealModule _ (fun c => ?_)
  have hcT : c ∈ ⨆ i, (D.chart i).1 := by rw [D.chart_cover]; trivial
  obtain ⟨i, hi⟩ := TopologicalSpace.Opens.mem_iSup.mp hcT
  exact ⟨D.chart i, hi, D.num i, D.span_num i, D.num_nzd i⟩

include D in
/-- `D₂` is Cartier, so `I(D₂)` is an invertible `𝒪_C`-module. -/
theorem isInvertible_idealModule_snd : IsInvertible (idealModule J₂) :=
  D.symm.isInvertible_idealModule_fst

end PrincipalDivisorData

variable {J₁ J₂}

/-- **A principal divisor trivialises the corresponding ideal module (T10-cmp-core).**

If a rational function `f` on `C` has divisor `D₁ − D₂` — presented, as it must be on a scheme,
by local equations `f = num i / den i` on an affine cover, with `num i` generating `J₁` and
`den i` generating `J₂` — then multiplication by `f` is an isomorphism of `𝒪_C`-modules
`I(D₂) ≅ I(D₁)`.

This is the scheme-level, curve-agnostic input to "linearly equivalent divisors have isomorphic
ideal modules", hence to the comparison `Pic C ≅ Cl C` and to the Abel map computations for
elliptic curves. -/
theorem nonempty_idealModule_iso_of_principalDivisorData (D : PrincipalDivisorData J₁ J₂) :
    Nonempty (idealModule J₂ ≅ idealModule J₁) := ⟨D.mulIso⟩

/-- Tensor form of `nonempty_idealModule_iso_of_principalDivisorData`: the two ideal modules
may be replaced by one another inside any tensor product. -/
theorem nonempty_tensorObj_idealModule_iso_of_principalDivisorData
    (D : PrincipalDivisorData J₁ J₂) (N : C.Modules) :
    Nonempty (tensorObj (idealModule J₂) N ≅ tensorObj (idealModule J₁) N) :=
  ⟨tensorObjCongr D.mulIso (Iso.refl N)⟩

end AlgebraicGeometry.Scheme.Modules
