import BernoulliRegular.FLT37.Eichler.CaseII.RootClass.IntSolutionToRealDatum
import BernoulliRegular.FLT37.Eichler.FLT37CaseIWired

/-!
# [FLT37-CASEII-II1-REROUTE] The genuine single-root linear-measure Case-II descent

## Why the previous endpoint was vacuous

The FLT37 Case-II II1 leaf was carried as `CaseIIRealIdealDescent37`
(`RealGeneratorBridge.lean`): for each `CaseIIData37` and adjacent root `η ≠ η₀`, a nonzero ideal
`J` of `𝓞 K⁺` with `J.map = 𝔞(η)/𝔞₀`.  This is **provably false**:

* `σ(𝔞(η)) = 𝔞(η⁻¹)` (`caseII_map_rootIdeal`), so for an adjacent root the single-quotient
  `𝔞(η)/𝔞₀` is sent by `σ` to `𝔞(η⁻¹)/𝔞₀ ≠ 𝔞(η)/𝔞₀`.  A `J ⊆ 𝓞 K⁺` would force `𝔞(η)/𝔞₀` to be
  `σ`-stable.  So no such `J` exists, and every endpoint resting on `CaseIIRealIdealDescent37` is
  vacuous.

## The honest residual

Washington's §9.4 descent step
(`caseII_descent_step_of_adjacent_etaZeroSpanSingletons_and_unitPower`,
`SpecificChain.lean`) does **not** require a `𝓞 K⁺` ideal or `σ`-fixed generator.  It requires only
that the single-root **anchored quotients** `𝔞(η₁)/𝔞₀`, `𝔞(η₂)/𝔞₀` at the two adjacent roots
`η₁ = η₀ζ`, `η₂ = η₀ζ²` are **principal in `𝓞 K`** (generated by ratios `a/b` of elements of
`𝓞 K`, with `a, b` coprime to `ζ - 1`).  Equivalently `[𝔞(η₁)] = [𝔞₀] = [𝔞(η₂)]` in `Cl(𝓞 K)`.

This is the genuine Washington §9.1 `B_a` content.  It is the irreducible obstruction: the class
`[𝔞(η)/𝔞₀]` lies in `Cl⁻(𝓞 K)[37]` (it pairs with its conjugate to land in `Cl⁺[37] = 0`, by
Vandiver / `caseII_sigma_stable_ideal_descends`), which is generally **nonzero** for the irregular
prime `37`.  It is **strictly more honest** than `CaseIIRealIdealDescent37`, which additionally —
and
falsely — demanded `𝓞 K⁺`-descent (hence `σ`-stability).

`CaseIIAdjacentSingleRootQuotientPrincipal37` names exactly this single-root principality.  This
file:

* defines the residual `CaseIIAdjacentSingleRootQuotientPrincipal37` (`def … : Prop`, **not** an
  axiom);
* derives the strict `CaseIIData37` descent step from it + Assumption II (the proven
  `WashingtonCaseIIExactQuotientUnitPower37Source`) via the **linear-measure** Washington descent
  `caseII_descent_step_of_adjacent_etaZeroSpanSingletons_and_unitPower`;
* assembles a top-level `FermatLastTheoremFor 37` resting on the residual + Assumption II + the
  user-owned second-order input — **with `CaseIIRealIdealDescent37` entirely removed**.

It imports only; it does **not** modify any existing file.

## References
* Washington, *Introduction to Cyclotomic Fields*, GTM 83, §9.1 (`B_a`, Lemma 9.2), Theorem 9.4.
-/

@[expose] public section

noncomputable section

open NumberField Polynomial
open scoped nonZeroDivisors

namespace BernoulliRegular.FLT37.Eichler

open FLT37.LehmerVandiver.CaseII

/-- **[FLT37-CASEII-II1-RESIDUAL] The single-root anchored quotients are principal in `𝓞 K`.**

For every Case-II datum `D : CaseIIData37 (CyclotomicField 37 ℚ) m`, the two adjacent anchored
quotients `𝔞(η₀ζ)/𝔞₀` and `𝔞(η₀ζ²)/𝔞₀` are principal fractional ideals, generated by ratios
`a₁/b₁`, `a₂/b₂` of `𝓞 K`-elements coprime to `ζ - 1` (so the anchor exponent is preserved).

This is the irreducible Washington §9.1 content of the Case-II II1 leaf, isolated as a named
hypothesis (`def`, not `axiom`).  It is the `σ`-free, `K⁺`-descent-free, satisfiable replacement for
the provably-false `CaseIIRealIdealDescent37`.

Mathematically it is the statement that `[𝔞(η)] = [𝔞₀]` in `Cl(𝓞 K)` for the adjacent roots — i.e.
the vanishing of the `Cl⁻(𝓞 K)[37]` classes of the adjacent root ideals (Washington §9.1, via the
`Cl⁺[37] = 0` pairing + the symmetric reassembly across the adjacent roots). -/
def CaseIIAdjacentSingleRootQuotientPrincipal37
    [NumberField.IsCMField (CyclotomicField 37 ℚ)] : Prop :=
  ∀ {m : ℕ} (D : CaseIIData37 (CyclotomicField 37 ℚ) m),
    ∃ a₁ b₁ a₂ b₂ : 𝓞 (CyclotomicField 37 ℚ),
      ¬ (D.hζ.toInteger - 1) ∣ a₁ ∧
      ¬ (D.hζ.toInteger - 1) ∣ b₁ ∧
      ¬ (D.hζ.toInteger - 1) ∣ a₂ ∧
      ¬ (D.hζ.toInteger - 1) ∣ b₂ ∧
      FractionalIdeal.spanSingleton (𝓞 (CyclotomicField 37 ℚ))⁰
          (a₁ / b₁ : CyclotomicField 37 ℚ) =
        (D.rootIdeal D.etaOne /
          aEtaZeroDvdPPow (by decide : (37 : ℕ) ≠ 2)
            D.hζ D.equation D.hy :
          FractionalIdeal (𝓞 (CyclotomicField 37 ℚ))⁰ (CyclotomicField 37 ℚ)) ∧
      FractionalIdeal.spanSingleton (𝓞 (CyclotomicField 37 ℚ))⁰
          (a₂ / b₂ : CyclotomicField 37 ℚ) =
        (D.rootIdeal D.etaTwo /
          aEtaZeroDvdPPow (by decide : (37 : ℕ) ≠ 2)
            D.hζ D.equation D.hy :
          FractionalIdeal (𝓞 (CyclotomicField 37 ℚ))⁰ (CyclotomicField 37 ℚ))


/-- **`𝔞(η)/𝔞(η₀)` principal as a fractional ideal `⟹` `IsPrincipal(𝔞(η)/𝔞₀)`.**

The anchored quotient `𝔞(η)/𝔞₀` (`𝔞₀ = aEtaZeroDvdPPow`, the `𝔭`-coprime part of `𝔞(η₀)`) is
principal whenever the *root* quotient `𝔞(η)/𝔞(η₀)` is principal as a fractional ideal.  The `𝔭^m`
correction is principal (`𝔭 = (ζ-1)` is principal), so it cannot break principality.  Mirrors the
final ideal-bookkeeping steps of `caseII_a_div_a_zero_isPrincipal_of_realIdealModel`
(`SpecificDischarge.lean`), but driven by the bare fractional-ideal principality of `𝔞(η)/𝔞(η₀)`
rather than by a `𝓞 K⁺` real-ideal-model witness. -/
theorem caseII_isPrincipal_aDivAEtaZero_of_rootQuotientPrincipal
    {K : Type} [Field K] [NumberField K] [IsCyclotomicExtension {37} ℚ K]
    [NumberField.IsCMField K] (hp : (37 : ℕ) ≠ 2)
    {ζ : K} (hζ : IsPrimitiveRoot ζ 37)
    {x y z : 𝓞 K} {ε : (𝓞 K)ˣ} {m : ℕ}
    (e : x ^ 37 + y ^ 37 = ε * ((hζ.toInteger - 1) ^ (m + 1) * z) ^ 37)
    (hy : ¬ hζ.toInteger - 1 ∣ y)
    (η : nthRootsFinset 37 (1 : 𝓞 K))
    (h_root :
      Submodule.IsPrincipal
        (((rootDivZetaSubOneDvdGcd hp hζ e hy η) /
          (rootDivZetaSubOneDvdGcd hp hζ e hy
            (zetaSubOneDvdRoot hp hζ e hy))
          : FractionalIdeal (𝓞 K)⁰ K) : Submodule (𝓞 K) K)) :
    Submodule.IsPrincipal
      ((rootDivZetaSubOneDvdGcd hp hζ e hy η /
        aEtaZeroDvdPPow hp hζ e hy
        : FractionalIdeal (𝓞 K)⁰ K) : Submodule (𝓞 K) K) := by
  haveI : Fact (Nat.Prime 37) := ⟨by decide⟩
  rw [← a_eta_zero_dvd_p_pow_spec, mul_comm, FractionalIdeal.coeIdeal_mul,
      ← div_div, FractionalIdeal.isPrincipal_iff] at h_root
  obtain ⟨a, ha⟩ := h_root
  rw [div_eq_iff, Ideal.span_singleton_pow, FractionalIdeal.coeIdeal_span_singleton,
    FractionalIdeal.spanSingleton_mul_spanSingleton] at ha
  · rw [FractionalIdeal.isPrincipal_iff]
    exact ⟨_, ha⟩
  · rw [← FractionalIdeal.coeIdeal_bot,
      (FractionalIdeal.coeIdeal_injective' (le_rfl : (𝓞 K)⁰ ≤ (𝓞 K)⁰)).ne_iff]
    apply mt eq_zero_of_pow_eq_zero
    rw [Ideal.zero_eq_bot, Ideal.span_singleton_eq_bot]
    exact hζ.toInteger_isPrimitiveRoot.sub_one_ne_zero (by decide : (1 : ℕ) < 37)


/-- **`[𝔞(η)] = [𝔞(η₀)]` (class equality) `⟹` `𝔞(η)/𝔞(η₀)` principal as a fractional ideal.**

Stated on a `CaseIIData37` datum `D` (so the root-ideal nonvanishing comes from
`caseII_rootIdeal_ne_bot D`).
The pure class-group statement `[𝔞(η)] = [𝔞(η₀)]` in `Cl(𝓞 K)` is, by `ClassGroup.mk0_eq_mk0_iff`,
the existence of `a, b ≠ 0` with `(a)·𝔞(η) = (b)·𝔞(η₀)`, which exhibits `𝔞(η)/𝔞(η₀) = (b/a)` as a
principal fractional ideal. -/
theorem caseII_rootQuotientPrincipal_of_classEq
    {K : Type} [Field K] [NumberField K] [IsCyclotomicExtension {37} ℚ K]
    [NumberField.IsCMField K] {m : ℕ} (D : CaseIIData37 K m) (hp : (37 : ℕ) ≠ 2)
    (η : nthRootsFinset 37 (1 : 𝓞 K))
    (h_classEq :
      ClassGroup.mk0 ⟨D.rootIdeal η,
          mem_nonZeroDivisors_iff_ne_zero.mpr
            (by rw [Ideal.zero_eq_bot]; exact caseII_rootIdeal_ne_bot D hp η)⟩ =
        ClassGroup.mk0 ⟨D.rootIdeal D.etaZero,
          mem_nonZeroDivisors_iff_ne_zero.mpr
            (by rw [Ideal.zero_eq_bot]; exact caseII_rootIdeal_ne_bot D hp D.etaZero)⟩) :
    Submodule.IsPrincipal
      (((D.rootIdeal η) / (D.rootIdeal D.etaZero)
        : FractionalIdeal (𝓞 K)⁰ K) : Submodule (𝓞 K) K) := by
  haveI : Fact (Nat.Prime 37) := ⟨by decide⟩
  obtain ⟨a, b, ha, hb, hab⟩ := ClassGroup.mk0_eq_mk0_iff.mp h_classEq
  -- a ≠ 0 as a fractional-ideal spanSingleton scalar.
  have haK : (a : K) ≠ 0 := by
    simpa using (FaithfulSMul.algebraMap_injective (𝓞 K) K).ne ha
  have hsa_ne : FractionalIdeal.spanSingleton (𝓞 K)⁰ (a : K) ≠ 0 :=
    FractionalIdeal.spanSingleton_ne_zero_iff.mpr haK
  -- Coerce (a)·𝔞(η) = (b)·𝔞(η₀) to fractional ideals.
  have hcoe := congrArg
    (fun (I : Ideal (𝓞 K)) ↦ (I : FractionalIdeal (𝓞 K)⁰ K)) hab
  simp only [FractionalIdeal.coeIdeal_mul, FractionalIdeal.coeIdeal_span_singleton] at hcoe
  -- 𝔞(η) = spanSingleton(b/a) · 𝔞(η₀): cancel spanSingleton(a) from `hcoe`.
  have hkey : (D.rootIdeal η : FractionalIdeal (𝓞 K)⁰ K) =
      FractionalIdeal.spanSingleton (𝓞 K)⁰ ((b : K) / (a : K)) *
        (D.rootIdeal D.etaZero : FractionalIdeal (𝓞 K)⁰ K) := by
    apply mul_left_cancel₀ hsa_ne
    rw [hcoe, ← mul_assoc, FractionalIdeal.spanSingleton_mul_spanSingleton,
      mul_div_cancel₀ _ haK]
  rw [FractionalIdeal.isPrincipal_iff]
  refine ⟨(b : K) / (a : K), ?_⟩
  rw [hkey, mul_div_assoc, div_self
    (by
      rw [← FractionalIdeal.coeIdeal_bot,
        (FractionalIdeal.coeIdeal_injective' (le_rfl : (𝓞 K)⁰ ≤ (𝓞 K)⁰)).ne_iff]
      exact caseII_rootIdeal_ne_bot D hp D.etaZero),
    mul_one]

/-- **[FLT37-CASEII-II1-SHARP-RESIDUAL] The adjacent root-ideal classes equal the anchor class.**

The sharpest form of the Case-II II1 residual: a **pure `Cl(𝓞 K)` equation**.  For every Case-II
datum `D` and each adjacent root `η ∈ {η₀ζ, η₀ζ²}`, the Washington root-ideal class equals the
anchor class: `[𝔞(η)] = [𝔞(η₀)]` in `Cl(𝓞 K)`.

This is equivalent (`caseII_rootQuotientPrincipal_of_classEq` +
`caseII_isPrincipal_aDivAEtaZero_of_rootQuotientPrincipal`
+ the coprime-generator bridge) to `CaseIIAdjacentSingleRootQuotientPrincipal37`, but carries **no**
fractional ideals and **no** generators — only the vanishing of the anchored class
`c = [𝔞(η)]·[𝔞(η₀)]⁻¹`.

It is the genuine irreducible obstruction for the irregular prime `37`: `c` is `37`-torsion
(`caseII_anchored_class_pow_eq_one`) and satisfies `c·σc = 1`
(`caseII_anchored_classGroup_mul_conj_eq_one`,
i.e. `c ∈ Cl⁻[37]`) under the proven Vandiver `37 ∤ h⁺` — but `Cl⁻(𝓞 K)[37]` is **nonzero**, so
`c·σc = 1` does **not** give `c = 1`.  Forcing `c = 1` is exactly the Washington 9.4 §9.1
second-order
content (the symmetric reassembly across the adjacent roots together with the second-order Bernoulli
condition).  This is where full regularity (`37 ∤ h`) is used in flt-regular's `a_div_principal`. -/
def CaseIIAdjacentAnchoredClassTrivial37
    [NumberField.IsCMField (CyclotomicField 37 ℚ)] : Prop :=
  haveI : Fact (Nat.Prime 37) := ⟨by decide⟩
  ∀ {m : ℕ} (D : CaseIIData37 (CyclotomicField 37 ℚ) m)
    (η : nthRootsFinset 37 (1 : 𝓞 (CyclotomicField 37 ℚ))),
    η ≠ D.etaZero →
    ClassGroup.mk0 ⟨D.rootIdeal η,
        mem_nonZeroDivisors_iff_ne_zero.mpr
          (by rw [Ideal.zero_eq_bot]
              exact caseII_rootIdeal_ne_bot D (by decide : (37 : ℕ) ≠ 2) η)⟩ =
      ClassGroup.mk0 ⟨D.rootIdeal D.etaZero,
        mem_nonZeroDivisors_iff_ne_zero.mpr
          (by rw [Ideal.zero_eq_bot]
              exact caseII_rootIdeal_ne_bot D (by decide : (37 : ℕ) ≠ 2) D.etaZero)⟩

/-- **[FLT37-CASEII-II1-2TORSION] The anchored class is square-trivial (`c² = 1`).**

The *maximally* reduced form of the Case-II II1 residual.  For each adjacent root `η`, the anchored
class `c = [𝔞(η)]·[𝔞(η₀)]⁻¹ ∈ Cl(𝓞 K)` squares to `1`.

Combined with the **proven** facts `c³⁷ = 1` (`caseII_anchored_class_pow_eq_one`) and `c·σc = 1`
(`caseII_anchored_classGroup_mul_conj_eq_one`, Vandiver `37 ∤ h⁺`), `c² = 1` already forces `c = 1`
(coprimality of `2` and `37`), hence `[𝔞(η)] = [𝔞(η₀)]`.  So the entire Case-II II1 obstruction is
precisely: **the `Cl⁻(𝓞 K)[37]` anchored class is `2`-torsion** — equivalently, it vanishes.  This
is the genuine, irreducible second-order content (Washington 9.4 §9.1). -/
def CaseIIAdjacentAnchoredClassTwoTorsion37
    [NumberField.IsCMField (CyclotomicField 37 ℚ)] : Prop :=
  haveI : Fact (Nat.Prime 37) := ⟨by decide⟩
  ∀ {m : ℕ} (D : CaseIIData37 (CyclotomicField 37 ℚ) m)
    (η : nthRootsFinset 37 (1 : 𝓞 (CyclotomicField 37 ℚ))),
    η ≠ D.etaZero →
    (ClassGroup.mk0 ⟨D.rootIdeal η,
        mem_nonZeroDivisors_iff_ne_zero.mpr
          (by rw [Ideal.zero_eq_bot]
              exact caseII_rootIdeal_ne_bot D (by decide : (37 : ℕ) ≠ 2) η)⟩ *
      (ClassGroup.mk0 ⟨D.rootIdeal D.etaZero,
        mem_nonZeroDivisors_iff_ne_zero.mpr
          (by rw [Ideal.zero_eq_bot]
              exact caseII_rootIdeal_ne_bot D (by decide : (37 : ℕ) ≠ 2) D.etaZero)⟩)⁻¹) ^ 2 = 1

/-- **`c² = 1` (with the proven `c³⁷ = 1`) forces `c = 1`: the class-equality residual.**

`CaseIIAdjacentAnchoredClassTrivial37` follows from `CaseIIAdjacentAnchoredClassTwoTorsion37`,
using the proven `caseII_anchored_class_pow_eq_one` (`c³⁷ = 1`).  From `c² = 1` and `c³⁷ = 1` the
order of `c` divides `gcd(2, 37) = 1`, so `c = 1`, i.e. `[𝔞(η)] = [𝔞(η₀)]`. -/
theorem caseIIAdjacentAnchoredClassTrivial37_of_twoTorsion
    [NumberField.IsCMField (CyclotomicField 37 ℚ)]
    (h2 : CaseIIAdjacentAnchoredClassTwoTorsion37) :
    CaseIIAdjacentAnchoredClassTrivial37 := by
  haveI : Fact (Nat.Prime 37) := ⟨by decide⟩
  intro m D η hη
  -- The anchored class `c = [𝔞(η)]·[𝔞(η₀)]⁻¹`.
  -- proven: c³⁷ = 1 (caseII_anchored_class_pow_eq_one); c² = 1 (hypothesis).
  have hpow37 := caseII_anchored_class_pow_eq_one D (by decide : (37 : ℕ) ≠ 2) η
  have hpow2 := h2 D η hη
  -- order divides gcd(2,37)=1 ⟹ c·c0⁻¹ = 1 ⟹ [𝔞(η)] = [𝔞(η₀)].
  have hdvd := Nat.dvd_gcd (orderOf_dvd_of_pow_eq_one hpow2)
    (orderOf_dvd_of_pow_eq_one hpow37)
  rw [show Nat.gcd 2 37 = 1 from by decide] at hdvd
  exact mul_inv_eq_one.mp (orderOf_eq_one_iff.mp (Nat.dvd_one.mp hdvd))

/-- **The single-root principalization predicate from the sharp class-equality residual.**

From `CaseIIAdjacentAnchoredClassTrivial37` (the pure `[𝔞(η)] = [𝔞(η₀)]` form) we recover the
codebase's `CaseIIPrincipalizationAgainstEtaZero` for each datum: `[𝔞(η)] = [𝔞(η₀)]` gives
`𝔞(η)/𝔞(η₀)` principal as a fractional ideal (`caseII_rootQuotientPrincipal_of_classEq`), then the
`𝔭^m`-correction step (`caseII_isPrincipal_aDivAEtaZero_of_rootQuotientPrincipal`) yields
`IsPrincipal(𝔞(η)/𝔞₀)`. -/
theorem caseIIPrincipalizationAgainstEtaZero_of_anchoredClassTrivial37
    [NumberField.IsCMField (CyclotomicField 37 ℚ)]
    (h_class : CaseIIAdjacentAnchoredClassTrivial37)
    {m : ℕ} (D : CaseIIData37 (CyclotomicField 37 ℚ) m) :
    CaseIIPrincipalizationAgainstEtaZero
      37 (CyclotomicField 37 ℚ) (by decide : (37 : ℕ) ≠ 2)
      D.hζ D.equation D.hy := by
  haveI : Fact (Nat.Prime 37) := ⟨by decide⟩
  intro η hη
  -- `D.etaZero = zetaSubOneDvdRoot …`, `D.rootIdeal η = rootDivZetaSubOneDvdGcd …`.
  have h_root := caseII_rootQuotientPrincipal_of_classEq D (by decide : (37 : ℕ) ≠ 2) η
    (h_class D η hη)
  exact caseII_isPrincipal_aDivAEtaZero_of_rootQuotientPrincipal
    (by decide : (37 : ℕ) ≠ 2) D.hζ D.equation D.hy η h_root

/-- **The single-root principality residual from the sharp class-equality residual.**

Chains `caseIIPrincipalizationAgainstEtaZero_of_anchoredClassTrivial37` with the proven
coprime-generator bridge `exists_not_dvd_spanSingleton_eq_a_div_a_zero_of_etaZeroPrincipalization`
(at the two adjacent roots) to produce `CaseIIAdjacentSingleRootQuotientPrincipal37`. -/
theorem caseIIAdjacentSingleRootQuotientPrincipal37_of_anchoredClassTrivial37
    [NumberField.IsCMField (CyclotomicField 37 ℚ)]
    (h_class : CaseIIAdjacentAnchoredClassTrivial37) :
    CaseIIAdjacentSingleRootQuotientPrincipal37 := by
  haveI : Fact (Nat.Prime 37) := ⟨by decide⟩
  haveI : NeZero 37 := ⟨by decide⟩
  intro m D
  have hP := caseIIPrincipalizationAgainstEtaZero_of_anchoredClassTrivial37 h_class D
  obtain ⟨a₁, b₁, ha₁, hb₁, hspan₁⟩ :=
    exists_not_dvd_spanSingleton_eq_a_div_a_zero_of_etaZeroPrincipalization
      (by decide : (37 : ℕ) ≠ 2) D.hζ D.equation D.hy D.hz hP D.etaOne D.etaOne_ne_etaZero
  obtain ⟨a₂, b₂, ha₂, hb₂, hspan₂⟩ :=
    exists_not_dvd_spanSingleton_eq_a_div_a_zero_of_etaZeroPrincipalization
      (by decide : (37 : ℕ) ≠ 2) D.hζ D.equation D.hy D.hz hP D.etaTwo D.etaTwo_ne_etaZero
  exact ⟨a₁, b₁, a₂, b₂, ha₁, hb₁, ha₂, hb₂, hspan₁, hspan₂⟩

/-- **The honest residual follows from the existing parametric `η₀`-principalization predicate.**

`CaseIIAdjacentSingleRootQuotientPrincipal37` is implied by the codebase's pre-existing
`CaseIIPrincipalizationAgainstEtaZeroOnSpecific 37 K` (the refined Washington 9.4 target that
quantifies the principalization of `𝔞(η)/𝔞₀` over the concrete case-II data —
`SpecificDischarge.lean`).

The bridge is `exists_not_dvd_spanSingleton_eq_a_div_a_zero_of_etaZeroPrincipalization`, which turns
the principal fractional ideal `𝔞(η)/𝔞₀` (with `𝔭 ∤ 𝔞(η)` for `η ≠ η₀` and `𝔭 ∤ 𝔞₀`) into a
`ζ-1`-coprime ratio generator `a/b`.  This identifies our honest residual with the **existing**
parametric infrastructure flagged in the codebase as "the realistic mathematical target for filling"
— the form that does NOT carry the false `σ`-stability / `𝓞 K⁺`-descent requirement of
`CaseIIRealIdealDescent37`. -/
theorem caseIIAdjacentSingleRootQuotientPrincipal37_of_etaZeroPrincipalizationOnSpecific
    [NumberField.IsCMField (CyclotomicField 37 ℚ)]
    (h_principal : CaseIIPrincipalizationAgainstEtaZeroOnSpecific
      37 (CyclotomicField 37 ℚ) (by decide : (37 : ℕ) ≠ 2)) :
    CaseIIAdjacentSingleRootQuotientPrincipal37 := by
  haveI : Fact (Nat.Prime 37) := ⟨by decide⟩
  haveI : NeZero 37 := ⟨by decide⟩
  intro m D
  have hP := h_principal D.hζ D.equation D.hy
  obtain ⟨a₁, b₁, ha₁, hb₁, hspan₁⟩ :=
    exists_not_dvd_spanSingleton_eq_a_div_a_zero_of_etaZeroPrincipalization
      (by decide : (37 : ℕ) ≠ 2) D.hζ D.equation D.hy D.hz hP D.etaOne D.etaOne_ne_etaZero
  obtain ⟨a₂, b₂, ha₂, hb₂, hspan₂⟩ :=
    exists_not_dvd_spanSingleton_eq_a_div_a_zero_of_etaZeroPrincipalization
      (by decide : (37 : ℕ) ≠ 2) D.hζ D.equation D.hy D.hz hP D.etaTwo D.etaTwo_ne_etaZero
  exact ⟨a₁, b₁, a₂, b₂, ha₁, hb₁, ha₂, hb₂, hspan₁, hspan₂⟩

/-- **The strict Case-II descent step from the single-root residual + Assumption II.**

Given the single-root anchored-quotient principality `CaseIIAdjacentSingleRootQuotientPrincipal37`
and Assumption II (`WashingtonCaseIIExactQuotientUnitPower37Source`, the proven Case-II descent-unit
`37`-th-power statement), the public Case-II descent measure strictly decreases:
`∃ m' < m, Nonempty (CaseIIData37 K m')`.

This is the **linear-measure** Washington 9.4 descent
(`caseII_descent_step_of_adjacent_etaZeroSpanSingletons_and_unitPower`): the single-root quotients
drop the anchor exponent `m` by one, unlike the `σ`-stable *pair* product (whose `𝔭`-valuations
double).  `¬ 37 ∣ h⁺` is discharged internally by `Sinnott.flt37_not_dvd_hPlus`. -/
theorem caseII_descent_step_of_singleRootPrincipal
    [NumberField.IsCMField (CyclotomicField 37 ℚ)]
    (h_single : CaseIIAdjacentSingleRootQuotientPrincipal37)
    (h_exactUnit : WashingtonCaseIIExactQuotientUnitPower37Source)
    (hV : ¬ (37 : ℕ) ∣ hPlus (CyclotomicField 37 ℚ))
    (hSO : NoSecondOrderIrregularPair 37 32)
    {m : ℕ}
    (D : CaseIIData37 (CyclotomicField 37 ℚ) m) :
    ∃ m' : ℕ, m' < m ∧
      Nonempty (CaseIIData37 (CyclotomicField 37 ℚ) m') :=
  caseII_descent_step_of_adjacent_etaZeroSpanSingletons_and_unitPower
    (K := CyclotomicField 37 ℚ)
    (fun {_m} D ↦ h_single D)
    (fun {_m} D ↦ caseII_exact_quotient_unitPower37 h_exactUnit hV hSO D)
    D

/-- **The public Case-II bridge from the single-root residual + Assumption II** — with
`¬ 37 ∣ h⁺` banked. Composes `caseII_descent_step_of_singleRootPrincipal` through the well-founded
minimality wrapper `caseIIBridge_thirtyseven_of_descent_step`. -/
theorem caseIIBridge_thirtyseven_of_singleRootPrincipal
    [NumberField.IsCMField (CyclotomicField 37 ℚ)]
    (h_single : CaseIIAdjacentSingleRootQuotientPrincipal37)
    (h_exactUnit : WashingtonCaseIIExactQuotientUnitPower37Source) :
    BernoulliRegular.CaseIIBridge 37 (CyclotomicField 37 ℚ) 32 :=
  caseIIBridge_thirtyseven_of_descent_step
    (fun hV hSO {_m} D ↦
      caseII_descent_step_of_singleRootPrincipal h_single h_exactUnit hV hSO D)

/-- **Fermat's Last Theorem for `37`, rerouted off the vacuous `CaseIIRealIdealDescent37`.**

`FermatLastTheoremFor 37` from:

* `caseII_single` (`CaseIIAdjacentSingleRootQuotientPrincipal37`): **Case-II II1**, the single-root
  anchored quotients `𝔞(η)/𝔞₀` are principal in `𝓞 K` (the honest Washington §9.1 residual,
  replacing the provably-false `CaseIIRealIdealDescent37`);
* `caseII_exactUnit` (`WashingtonCaseIIExactQuotientUnitPower37Source`): **Case-II II2**, Assumption
  II — the descent-equation quotient unit is a `37`-th power (proven membership-free in the Eichler
  module);
* `noSecondOrderIrregular` (`NoSecondOrderIrregularPair 37 32`): the user-owned second-order
  Bernoulli input.

Case I is discharged unconditionally by the Eichler first-case proof (`fltCaseI_thirtyseven`), and
`¬ 37 ∣ h⁺` is supplied internally by the proven `Sinnott.flt37_not_dvd_hPlus`.  The descent runs at
**linear** measure (single-root quotients), not the doubled measure of the `σ`-stable pair
product. -/
theorem fermatLastTheoremFor_thirtyseven_of_singleRootPrincipal
    [NumberField.IsCMField (CyclotomicField 37 ℚ)]
    (caseII_single : CaseIIAdjacentSingleRootQuotientPrincipal37)
    (caseII_exactUnit : WashingtonCaseIIExactQuotientUnitPower37Source)
    (noSecondOrderIrregular : NoSecondOrderIrregularPair 37 32) :
    FermatLastTheoremFor 37 := by
  haveI : Fact (Nat.Prime 37) := ⟨by decide⟩
  haveI : NeZero 37 := ⟨by decide⟩
  exact fermatLastTheoremFor_thirtyseven_of_remaining
    (cor8_19Bridge_of_not_dvd_hPlus 37 (CyclotomicField 37 ℚ)
      Sinnott.flt37_not_dvd_hPlus)
    caseIBridge_thirtyseven_eichler
    noSecondOrderIrregular
    (caseIIBridge_thirtyseven_of_singleRootPrincipal caseII_single caseII_exactUnit)

/-- **Fermat's Last Theorem for `37`, resting on the codebase's existing parametric
`η₀`-principalization target** (and the proven Assumption II + the user-owned second-order input).

This is the maximally-unified non-vacuous endpoint:

* the Case-II II1 input is the **pre-existing** `CaseIIPrincipalizationAgainstEtaZeroOnSpecific 37
  K`
  — the refined Washington 9.4 principalization predicate that the codebase already flags as the
  realistic fill target — fed through `caseII_descent_step_of_singleRootPrincipal` at **linear**
  measure (single-root quotients), not the doubled measure of the `σ`-stable pair;
* Assumption II is `WashingtonCaseIIExactQuotientUnitPower37Source` (proven membership-free in the
  Eichler module);
* `noSecondOrderIrregular : NoSecondOrderIrregularPair 37 32` is carried.

Compared with the older
`caseIIBridge_thirtyseven_of_etaZeroPrincipalizationOnSpecific_and_adaptedKummer_via_descent`
this consumes the **proven** Assumption II rather than the unproven full
`AdaptedKummersLemmaOnSpecific`,
and—crucially—it carries **no** `CaseIIRealIdealDescent37` (the provably-false `σ`-stable real-ideal
descent), so no part of the chain is vacuous. -/
theorem fermatLastTheoremFor_thirtyseven_of_etaZeroPrincipalizationOnSpecific
    [NumberField.IsCMField (CyclotomicField 37 ℚ)]
    (caseII_principal : CaseIIPrincipalizationAgainstEtaZeroOnSpecific
      37 (CyclotomicField 37 ℚ) (by decide : (37 : ℕ) ≠ 2))
    (caseII_exactUnit : WashingtonCaseIIExactQuotientUnitPower37Source)
    (noSecondOrderIrregular : NoSecondOrderIrregularPair 37 32) :
    FermatLastTheoremFor 37 :=
  fermatLastTheoremFor_thirtyseven_of_singleRootPrincipal
    (caseIIAdjacentSingleRootQuotientPrincipal37_of_etaZeroPrincipalizationOnSpecific
      caseII_principal)
    caseII_exactUnit noSecondOrderIrregular

/-- **Fermat's Last Theorem for `37`, resting on the sharp `Cl(𝓞 K)`-equality residual.**

The cleanest non-vacuous endpoint.  `FermatLastTheoremFor 37` from:

* `caseII_classTrivial` (`CaseIIAdjacentAnchoredClassTrivial37`): **Case-II II1**, the pure
  class-group equation `[𝔞(η)] = [𝔞(η₀)]` in `Cl(𝓞 K)` for the adjacent roots — the irreducible
  Washington §9.1 obstruction, with no fractional ideals, no generators, and (crucially) **no**
  false
  `σ`-stability / `𝓞 K⁺`-descent requirement;
* `caseII_exactUnit` (`WashingtonCaseIIExactQuotientUnitPower37Source`): **Case-II II2**, Assumption
  II (proven membership-free in the Eichler module);
* `noSecondOrderIrregular` (`NoSecondOrderIrregularPair 37 32`): the user-owned second-order input.

Case I is discharged unconditionally (`fltCaseI_thirtyseven`); `¬ 37 ∣ h⁺` is the proven
`Sinnott.flt37_not_dvd_hPlus`.  The descent runs at **linear** measure (single-root quotients). -/
theorem fermatLastTheoremFor_thirtyseven_of_anchoredClassTrivial
    [NumberField.IsCMField (CyclotomicField 37 ℚ)]
    (caseII_classTrivial : CaseIIAdjacentAnchoredClassTrivial37)
    (caseII_exactUnit : WashingtonCaseIIExactQuotientUnitPower37Source)
    (noSecondOrderIrregular : NoSecondOrderIrregularPair 37 32) :
    FermatLastTheoremFor 37 :=
  fermatLastTheoremFor_thirtyseven_of_singleRootPrincipal
    (caseIIAdjacentSingleRootQuotientPrincipal37_of_anchoredClassTrivial37 caseII_classTrivial)
    caseII_exactUnit noSecondOrderIrregular

/-- **Fermat's Last Theorem for `37`, resting on the maximally-reduced `2`-torsion residual.**

`FermatLastTheoremFor 37` from:

* `caseII_classTwoTorsion` (`CaseIIAdjacentAnchoredClassTwoTorsion37`): **Case-II II1**, the
  anchored
  class `c = [𝔞(η)]·[𝔞(η₀)]⁻¹` squares to `1`.  This is the genuine irreducible obstruction: with
  the
  **proven** `c³⁷ = 1` and `c·σc = 1` (Vandiver), `c² = 1` forces `c = 1`.  No fractional ideals, no
  generators, no `σ`-stability — only the `2`-torsion vanishing of the `Cl⁻(𝓞 K)[37]` anchored
  class;
* `caseII_exactUnit` (`WashingtonCaseIIExactQuotientUnitPower37Source`): Assumption II;
* `noSecondOrderIrregular` (`NoSecondOrderIrregularPair 37 32`): the user-owned second-order input.

This is the sharpest current statement of the FLT-`37` Case-II II1 content. -/
theorem fermatLastTheoremFor_thirtyseven_of_anchoredClassTwoTorsion
    [NumberField.IsCMField (CyclotomicField 37 ℚ)]
    (caseII_classTwoTorsion : CaseIIAdjacentAnchoredClassTwoTorsion37)
    (caseII_exactUnit : WashingtonCaseIIExactQuotientUnitPower37Source)
    (noSecondOrderIrregular : NoSecondOrderIrregularPair 37 32) :
    FermatLastTheoremFor 37 :=
  fermatLastTheoremFor_thirtyseven_of_anchoredClassTrivial
    (caseIIAdjacentAnchoredClassTrivial37_of_twoTorsion caseII_classTwoTorsion)
    caseII_exactUnit noSecondOrderIrregular

end BernoulliRegular.FLT37.Eichler

end
