module

public import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal
public import Mathlib.NumberTheory.RamificationInertia.Galois

/-!
# Primes above `p` in the Stickelberger field

This file starts the `T027d3` prime-above-`p` infrastructure for the
Stickelberger field

`L = ℚ(ζ_{p(p-1)})`.

The setup remains abstract: we package the finite set of primes of `𝓞_L` lying
above `(p)`, choose one distinguished prime `P₀` from that set, and record the
basic facts that `P₀` is prime and lies over `(p)`.

The split Galois-action layer records the downstream identifications with the
concrete cyclotomic prime generated by `1 - ζ_p`.

For `T027d3b`, we use the standard Galois action on primes over a fixed prime
to show that every prime above `(p)` is Galois-conjugate to `P₀`.
-/

@[expose] public section

noncomputable section

open NumberField
open scoped Pointwise

namespace BernoulliRegular

section PrimesAboveP

variable (p : ℕ) [hp : Fact p.Prime]
  (L : Type*) [Field L] [NumberField L] [IsCyclotomicExtension {p * (p - 1)} ℚ L]

local notation "𝔭" => (Ideal.span ({(p : ℤ)} : Set ℤ))

/-- The finite set of prime ideals of `𝓞_L` lying above `(p)`. -/
noncomputable def primesAboveP : Finset (Ideal (𝓞 L)) :=
  IsDedekindDomain.primesOverFinset 𝔭 (𝓞 L)

omit [IsCyclotomicExtension {p * (p - 1)} ℚ L] in
lemma mem_primesAboveP_iff {P : Ideal (𝓞 L)} :
    P ∈ primesAboveP p L ↔ P ∈ Ideal.primesOver 𝔭 (𝓞 L) := by
  haveI : (Ideal.span ({(p : ℤ)} : Set ℤ) : Ideal ℤ).IsMaximal :=
    Int.ideal_span_isMaximal_of_prime p
  have hp_ne_bot : (𝔭 : Ideal ℤ) ≠ ⊥ := by
    simp [hp.out.ne_zero]
  exact _root_.IsDedekindDomain.mem_primesOverFinset_iff hp_ne_bot (𝓞 L)

omit [IsCyclotomicExtension {p * (p - 1)} ℚ L] in
lemma coe_primesAboveP :
    (↑(primesAboveP p L) : Set (Ideal (𝓞 L))) = Ideal.primesOver 𝔭 (𝓞 L) := by
  ext P
  rw [Finset.mem_coe, mem_primesAboveP_iff]

omit [IsCyclotomicExtension {p * (p - 1)} ℚ L] in
lemma primesAboveP_nonempty : (primesAboveP p L).Nonempty := by
  classical
  haveI : (Ideal.span ({(p : ℤ)} : Set ℤ) : Ideal ℤ).IsMaximal :=
    Int.ideal_span_isMaximal_of_prime p
  obtain ⟨⟨P, hP_prime, hP_over⟩⟩ :=
    (Ideal.span ({(p : ℤ)} : Set ℤ) : Ideal ℤ).nonempty_primesOver (S := 𝓞 L)
  exact ⟨P, (mem_primesAboveP_iff (p := p) (L := L)).2 ⟨hP_prime, hP_over⟩⟩

/-- A distinguished prime of `𝓞_L` above `(p)`. This is the abstract prime
`P₀` used by the factorization package; downstream Galois-action files relate
it to the concrete cyclotomic prime. -/
noncomputable def distinguishedPrimeAboveP : Ideal (𝓞 L) :=
  Classical.choose (primesAboveP_nonempty (p := p) (L := L))

omit [IsCyclotomicExtension {p * (p - 1)} ℚ L] in
lemma distinguishedPrimeAboveP_mem :
    distinguishedPrimeAboveP p L ∈ primesAboveP p L :=
  Classical.choose_spec (primesAboveP_nonempty (p := p) (L := L))

omit [IsCyclotomicExtension {p * (p - 1)} ℚ L] in
lemma distinguishedPrimeAboveP_mem_primesOver :
    distinguishedPrimeAboveP p L ∈ Ideal.primesOver 𝔭 (𝓞 L) :=
  (mem_primesAboveP_iff (p := p) (L := L)).1
    (distinguishedPrimeAboveP_mem (p := p) (L := L))

instance distinguishedPrimeAboveP_isPrime :
    (distinguishedPrimeAboveP p L).IsPrime :=
  (distinguishedPrimeAboveP_mem_primesOver (p := p) (L := L)).1

instance distinguishedPrimeAboveP_liesOver :
    (distinguishedPrimeAboveP p L).LiesOver 𝔭 :=
  (distinguishedPrimeAboveP_mem_primesOver (p := p) (L := L)).2

lemma exists_galois_smul_distinguishedPrimeAboveP_eq {P : Ideal (𝓞 L)}
    (hP : P ∈ primesAboveP p L) :
    ∃ σ : Gal(L / ℚ), σ • distinguishedPrimeAboveP p L = P := by
  let _ : IsGalois ℚ L :=
    IsCyclotomicExtension.isGalois (S := ({p * (p - 1)} : Set ℕ)) (K := ℚ) (L := L)
  let _ : IsGaloisGroup Gal(L / ℚ) ℚ L := inferInstance
  let _ : MulSemiringAction Gal(L / ℚ) (𝓞 L) := inferInstance
  have _ : IsGaloisGroup Gal(L / ℚ) ℤ (𝓞 L) := inferInstance
  have hP_over : P ∈ Ideal.primesOver 𝔭 (𝓞 L) := (mem_primesAboveP_iff (p := p) (L := L)).1 hP
  letI : P.IsPrime := hP_over.1
  letI : P.LiesOver 𝔭 := hP_over.2
  exact Ideal.exists_smul_eq_of_isGaloisGroup
    (A := ℤ) (B := 𝓞 L) (p := 𝔭)
    (P := distinguishedPrimeAboveP p L) (Q := P) (G := Gal(L / ℚ))

end PrimesAboveP

end BernoulliRegular
