module

public import Mathlib.NumberTheory.RamificationInertia.Ramification
public import BernoulliRegular.CyclotomicEmbedding
public import BernoulliRegular.GaussSum.PrimeFactorization.GaloisAction

/-!
# Local prime-above-`p` exponents for the lifted Gauss sum

Let

`L = ℚ(ζ_{p(p-1)})`.

This file starts the explicit prime factorisation of the lifted Gauss sum by
isolating the contribution of the distinguished prime `P₀` above `p`.

For `T027d4a`, we package the principal ideal generated by the canonical
integral lift `gaussSumIntegers p L χ`, define its exponent at `P₀` as the
`normalizedFactors` count of `distinguishedPrimeAboveP p L`, and prove the
local relation coming from the ideal identity

`(τ(χ)) · (τ(χ⁻¹)) = (p)`.

For `T027d4b`, we transport the same local relation to the decomposition-group
orbit `σ_a(P₀)` indexed by `a : (ZMod p)ˣ`.
-/

@[expose] public section

noncomputable section

open NumberField IsCyclotomicExtension
open scoped Pointwise

namespace BernoulliRegular

section PrimeAboveP

variable (p : ℕ) [hp : Fact p.Prime]
  (L : Type*) [Field L] [NumberField L]

local notation "𝔭" => (Ideal.span ({(p : ℤ)} : Set ℤ))

/-- Any prime of `𝓞_L` lying over `(p)` is nonzero. -/
lemma primeAboveP_ne_bot {P : Ideal (𝓞 L)} [P.LiesOver 𝔭] : P ≠ ⊥ := by
  intro hbot
  have hbotp : (Ideal.span ({(p : ℤ)} : Set ℤ) : Ideal ℤ) = ⊥ := by
    simpa [hbot] using Ideal.LiesOver.over (p := 𝔭) (P := P)
  exact Ideal.span_singleton_eq_bot.not.mpr
    (show (p : ℤ) ≠ 0 by exact_mod_cast hp.out.ne_zero) hbotp

end PrimeAboveP

section Valuation

variable (p : ℕ) [hp : Fact p.Prime]
  (L : Type*) [Field L] [NumberField L] [IsCyclotomicExtension {p * (p - 1)} ℚ L]

local notation "N" => p * (p - 1)
local notation "𝔭" => (Ideal.span ({(p : ℤ)} : Set ℤ))

/-- The principal ideal generated by the integral lift of the Gauss sum. -/
noncomputable abbrev gaussSumIdeal (χ : DirichletCharacter ℂ p) : Ideal (𝓞 L) :=
  Ideal.span ({gaussSumIntegers p L χ} : Set (𝓞 L))

lemma gaussSumIdeal_ne_bot {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) :
    gaussSumIdeal (p := p) (L := L) χ ≠ ⊥ :=
  Ideal.span_singleton_eq_bot.not.mpr
    (gaussSumIntegers_ne_zero (p := p) (L := L) hχ)

/-- The exponent of the distinguished prime `P₀` in the principal ideal
generated by the lifted Gauss sum. -/
noncomputable def distinguishedPrimeExponent (χ : DirichletCharacter ℂ p) : ℕ :=
  (UniqueFactorizationMonoid.normalizedFactors (gaussSumIdeal (p := p) (L := L) χ)).count
    (distinguishedPrimeAboveP p L)

/-- Every prime above `(p)` occurs in `(p)` with multiplicity `p - 1` in
`𝓞_L`, since `L = ℚ(ζ_{p(p-1)})` has ramification index `p - 1` at `p`. -/
lemma count_primeAboveP_span_p {P : Ideal (𝓞 L)} [P.IsPrime] [P.LiesOver 𝔭] :
    (UniqueFactorizationMonoid.normalizedFactors
        (Ideal.span ({(p : 𝓞 L)} : Set (𝓞 L)))).count P = p - 1 := by
  have hmap :
      Ideal.map (algebraMap ℤ (𝓞 L)) (Ideal.span ({(p : ℤ)} : Set ℤ)) =
        Ideal.span ({(p : 𝓞 L)} : Set (𝓞 L)) := by
    simpa using Ideal.map_span (algebraMap ℤ (𝓞 L)) ({(p : ℤ)} : Set ℤ)
  have hmap_ne_bot : Ideal.map (algebraMap ℤ (𝓞 L)) 𝔭 ≠ ⊥ := by
    rw [hmap]
    exact Ideal.span_singleton_eq_bot.not.mpr
      (show (p : 𝓞 L) ≠ 0 by exact_mod_cast hp.out.ne_zero)
  have hram :
      Ideal.ramificationIdx 𝔭 P = p - 1 := by
    rw [Ideal.ramificationIdx_eq_ramificationIdx' (q := P) (p := 𝔭)
      (hp := by simp [hp.out.ne_zero])]
    simpa using
      (Rat.ramificationIdx_eq
        (p := p) (n := N) (k := 0) (m := p - 1) (K := L) (P := P) (by simp)
        (Nat.not_dvd_of_pos_of_lt (Nat.sub_pos_of_lt hp.out.one_lt)
          (Nat.pred_lt hp.out.ne_zero)))
  rwa [Ideal.IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count
      (R := ℤ) (S := 𝓞 L) (p := 𝔭) (P := P) hmap_ne_bot inferInstance
      (primeAboveP_ne_bot (p := p) (L := L) (P := P)), hmap] at hram

/-- The exponent of a chosen prime above `(p)` in the principal ideal
generated by the lifted Gauss sum. -/
noncomputable def primeAbovePExponent (P : Ideal (𝓞 L)) (χ : DirichletCharacter ℂ p) : ℕ :=
  (UniqueFactorizationMonoid.normalizedFactors (gaussSumIdeal (p := p) (L := L) χ)).count P

/-- The local `χ` / `χ⁻¹` exponent relation at any prime above `(p)`. -/
lemma primeAbovePExponent_add_inv_eq_pred
    {P : Ideal (𝓞 L)} [P.IsPrime] [P.LiesOver 𝔭]
    {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) :
    primeAbovePExponent (p := p) (L := L) P χ +
        primeAbovePExponent (p := p) (L := L) P χ⁻¹ = p - 1 := by
  let Iχ : Ideal (𝓞 L) := gaussSumIdeal (p := p) (L := L) χ
  let Iχinv : Ideal (𝓞 L) := gaussSumIdeal (p := p) (L := L) χ⁻¹
  have hχinv : χ⁻¹ ≠ 1 := inv_ne_one.mpr hχ
  have hIχ : Iχ ≠ ⊥ := gaussSumIdeal_ne_bot (p := p) (L := L) hχ
  have hIχinv : Iχinv ≠ ⊥ := gaussSumIdeal_ne_bot (p := p) (L := L) hχinv
  have hcount :
      (UniqueFactorizationMonoid.normalizedFactors (Iχ * Iχinv)).count P = p - 1 := by
    calc
      (UniqueFactorizationMonoid.normalizedFactors (Iχ * Iχinv)).count P
          = (UniqueFactorizationMonoid.normalizedFactors
              (Ideal.span ({(p : 𝓞 L)} : Set (𝓞 L)))).count P := by
                simpa [Iχ, Iχinv, gaussSumIdeal] using
                  congrArg
                    (fun I : Ideal (𝓞 L) ↦
                      (UniqueFactorizationMonoid.normalizedFactors I).count P)
                    (gaussSum_ideal_mul_inv_eq_span_p (p := p) (L := L) hχ)
      _ = p - 1 := count_primeAboveP_span_p (p := p) (L := L) (P := P)
  rw [UniqueFactorizationMonoid.normalizedFactors_mul hIχ hIχinv, Multiset.count_add] at hcount
  simpa [primeAbovePExponent, Iχ, Iχinv, gaussSumIdeal] using hcount

lemma distinguishedPrimeExponent_add_inv_eq_pred
    {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) :
    distinguishedPrimeExponent (p := p) (L := L) χ +
        distinguishedPrimeExponent (p := p) (L := L) χ⁻¹ = p - 1 := by
  simpa [distinguishedPrimeExponent, primeAbovePExponent] using
    (primeAbovePExponent_add_inv_eq_pred (p := p) (L := L)
      (P := distinguishedPrimeAboveP p L) hχ)

/-- The exponent of the conjugate prime `σ_a(P₀)` in the principal ideal
generated by the lifted Gauss sum. -/
noncomputable def sigmaOfUnitPrimeExponent
    (a : (ZMod p)ˣ) (χ : DirichletCharacter ℂ p) : ℕ :=
  primeAbovePExponent (p := p) (L := L) ((sigmaOfUnit (p := p) L a) •
    distinguishedPrimeAboveP p L) χ

/-- The local `χ` / `χ⁻¹` exponent relation transported to the prime
`σ_a(P₀)`. -/
lemma sigmaOfUnitPrimeExponent_add_inv_eq_pred
    (a : (ZMod p)ˣ) {χ : DirichletCharacter ℂ p} (hχ : χ ≠ 1) :
    sigmaOfUnitPrimeExponent (p := p) (L := L) a χ +
        sigmaOfUnitPrimeExponent (p := p) (L := L) a χ⁻¹ = p - 1 := by
  simpa [sigmaOfUnitPrimeExponent] using
    (primeAbovePExponent_add_inv_eq_pred (p := p) (L := L)
      (P := (sigmaOfUnit (p := p) L a) • distinguishedPrimeAboveP p L) hχ)

end Valuation

end BernoulliRegular
