import HasseWeil.Foundation.Auxiliary.DivisionPolynomial
import HasseWeil.Foundation.Auxiliary.PullbackKaehler
import HasseWeil.Foundation.Basic
import HasseWeil.Foundation.ChordExpansion
import HasseWeil.Foundation.Curves.Map.BaseChange
import HasseWeil.Foundation.Curves.Basic
import HasseWeil.Foundation.Curves.Map.CurveMap
import HasseWeil.Foundation.Curves.Differentials
import HasseWeil.Foundation.Curves.Divisor.Divisors
import HasseWeil.Foundation.Curves.Valuation.DVR
import HasseWeil.Foundation.Curves.Divisor.ProjectiveDivisor
import HasseWeil.Foundation.Curves.Valuation.NormValuation
import HasseWeil.Foundation.Curves.FiniteOverKx
import HasseWeil.Foundation.Curves.GaloisAction
import HasseWeil.Foundation.Curves.NormBezout
import HasseWeil.Foundation.Curves.Divisor.ProjectiveTuple
import HasseWeil.Foundation.Curves.Ramification.RamificationAtInfinity
import HasseWeil.Foundation.Curves.Map.RationalMap
import HasseWeil.Foundation.Curves.Valuation.Valuation
import HasseWeil.FormalGroup.Associated
import HasseWeil.FormalGroup.CharP
import HasseWeil.FormalGroup.EvalGroup
import HasseWeil.FormalGroup.Height
import HasseWeil.FormalGroup.Hom
import HasseWeil.FormalGroup.InvariantDiff
import HasseWeil.FormalGroup.Inverse
import HasseWeil.FormalGroup.Logarithm
import HasseWeil.FormalGroup.MulByNat
import HasseWeil.FormalGroup.OrderSubst
import HasseWeil.FormalGroup.PadicValFactorial
import HasseWeil.FormalGroup.FormalGroupLawSpec
import HasseWeil.Foundation.InvariantDifferential
import HasseWeil.Isogeny.Endomorphism
import HasseWeil.Isogeny.Dual.Relation
import HasseWeil.Foundation.EC.MulByIntBaseCase
import HasseWeil.Foundation.EC.MulByIntComp
import HasseWeil.Foundation.EC.AffinePointMap
import HasseWeil.Foundation.EC.GenericPoint
import HasseWeil.Foundation.EC.GenericPointZsmul
import HasseWeil.Isogeny.Kernel
import HasseWeil.Isogeny.OrdTransport
import HasseWeil.Foundation.EC.MulByIntUnramified
import HasseWeil.Foundation.EC.PointMapSurjective
import HasseWeil.Foundation.DegreeQuadraticForm
import HasseWeil.Isogeny.Frobenius.PointCount
import HasseWeil.HasseBound.Parametric
import HasseWeil.HasseBound.PointCount
import HasseWeil.Foundation.EC.PointMap
import HasseWeil.HasseBound.Separability
import HasseWeil.HasseBound.TorsionCard
import HasseWeil.Foundation.DiscriminantBounds
import HasseWeil.Foundation.InvariantDifferentialPullback
import HasseWeil.Foundation.PullbackCoeff
import HasseWeil.Foundation.OmegaCoeffMulByIntFiniteField
import HasseWeil.Isogeny.OmegaCoeffViaFormalGroup
import HasseWeil.Isogeny.VerschiebungFactorization
import HasseWeil.Pic0.PicDualDegreeViaIsDualOf
import HasseWeil.Pic0.PicDualDegreeViaGeometricInjectivity
import HasseWeil.Pic0.PicDualClassMapMultiplicativity
import HasseWeil.Pic0.TheoremOfSquareDivisorForm
import HasseWeil.Pic0.PicDualPullbackTheoremOfSquare
import HasseWeil.HasseBound.WeilPairing.Assembly
import HasseWeil.HasseBound.WeilPairing.SigmaBridge
import HasseWeil.HasseBound.WeilPairing.WeilFunction
import HasseWeil.HasseBound.WeilPairing.RootsOfUnity
import HasseWeil.HasseBound.WeilPairing.Constancy
import HasseWeil.HasseBound.WeilPairing.PairingProps
import HasseWeil.HasseBound.WeilPairing.DetDeg
import HasseWeil.HasseBound.WeilPairing.HasseAssembly
import HasseWeil.HasseBound.WeilPairing.FrobMatrixData
import HasseWeil.HasseBound.WeilPairing.DivisorGalois
import HasseWeil.HasseBound.WeilPairing.FrobeniusDivisorGalois
import HasseWeil.HasseBound.WeilPairing.Scaling.FrobeniusGalois
import HasseWeil.HasseBound.WeilPairing.Scaling.OneSub
import HasseWeil.Isogeny.BaseChange.Concrete
import HasseWeil.HasseBound.WeilPairing.OneSubFrobeniusBaseChangeWitnesses
import HasseWeil.HasseBound.WeilPairing.OneSubDualDivisor
import HasseWeil.HasseBound.WeilPairing.PencilDualDivisor
import HasseWeil.Isogeny.SeparableWitnessReductions
import HasseWeil.HasseBound.WeilPairing.MapTranslateGenericAdditive
import HasseWeil.HasseBound.WeilPairing.FrobeniusGenericCovariance
import HasseWeil.HasseBound.WeilPairing.PencilSeparable
import HasseWeil.HasseBound.WeilPairing.Scaling.OneSubTransport
import HasseWeil.HasseBound.WeilPairing.PencilCovariance
import HasseWeil.HasseBound.WeilPairing.Scaling.Pencil
import HasseWeil.HasseBound.WeilPairing.PencilComapPointValuation
import HasseWeil.HasseBound

-- Silverman continuation (2026-06-09): faithful isogeny + III.4.8, the Tate module, isogeny classes
import HasseWeil.Foundation.Curves.Divisor.PushforwardDivisor
import HasseWeil.Isogeny.GroupHom.Basic
import HasseWeil.Isogeny.GroupHom.Descend
import HasseWeil.Isogeny.Dual.Morphism
import HasseWeil.Isogeny.Class
import HasseWeil.Isogeny.Label
import HasseWeil.Isogeny.Dual.Descent
import HasseWeil.Isogeny.Dual.Galois
import HasseWeil.Isogeny.Bridge
import HasseWeil.Foundation.Curves.Ramification.OrdAtInftyRamification
import HasseWeil.Isogeny.Ramification
import HasseWeil.Foundation.EC.GenericCovarianceGeneral
import HasseWeil.Isogeny.Dual.GaloisClosed
import HasseWeil.Isogeny.Frobenius.Dual
import HasseWeil.Isogeny.MulByInt.Composition
import HasseWeil.Isogeny.Dual.Reduction
import HasseWeil.Foundation.Curves.Ramification.RamificationFinite
import HasseWeil.Foundation.Curves.Fiber.GoodAffineLocus
import HasseWeil.Foundation.Curves.Fiber.GoodFiber
import HasseWeil.Foundation.EC.KernelCount
import HasseWeil.NTorsion.PadicLimZMod
import HasseWeil.NTorsion.TorsionPow
import HasseWeil.NTorsion.TorsionPowStructure
import HasseWeil.NTorsion.InverseSystem
import HasseWeil.NTorsion.TateModule
import HasseWeil.NTorsion.Representation
import HasseWeil.Isogeny.Dual.GaloisUnconditional
import HasseWeil.Foundation.Curves.Fiber.LocalizedDictionary
import HasseWeil.Foundation.EC.KernelCountGeneral
import HasseWeil.Foundation.Curves.Ramification.KernelOfDifferential
import HasseWeil.Isogeny.Frobenius.Twist
import HasseWeil.Isogeny.Frobenius.Factorization
import HasseWeil.Isogeny.Dual.Canonical
import HasseWeil.Isogeny.Adjoint
import HasseWeil.Isogeny.Dual.Additivity
import HasseWeil.Isogeny.MulByInt.Covariance
import HasseWeil.Isogeny.Dual.Universal
import HasseWeil.Isogeny.BaseChange.Morphism
import HasseWeil.Foundation.Curves.Map.CoordHomFinite
import HasseWeil.Foundation.OmegaCoeffMulByIntGeneral
