import HasseWeil.Auxiliary.DivisionPolynomial
import HasseWeil.Auxiliary.PullbackKaehler
import HasseWeil.Basic
import HasseWeil.ChordExpansion
import HasseWeil.Curves.BaseChange
import HasseWeil.Curves.Basic
import HasseWeil.Curves.CurveMap
import HasseWeil.Curves.Differentials
import HasseWeil.Curves.Divisors
import HasseWeil.Curves.DVR
import HasseWeil.Curves.ProjectiveDivisor
import HasseWeil.Curves.NormValuation
import HasseWeil.Curves.FiniteOverKx
import HasseWeil.Curves.GaloisAction
import HasseWeil.Curves.NormBezout
import HasseWeil.Curves.ProjectiveTuple
import HasseWeil.Curves.RamificationAtInfinity
import HasseWeil.Curves.RationalMap
import HasseWeil.Curves.Valuation
import HasseWeil.FormalGroup.Associated
import HasseWeil.FormalGroup.CharP
import HasseWeil.FormalGroup.EvalGroup
import HasseWeil.FormalGroup.Height
import HasseWeil.FormalGroup.Hom
import HasseWeil.FormalGroup.InvariantDiff
import HasseWeil.FormalGroup.Inverse
import HasseWeil.FormalGroup.Logarithm
import HasseWeil.FormalGroup.MulByNat
import HasseWeil.FormalGroup.OrderSubst
import HasseWeil.FormalGroup.PadicValFactorial
import HasseWeil.FormalGroupLawSpec
import HasseWeil.InvariantDifferential
import HasseWeil.Endomorphism
import HasseWeil.DualIsogeny
import HasseWeil.EC.MulByIntBaseCase
import HasseWeil.EC.MulByIntComp
import HasseWeil.EC.AffinePointMap
import HasseWeil.EC.GenericPoint
import HasseWeil.EC.GenericPointZsmul
import HasseWeil.EC.IsogenyKernel
import HasseWeil.EC.IsogenyOrdTransport
import HasseWeil.EC.MulByIntUnramified
import HasseWeil.EC.PointMapSurjective
import HasseWeil.DegreeQuadraticForm
import HasseWeil.Frobenius
import HasseWeil.Hasse.HasseBoundParametric
import HasseWeil.Hasse.PointFix
import HasseWeil.EC.PointMap
import HasseWeil.Hasse.Separability
import HasseWeil.Hasse.TorsionCard
import HasseWeil.DiscriminantBounds
import HasseWeil.InvariantDifferentialPullback
import HasseWeil.PullbackCoeff
import HasseWeil.OmegaCoeffMulByIntFiniteField
import HasseWeil.GapQfKernel
import HasseWeil.GapSpines
import HasseWeil.Pic0.PicDualDegreeViaIsDualOf
import HasseWeil.Pic0.PicDualDegreeViaGeometricInjectivity
import HasseWeil.Pic0.PicDualClassMapMultiplicativity
import HasseWeil.Pic0.TheoremOfSquareDivisorForm
import HasseWeil.Pic0.PicDualPullbackTheoremOfSquare
import HasseWeil.WeilPairing.Assembly
import HasseWeil.WeilPairing.TorsionSeparable
import HasseWeil.WeilPairing.SigmaBridge
import HasseWeil.WeilPairing.WeilFunction
import HasseWeil.WeilPairing.RootsOfUnity
import HasseWeil.WeilPairing.Constancy
import HasseWeil.WeilPairing.PairingProps
import HasseWeil.WeilPairing.DetDeg
import HasseWeil.WeilPairing.HasseAssembly
import HasseWeil.WeilPairing.FrobMatrixData
import HasseWeil.WeilPairing.FrobeniusGalois
import HasseWeil.WeilPairing.DivisorGalois
import HasseWeil.WeilPairing.FrobeniusDivisorGalois
import HasseWeil.WeilPairing.FrobeniusGaloisScaling
import HasseWeil.WeilPairing.OneSubScaling
import HasseWeil.WeilPairing.IsogenyBaseChangeConcrete
import HasseWeil.WeilPairing.OneSubFrobeniusBaseChangeWitnesses
import HasseWeil.WeilPairing.OneSubDualDivisor
import HasseWeil.WeilPairing.PencilDualDivisor
import HasseWeil.WeilPairing.IsogenyWitnessReductions
import HasseWeil.WeilPairing.MapTranslateGenericAdditive
import HasseWeil.WeilPairing.FrobeniusGenericCovariance
import HasseWeil.WeilPairing.PencilSeparable
import HasseWeil.WeilPairing.OneSubProjOrdTransport
import HasseWeil.WeilPairing.PencilCovariance
import HasseWeil.WeilPairing.PencilComapScaling
import HasseWeil.WeilPairing.PencilComapPointValuation
import HasseWeil.WeilPairing.HasseBound

-- Silverman continuation (2026-06-09): faithful isogeny + III.4.8, the Tate module, isogeny classes
import HasseWeil.Curves.PushforwardDivisor
import HasseWeil.EC.IsogenyAG.GroupHom
import HasseWeil.EC.IsogenyAG.GroupHomDescend
import HasseWeil.EC.IsogenyAG.Dual
import HasseWeil.EC.IsogenyAG.IsogenyClass
import HasseWeil.EC.IsogenyAG.IsogenyClassLabel
import HasseWeil.EC.IsogenyAG.DualDescent
import HasseWeil.EC.IsogenyAG.DualGalois
import HasseWeil.EC.IsogenyAG.Bridge
import HasseWeil.Curves.OrdAtInftyRamification
import HasseWeil.EC.IsogenyAG.RamificationInfty
import HasseWeil.WeilPairing.GenericCovarianceGeneral
import HasseWeil.EC.IsogenyAG.DualGaloisClosed
import HasseWeil.EC.IsogenyAG.FrobeniusDual
import HasseWeil.EC.IsogenyAG.MulByIntPullbackComp
import HasseWeil.EC.IsogenyAG.DualReduction
import HasseWeil.Curves.RamificationFinite
import HasseWeil.Curves.GoodAffineLocus
import HasseWeil.Curves.GoodFiber
import HasseWeil.EC.KernelCount
import HasseWeil.TateModule.PadicLimZMod
import HasseWeil.TateModule.TorsionPow
import HasseWeil.TateModule.TorsionPowStructure
import HasseWeil.TateModule.InverseSystem
import HasseWeil.TateModule.TateModule
import HasseWeil.TateModule.Representation
import HasseWeil.EC.IsogenyAG.DualGaloisDataUnconditional
import HasseWeil.Curves.LocalizedDictionary
import HasseWeil.EC.KernelCountGeneral
import HasseWeil.Curves.KernelOfDifferential
import HasseWeil.EC.IsogenyAG.FrobeniusTwist
import HasseWeil.EC.IsogenyAG.TwistedFactorization
import HasseWeil.EC.IsogenyAG.CanonicalDual
import HasseWeil.WeilPairing.AdjointTransfer
import HasseWeil.EC.IsogenyAG.DualAdditivity
import HasseWeil.EC.IsogenyAG.CovarianceDischarge
import HasseWeil.WeilPairing.OneSubPullbackEvaluation
import HasseWeil.EC.IsogenyAG.DualUniversal
import HasseWeil.EC.IsogenyAG.BaseChange
import HasseWeil.Curves.CoordHomFinite
import HasseWeil.OmegaCoeffMulByIntGeneral
