import BernoulliRegular.FLT37.LehmerVandiver.PollaczekUnit

/-!
# Washington §8.1 Lemma 8.1: the real cyclotomic generators `ξ_a`, for `p = 37`

This file builds **Washington's Lemma 8.1(a)** (Washington *Introduction to Cyclotomic Fields*,
2nd ed., GTM 83, §8.1, p. 144) for the cyclotomic field `K = ℚ(ζ_p)` with `p` an odd prime: the
real cyclotomic units of `ℚ(ζ_p)⁺` are generated by `-1` and the units

  `ξ_a = ζ^{(1-a)/2} · (1 - ζ^a)/(1 - ζ)`,    `1 < a < ½p`, `(a, p) = 1`.

Here `ζ = ζ_p = zeta p ℚ K` is the canonical primitive root (the one underlying `cyclotomicUnit`),
and the half-integer exponent `(1-a)/2` is interpreted in `ℤ/pℤ` via the inverse `2⁻¹ = (p+1)/2` of
`2` (legitimate since `p` is odd): we realise `ζ^{(1-a)/2}` as the genuine unit power
`(zeta_spec p ℚ K).unit'^{(1-a)·2⁻¹}` of the root-of-unity unit `ζ_p`.  The "real units" observation
of Washington p. 144 is that `ξ_a = ζ^{(1-a)/2}(1-ζ^a)/(1-ζ)` is real (totally real), because
`ζ^{(1-a)/2}(1-ζ^a)/(1-ζ) = ± sin(πa/n)/sin(π/n)`.

The arithmetic content we need downstream (Washington Lemma 9.8, §9.1) is the **Lemma 8.1 ratio
identity** (Washington p. 179):

  `(ζ^a - ζ^j)/(1 - ζ^{a+j}) = -ξ_{a-j} / ξ_{a+j} = -ξ_{a+j}^{-1} · ξ_{a-j}`,

which we prove in the cross-multiplied (division-free) form

  `(ζ^a - ζ^j) · ξ_{a+j} = -(1 - ζ^{a+j}) · ξ_{a-j}`   in `𝓞 K`,

valid for all integer shifts `a, j` (the indices being interpreted mod `p`).  This is the bridge by
which Washington's cyclic-group `p`-th-power congruence on `(ζ^a-ζ^j)/(1-ζ^{a+j})` transfers to the
`ξ` units and telescopes (Lemma 9.8 steps 5–7).

## What is proven here (axiom-clean Lean)

* `xiUnit` — the unit `ξ_a ∈ (𝓞 K)ˣ` of Lemma 8.1 (the `ζ`-power prefactor times the cyclotomic
  unit `(1-ζ^a)/(1-ζ)`), for `a` coprime to `p`.
* `xiUnit_val`, `xiUnit_val'` — its underlying ring element.
* `zetaPow`, `zetaPow_add`, `zetaPow_congr` — integer `ζ`-powers (taken in `(𝓞 K)ˣ`) and their
  multiplicativity / mod-`p` exponent reduction.
* `halfExp_shift` — the half-power exponent shift `halfExp d ≡ halfExp s + j (mod p)`.
* `xi_ratio_identity` — the **Lemma 8.1 ratio identity** in cross-multiplied form (the bridge to
  Lemma 9.8).

## References
* Washington, *Introduction to Cyclotomic Fields*, 2nd ed., GTM 83, §8.1, Lemma 8.1 (p. 144), and
  §9.1–9.2, Lemma 9.8 (p. 178–179, the `ξ`-identity / telescoping).
-/

@[expose] public section

noncomputable section

open NumberField IsCyclotomicExtension

namespace BernoulliRegular.FLT37

variable (p : ℕ) [hp : Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

section Lemma81

variable {p K}

/-- The half-power exponent `(1 - a)·2⁻¹` interpreted as an integer.  We use the explicit inverse
`2⁻¹ = (p+1)/2` of `2` modulo `p` (`p` odd), so that `2·((p+1)/2) ≡ 1 (mod p)` and
`(ζ^{halfExp a})^2 = ζ^{1-a}`. -/
def halfExp (a : ℤ) : ℤ := (1 - a) * ((p + 1) / 2 : ℕ)

/-- `2 · ((p+1)/2) = p + 1` for `p` odd, so `(p+1)/2` is a genuine inverse of `2` mod `p`. -/
theorem two_mul_succ_div_two (hp_odd : p ≠ 2) : 2 * ((p + 1) / 2) = p + 1 := by
  have hodd : Odd p := hp.1.odd_of_ne_two hp_odd
  obtain ⟨r, hr⟩ := hodd
  omega

end Lemma81

section XiUnit

variable [NeZero p]

/-- The canonical root-of-unity unit `ζ_p ∈ (𝓞 K)ˣ`
(`((zeta_spec p ℚ K).toInteger_isPrimitiveRoot.isUnit (NeZero.ne p)).unit`), the same `ζ`
underlying `cyclotomicUnit`. -/
noncomputable abbrev zetaU : (𝓞 K)ˣ :=
  ((zeta_spec p ℚ K).toInteger_isPrimitiveRoot.isUnit (NeZero.ne p)).unit

/-- **Washington's Lemma 8.1 unit `ξ_a`.**  For `a` coprime to `p`,

  `ξ_a = ζ^{(1-a)/2} · (1 - ζ^a)/(1 - ζ) ∈ (𝓞 K)ˣ`,

realised as the unit power `ζ^{halfExp a}` of the canonical root-of-unity unit `ζ_p` times the
cyclotomic unit `cyclotomicUnitUnit p K a`.  The exponent `halfExp a = (1-a)·(p+1)/2` realises the
half-integer `ζ`-power.  We use the canonical `ζ = zeta p ℚ K` (matching `cyclotomicUnit`). -/
noncomputable def xiUnit (a : ℕ) (ha : a.Coprime p) : (𝓞 K)ˣ :=
  zetaU p K ^ (halfExp (p := p) (a : ℤ)) * cyclotomicUnitUnit p K a ha hp.1.two_le

/-- The underlying ring element of `ξ_a` is `ζ^{halfExp a} · (1-ζ^a)/(1-ζ)`. -/
theorem xiUnit_val (a : ℕ) (ha : a.Coprime p) :
    (xiUnit p K a ha : 𝓞 K) =
      (zetaU p K ^ (halfExp (p := p) (a : ℤ)) : (𝓞 K)ˣ) * cyclotomicUnit p K a := by
  unfold xiUnit
  rw [Units.val_mul, cyclotomicUnitUnit_val]

/-! ### `ζ`-power exponent reduction modulo `p`

The root-of-unity unit `ζ_p` has order exactly `p` in `(𝓞 K)ˣ`, so two `ζ`-powers agree iff the
exponents are congruent mod `p`.  This is the engine for the half-power exponent arithmetic in the
Lemma 8.1 ratio identity. -/

omit hp in
/-- `ζ_p` is a primitive `p`-th root of unity *in the unit group* `(𝓞 K)ˣ`. -/
theorem unit'_isPrimitiveRoot : IsPrimitiveRoot (zetaU p K) p :=
  IsPrimitiveRoot.coe_units_iff.mp <| by
    rw [zetaU, IsUnit.unit_spec]; exact (zeta_spec p ℚ K).toInteger_isPrimitiveRoot

omit hp in
/-- The order of the root-of-unity unit `ζ_p` is exactly `p`. -/
theorem orderOf_unit' : orderOf (zetaU p K) = p :=
  (unit'_isPrimitiveRoot p K).eq_orderOf.symm

omit hp in
/-- **`ζ`-power exponent congruence:** if `a ≡ b (mod p)` then `ζ^a = ζ^b`. -/
theorem unit'_zpow_congr {a b : ℤ} (h : (p : ℤ) ∣ a - b) : (zetaU p K) ^ a = (zetaU p K) ^ b := by
  have hord : (orderOf (zetaU p K) : ℤ) ∣ a - b := by rw [orderOf_unit' p K]; exact h
  exact (orderOf_dvd_sub_iff_zpow_eq_zpow).mp hord

/-- The element `ζ^e ∈ 𝓞 K` for an *integer* exponent `e`, realised as the value of the unit power
`ζ_p^e`.  (The ring `𝓞 K` has no `ℤ`-power, so integer `ζ`-powers are taken in the unit group and
coerced.)  Mod `p` the exponent is irrelevant: `zetaPow` only depends on `e mod p`. -/
noncomputable def zetaPow (e : ℤ) : 𝓞 K := (((zetaU p K) ^ e : (𝓞 K)ˣ) : 𝓞 K)

omit hp in
/-- `ζ^{e₁+e₂} = ζ^{e₁}·ζ^{e₂}` (multiplicativity of `zetaPow`). -/
theorem zetaPow_add (e₁ e₂ : ℤ) :
    zetaPow p K (e₁ + e₂) = zetaPow p K e₁ * zetaPow p K e₂ := by
  unfold zetaPow; rw [zpow_add, Units.val_mul]

omit hp in
/-- `ζ^{(k : ℤ)} = ζ^k` (the integer power of the unit value agrees with the natural power). -/
theorem zetaPow_natCast (k : ℕ) :
    zetaPow p K (k : ℤ) = ((zetaU p K) : 𝓞 K) ^ k := by
  unfold zetaPow; rw [zpow_natCast, Units.val_pow_eq_pow_val]

omit hp in
/-- `ζ^e ≠ 0` (it is a unit). -/
theorem zetaPow_ne_zero (e : ℤ) : zetaPow p K e ≠ 0 := by
  unfold zetaPow; exact ((zetaU p K) ^ e).ne_zero

omit hp in
/-- **`ζ`-power exponent congruence (element form):** `ζ^{e₁} = ζ^{e₂}` if `e₁ ≡ e₂ (mod p)`. -/
theorem zetaPow_congr {e₁ e₂ : ℤ} (h : (p : ℤ) ∣ e₁ - e₂) :
    zetaPow p K e₁ = zetaPow p K e₂ := by
  unfold zetaPow; rw [unit'_zpow_congr p K h]

/-- The underlying ring element of `ξ_a`, written via `zetaPow`:
`ξ_a = ζ^{halfExp a} · cyclotomicUnit a`. -/
theorem xiUnit_val' (a : ℕ) (ha : a.Coprime p) :
    (xiUnit p K a ha : 𝓞 K) = zetaPow p K (halfExp (p := p) (a : ℤ)) * cyclotomicUnit p K a := by
  rw [xiUnit_val]; rfl

/-! ### The Lemma 8.1 ratio identity (the bridge to Lemma 9.8)

Washington (p. 179) records the identity

  `(ζ^a - ζ^j)/(1 - ζ^{a+j}) = -ξ_{a-j}/ξ_{a+j}`.

We prove its cross-multiplied (division-free) form

  `(ζ^a - ζ^j)·ξ_{a+j} = -(1 - ζ^{a+j})·ξ_{a-j}`   in `𝓞 K`,

parametrised by integer exponents `a, j` and concrete coprime natural indices `s ≡ a+j`,
`d ≡ a-j (mod p)` realising the residues `ζ^{a+j} = ζ^s`, `ζ^{a-j} = ζ^d`.

The proof multiplies through by `ζ - 1` (a non-zero-divisor in the domain `𝓞 K`), uses
`(ζ-1)·cyclotomicUnit k = ζ^k - 1`, and reduces the resulting `ζ`-power identity to the single
fact `ζ^{2·2⁻¹} = ζ`, i.e. `2·((p+1)/2) ≡ 1 (mod p)`.  -/

omit hp in
/-- The integer-exponent congruence underlying `ζ^e = ζ^d`: from the unit equality
`ζ_p^e = ζ_p^d` we extract `p ∣ d - e`. -/
theorem dvd_of_unit'_zpow_eq {e : ℤ} {d : ℕ}
    (h : (zetaU p K) ^ e = (zetaU p K) ^ (d : ℤ)) :
    (p : ℤ) ∣ (d : ℤ) - e := by
  have hord : (orderOf (zetaU p K) : ℤ) ∣ e - (d : ℤ) :=
    orderOf_dvd_sub_iff_zpow_eq_zpow.mpr h
  rw [orderOf_unit' p K] at hord
  rwa [← dvd_neg, neg_sub] at hord

omit [NeZero p] in
/-- `2·((p+1)/2) = p+1` over `ℤ` (the cast of the natural identity). -/
theorem two_mul_inv2_int (hp_odd : p ≠ 2) :
    (2 : ℤ) * ((p + 1) / 2 : ℕ) = (p : ℤ) + 1 := by
  have hnat := two_mul_succ_div_two (p := p) hp_odd
  omega

omit [NeZero p] in
/-- The half-power exponent shift `halfExp d ≡ halfExp s + j (mod p)` whenever `s - d ≡ 2j (mod p)`.
This is the single arithmetic fact (`(s-d)·2⁻¹ ≡ j`) driving the Lemma 8.1 ratio cancellation:
`halfExp d - halfExp s - j = (s-d)*2⁻¹ - j`, and `(s-d)*2⁻¹ ≡ j` since `2*2⁻¹ ≡ 1` and
`s-d ≡ 2j`. -/
theorem halfExp_shift (hp_odd : p ≠ 2) {j : ℤ} {s d : ℕ}
    (hdvd : (p : ℤ) ∣ ((s : ℤ) - (d : ℤ)) - 2 * j) :
    (p : ℤ) ∣ halfExp (p := p) (d : ℤ) - (halfExp (p := p) (s : ℤ) + j) := by
  have h2 := two_mul_inv2_int (p := p) hp_odd
  obtain ⟨t, ht⟩ := hdvd
  -- `s - d = 2j + p·t`.  Then `2·(halfExp d - halfExp s - j) = (s-d)(p+1) - 2j = p·(...)`.
  unfold halfExp
  -- `(1-d)c - ((1-s)c + j) = (s-d)c - j = (2j+pt)c - j = j(2c-1) + ptc = p·(j + tc)`,
  -- using `2c = p+1` (so `2c - 1 = p`).  Witness: `j + t·c`.
  refine ⟨j + t * ((p + 1) / 2 : ℕ), ?_⟩
  have hsd : (s : ℤ) - (d : ℤ) = 2 * j + (p : ℤ) * t := by linarith [ht]
  -- (1-d)c - ((1-s)c + j) - p(j + tc) = c·((s-d) - 2j - pt) + j·(2c - (p+1)) = 0.
  linear_combination ((p + 1) / 2 : ℕ) * hsd + j * h2

set_option maxHeartbeats 800000 in
-- The final `ring` over the many distinct `ζ`-power atoms is heartbeat-heavy; raise the limit.
/-- **Washington's Lemma 8.1 ratio identity, cross-multiplied (general odd prime `p`).**

For integers `a, j` and natural numbers `s, d` coprime to `p` with
`ζ^{a+j} = ζ^s`, `ζ^{a-j} = ζ^d` (i.e. `s ≡ a+j`, `d ≡ a-j (mod p)`),

  `(ζ^a - ζ^j) · ξ_s = -(1 - ζ^s) · ξ_d`     in `𝓞 K`,

where `ξ_s, ξ_d` are Washington's real cyclotomic units (`xiUnit`) and `ζ^e = zetaPow e`.  This is
the bridge that transfers the cyclic-group `p`-th-power congruence on `(ζ^a-ζ^j)/(1-ζ^{a+j})` to the
`ξ` units (Washington Lemma 9.8, steps 5–7, p. 179).

The proof multiplies both sides by `ζ - 1` (a non-zero-divisor in the domain `𝓞 K`), telescopes the
cyclotomic factors via `(ζ-1)·cyclotomicUnit k = ζ^k - 1`, and the resulting pure `ζ`-power identity
collapses using the single shift `halfExp d ≡ halfExp s + j (mod p)` (`halfExp_shift`). -/
theorem xi_ratio_identity (hp_odd : p ≠ 2) (a j : ℤ) (s d : ℕ)
    (hs : s.Coprime p) (hd : d.Coprime p)
    (hs_eq : (zetaU p K) ^ (a + j) = (zetaU p K) ^ (s : ℤ))
    (hd_eq : (zetaU p K) ^ (a - j) = (zetaU p K) ^ (d : ℤ)) :
    (zetaPow p K a - zetaPow p K j) * (xiUnit p K s hs : 𝓞 K) =
      -(1 - zetaPow p K (s : ℤ)) * (xiUnit p K d hd : 𝓞 K) := by
  -- `ζ - 1` is a non-zero-divisor.
  have hne : (((zetaU p K) : 𝓞 K) - 1) ≠ 0 := (zeta_spec p ℚ K).zeta_sub_one_prime'.ne_zero
  -- Abbreviations for the half-power exponents of the two `ξ` factors.
  set Hs : ℤ := halfExp (p := p) (s : ℤ) with hHs
  set Hd : ℤ := halfExp (p := p) (d : ℤ) with hHd
  -- The `ζ`-power residue facts.
  have hsval : zetaPow p K (a + j) = zetaPow p K (s : ℤ) := by unfold zetaPow; rw [hs_eq]
  have hdval : zetaPow p K (a - j) = zetaPow p K (d : ℤ) := by unfold zetaPow; rw [hd_eq]
  -- It suffices after right-multiplication by `ζ - 1`.
  apply mul_right_cancel₀ hne
  -- Expand `ξ` values.
  rw [xiUnit_val', xiUnit_val']
  -- Telescope the cyclotomic factors: `(ζ-1)·cyc k = ζ^k - 1 = ζ^{(k:ℤ)} - 1`.
  have hcyc_s : (((zetaU p K) : 𝓞 K) - 1) * cyclotomicUnit p K s = zetaPow p K (s : ℤ) - 1 := by
    rw [zetaPow_natCast]; exact zeta_sub_one_mul_cyclotomicUnit p K s
  have hcyc_d : (((zetaU p K) : 𝓞 K) - 1) * cyclotomicUnit p K d = zetaPow p K (d : ℤ) - 1 := by
    rw [zetaPow_natCast]; exact zeta_sub_one_mul_cyclotomicUnit p K d
  -- Push `(ζ-1)` inside to hit the telescopes; rewrite `ζ^s`, `ζ^d` by the residues.
  rw [show (zetaPow p K a - zetaPow p K j) * (zetaPow p K Hs * cyclotomicUnit p K s) *
        (((zetaU p K) : 𝓞 K) - 1) =
        (zetaPow p K a - zetaPow p K j) * zetaPow p K Hs *
          ((((zetaU p K) : 𝓞 K) - 1) * cyclotomicUnit p K s) by ring,
    show -(1 - zetaPow p K (s : ℤ)) * (zetaPow p K Hd * cyclotomicUnit p K d) *
        (((zetaU p K) : 𝓞 K) - 1) =
        -(1 - zetaPow p K (s : ℤ)) * zetaPow p K Hd *
          ((((zetaU p K) : 𝓞 K) - 1) * cyclotomicUnit p K d) by ring,
    hcyc_s, hcyc_d, ← hsval, ← hdval]
  -- The residue `s - d ≡ 2j (mod p)`, from `s ≡ a+j`, `d ≡ a-j`.
  have hsd2j : (p : ℤ) ∣ ((s : ℤ) - (d : ℤ)) - 2 * j := by
    have hs1 : (p : ℤ) ∣ (s : ℤ) - (a + j) := dvd_of_unit'_zpow_eq p K hs_eq
    have hd1 : (p : ℤ) ∣ (d : ℤ) - (a - j) := dvd_of_unit'_zpow_eq p K hd_eq
    have : ((s : ℤ) - (d : ℤ)) - 2 * j = ((s : ℤ) - (a + j)) - ((d : ℤ) - (a - j)) := by ring
    rw [this]; exact dvd_sub hs1 hd1
  -- The half-power shift `Hd ≡ Hs + j (mod p)`.
  have hshift : (p : ℤ) ∣ Hd - (Hs + j) := by
    rw [hHd, hHs]; exact halfExp_shift (p := p) hp_odd hsd2j
  -- Master `ζ`-power facts:
  --   MS : ζ^{a+j} = ζ^a · ζ^j
  --   MF : ζ^{Hd}        = ζ^{Hs} · ζ^j        (halfExp shift)
  --   MG : ζ^{Hd}·ζ^{a-j} = ζ^{Hs} · ζ^a       (halfExp shift)
  have MS : zetaPow p K (a + j) = zetaPow p K a * zetaPow p K j := zetaPow_add p K a j
  have MF : zetaPow p K Hd = zetaPow p K Hs * zetaPow p K j := by
    rw [← zetaPow_add p K]; exact zetaPow_congr p K hshift
  have MG : zetaPow p K Hd * zetaPow p K (a - j) = zetaPow p K Hs * zetaPow p K a := by
    rw [← zetaPow_add p K, ← zetaPow_add p K]
    apply zetaPow_congr p K
    -- (Hd + (a-j)) - (Hs + a) = Hd - (Hs+j) ≡ 0 (mod p)
    have : Hd + (a - j) - (Hs + a) = Hd - (Hs + j) := by ring
    rw [this]; exact hshift
  -- Finish: expand `ζ^{a+j}`, the `ζ^{Hd}` terms, then `ring`.
  rw [MS, show -(1 - zetaPow p K a * zetaPow p K j) * zetaPow p K Hd * (zetaPow p K (a - j) - 1) =
        -(1 - zetaPow p K a * zetaPow p K j) *
          (zetaPow p K Hd * zetaPow p K (a - j) - zetaPow p K Hd) by ring,
    MG, MF]
  ring

end XiUnit

end BernoulliRegular.FLT37

end
