import Verso
import VersoManual
import VersoBlueprint
import BernoulliRegular
import BernoulliRegularBlueprint.Refs
import BernoulliRegularBlueprint.TexPrelude

open Verso.Genre
open Verso.Genre.Manual
open Informal


#doc (Manual) "Cyclotomic units and the plus class number" =>

This chapter records the cyclotomic-unit part of the proof. The purpose is to
connect Bernoulli non-divisibility with the plus class number. Throughout this
chapter $`p` is an odd prime, $`K` is a field isomorphic to $`\mathbb{Q}(\zeta_p)`,
and $`K^+ = \mathbb{Q}(\zeta_p)^+` is its maximal real subfield. The group of real
units is $`E^+ := (\mathcal{O}_{K^+})^\times`. Thus $`E^+` is the full unit group of
the maximal real subfield.

# Real cyclotomic units

Let $`u_a = \frac{1-\zeta_p^a}{1-\zeta_p}` ($`a \in \mathbb{Z}`, $`(a,p)=1`) be the
usual cyclotomic unit in $`\mathcal{O}_K^\times`. For the real subfield one uses the
conjugation-fixed unit
$$`\varepsilon_a = u_a\,\overline{u_a} = \zeta_p^{\,1-a} \left(\frac{1-\zeta_p^a}{1-\zeta_p}\right)^2 .`
It lies in $`K^+` because complex conjugation fixes it, and it is a unit because both
$`u_a` and $`\overline{u_a}` are units. The range used for prime conductor is
$`2 \le a \le \frac{p-1}{2}`. In that range $`0<a<p`, so a prime $`p` cannot divide
$`a`; hence $`(a,p)=1` and the above cyclotomic unit is defined.

:::lemma_ "lem:real-cyclotomic-index-coprime" (lean := "BernoulliRegular.realCyclotomicUnit_index_coprime")
**Coprimality of the standard indices.** Let $`2 \le a \le (p-1)/2`. Then $`a` is
coprime to $`p`.

{uses "def:galois-cyclotomic"}[]
:::

:::proof "lem:real-cyclotomic-index-coprime"
The lower bound gives $`a>0`. The upper bound gives $`a \le (p-1)/2 < p`, so $`a<p`.
If $`p` divided $`a`, then since $`a` is positive we would have $`p \le a`,
contradicting $`a<p`. Because $`p` is prime, not being divisible by $`p` is
equivalent to being coprime to $`p`.
:::

:::definition "def:real-cyclotomic-unit" (lean := "BernoulliRegular.realCyclotomicUnit")
**Real cyclotomic unit.** For $`2 \le a \le (p-1)/2`, the unit
$`\varepsilon_a \in E^+` is the unique real unit whose image in
$`\mathcal{O}_K^\times` is the conjugation-fixed product $`u_a\overline{u_a}`.

{uses "def:cm-real-subfield"}[] {uses "lem:real-cyclotomic-index-coprime"}[]
:::

After extension of scalars from $`\mathcal{O}_{K^+}` to $`\mathcal{O}_K`, this unit
is exactly the standard conjugation-fixed product $`u_a\overline{u_a}`, and is fixed
by complex conjugation.

# The cyclotomic-unit subgroups

There are two closely related real cyclotomic-unit subgroups. The logarithmic
saturation argument is most convenient for the squared family $`\varepsilon_a`. The
index theorem is naturally stated for the normalised family
$$`\eta_a = \zeta_p^{(1-a)/2}\frac{1-\zeta_p^a}{1-\zeta_p}, \qquad \eta_a^2=\varepsilon_a .`
Here $`(1-a)/2` is understood modulo $`p`, using that $`2` is invertible modulo the
odd prime $`p`.

:::definition "def:CPlus-squared" (lean := "BernoulliRegular.CPlus")
**The squared cyclotomic-unit subgroup.** Let $`g=(p-3)/2`. The subgroup
$`C^+_{\mathrm{sq}}\le E^+` is generated by $`-1` and by the units
$`\varepsilon_2,\varepsilon_3,\ldots,\varepsilon_{(p-1)/2}`. Equivalently,
$$`C^+_{\mathrm{sq}} = \left\langle -1,\ \varepsilon_a\ (2\le a\le (p-1)/2) \right\rangle .`

{uses "def:real-cyclotomic-unit"}[]
:::

The finite index set may be written as $`i\in \operatorname{Fin}((p-3)/2)`,
$`a=i+2`. Thus the listed units are precisely the nontrivial real cyclotomic
generators in the prime-conductor range, together with the torsion unit $`-1`.

:::definition "def:CPlus-normalized" (lean := "BernoulliRegular.normalizedCPlus")
**The normalised cyclotomic-unit subgroup.** The subgroup
$`C^+_{\mathrm{norm}}\le E^+` is generated by $`-1` and by the normalised real
cyclotomic units $`\eta_2,\eta_3,\ldots,\eta_{(p-1)/2}`.

{uses "def:real-cyclotomic-unit"}[]
:::

The relation between the two families is exactly the relation $`\eta_a^2=\varepsilon_a`.

:::lemma_ "lem:normalized-square" (lean := "BernoulliRegular.normalizedCPlusGenerator_sq_eq_CPlusGenerator")
**Squares of normalised generators.** For each standard generator index $`a`,
$`\eta_a^2=\varepsilon_a`.

{uses "def:CPlus-squared"}[] {uses "def:CPlus-normalized"}[]
:::

:::proof "lem:normalized-square"
This is the elementary identity
$$`\left( \zeta_p^{(1-a)/2}\frac{1-\zeta_p^a}{1-\zeta_p} \right)^2 = \zeta_p^{1-a} \left(\frac{1-\zeta_p^a}{1-\zeta_p}\right)^2 = u_a\overline{u_a}.`
The last equality is the standard computation
$`\overline{u_a} = \frac{1-\zeta_p^{-a}}{1-\zeta_p^{-1}} = \zeta_p^{1-a}\frac{1-\zeta_p^a}{1-\zeta_p}`.
:::

:::lemma_ "lem:CPlus-index-normalized-index" (lean := "BernoulliRegular.CPlus_index_prime_dvd_iff_normalizedCPlus_index_prime_dvd, BernoulliRegular.subgroup_index_prime_dvd_iff_of_relIndex_dvd_two_pow")
**Odd-primary comparison of the two indices.** For odd $`p`,
$$`p \mid [E^+ : C^+_{\mathrm{sq}}] \quad\Longleftrightarrow\quad p \mid [E^+ : C^+_{\mathrm{norm}}].`

{uses "def:CPlus-squared"}[] {uses "def:CPlus-normalized"}[] {uses "lem:normalized-square"}[]
:::

:::proof "lem:CPlus-index-normalized-index"
The subgroup $`C^+_{\mathrm{sq}}` is contained in $`C^+_{\mathrm{norm}}`, because
$`-1` is a normalised generator and each squared generator $`\varepsilon_a` is the
square of the normalised generator $`\eta_a`. Conversely, every class in
$`C^+_{\mathrm{norm}}/C^+_{\mathrm{sq}}` has square one: it is enough to check this on
the generators, and it follows from $`\eta_a^2=\varepsilon_a` and $`(-1)^2=1`. Hence
the relative index $`[C^+_{\mathrm{norm}}:C^+_{\mathrm{sq}}]` divides a power of $`2`.
The two ambient indices differ by this relative index. Since $`p` is odd, $`p` does
not divide any power of $`2`. Therefore the $`p`-primary divisibility of
$`[E^+ : C^+_{\mathrm{sq}}]` and $`[E^+ : C^+_{\mathrm{norm}}]` is the same.
:::

# Exact p-saturation

Let $`G` be an abelian group and $`H\le E\le G`. We use the exact image of the
$`p`-th power map: $`H^p := \{h^p : h\in H\}`. This is not a closure or saturation of
the image; it is the literal subgroup of $`p`-th powers.

:::definition "def:p-saturated" (lean := "BernoulliRegular.pSaturated, BernoulliRegular.pPowerSubgroup")
**Exact $`p`-saturation.** The subgroup $`H` is $`p`-saturated in $`E` if $`H\le E`
and $`H\cap E^p \subseteq H^p`. Equivalently, whenever $`x\in H` and $`x=y^p` for
some $`y\in E`, there exists $`z\in H` such that $`x=z^p`.
:::

The useful criterion for $`C^+_{\mathrm{sq}}` is stated in terms of exponent vectors.
Every element of $`C^+_{\mathrm{sq}}` can be written as
$`(-1)^s\prod_{a=2}^{(p-1)/2}\varepsilon_a^{e_a}`, $`s,e_a\in\mathbb{Z}`. The
following criterion uses these exponent vectors.

:::theorem "thm:CPlus-pSaturated-exponents" (lean := "BernoulliRegular.exists_CPlusExponentProduct_of_mem_CPlus, BernoulliRegular.CPlus_pSaturated_of_generator_exponents_modP_zero, BernoulliRegular.CPlusExponentProduct_mem_CPlus, BernoulliRegular.neg_one_zpow_mem_pPowerSubgroup_CPlus, BernoulliRegular.CPlusExponentProduct_pow_of_exponents_eq_mul")
**Exponent criterion for saturation.** Assume that for every expression
$`x=(-1)^s\prod_a \varepsilon_a^{e_a}\in C^+_{\mathrm{sq}}` which is a $`p`-th power in
$`E^+`, all exponents satisfy $`e_a\equiv 0 \pmod p`. Then $`C^+_{\mathrm{sq}}` is
$`p`-saturated in $`E^+`.

{uses "def:p-saturated"}[] {uses "def:CPlus-squared"}[]
:::

:::proof "thm:CPlus-pSaturated-exponents"
Let $`x\in C^+_{\mathrm{sq}}` and suppose $`x=y^p` for some $`y\in E^+`. Choose an
exponent expression $`x=(-1)^s\prod_a \varepsilon_a^{e_a}`. By hypothesis,
$`e_a\equiv 0\pmod p` for every $`a`, so choose integers $`k_a` with $`e_a=pk_a`.
Since $`p` is odd, the sign term is already a $`p`-th power of itself:
$`((-1)^s)^p=(-1)^s`. Therefore
$`x = (-1)^s\prod_a \varepsilon_a^{pk_a} = \left((-1)^s\prod_a \varepsilon_a^{k_a}\right)^p`.
The element inside the parentheses belongs to $`C^+_{\mathrm{sq}}`, so $`x` is a
$`p`-th power inside $`C^+_{\mathrm{sq}}`. This is exactly $`p`-saturation.
:::

# From saturation to index non-divisibility

:::theorem "thm:not-dvd-index-of-pSaturated" (lean := "BernoulliRegular.not_dvd_index_of_pSaturated, BernoulliRegular.subgroup_not_dvd_index_of_pSaturated_top_of_pow_eq_one_mem, BernoulliRegular.CPlus_index_ne_zero")
**Saturation forbids $`p` in the index.** If $`C^+_{\mathrm{sq}}` is $`p`-saturated in
$`E^+`, then $`p\nmid [E^+:C^+_{\mathrm{sq}}]`.

{uses "def:p-saturated"}[] {uses "def:CPlus-squared"}[]
:::

:::proof "thm:not-dvd-index-of-pSaturated"
The proof is purely group-theoretic once one knows that $`C^+_{\mathrm{sq}}` has
finite index in $`E^+` and contains the torsion of $`E^+`. Suppose for contradiction
that $`p` divides $`[E^+:C^+_{\mathrm{sq}}]`. By Cauchy's theorem applied to the
finite quotient $`E^+/C^+_{\mathrm{sq}}`, there is a non-trivial quotient class of
order $`p`. Choose a representative $`g\in E^+`. The order condition says
$`g^p\in C^+_{\mathrm{sq}}`. Of course $`g^p` is a $`p`-th power in $`E^+`. By
$`p`-saturation, there is $`h\in C^+_{\mathrm{sq}}` with $`h^p=g^p`. Then
$`(gh^{-1})^p=1`. Thus $`gh^{-1}` is $`p`-torsion in $`E^+`. The only torsion units in
the real cyclotomic field are $`\pm1`, and both belong to $`C^+_{\mathrm{sq}}`. Hence
$`gh^{-1}\in C^+_{\mathrm{sq}}`, and since $`h\in C^+_{\mathrm{sq}}`, also
$`g\in C^+_{\mathrm{sq}}`. This means the quotient class of $`g` was trivial,
contradicting its order $`p`.
:::

# The Kummer logarithm determinant

The $`p`-adic part of the argument studies the logarithms of the real cyclotomic
units at the prime above $`p`. After passing to the completed local ring and reducing
suitable logarithmic coordinates modulo $`p`, one obtains a matrix over
$`\mathbb{F}_p`. Its columns are indexed by the generators
$`\varepsilon_2,\ldots,\varepsilon_{(p-1)/2}`, and its rows are indexed by the even
powers which occur in the Kummer range.

The determinant has two parts. One part is a finite-field Vandermonde determinant in
the Teichmuller nodes; this is nonzero because the nodes are distinct. The other part
is the product of Bernoulli factors. Consequently the determinant is nonzero exactly
when no Bernoulli numerator in Kummer's range is divisible by $`p`.

:::theorem "thm:kummer-log-det-bernoulli" (lean := "BernoulliRegular.CyclotomicUnits.kummerLogMatrix_det_ne_zero_iff_bernoulli_nonzero, BernoulliRegular.CyclotomicUnits.concreteKummerLogMatrix_eq_diagonal_mul_vandermonde, BernoulliRegular.CyclotomicUnits.concreteKummerLogMatrix_det_ne_zero_iff_forall_bernoulliFactor_ne_zero, BernoulliRegular.CyclotomicUnits.bernoulliFactor_ne_zero_iff_not_dvd_bernoulli_num, BernoulliRegular.CyclotomicUnits.vandermonde_teichmuller_even_sub_one_det_ne_zero")
**Kummer logarithm determinant criterion.** Assume $`p\ge 5`. The Kummer logarithm
matrix has nonzero determinant if and only if
$$`\forall j,\quad 1\le j,\ 2j\le p-3 \Longrightarrow p\nmid (B_{2j})_{\mathrm{num}}.`

{uses "def:CPlus-squared"}[] {uses "thm:bernoulli-padicInt-below"}[] {uses "cor:bernoulli-den-coprime"}[]
:::

:::proof "thm:kummer-log-det-bernoulli"
The determinant computation factors the matrix as
$`\operatorname{diag}(r_1,\ldots,r_g)\,V`, $`g=(p-3)/2`, where $`V` is the
finite-field Vandermonde matrix attached to the even Teichmuller nodes and $`r_j` is
the Bernoulli row factor attached to $`B_{2j}/(2j)`. The determinant is therefore
$`\det(V)\prod_j r_j`. The Vandermonde determinant is nonzero because the Teichmuller
nodes are pairwise distinct in $`\mathbb{F}_p`. Thus the determinant is nonzero
exactly when every $`r_j` is nonzero. For $`1\le j` and $`2j\le p-3`, the denominator
of $`B_{2j}` is prime to $`p` by the integrality results for Bernoulli numbers below
the boundary. Also $`2j<p`. Hence reducing $`B_{2j}/(2j)` modulo $`p` gives zero
exactly when the integer numerator of $`B_{2j}` is divisible by $`p`. This identifies
the non-vanishing of all row factors with the displayed Bernoulli non-divisibility
condition.
:::

:::theorem "thm:kummer-log-det-saturation" (lean := "BernoulliRegular.CyclotomicUnits.cyclotomicUnits_pSaturated_of_kummerLog_det_ne_zero, BernoulliRegular.CyclotomicUnits.completedLog_relation_of_CPlus_product_mem_powers, BernoulliRegular.CyclotomicUnits.concreteKummerLogMatrix_mulVec_exponents_eq_zero, BernoulliRegular.CyclotomicUnits.exponents_modP_eq_zero_of_kummerLogMatrix_relation, BernoulliRegular.CyclotomicUnits.CPlusGenerator_exponents_modP_zero_of_kummerLog_det_ne_zero")
**Determinant non-vanishing gives saturation.** Assume $`p\ge 5`. If the Kummer
logarithm determinant is nonzero, then $`C^+_{\mathrm{sq}}` is $`p`-saturated in
$`E^+`.

{uses "def:p-saturated"}[] {uses "def:CPlus-squared"}[] {uses "thm:CPlus-pSaturated-exponents"}[]
:::

:::proof "thm:kummer-log-det-saturation"
Suppose an element $`x=(-1)^s\prod_a \varepsilon_a^{e_a}` is a $`p`-th power in
$`E^+`. Taking completed $`p`-adic logarithms of the local image of this relation
gives an additive relation $`\sum_a e_a\,\log(\varepsilon_a) \in p\cdot L`, where
$`L` is the completed logarithm lattice. The sign term disappears from the
logarithmic coordinates, because $`p` is odd and the sign is torsion. Reducing the
coordinates of this relation modulo $`p` gives $`M\,(e_a\bmod p)_a=0` for the Kummer
logarithm matrix $`M`. If $`\det(M)\ne0`, then $`M` is invertible over
$`\mathbb{F}_p`, so every coordinate $`e_a\bmod p` is zero. The exponent criterion of
{bpref "thm:CPlus-pSaturated-exponents"}[] then proves $`p`-saturation.
:::

# Bernoulli non-divisibility and the plus index

The previous sections combine into the theorem used by the final proof.

:::theorem "thm:bernoulli-nonzero-index" (lean := "BernoulliRegular.not_dvd_cyclotomicUnitIndex_of_bernoulli_nonzero")
**Bernoulli non-divisibility implies index non-divisibility.** Assume $`p` is odd and
$$`\forall j,\quad 1\le j,\ 2j\le p-3 \Longrightarrow p\nmid (B_{2j})_{\mathrm{num}}.`
Then $`p\nmid [E^+:C^+_{\mathrm{sq}}]`.

{uses "thm:kummer-log-det-bernoulli"}[] {uses "thm:kummer-log-det-saturation"}[] {uses "thm:not-dvd-index-of-pSaturated"}[]
:::

:::proof "thm:bernoulli-nonzero-index"
If $`p=3`, then the generator range is empty. The real subfield of
$`\mathbb{Q}(\zeta_3)` is $`\mathbb{Q}`, so its unit group is generated by $`-1`.
Hence $`C^+_{\mathrm{sq}}=E^+` and the index is $`1`, which is not divisible by $`p`.
Now assume $`p\ge5`. The Bernoulli non-divisibility hypothesis makes the Kummer
logarithm determinant nonzero by {bpref "thm:kummer-log-det-bernoulli"}[]. The
determinant non-vanishing theorem {bpref "thm:kummer-log-det-saturation"}[] gives
$`p`-saturation of $`C^+_{\mathrm{sq}}` in $`E^+`. Finally
{bpref "thm:not-dvd-index-of-pSaturated"}[] converts this saturation into
$`p\nmid [E^+:C^+_{\mathrm{sq}}]`.
:::

# The needed Sinnott index formula

The index theorem used in the final argument is the odd-primary consequence of
Sinnott's formula for real cyclotomic units. The family used in the regulator
computation is the same squared family as above, but with the torsion subgroup
adjoined explicitly.

:::definition "def:sinnott-index-subgroup" (lean := "BernoulliRegular.cyclotomicUnitIndexSubgroup")
**Sinnott's full-rank subgroup.** For $`p\ge3`, let
$$`C^+_{\mathrm{Sin}} = \left\langle \varepsilon_2,\varepsilon_3,\ldots,\varepsilon_{(p-1)/2} \right\rangle \vee E^+_{\mathrm{tors}} \le E^+ .`
Equivalently, $`C^+_{\mathrm{Sin}}` is generated by the full-rank real
cyclotomic-unit family used in the regulator determinant, together with all torsion
units of $`E^+`.

{uses "def:real-cyclotomic-unit"}[] {uses "def:CPlus-squared"}[]
:::

:::lemma_ "lem:sinnott-subgroup-eq-CPlus" (lean := "BernoulliRegular.cyclotomicUnitIndexSubgroup_eq_CPlus, BernoulliRegular.CPlusGenerator_eq_cyclotomicUnitFamilyKplus, BernoulliRegular.range_cyclotomicUnitFamilyKplusFinRank_eq, BernoulliRegular.torsionKplus_le_CPlus, BernoulliRegular.CPlus_le_cyclotomicUnitIndexSubgroup, BernoulliRegular.cyclotomicUnitIndexSubgroup_le_CPlus")
**Agreement with the squared subgroup.** For $`p\ge3`,
$`C^+_{\mathrm{Sin}}=C^+_{\mathrm{sq}}`.

{uses "def:sinnott-index-subgroup"}[] {uses "def:CPlus-squared"}[]
:::

:::proof "lem:sinnott-subgroup-eq-CPlus"
The full-rank family in $`C^+_{\mathrm{Sin}}` is indexed by
$`\operatorname{Fin}((p-3)/2)`, and the element with index $`i` is exactly
$`\varepsilon_{i+2}`. Thus its range is the same generator range used for
$`C^+_{\mathrm{sq}}`. It remains to compare torsion. The torsion of the real
cyclotomic unit group is $`\{\pm1\}`. The unit $`1` belongs to every subgroup, and
$`-1` is one of the generators of $`C^+_{\mathrm{sq}}`. Hence adjoining torsion to the
full-rank family adds nothing beyond the subgroup already generated by
$`-1,\varepsilon_2,\ldots,\varepsilon_{(p-1)/2}`.
:::

:::theorem "thm:sinnott-index-pprimary" (lean := "BernoulliRegular.cyclotomicUnitIndex_primeConductor_pPrimary_of_sinnottIndexFormula, BernoulliRegular.cyclotomicUnitIndex_primeConductor_pPrimary_of_kummerDirichletDeterminant, BernoulliRegular.FLT37.Sinnott.sinnottRegulatorIdentity_iff_kummerDirichletDeterminant, BernoulliRegular.FLT37.Sinnott.sinnottIndexFormula_of_regulatorIdentity, BernoulliRegular.FLT37.Sinnott.index_eq_twoPow_mul_hPlus_of_sinnottIndexFormula, BernoulliRegular.prime_dvd_two_pow_mul_iff_dvd")
**Sinnott formula, odd-primary consequence.** Assume the Kummer-Dirichlet determinant
identity for the real cyclotomic-unit logarithm matrix. Then
$$`p\mid [E^+:C^+_{\mathrm{Sin}}] \quad\Longleftrightarrow\quad p\mid h^+ .`

{uses "def:sinnott-index-subgroup"}[]
:::

:::proof "thm:sinnott-index-pprimary"
Write $`g=(p-3)/2` and let $`R^+ = \operatorname{Reg}(E^+)` be the regulator of the
maximal real subfield. The determinant identity is the regulator identity
$`\operatorname{Reg}(\varepsilon_2,\ldots,\varepsilon_{(p-1)/2}) = 2^g h^+ R^+`. The
passage from regulators to indices is the standard covolume comparison for the
logarithmic unit lattice. Modulo torsion, the units $`E^+` form a lattice of rank
$`g`, and the family $`\varepsilon_2,\ldots,\varepsilon_{(p-1)/2}` spans a full-rank
sublattice. The covolume of the latter is its index in the former times the covolume
of the former:
$`\frac{\operatorname{Reg}(\varepsilon_2,\ldots,\varepsilon_{(p-1)/2})}{R^+} = [E^+:C^+_{\mathrm{Sin}}]`.
Since $`R^+>0`, the displayed regulator identity therefore gives Sinnott's index
formula in this normalization: $`[E^+:C^+_{\mathrm{Sin}}]=2^g h^+`. Finally, $`p` is
odd, so $`p\nmid 2^g`. Euclid's lemma gives
$`p\mid 2^g h^+ \Longleftrightarrow p\mid h^+`, and combining this with the index
formula proves the stated equivalence.
:::

:::theorem "thm:deleted-fourier-kummer-dirichlet" (lean := "BernoulliRegular.kummerDirichletDeterminant_of_deletedFourier")
**Deleted-Fourier determinant identity.** Assume $`p\ge5`. The logarithm matrix of
the full-rank real cyclotomic-unit family satisfies the Kummer-Dirichlet determinant
identity.

{uses "def:sinnott-index-subgroup"}[] {uses "def:dirichlet-character"}[] {uses "def:real-cyclotomic-unit"}[]
:::

:::proof "thm:deleted-fourier-kummer-dirichlet"
The rows of the matrix are indexed by the non-trivial even characters modulo $`p`,
and the columns by $`\varepsilon_2,\ldots,\varepsilon_{(p-1)/2}`. After the standard
Fourier change of basis, the determinant separates into a deleted Fourier determinant
and the product of the even character factors. The deleted Fourier determinant is
nonzero: it is the determinant of the character table with the trivial row and the
redundant column removed, and orthogonality of characters gives its inverse after
multiplying by a power of $`p`. The remaining product is the even part of the
cyclotomic class-number formula. With the present squared-unit normalization, the
regulator identity therefore has the form
$`\operatorname{Reg}(\varepsilon_2,\ldots,\varepsilon_{(p-1)/2}) = 2^g h^+ R^+`,
$`g=(p-3)/2`. This is precisely the Kummer-Dirichlet determinant identity used in the
index calculation.
:::

:::corollary "cor:sinnott-index-prime-conductor" (lean := "BernoulliRegular.kummerDirichletDeterminant_of_deletedFourier, BernoulliRegular.cyclotomicUnitIndex_primeConductor_pPrimary_aux, BernoulliRegular.cyclotomicUnitIndex_primeConductor_pPrimary_of_kummerDirichletDeterminant")
**Sinnott formula for prime conductor.** If $`p\ge5`, then
$$`p\mid [E^+:C^+_{\mathrm{Sin}}] \quad\Longleftrightarrow\quad p\mid h^+ .`

{uses "thm:sinnott-index-pprimary"}[] {uses "thm:deleted-fourier-kummer-dirichlet"}[]
:::

:::proof "cor:sinnott-index-prime-conductor"
For $`p\ge5`, the deleted-Fourier determinant computation evaluates the logarithm
determinant of the real cyclotomic units. The matrix rows are the even non-trivial
characters, the columns are the units $`\varepsilon_2,\ldots,\varepsilon_{(p-1)/2}`,
and the determinant splits into a nonzero Fourier determinant times the product of
the character factors. The class-number formula for the real subfield identifies this
product with $`h^+R^+`, with the extra factor $`2^g` coming from using the squared
cyclotomic-unit family. Thus the Kummer-Dirichlet determinant identity holds, and
{bpref "thm:sinnott-index-pprimary"}[] applies.
:::

:::theorem "thm:cyclotomic-unit-index-hplus" (lean := "BernoulliRegular.cyclotomicUnitIndex_primeConductor_pPrimary, BernoulliRegular.cyclotomicUnitIndex_primeConductor_pPrimary_of_eq_three, BernoulliRegular.cyclotomicUnitIndex_primeConductor_pPrimary_of_five_le")
**Prime-conductor cyclotomic-unit index theorem.** For odd $`p`,
$$`p \mid [E^+:C^+_{\mathrm{norm}}] \quad\Longleftrightarrow\quad p \mid h^+.`

{uses "cor:sinnott-index-prime-conductor"}[] {uses "lem:sinnott-subgroup-eq-CPlus"}[] {uses "lem:CPlus-index-normalized-index"}[]
:::

:::proof "thm:cyclotomic-unit-index-hplus"
There are two cases. If $`p=3`, then $`K^+=\mathbb{Q}`. The plus class number is
therefore $`h^+=1`. The real unit rank is zero, so the normalised cyclotomic-unit
subgroup is the whole unit group. Hence both sides are the assertion that $`3`
divides $`1`, and both are false. Now assume $`p\ne3`. Since $`p` is an odd prime,
this gives $`p\ge5`. By {bpref "cor:sinnott-index-prime-conductor"}[],
$`p\mid [E^+:C^+_{\mathrm{Sin}}] \Longleftrightarrow p\mid h^+`. The subgroup
identification {bpref "lem:sinnott-subgroup-eq-CPlus"}[] replaces
$`C^+_{\mathrm{Sin}}` by $`C^+_{\mathrm{sq}}`. Finally, the odd-primary comparison
{bpref "lem:CPlus-index-normalized-index"}[] replaces $`C^+_{\mathrm{sq}}` by
$`C^+_{\mathrm{norm}}`, because the quotient between the two generated subgroups has
exponent dividing a power of $`2`. Since $`p` is odd, this quotient does not affect
$`p`-divisibility of the ambient index. The displayed equivalence follows.
:::
