import Verso
import VersoManual
import VersoBlueprint
import BernoulliRegular
import BernoulliRegularBlueprint.Refs
import BernoulliRegularBlueprint.TexPrelude

open Verso.Genre
open Verso.Genre.Manual
open Informal


#doc (Manual) "Gauss sums and Stickelberger" =>

This chapter assembles the algebraic ingredients that give the Herbrand
implication: a non-trivial $`\chi`-eigenspace in the $`p`-part of the class group
forces $`p \mid B_{1,\chi}`. The analytic chapters below use the same Gauss-sum
normalization in the relative class-number formula.

# Gauss sums

:::definition "def:gauss-sum" (lean := "gaussSum")
For a Dirichlet character $`\chi` modulo $`p` valued in $`\mathbb{C}`, the *Gauss
sum* is
$$`\tau(\chi) \;=\; \sum_{a \in \mathbb{Z}/p\mathbb{Z}} \chi(a)\,e^{2\pi i a / p} \;\in\; \mathbb{C},`
where the additive character is $`a \mapsto e^{2\pi i a/p}`.

{uses "def:dirichlet-character"}[]
:::

:::proposition "prop:gauss-norm" (lean := "BernoulliRegular.gaussSum_mul_gaussSum_inv_stdAddChar")
For a non-trivial Dirichlet character $`\chi` modulo $`p`,
$$`\tau(\chi)\,\tau(\bar\chi) \;=\; \chi(-1)\,p, \qquad |\tau(\chi)|^2 \;=\; p.`

{uses "def:gauss-sum"}[]
:::

:::proof "prop:gauss-norm"
Expand both Gauss sums and multiply:
$`\tau(\chi)\tau(\bar\chi) = \sum_{a,b}\chi(a)\bar\chi(b)e^{2\pi i(a+b)/p}`. After the
change of variables $`a=tb` on the terms with $`b\ne0`, the inner sum over $`b`
vanishes unless $`t=-1`. The surviving contribution is $`\chi(-1)p`. Moreover
$`\overline{\tau(\chi)}=\chi(-1)\tau(\bar\chi)`, and therefore
$$`|\tau(\chi)|^2 = \tau(\chi)\overline{\tau(\chi)} = \chi(-1)\tau(\chi)\tau(\bar\chi) = p.`
:::

The Gauss-sum sign (whether $`\tau(\chi) = +\sqrt{p}` or $`-\sqrt{p}` for a real
quadratic character) is fixed by the classical quadratic Gauss-sum evaluation and is
used in the $`L(1,\chi)` formula of the next chapter.

# The Stickelberger element

:::definition "def:stickelberger" (lean := "BernoulliRegular.stickelbergerElement")
The *Stickelberger element* is
$$`\theta \;=\; \sum_{a \in (\mathbb{Z}/p\mathbb{Z})^\times} \Bigl\langle \frac{a}{p} \Bigr\rangle\,\sigma_a^{-1} \;\in\; \mathbb{Q}\bigl[(\mathbb{Z}/p\mathbb{Z})^\times\bigr],`
where $`\langle x \rangle = x-\lfloor x\rfloor` denotes the fractional part, and
$`\sigma_a` is the automorphism sending $`\zeta_p\mapsto\zeta_p^a`. Multiplying by
the appropriate denominator gives the usual integral Stickelberger ideal.

{uses "def:dirichlet-character"}[]
:::

:::theorem "thm:stickelberger" (lean := "BernoulliRegular.stickelbergerCharacterCoefficientGroupRingTarget_annihilates_primeClass")
**Stickelberger's theorem.** The integral Stickelberger ideal
$`I_\theta \subset \mathbb{Z}[(\mathbb{Z}/p\mathbb{Z})^\times]` annihilates the class
group of $`\mathbb{Q}(\zeta_p)`: for any prime $`\mathfrak l \nmid p` and any
$`\beta \in I_\theta`, the ideal $`\mathfrak l^\beta` is principal.

{uses "def:stickelberger"}[] {uses "def:gauss-sum"}[]
:::

:::proof "thm:stickelberger"
One first proves the ideal factorisation of Gauss sums: for a non-trivial character
$`\chi`, the principal ideal generated by $`\tau(\chi)` has factorisation prescribed
by the Stickelberger exponent. Since a principal ideal represents the trivial class,
the corresponding group-ring exponent annihilates the class of every prime above a
rational prime $`\ell\ne p`. Such prime classes generate the ideal class group, so
every element of the integral Stickelberger ideal annihilates the full class group.
:::

# Herbrand's theorem

Herbrand's theorem converts Stickelberger annihilation into a divisibility statement
for generalised Bernoulli numbers.

:::theorem "thm:herbrand" (lean := "BernoulliRegular.generalizedBernoulliPDivisible_of_nontrivial_oddComponent")
**Herbrand bridge.** Let $`\chi` be an odd Dirichlet character modulo $`p`. If the
$`\chi`-eigenspace $`\mathrm{Cl}(\mathcal{O}_{\mathbb{Q}(\zeta_p)})[p]^\chi` of the
$`p`-part of the class group is non-trivial, then $`p \mid B_{1,\chi}`.

{uses "thm:stickelberger"}[] {uses "def:gen-bernoulli"}[] {uses "def:even-odd"}[]
:::

:::proof "thm:herbrand"
Project the Stickelberger annihilation relation to the $`\chi`-eigenspace. On that
eigenspace the Stickelberger element acts by the scalar $`B_{1,\chi}`, up to the
standard nonzero normalising factor. If the $`\chi`-component of the $`p`-class group
is non-trivial, a scalar that annihilates it must be divisible by $`p`; otherwise it
would be a unit on the $`\mathbb{F}_p`-component and could not kill a nonzero element.
Hence $`p\mid B_{1,\chi}`.
:::
