/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import «Adic spaces».WP.Algebra

/-!
# `𝒜` is not noetherian ([WP] prop:parity-nonnoetherian)

For each `m` the paper builds a bounded homomorphism `ψ_m : 𝒜 → k⟨T⟩` killing
`W, Y_j, Z_j (j ≠ m+1)` and sending `Z_{m+1} ↦ T`, and concludes that the ideals
`I_m = (Z_1,…,Z_m)` form a strictly increasing chain.

Source ([WP] lines 817–834): "There is a compatible family of norm-nonincreasing maps
on the finite stages, and hence a bounded homomorphism `ψ_m : 𝒜 → k⟨T⟩`, which sends
`W` and every `Y_j` to zero, sends `Z_{m+1}` to `T`, and sends every other `Z_j` to
zero. … The map `ψ_m` kills `I_m` but not `Z_{m+1}`.  Therefore `I_1 ⊊ I_2 ⊊ ⋯`, so
`𝒜` is not noetherian."

Route note (support model, documented divergence): `ψ_m` is defined directly on the
support algebra — the monomial `W^a U^ν` maps to `T^q` when `(a,ν) = (0, 2q·δ_{m+1})`
and to `0` otherwise; multiplicativity holds because the non-preserved monomials form a
monoid ideal inside `S` (an odd `U_{m+1}`-exponent forces `a ≥ w (m+1) ≥ 1`, whence the
weight hypothesis).  The presentation-preservation step of the paper disappears.
-/

@[expose] public section

namespace WeightedParity

variable (K : Type*) [NontriviallyNormedField K] [IsUltrametricDist K] [CompleteSpace K]
variable (w : ℕ → ℕ)

/-- The coefficientwise character `ψ_m : 𝒜 → k⟨T⟩` ([WP] prop:parity-nonnoetherian):
pure even powers `U_{m+1}^{2q} ↦ T^q`, all other allowed monomials `↦ 0`.  Requires
positive weights (`hw`) so that odd `U_{m+1}`-exponents force `W`-content. -/
noncomputable def psiHom (m : ℕ) (hw : ∀ n, 1 ≤ n → 1 ≤ w n) :
    WPA K w →+* PowerSeries.Restricted K (1 : ℝ) := by sorry

theorem psiHom_Za_succ_ne_zero (m : ℕ) (hw : ∀ n, 1 ≤ n → 1 ≤ w n) :
    psiHom K w m hw (Za K w (m + 1)) ≠ 0 := by sorry

@[simp] theorem psiHom_Za_of_le (m : ℕ) (hw : ∀ n, 1 ≤ n → 1 ≤ w n) {j : ℕ}
    (hj : j ≤ m) : psiHom K w m hw (Za K w j) = 0 := by sorry

/-- `Z_{m+1}` is not in the ideal generated by `Z_1, …, Z_m`
([WP]: "The map `ψ_m` kills `I_m` but not `Z_{m+1}`"). -/
theorem Za_succ_notMem_span (m : ℕ) (hw : ∀ n, 1 ≤ n → 1 ≤ w n) :
    Za K w (m + 1) ∉ Ideal.span ((fun j => Za K w j) '' {j | 1 ≤ j ∧ j ≤ m}) := by sorry

/-- **`𝒜` is not noetherian** ([WP] prop:parity-nonnoetherian / thm 6.2(1)). -/
theorem not_isNoetherianRing_WPA (hw : ∀ n, 1 ≤ n → 1 ≤ w n) :
    ¬ IsNoetherianRing (WPA K w) := by sorry

end WeightedParity
